common/resource/resourceImpl.go, service/matching/handlerGRPC.go, service/matching/service.go
Proxy handler for smooth gRPC migration.
=> Add handlerGRPC for matching service

common/adapter/history_service.go, common/resource/resourceImpl.go, proto/historyservice/request_response.proto, proto/historyservice/service.proto, service/history/handlerGRPC.go, service/history/service.go
Proxy handler for smooth gRPC migration.
=> Add handlerGRPC for history service 

idl/github.com/temporalio/temporal/sqlblobs.thrift
Remove TimerTaskInfo, TransferTaskInfo, ReplicationTaskInfo and ShardInfo
=> Remove already converted Thrift definitions

cmd/server/temporal/server.go
Avoid mysterious errors when providing an empty host string in the PublicClient hostport configuration.
=> Validate PublicClient Hostport parsable

service/frontend/adminHandler.go, service/frontend/errors.go, service/history/handler.go, service/matching/handler.go
Use predefined variables for simiar errors.
=> Extract errors to variables

docker/buildkite/docker-compose-local.yml, docker/config_template.yaml, docker/docker-compose-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
- Docker compose fixes to use grpc ports
- Docker compose fixes to use Temporal images from dockerhub
=> fix docker-compose to work with temporal docker images

README.md, docs/non-deterministic-error.md, tools/cli/README.md
Update all references to Temporal.
Use links to Temporal resources
- docs
- buildkite
- slack
=> Update readme to reference Temporal

common/persistence/dataInterfaces.go, common/persistence/persistence-tests/executionManagerTest.go, common/persistence/persistence-tests/persistenceTestBase.go, common/persistence/serializer.go, common/persistence/serializer_test.go, service/history/historyBuilder.go, service/history/historyEngine.go, service/history/mutableStateBuilder.go, service/history/transferQueueActiveProcessor.go
- Migrate `shared.ResetPoint` thrift usage to `commonproto.ResetPoint`
- Implement ResetPoint PayloadSerializer proto logic
=> ResetPoint Proto Conversion

common/persistence/dataInterfaces.go
=> Remove unused TimerTaskInfo POGO

common/service/config/config.go, common/service/config/rpc.go, config/development.yaml, config/development_active.yaml, config/development_es.yaml, config/development_mysql.yaml, config/development_other.yaml, config/development_postgres.yaml, config/development_prometheus.yaml, config/development_standby.yaml, docker/config_template.yaml, host/onebox.go
RingpopPort has been renamed to MembershipPort
**Why?**
Membership layer may not stay ringpop only in future.
Rename only.
=> Rename RingpopPort to MembershipPort

service/matching/matcher_test.go
Changed how mock call result condition is stored for TestQueryRemoteSyncMatch to prevent data race
**Why?**
Theres a data race
The test doesnt break with -race anymore
Test code, no production deployment
=> Solve race in TestQueryRemoteSyncMatch

docker/config_template.yaml
config_template.yaml updated to match current config schema.
**Why?**
Temporal docker image is broken now.
Build docker image locally and started it.
None.
=> Update config_template.yaml with latest config changes

docker/README.md, docker/docker-compose-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
Updating docker-compose files (and the README file) to reference correct images and image tags.
Removed web component, until it is ready to be shipped.
docker-compose should be using correct docker images, and there is no need to start web component, which is a work in progress.
I executed every docker-compose*.yaml file by running  `docker-compose -f <file name> up` and made sure the containers started without errors.
I think these files are used for local testing and buildkite testing, so our ability to test might be impacted.
=> updating various docker-compose files under docker/

go.sum
Add missing dependencies to go.sum file
**Why?**
This is to fix a build break
Able to successfully build locally
No risk.
=> Update go.sum file to add missing dependencies

docker/docker-compose-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
Update docker-compose to use v0.20.0
**Why?**
Cutting v0.20.0 alpha release
Run image locally
No risk
=> Update docker-compose to use v0.20.0

docker/docker-compose-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
Added Temporal-Web to docker
**Why?**
For easy installation of Temporal-Web 
[WIP] Ran locally
=> Add Temporal-Web to docker

common/archiver/gcloud/visibilityArchiver_test.go, common/checksum/crc.go, common/checksum/defs.go, common/persistence/persistence-tests/executionManagerTest.go, common/persistence/persistence-tests/executionManagerTestForEventsV2.go, proto/archiver/archiver.proto, proto/historyservice/request_response.proto, proto/persistenceblobs/persistenceblobs.proto, proto/token/token.proto, service/history/mutableStateBuilder_test.go
All fields in proto files were converted to camelCase.
**Why?**
Most of the fields are already in camelCase.
Code is not affected.
No risks.
=> Convert all proto fields to camelCase

CONTRIBUTING.md, PROPOSALS.md, service/worker/README.md, tools/cassandra/README.md, tools/cli/README.md, tools/sql/README.md
MD files were changed to reflect actual tools state.
**Why?**
To keep docs in sync.
Read all of it.
No risks.
=> Fix MD files

service/history/historyEngine.go
The consistent query is not going to fail with an error it it happened before the first decision.
**Why?**
This error doesn't make sense for consistent query and was left in the code by mistake.
Tested through Java client.
Consistent queries get broken.
=> Don't fail with ErrQueryWorkflowBeforeFirstDecision for consistent query

common/persistence/persistence-tests/executionManagerTestForEventsV2.go, common/persistence/sql/sqlplugin/interfaces.go, common/persistence/sql/sqlplugin/mysql/execution_maps.go, common/persistence/sql/sqlplugin/postgres/execution_maps.go, common/persistence/sql/workflowStateMaps.go, schema/mysql/v57/temporal/schema.sql, schema/mysql/v57/temporal/versioned/v0.1/base.sql, schema/postgres/temporal/schema.sql, schema/postgres/temporal/versioned/v0.1/base.sql
Two heatbeat related fields were removed from ActivityInfoRow.
**Why?**
`Payload` migration #324 requires these fields to be part of proto and they are already there.
Run tests.
I see no risks.
=> Remove heartbeat fields from ActivityInfoRow

go.mod, go.sum, host/activity_test.go, host/continueasnew_test.go, host/integration_test.go, host/signalworkflow_test.go, service/history/historyBuilder_test.go, service/matching/matchingEngine_test.go
`Headers` are using `Payload` instead of `bytes` now.
**Why?**
This is last step to implement #107.
All tests.
No risks.
=> Convert Header message to use Payload

docs/non-deterministic-error.md, tools/cli/README.md
Updated old links to docs to the new ones
**Why?**
so i can find relevant docs when following links from github instead of encountering 404
opened links
no risks
=> Update docs links

config/dynamicconfig/development_es.yaml, host/testdata/es_index_template.json, schema/elasticsearch/visibility/index_template.json, tools/cli/admin.go, tools/cli/workflowBatchCommands.go
Rename few leftover ID to Id.
**Why?**
For consistency.
Tests.
No risks.
=> Rename few leftover ID to Id

cmd/server/temporal/server.go, cmd/server/temporal/temporal.go, common/service/config/config.go, common/service/config/ringpop/ringpop.go, common/service/config/ringpop/ringpop_test.go, config/development.yaml, config/development_active.yaml, config/development_es.yaml, config/development_mysql.yaml, config/development_other.yaml, config/development_postgres.yaml, config/development_prometheus.yaml, config/development_standby.yaml, docker/config_template.yaml
Changed header names in yaml config files from:
- Ringpop to Membership
- Server to Global
There are two additional changes coming after this PR to complete config refactoring:
- Services -> Role
- Moving Metrics to Global scope
**Why?**
More appropriate/generic naming
Relying on Buildkite
Service fails to start because of missing config
=> Rename Config: Ringpop->Membership, Server->Global

common/rpc/rpc.go, common/service/config/config.go
Adding comments to configuration. Adding an additional nil check for server options.
**Why?**
Additional iteration of TLS.
Server start locally, buildkite
None
=> Add comments to config, additional nil check

tools/cli/util.go, tools/cli/workflowCommands.go
`input` flag supported only parameters of type `string`. Now it supports any JSON.
**Why?**
CLI wasn't properly updated after `[]byte` to `Payloads` migration.
Run tests and command manually.
Some CLI commands might be broken.
=> Fix CLI input flag

common/headers/versionChecker.go, tools/cli/app.go
GoSDK and CLI version were bumped up to `0.23.0`. 
**Why?**
This will accept request from new SDK.
Run all tests.
No risks.
=> Bump SDK version

host/onebox.go, host/testcluster.go
Rename Cadence (test cluster name) to Temporal.
**Why?**
Because we are Temporal, not Cadence.
None. This is just internal names change.
No risks.
=> Rename Cadence (test cluster name) to Temporal

go.mod, go.sum
`go.sum` is updated to the latest state with `go mod tidy` command.
**Why?**
CI/CD fails with outdated `go.sum`.
No tests.
No risks.
=> Fix go.sum

tools/cli/admin.go, tools/cli/adminCommands.go
Created an admin CLI command that allows to list ringpop members. Optionally allows to filter based on role
**Why?**
Allows to discover and get information on ringpop members
Ran with and without options `tctl admin membership list-gossip --role history`
Minimal risk. The code adds logic, doesn't change the existing
=> Create CLI command to list Ringpop Members

Makefile, service/matching/matcher.go
Cancel it called before returning from the func.
**Why?**
To prevent momory leak.
No tests.
No risks.
=> Call cancel on context to prevent memory leak

tools/cli/admin.go, tools/cli/adminTaskListCommands.go, tools/cli/flags.go
admin CLI command that allows to list Tasks from a TaskList now has an optional Workflow Id and Run Id filter. 
The command itself now utilizes paginate util to switch between table and json views 
**Why?**
Allows to narrow down to specific workflow runs when discovering tasks of a tasklist
ran tests and command
low risk
=> Add execution filter to tasklist tasks CLI command

tools/cli/adminCommands.go, tools/cli/workflowCommands.go
Executable permission was removed from JSON files.
**Why?**
JSON files are not executable.
Run CLI command manually.
Zero risks.
=> Remove executable permission from JSON files generated from CLI

Makefile
Add default `install` target.
**Why?**
Default `install` target was removed recently but it is still needed.
Run.
No risks.
=> Revert install target

common/log/tag/tags.go, host/sizelimit_test.go, service/history/decisionChecker.go, service/history/decisionHandler.go, service/history/decisionTaskHandler.go
`ServerFailure` was created as retryable where it shouldn't. Also improve logging to log string representation of enums not int.
**Why?**
Fix bugs, improve logging.
Tests.
No risks.
=> Fix ServerFailure retryable and improve loggging

docs/diagrams/matchin-nonsync.iml, docs/diagrams/matchin-sync.iml
Added sequence diagrams in [PlantUML](https://plantuml.com/) format that demonstrates how matching service works.
**Why?**
These diagrams were used to answer a [question](https://community.temporal.io/t/async-and-sync-matching-flow/135/2) at the community forum.
None.
=> Sequence diagrams of the matching process

config/development.yaml, config/development_active.yaml, config/development_es.yaml, config/development_mysql.yaml, config/development_other.yaml, config/development_postgres.yaml, config/development_prometheus.yaml, config/development_standby.yaml
`status` was renamed to `state` in config files.
**Why?**
To match with server renames.
Run server.
No risks.
=> Rename status to state in configs

docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
References a new docker image for web v0.28.1
**Why?**
The new image fixes few issues on web ui
1. `docker-compose up`
2. web ui tests + manual
no risks
=> Upgrade Web UI to v0.28.1

common/service/config/config.go
These fields are not referenced anywhere. Removing.
=> Remove unused yaml fields for logging

service/history/historyEngine.go
Unused errors were removed.
**Why?**
Code cleanup and close #300.
No test needed.
No risks.
=> Remove unused errors

common/rpc/rpc_common_test.go, common/rpc/rpc_localstore_tls_test.go, common/service/config/config.go, common/service/config/ringpop/ringpop.go, common/service/config/ringpop/ringpop_test.go, docker/config_template.yaml, service/history/shardContext.go, tools/cli/defs.go
Unused configuration value, removing for clearness to consumers. Also formatting.
=> Remove Membership.Name config; Hardcode ringpop app name

config/development_other.yaml
correct publicClient port
**Why?**
publicClient port should be frontend rpc Port
build cluster locally
Just example config, no risks
=> Fix publicClient

docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
Reference Web v0.29.1 as default for docker images
**Why?**
Web v0.29.1 has a number of improvements and fixes
docker compose
No risks
=> Update Web reference to v0.29.1

config/development_active.yaml, config/development_other.yaml
local NDC config
**Why?**
config is inconsistent with code
build NDC services locally
local config, no risks
=> Fix wrong field 

tools/cli/adminCommands.go, tools/cli/flags.go, tools/cli/persistenceUtil.go
Added support for MySQL in admin CLI
**Why?**
Better visibility into temporal data stored in MySQL
Ran list namespace command
Some admin list commands may still not work with MySQL - workaround PageSize might need to be explicitly set as part of the request
=> Add support for MySQL in admin cli

common/auth/tls.go, common/cassandra/cassandraCluster.go, common/cassandra/cassandraCluster_test.go, common/persistence/cassandra/cassandraClusterMetadata.go, common/persistence/cassandra/cassandraHistoryPersistence.go, common/persistence/cassandra/cassandraMetadataPersistenceV2.go, common/persistence/cassandra/cassandraPersistence.go, common/persistence/cassandra/cassandraPersistenceTest.go, common/persistence/cassandra/cassandraQueue.go, common/persistence/cassandra/cassandraVisibilityPersistence.go, common/persistence/cassandra/factory.go, tools/cassandra/cqlclient.go
to make deploying with private CA easier
=> Support shipping base64 encoded CA in config

docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
docker version of web wasn't updated during last release process. This PR to fix it.
=> Upgrade web to 0.30.0 in docker-compose files

tools/cli/workflowCommands.go
Changed the formatting of tctl command to output workflow history into a file 
**Why?**
Helps reading the output
Ran the command and tests. Sample output:
No risks
=> Prettify tctl workflow history export to file

client/admin/client.go, client/clientBean.go, client/clientfactory.go, common/metrics/defs.go, common/persistence/persistence-tests/executionManagerTest.go, common/persistence/sql/sqlplugin/postgres/execution_maps.go, common/service/dynamicconfig/constants.go, common/util.go, common/util_test.go, host/activity_test.go, service/history/historyEngine.go, service/history/mutableStateBuilder.go, service/history/queueTask.go, service/history/replicationTaskExecutor.go, service/history/replicationTaskProcessor.go, service/history/service.go, service/history/shardContext.go, service/history/taskProcessor.go, service/history/timerQueueProcessor.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueProcessor.go, service/history/transferQueueTaskExecutorBase.go, service/worker/replicator/replicator.go, service/worker/service.go, tools/cli/adminKafkaCommands.go
Tune dynamic config knobs
https://github.com/uber/cadence/pull/3311
https://github.com/uber/cadence/pull/3411
https://github.com/uber/cadence/pull/3473
https://github.com/uber/cadence/pull/3437
https://github.com/uber/cadence/pull/3489
https://github.com/uber/cadence/pull/3373
https://github.com/uber/cadence/pull/3227
https://github.com/uber/cadence/pull/3494
https://github.com/uber/cadence/pull/3498
https://github.com/uber/cadence/pull/3452
https://github.com/uber/cadence/pull/3459
=> Cherry pick some commits from Cadence

service/history/historyEngine.go, service/history/replicationDLQHandler.go, service/history/replicationDLQHandler_mock.go, service/history/replicationDLQHandler_test.go, service/history/replicationTaskExecutor.go, service/history/replicationTaskExecutor_mock.go, service/history/replicationTaskExecutor_test.go, service/history/replicationTaskProcessor.go
Merge https://github.com/uber/cadence/pull/3365 from Cadence.
=> Fix history resender source cluster (#3365)

client/history/client.go, common/backoff/retrypolicy.go, common/service/dynamicconfig/constants.go, common/util.go, host/onebox.go, service/history/historyEngine.go, service/history/replicationTaskFetcher.go, service/history/replicationTaskFetcher_mock.go, service/history/replicationTaskProcessor.go, service/history/replicationTaskProcessor_mock.go, service/history/replicationTaskProcessor_test.go, service/history/service.go, service/worker/replicator/processor.go, service/worker/replicator/replicator.go
https://github.com/uber/cadence/pull/3376
https://github.com/uber/cadence/pull/3458
=> Merge critical fixes from Cadence

common/persistence/sql/sqlplugin/mysql/task.go, common/persistence/sql/sqlplugin/postgresql/task.go, common/persistence/sql/sqlplugin/tests/matching_task_queue_test.go, common/persistence/sql/sqlplugin/tests/matching_task_test.go, common/persistence/sql/sqlplugin/tests/mysql_test.go, common/persistence/sql/sqlplugin/tests/postgresql_test.go
* Add matching task queue tests
Add SQL persistence specific tests.
**Why?**
Run tests.
=> Add SQL persistence specific tests

tools/cli/util.go
Events with a field of type common.Payloads now render content in human readable form
**Why?**
Adds visibility into payloads content
Tests + ran command. See details key below:
no risks
=> Make Events with Payloads field readable in cli

tools/cli/util.go
UpsertWorkflowSearchAttributes event now renders search attributes in human readable form
**Why?**
Adds visibility into UpsertWorkflowSearchAttributes data
Tests + ran command
no risks
=> Make Upsert Search Attributes event readable in cli

Makefile, common/persistence/sql/sqlMetadataManagerV2.go, common/persistence/sql/sqlplugin/common.go, common/persistence/sql/sqlplugin/interfaces.go, common/persistence/sql/sqlplugin/mysql/namespace.go, common/persistence/sql/sqlplugin/postgresql/namespace.go, common/persistence/sql/sqlplugin/tests/matching_task_queue_test.go, common/persistence/sql/sqlplugin/tests/mysql_test.go, common/persistence/sql/sqlplugin/tests/namespace_test.go, common/persistence/sql/sqlplugin/tests/postgresql_test.go, common/persistence/workflowExecutionInfo.go, service/history/mutableStateBuilder_test.go, service/history/nDCWorkflow_test.go, service/history/replicationDLQHandler_mock.go, service/history/replicationTaskExecutor_mock.go, service/history/replicationTaskFetcher_mock.go, service/history/replicationTaskProcessor_mock.go
* Add namespace tests
* Remove redundant select during creation of namespace
Add SQL persistence specific tests.
**Why?**
Run tests.
=> Add SQL specific tests for namespace

Makefile, common/persistence/sql/sqlShardManager.go, common/persistence/sql/sqlplugin/history.go, common/persistence/sql/sqlplugin/interfaces.go, common/persistence/sql/sqlplugin/mysql/shard.go, common/persistence/sql/sqlplugin/postgresql/shard.go, common/persistence/sql/sqlplugin/tests/history_shard_test.go, common/persistence/sql/sqlplugin/tests/matching_task_queue_test.go, common/persistence/sql/sqlplugin/tests/matching_task_test.go, common/persistence/sql/sqlplugin/tests/mysql_test.go, common/persistence/sql/sqlplugin/tests/postgresql_test.go
* Add history shard tests
Add SQL persistence specific tests.
**Why?**
Run tests.
=> Add SQL specific tests for history shard

common/persistence/sql/sqlplugin/definition.go, common/persistence/sql/sqlplugin/history.go, common/persistence/sql/sqlplugin/interfaces.go, common/persistence/sql/sqlplugin/mysql/execution_maps.go, common/persistence/sql/sqlplugin/postgresql/execution_maps.go, common/persistence/sql/sqlplugin/tests/history_execution_activity_test.go, common/persistence/sql/sqlplugin/tests/history_execution_buffer_test.go, common/persistence/sql/sqlplugin/tests/history_execution_child_workflow_test.go, common/persistence/sql/sqlplugin/tests/history_execution_timer_test.go, common/persistence/sql/sqlplugin/tests/history_shard_test.go, common/persistence/sql/sqlplugin/tests/mysql_test.go, common/persistence/sql/sqlplugin/tests/postgresql_test.go, common/persistence/sql/workflowStateMaps.go, common/persistence/sql/workflowStateNonMaps.go
* Add history execution buffer tests
* Add history execution activity tests
* Add history execution child workflow tests
* Add history execution timer tests
Add SQL persistence specific tests.
**Why?**
Run tests.
=> Add SQL specific tests for mutable state, part 1

common/persistence/sql/sqlplugin/definition.go, common/persistence/sql/sqlplugin/history.go, common/persistence/sql/sqlplugin/mysql/execution_maps.go, common/persistence/sql/sqlplugin/postgresql/execution_maps.go, common/persistence/sql/sqlplugin/tests/history_execution_activity_test.go, common/persistence/sql/sqlplugin/tests/history_execution_buffer_test.go, common/persistence/sql/sqlplugin/tests/history_execution_child_workflow_test.go, common/persistence/sql/sqlplugin/tests/history_execution_request_cancel_test.go, common/persistence/sql/sqlplugin/tests/history_execution_signal_requested_test.go, common/persistence/sql/sqlplugin/tests/history_execution_signal_test.go, common/persistence/sql/sqlplugin/tests/history_execution_timer_test.go, common/persistence/sql/sqlplugin/tests/history_shard_test.go, common/persistence/sql/sqlplugin/tests/matching_task_queue_test.go, common/persistence/sql/sqlplugin/tests/matching_task_test.go, common/persistence/sql/sqlplugin/tests/mysql_test.go, common/persistence/sql/sqlplugin/tests/namespace_test.go, common/persistence/sql/sqlplugin/tests/postgresql_test.go, common/persistence/sql/workflowStateMaps.go, common/persistence/sql/workflowStateNonMaps.go
Add SQL persistence specific tests:
* Add history execution request cancel tests
* Add history execution signal tests
* Add history execution signal request tests
**Why?**
Run tests.
=> Add SQL specific tests for mutable state, part 2

common/convert/convert.go, common/persistence/sql/sqlVisibilityStore.go, common/persistence/sql/sqlplugin/mysql/visibility.go, common/persistence/sql/sqlplugin/postgresql/visibility.go, common/persistence/sql/sqlplugin/tests/visibility_test.go, common/persistence/sql/sqlplugin/visibility.go
* Add visibility tests
* Add visibility pagination tests
**Why?**
Run tests.
=> Add SQL specific tests for visibility, part 2

Makefile, docker/dependencies/docker-compose.darwin.yml, docker/dependencies/docker-compose.jaeger.yml, docker/dependencies/docker-compose.linux.yml, docker/dependencies/docker-compose.prometheus.yml, docker/dependencies/docker-compose.windows.yml, docker/dependencies/docker-compose.yml
Improved `docker-compose.yml` files which are used to run dependencies locally.
**Why?**
1. Added Jaeger.
2. Added Prometheus.
3. Attached `web` to the right network on Mac.
Run locally.
No risks, development environment.
=> Improve dependencies docker-compose.yml

common/persistence/sql/sqlExecutionManager.go, common/persistence/sql/sqlExecutionManagerUtil.go, common/persistence/sql/sqlplugin/definition.go, common/persistence/sql/sqlplugin/history.go, common/persistence/sql/sqlplugin/history_execution.go, common/persistence/sql/sqlplugin/mysql/execution.go, common/persistence/sql/sqlplugin/postgresql/events.go, common/persistence/sql/sqlplugin/postgresql/execution.go, common/persistence/sql/sqlplugin/tests/history_current_execution_test.go, common/persistence/sql/sqlplugin/tests/history_execution_buffer_test.go, common/persistence/sql/sqlplugin/tests/history_execution_test.go, common/persistence/sql/sqlplugin/tests/matching_task_queue_test.go, common/persistence/sql/sqlplugin/tests/mysql_test.go, common/persistence/sql/sqlplugin/tests/postgresql_test.go
* Add history current execution tests
* Add history execution tests
**Why?**
Run tests.
=> Add SQL specific tests for executions

docker/dependencies/docker-compose.yml
`docker/dependencies/docker-compose.yml` was updated to match build kite settings changed in #821.
**Why?**
To keep local development more predictable.
Run tests locally.
No risks.
=> Update PostgreSQL dependencies docker-compose.yml

common/log/tag/tags.go, service/history/queueAckMgr.go, service/history/timerQueueAckMgr.go
*Remove unnecessary debug logging with task processing
**Why?**
The debug logging is usually not enabled, but still consumes lots of CPU / Mem
Make bins
N/A
=> Remove unnecessary debug logging

config/development.yaml, config/development_archival.yaml
Removed unneeded settings from config files.
**Why?**
These were some leftover settings.
Manually tested that server starts without these settings.
None really.
=> Remove unneeded settings from config files

docker/config_template.yaml, docker/docker-compose-cockroach.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml, docker/start.sh
* Update PostgreSQL related Docker configs
**Why?**
Prepare for PostgreSQL readyness
Manually run local built auto-setup along with modified `docker/docker-compose-postgres.yml`
PostgreSQL is not officially supported, N/A
=> PostgreSQL readyness for Docker

common/persistence/sql/sqlExecutionManager.go, common/persistence/sql/sqlplugin/definition.go, common/persistence/sql/sqlplugin/history.go, common/persistence/sql/sqlplugin/history_activity.go, common/persistence/sql/sqlplugin/history_child_workflow.go, common/persistence/sql/sqlplugin/history_execution.go, common/persistence/sql/sqlplugin/history_replication_dlq_tasks.go, common/persistence/sql/sqlplugin/history_replication_tasks.go, common/persistence/sql/sqlplugin/history_request_cancel.go, common/persistence/sql/sqlplugin/history_signal.go, common/persistence/sql/sqlplugin/history_signal_request.go, common/persistence/sql/sqlplugin/history_timer.go, common/persistence/sql/sqlplugin/history_timer_tasks.go, common/persistence/sql/sqlplugin/history_transfer_tasks.go, common/persistence/sql/sqlplugin/interfaces.go, common/persistence/sql/sqlplugin/mysql/execution.go, common/persistence/sql/sqlplugin/postgresql/execution.go, common/persistence/sql/sqlplugin/tests/history_replication_task_dlq_test.go, common/persistence/sql/sqlplugin/tests/history_replication_task_test.go, common/persistence/sql/sqlplugin/tests/mysql_test.go, common/persistence/sql/sqlplugin/tests/postgresql_test.go
* Some minor code structure change
* Add replication tasks tests
* Add replication DLQ tasks tests
**Why?**
Run tests.
=> Add SQL specific tests for replication tasks

Dockerfile, docker/buildkite/Dockerfile
Update go version in Dockerfile
**Why?**
Use latest go
Buildkite tests
N/A
=> Use go 1.15

common/persistence/cassandra/cassandraPersistence.go, go.mod
Correctly handle error.
Solve #868
**Why?**
Previously the error was ignored causing SIGSEGV.
run command `./tctl adm db scan --db_address localhost --db_port 9042`
N/A
=> Improve error handling

common/rpc/interceptor.go, service/frontend/service.go, service/history/service.go, service/matching/service.go
Replaced three instances of identical gRPS interceptor code with one shared version.
**Why?**
Removed code duplication and created one place where the interceptor code can be extended.
Unit tests.
I see no risk.
=> Consolidate gPRC interceptors and eliminate code duplication

docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
Switch to Web v1.1.1 in docker files
**Why?**
Newer Web
Tests + manual run
no risks
=> Reference Web v1.1.1

Dockerfile, docker/start-temporal.sh
Temporary fix cherry picked from `v1.1.1`.
=> Hotfix SERVICES env

common/headers/versionChecker.go, docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
* Update docker compose files
* Update server / cli version
**Why?**
Release 1.2.0
CICD
N/A
=> Release 1.2.0

common/headers/versionChecker.go, docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
* Update docker compose files
* Update server / cli version
**Why?**
Release 1.2.1
CICD
N/A
=> Release 1.2.1

docker/docker-compose-cockroach.yml
Fix bug in cockroach DB config.
**Why?**
Bugfix.
Run docker compose locally.
N/A
=> Fix docker compose cockroach config

common/persistence/persistence-tests/executionManagerTest.go, common/persistence/persistence-tests/historyV2PersistenceTest.go, common/persistence/persistence-tests/matchingPersistenceTest.go, common/persistence/persistence-tests/metadataPersistenceV2Test.go, common/persistence/persistence-tests/queuePersistenceTest.go, common/persistence/persistence-tests/shardPersistenceTest.go, common/persistence/persistence-tests/visibilityPersistenceTest.go, go.mod, go.sum, host/integration_test.go, tools/cassandra/setupTask_test.go, tools/cassandra/version_test.go, tools/sql/clitest/setuptaskTest.go
`logrus` was removed from dependency list.
**Why?**
It was used in tests only in a very simple way where standrat `log` package is good enough.
Build.
No risks.
=> Remove logrus dependency

service/history/shard/controller_test.go
* Fix a bug on shard controller test
**Why?**
Test sometimes is broken
Run test
N/A
=> Fix shard controller test bug

common/persistence/sql/sqlTaskManager.go, common/persistence/sql/sqlplugin/matching_task.go, common/persistence/sql/sqlplugin/matching_task_queue.go, common/persistence/sql/sqlplugin/mysql/task.go, common/persistence/sql/sqlplugin/postgresql/task.go, common/persistence/sql/sqlplugin/tests/matching_task_queue_test.go, common/persistence/sql/sqlplugin/tests/matching_task_test.go
* Use filter struct instead of pointer for matching SQL layer
**Why?**
Run tests.
=> Use filter struct instead of pointer for matching SQL layer

common/persistence/cassandra/cassandraMetadataPersistenceV2.go
Duplicate line removed.
**Why?**
Bug fix.
Build.
No risks.
=> Remove duplicated line

common/headers/versionChecker.go, docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
* Update docker compose file
**Why?**
Update docker compose file version
Cherry pick from release branch
N/A
=> Release 1.2.1 (#908)

host/resetworkflow_test.go
* Increase workflow reset test activity timeout
**Why?**
Test is not stable
Run tests
N/A
=> Fix unstable workflow reset test

Makefile, proto/api-linter.yaml, proto/buf.yaml
`PATH` variable is set in a MacOS compatible way.
**Why?**
Simple `export PATH` doesn't work on Mac.
Run different make targets on Linux and Mac.
No risks.
=> Fix PATH variable on MacOS

service/history/mutableStateBuilder.go, service/history/mutable_state_builder_state_status.go, service/history/nDCWorkflow.go, service/history/nDCWorkflow_test.go
`executuonstate` package was removed.
**Why?**
This package is not needed and can be part of `history` (later it needs to be extracted to another package together with other mutable state related stuff.
Build.
No risks.
=> Remove executionstate package

config/development_active.yaml, config/development_other.yaml, config/development_standby.yaml, host/dynamicconfig.go, host/ndc/replication_integration_test.go, service/frontend/service.go, service/history/configs/config.go, service/worker/service.go
* Fix broken NDC yaml config
* Set NDC replication to default to Kafka
**Why?**
Update default NDC related configs 
Run locally
N/A
=> Update NDC default config

service/history/historyBuilder.go, service/history/historyBuilder_test.go, service/history/historyEngine.go, service/history/mutableState.go, service/history/mutableStateBuilder.go, service/history/mutableState_mock.go, service/history/stateBuilder.go, service/history/stateBuilder_test.go
* Remove unused cause / reason from cancel workflow
* Format history builder
**Why?**
Better code management
Make bins
N/A
=> Remove unused cause / reason from cancel workflow

Dockerfile
* Update docker file with alpine 3.12
**Why?**
Use newer dependency
Buildkite / CICD
N/A
=> Update docker with alpine 3.12

service/history/nDCStateRebuilder.go, service/history/nDCStateRebuilder_test.go, service/history/replicatorQueueProcessor.go, service/history/replicatorQueueProcessor_test.go, service/history/workflowResetter.go
* Remove / cleanup unused replication code
**Why?**
Remove duplicated / unnecessary wrapper / logic
Run tests
N/A
=> Remove / cleanup unused replication code

common/persistence/cassandra/cassandraQueue.go, common/persistence/namespaceReplicationQueue.go, common/persistence/persistence-tests/queuePersistenceTest.go, common/persistence/persistenceInterface.go, common/persistence/persistenceRateLimitedClients.go, common/persistence/sql/sqlQueue.go, common/persistence/sql/sqlplugin/queue_message.go, service/history/replicationDLQHandler_test.go, service/history/replicationTaskExecutor_test.go, service/history/replicationTaskProcessor.go, service/history/replicatorQueueProcessor.go
* Unify queue message ID definition
**Why?**
Better code structure
Run tests
N/A
=> NoSQL / SQL specific changes for messages, part 4

service/history/historyEngine.go
* Remove duplicated history engine interface definition
**Why?**
Duplicated interface definition
Make bins
N/A
=> Remove duplicated history engine interface definition

config/dynamicconfig/development.yaml, config/dynamicconfig/development_es.yaml
* Update dynamic config removing the override on namespace min retention days
**Why?**
Min 0 default retention days is misleading
N/A
N/A
=> Update stale dynamic config

common/persistence/sql/sqlplugin/history_activity.go, common/persistence/sql/sqlplugin/history_child_workflow.go, common/persistence/sql/sqlplugin/history_request_cancel.go, common/persistence/sql/sqlplugin/history_signal.go, common/persistence/sql/sqlplugin/history_signal_request.go, common/persistence/sql/sqlplugin/history_timer.go, common/persistence/sql/sqlplugin/interfaces.go, common/persistence/sql/sqlplugin/mysql/execution_maps.go, common/persistence/sql/sqlplugin/postgresql/execution_maps.go, common/persistence/sql/sqlplugin/tests/context_test.go, common/persistence/sql/sqlplugin/tests/history_execution_activity_test.go, common/persistence/sql/sqlplugin/tests/history_execution_child_workflow_test.go, common/persistence/sql/sqlplugin/tests/history_execution_request_cancel_test.go, common/persistence/sql/sqlplugin/tests/history_execution_signal_requested_test.go, common/persistence/sql/sqlplugin/tests/history_execution_signal_test.go, common/persistence/sql/sqlplugin/tests/history_execution_timer_test.go, common/persistence/sql/workflowStateMaps.go, common/persistence/sql/workflowStateNonMaps.go
* Optimize SQL layer supporting batch delete
* Split DeleteFromActivityInfoMaps into DeleteFromActivityInfoMaps and DeleteAllFromActivityInfoMaps
* Split DeleteFromTimerInfoMaps into DeleteFromTimerInfoMaps and DeleteAllFromTimerInfoMaps
* Split DeleteFromChildExecutionInfoMaps into DeleteFromChildExecutionInfoMaps and DeleteAllFromChildExecutionInfoMaps
* Split DeleteFromRequestCancelInfoMaps into DeleteFromRequestCancelInfoMaps and DeleteAllFromRequestCancelInfoMaps
* Split DeleteFromSignalInfoMaps into DeleteFromSignalInfoMaps and DeleteAllFromSignalInfoMaps
* Split DeleteFromSignalsRequestedSets into DeleteFromSignalsRequestedSets and DeleteAllFromSignalsRequestedSets
**Why?**
Perf optimization
Run tests
N/A
=> Optimize SQL layer supporting batch delete

common/service/config/config.go
Updated yaml property name to match its updated name.
**Why?**
Names should match.
Buildkite
No risk
=> Update yaml property name after renaming Security -> Authorization

common/persistence/cassandra/cassandraHistoryPersistence.go, common/persistence/cassandra/cassandraVisibilityPersistence.go, common/persistence/sql/sqlHistoryManager.go, service/history/replicationDLQHandler.go, service/history/replicationDLQHandler_test.go
* Fix replication DLQ handler mem allocation
* Add more tests
* Optimize other use of make slice
**Why?**
Fix a small bug in replication DLQ handler mem allocation
Existing tests
N/A
=> Bugfix: replication DLQ handler mem allocation

service/history/replicationTaskFetcher.go, service/history/replicationTaskFetcher_mock.go, service/history/replicationTaskFetcher_test.go, service/history/replicationTaskProcessor.go, service/history/replicationTaskProcessor_test.go
* Rewrite some of the fetch & processing logic better handling error case
* Add additional unit tests
**Why?**
Make code more resilient when remote cluster is unreachable
Run tests
N/A
=> Better error handling for replication fetcher & processor

common/cache/namespaceCache.go, common/cache/namespaceCache_test.go, common/persistence/sql/sqlplugin/mysql/events.go, common/persistence/sql/sqlplugin/postgresql/events.go, common/persistence/sql/sqlplugin/tests/history_tree_test.go
cherry pick #1014
**Why?**
cherry pick #1014
cherry pick #1014
cherry pick #1014
=> Remove forced namespace cache refresh (cherry pick #1014)

common/authorization/defaultJWTClaimMapper_test.go
Fixed a typo.
**Why?**
Fixed a typo.
No need for verification.
No risk.
=> Fix typo in json name attribute

docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
Docker compose now references web docker image v1.3.1
**Why?**
New updates on web, most importantly keycloak authn fix, adds mTLS support, fixes an issue in workflow ALL view
`docker-compose up` + CI tests
Changes the behavior on web, no risks to server
=> Reference web docker image v1.3.1 

common/service/config/metrics.go, common/service/config/metrics_test.go, temporal/server.go, temporal/server_option.go, temporal/server_options.go
Added option to provide custom metrics reporter to temporal server.
**Why?**
https://github.com/temporalio/temporal/issues/1008
unit tests, manual
Metrics not reported.
=> Allow to specify custom metrics reporter

common/persistence/versionhistory/version_histories.go, common/persistence/versionhistory/version_history.go, common/persistence/versionhistory/version_history_item.go, service/history/historyEngine.go
* Ensure value returned from version history package are copied
**Why?**
DATA RACE during test & we should have immutable data structure
Existing tests
N/A
=> Ensure version history values are copied

service/history/timerQueueActiveTaskExecutor.go
* Enforce context deadline with pushing activity retry task to matching service 
**Why?**
Remote RPC calls should comes with timeout
N/A
N/A
=> Use proper context deadline when pushing activity to matching

go.mod, go.sum
* Pin github.com/go-sql-driver/mysql to v1.5.0
**Why?**
Update dependency
Run tests & CICD
N/A
=> Pin github.com/go-sql-driver/mysql to v1.5.0

common/constants.go, common/metrics/defs.go, common/persistence/cassandra/cassandraPersistence.go, common/service/dynamicconfig/constants.go, common/todo_deprecate.go, common/util.go, common/util_test.go, host/continueasnew_test.go, service/frontend/service.go, service/frontend/workflowHandler.go, service/history/commandChecker.go, service/history/configs/config.go, service/history/historyEngine.go, service/history/historyEngine_test.go, service/history/nDCTransactionMgrForNewWorkflow.go, service/history/timerSequence.go, service/history/timerSequence_test.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/workflowExecutionUtil.go, service/history/workflowTaskHandler.go, service/matching/forwarder.go, service/matching/matchingEngine.go, service/matching/taskWriter.go, service/worker/scanner/taskqueue/handler.go
* Remove unnecessary dynamic config related to workflow max timeout
* Remove unnecessary dynamic config related to workflow task timeout
* Handle tasks TTL in matching service properly
* Handle activity without timeout
**Why?**
Allow infinite workflow timeout
Manual tests
N/A
=> Allow workflow timeout being infinite

service/history/historyEngine.go, tools/cli/admin.go, tools/cli/adminDLQCommands.go
* Fix broken admin DLQ CLI
**Why?**
See above
Manual test
N/A
=> Fix broken admin DLQ CLI

common/service/dynamicconfig/constants.go, service/history/configs/config.go, service/history/handler.go, service/history/replicationDLQHandler.go, service/history/replicationTaskProcessor.go, service/history/replicationTaskProcessor_test.go, service/history/shard/context_impl.go, service/history/shard/controller_test.go
* Adjust RPC replication configs
* Fix bug on DLQ message generation
* Sort replication tasks by shard ID, task ID when querying DLQ
* Fix bug on ReplicationDlqAckLevel initialization
**Why?**
Fix issues related to NDC RPC stack
Manual tests & existing tests
N/A
=> Adjust RPC replication config

temporal/server.go
* Do not validate Kafka config if RPC replication stack is used
**Why?**
Unnecessary check
N/A
N/A
=> Do not validate Kafka config if RPC replication stack is used

common/service/dynamicconfig/constants.go, common/todo_deprecate.go, host/integration_test.go, service/frontend/service.go, service/frontend/workflowHandler.go, service/history/commandChecker.go, service/history/configs/config.go
This reverts commit f67c31b0d1800339a7122f19f926ca70b389c3e9.
Revert the #1030 due to bug found in cron workflow & retry
**Why?**
Behavior broken for cron workflow with retry
N/A
N/A
=> Revert "Finish migration of infinite workflow timeout (#1030)"

common/headers/versionChecker.go, docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
Update docker server tag
**Why?**
N/A
N/A
N/A
=> Release server 1.4.1

common/headers/versionChecker.go, docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
* Update docker compose file for v1.4.1
**Why?**
See above
N/A
N/A
=> Bump server version to 1.4.1 (#1072)

common/persistence/cassandra/cassandraPersistenceUtil.go, common/persistence/serialization/blob.go, common/persistence/sql/sqlExecutionManager.go, common/persistence/sql/sqlExecutionManagerUtil.go
* Wire visibility tasks for SQL for Kafka deprecation
**Why?**
See above
Run tests
N/A
=> Wire visibility tasks for SQL

common/persistence/cassandra/cassandraPersistence.go, common/persistence/persistence-tests/executionManagerTest.go, common/persistence/sql/sql_execution.go, common/persistence/sql/sql_execution_util.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/timerQueueTaskExecutorBase.go, service/history/timerQueueTaskExecutorBaseV2_test.go, service/history/workflowExecutionContext.go
* Do not touch mutable state when creating delete visibility task
* Add deleted zombie workflow not being current workflow checks & tests
**Why?**
Cleanup for Kafka deprecation.
Partially solve #1079
Run tests
N/A
=> Optimize delete visibility task

service/history/service.go
* Correctly set the ES config according to latest release
**Why?**
ES is not correctly configured
N/A
N/A
=> Correctly config ES for history service

service/frontend/service.go
* Correctly config ES for frontend service
**Why?**
ES is not correctly configured
N/A
N/A
=> Correctly config ES for frontend service

service/history/shard/context_test.go
Unit test for `AddTasks` added.
**Why?**
Increase coverage.
Run it.
N/A
=> Add AddTasks test

schema/cassandra/temporal/schema.cql
Comment added.
**Why?**
Fix comment.
N/A
N/A
=> Add VisibilityTask to type comment

common/persistence/sql/sqlTaskManager.go, service/matching/taskWriter.go
* Properly handle ConditionFailedError when task queue range ID mismatch
* Properly handle ConditionFailedError when task queue expires
**Why?**
When encounter ConditionFailedError, in mem task queue should be shutdown and re-initialized
Existing tests
N/A
=> Properly handling task queue lease expiration

docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
Reference Web v1.4.1
**Why?**
New version of Web
Tests, ran temporal with Web v1.4.1
no risks
=> Tag Web v1.4.1

common/authorization/interceptor.go, common/authorization/interceptor_test.go, common/metrics/defs.go
`Authorization` metrics scope was moved under front end section.
**Why?**
Bug fix. Metrics are service dependent and should be defined under the correct service scope.
Existing tests, manual run.
No risks.
=> Fix autorization metrics scope

common/headers/versionChecker.go, docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
Version were updated to 1.5.0.
**Why?**
Prepare 1.5.0 release.
N/A
N/A
=> Release v1.5.0

go.mod, go.sum
* Fix broken docker build
**Why?**
Docker build is broken
N/A
N/A
=> Fix docker build

common/headers/versionChecker.go, docker/docker-compose-cockroach.yml, docker/docker-compose-es.yml, docker/docker-compose-mysql-es.yml, docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml, docker/docker-compose.yml
* Update docker compose for 1.5.1
**Why?**
Update docker compose file
N/A
N/A
=> Update docker compose for 1.5.1

common/persistence/cassandra/cassandraHistoryPersistence.go, common/persistence/cassandra/factory.go
* Add more Cassandra log
**Why?**
N/A
N/A
N/A
=> Add more Cassandra log

Makefile, common/metrics/runtime.go, common/metrics/tags.go, ldflags/ldflags.go, scripts/go-build-ldflags.sh
Cleaned up `ldflags`. Moved the to separate package for better discovery.
**Why?**
`Makefile` cleanup and refactoring.
Build.
`git_version` changed to `git_tag` in build info reporter. I believe this metric is not used though.
=> Refactor ldlflags

Dockerfile, Makefile
Removed unused binaries from `Dockerfile`. 
**Why?**
Decrease docker image build speed.
Build images locally and run them.
No risks.
=> Clean up main Dockerfile

common/headers/versionChecker.go
Current version is set to `1.6.0`.
**Why?**
After `1.5.0` release, current `master` branch, in fact, becomes next version. Bumping up it right after release makes any docker image built from `master` a release candidate.
N/A
N/A
=> Bump current version to 1.6.0

Makefile, common/persistence/sql/sqlplugin/mysql/admin.go, common/persistence/sql/sqlplugin/postgresql/admin.go, tools/cassandra/cqlclient.go, tools/cassandra/handler.go, tools/cassandra/main.go, tools/sql/handler.go, tools/sql/main.go
`Makefile` `instal-schema*` targets recreate database/keyspace every time.
**Why?**
Improve developer experience. 
Run manually on all 3 storage types.
No risks.
=> Drop database/keyspace if exists

.dockerignore
`.dockerignore` file updated.
**Why?**
Keep docker build up to date.
Build images manually.
No risks.
=> Clean up .dockerignore

common/persistence/cassandra/cassandraHistoryPersistence.go
* Bugfix: AppendHistoryNodes batch write error not correctly set
**Why?**
Bugfix
N/A
N/A
=> Bugfix: AppendHistoryNodes return error not correctly set

temporal/server.go
Bug fix for service resolver not being properly initialized on startup.
**Why?**
Bug fix.
Start server locally.
No risks.
=> Fix server startup bug

service/frontend/workflowHandler.go
Log level for visibility request was decreased to `Debug` from `Info`.
**Why?**
Remove noisy logs.
N/A
N/A
=> Decrease list visibility requests log level to Debug

service/frontend/adminHandler.go
* Do not use nil as response when no error
**Why?**
N/A
N/A
N/A
=> Fix nil response within admin handler

config/dynamicconfig/development.yaml, config/dynamicconfig/development_es.yaml
All missed settings from `dynamicconfig/development.yaml` were copied to `dynamicconfig/development_es.yaml`.
**Why?**
There is no config inheritance for dynamic configs and all settings must exists in both configs.
Run locally.
No risks.
=> Sync non-ES and ES dynamic configs

Makefile, config/development_mysql-es.yaml
Added config and `Makefile` targets to run MySQL+ES configuration.
**Why?**
To enable local testing of MySQL+ES setup.
Run locally.
No risks.
=> Add MySQL+ES configuration

Makefile
Improved error message for `ensure-no-changes` target.
**Why?**
Beter dev exp.
Run locally.
N/A.
=> Improve ensure-no-changes target error message

common/headers/versionChecker.go
Increased version to `1.7.0` after `v1.6.0` release.
**Why?**
Prepare for next release.
N/A
N/A
=> Bump ServerVersion to 1.7.0

service/history/replicatorQueueProcessor.go
* Fix prometheus metrics for NDC replication lag
**Why?**
N/A
N/A
N/A
=> Fix NDC metrics reporting

Dockerfile
* Update docker pip install script
**Why?**
Previous link is broken (not python 2)
N/A
N/A
=> Update pip install script

common/elasticsearch/client_v7.go, common/persistence/elasticsearch/esProcessor.go
Enabled extra logging for ES.
**Why?**
Debug ES7 behaviour.
N/A
N/A
=> Add more logging to ES

common/metrics/tags.go
* Bugfix on task queue metrics tag name
**Why?**
N/A
N/A
N/A
=> Fix metrics tag name

common/metrics/defs.go
* Fix parent close metrics definition
**Why?**
Bugfix
N/A
N/A
=> Fix parent close metrics definition

service/history/replicationTaskProcessor.go
* Use correct metrics when replication fails
**Why?**
Bugfix
N/A
N/A
=> Fix replication failure metrics

.development/docker-compose/docker-compose.yml
Update web image tag to the latest `1.6.0`.
**Why?**
Keeping web image up to date.
N/A
N/A
=> Update web to 1.6.0 in development docker-compose

docker/config_template.yaml
Fix spacing in `config-template.yaml` for `ES_VERSION`.
**Why?**
Bug fix.
Build docker image locally and run it.
No risks.
=> Fix spacing in config-template.yaml for ES_VERSION

common/archiver/s3store/historyArchiver.go, common/metrics/client.go, common/metrics/interfaces.go, common/metrics/mocks/Client.go, common/metrics/mocks/Scope.go, common/metrics/scope.go, common/task/sequentialTaskProcessor.go, common/util.go, service/frontend/adminHandler.go, service/frontend/workflowHandler.go, service/history/queueAckMgr.go, service/history/queueProcessor.go, service/history/queueTask.go, service/history/replicationTaskProcessor.go, service/history/replicatorQueueProcessor.go, service/history/shard/context_impl.go, service/history/taskProcessor.go, service/history/timerQueueAckMgr.go, service/history/workflowMetrics.go, service/worker/archiver/replay_metrics_client.go
* Fix histogram metrics reporting for non time metrics
**Why?**
N/A
N/A
N/A
=> Fix distribution metrics issue

.development/docker-compose/docker-compose.yml
Tag web 1.6.1
**Why?**
Newer version
tests + run
No risks
=> Tag Web v1.6.1

common/service/config/metrics.go
* Fix prometheus reporter initialization issue
**Why?**
N/A
N/A
N/A
=> Correctly initialize prometheus reporter

service/matching/matcher.go, service/matching/taskQueueManager_test.go
* Simplify matching engine rate limit logic
**Why?**
Remove twisted logic
N/A
N/A
=> Simplify matching engine rate limit logic

common/service/config/metrics.go, common/service/config/metrics_test.go, temporal/server.go
Refactor custom meteric reporter.
**Why?**
Improve code readablity.
No risks.
=> Refactor custom metrics reporter

service/matching/matchingEngine_test.go, service/matching/taskWriter.go
* Change matching engine shutdown error from no type to ConditionFailedError type
**Why?**
Better error handling
N/A
N/A
=> Improve matching engine error type

service/matching/taskQueueManager.go
* Remove duplicated code in matching service
* Add more error handling
**Why?**
N/A
N/A
N/A
=> Remove duplicated code in matching service

common/log/tag/tags.go, service/matching/context.go, service/matching/handler.go, service/matching/matcher.go, service/matching/matchingEngine_test.go, service/matching/taskQueueManager.go
* Categorize remote sync match failure as cancelled error 
* Add logger to matching service
* Minor changes to tests
**Why?**
N/A
N/A
N/A
=> Add logger to matching service

common/rpc/test/rpc_common_test.go, common/rpc/test/rpc_localstore_tls_test.go
Moved tests to a test subdirectory.
Refactored TLS tests to consolidate test configs.
**Why?**
Preparation for adding more tests for dynamic cert providers.
Unit tests.
No risk - test code organization only.
=> Refactor TLS tests

.development/docker-compose/docker-compose.yml
Referenced Web v1.6.2
**Why?**
New patch release
ran using docker-compose
no risks
=> Tag Web v1.6.2

service/history/mutableStateBuilder_test.go, service/history/mutableStateWorkflowTaskManager.go
* Guarantee workflow last write version is valid
**Why?**
https://github.com/uber/cadence/pull/3960
=> Create non-transient workflow task when version changes

tools/sql/README.md
A command in the README.md file about update mysql schema.
**Why?**
Because I think it's not true.
=> Fix update schema command for temporal_visibility

tools/cassandra/cqlclient.go
* Set connection timeout for cassandra tool
**Why?**
N/A
N/A
N/A
=> Set connection timeout for cassandra tool

cmd/server/main.go, docker/config_template.yaml
Add quotes to `config_tempate.yaml`.
**Why?**
Without quotes Some values can lead to invalid yaml.
Run locally.
No risks.
=> Add quotes to config_tempate.yaml

service/history/historyEngine.go
* Add additional check on started child workflow ID
**Why?**
N/A
N/A
N/A
=> Add protection on child workflow ID

common/persistence/cassandra/cassandraPersistenceTest.go, common/persistence/client/bean.go, common/persistence/client/factory.go, common/persistence/sql/sqlPersistenceTest.go, common/resource/resourceImpl.go, host/continueasnew_test.go, host/elasticsearch_test.go, host/xdc/elasticsearch_test.go, service/frontend/service.go, service/frontend/workflowHandler_test.go, service/history/service.go
Minor search attributes related refactorings.
**Why?**
Decompose big search attributes refactoring PR.
Run all tests.
No risks.
=> Minor search attributes refactorings

.development/docker-compose/docker-compose.yml
Upgrade web to v1.7.0
**Why?**
Newer version
docker-compose up
no risks
=> Tag Web v1.7.0

common/service/dynamicconfig/config.go, common/service/dynamicconfig/constants.go, service/matching/config.go, service/matching/matcher.go, service/matching/matchingEngine_test.go, service/matching/taskQueueManager_test.go, service/matching/taskReader.go
* Add admin dynamic config controlled task queue max rate limit
**Why?**
N/A
N/A
N/A
=> Add server controlled task queue max dispatch rate

common/persistence/cassandra/cassandraHelpers.go, common/persistence/cassandra/cassandraPersistenceTest.go, common/persistence/client/factory.go, common/persistence/sql/factory.go, common/persistence/sql/sqlPersistenceTest.go, common/persistence/sql/sqlplugin/interfaces.go, common/persistence/sql/sqlplugin/mysql/db.go, common/persistence/sql/sqlplugin/mysql/plugin.go, common/persistence/sql/sqlplugin/postgresql/db.go, common/persistence/sql/sqlplugin/postgresql/plugin.go, common/persistence/sql/sqlplugin/tests/mysql_test.go, common/persistence/sql/sqlplugin/tests/postgresql_test.go, common/persistence/sql/store.go, common/persistence/sql/version_checker.go, tools/cassandra/handler.go, tools/cassandra/version_test.go, tools/common/schema/handler.go, tools/sql/clitest/versionTest.go, tools/sql/conn.go, tools/sql/handler.go
* Add version check method to SQL interface
* Remove tools version check method in favor of functions defined in persistence package
* Refactor tests to not depend on tools package
**Why?**
Better compatibility
N/A
N/A
=> Unify db version check

tools/cassandra/handler.go, tools/cassandra/handler_test.go, tools/cassandra/main.go, tools/common/schema/handler.go, tools/common/schema/types.go, tools/sql/clitest/handler_test.go, tools/sql/handler.go, tools/sql/main.go
* Remove dry run option in schema tools since this option is essentially broken and can easily backfire
Closes #1197
=> Remove dryrun option in schema tools

common/service/dynamicconfig/constants.go, service/matching/config.go, service/matching/matcher.go
* Update dynamic config for task queue qps control
**Why?**
N/A
N/A
N/A
=> Update dynamic config for task queue qps control

common/persistence/historyStore.go, common/persistence/persistence-tests/historyV2PersistenceTest.go, service/frontend/workflowHandler.go, service/history/events/cache.go, service/history/nDCStateRebuilder.go, service/history/workflowResetter.go, service/worker/scanner/executions/shard_validator.go
* Add more logging including namespace ID & workflow ID & run ID if DB encounters data loss
**Why?**
N/A
N/A
N/A
No
=> Add more logging in case events are not contiguous

common/rpc/interceptor/namespace_count_limit.go, common/rpc/interceptor/namespace_rate_limit.go, common/rpc/interceptor/telemetry.go, common/util.go, service/frontend/workflowHandler.go, service/frontend/workflowHandler_test.go, service/history/commandChecker.go, service/history/workflowTaskHandlerCallbacks.go
* Add metrics back
**Why?**
N/A
N/A
N/A
=> Use context to propagate API metrics scope

tools/cassandra/cqlclient.go
* Allow specification of datacenter
**Why?**
see #1309 
N/A
N/A
N/A
=> Fix cassandra tool

service/frontend/workflowHandler.go, tools/cli/workflowCommands.go
=> Fix new line in tctl error message

common/collection/pagingIterator.go
* Add ability to initialize a paging iterator with initial token
**Why?**
N/A
N/A
N/A
N/A
=> Add ability to initialize a paging iterator with initial token

common/persistence/dataInterfaces.go, common/persistence/historyStore.go, service/history/historyEngine.go
=> Remove unused variable

common/searchattribute/validator.go, common/searchattribute/validator_test.go, host/elasticsearch_test.go, service/history/commandChecker.go, service/history/commandChecker_test.go, service/history/historyEngine.go
Move search attribute validator to `searchattribute` package.
**Why?**
Consolidate all search attribute related code in `searchattribute` package.
No risks.
No.
=> Move search attribute validator to searchattribute package

temporal/server.go
Add space to cluster metadata error message.
**Why?**
Error message w/o space is confusing.
N/A
No risks.
No.
=> Add space to cluster metadata error message

common/persistence/cassandra/cassandraPersistence.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/interfaces.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/interfaces_mock.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go, tools/cassandra/cqlclient.go, tools/cli/adminCommands.go, tools/cli/adminDBScanCommand.go
* Update CLI using new gocql wrapper
**Why?**
N/A
N/A
N/A
N/A
=> Update CLI using new gocql wrapper

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Update CONTRIBUTING.md to go 1.16.
**Why?**
Go 1.16 is required for build to work properly.
N/A
No risks.
No.
=> Update CONTRIBUTING.md to go 1.16

common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go
* Revert PR #1340 due to unknown issue when connecting to cassandra
**Why?**
N/A
N/A
N/A
N/A
=> Revert #1340

common/rpc/encryption/localStoreCertProvider.go, common/rpc/encryption/localStoreCertProvider_test.go, go.mod, go.sum
Remove `hashicorp/go-multierror` package dependency.
**Why?**
Remove extra dependency.
New unit test.
No risks.
No.
=> Remove hashicorp/go-multierror package dependency

common/cache/lru.go, common/cache/lru_test.go, service/history/historyCache_test.go
* Add one test case which assert the max capacity behavior of LRU cache
**Why?**
Adding more tests
New test
N/A
No
=> Add more test to LRU cache

service/history/handler.go
History service reports WorkflowAlreadyStarted as explicit error instead of SreviceError
**Why?**
Makes error easier to undrestand.
auto tests.
Change in metrics.
Incorrect downstream error handling.
No.
=> Report explicit WorkflowAlreadyStarted error

common/headers/versionChecker.go
Updated ServerVersion and CLIVersion constants to 1.9.0
**Why?**
Release 1.8.0 is done.
Automated tests.
N/A
No
=> Update server and cli versions to 1.9.0

CONTRIBUTING.md, develop/docs/macos/cassandra.md, develop/docs/macos/mysql.md, develop/docs/macos/postgresql.md, develop/docs/run_dependencies_host.md
Add documentation for running dependencies on the host.
**Why?**
Clarify documentation and link pages together.
N/A
N/A
No.
=> Add documentation for running dependencies on the host

CONTRIBUTING.md, develop/docs/run_dependencies_host.md
Fix broken links in docs.
**Why?**
Follow up to #1416.
N/A
N/A
No.
=> Fix broken links in docs

service/history/mutablestate/history_builder.go, service/history/mutablestate/history_builder_test.go
* Cleanup new history builder
* Add necessary UT
**Why?**
Cleanup the history builder && add necessary unit tests since previous tests are coupled with mutable state
UT
N/A
No
=> Cleanup new history builder

develop/docker-compose/docker-compose.yml
Upgraded to the latest version of Web
**Why?**
New version
docker-compose up
no risks
=> Bump Web from 1.7.1 to 1.8.0

go.mod, go.sum
* Update gocql to latest master (87a5d7a5ff74ffa9eb716f05f6e26191836bf03d)
**Why?**
Update dependency
CICD
Maybe behavior change from gocql, e.g. host name verification will be performed if either condition is met
* `Config.InsecureSkipVerify` being `false`
* `EnableHostVerification` being `true`
see: https://github.com/gocql/gocql/commit/e96e0011d09a9bed3e13115695f5751ca8c17e9b
No
=> Update gocql to latest master (87a5d7a)

temporal/server.go
* Add missing error check for schema version check
**Why?**
Missing error check
Manual
N/A
No
=> Add missing error check for schema version check

develop/docker-compose/docker-compose.yml
Bumps docker compose Web to v1.9.0
**Why?**
new version
docker-compose up
no
no
=> Bump docker-compose Web to v1.9.0

service/history/configs/config.go, service/history/mutableStateBuilder.go
* Default to use DB record version for mutable state to better enforce CAS operation
**Why?**
Follow up of #1420
N/A
N/A
No
=> Default to use DB record version for mutable state

common/rpc/encryption/localStoreTlsProvider.go
Added an explicit check for certificate expiration on server start.
Also added recovery from panic when checking for certificate expiration.
**Why?**
Without this we have to wait for the initial period of expiration checks to pass before metrics appear. This is inconvenient for quick validations.
Unit tests.
I see no risk.
No.
=> Add check for certificate expiration on start

common/persistence/elasticsearch/client/client.go, common/persistence/elasticsearch/client/client_mock.go, common/persistence/elasticsearch/client/client_v6.go, common/persistence/elasticsearch/client/client_v7.go, common/persistence/elasticsearch/client/errors.go, common/persistence/elasticsearch/processor.go, common/persistence/elasticsearch/processor_test.go, service/frontend/adminHandler.go, service/frontend/adminHandler_test.go
Modify Elasticsearch client for the new search attribute implementation.
**Why?**
Modify existing and add new APIs for upcoming search attributes changes.
No risks.
No.
=> Modify Elasticsearch client for the new search attribute implementation

common/metrics/grpc.go
Do not try to assign metrics trailer if context is closed.
**Why?**
gRPC channel is closed in this case.
Automated/manual tests
Metrics not propagated.
No
=> Do not try set trailer if context is closed

common/metrics/baggage_bench_test.go, common/metrics/grpc.go, common/metrics/grpc_test.go, common/rpc/interceptor/telemetry.go
Add thread safety to metrics context.
**Why?**
We report metrics in multiple threads.
manual/auto tests/local canary run
Performance
No
=> Add thread safety to metrics context

.gitignore, Makefile, develop/buildkite/Dockerfile, develop/buildkite/docker-compose.yml, develop/buildkite/pipeline.yml, docker/base-images/base-builder.Dockerfile
Add fossa scan to buildkite.
**Why?**
Adding fossa scans.
Buildkite on this PR.
Buildkite not working.
No
=> Add fossa scan to buildkite

Makefile
Fix go test coverage log warning.
**Why?**
`tools` package doesn't have integration tests and gives a warning:
```
warning: no packages being tested depend on matches for pattern go.temporal.io/server/tools/...
```
Run locally.
No risks.
No.
=> Fix go test coverage log warning

README.md
=> fix Readme Slack invite link

Makefile, develop/buildkite/docker-compose.yml
Specify branch when starting fossa analyze.
**Why?**
Having branch reported will group relevant jobs.
This PR test.
Fossa check fails. Mulitple branches on fossa side.
No.
=> Set branch on fossa analyze

common/persistence/visibilityWrapper.go
Upsert and Delete visibility record in the configured database only.
**Why?**
`DeleteWorkflowExecution` caused NPE when regular visibility is not configured (allowed in `1.9.1`).
Run locally and existing test.
No risks.
Yes, this will be included in `1.9.2` patch.
=> Upsert and Delete visibility record in the configured database only

README.md
Added fossa badge to readme.
**Why?**
License scan visibility.
Preview
N/A
No
=> Add fossa badge to readme

common/headers/versionChecker.go
Bump current version to 1.10.0.
**Why?**
Current version needs to be +1 for the latest release.
N/A
No risks.
No.
=> Bump current version to 1.10.0

service/frontend/service.go
* Use GlobalNamespaceRPS for additional QPS allocated per namespace per host. 
* Per frontend per namespace QPS: `hostRPS+globalRPS*math.Exp((1.0-hosts)/8.0)`
NOTE: above is not distributing tokens among all frontend hosts, but rather a temporary hack.
Plot below is based on 
* hostRPS: 1 
* globalRPS: 1 
**Why?**
Allow caller to experience less throttling error due to unbalanced req -> frontend
Local manual testing
N/A
No
=> Reuse GlobalNamespaceRPS for better distribution of QPS tokens in frontend service

develop/docker-compose/docker-compose.yml
Bumps Web to v1.9.1
**Why?**
New patch version
`docker-compose up -d`
No
No
=> Bump Web to v1.9.1

host/child_workflow_test.go, host/continue_as_new_test.go, service/frontend/workflowHandler.go, service/frontend/workflowHandler_test.go
Set search attribute types for history events attributes.
**Why?**
SDK needs SA type information to properly deserialize it.
Modified unit and integration tests.
No risks.
No.
=> Set search attribute types for history events attributes

docker/auto-setup.sh
Add `ES_USER` and `ES_PWD` to `auto-setup.sh`.
**Why?**
All Elasticsearch related variables but these two were used. In general case these two also must be used.
Closes #1544.
Build image locally and run with docker-compose.
No risks.
No.
=> Add ES_USER and ES_PWD to auto-setup.sh

docker/base-images/base-builder.Dockerfile
Add shellcheck to the base builder image.
**Why?**
I am going to use in `ci-build` target in upcoming PR.
Built image locally.
No risks.
No.
=> Add shellcheck to the base builder image

Dockerfile, Makefile, develop/buildkite/Dockerfile, develop/buildkite/scripts/coverage-report.sh, develop/buildkite/scripts/docker-push.sh, develop/scripts/go-build-ldflags.sh, develop/scripts/goreleaser.sh
=> Use shellcheck in ci-build target

config/dynamicconfig/development_es.yaml, docker/auto-setup.sh, schema/elasticsearch/v6/visibility/index_template.json, schema/elasticsearch/v7/visibility/index_template.json, temporal/server.go
Remove `Custom*Field` search attributes from main code base and create them for auto setup image only.
**Why?**
=> Remove Custom*Field search attributes

schema/cassandra/README.md, tools/cassandra/README.md, tools/sql/README.md
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
Tagging along with https://github.com/temporalio/temporal/pull/1300
to also remove the "-y" and dry run test mentions from the documentation
**Why?**
=> Remove dry run flag and test run from documentation

common/persistence/namespaceReplicationQueue.go
* Improve namespace ack level calculation better handling edge case (if no ack map present)
**Why?**
If ack level maps is empty / not initialized, all namespace replication tasks can be deleted
N/A
N/A
No
=> Improve namespace ack level calculation

develop/docker-compose/docker-compose.yml
Bumps development Web to v1.9.2
**Why?**
New version
docker-compose up
no risks
=> Bump Web to v1.9.2

common/persistence/sql/sqlplugin/postgresql/plugin.go
* Return errors encountered when trying to connect to PostgreSQL compatible DBs
**Why?**
Close #1577
N/A
N/A
No
=> Show connection error details for PostgreSQL layer

common/rpc/interceptor/telemetry.go
* Include namespace tag to API error metrics
**Why?**
Metrics will include details
CICD
N/A
No
=> Include namespace tag to API error metrics

go.mod, service/matching/matchingEngine_test.go
Remove `spew` dependency.
**Why?**
`spew` was used in one test without a good reason.
Run tests.
No risks.
No.
=> Remove spew dependency

common/rpc/interceptor/telemetry.go
* Include namespace in API error log for better debugging exp
**Why?**
See above
N/A
N/A
No
=> Include namespace in API error log

common/authorization/default_jwt_claim_mapper.go, common/authorization/default_jwt_claim_mapper_test.go, go.mod, go.sum
Upgraded dgrijalva/jwt-go dependency to v4.0.0-preview1
**Why?**
To use the latest and greatest version
Unit tests
The new version in theory may bring new bugs
Yes
=> Upgrade 	dgrijalva/jwt-go to v4.0.0-preview1

common/persistence/cassandra/cassandraPersistence.go, common/persistence/client/factory.go, common/persistence/persistenceInterface.go, common/persistence/sql/task.go, common/persistence/task_manager.go
Separate TaskStore from TaskManager. This diff refactored LeaseTaskQueue. At TaskStore layer, it is consists of 3 functions: CreateTaskQueue, GetTaskQueue and ExtendLeaseTask. At TaskManager layer, it handles logic to check if queue exists or not, and create new queue or extend lease for existing queue, as well as serialization / deserialization logic.
Note: this PR only refactored LeaseTaskQueue, other functions will be refactored in separate PR.
**Why?**
Clear separation of persistence layering
Unit test and manually run a workflow.
Low
No
=> Adding TaskManagerImpl

common/dynamicconfig/constants.go, common/locks/condition_variable_test.go, service/history/configs/config.go, service/history/service.go
* Enable mutable state DB version CAS by default
* Adjust condition variable tests to limit test time
**Why?**
Make CAS of mutable state more reliable
Existing tests & CICD
N/A
N/A
=> Enable mutable state DB version CAS by default

common/config/persistence.go, common/persistence/client/factory.go, temporal/server.go, temporal/server_option.go, temporal/server_options.go
Add a new server option to use custom DataStoreFactory. Hookup code to pass the custom factory when present. 
**Why?**
Make it possible to supply custom data store that is not currently offically supported.
Make sure all tests pass.
No.
No.
=> hookup custom data store factory

common/persistence/cassandra/cassandraQueue.go, common/persistence/client/factory.go, common/persistence/namespaceReplicationQueue.go, common/persistence/persistenceInterface.go, common/persistence/persistenceMetricClients.go, common/persistence/persistenceRateLimitedClients.go, common/persistence/sql/queue.go, common/persistence/sql/sqlplugin/mysql/queue.go, common/persistence/sql/sqlplugin/postgresql/queue.go, common/persistence/sql/sqlplugin/queue_metadata.go, common/persistence/sql/sqlplugin/tests/queue_metadata_test.go, schema/mysql/v57/temporal/schema.sql, schema/mysql/v57/temporal/versioned/v1.6/manifest.json, schema/mysql/v57/temporal/versioned/v1.6/queue_metadata.sql, schema/mysql/version.go, schema/postgresql/v96/temporal/schema.sql, schema/postgresql/v96/temporal/versioned/v1.6/manifest.json, schema/postgresql/v96/temporal/versioned/v1.6/queue_metadata.sql, schema/postgresql/version.go
Refactored Queue (for namespace replication).
**Why?**
Clear layer separation for persistence
Unit tests and integration tests
Low
No.
=> Refactor Queue for namespace replication

common/persistence/elasticsearch/visibility_store.go, common/persistence/elasticsearch/visibility_store_read_test.go, common/persistence/persistenceInterface.go, common/searchattribute/defs.go, host/testdata/es_v6_index_template.json, host/testdata/es_v7_index_template.json, schema/elasticsearch/visibility/index_template_v6.json, schema/elasticsearch/visibility/index_template_v7.json, schema/elasticsearch/visibility/versioned/v1/index_template_v6.json, schema/elasticsearch/visibility/versioned/v1/index_template_v7.json, schema/elasticsearch/visibility/versioned/v1/reindex.painless, schema/elasticsearch/visibility/versioned/v1/reindex.sh
Add `ExecutionDuration` Elasticsearch field.
**Why?**
To support queries like `ExecutionDuration between '00:00:10' and '00:01:00'`.
Added unit test and manually.
No risks.
No.
=> Add ExecutionDuration ES field

common/persistence/elasticsearch/visibility_store.go, common/persistence/elasticsearch/visibility_store_read_test.go, common/persistence/persistenceInterface.go, common/persistence/visibilityInterfaces.go, common/persistence/visibilityStore.go, common/searchattribute/defs.go, host/testdata/es_v6_index_template.json, host/testdata/es_v7_index_template.json, schema/elasticsearch/visibility/index_template_v6.json, schema/elasticsearch/visibility/index_template_v7.json, schema/elasticsearch/visibility/versioned/v1/index_template_v6.json, schema/elasticsearch/visibility/versioned/v1/index_template_v7.json, service/history/transferQueueActiveTaskExecutor_test.go, service/history/visibilityQueueTaskExecutor.go
Add `StateTransitionCount` field to Elasticsearch index.
**Why?**
To support queries like `StateTransitionCount > 100`.
Modified unit tests, local canary run.
No risks.
No.
=> Add StateTransitionCount field to Elasticsearch index

schema/elasticsearch/visibility/versioned/v1/reindex.sh
Auto create custom search attributes fields in reindex script.
**Why?**
Better automation for reindex process.
Run manually.
No risks.
No.
=> Auto create custom search attributes fields in reindex script

temporal/server.go
typo: uknown -> unknown
**Why?**
There's no test.
No.
No.
=> typo: uknown

client/clientfactory.go, common/resource/bootstrapParams.go, common/resource/resourceImpl.go, temporal/server.go, temporal/server_option.go, temporal/server_options.go
Add ServerOption to use customized ClientFactory
**Why?**
This will make it possible to override client factory to have different customized logic.
Existing integration tests
No.
No.
=> option to use customized client factory

common/dynamicconfig/constants.go, common/namespace/attrValidator.go, common/namespace/attrValidator_test.go, common/namespace/const.go, common/namespace/handler.go, common/namespace/handler_GlobalNamespaceDisabled_test.go, common/namespace/handler_GlobalNamespaceEnabled_MasterCluster_test.go, common/namespace/handler_GlobalNamespaceEnabled_NotMasterCluster_test.go, common/namespace/handler_test.go, host/integrationbase.go, service/frontend/service.go, service/frontend/workflowHandler.go, tools/cli/namespaceUtils.go
Followup from #1615: add extra checks to ensure sane minimums.
**Why?**
To ensure replication can complete, this can't be too low for global namespaces.
Unit tests
=> Add hard minimum for retention duration

common/persistence/cassandra/errors.go, common/persistence/cassandra/errors_test.go
* Rewrite Cassandra error extraction util
* Add unit test
**Why?**
Cleaner implementation & additional tests
New tests
N/A
No
=> Reimplement Cassandra error extraction util

common/persistence/cassandra/cassandraPersistence.go, common/persistence/cassandra/errors.go
* Wire Cassandra layer using new error extraction util for update workflow & conflict resolve workflow APIs
**Why?**
Using new error handling logic which is easier to maintain
Existing tests
N/A
No
=> Wire Cassandra layer using new error extraction util

service/history/configs/config.go
Increase default bulk actions count from 200 to 500.
**Why?**
After running performance tests I believe that 500 is a better value for default bulk action count.
Performance tests.
No risks.
No.
=> Increase default bulk actions count from 200 to 500

schema/elasticsearch/visibility/versioned/v1/reindex.json, schema/elasticsearch/visibility/versioned/v1/reindex.sh, schema/elasticsearch/visibility/versioned/v1/rollback.json, schema/elasticsearch/visibility/versioned/v1/rollback.painless, schema/elasticsearch/visibility/versioned/v1/rollback.sh
Add `rollback.sh` for `reindex.sh`.
Use async mode reindexing.
Improve final report.
**Why?**
To have ability to revert Elasticsearch schema changes.
Run manually with big number of documents.
Reindex or rollback fail.
No.
=> Add rollback.sh for reindex.sh

common/log/tag/tags.go, service/frontend/workflowHandler.go
Ignore caller context cancellation error.
**Why?**
If request was cancelled but caller, then caller context will be also cancelled and we don't want to propagate this error back to the client and count against SLA.
No risks.
No.
=> Ignore caller context cancellation error

Makefile, common/persistence/elasticsearch/processor.go, common/persistence/elasticsearch/processor_test.go, config/dynamicconfig/development_es.yaml, schema/elasticsearch/visibility/cluster_settings_v6.json, schema/elasticsearch/visibility/cluster_settings_v7.json
Disable Elasticsearch index auto creation.
**Why?**
By default Elasticsearch silently create new index if it doesn't exists. This may lead to unexpected behaviour in case if user specify a wrong index name in the config.
Run locally.
No risks.
No.
=> Disable Elasticsearch index auto creation

common/headers/versionChecker.go
Update version for next release.
**Why?**
Increase version for next release. Version in master should be next release.
N/A
No
No
=> Bump version for next release

common/persistence/cassandra/cassandraPersistenceUtil.go, common/persistence/dataInterfaces.go, common/persistence/dataInterfaces_mock.go, common/persistence/persistence-tests/executionManagerTest.go, common/persistence/sql/execution_util.go, service/history/shard/context_impl.go, service/history/timerQueueActiveTaskExecutor_test.go, service/history/timerQueueProcessorBase.go, service/history/timerQueueStandbyTaskExecutor_test.go, service/history/workflow/mutable_state_util.go
* Rename GetVisibilityTimestamp to GetVisibilityTime
* Rename SetVisibilityTimestamp to SetVisibilityTime
* Fix lint errors
**Why?**
Code cleanup
N/A
N/A
No
=> Rename internal API names

service/worker/addsearchattributes/workflow.go, tools/cli/admin.go, tools/cli/app.go
Fix few typos.
**Why?**
N/A
N/A
No risks.
No.
=> Fix few typos

service/history/historyEngine.go, service/history/nDCTransactionMgr.go, service/history/nDCTransactionMgrForNewWorkflow.go, service/history/nDCTransactionMgrForNewWorkflow_test.go, service/history/nDCTransactionMgr_test.go, service/history/workflow/context.go, service/history/workflow/context_mock.go, service/history/workflow/context_util.go, service/history/workflowResetter.go, service/history/workflowResetter_test.go
* Split workflow context logic into 2 files for maintenance purpose
**Why?**
See above
N/A
N/A
No
=> Split workflow context logic into 2 files

service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/historyEngine3_eventsv2_test.go, service/history/historyEngine_test.go, service/history/timerQueueTaskExecutorBase_test.go, service/history/transferQueueActiveTaskExecutor_test.go
Delete dead code
**Why?**
Clean up
Run server, test a simple workflow, still works.
No
No
=> Remove unused history manager reference from history engine

common/persistence/execution_manager.go, service/history/workflow/context.go, service/history/workflow/context_util.go
* Extract persistence of history events & workflow snapshot into dedicated utils (create &| conflict resolve)
* Extract persistence of history events & workflow mutation into dedicated utils (update &| conflict resolve)
* Extract task notification into dedicated utils
**Why?**
Existing tests
N/A
No
=> Extract workflow & events persistence ops into dedicated util

service/history/workflow/context.go, service/history/workflow/context_util.go
* Extract & move notification of new tasks in dedicated util
* Extract & move notification of workflow progress in dedicated util
* Remove unused variable from workflow context
**Why?**
Existing tests
N/A
No
=> Extract workflow notification into dedicated util

service/history/historyEngine.go
* Remove current mutable state lock for start & signal with start workflow to decrease potential lock contention
**Why?**
See above
N/A
N/A
No
=> Remove current mutable state lock for start & signal with start workflow

common/persistence/elasticsearch/visibility_store.go, common/persistence/elasticsearch/visibility_store_read_test.go
Include root cause reasons in Elasticsearch error message.
**Why?**
Some Elasticsearch errors are very generic and actionable error reason is in details.
No risks.
No.
=> Include root cause reasons in Elasticsearch error message

service/matching/forwarder.go, service/matching/matcher.go
Reverts part of the cleanup change to keep code more understandable (nil receivers can be confusing).
**Why?**
unit tests
=> Revert part of Matching cleanup (a18bb3abd)

common/persistence/cassandra/cassandraPersistence.go, common/persistence/cassandra/factory.go, common/persistence/client/factory.go, common/persistence/execution_manager.go, common/persistence/history_manager.go, common/persistence/mock/store_mock.go, common/persistence/persistenceInterface.go, common/persistence/sql/execution.go, common/persistence/sql/execution_tasks.go, common/persistence/sql/execution_util.go, common/persistence/sql/factory.go, common/persistence/sql/history_store.go, common/persistence/tests/cassandra_test.go, common/persistence/tests/history_store_test.go, common/persistence/tests/mysql_test.go, common/persistence/tests/postgresql_test.go, tools/cli/adminCommands.go, tools/cli/adminDBCleanCommand.go, tools/cli/adminDBScanCommand.go
Rename WorkflowStore back to ExecutionStore
**Why?**
Not a good idea to use a different name. ExecutionStore/ExecutionManager is used every where.
Unit tests, integration tests.
No
No
=> Rename WorkflowStore to ExecutionStore

common/metrics/defs.go, common/rpc/interceptor/telemetry.go
Added explicit counter for user latency.
**Why?**
Better tracking and alert capabilities.
Local test, automated tests.
More load on metric system.
No
=> Report service user latency metric explicitly

go.mod, go.sum, tools/cli_next/app.go
Releases experimental `tctl next` (the current tctl is still the default)
Switches to `tctl next` if config version is set to `next`:
```bash
./tctl config set version next 
```
**Why?**
Experimental release of `tctl next` so users can start playing with and exploring the new UX
1. Verifying that the current tctl is still the default 
2. running `./tctl config set version next`
3. Checking that tctl now uses the new UX
4. switching back to current tctl by `./tctl config set version current` and verifying  is still available. Note: the value can be anything other than `next` to switch back to current version
not tested on windows. However if there is any issue with `config` feature, it's going to fallback to tctl v1 as the …
=> Release new tctl UX

common/dynamicconfig/constants.go, host/onebox.go, service/history/configs/config.go, service/history/historyEngine.go, service/worker/archiver/client_worker.go, service/worker/batcher/batcher.go, service/worker/parentclosepolicy/processor.go, service/worker/replicator/replicator.go, service/worker/scanner/scanner.go, service/worker/scanner/workflow.go, service/worker/service.go
* Add system worker execution size dynamic configs
* Add system worker poller count dynamic configs
* Remove unused dynamic configs
**Why?**
Allow user to config system worker execution size / poller count
N/A
N/A
No
=> Add system worker execution & poller dynamic configs

develop/buildkite/Dockerfile, docker/base-images/base-ci-builder.Dockerfile
Rebuilt build-ci-builder image.
**Why?**
Refresh fossa cli tool
This PR.
PR builds fail.
No
=> Update base-ci-builder image

Makefile, develop/buildkite/pipeline.yml
Patch fossa test.
**Why?**
Fossa suggested to add delay between analyze and test.
Local run, this PR tests.
N/A
No
=> Enable fossa test and add delay between analyze and test

go.mod, go.sum
* Upgrade gocql dependency for https://github.com/gocql/gocql/commit/9a3953d1826df998f14cc6857738786d1691a326
**Why?**
Upgrade dependency
N/A
N/A
No
=> Upgrade gocql dependency

service/history/shard/controller_impl.go
* Make sure shard acquirement channel will not be blocked by using buffered channel with enough size
**Why?**
Fix potential shard acquirement deadlock, which can cause startup issue
N/A
N/A
No
=> Make sure shard acquirement channel will not be blocked

service/history/service.go, service/history/shard/controller_impl.go
* Remove unnecessary shard controller prepare to stop logic in favor of existing stop logic
* Remove error prone check staus then adding message to channel in favor of select on both message channel & show down channel
**Why?**
Follow up of #1806 
Existing tests & CICD
N/A
No
=> Remove unnecessary shard controller prepare to stop logic

go.mod, go.sum
=> Update SDK to 1.9.0

Makefile, develop/buildkite/Dockerfile, docker/base-images/base-ci-builder.Dockerfile
Update fossa cli
Reduce delay between scan and test
**Why?**
N/A
No
=> Udpate fossa cli

common/persistence/cassandra/factory.go
Add new NewFactoryFromSession to create Cassandra data store factory from given session.
**Why?**
To avoid fatal error during start up.
Manual test.
No.
No.
=> NewFactory with given session

common/authorization/authorizer.go
Fixed API doc comment for `authorization.CallTarget.Request`.
**Why?**
Copy-paste error.
No testing needed
None
No
=> Fix API doc comment for authorization.CallTarget.Request

README.md
* Update link to buildkite badge
**Why?**
Stale link to buildkite badge image
N/A
N/A
N/A
=> Update link to buildkite badge

service/history/workflow/mutable_state_impl.go
* Execution time is not set correctly during continue as new (cron / retry)
**Why?**
Bugfix
Manual
N/A
No
=> Fix execution time not set correctly during continue as new

tools/cli/adminTaskQueueCommands.go, tools/cli/taskQueue.go, tools/cli/taskQueueCommands.go
Fix admin tq describe crashing if there are no pollers on the queue
**Why?**
No reason to bail out hard like that, and it is causing pipeline problems
Ran tctl directly
=> Fix crash when no pollers on task queue. Dedupe code.

common/metrics/defs.go, common/persistence/visibility/elasticsearch/processor.go, common/persistence/visibility/elasticsearch/processor_test.go
Add more metrics to Elasticsearch bulk processor.
**Why?**
To better visibility of ES bulkprocessor.
Locally.
No risks.
No.
=> Add more metrics to Elasticsearch bulk processor

service/matching/matchingEngine.go, service/matching/matchingEngine_test.go, service/matching/taskQueueManager.go, service/matching/taskQueueManager_test.go, service/matching/taskWriter.go
As the initial task ID block allocation storage call can block for tens
of seconds, we move that operation from the taskQueueManager itself down
into the taskWriter and put it on the taskWriter's goroutine.
**Why?**
taskQueueManager and related types (e.g. taskWriter, taskReader) can operate performing _just_ sync matching when their data access is unavailable. Thus we don't want to block their startup on a successful data operation. This moves the initial taskWriter ID block allocation off of the synchronous startup path for a taskQueueManager so that Start() can be fast and safe to call under the fat lock in matchingEngine. 
Changing the locking pattern in matchingEngine is also on the todo list but not in this PR. …
=> Streamline taskQueueManager startup

Makefile, common/config/config.go, common/persistence/cassandra/cassandraPersistenceTest.go, common/persistence/client/factory.go, common/persistence/client/fault_injection.go, common/persistence/client/fault_injection_errorgenerator.go, common/persistence/client/fault_injection_errorgenerator_test.go, common/persistence/persistence-tests/persistenceTestBase.go, common/persistence/sql/sqlPersistenceTest.go, develop/buildkite/pipeline.yml, host/flag.go, host/testcluster.go
Add option to inject failures in persistence api.
**Why?**
Open path for extra testing scenarios.
Manual/auto tests.
Instability in new integration tests.
no
=> Add fault injection for persistence API

service/matching/taskQueueManager.go, service/matching/taskWriter.go
Loop indefinitely in the taskWriter to obtain the first task ID block
**Why?**
The taskWriter isn't going to be able to write anything anyway until it
gets a task ID block so either we block in Start() or we block the first
write. This task ID block allocation happens in a background goroutine
in either case so it doesn't actually prefent Start() from returning.
Stuck looping for task ID block if retry logic is wrong
No
=> Spin loading initial taskWriter state in Start()

common/persistence/cassandra/version_checker.go
Expose method cassandra.CheckCompatibleVersion()
**Why?**
So this could be used by custom implementation of persistence.
No
No
=> Expose cassandra.CheckCompatibleVersion()

temporal/server.go
Close factory after use
**Why?**
To properly release resources used by factory.
No.
No.
=> Close factory after use

common/config/elasticsearch.go, common/persistence/visibility/elasticsearch/client/client.go, common/persistence/visibility/elasticsearch/client/client_factory.go, common/persistence/visibility/elasticsearch/client/client_v6.go, common/persistence/visibility/elasticsearch/client/client_v7.go, config/development_es.yaml, config/development_mysql-es.yaml, temporal/server.go, temporal/server_option.go, temporal/server_options.go
Add `closeIdleConnectionsInterval`, `enableSniff`, and `enableHealthcheck` to Elasticsearch config.
**Why?**
Closes #1830.
Local run.
Healthcheck is now disabled by default.
No.
=> Add closeIdleConnectionsInterval, enableSniff, and enableHealthcheck to Elasticsearch config

common/metrics/opentelemetry_user_scope.go, common/metrics/tally_user_scope.go
Fixed non-implemented methods in metrics UserScope.
**Why?**
Implemented missing functionality.
Manual/auto tests
N/A
=> Patch metrics UserScope

common/persistence/visibility/elasticsearch/errors.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/shard/context_util.go, service/history/visibilityQueueTaskExecutor.go
Remove retry from `DeleteExecution`.
**Why?**
Visibility task are retried on task processor level.
No risks.
No.
=> Remove retry from DeleteExecution

internal/goro/example_group_test.go, internal/goro/goro.go, internal/goro/goro_test.go, internal/goro/package.go
Adds docs and examples
**Why?**
Altruism? Hubris? Shame?
Manual
None
No
=> Adds docs and examples to the goro package

internal/goro/goro.go, internal/goro/group.go, internal/goro/package.go
Additional notes in documentation
**Why?**
A handful of suggestions came in after the previous documentation PR was already merged
n/a
No
No
=> Additional doc updates for package goro

host/continue_as_new_test.go
This test was reliably hitting a race condition: it was polling for a workflow task after checking that the workflow wasn't timed out yet, but because of matching delays, the workflow would often time out before it got a task, and then the test would block for the full 60s long poll.
The simplest fix is to add a buffer: it'll avoid polling within 2s of the workflow timeout. This still leaves 3s (out of the 5s timeout) to get through a few continue-as-new cycles without extending the test. 2s was determined empirically in local testing: 1s wasn't enough, and 2s let the test to finish quickly in 199/200 runs on my laptop.
**Why?**
So CI finishes faster.
It's a test.
It's a test.
=> Make TestContinueAsNewWorkflow_Timeout faster

common/metrics/defs.go, common/metrics/tags.go, common/persistence/visibility/elasticsearch/visibility_manager_metrics.go, common/persistence/visibility/visibility_manager_metrics.go, common/persistence/visibility/visibility_manager_sampling.go, common/persistence/visibility/visibility_manager_sampling_test.go
Unify visibility metrics for standard and advanced visibility.
**Why?**
Prepare refactoring PR with less code duplication.
No risks.
No.
=> Unify visibility metrics

common/persistence/cassandra/cassandraPersistence.go, common/persistence/dataInterfaces.go, common/persistence/dataInterfaces_mock.go, common/persistence/execution_manager.go, common/persistence/persistence-tests/persistenceTestBase.go, common/persistence/persistenceInterface.go, common/persistence/persistenceMetricClients.go, common/persistence/persistenceRateLimitedClients.go, common/persistence/sql/execution.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/workflow/transaction_impl.go
Merge persistence API for append history and conflict resolve
**Why?**
Make it possible to optimize these operations in one transaction.
Unit tests and integration tests.
No
No
=> Merge persistence API for append history and conflict resolve

common/resource/resource.go, common/resource/resourceImpl.go, common/resource/resourceTest.go, host/onebox.go, service/frontend/dcRedirectionHandler_test.go, service/frontend/service.go, service/frontend/workflowHandler.go, service/frontend/workflowHandler_test.go, service/history/handler.go, service/history/historyEngine.go, service/history/service.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/shard/context_util.go, service/history/timerQueueTaskExecutorBase_test.go, service/history/transferQueueActiveProcessor.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueProcessor.go, service/history/transferQueueStandbyProcessor.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/transferQueueTaskExecutorBase.go, service/history/visibilityQueueProcessor.go, service/history/visibilityQueueTaskExecutor.go, service/history/visibilityQueueTaskExecutor_test.go, service/matching/service.go, service/worker/service.go
Extract `VisibilityManager` from `Resources`. Also remove unused fields.
**Why?**
Refactoring for the next PR.
No risks.
No.
=> Extract VisibilityManager from Resources

service/history/historyEngine.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/query.go, service/history/workflowTaskHandler.go, service/history/workflowTaskHandlerCallbacks.go
* Update mutable state related code
* Update remaining history service logic
* Remove unnecessary error creation
**Why?**
Use internal error to indicate code bug / contract breach
N/A
N/A
No
=> Use internal error to indicate code bug / contract breach

common/metrics/defs.go
Removed unused metric def.
**Why?**
code cleanup.
compilation
N/A
No
=> Remove unused code

common/persistence/dataInterfaces.go, common/persistence/execution_manager.go, common/persistence/size.go, service/history/historyEngine2_test.go, service/history/historyEngine3_eventsv2_test.go, service/history/tests/vars.go, service/history/workflow/context.go, service/history/workflow/metrics.go, service/history/workflow/transaction_impl.go
* Add per change history event count diff to metrics reported
**Why?**
Adding more metrics
N/A
N/A
No
=> Add more metrics for mutable state update

common/config/config.go, common/config/persistence.go, common/constants.go, common/persistence/cassandra/version_checker.go, common/persistence/sql/version_checker.go, common/persistence/visibility/defs.go, common/persistence/visibility/store/elasticsearch/client/aws.go, common/persistence/visibility/store/elasticsearch/client/client_v6.go, common/persistence/visibility/store/elasticsearch/client/client_v7.go, common/persistence/visibility/store/elasticsearch/client/config.go, common/persistence/visibility/visibility_manager_dual.go, common/resource/bootstrapParams.go, common/util.go, go.mod, host/dynamicconfig.go, host/integrationbase.go, host/onebox.go, host/testcluster.go, service/frontend/adminHandler.go, service/frontend/adminHandler_test.go, service/frontend/service.go, service/history/configs/config.go, service/history/fx.go, service/history/service.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/task_refresher.go, temporal/server.go, tools/cassandra/version_test.go, tools/sql/clitest/versionTest.go
Move Elasticsearch client config to `elasticsearch/client` package. Also removed start server dependencies on dynamic config.
**Why?**
`config` package is splitted up to dedicated packages.
Existing tests, local run.
No risks.
No.
=> Move Elasticsearch client config to elasticsearch/client package

common/dynamicconfig/constants.go, common/rpc/rpc.go, common/rpc/test/rpc_localstore_tls_test.go, temporal/server.go
Add feature flag to enable Ringpop TLS.
**Why?**
To maintain backward compatibility with existing configuration after introducing Ringpop TLS in #1902.
No risks.
No.
=> Add feature flag to enable Ringpop TLS

common/persistence/client/factory.go, common/persistence/client/fx.go, common/resource/fx.go, common/resource/resource.go, common/resource/resourceImpl.go, common/resource/resourceTest.go, go.mod, host/onebox.go, service/history/fx.go, temporal/server.go
Initialize resource via DI.
**Why?**
Migrate to Uber/Fx
local/automated tests
History service doesn't initialize correctly.
No
=> Initialize resource via DI

service/history/historyEngine_test.go, service/history/workflow/mutable_state_impl.go
Add more details as requested by SDK folks to invalid command attributes.
**Why?**
It would help SDK side to easier identify if the error is due to SDK bug or user code.
updated unit tests
No
No
=> Add more details to invalid command attributes error

go.mod, go.sum, service/frontend/workflowHandler.go
Add `persistence_store` and `visibility_store` to `GetClusterInfo` API.
**Why?**
Expose more info in `GetClusterInfo` API that could be useful for WebUI.
No risks.
No.
=> Add persistence/visibility store info to GetClusterInfo

common/searchattribute/validator.go, common/searchattribute/validator_test.go, host/elasticsearch_test.go
Improve invalid search attribute error message.
**Why?**
Make error message more verbose.
No risks.
No.
=> Improve invalid search attribute error message

service/history/historyEngine.go, service/history/nDCActivityReplicator.go, service/history/nDCActivityReplicator_test.go, service/history/nDCHistoryReplicator.go, service/history/nDCTransactionMgr.go, service/history/queueProcessor.go, service/history/replicatorQueueProcessor.go, service/history/taskProcessor.go, service/history/timerQueueProcessorBase.go, service/history/timerQueueTaskExecutorBase.go, service/history/transferQueueTaskExecutorBase.go, service/history/visibilityQueueTaskExecutor.go, service/history/workflow/cache.go, service/history/workflow/cache_test.go, service/history/workflowResetter.go, service/history/workflowTaskHandlerCallbacks.go
Make `workflow.Cache` an interface.
**Why?**
So it is possible to provide different implementation for workflow cache.
Unit tests and integration tests.
No risks.
No.
=> Make workflow.Cache interface

service/history/fx.go, service/history/handler.go, service/history/historyEngine.go, service/history/service.go, service/history/workflow/cache.go, service/history/workflow/fx.go
Use DI to get the provider function to create new workflow cache.
**Why?**
Make it possible to inject different workflow cache implementation. 
Manual test
No
No.
=> Use DI to inject new cache provider

service/history/commandChecker.go, service/history/commandChecker_test.go, service/history/workflowTaskHandler.go
* Add SDK commands sequence validation & UT
**Why?**
Add additional checking for new SDKs
New tests
N/A
No
=> Add SDK commands sequence validation

common/metrics/defs.go, common/persistence/visibility/store/elasticsearch/processor.go, common/persistence/visibility/store/elasticsearch/processor_test.go
Add `elasticsearch_bulk_processor_duplicate_request` metric.
**Why?**
Better visibility of advanced visibility :smiley: .
No risks.
No.
=> Add elasticsearch_bulk_processor_duplicate_request metric

common/tasks/task.go
* Make compare function easy to use for task key
**Why?**
More functionality to task key type
Existing tests
N/A
No
=> Make compare function easy to use for task key

common/namespace/cache.go, common/namespace/cache_mock.go, common/namespace/cache_test.go, common/namespace/testconstructors.go, service/history/historyEngine.go, service/history/nDCTransactionMgr.go, service/history/nDCTransactionMgr_test.go, service/history/tests/vars.go, service/history/timerQueueActiveTaskExecutor_test.go, service/history/timerQueueStandbyTaskExecutor_test.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/visibilityQueueTaskExecutor.go, service/history/visibilityQueueTaskExecutor_test.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/task_generator.go, service/history/workflowResetter.go, service/matching/matchingEngine_test.go, service/matching/taskQueueManager_test.go
Dropped unused methods and remove unnecessary object cloning
**Why?**
Cleaning up the internals of namespace.Cache 
Existing unit tests - still no functional changes.
No
=> Namespace Cache refactor to take advantage of immutability

service/frontend/service.go
This reverts commit e80e8c1a0bac9a66f1973c1e3ae90a0373c1f342.
=> Revert "unlimited MaxConnectionAge (#1998)"

common/persistence/sql/sqlplugin/postgresql/plugin.go
Escape Postgres password in buildDSN function using
`url.QueryEscape(cfg.Password)`
**Why?**
To resolve [issue 903](https://github.com/temporalio/temporal/issues/903)
Tested the sample script with QueryEscape using [Go Playground](https://play.golang.org/)
The [buildDSN](https://github.com/temporalio/temporal/blob/e92adc008ca4a77463b3f479a9d53c6263d25228/common/persistence/sql/sqlplugin/postgresql/plugin.go#L105) function might fail
No
=> Escape password in connection url

service/matching/matcher.go
This change restores the earlier poll behavior wherein if poll forwarding
fails the request spends the remainder of its time in a blocking read
from the _local_ task queue channels.
**Why?**
I suspect this recursion is the root of some of the reports of increased
CPU utilization we've had from the field. A change in the 1.12 time
frame has consumer-side task polling recurse as a last resort. In cases
where forwarding fails, this recursion can approximate a spin until the
context timeout, resulting in high CPU utilization. Also there's the
potential to overflow the stack.
Existing unit tests (both implementations are functionally correct)
Low
Yes
=> Remove task polling recursion

service/worker/service.go
Fix tally import according to new go.mods
**Why?**
fix build
auto-tests
N/A
No
=> Patch tally import

common/namespace/handler.go, common/namespace/replicationTaskExecutor.go, common/persistence/cassandra/metadata_store.go, common/persistence/dataInterfaces.go, common/persistence/metadata_manager.go, common/persistence/persistence-tests/metadataPersistenceV2Test.go, common/persistence/persistenceInterface.go, common/persistence/sql/metadata.go, common/persistence/sql/sqlplugin/mysql/namespace.go, common/persistence/sql/sqlplugin/postgresql/namespace.go, common/persistence/sql/sqlplugin/sqlite/namespace.go, go.mod, go.sum, tools/cli/flags.go, tools/cli/namespaceCommands.go, tools/cli/namespaceUtils.go
Add ability to promote local namespace to global namespace. 
**Why?**
Make it possible to promote local namespace to global namespace.
Manual test locally with cassandra/mysql/postgres as persistence layer, verify update is write to database.
No
No.
=> Promote local namespace to global namespace

tools/cli/app.go
Unified CLI command usages section with a capital case
No
=> update cli usage

service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/task_generator.go, service/history/workflow/task_generator_mock.go, service/history/workflow/timer_sequence.go, service/history/workflow/timer_sequence_test.go
* Move history replication task generation logic to task generator
* Add generate last history replication task API
**Why?**
Code re-structure
Existing test
N/A
No
=> Move generation of replication task logic to task generator

service/frontend/adminHandler.go, service/worker/common/interface.go, service/worker/fx.go, service/worker/scanner/replication/fx.go, service/worker/scanner/replication/replication.go, service/worker/worker.go
Add gen-replication workflow for server worker role
**Why?**
This will be used to generate replication tasks for all workflows in a given namespace.
Tested locally
No
No
=> Add gen-replication workflow

host/testcluster.go, host/xdc/integration_failover_test.go
fix flaky test
**Why?**
use sdk worker to run integration test to avoid flakiness
integration test
no
no
=> fix flaky TestActivityHeartbeatFailover

service/history/shard/context_impl.go
Fix a potential use of nil pointer when stopping the shard.
**Why?**
If there was a failure in acquiring the lock during startup, this would crash here.
Will test with fault injection tests
=> Fix potential nil pointer use in shard context

client/clientfactory.go, common/clientCache.go
Refactor client (history/matching client etc) a little bit to add the knowledge needed to do fan out calls to all servers in the ring.
**Why?**
Plan to add new history API that will need to fan out to all history nodes.
Will test in follow up PRs.
No
No
=> Add GetAllAddresses to keyResolver

common/persistence/serialization/task_serializer.go, common/persistence/serialization/task_serializer_test.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_util.go
Set VisibilityTimestamp on ReplicationTask
**Why?**
So we can measure how far behind in time duration the acked replication task is.
Unit tests
No
No
=> Set VisibilityTimestamp on ReplicationTask

common/persistence/persistence-tests/executionManagerTest.go
* Always delete current execution before delete execution
**Why?**
=> Fix test behavior

common/persistence/execution_manager.go
* Initialize SignalRequestedIDs correctly as non-nil map
**Why?**
=> Initialize SignalRequestedIDs correctly

common/authorization/default_token_key_provider.go, common/config/config.go, docker/config_template.yaml
Added conditional statements to config_template.yaml to prevent empty values from being set by default.
Added code to check for and skip empty string values in `KeySourceURIs`.
**Why?**
Fixes #2134 
Unit tests, manually
I don't see much risk here
No
=> Add protection for empty JWT key source URIs

common/locks/priority_mutex_impl.go, common/locks/priority_mutex_test.go
* Add IsLocked to priority mutex & UT
**Why?**
More functionality to priority mutex
UT
N/A
No
=> Add IsLocked to priority mutex

common/locks/priority_mutex.go, common/locks/priority_mutex_impl.go, common/locks/priority_mutex_test.go
* Add try lock APIs to priority mutex
**Why?**
More functionality
UT
N/A
No
=> Add try lock APIs to priority mutex

host/xdc/integration_failover_test.go, service/history/handler.go, service/history/historyEngine.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
Implement GetReplicationStatus API
**Why?**
Implement GetReplicationStatus API
Integration test
No
No
=> Implement GetReplicationStatus

develop/buildkite/docker-compose.yml, develop/docker-compose/docker-compose.yml
Update development environment to PostgreSQL 13.5.
**Why?**
Keeping up to date with latest dependencies.
MySQL persistence might work incorrectly for the cases not covered with tests.
No.
=> Update development environment to PostgreSQL 13.5

develop/buildkite/docker-compose.yml, develop/buildkite/mysql-init/init.sql, develop/docker-compose/docker-compose.yml, develop/docker-compose/mysql-init/init.sql
Update development environment to MySQL 8.0.
**Why?**
Keeping up to date with latest dependencies.
MySQL persistence might work incorrectly for the cases not covered with tests.
No.
=> Update development environment to MySQL 8.0

client/history/client.go, common/clientCache.go
Add fan out to history client for GetReplicationStatus
=> Add fan out to history client for GetReplicationStatus

common/config/loader.go, common/dynamicconfig/file_based_client.go, common/ringpop/ringpop_test.go, go.mod, host/integrationbase.go, host/ndc/ndc_integration_test.go, host/xdc/elasticsearch_test.go, host/xdc/integration_failover_test.go
- Replace all gopkg.in/yaml.v2 to gopkg.in/yaml.v3
**Why?**
- Consistency in dependency
- Unit test
- No
- No
=> Use gopkg.in/yaml.v3 instead of v2

common/metrics/defs.go, common/metrics/opentelemetry_reporter.go, common/resource/bootstrapParams.go, common/resource/fx.go, common/resource/resourceImpl.go, common/rpc/encryption/localStoreTlsProvider.go, common/rpc/encryption/tlsFactory.go, host/onebox.go, service/frontend/fx.go, service/history/fx.go, service/matching/service.go, temporal/fx.go, temporal/server_impl.go, tools/cli/persistenceUtil.go
* Reduced dependencies on ServerOptions
* Make UserScope available to user extension providers
**Why?**
Onboarding uber/fx
Make UserScope available to user extensions.
Server is not initialized correctly.
no
=> Make UserScope available to user extension providers

temporal/fx.go
Handle missing metrics config
**Why?**
nil exception fix
N/A
N/A
=> Handle missing metrics config

service/history/historyEngine.go, service/worker/scanner/replication/fx.go, service/worker/scanner/replication/replication.go
Added wait step to force replication workflow
=> Wait replications

common/metrics/defs.go, common/persistence/cassandra/cluster_metadata_store.go, common/persistence/client/fault_injection.go, common/persistence/clusterMetadataStore.go, common/persistence/dataInterfaces.go, common/persistence/dataInterfaces_mock.go, common/persistence/mock/store_mock.go, common/persistence/persistence-tests/clusterMetadataManagerTest.go, common/persistence/persistence-tests/setup.go, common/persistence/persistenceInterface.go, common/persistence/persistenceMetricClients.go, common/persistence/persistenceRateLimitedClients.go, common/persistence/sql/cluster_metadata.go, common/persistence/sql/sqlplugin/cluster_metadata.go, common/persistence/sql/sqlplugin/mysql/cluster_metadata.go, common/persistence/sql/sqlplugin/postgresql/cluster_metadata.go, common/persistence/sql/sqlplugin/sqlite/cluster_metadata.go, temporal/fx.go
Add List Cluster Metadata API
**Why?**
To get all cluster metadata for dynamically update
Integration tests
N.A
N.A
=> Add List Cluster Metadata API

common/namespace/handler.go, common/rpc/interceptor/namespace_validator.go, go.mod, go.sum, tools/cli/flags.go, tools/cli/namespaceCommands.go, tools/cli/namespaceUtils.go
Allow namespace state update via tctl
**Why?**
Provide a way to update namespace state
Manual test using TCTL command
No
No
=> Allow namespace state update

temporal/fx.go
Extract common struct for service provider args
**Why?**
Cleanup DI struct
N/A
No
=> Extract common struct for service provider args

common/resource/fx.go, tools/cli/admin.go, tools/cli/adminClusterCommands.go, tools/cli/flags.go
1. Add enable remote connection tctl
2.  Fix client factory DI
**Why?**
To support add remote connection and disable the connection by default
Local tctl test
N/A
N/A
=> Add enable remote connection tctl

common/resource/fx.go, service/worker/fx.go, service/worker/service.go
Make Worker service use service name tagged logger.
**Why?**
instill common behavior.
manual/auto-tests
N/A
No
=> Use proper logger for worker service

common/namespace/handler.go, common/rpc/interceptor/namespace_validator.go, common/rpc/interceptor/namespace_validator_test.go
Allow delete deprecated namespace.
**Why?**
Should be able to delete deprecated namespace.
Unit test
No
No
=> Namespace state update fix

common/persistence/cassandra/mutable_state_store.go, common/persistence/dataInterfaces.go, common/persistence/operationModeValidator.go, common/persistence/operationModeValidator_test.go, common/persistence/sql/execution.go, common/persistence/sql/execution_util.go, service/history/workflowResetter.go, service/history/workflowResetter_test.go
* Remove unnecessary CreateWorkflowModeContinueAsNew mode
**Why?**
Reduce unnecessary code complexity
UT
N/A
No
=> Remove unnecessary CreateWorkflowModeContinueAsNew mode

schema/mysql/v57/temporal/schema.sql, schema/mysql/v57/temporal/versioned/v1.7/no_start_version.sql, schema/postgresql/v96/temporal/schema.sql, schema/postgresql/v96/temporal/versioned/v1.7/no_start_version.sql
* Fix forward / backward compatibility issue introduced by #2236
**Why?**
See above
N/A
N/A
No
=> Fix forward / backward compatibility issue

common/persistence/operationModeValidator.go, common/persistence/operationModeValidator_test.go, common/persistence/persistence-tests/executionManagerTest.go, common/persistence/tests/cassandra_test.go, common/persistence/tests/execution_mutable_state_test.go, common/persistence/tests/mysql_test.go, common/persistence/tests/postgresql_test.go, common/persistence/tests/util.go, common/persistence/workflowStateStatusValidator.go, common/persistence/workflowStateStatusValidator_test.go, go.mod, go.sum
* Add new test suits for workflow creation
* Allow creation of completed workflow
**Why?**
More tests
More tests
N/A
No
=> Add dedicated persistence execution mutable state integration tests

Makefile, docker/base-images/Makefile, docker/base-images/README.md
Add `Makefile` targets for `arm64`.
**Why?**
To support build of cross-platform docker images.
Run and build images locally.
No risks.
No.
=> Add Makefile targets for arm64

common/metrics/defs.go, service/matching/config.go, service/matching/matcher.go, service/matching/matcher_test.go, service/matching/matchingEngine.go, service/matching/taskQueueManager.go, service/matching/taskReader.go, service/matching/taskWriter.go
1) Added metrics to track task queue load / unload counter
2) Add namespace tag to task queue manager logger
3) simplify the namespace/metricScope init logic for taskQueueManager.
**Why?**
Add more metrics, more logging, and simplify code.
Local test, curl http://localhost:8000/metrics and verify metrics emitted as expected, verify logging on task queue load / unload logging include namespace tag.
No
No
=> Matching cleanup

common/namespace/replicationTaskExecutor.go, common/persistence/cassandra/queue_store.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/errors.go, common/persistence/operationModeValidator.go, common/persistence/sql/queue.go, service/frontend/workflowHandler.go, service/history/consts/const.go, service/history/nDCBranchMgr.go, service/history/nDCConflictResolver.go, service/history/nDCHistoryReplicator.go, service/history/nDCStateRebuilder.go, service/history/nDCTransactionMgrForExistingWorkflow.go, service/history/nDCTransactionMgrForNewWorkflow.go, service/history/nDCWorkflow.go, service/history/replicatorQueueProcessor.go, service/history/timerQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/workflow/context.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/task_generator.go, service/history/workflowResetter.go, service/worker/scanner/history/scavenger.go
fixed many typos, all the same word ... encounter => encountered
I just can't stand it any more!
=> only message typos

common/persistence/dataInterfaces.go, common/persistence/persistence-tests/executionManagerTest.go, common/persistence/persistence-tests/persistenceTestBase.go, common/persistence/persistence-tests/shardPersistenceTest.go, common/persistence/persistenceInterface.go, common/persistence/shard_manager.go, common/persistence/tests/execution_mutable_state.go, service/history/shard/context_impl.go, service/history/shard/context_testutil.go, service/history/shard/controller_test.go
Add (Go) context that lives for lifetime of shard context
**Why?**
Useful to track shard lifetime
=> Add shard lifetime context

common/resource/resourceImpl.go
Fix onebox worker shutdown.
**Why?**
Proper worker shutdown.
Allow for fast tests rerun.
manual/auto tests.
N/A
=> Fix onebox worker shutdown

service/worker/scanner/replication/fx.go, service/worker/scanner/replication/replication.go
Add namespace-handover workflow
**Why?**
to handover namespace
This is not hookup yet. Will test in follow up PR.
No
No
=> handover workflow

service/history/transferQueueActiveTaskExecutor.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go
* Use history event as signal payload data reducing mutable state size
NOTE: this PR is part 1 due to forward / backward compatibility
**Why?**
Reducing mutable state size
N/A
N/A
No
=> Use history event as signal payload data

host/workflow_visibility_test.go
Add workflow type to the query filter. 
**Why?**
There could be other integration test running from the same integrationSuite, query only based on the StartTime filter could include workflows from other tests.
Local tests
No
No.
=> Fix flaky TestVisibility

common/metrics/defs.go
Use correct histogram type for dimensionless
**Why?**
fix bug
N/A
N/A
=> Use correct histogram type for dimensionless

common/metrics/opentelemetry_scope.go
Add custom buckets to rollup metrics
**Why?**
N/A
N/A
N/A
=> Add custom buckets to rollup metrics

common/metrics/tally_client.go, common/metrics/tally_scope.go
Patch tally histogram reporting
**Why?**
Bug fix
N/A
N/A
=> Report tally histogram correctly

service/frontend/errors.go, service/frontend/workflowHandler.go
* Add UTF-8 validation to namespace
* Add UTF-8 validation to workflow ID
**Why?**
Necessary input validation
N/A
N/A
No
=> Add additional UTF-8 validation

common/persistence/visibility/store/standard/visibility_store.go
Rename `simpleStore` to `standardStore` for consistency.
**Why?**
This struct was somehow missed in the previous refactoring.
N/A
No risks.
No.
=> Rename simpleStore to standardStore

common/future/future.go, common/future/future_impl.go, common/future/future_test.go, common/future/ready_future_impl.go
* Add future implementation & UT
* Add ready future implementation
**Why?**
Adding building blocks
UT
N/A
No
=> New future implementation

common/headers/versionChecker.go
* Increase version for 1.15 development
**Why?**
New version development
N/A
N/A
No
=> Increase version for 1.15 development

common/persistence/sql/history_store.go
* Remove deprecated SQL side pagination code path
**Why?**
Code cleanup
N/A
N/A
No
=> Remove deprecated code path

common/metrics/opentelemetry_client.go, common/metrics/opentelemetry_scope.go, common/metrics/tally_client.go
Changed root scope to support rollup metrics.
**Why?**
correct rollup metrics reporting
N/A
N/A
=> Fix rollup metrics aggregation

host/activity_test.go
Rewrote TestActivityHeartbeatDetailsDuringRetry test.
**Why?**
Deflake test.
`clear && go test ./host -race -count=50 -failfast -v --run TestClientIntegrationSuite/TestActivityHeartbeatDetailsDuringRetry`
N/A
No
=> Deflake/rewrite TestActivityHeartbeatDetailsDuringRetry test

common/persistence/persistenceMetricClients.go, common/persistence/persistenceRateLimitedClients.go, common/persistence/visibility/visiblity_manager_metrics.go
Cherry pick patch.
**Why?**
Patch persistence stress resilience.
Automated tests
Incorrect error handling.
This is a hotfix.
=> Revert persistence rate limit error type (#2312)

common/headers/versionChecker.go
Update CLI and Server versions for release.
=> Update CLI and Server versions in version checker

host/client_integration_test.go
- Fix flaky Test_ActivityTimeouts
**Why?**
- The test is flaky: https://buildkite.com/temporal/temporal-public/builds/2111#_
- Please check the inline comment for why the test is flaky.
- Run the test locally
N/A
No.
=> Fix flaky Test_ActivityTimeouts

common/namespace/handler.go, common/namespace/handler_test.go
Update namespace failover version when namespace promote from local to global.
**Why?**
Promote namespace from local to global needs to increment failover version.
New unit test
No
No
=> Update failover version for namespace promote

common/cluster/metadata.go, common/cluster/metadata_test.go
Use page token when list cluster metadata from DB
**Why?**
Use pagination token to list all cluster metadata
Added new unit tests
=> Use page token when list cluster metadata from DB

common/persistence/tests/execution_mutable_state.go
* Initialize shard correctly in ExecutionMutableStateSuite
**Why?**
Update tests
N/A
N/A
N/A
=> Initialize shard correctly in ExecutionMutableStateSuite

temporal/server_option.go
Fixes a few typos, copy-paste errors and standardizes comments for the ServerOptions. There are no functional changes in this PR.
=> Cleans up some comments for ServerOptions

service/history/tieredStorageQueueTaskExecutor.go
Return correct error message in tiered storage queue
**Why?**
Return correct error message in tiered storage queue
=> Use error message for tiered storage

service/history/shard/controller_impl.go
Unload shard when ownership lost notified by ringpop
**Why?**
Eagerly unload shard after ownership lost.
eye_ball
No
No
=> Unload shard when ownership lost

service/history/historyEngine.go
Use latest worker identify for pending activity.
**Why?**
If activity is retrying, use the current worker identity instead of last attempt's worker identity.
eye_ball
No
No
=> Use latest worker identity for pending activity

common/persistence/tests/execution_mutable_state.go, common/persistence/tests/util.go
I'd like to be able to experiment with additional tests base on the existing test suite by extending and reusing them.
ran tests
minimal risk ... changing only test code
=> make tests more extensible/reusable by other tests

common/persistence/cassandra/cluster_metadata_store.go, common/persistence/client/fault_injection.go, common/persistence/clusterMetadataStore.go, common/persistence/dataInterfaces.go, common/persistence/dataInterfaces_mock.go, common/persistence/mock/store_mock.go, common/persistence/persistence-tests/clusterMetadataManagerTest.go, common/persistence/persistenceInterface.go, common/persistence/persistenceMetricClients.go, common/persistence/persistenceRateLimitedClients.go, common/persistence/sql/cluster_metadata.go, common/persistence/sql/sqlplugin/cluster_metadata.go, common/persistence/sql/sqlplugin/mysql/cluster_metadata.go, common/persistence/sql/sqlplugin/postgresql/cluster_metadata.go, common/persistence/sql/sqlplugin/sqlite/cluster_metadata.go, config/development_active.yaml, config/development_other.yaml, config/development_standby.yaml, schema/cassandra/temporal/schema.cql, schema/mysql/v57/temporal/schema.sql, schema/postgresql/v96/temporal/schema.sql, schema/sqlite/v3/temporal/schema.sql, temporal/fx.go
Remove cluster metadata dual write
**Why?**
New cluster metadata will be configured from TCTL admin tool. Only current cluster metadata from config from the static config file.
Not new code added. Depends on existing unit tests.
N/A
=> Remove cluster metadata dual write

service/worker/migration/replication.go
Add basic rate limit to force replication workflow
**Why?**
To avoid generating too much load to server when doing force replication
local test
No
No
=> add basic rate limit to force replication workflow

temporal/fx.go
* Favor config value in enable global namespace
Cherry pick "Favor local config value on enable global namespace (#2368)"
**Why?**
Cherry pick "Favor local config value on enable global namespace (#2368)"
=> Favor local config value on enable global namespace (#2368)

common/cache/cache.go, common/cache/lru.go, common/cache/lru_test.go
* Remove element removal function since this functionality is not used & brings complexity
**Why?**
Remove unused functionality & reduce code complexity
N/A
N/A
No
=> Remove removal function away from LRU cache for simplicity

service/history/workflow/cache_test.go, service/history/workflow/history_builder_test.go
* Add additional mutable state concurrent access & pinning tests
**Why?**
More tests
N/A
N/A
No
=> Add more tests to history cache

common/cluster/fx.go, common/resource/fx.go
Wire up cluster metadata in start fx DI
**Why?**
Cluster metadata doesn't start a refresh loop.
Local test
Yes.
=> Wire up cluster metadata in start fx DI

host/archival_test.go
Verify run IDs in archival int test
**Why?**
Verify if the flaky tests are caused by race condition between executions
Integration tests
NA
NA
=> Verify run IDs in archival int test

common/persistence/sql/history_store.go
* Correctly handle retry of history node / tree query 
**Why?**
Close #2408
N/A
N/A
No
=> Handle SQL duplicate key case

.github/workflows/trigger-publish.yml
Corrected the name of the branch on which to trigger the docker image build pipeline
**Why?**
old branch wouldn't trigger the pipeline
=> Correct branch name in docker image build pipeline

common/metrics/defs.go, service/history/replicationTaskProcessor.go, service/history/replicationTaskProcessor_test.go
Add metrics on replication lag and replication task apply latency
**Why?**
To monitor cross cluster replication replication stack latency and task execution latency.
No
=> Add metrics on replication lag and replication task apply latency

common/cluster/metadata.go, common/cluster/metadata_test.go, common/dynamicconfig/constants.go, common/persistence/persistence-tests/persistenceTestBase.go, common/resource/resourceImpl.go, host/dynamicconfig.go, host/testdata/xdc_integration_es_clusters.yaml, host/testdata/xdc_integration_test_clusters.yaml, host/xdc/elasticsearch_test.go, host/xdc/integration_failover_test.go, tools/cli/namespaceUtils.go
Update XDC integration test to use add remote cluster api
**Why?**
New release only support adding remote clusters via admin api.
Integration tests
No
=> Update XDC integration test to use add remote cluster api

host/taskpoller.go
Retry with empty task response
**Why?**
Race condition on workflow task complete and activity task polling from matching.
I cannot repro the failure test on my on local. From the previous failure logs, I see the test polled empty task response.
N/A
No
=> Integration test: retry with empty task response

common/cluster/metadata.go, common/namespace/mutate.go, common/namespace/namespace_migration_util.go, service/history/historyEngine2_test.go, service/history/historyEngine3_eventsv2_test.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/test_util.go
* Add new namespace conversion util handling namespace promotion & buffered events case
* Remove unused StartTransactionSkipWorkflowTaskFail
**Why?**
Handle NDC namespace local -> global & buffered event case
N/A
N/A
No
=> Handle buffered events during namespace migration/promotion

go.mod, go.sum
Update SDK version to 1.13.0
**Why?**
New version release
Traditional tests
None
No
=> Update SDK version to 1.13.0

service/history/historyEngine.go
Use namespace function to check active cluster
**Why?**
Use namespace function to check active cluster for local namespace.
rely on existing tests
No
=> Use namespace function to check active cluster

host/ndc/ndc_integration_test.go, host/xdc/integration_failover_test.go
Added more tests for namespace promotion
**Why?**
=> Add more test for namespace promotion

Dockerfile, develop/buildkite/Dockerfile
Upgrade base images to the latest version.
**Why?**
Close #2451.
No risks.
It might be depending on investigations.
=> Upgrade base images

service/history/commandChecker.go
Update error message.
**Why?**
=> Update invalid command message

common/metrics/defs.go, service/history/nDCTaskUtil.go
=> Emit history task skipped metric

common/log/panic_test.go
Properly capture panic when panic obj is not error
**Why?**
=> convert panic when it is not error

common/dynamicconfig/constants.go, common/metrics/defs.go, service/history/configs/config.go, service/history/workflow/workflow_task_state_machine.go
- Emit workflow task attempt stats
**Why?**
- Better visibility for stuck workflows
N/A, just emitting metric
no.
=> Emit workflow task attempt stats

.github/workflows/goreleaser.yml
Update go version of goreleaser to to 1.17.6.
**Why?**
To keep parity with other buiilds.
N/A
No risks.
Maybe.
=> Update go version of goreleaser to to 1.17.6

common/namespace/handler.go, common/namespace/handler_GlobalNamespaceEnabled_MasterCluster_test.go, common/namespace/handler_test.go, common/namespace/transmissionTaskHandler.go
Generate namespace replication only with 2+ clusters
**Why?**
Generate namespace replication only with 2+ clusters
=> Generate namespace replication only with 2+ clusters

service/history/workflow/metrics.go
* Fix metrics scope bug when emitting mutable state metrics
**Why?**
Bugfix
N/A
N/A
No
=> Fix metrics scope

common/config/config.go, common/rpc.go, common/rpc/encryption/localStoreTlsProvider.go, common/rpc/encryption/testDynamicTLSConfigProvider.go, common/rpc/encryption/tlsFactory.go, common/rpc/rpc.go, common/rpc/test/rpc_common_test.go, common/rpc/test/rpc_localstore_tls_test.go, temporal/server_impl.go
Add config and handling for remote cluster certificate
**Why?**
So that multi-cluster can work with certs
Local multi-cluster setup
No
No
=> Add config and handling for remote cluster cert

develop/docker-compose/docker-compose.darwin.yml, develop/docker-compose/docker-compose.linux.yml, develop/docker-compose/docker-compose.windows.yml, develop/docker-compose/docker-compose.yml
Add Temporal Web 2.0 to development docker-compose.
**Why?**
Dog food new UI at http://localhost:8080.
Run locally and try.
No risks.
No.
=> Add Temporal Web 2.0 to development docker-compose

service/matching/taskQueueManager_test.go
Fix flaky matching AddTaskStandby test
**Why?**
=> Fix flaky matching AddTaskStandby test

temporal/fx.go
Refactor the server fx module a bit on server options.
**Why?**
To move the server options providers into one place.
local run
No
No
=> provide serverOptions as fx.Out struct

temporal/fx.go
Preserve the info when updating is_global_namespace_enabled
**Why?**
Preserve the info when enable global namespace to have search attributes and version info
Local tests
Yes
=> Preserve the info when enable global namespace

service/history/handler.go
Check is global namespace enabled in handler
**Why?**
The replicate remote clusters may mismatch with the is global namespace enabled
Local test
=> Check is global namespace enabled in handler

client/history/metricClient.go, client/matching/metricClient.go, service/history/replicationTaskProcessor.go
Reduce unnecessary logging
**Why?**
Too many logging pollute the log and make it harder to use. 
=> reduce unnecessary logging

common/headers/versionChecker.go
Bump server and cli version to 1.15.1
**Why?**
For v1.15.1 patch
=> Bump server and cli version to 1.15.1

common/persistence/tests/execution_mutable_state.go
* Add / update tests to execution store
**Why?**
More tests
N/A
N/A
No
=> Update execution tests

service/history/shard/context_impl.go
* Correctly release shard lock 
**Why?**
Bugfix
N/A
N/A
Yes
=> Fix potential shard deadlock issue

common/headers/versionChecker.go
V1.14.6 bump
**Why?**
V1.14.6 bump
=> V1.14.6 bump

common/headers/versionChecker.go
Prepare 1.15.2 patch
**Why?**
Prepare 1.15.2 patch
=> Prepare 1.15.2 patch

service/history/shard/context_impl.go
Continue to delete workflow execution if namespace is deleted.
**Why?**
Under some circumstances there is a chance of race condition between delete namespace workflow and delete workflow execution task processor. If visibility was successfully deleted but one of other steps failed, delete namespace workflow will consider this namespace empty and delete it. Workflow execution may "hang" undeleted in this case.
Existing tests, but it is hard to emulate this particular edge case.
No risks.
No.
=> Continue to delete workflow execution if namespace is deleted

common/rpc/test/rpc_localstore_tls_test.go
Added a test for #2563.
**Why?**
Test coverage.
It's a new test
None
No
=> Add a test for #2563

service/history/shard/context_impl.go
- Check shard context state inside write lock
- Remove errorByState()
**Why?**
- Currently the state check is done in a separate read lock and the state may change after the read lock is release and before the operation write lock is grabbed. 
- If shard state change to finished (unloaded), s.engine will become nil and we may hit NPE issue can accessing s.engine.
Existing test, eyeballing
Maybe
=> Fix shard context error state check

service/history/replicatorQueueProcessor.go
Copy version history before returning.
**Why?**
Version history might append new items.
Yes
=> Copy version history before returning

go.mod, go.sum, service/frontend/workflowHandler.go, service/frontend/workflowHandler_test.go
Server capabilities update
**Why?**
For SDK usage
Local
None
No
=> Update server capabilities for sdk usage

service/history/historyEngine.go
De-duplicate reapply event
**Why?**
If the reapply event already exist in the active cluster, it will be reapplied correctly. No need to trigger the reapply from a passive cluster.
=> De-duplicate reapply event

.github/workflows/goreleaser.yml, CONTRIBUTING.md, Makefile, develop/buildkite/Dockerfile, go.mod, go.sum
Upgrade go version to 1.18.
**Why?**
Keep go version up to date.
Buildkite build.
No risks.
No.
=> Upgrade go version to 1.18

service/worker/deletenamespace/deleteexecutions/activities.go, service/worker/deletenamespace/deleteexecutions/workflow_test.go, service/worker/deletenamespace/reclaimresources/activities.go, service/worker/deletenamespace/reclaimresources/workflow_test.go
- Fix merge confict.
**Why?**
- Last commit had merge confict and this fails build on master.
- Build locally
=> Fix merge conflit

service/worker/replicator/namespace_replication_message_processor.go
=> Suppress nonuseful namespaceReplicationMessageProcessor log

common/dynamicconfig/constants.go, common/log/tag/tags.go, common/metrics/defs.go, go.mod, go.sum, service/frontend/errors.go, service/frontend/fx.go, service/frontend/interface_mock.go, service/frontend/operator_handler.go, service/frontend/operator_handler_test.go, service/frontend/service.go, service/worker/addsearchattributes/workflow.go, service/worker/deletenamespace/deleteexecutions/config.go, service/worker/deletenamespace/workflow.go, service/worker/deletenamespace/workflow_test.go
Add DeleteNamespace API.
**Why?**
Expose DeleteNamespace feature.
Invoke API manually but will add intergration tests later.
No risks.
No.
=> Add DeleteNamespace API

common/rpc/interceptor/telemetry.go
=> Fix namespace not active error metric

develop/docker-compose/docker-compose.yml
Upgrade web images to the latest versions.
**Why?**
Keep web UI up to date.
N/A
No risks.
No.
=> Upgrade web images to the latest versions

.vscode/launch.json, common/backoff/retry_test.go, common/persistence/persistence-tests/setup.go, common/persistence/persistence-tests/sqlite_test.go, common/persistence/sql/cluster_metadata.go, common/persistence/sql/sqlplugin/cluster_metadata.go, common/persistence/sql/sqlplugin/mysql/cluster_metadata.go, common/persistence/sql/sqlplugin/postgresql/cluster_metadata.go, common/persistence/sql/sqlplugin/sqlite/cluster_metadata.go, common/persistence/tests/sqlite_test.go
Adding sqlite persistence tests
**Why?**
Because validation is good
Heh
=> Add sqlite persistence tests

common/persistence/cassandra/cluster_metadata_store.go, common/persistence/cassandra/history_store.go, common/persistence/cassandra/matching_task_store.go, common/persistence/cassandra/metadata_store.go, common/persistence/cassandra/mutable_state_store.go, common/persistence/cassandra/mutable_state_task_store.go, common/persistence/cassandra/queue_store.go, common/persistence/cassandra/shard_store.go, common/persistence/visibility/store/standard/cassandra/visibility_store.go
- Use passed in context for cassandra persistence store impl
**Why?**
- Enforce persistence timeout, instead of always timeout after 10s
-  We may see an increased number of persistence context timeout error as now a lower context timeout will be used.
- No.
=> Persistence context part 8: cassandra store

common/persistence/visibility/store/elasticsearch/visibility_store.go
- Use passed in context for elasticsearch persistence store impl
**Why?**
- Enforce persistence timeout, instead of always timeout after 8s
-  We may see an increased number of persistence context timeout error as now a lower context timeout will be used.
- No.
=> Persistence context part 9: elasticsearch visibility store

common/persistence/execution_manager.go
* Improve mem allocation efficiency
**Why?**
N/A
N/A
N/A
N/A
=> Improve mem efficiency when mutating workflow

common/channel/shutdown_once.go
* Add a new broadcast shutdown channel
**Why?**
Add commonly used utility
N/A
N/A
=> Add broadcast shutdown channel

service/history/shard/context_impl.go
Move the call to cancel shard lifecycle context earlier. 
**Why?**
=> Cancel context earlier

common/log/tag/tags.go, service/history/nDCTaskUtil.go, service/history/queueProcessor.go, service/history/timerQueueProcessorBase.go, service/history/transferQueueTaskExecutorBase.go, service/matching/matchingEngine.go
- Log NotFound error for transfer task processing
**Why?**
-  For debugging task processing logic
- Yes
=> Log NotFound error for transfer task processing

service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/shard/context_test.go, service/history/shard/context_testutil.go, service/history/shard/controller_impl.go
* Simplify history engine init & wait logic using future
**Why?**
Simplify logic 
N/A
N/A
N/A
=> Simplify history engine init & wait logic

common/headers/versionChecker.go
=> Prepare 1.16.1 patch

common/persistence/sql/sqlPersistenceTest.go, common/persistence/sql/sqlplugin/sqlite/plugin.go, common/persistence/sql/sqlplugin/tests/sqlite_test.go, common/persistence/tests/sqlite_test.go, config/development_sqlite.yaml
Revert sqlite DSN construction back to file uri
**Why?**
More flexible
Local testing
No
N/A
=> Revert back to using file URI for sqlite dsn

service/history/commandChecker.go, service/history/commandChecker_test.go, service/history/workflowTaskHandler.go
Fail workflow task with BadSearchAttributes cause if search attributes are wrong.
**Why?**
To provide more detailed error message.
No risks.
No.
=> Fail workflow task with BadSearchAttributes cause if search attributes are wrong

go.mod
Remove duplicated `require` section from `go.mod`.
**Why?**
For the sake of the beauty and symmetry.
N/A
No risks.
No.
=> Remove duplicated require section from go.mod

common/tasks/benchmark_test.go, common/tasks/interleaved_weighted_round_robin.go, common/tasks/interleaved_weighted_round_robin_test.go, service/history/queues/scheduler.go
- Implement Task executable scheduler interface
**Why?**
- Host level worker pool implementation
- Eyeballing
- N/A, not used anywhere
No.
=> Task executable scheduler implementation

develop/docker-compose/docker-compose.yml
Update UI to `0.10.6`.
**Why?**
Keep dependencies up to date.
N/A
No risks.
No.
=> Update UI to v0.10.6

.goreleaser.yml, Makefile, develop/buildkite/pipeline.yml
Disable cgo by default.
**Why?**
After #2704 is merged cgo is not needed anymore.
Build locally and run.
No risks.
No.
=> Disable cgo by default

service/history/handler.go, service/history/shard/controller_impl.go, service/history/shard/controller_test.go, service/matching/matchingEngine.go
* Include current shard time to APIs below
* StartWorkflowExecutionResponse
* RecordWorkflowTaskStartedResponse
* RecordActivityTaskStartedResponse
**Why?**
see #2743 
N/A
N/A
N/A
=> Make shard accessible to history handler

client/history/client.go, common/serviceerror/shardOwnershipLost.go, service/history/handler.go, service/history/shard/controller_impl.go
* Fix shard ownership lost error owner & current host mismatch issue
**Why?**
Bugfix
N/A
N/A
N/A
=> Improve history client retry logic

develop/docker-compose/docker-compose.yml
=> Update UI to v0.11.0

common/locks/condition_variable_test.go
=> Fix conditional variable test

common/headers/versionChecker.go
Added UI as a client in version checker
**Why?**
allows UI to pass the version to Temporal
Verified that the UI requests still pass and version checker doesn't throw unsupported version error 
=> Support UI as a client in version checker

service/history/nDCActivityReplicator.go, service/history/timerQueueActiveTaskExecutor.go, service/history/workflow/mutable_state_impl.go
=> Add debugging logs

service/history/timerQueueActiveTaskExecutor.go
=> Activity retry debug

service/history/nDCActivityReplicator.go
=> Log request

common/metrics/metric_client_tests.go, common/metrics/opentelemetry_client.go, common/metrics/otel_metric_test_utility.go, common/metrics/tally_client.go
Use same root tags for system scope and user scope
**Why?**
system and user scope should share the same root tags and the metrics with same name can be aggregated.
Unit tests
=> Use same root tags for system scope and user scope

common/log/lazy_logger.go, service/history/queues/executable.go, service/history/tasks/utils.go
- Lazy init task executable logger
**Why?**
- Improve memory efficiency
- Tested locally.
- no.
- no.
=> Lazy init task executable logger

service/history/transferQueueActiveTaskExecutor.go
Remove `UNSPECIFIED` failed cause.
**Why?**
SDKs can't handle `UNSPECIFIED` failed cause properly therefore it is better to return an error and keep retrying rather than setting `UNSPECIFIED` failed cause.
No risks.
No.
=> Remove UNSPECIFIED failed cause

service/history/historyEngine.go, service/history/historyEngine2_test.go
- Reload mutable state if child workflow initiated event is found on current branch but child started event has not been recorded.
**Why?**
- Existing mutable state staleness check only checks for initiated event and return not found error if later found there's no started event. However, if the staleness of the mutable state is between initiated event and started event, then there's no reload for mutable state and a not found error is returned to the child workflow's close execution transfer task. Upon getting the error, close execution task treat it as an expected error and ack the task. Then parent workflow will get stuck, keep waiting for the child workflow to complete.
- Added new unit test
- Risk is low, since only the …
=> Fix mutable state stale check for recordChildExecutionCompleted

develop/docker-compose/docker-compose.yml
=> Bump UI to v0.13.1

service/history/timerQueueActiveProcessor.go, service/history/timerQueueProcessor.go, service/history/transferQueueActiveProcessor.go, service/history/transferQueueProcessor.go
- Fix scheduler npe for timer failover processor
- Use host level pool in timer/transfer failover processor if exists
**Why?**
=> Fix scheduler NPE for timer failover processor

service/history/shard/context_impl.go
* Enforce timeout when updating shard
**Why?**
IO to DB should have timeout
N/A
N/A
No
=> Enforce timeout when updating shard

common/metrics/defs.go
Metric name.
**Why?**
It's a typo. 
No. 
Grafana dashboards broken or alerting system no more sending alerts for WorkflowTaskAttempt. 
No.
=> Fix WorkflowTaskAttempt metric definition

Makefile, README.md, develop/buildkite/pipeline.yml
Remove fossa from buildkite
**Why?**
=> Remove fossa from buildkite

service/matching/matchingEngine.go
Do not load sticky task queue for add task or query if they are not already loaded.
Only sticky poller could trigger sticky queue to be loaded. 
**Why?**
SDK might not reset sticky, which means when history push sticky task, the worker might already long gone. In that case, loading task queue manager adds no value and consumes system resource.
=> Do not load sticky queue for add task

service/history/transferQueueProcessor.go
=> Fix transfer standby queue processor locking

service/history/shard/controller_impl.go
* Adding more protection for shard shutdown
**Why?**
More shard shutdown porotection
N/A
N/A
N/A
=> Guarantee shard shutdown

CONTRIBUTING.md
Updated tctl details in Contributing.md
**Why?**
installation process for tctl has changed
=> Update tctl details in contributing.md

develop/buildkite/Dockerfile
Update `base-ci-builder` image to `1.5.0`.
**Why?**
Keep dependencies up to date. See https://github.com/temporalio/docker-builds/pull/51 for details.
N/A
No risks.
No.
=> Update base-ci-builder to 1.5.0

service/history/historyEngine.go
=> Fix record child completion mutable state stale check

common/namespace/handler.go, common/namespace/handler_test.go
=> Changed RegisterNamespace to initialize new Namespaces in REPLICATION_STATE_NORMAL

service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/historyEngine3_eventsv2_test.go, service/history/historyEngine_test.go, service/history/nDCActivityReplicator_test.go, service/history/timerQueueActiveTaskExecutor_test.go, service/history/timerQueueStandbyTaskExecutor_test.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/visibilityQueueTaskExecutor_test.go, service/history/workflowTaskHandlerCallbacks.go, service/history/workflowTaskHandlerCallbacks_test.go
* Use workflow consistency checker for all APIs
**Why?**
Unify API logic
Existing tests
N/A
N/A
=> Use workflow consistency checker for all APIs

.vscode/launch.json
Updated vscode launch debug scripts 
**Why?**
they were broken due to file name changes
debugged Temporal in vscode
=> Update vscode launch scripts

service/frontend/workflowHandler.go
Update comment to reflect the actual behavior of RequestCancelWorkflowExecution
**Why?**
=> Update comments for RequestCancelWorkflow

common/persistence/execution_manager.go, service/history/timerQueueProcessor.go
- Fix an issue introduced by last https://github.com/temporalio/temporal/pull/2907. 
- Remove extra debug println
**Why?**
=> Fix timer task completion

service/history/replication/task_processor.go
=> Fix npe for dlq retry policy

common/persistence/persistence-tests/shardPersistenceTest.go, common/persistence/tests/execution_mutable_state.go, common/persistence/tests/execution_mutable_state_task.go
* Limit max number of shards used by tests
**Why?**
N/A
N/A
N/A
N/A
=> Limit max number of shards used by tests

develop/docker-compose/docker-compose.yml, service/worker/deletenamespace/reclaimresources/activities.go, service/worker/deletenamespace/reclaimresources/activities_test.go, service/worker/deletenamespace/reclaimresources/workflow.go, service/worker/deletenamespace/reclaimresources/workflow_test.go, service/worker/deletenamespace/workflow_test.go
Improve `deletenamespace` workflow logging.
**Why?**
To get better visibility of what is going on.
Run manually.
No risks.
No.
=> Improve deletenamespace logging

service/worker/replicator/replicator.go
Fix cluster metadata remove
**Why?**
No need to access remote cluster when cluster is removing.
Local test
=> Fix cluster metadata remove

common/enums/defaults.go, service/frontend/workflowHandler.go, service/history/historyEngine.go, service/history/workflowResetter.go
Clean up reset reapply default value.
**Why?**
Consolidate "set default" logic in one file and call it from frontend only which is responsible for validation.
Exitsing tests.
No risks.
No.
=> Clean up reset reapply default value

service/history/timerQueueStandbyProcessor.go, service/history/transferQueueActiveProcessor.go
=> Fix task rescheduler metric scope

README.md
Updated UI Readme to v2
**Why?**
moving towards v2
=> Update UI readme to v2

develop/docker-compose/docker-compose.yml
Bump UI to v2.0.0.
**Why?**
To dog food latest version.
N/A
No risks.
No.
=> UI bump to v2.0.0

service/history/tasks/key.go, service/history/tasks/key_test.go, service/history/tasks/range.go, service/history/tasks/range_test.go, service/history/tasks/task.go
- Add task key & range definition and related methods
**Why?**
- Building blocks for multi-cursor queue
- Unit test
- N/A, not used
- No
=> Multi-cursor queue components: task key and range

temporal/fx.go
Moving handler instantiation
**Why?**
Case for when metrics are not configured
Locally
None
No
=> moving handler instantiation to allow noop reporter for autosetup

common/sdk/factory.go, go.mod, go.sum, host/client_integration_test.go, host/xdc/integration_failover_test.go
=> Update SDK to v1.15.0

develop/docker-compose/docker-compose.cdc.yml, service/worker/deletenamespace/reclaimresources/workflow.go
Fix error details bug in `deletenamespace` workflow.
**Why?**
Error details were not propagated properly.
Manually.
No risks.
No.
=> Fix error details bug in deletenamespace workflow

common/metrics/defs.go, common/persistence/persistenceMetricClients.go, common/rpc/interceptor/telemetry.go, service/frontend/adminHandler.go, service/frontend/operator_handler.go
Make persistence error with tag a new metric.
**Why?**
To keep old metric untouched.
eye balls.
No
No
=> Error with tag metrics

service/history/shard/context_impl.go, service/history/workflow/delete_manager.go
* Do not retry while holding the shard lock
**Why?**
See above
N/A
N/A
N/A
=> Do not retry while holding the shard lock

develop/docker-compose/docker-compose.yml
=> Bump UI to v2.0.1

common/metrics/events.go, common/metrics/events_client.go, common/metrics/events_reporter.go, common/metrics/events_scope.go, common/metrics/events_scope_test.go, common/metrics/events_test.go, common/metrics/events_userscope.go, common/metrics/events_userscope_test.go, common/metrics/otel_event_handler.go, common/metrics/tally_event_handler.go
changes to function receivers for possible performance issue
**Why?**
because throughput dropped!
dev environment testing
None
No
=> mitigate performance issue with userscope

develop/docker-compose/docker-compose.cdc.yml
Bump UI version.
**Why?**
Keep dev dependencies up to date.
N/A
No risks.
No.
=> Update docker-compose.cdc.yml to UI v2.0.1

common/metrics/config.go, common/metrics/otel_metric_provider.go, common/metrics/otel_metric_provider_test.go, common/metrics/tally_metric_provider.go, common/metrics/tally_metric_provider_test.go, common/metrics/userscope_test.go
tag exclusion (filtering) fix
**Why?**
bug
added unit test
None
No
=> Correct tag exclusion logic and add tests.

common/metrics/config.go
Use correct scope constructor as default
**Why?**
startup panic
locally
No
No
=> use correct scope constructor

develop/docs/tracing.md
Added some extra tips to the tracing doc
**Why?**
Everyone loves tips
n/a
n/a
no
=> Some instrumentation tips for tracing

develop/docs/tracing.md
The headers stanza should be a child of spec, not connection. Dedent 2
spaces.
**Why?**
Incorrect docs are bad
Copy/pasted into development.yaml and ran server
n/a
n/a
=> Tracing docs typo

service/matching/matchingEngine.go
* Remove unnecessary debug log
**Why?**
See above
N/A
N/A
N/A
=> Remove unnecessary debug log

service/frontend/fx.go
Reorder frontend rate limiter.
**Why?**
Per namespace rate limiter should be applied before overall rate limiter to avoid one namespace exhaust quota for everyone.
eye balls
No
Yes
=> Reorder frontend rate limiter

service/history/shard/context_impl.go
This function was moved to different package
**Why?**
Fix build
unit tests
=> Fix merge collision between #3078 and #3074

common/constants.go, service/frontend/errors.go, service/frontend/operator_handler.go, service/frontend/operator_handler_test.go
Add protection against system namespace delete.
**Why?**
To prevent accident deletion of system namespace.
New unit test.
No risks.
No.
=> Add protection against system namespace delete

common/membership/ringpop.go
Replace hand-written retry loop with backoff.ThrottleRetry.
**Why?**
Code clarity and reuse.
Unit tests
I tried to match the existing behavior exactly, but it's possible there's some subtle difference.
no
=> Use backoff.ThrottleRetry in ringpop

temporal/server_impl.go
When running multiple services in one process, start them in parallel.
**Why?**
This helps ringpop behave better in development: if we find old membership records from a previous instance of the process, the first service to initialize try to contact the other services, which haven't started yet, and block. If we start everything in parallel, it will succeed instead.
Manual testing
Multiple services in one process is generally only used in development. This should have no effect on production.
no
=> Start services in parallel

service/history/shard/context_impl.go
- Expand comment about shard [re]acquire behavior
- Change initial interval to 1 second
**Why?**
Help people understand confusing code
Existing tests
=> Expand comment on shard context acquire behavior

service/history/historyEngine.go, service/history/workflow/query_registry.go, service/history/workflow/query_registry_test.go
Refactor: rename `termCh` to `completionCh`.
**Why?**
Leftover after #3000 rename.
N/A
No risks.
No.
=> Refactor: rename termCh to completionCh

api/historyservice/v1/service.pb.go, proto/internal/temporal/server/api/historyservice/v1/service.proto
Updating to match https://github.com/temporalio/api/pull/195
=> Update DeleteWorkflowExecution description

common/metrics/defs.go, service/frontend/dcRedirectionHandler.go, service/history/workflowTaskHandler.go
- Emit metric for activity eager execution
**Why?**
- Better visibility for activity eager execution feature
- Yes
=> Emit metric for activity eager execution

common/rpc/interceptor/telemetry.go
Don't count PermissionDenied as ServiceFailure.
Also stopping emitting special per error type metrics. Instead, rely on the generic service_error_with_type that contains error_type tag.
**Why?**
Simplify error metrics.
Manual test to verify.
No
No
=> Don't count PermissionDenied as ServiceFailure

service/history/queues/priority_assigner.go
- Use namespace name instead of namespaceID when filtering high priority rps dynamicconfig.
**Why?**
- Otherwise, the value can't be tuned for each namespace.
=> Fix task rate limiting

service/history/shard/controller_impl.go
* Randomize shard ownership assertion starting position to avoid hot spot
**Why?**
See above
N/A
N/A
N/A
=> Randomize shard ownership assertion starting position

service/history/replication/task_processor_manager.go
Bring back the task complete loop
**Why?**
Got deleted by accident.
=> Bring back the task complete loop

service/history/queues/reader_group.go, service/history/queues/reader_group_test.go
- Add a utility for managing multiple readers.
**Why?**
- Utility components
- Unit test
- No. Code not wired up yet.
- No.
=> Multi-cursor: reader group

tools/tdbg/commands.go, tools/tdbg/task_queue_commands.go, tools/tdbg/tdbg_commands.go, tools/tdbg/util.go
- Implement tdbg AdminDeleteWorkflow
**Why?**
- Implement tdbg AdminDeleteWorkflow
- Tested locally
- No.
=> Implement tdbg AdminDeleteWorkflow

service/history/queues/convert.go, service/history/queues/queue_base.go, service/history/queues/queue_base_test.go, service/history/queues/queue_immediate.go, service/history/queues/queue_scheduled.go, service/history/queues/queue_scheduled_test.go, service/history/queues/reader.go, service/history/queues/reader_group.go, service/history/queues/reader_group_test.go, service/history/queues/reader_test.go
- Multi-cursor: queue implementation
**Why?**
- Multi-cursor impl
- Unit test
- Code not wired up yet.
- No
=> Multi-cursor: queue implementation

tools/tdbg/commands.go, tools/tdbg/tdbg_commands.go
* Add admin workflow rebuild command
**Why?**
This PR only creates the admin command, business logic is tested [here](https://github.com/temporalio/temporal/blob/master/host/admin_test.go)
N/A
N/A
N/A
=> Add admin workflow rebuild command

service/history/historyEngine.go, service/history/historyEngineFactory.go
* Pass in workflow cache to history engine initialization
* Pass in workflow consistency checker to history engine initialization
**Why?**
N/A
N/A
N/A
=> Code restructure

common/metrics/defs.go, common/persistence/dataInterfaces.go, common/persistence/dataInterfaces_mock.go, common/persistence/history_manager.go, common/persistence/persistenceMetricClients.go, common/persistence/persistenceRateLimitedClients.go, common/resource/resourceTest.go, service/history/api/create_workflow_util.go, service/history/api/signalwithstart/signal_with_start_workflow.go, service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/nDCHistoryReplicator.go, service/history/nDCStateRebuilder.go, service/history/nDCStateRebuilder_test.go, service/history/timerQueueActiveTaskExecutor.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/mutable_state_rebuilder.go, service/history/workflow/mutable_state_rebuilder_mock.go, service/history/workflow/mutable_state_rebuilder_test.go, service/history/workflow/test_util.go, service/history/workflow/util.go, service/history/workflowTaskHandler.go
=> Make branch token initialization part of data persistence interface

service/history/tasks/predicates.go, service/history/tasks/predicates_test.go
=> Fix task predicates operation

service/history/historyEngine2_test.go, service/history/historyEngine3_eventsv2_test.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go
Refactor transient workflow task creation.
**Why?**
Prerequisite for the new feature.
No risks.
No.
=> Refactor transient workflow task creation

service/history/queueProcessor.go
- Fix queue processor throttling logic
**Why?**
- Backoff timer should be cleared after firing
- Yes.
=> Fix queue processor throttling logic

common/log/zap_logger.go, host/elasticsearch_test.go, host/integrationbase.go, host/namespace_delete_test.go, host/test_cluster.go, host/testdata/integration_namespace_cluster.yaml, host/util.go, host/xdc/elasticsearch_test.go, host/xdc/integration_failover_test.go
Add `DeleteNamespace` integration test.
**Why?**
To cover basic delete namespace functionality.
Run new tests.
No risks.
No.
=> Add DeleteNamespace integration test

service/history/transferQueueActiveTaskExecutor.go
Only load close event if needed during transfer close task.
**Why?**
Existing code would always load close event during transfer close task, but it is only needed if it is a child workflow.
=> Only load complete event if need to report to parent

service/history/transferQueueStandbyTaskExecutor.go
Avoid loading close event for transfer standby closed task.
**Why?**
Only load close event in transfer standby processor for close task if needed.
=> Only load complete event for standby close task if needed

common/authorization/frontend_api.go
Added recently added read-only APIs to the list.
**Why?**
For `IsReadOnlyNamespaceAPI()` to return correct results.
No testing necessary
None
No
=> Add read-only APIs that've been added since the original list was created

service/history/shard/context_impl.go
- Add comment for newDetachedContext
**Why?**
- https://github.com/temporalio/temporal/pull/3194#discussion_r939722872
- N/A
- N/A
- No.
=> Add comment for newDetachedContext

service/history/queueProcessor.go, service/history/queues/executable.go, service/history/queues/metrics.go, service/history/queues/queue_base.go, service/history/queues/queue_scheduled.go, service/history/timerQueueActiveProcessor.go, service/history/timerQueueProcessorBase.go, service/history/timerQueueStandbyProcessor.go, service/history/transferQueueActiveProcessor.go, service/history/transferQueueStandbyProcessor.go, service/history/visibilityQueueProcessor.go
- Emit currently defined metrics for multi cursor queue implementation so that existing dashboard won't be break.
**Why?**
=> Multi-cursor: metrics

go.mod, go.sum
Upgrade gocql version to v1.2.0
**Why?**
Upgrade gocql version to v1.2.0
=> Upgrade gocql version to v1.2.0

common/metrics/defs.go, common/persistence/cassandra/history_store.go, common/persistence/client/fault_injection.go, common/persistence/dataInterfaces.go, common/persistence/dataInterfaces_mock.go, common/persistence/execution_manager.go, common/persistence/history_manager.go, common/persistence/mock/store_mock.go, common/persistence/persistenceInterface.go, common/persistence/persistenceMetricClients.go, common/persistence/persistenceRateLimitedClients.go, common/persistence/persistenceRetryableClients.go, common/persistence/sql/history_store.go, service/history/nDCHistoryReplicator.go, service/history/nDCHistoryReplicator_test.go
=> Delegate branch token serialization/deserialization to store layer

common/persistence/history_manager.go, common/persistence/persistenceInterface.go
=> Propagate original branch token to persistence history store layer

host/onebox.go
Remove unused code (unused as of #2680, as far as I can tell)
**Why?**
Unused code
Integration tests
=> Remove GetRingpopChannel from integration tests

service/history/shard/context_impl.go
* Prevent concurrent workflow execution deletion
**Why?**
Decrease concurrent workflow deletion, reducing possible contention
N/A
N/A
N/A
=> Prevent concurrent workflow execution deletion

common/persistence/history_manager.go, service/history/timerQueueTaskExecutorBase.go
=> Address context.TODO in history service

common/dynamicconfig/constants.go, service/frontend/fx.go, service/frontend/service.go
Evenly distribute frontend global rate limit
**Why?**
Change dynamic config FrontendGlobalNamespaceRPS behavior to match with its comment.
=> Evenly distributed frontend global rps limit

service/history/workflowResetter.go
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
Error message in workflow resetter is confusing.
=> Small update to workflow resetter confusing error message

common/metrics/defs.go, common/persistence/persistenceMetricClients.go, common/persistence/persistenceRateLimitedClients.go, common/persistence/visibility/visiblity_manager_metrics.go, go.mod, go.sum
Add RESOURCE_EXHAUSTED_CAUSE_PERSISTENCE_LIMIT
**Why?**
To differentiate persistence from other resource exhausted causes.
=> Add resource exhausted cause persistence limit

common/dynamicconfig/constants.go, common/headers/versionChecker.go, common/headers/versionChecker_test.go, common/rpc/interceptor/sdk_version.go, common/rpc/interceptor/sdk_version_test.go, service/frontend/service.go, service/frontend/workflowHandler.go
1. Move client version check to interceptor
2. Delete enable client version check flag
**Why?**
This belongs to client sdk interceptor
=> Move client version check to SDK interceptor

common/persistence/visibility/store/elasticsearch/client/bulk_processor_v7.go, common/persistence/visibility/store/elasticsearch/client/bulk_service_v7.go, common/persistence/visibility/store/elasticsearch/client/client.go, common/persistence/visibility/store/elasticsearch/client/client_factory.go, common/persistence/visibility/store/elasticsearch/client/client_mock.go, common/persistence/visibility/store/elasticsearch/client/client_v7.go, common/persistence/visibility/store/elasticsearch/processor_test.go, common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go, common/resource/resourceTest.go
Follow up refactor from deprecating ES6 (#3184). This PR merges ES v7 client interface with the general ES client interface and cleans up some code related to ES6.
**Why?**
ES6 has been deprecated, and this PR cleans up the code a little bit.
`make unit-test && make integration-test`
No risk.
No.
=> Merge ES ClientV7 with base client interface

common/metrics/defs.go, common/persistence/persistenceMetricClients.go, common/persistence/visibility/visiblity_manager_metrics.go, common/rpc/interceptor/telemetry.go
Remove some redundant error metrics
**Why?**
Rely on service_error_with_type and persistence_error_with_type
=> Remove redundant error metrics

common/namespace/registry.go
Increase page size from 200 to 1000
**Why?**
Reduce overhead for cells with larger numbers of namespaces
unit tests
=> Increase page size for namespace registry refresh

service/history/queues/monitor.go, service/history/queues/queue_base.go, service/history/queues/reader.go, service/history/queues/reader_group.go, service/history/queues/reader_group_test.go
- Stop empty queue readers. 
- Do not persist state for empty readers
**Why?**
- Added test. also tested in test cluster
=> Multi-cursor: stop empty readers

service/history/queues/executable.go
=> Fix task executable metrics tags

service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go
1. Fix describe completed batch operation counter
2. Update describe batch operation reason read from memo
**Why?**
Need to show processed workflow metrics in completed operations.
New canary test and unit test
=> Fix describe completed batch operation counter

service/worker/fx.go, service/worker/migration/fx.go, service/worker/scheduler/fx.go
Use default `FrontendClientProvider` from `resource` in worker
**Why?**
The local special case isn't necessary after #3160 and #3280
run locally, integration test, will test in production
=> Simplify worker fx

service/history/api/signalwithstartworkflow/api.go, service/history/api/signalwithstartworkflow/convert.go, service/history/api/signalwithstartworkflow/signal_with_start_workflow.go, service/history/api/signalwithstartworkflow/signal_with_start_workflow_test.go, service/history/api/startworkflow/api.go, service/history/historyEngine.go
* Move start workflow to api package
**Why?**
N/A
N/A
N/A
=> Move start workflow to api package

go.mod, go.sum
Update `go.temporal.io/sdk` to the latest version.
**Why?**
To include recent changes.
N/A
No risks.
No.
=> Update go.temporal.io/sdk to latest version

develop/buildkite/Dockerfile
Update base CI image version.
**Why?**
Keep CI base builder image up to date and in sync with server builder.
Buildkite.
No risks.
No.
=> Update base CI image version

service/history/transferQueueActiveTaskExecutor.go, service/worker/parentclosepolicy/workflow.go
Remove deprecated namespace fields from `parentclosepolicy.Request`.
**Why?**
Fields were deprecated some time ago and are not used anymore.-
No risks.
No.
=> Remove deprecated namespace fields from parentclosepolicy.Request

cmd/server/main.go
Fixing var name from snake case to camel case.
**Why?**
N/A
`make bins`
No.
No
=> Fix snake case to camel case

service/history/api/recordactivitytaskheartbeat/api.go, service/history/historyEngine.go
* Move record activity task heartbeat to api package
**Why?**
N/A
N/A
N/A
=> Move record activity task heartbeat to api package

service/history/api/requestcancelworkflow/api.go, service/history/handler.go, service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
* Move request cancel workflow to api package
**Why?**
N/A
N/A
N/A
=> Move request cancel workflow to api package

service/history/api/terminateworkflow/api.go, service/history/handler.go, service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
* Move terminate workflow to api package
**Why?**
N/A
N/A
N/A
=> Move terminate workflow to api package

service/history/api/respondactivitytaskcanceled/api.go, service/history/handler.go, service/history/historyEngine.go, service/history/historyEngine_test.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
* Move respond activity task canceled to api package
**Why?**
N/A
N/A
N/A
=> Move respond activity task canceled to api package

common/dynamicconfig/constants.go, service/frontend/operator_handler.go, service/frontend/operator_handler_test.go, service/frontend/service.go, service/worker/deletenamespace/deleteexecutions/config.go, service/worker/deletenamespace/deleteexecutions/workflow.go, service/worker/deletenamespace/deleteexecutions/workflow_test.go, service/worker/deletenamespace/errors/errors.go, service/worker/deletenamespace/reclaimresources/workflow.go, service/worker/deletenamespace/reclaimresources/workflow_test.go, service/worker/deletenamespace/workflow.go, service/worker/deletenamespace/workflow_test.go
Delay namespace deletion.
**Why?**
After all workflow execution are deleted, namespace is deleted immediately but some auxiliary systems might require it to stay longer.
No risks.
No.
=> Delay namespace deletion

service/history/api/signalworkflow/api.go, service/history/handler.go, service/history/historyEngine.go, service/history/historyEngine_test.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
* Move signal workflow to api package
**Why?**
N/A
N/A
N/A
=> Move signal workflow to api package

go.mod, go.sum
=> Update Go SDK to v1.17.0

common/persistence/persistenceMetricClients.go
- Get visibility into how many persistence requests each namespace has so we can know how to set the per-ns persistence rps limit.
**Why?**
=> Add namespace tag for persistence metrics

client/admin/metric_client.go, client/admin/metric_client_gen.go, client/frontend/metric_client.go, client/frontend/metric_client_gen.go, client/history/metric_client.go, client/history/metric_client_gen.go, client/matching/metric_client.go, client/matching/metric_client_gen.go, cmd/tools/rpcwrappers/main.go
- Add namespace tag for service client metrics
**Why?**
- For visibility & debugging.
=> Add namespace tag for service client metrics

common/metrics/defs.go, service/history/api/create_workflow_util.go, service/history/commandChecker.go
Add dedicated metrics for memo size
**Why?**
To capture memo size metrics from both commands and StartWorkflow/SignalWithStart APIs
=> Add separate metrics for memo size

service/history/workflow/context.go
Remove unused history event check
**Why?**
Remove unused history event check
This is future function
=> Remove unused history event check

client/history/metric_client.go
=> Exclude taskAlreadyStarted error from history client logging

go.mod, go.sum
Update to tagged api version v1.12.0
**Why?**
=> Update api version to v1.12.0

common/persistence/cassandra/history_store.go, common/persistence/dataInterfaces.go, common/persistence/sql/history_store.go, common/persistence/tests/history_store.go, service/worker/scanner/history/scavenger.go, service/worker/scanner/history/scavenger_test.go
=> Allow NewHistoryBranch optionally specify branch id

service/worker/pernamespaceworker.go
SDK workers can encounter errors after Start returns successfully, e.g. namespace not found. In these cases, the per-namespace worker manager would not retry creating the worker. This unifies retry handling for pre-Start and post-Start errors.
**Why?**
For now, it is actually likely to get a namespace not found error on a newly created namespace for ~10s, because each node refreshes its namespace registry on a separate timer, so DescribeNamespace may succeed but the first Poll may fail.
unit test, plus a bunch of manual testing
=> Retry after sdk post-Start errors in per-namespace worker

service/history/queues/executable.go
=> Fix task schedule latency metric

service/worker/scheduler/workflow.go, service/worker/scheduler/workflow_test.go
Fix to scheduler workflow logic: process signals (update, patch) after pending actions for the preceding time interval.
**Why?**
Processing signals immediately after waking up means that an update would apply retroactively in the past, which could be confusing.
unit test
=> Process signals later in scheduler workflow

service/history/queues/executable.go
=> Fix task reschedule policy

common/payload/payload.go
Better var names in `MergeMapOfPayload`.
**Why?**
The function is not symmetrical, so giving better var names to prevent confusion.
`make unit-test`
No.
No.
=> Rename parameters of `MergeMapOfPayload`

service/history/visibilityQueueTaskExecutor.go, service/history/visibilityQueueTaskExecutor_test.go
Same as https://github.com/temporalio/temporal/pull/3402 but fixes a merge issue with the last one.
=> Retry attempts to delete open visibility records (#3402)

common/rpc/interceptor/telemetry.go
Fix action metrics
**Why?**
Action metrics is broken by https://github.com/temporalio/temporal/pull/3125.
This PR is to fix that regression. 
We will need a follow up PR to add an integration test to prevent this from happening again.
Local manual test.
No
No
=> Fix action metrics

common/persistence/dataInterfaces.go, service/history/workflow/mutable_state_impl.go
=> Supply optionally configured workflow settings as hints

service/history/replication/ack_manager.go
=> Add logging to replication

service/history/replication/ack_manager.go
=> Use branch token from version history

common/persistence/visibility/manager/visibility_manager.go, common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/visibility_store.go, common/persistence/visibility/visibility_manager_impl.go, common/searchattribute/defs.go, schema/elasticsearch/visibility/index_template_v7.json, schema/elasticsearch/visibility/versioned/v4/index_template_v7.json, schema/elasticsearch/visibility/versioned/v4/upgrade.sh, service/history/visibilityQueueTaskExecutor.go
Add history size to ES when workflow closes.
There will be follow up PR to add the same to other visibility persistence implementation, and to return such info from list workflow API.
**Why?**
=> Index history size when workflow closes

service/history/api/recordchildworkflowcompleted/api.go, service/history/api/retry_util.go, service/history/handler.go, service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
* Move record child workflow completed to api package
**Why?**
N/A
N/A
N/A
=> Move record child workflow completed to api package

service/history/api/verifychildworkflowcompletionrecorded/api.go, service/history/handler.go, service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
* Move verify child workflow completion recorded to api package
**Why?**
N/A
N/A
N/A
=> Move verify child workflow completion recorded to api package

common/dynamicconfig/client.go, common/dynamicconfig/collection.go, common/dynamicconfig/config/testConfig.yaml, common/dynamicconfig/file_based_client.go, common/dynamicconfig/file_based_client_test.go
Compare task type enum
**Why?**
No need to convert to string and compare
=> Compare task type enum

service/history/api/get_workflow_util.go, service/history/historyEngine.go
* Move get / poll mutable state to api package
**Why?**
N/A
N/A
N/A
=> Move get / poll mutable state to api package

service/history/api/deleteworkflow/api.go, service/history/handler.go, service/history/historyEngine.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
* Move delete workflow to api package
**Why?**
N/A
N/A
N/A
=> Move delete workflow to api package

service/history/api/refreshworkflow/api.go, service/history/historyEngine.go
* Move refresh workflow to api package
**Why?**
N/A
N/A
N/A
=> Move refresh workflow to api package

service/history/replication/dlq_handler.go
=> Handle sync workflow state task in replication dlq handler

develop/docker-compose/docker-compose.cdc.yml, develop/docker-compose/docker-compose.yml
Bump UI to v2.7.1. 
**Why?**
Keep dependencies up to date.
N/A
No risks.
No.
=> Bump UI to v2.7.1

service/history/api/describemutablestate/api.go, service/history/api/queryworkflow/api.go, service/history/historyEngine.go
* Move query workflow to api package
**Why?**
N/A
N/A
N/A
=> Move query workflow to api package

CONTRIBUTING.md, develop/docker-compose/docker-compose.darwin.yml, develop/docker-compose/docker-compose.linux.yml, develop/docker-compose/docker-compose.windows.yml, develop/docker-compose/docker-compose.yml
Remove UI v1 from development environment.
**Why?**
Deprecating v1.
N/A
No risks.
No.
=> Remove UI v1 from development environment

tools/cassandra/README.md
=> schama -> schema

service/history/shard/context_impl.go, service/history/shard/controller_impl.go, service/history/shard/controller_test.go
Assert shard ownership by IO when checking ownership
**Why?**
Close #3135
N/A
N/A
N/A
=> Check shard ownership by assertion

service/history/api/consistency_checker.go, service/history/api/signalwithstartworkflow/signal_with_start_workflow.go, service/history/api/workflow_context.go, service/history/handler.go, service/history/historyEngine.go, service/history/queueFactoryBase.go, service/history/queues/executable_mock.go, service/history/tasks/task.go, service/history/tasks/task_mock.go, service/history/timerQueueFactory.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueFactory.go, service/history/transferQueueTaskExecutorBase.go, service/history/visibilityQueueFactory.go, service/history/workflow/context.go, service/history/workflow/context_mock.go
* Simplify interface & remove unused vars
**Why?**
Code cleanup
N/A
N/A
N/A
=> Simplify interface & remove unused vars

common/metrics/otel_metrics_handler.go, common/metrics/otel_metrics_handler_test.go
Use async instrument for gauge type
**Why?**
Fix gauge type for otel metric
Run locally, verify gauge values are correct.
No
No
=> Fix otel gauge metric type

common/dynamicconfig/constants.go, service/worker/scanner/history/scavenger.go, service/worker/scanner/history/scavenger_test.go, service/worker/scanner/scanner.go, service/worker/scanner/workflow.go, service/worker/service.go
Add retention validation in history scavenger
**Why?**
We want to compare the retention validation from execution scavenger and history scavenger.
Unit tests and local tests
=> Add retention validation in history scavenger

temporal/fx.go
Take rpc address from config for local cluster
**Why?**
This allow users to upload the local cluster rpc address.
local tested.
=> Take rpc address from config for local cluster

service/worker/migration/activities.go
=> Fix namespace handover log

common/util.go, host/continue_as_new_test.go, host/integrationbase.go, host/taskpoller.go, host/workflow_test.go
Improve integration test framework:
- add `EqualHistory` and `EqualHistoryEvents` functions to assert on expected histories,
- add `formatHistoryCompact` to print out history in a very compact format,
- refactor the way how commands and history are printed during integration tests.
**Why?**
Improve testing expirience.
Use in upcomming PRs.
No risks.
No.
=> Improve integration test framework

common/dynamicconfig/constants.go, common/log/tag/values.go, service/history/configs/config.go, service/history/queues/metrics.go, service/history/queues/metrics_test.go
This diff adds some dynamic config values, and telemetry tags for the new archival queue.
**Why?**
The archival queue will need these values.
There's a test for the only executable lines in this PR.
Nothing--it just adds new dynamic configs that aren't used yet.
No.
=> Add some config values for the archival queue

common/persistence/cassandra/history_store.go, common/persistence/dataInterfaces.go, common/persistence/persistenceMetricClients.go, common/persistence/sql/history_store.go, service/history/handler.go, service/history/shard/context_impl.go, service/history/workflow/transaction_impl.go, service/worker/scanner/history/scavenger.go, service/worker/scanner/history/scavenger_test.go
* Make shard more resilient to append history timeout by not triggering shard ownership check
**Why?**
See above
N/A
N/A
N/A
=> Make shard more resilient to append history timeout

common/dynamicconfig/constants.go, host/integration_test.go, service/history/configs/config.go, service/history/workflow/task_generator.go, service/history/workflow/task_generator_test.go
Add jitter for retention timer
**Why?**
For spiky close workflow traffic pattern, add a timer jitter to smooth the spikes. 
Unit tests.
No
No
=> Add jitter for retention timer

common/persistence/tests/execution_mutable_state_task.go
=> Fix task serialization in persistence tests

develop/docker-compose/docker-compose.cdc.yml, develop/docker-compose/docker-compose.yml
bump ui to v2.8.3 in develop docker-compose.yml and docker-compose.cdc.yml
**Why?**
Keep ui up to date
n/a
n/a
No
=> bump ui to v2.8.3

common/metrics/defs.go, common/metrics/metric_defs.go, service/history/queues/executable.go, service/history/queues/metrics.go, service/history/queues/mitigator.go, service/history/queues/queue_base.go, service/history/queues/queue_scheduled.go, service/history/queues/rescheduler.go, service/history/queues/scheduler_monitor.go, service/history/queues/scheuduler_monitor_test.go, service/history/replication/task_processor.go, service/history/timerQueueActiveProcessor.go, service/history/timerQueueFactory.go, service/history/timerQueueStandbyProcessor.go, service/history/transferQueueActiveProcessor.go, service/history/transferQueueFactory.go, service/history/transferQueueStandbyProcessor.go, service/history/visibilityQueueFactory.go, service/history/visibilityQueueProcessor.go
Move queue metrics to metrics package
**Why?**
Have all metrics tag and scope in metrics package.
No
=> Move queue metrics to metrics package

develop/docker-compose/docker-compose.yml
Limit Cassandra memory appetite to 1Gb in development configuration.
**Why?**
To conserve developer machine resources.
Run locally.
No risks.
No.
=> Limit Cassandra memory appetite to 1Gb in development configuration

develop/docker-compose/docker-compose.yml
Upgraded Grafana version used in Docker to 9.1.4.
**Why?**
Version 8.1.5 has a bug in query input box that makes it unusable.
Set up Prometheus and Grafana, and tested with local Temporal server.
No.
No.
=> Upgrade dev grafana version used in docker

service/history/visibilityQueueProcessor.go
Fix visibility queue log message and level
**Why?**
^^
No
No
=> Fix visibility queue log message and level

.goreleaser.yml
Add `tdbg` to goreleaser.
**Why?**
To build `tdbg` binaries for every Temporal server release.
Build locally with `goreleaser release --snapshot --rm-dist` command.
No risks.
No.
=> Add tdbg to goreleaser

service/frontend/errors.go, service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go
Add request validation on batch APIs
**Why?**
Add request validation on batch APIs to fail request early
Unit tests
No
No
=> Add request validation on batch APIs

service/history/ndc/history_replicator.go
this time without the accidental submodule update
=> Fix function name typos

common/persistence/execution_manager.go, common/persistence/tests/execution_mutable_state_task.go, service/history/tasks/key.go
=> Fix immediate task fire time equality check

common/persistence/cassandra/test.go, common/persistence/sql/sqlPersistenceTest.go, tests/testhelper/source_root.go, tests/testhelper/source_root_test.go
I extracted this duplicated function into the common test helper package.
**Why?**
To keep the code DRY, especially because I have a new use case for it.
I added unit tests that cover every branch.
None.
No.
=> Extract duplicated getTemporalPackageDir into common function

service/history/api/reapplyevents/api.go
Revert change 'De-duplicate reapply event'(#2629)
**Why?**
This change may cause workflow lock deadlock. Remove this and will do a refactor in reapply logic.
Local test
The de-dup logic will be broken
yes
=> Revert change 'De-duplicate reapply event'

service/worker/service.go
Enable history scavenger to scan expired workflow
**Why?**
Enable history scavenger to scan expired workflow by default
Unit test and local tests
No
=> Enable history scavenger to scan expired workflow

common/persistence/cassandra/mutable_state_task_store.go, common/persistence/execution_manager.go, common/persistence/tests/execution_mutable_state_task.go
- Fix persistence GetHistoryTask
**Why?**
- Bug fix
- Added tests
- N/A, this persistence api is never used.
=> Fix persistence GetHistoryTask

service/history/workflowTaskHandlerCallbacks.go
Fix fail workflow batch id
**Why?**
When failing workflow, it should use the failing workflow first event id of the batch instead of next event id.
local test
Yes
=> Fix fail workflow batch id

common/metrics/metric_defs.go
- Fix pending tasks metric
**Why?**
=> Fix pending tasks metric

common/cluster/fx.go, common/deadlock/deadlock.go, common/resource/fx.go, service/history/shard/fx.go
Use fx groups to set up roots for deadlock detector
**Why?**
Easier and more flexible to add new roots
manual check
=> Use fx group for deadlock detector

service/history/configs/config.go, service/history/visibilityQueueTaskExecutor_test.go
Disable visibility verify close before delete
**Why?**
It is not useful and could potentially block visibility queue.
=> Disable visibility verify close before delete

common/metrics/metric_defs.go, common/rpc/interceptor/telemetry.go, common/rpc/interceptor/telemetry_test.go
Fix one metrics name
**Why?**
Change WorkflowCompletionStats to CompletionStats
=> Fix one metrics name

common/persistence/persistenceMetricClients.go
Update persistence error metrics
**Why?**
Fix the defer emit error issue.
Local verification
=> Update persistence error metrics

common/persistence/visibility/persistence-tests/visibility_persistence_suite_test.go
I fixed a flaky integration test. It was flaky because it assumed the `listWithPagination` method returned the items in the same order that requests were sent. However, there is no sorting on the actual queries: `templateGetWorkflowExecution` and `templateGetClosedWorkflowExecution`.
**Why?**
This flake caused a build of mine to fail: https://buildkite.com/temporal/temporal-public/builds/6712#0184ac44-36c5-4014-9843-1cc175c26426
I ran it 100 times: 
```
go test ./common/persistence/visibility/persistence-tests -run VisibilityPersistenceSuite/TestAdvancedVisibilityPagination -count 100
```
None.
No.
=> Fix a flaky persistence integration test

client/clientfactory.go, common/constants.go, common/namespace/handler.go, common/resource/fx.go, common/resourcetest/resourceTest.go, host/onebox.go, service/frontend/adminHandler.go, service/frontend/fx.go, service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go, service/history/fx.go, service/history/transferQueueTaskExecutorBase.go, service/history/workflow/delete_manager.go, service/history/workflow/delete_manager_test.go, service/matching/fx.go, service/worker/archiver/activities.go, service/worker/archiver/activities_test.go, service/worker/parentclosepolicy/workflow.go, service/worker/service.go
Consolidate duplicate constants
**Why?**
Consistency
CI
=> Consolidate service name constants

common/rpc/rpc.go
Fix incorrect locking pattern
**Why?**
Correctness
CI
=> Fix grpc listener initialization

common/archiver/s3store/historyArchiver.go, common/archiver/s3store/util.go, common/archiver/s3store/visibilityArchiver.go, common/archiver/s3store/visibilityArchiver_test.go
made some useful utility functions public
need this functionality in a dependent project, don't like copy/paste
no code changes, only naming
can't think of any 
no
=> make some s3 utility functions public

common/persistence/operationModeValidator.go, common/persistence/operationModeValidator_test.go
* Update workflow state validator allowing creation of completed workflow for created / updated / conflict resolved APIs
**Why?**
Allow more use case
N/A
N/A
N/A
=> Update workflow state validator

service/history/ndc/history_replicator.go, service/history/ndc/workflow_resetter.go
* Make sure defer release is able to capture returned error
* Added additional panic handling
**Why?**
Fix bug & make code robost
N/A
N/A
N/A
=> Fix defer not able to capture return error issue

service/history/queues/slice.go
=> Fix slice pending task count

service/history/workflow/mutable_state_impl.go
Rename `mutableStateImpl` receiver from `e` to `ms`.
**Why?**
To better reflect the type name.
Build.
No risks.
No.
=> Rename mutableStateImpl receiver

service/frontend/workflow_handler_test.go
Added error-checking to a test in this directory. Very simple
**Why?**
To help fix `errcheck` in our repo.
Ran again in this dir
None
No
=> Fix errcheck in service/frontend

common/rpc/interceptor/caller_info_test.go, common/rpc/interceptor/sdk_version_test.go
=> Fix errcheck in ./common/rpc/

service/matching/matcher_test.go, service/matching/service.go, service/matching/taskQueueManager.go, service/matching/taskReader.go
=> Fix errcheck in service/matching

temporal/fx.go, temporal/server.go, temporal/server_impl.go
=> Fix errcheck in temporal/

service/history/queues/queue_base_test.go, service/history/queues/queue_immediate.go, service/history/workflowTaskHandlerCallbacks_test.go
=> Fix errcheck in service/history

tests/testhelper/tls.go
We now handle a few unhandled errors during PEM encoding
**Why?**
As part of an effort to make `errcheck` blocking
Ran `errcheck ./tests/...`
Only used in tests.
No
=> Handle unhandled errors in tests/ directory

common/authorization/default_token_key_provider.go, common/log/zap_logger_test.go
=> Fix some unhandled deferred errors in ./common/

README.md, common/archiver/URI_test.go, common/collection/pagingIterator_test.go, service/frontend/workflow_handler_test.go
This PR fixes gofmt in a few files and adds a link to our Go report card (which now shows 100% A+)
**Why?**
To advertise this codebase to outside contributors, and to ensure we keep this in mind as we make more changes.
I opened the link in the badge
None
No
=> Fix gofmt and add Go report card

service/history/archival_queue_task_executor_test.go, service/history/queues/executable.go, service/history/queues/executable_test.go, service/history/queues/queue_base.go, service/history/queues/reader_test.go, service/history/queues/slice_test.go, service/history/timerQueueActiveTaskExecutor_test.go, service/history/timerQueueStandbyTaskExecutor_test.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/visibilityQueueTaskExecutor_test.go
=> Remove unused parameters from task executable

common/tasks/fifo_scheduler.go
- Prioritize worker pool shutdown
**Why?**
- Speed up worker pool shutdown. 
=> Prioritize worker pool shutdown

Makefile
Minor test target fixes
**Why?**
Minor test target fixes
=> Minor test target fixes

common/headers/versionChecker.go
=> Upgrade version to 1.19.1

service/matching/forwarder_test.go
A loop variable is captured in a groutine here, so the test is non-deterministic. A golangci-linter pointed this out to me.
**Why?**
Ensure this test is working correctly.
Reran the linter.
None, just a test
No
=> Fix datarace in forwarder_test

service/history/replication/task_executor.go
Fix redirect replicate workflow state
**Why?**
Fix redirect replicate workflow state
=> Fix redirect replicate workflow state
