common/searchattribute/validator.go, common/searchattribute/validator_test.go
**Why?**
Currently, if an invalid string search attribute is sent in the upsert or start, a message like 
"this is a string and not an int is not a valid value for search attribute CustomIntField of type Int" is produced. 
This makes it hard for the reader to consume because the search attributes boundaries are not defined.
The string value of the search attribute in this message should be escaped with " or the message should be reworked to the most common validation errors pattern in Temporal: <validation error>: <invalid value> 
Reworked the error message about invalid search attribute to the same pattern as our validation errors to remove the need to escape the original value in the final message.
The unit tests cover the validation errors …
=> Change Invalid search attribute value message

client/history/metricClient.go, client/matching/metricClient.go
Change log level for history/matching client errors.
**Why?**
These are usually not real server errors, the stacks are not useful and become noisy. 
Close #2700
=> Client error log level

common/persistence/sql/cluster_metadata.go, common/persistence/sql/execution.go, common/persistence/sql/execution_tasks.go, common/persistence/sql/factory.go, common/persistence/sql/history_store.go, common/persistence/sql/metadata.go, common/persistence/sql/queue.go, common/persistence/sql/shard.go, common/persistence/sql/task.go, common/persistence/visibility/store/standard/sql/visibility_store.go
- Use passed in context for sql persistence store impl
**Why?**
- Enforce persistence timeout, instead of always timeout after 8s
-  We may see an increased number of persistence context timeout error as now a lower context timeout will be used.
- No.
=> Persistence context Part 7: SQL store implementation

common/future/future.go, common/future/future_impl.go, common/future/future_test.go, common/future/ready_future_impl.go, service/matching/db_task_manager.go, service/matching/db_task_manager_test.go, service/matching/db_task_writer.go, service/matching/db_task_writer_mock.go, service/matching/db_task_writer_test.go
* Update matching logic according
**Why?**
Use generics
N/A
N/A
N/A
=> Update future to use generics

service/history/workflowTaskHandlerCallbacks.go
Do not drop workflow task if it failed due to unhandled events.
**Why?**
When there are unhandled events, server would fail workflow task. In that case, we don't want to have this extra delay.
=> Do not drop workflow task if it failed due to unhandled events

common/namespace/registry.go, common/namespace/registry_mock.go, common/namespace/registry_test.go, service/history/historyEngine.go
* Use uuid as namespace change listener ID, instead of shard ID
**Why?**
In case shard is reloaded
N/A
N/A
N/A
=> Use uuid as namespace notification ID

client/clientBean.go, common/cluster/metadata.go, common/cluster/metadata_mock.go, common/cluster/metadata_test.go, common/namespace/registry.go, common/namespace/registry_mock.go, service/history/historyEngine.go, service/history/replicationTaskFetcher.go, service/history/timerQueueProcessor.go, service/history/transferQueueProcessor.go, service/worker/replicator/replicator.go
Use UUID as callback listener ID
**Why?**
Race conditional may happen if a new shard starts before the old one close
Use current unit tests
=> Use caller object as callback listener ID

common/metrics/defs.go, common/rpc/interceptor/telemetry.go, service/frontend/adminHandler.go, service/frontend/operator_handler.go
Adding additional generic service_errors metric with error_type tag for all service errors.
Additional metric for service errors with error type as tag
**Why?**
Simplify consumption error dashboards.
Locally, I am good at failures
```
service_errors_entity_not_found{namespace="temporal_system",operation="DescribeWorkflowExecution",service_name="frontend"} 1
service_errors_entity_not_found{namespace="temporal_system",operation="DescribeWorkflowExecution",service_name="history"} 1
service_errors_namespace_already_exists{namespace="canary",operation="RegisterNamespace",service_name="frontend"} 4
service_errors_namespace_already_exists{namespace="default",operation="RegisterNamespace",service_name="frontend"} 4 …
```
=> Always report service error as additional metric with error-type tag

common/persistence/visibility/visibility_manager_dual.go, service/worker/deletenamespace/deleteexecutions/workflow_test.go, service/worker/deletenamespace/errors/errors.go, service/worker/deletenamespace/reclaimresources/activities.go, service/worker/deletenamespace/reclaimresources/activities_test.go, service/worker/deletenamespace/reclaimresources/workflow.go, service/worker/deletenamespace/reclaimresources/workflow_test.go, service/worker/deletenamespace/workflow_test.go
Use better retry logic in `reclaimresources` workflow.
**Why?**
When advanced visibility is enabled, `EnsureNoExecutionActivity` uses better retry logic now. Instead of just retrying for some period of time, it monitors progress of task processing. If progress is made then it keeps waiting. In case if no progress is made activity returns non-retryable error and workflow tries to delete executions again.
Standard visibility just retries for 30 minutes making approximately 20 attempts.
Modified unit tests and local run.
No risks.
No.
=> Use better retry logic in reclaimresources workflow

common/dynamicconfig/constants.go, common/metrics/defs.go, common/metrics/tags.go, service/history/configs/config.go, service/history/configs/task.go, service/history/queues/priority_assigner.go, service/history/queues/priority_assigner_test.go, service/history/tests/vars.go
- Implement Task priority assigner interface
**Why?**
- Host level worker pool implementation
- N/A, not used anywhere
No.
=> Task priority assigner implementation

common/util.go, service/history/consts/const.go, service/history/historyEngine.go, service/history/nDCTaskUtil.go, service/history/queueProcessor.go, service/history/queues/executable.go, service/history/queues/executable_test.go, service/history/queues/queue.go, service/history/taskProcessor.go, service/history/tasks/fake_task.go, service/history/tasks/utils.go, service/history/timerQueueActiveProcessor.go, service/history/timerQueueProcessorBase.go, service/history/timerQueueStandbyProcessor.go, service/history/transferQueueActiveProcessor.go, service/history/transferQueueProcessorBase.go, service/history/transferQueueStandbyProcessor.go, service/history/transferQueueTaskExecutorBase.go, service/history/visibilityQueueProcessor.go
- Implement Task executable interface
**Why?**
- Host level worker pool implementation
- N/A, not used anywhere
No.
=> Task executable implementation

common/persistence/persistenceMetricClients.go
Adding error type tag to persistence failures metric
**Why?**
Follow on to #2741 
Locally, I am good at errors
Metric tagging differences
No
**metrics**
```
persistence_errors{error_type="serviceerror_NotFound",namespace="all",operation="GetCurrentExecution",service_name="history"} 1
persistence_errors{error_type="serviceerror_NotFound",namespace="all",operation="GetNamespace",service_name="frontend"} 2
persistence_errors{error_type="serviceerror_NotFound",namespace="all",operation="GetTaskQueue",service_name="matching"} 32
persistence_errors_entity_not_exists{namespace="all",operation="GetCurrentExecution",service_name="history"} 1
persistence_errors_entity_not_exists{namespace="all",operation="GetName …
```
=> Adding error type tag to peristence errors

go.mod, go.sum, service/history/tests/vars.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go
Add failure event if target namespace is missed during transfer task processing.
**Why?**
If namespace is deleted there is a chance that namespace existed when command was proccessed but got deleted when corresponding transfer task was processed. To handle this, corresponding failed event is recorded in caller history.
New unit tests.
No risks.
No.
=> Add failure event if target namespace is missed during transfer task processing

service/history/historyEngine_test.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/mutable_state_rebuilder.go, service/history/workflow/mutable_state_rebuilder_test.go, service/history/workflow/retry.go
* Use shard clock for parent / child workflow
**Why?**
see #2743 
Unit tests
N/A
N/A
=> Utilize shard clock for child workflow

common/dynamicconfig/constants.go, service/history/configs/config.go, service/history/workflow/workflow_task_state_machine.go
- Increase workflow task start to close timeout when workflow task is keep retrying
**Why?**
- Slow down workflow task retry.
- When workflow task is keep failing, workflow task response will be dropped and wait for the start to close timeout to happen
- Existing tests, tested locally.
- For sdk, since start to close timeout is increase, a workflow task may potentially executed for the entire start to close duration.
- The change only affects the timer duration for transient workflow task start to close timeout in active cluster. Since timer task processing logic is async, this can be viewed as a delayed fired timer.
- Doesn't affect xdc logic as transient workflow task scheduled is not a real event and won't be replicated. …
=> Slow down workflow task retry

service/history/workflowTaskHandler.go
Don't fail `ContinueAsNew` command if parent namespace doesn't exist.
**Why?**
`ContinueAsNew` can be called for the same namespace only, but internally mutable state supports different parent namespace. In case if this feature will ever be used, with this PR, subsequient calls to `ContinueAsNew` won't fail and won't store parent namespace name (only Id).
No risks.
No.
=> Don't fail ContinueAsNew command if parent namespace doesn't exist

common/dynamicconfig/constants.go, common/namespace/registry.go, common/namespace/registry_test.go, common/resource/fx.go, host/dynamicconfig.go, host/integrationbase.go, host/ndc/ndc_integration_test.go, host/onebox.go, host/xdc/integration_failover_test.go, service/history/configs/config.go, service/history/queues/executable.go, service/history/queues/executable_test.go, service/history/taskProcessor.go, service/history/taskProcessor_test.go, service/history/tests/vars.go
Add dynamic config for namespace refresh interval
**Why?**
To reduce wait time for namespace promotion and failover.
Local tests.
=> Add dynamic config for namespace refresh interval

client/history/client.go, common/metrics/defs.go, common/persistence/cassandra/shard_store.go, common/persistence/client/fault_injection.go, common/persistence/dataInterfaces.go, common/persistence/dataInterfaces_mock.go, common/persistence/mock/store_mock.go, common/persistence/persistenceInterface.go, common/persistence/persistenceMetricClients.go, common/persistence/persistenceRateLimitedClients.go, common/persistence/shard_manager.go, common/persistence/sql/shard.go, service/history/consistency_checker.go, service/history/consistency_checker_test.go, service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/historyEngine3_eventsv2_test.go, service/history/historyEngine_test.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/workflowRebuilder.go, service/history/workflowTaskHandlerCallbacks.go
* Utilize shard clock or shard ownership API for consistency check
* Workflow task:
* Start
* Completion
* Failure
* Activity task:
* Start
* Heartbeat
* Completion
* Failure
* Cancellation
* Child workflow:
* Start
* Completion
* Utilize shard ownership API for consistency check
* Delete workflow
* Terminate workflow
* RequestCancel workflow
* SignalWorkflowExecution
* RemoveSignalMutableState
* ResetWorkflowExecution
* RefreshWorkflowTasks
**Why?**
see #2743 
Updated tests
N/A
N/A
=> Update mutable state consistency check logic

service/history/historyEngine.go, service/history/historyEngine_test.go
- Do not wake up workflow in retry backoff upon signal
**Why?**
- Existing check only handles cron workflow not workflow retry.
- no
=> Do not wake up workflow in retry backoff upon signal

common/metrics/config.go, common/metrics/config_test.go
Fix set default per unit histogram boundaries
**Why?**
Current default histogram boundaries only get set when framework is define. If framework is not define, we fallback to tally with a different init code path. 
Local test.
=> Fix set default per unit histogram boundaries

service/history/api/start_workflow_uti.go, service/history/historyEngine.go, service/history/timerQueueActiveTaskExecutor.go, service/history/workflowTaskHandler.go
* Move workflow creation logic util into api package
* Simplify history engine impl
**Why?**
Code simplification & restructure
N/A
N/A
No
=> Move history API logic into its own package

common/metrics/defs.go, service/history/configs/config.go, service/history/consts/const.go, service/history/nDCStandbyTaskUtil.go, service/history/nDCTaskUtil.go, service/history/queues/executable.go, service/history/timerQueueActiveTaskExecutor.go, service/history/timerQueueStandbyTaskExecutor.go, service/history/timerQueueTaskExecutorBase.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueTaskExecutorBase.go, service/history/visibilityQueueTaskExecutor.go, service/history/workflow/context.go, service/history/workflow/transaction_impl.go, service/worker/parentclosepolicy/client.go, service/worker/parentclosepolicy/client_mock.go
- Limit task processing time to 3s
- 500ms for getting workflow execution lock
- For workflow reset task and standby history resend the timeout is 20s and 30s (default) respectively. The timeout for resend is controlled by a dynamicconfig.
**Why?**
- Host level pool require the processing for each task to be fast
- Integration tests & canary
- In terms of short context time + retry adding more load to downstream, this should not be a problem as the new retry policy is much less aggressive compared to the previous one. If worker pool sees timeout errors, the task will skip in-place retry and be send back to the rescheduler and the exponential backoff policy will kick in. 
- No.
=> Limit task processing time

common/dynamicconfig/constants.go, service/history/configs/config.go, service/history/queueProcessorFactory.go, service/history/timerQueueActiveProcessor.go, service/history/timerQueueActiveTaskExecutor_test.go, service/history/timerQueueProcessor.go, service/history/timerQueueProcessorBase.go, service/history/timerQueueStandbyProcessor.go, service/history/transferQueueActiveProcessor.go, service/history/transferQueueProcessor.go, service/history/transferQueueProcessorBase.go, service/history/transferQueueStandbyProcessor.go, service/history/visibilityQueueProcessor.go
- Add dynamicconfigs for enabling and tuning host level task scheduler
- Initialize host level task scheduler, if enabled, on service startup
- Will change the base branch after https://github.com/temporalio/temporal/pull/2770 is landed
**Why?**
- Host level worker pool
- Tested locally using canary with feature flag enabled.
- N/A, not enabled by default
- No.
=> Wire up host level task scheduler

service/worker/deletenamespace/reclaimresources/workflow.go, service/worker/deletenamespace/workflow.go
Limit number of delete workflow executions retries.
**Why?**
Infinity retries might generate too much load on the cluster.
Run locally.
No risks.
No.
=> Limit number of delete workflow executions retries

service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_util.go
- Remove `setTaskInfo` which overrides task version and visibility timestamp for immediate tasks
**Why?**
- All tasks, when created already specified the desired version and visibility timestamp, no need to override
- The overriding version is always namespace current version which may not be the right version for the task. and may cause the task to be dropped.
- Tested in test cluster
- Maybe.
=> Remove task version and visibility timestamp override

common/persistence/persistence-tests/clusterMetadataManagerTest.go
- Increase record expiry time in TestClusterMembershipReadFiltersCorrectly
**Why?**
- This test is flaky: https://buildkite.com/temporal/temporal-public/builds/3519#ff1160da-f066-439e-9891-9ae72a3c77ec/594-599
- no
=> Fix flaky TestClusterMembershipReadFiltersCorrectly

service/history/shard/context_impl.go
- Ensure queue processor cluster ack level is below failover ack (current) level
**Why?**
- Handle task lost issue during failover when shard movement happens before failover queue tasks are processed but after persisting new active/standby queue ack level update. Task may lost because upon shard reload, the range for the new failover queue is calculated based on the updated active/standby queue ack level.
- Verified that when deleting tasks, the failover queue's level is taken into consideration.
- eyeballing
- if failover level is never deleted, then active/standby queue processor's ack level will be stuck.
- maybe
=> Ensure queue processor cluster ack level is below failover ack level

service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go
`UpdateWorkflowTask` isn't called on `MutableState`, it's only used within `workflowTaskStateMachine`
**Why?**
less code
unit + integration tests
=> Remove unused method from MutableState

service/history/historyEngine_test.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor_test.go
- Schedule first workflow task for started abandoned child regardless if parent workflow is closed or not
**Why?**
- For abandoned it's possible that the child workflow is started and record in parent history, yet has no workflow task scheduled and child workflow will be blocked until timeout. This is ok for child with terminate or cancel parent close policy. But not for those with abandon policy, those should continue their execution. 
- Pick https://github.com/uber/cadence/pull/4579
=> Always schedule first workflow task for started abandoned child

common/namespace/namespace.go, common/namespace/namespace_test.go
Expose namespace data
**Why?**
Expose namespace data so we can use the customized data.
Unit test
=> Expose namespace data

service/worker/deletenamespace/activities.go, service/worker/deletenamespace/activities_test.go, service/worker/deletenamespace/deleteexecutions/workflow_test.go, service/worker/deletenamespace/workflow.go, service/worker/deletenamespace/workflow_test.go
Use part of namespace ID for delete namespace name.
**Why?**
Previously 5 random chars suffix was used to make sure that temporarry delete namespace name is unique. Using part of namesapce ID simplify debugging especially when many namespaces get deleted at the time.
No risks.
No.
=> Use part of namespace ID for delete namespace name

service/history/workflowTaskHandler.go
Return `NamespaceNotFound` error from `RespondWorkflowTaskCompleted` handler.
**Why?**
There are few places where `NamespaceNotFound` can be returned from namespace registry. Previously it was substituted with `Unavailable` error and it introduces inconsistency. Original error should be returned to the caller instead.
No risks.
No.
=> Return NamespaceNotFound error from RespondWorkflowTaskCompleted handler

common/persistence/visibility/store/standard/cassandra/visibility_store.go, service/history/visibilityQueueTaskExecutor.go
Remove obsolete `nil` `CloseTime` check.
**Why?**
`DeleteExecutionVisibilityTask` can be created with empty `CloseTime` and it means that visibility records needs to be deleted for open workflow execution. It is valid case and it can happen in replication stack. Obsolete case with Cassandra TTL is not valid anymore because visibility tasks are short lived and TTL was removed few releases ago.
Current tests and integration tests in upcoming PR.
No risks.
No.
=> Remove obsolete nil CloseTime check

service/history/transferQueueActiveTaskExecutor.go
Fix error handling in `processParentClosePolicy`.
**Why?**
1. There was a bug from previous PR which logs `NotFound` error and ignores all other but should do the opposite.
2. RPC calls can also return `NamespaceNotFound` error and the check was moved to higher level to cover this.
Exixting tests.
No risks.
No.
=> Fix error handling in processParentClosePolicy

common/metrics/defs.go, common/metrics/tags.go, service/frontend/adminHandler.go, service/frontend/workflowHandler.go, service/history/shard/context_impl.go, service/history/workflow/metrics.go, service/history/workflow/transaction_impl.go
Remove StatsTypeTag
**Why?**
We introduce metrics unit at metrics level. No need to have the stats type at scope level.
Local test
=> Deprecate StatsTypeTag

service/history/shard/context_impl.go, service/history/shard/context_test.go, service/history/workflow/transaction_impl.go, service/history/workflow/transaction_test.go
- Do not hold shard lock when calling historyEngine.NotifyNewTask, as the notify method may try to lock the shard again.
- This will happen when trying to add task for standby workflows. When notifying task to standby timer queue, the logic will try to lock shard again to get standby cluster time.
**Why?**
- Fix deadlock
- Tested locally with https://github.com/temporalio/temporal/pull/2809
=> Fix potential deadlock in shard addTask

service/history/configs/config.go, service/history/workflow/mutable_state_impl.go
Remove global StickyTTL which has default value of 1 year. The default sticky task queue ttl of 1 day is still in place.
**Why?**
With recent change to avoid 5s sticky delay, there is no need for that ttl.
=> Remove global StickyTTL

service/history/nDCStandbyTaskUtil.go, service/history/timerQueueStandbyTaskExecutor.go, service/history/timerQueueStandbyTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor_test.go
- Resend history instead of pushing to matching when pending standby activity/workflow task is between resend delay and discard delay.
**Why?**
- Resend history instead of pushing to matching to avoid persisting too many activity/workflow tasks in matching when replication latency is high or during ns migration.
- More refresh & resend history call on history service
- no
=> Resend history for pending standby activity workflow task

service/worker/migration/activities.go
=> Minor tweak to migration workflow wait replication check

common/metrics/defs.go, common/rpc/interceptor/telemetry.go, service/worker/deletenamespace/deleteexecutions/activities.go, service/worker/deletenamespace/deleteexecutions/workflow_test.go, service/worker/deletenamespace/errors/errors.go, service/worker/deletenamespace/reclaimresources/activities.go, service/worker/deletenamespace/reclaimresources/activities_test.go, service/worker/deletenamespace/reclaimresources/workflow.go, service/worker/deletenamespace/reclaimresources/workflow_test.go
Remove `TerminateWorkflowExecution` call when deleting namespace.
**Why?**
With recent changes `DeleteWorkflowExecution` supports delete of running workflows and there is no need to terminate it first.
Manually for now. Integration tests are pending.
No risks.
No.
=> Remove TerminateWorkflowExecution call when deleting namespace

service/history/historyEngine.go, service/history/nDCEventsReapplier.go, service/history/nDCEventsReapplier_test.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go
Check workflow task after reapply events
**Why?**
When reapply event to current branch, we need to check if it should schedule a new workflow task
=> Check workflow task after reapply events

common/namespace/replicationTaskExecutor.go, common/namespace/replicationTaskExecutor_test.go, host/test_cluster.go, service/frontend/adminHandler.go, service/frontend/adminHandler_test.go, service/worker/service.go
Ignore namespace replication task if the namespace does not live in current cluster.
**Why?**
When dynamically connect any clusters, we don't need namespace to be replicated everywhere. 
Existing unit test / integration tests.
=> Drop namespace replication task if it does not live in current cluster

docker/config_template.yaml
Signed-off-by: Alexander Mays <alex@eastside.io>
During the review process on the PR to add the SQL Auth Plugin, a new configuration block was added however the docker template was not updated to reflect that.
**Why?**
No
=> Fix docker template to handle SQLAuthPlugin config block

service/history/historyEngine.go, service/history/shard/context_impl.go
- Currently if shard reload happens when failover queue is running, the failover queue won't be re-created after is reloaded due to the notification version check.
**Why?**
=> Fix failover queue creation after shard reload

common/metrics/defs.go, common/metrics/tags.go, common/rpc/interceptor/telemetry.go
wire up interceptor
Add action metrics
**Why?**
To measure number of actions take by work load
Run samples work load, and observed metrics:
action{action_type="command_RecordMarker_LocalActivity",namespace="default",operation="RespondWorkflowTaskCompleted",service_name="frontend"} 3
action{action_type="command_ScheduleActivityTask",namespace="default",operation="RespondWorkflowTaskCompleted",service_name="frontend"} 2
action{action_type="command_StartChildWorkflowExecution",namespace="default",operation="RespondWorkflowTaskCompleted",service_name="frontend"} 1
action{action_type="command_StartTimer",namespace="default",operation="RespondWorkflowTaskCompleted",service_name="frontend"} 1
action{action_type="grpc_RecordActivityTaskHeartbeat",namespac …
=> Add action metrics

service/worker/deletenamespace/deleteexecutions/workflow_test.go, service/worker/deletenamespace/reclaimresources/workflow.go, service/worker/deletenamespace/reclaimresources/workflow_test.go, service/worker/deletenamespace/workflow.go
Remove custom retries for `ReclaimResourcesWorkflow`.
Also fixed broken unit tests.
**Why?**
It turn out that Temporal retries child workflows even with `PARENT_CLOSE_POLICY_ABANDON`.
Manually.
No risks.
No.
=> Remove custom retries for ReclaimResourcesWorkflow

client/clientBean.go, client/clientBean_mock.go, common/resource/resourceTest.go, service/frontend/adminHandler.go, service/frontend/dcRedirectionHandler.go, service/history/replication/dlq_handler.go, service/history/replication/dlq_handler_test.go, service/history/replication/task_fetcher.go, service/history/replication/task_processor_factory.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/timerQueueProcessor.go, service/history/timerQueueStandbyTaskExecutor.go, service/history/transferQueueProcessor.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/workflow/context.go, service/worker/parentclosepolicy/workflow.go, service/worker/parentclosepolicy/workflow_test.go, service/worker/replicator/replicator.go
Return error when cluster info is not found
**Why?**
The cluster info and namespace are both updated in frontend. There is a race conditional in history service, the namespace is updated earlier than the cluster info. This should recover after retries.
=> Return error when cluster info is not found

service/history/historyEngine.go, service/history/workflow/cache.go, service/history/workflow/cache_mock.go
* Remove lock on current workflow ID since this lock is close to noop
NOTE: all writes to DB are serialized by the shard lock
**Why?**
See above
N/A
N/A
N/A
=> Remove lock on current workflow ID

common/xdc/nDCHistoryResender.go, common/xdc/nDCHistoryResender_mock.go, common/xdc/nDCHistoryResender_test.go, service/frontend/adminHandler.go, service/history/historyEngine.go, service/history/historyEngineFactory.go, service/history/queueProcessorFactory.go, service/history/replication/dlq_handler.go, service/history/replication/dlq_handler_test.go, service/history/replication/task_executor.go, service/history/replication/task_executor_test.go, service/history/replication/task_processor_factory.go, service/history/timerQueueProcessor.go, service/history/timerQueueStandbyProcessor.go, service/history/timerQueueStandbyTaskExecutor.go, service/history/timerQueueStandbyTaskExecutor_test.go, service/history/transferQueueProcessor.go, service/history/transferQueueStandbyProcessor.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor_test.go
- Refactor ndc history resender to handle multiple remote clusters
**Why?**
- Existing history resend is bind to particular remote cluster and can't be used for resending history from other remote clusters. This means we need to create one resender for each remote cluster and also worry about cluster metadata update. 
- Needed by https://github.com/temporalio/temporal/pull/2864, so that we don't need to refactor existing standby task executor implementation (or creating multiple standby executors and add callback for cluster metadata update) but still be able to handle standby tasks which need to resend history from different remote clusters.
=> Refactor ndc history resender to handle multiple remote clusters

common/metrics/defs.go, common/persistence/dataInterfaces.go, common/persistence/persistenceMetricClients.go, common/persistence/size.go, service/history/workflow/metrics.go
This adds a metric that tracks the number of tasks in each workflow execution update.
**Why?**
We already had metrics that show the processing rate - this lets us compare creation rate to processing rate to detect task backlogs.
`make start` + benchmark workflows.
In prometheus, expressions like `sum(rate(task_count_sum{task_category="transfer"}[30s]))` work
Additional metrics break some customers' prometheus scrapers.
No
=> Add task count metric

Makefile
Disable cgo by default.
**Why?**
> When `make` runs a recipe, variables defined in the makefile are placed into the environment of each shell. This allows you to pass values to sub-make invocations (see [Recursive Use of make](https://www.gnu.org/software/make/manual/html_node/Recursion.html#Recursion)). By default, only variables that came from the environment or the command line are passed to recursive invocations. You can use the `export` directive to pass other variables. See [Communicating Variables to a Sub-make](https://www.gnu.org/software/make/manual/html_node/Variables_002fRecursion.html#Variables_002fRecursion), for full details.
Run manually.
No risks.
No.
=> Disable cgo by default

common/dynamicconfig/config.go, common/dynamicconfig/config/testConfig.yaml, common/dynamicconfig/file_based_client_test.go
Dynamic config filtered by task queue can take &lt;namespace, task queue, task queue type&gt; or &lt;namespace, task queue&gt; constraints. This adds &lt;namespace&gt; and &lt;task queue&gt; as a possible sets of constraints.
**Why?**
We can have server workers that listen on a specific task queue in all user namespaces. This lets us apply dynamic config to those.
unit test
=> Allow dynamic config filter by namespace or task queue name only

service/history/historyEngine.go, service/history/workflow/delete_manager.go, service/history/workflow/delete_manager_test.go
Check visibility ack level in standby cluster for `DeleteWorkflowExecution`.
**Why?**
Visibility queue ack level must be checked in standby cluster too to avoid resurrection of visibility record in standby cluster.
No risks.
No.
=> Check visibility ack level in standby cluster for DeleteWorkflowExecution

service/history/shard/context_impl.go, service/history/shard/controller_test.go
Add a `String` method (`fmt.Stringer`) to `ContextImpl`.
Also simplify `contextMatcher` implementation and move `getOrCreateShardRequestMatcher` to the bottom of the file just so the matchers are in one place.
**Why?**
This is a weird one: in some tests, we use a gomock matcher to differentiate between `Context`s in `CreateEngine`, to return the right value. Internally, gomock evaluates all its matchers, but for the failing ones (and there will always be failing ones if there's more than one), it constructs an error message using `Sprintf("%v")` and then throws it away when it finds a match. The default `"%v"` formatter reads private fields of the value being matched. Some of those private fields (e.g. `state`) are protected by a mutex, but it doesn't know that and reads …
=> Add String method to ContextImpl to fix a race

common/dynamicconfig/basic_client.go, common/dynamicconfig/config.go, common/dynamicconfig/config/testConfig.yaml, common/dynamicconfig/config_test.go, common/dynamicconfig/file_based_client_test.go, common/dynamicconfig/interface.go, common/dynamicconfig/interface_mock.go, common/dynamicconfig/mutable_ephemeral_client_test.go, common/dynamicconfig/noop_client.go, host/dynamicconfig.go
The logic for handling multiple dynamicconfig constraints (in the case of task queue constraints) was split between `Collection` and `Client`, which led to at least one bug: a less specific value would be preferred over a more specific one if the more specific one happened to match the default value supplied by the caller.
This pushes more of the logic into `Client`, which now takes a slice of filter maps, and checks them in order (plus the non-constrained value).
**Why?**
Fix a bug, make code easier to understand.
unit tests
This changes the interface of `dynamicconfig.Client`, so any projects that use the server as a library may have to update their code (to wrap the map in a slice). `Client` isn't used in the server itself …
=> Fix bug and simplify dynamicconfig

tools/sql/handler.go
adding condition to the temporal-sql-tool command where the create or drop commands were ignoring the global --datasource value provided, which effectively forced the connection to fall back to the default db instance name, which the fallback mechanism was hard-coding as one of two values: postgres or defaultdb. 
**Why?**
Default postgres db instance might not be postgres or defaultdb. The create and drop commands should allow --database definitions to override what the default db instance name is in the case it's not one of the two hard-coded values. Also, based on the blame it looks like the `cfg.DatabaseName = ""` line hasn't changed in nearly 2 years and when it was added it was part of a mysql tls support commit. I added the `if cfg.PluginName != "postgres"` check …
=> Enable Create or Drop Database Command for Postgres to Use Global Database Option

service/worker/deletenamespace/deleteexecutions/workflow.go, service/worker/deletenamespace/errors/errors.go, service/worker/deletenamespace/reclaimresources/activities.go, service/worker/deletenamespace/reclaimresources/workflow_test.go
Include actual numbers in `deletenamespace` workflow errors.
**Why?**
Error messages and details are shown in web UI and very useful for debugging.
Run locally.
No risks.
No.
=> Improve deletenamespace workflow errors

common/tasks/parallel_processor.go, common/tasks/parallel_processor_test.go, service/history/queueProcessorFactory.go, service/history/timerQueueProcessorBase.go, service/history/transferQueueProcessorBase.go, service/history/visibilityQueueProcessor.go
- Make task processing worker count config truly dynamic
**Why?**
- When tuning worker pool size, only need to change the dynamicconfig value. No need to restart the host or reload shard.
- Prepare for making the scheduler worker count config cluster level instead of host level.
- unit test, tested locally with canary and change timer worker count
=> Make task processing worker count config truly dynamic

go.mod, go.sum
Moving fork under temporal
This is temporary, in hopes of this PR landing
https://github.com/golang/exp/pull/34
**Why?**
Updating otel dependencies
Previous PR
None
No
=> moving fork to temporal

common/dynamicconfig/constants.go, service/frontend/errors.go, service/frontend/service.go, service/frontend/workflowHandler.go
Add dynamic config setting to control schedule-related rpcs at frontend.
**Why?**
controlled roll-out of features
=> Add dynamic config to disable frontend schedule rpcs

common/namespace/handler.go, common/namespace/handler_GlobalNamespaceDisabled_test.go, common/namespace/handler_GlobalNamespaceEnabled_MasterCluster_test.go, common/namespace/handler_GlobalNamespaceEnabled_NotMasterCluster_test.go, common/namespace/handler_test.go, go.mod, go.sum, service/frontend/adminHandler.go, service/frontend/workflowHandler.go, service/frontend/workflowHandler_test.go
Fill in fields added in https://github.com/temporalio/api/pull/186
**Why?**
So UI can tell if schedules are enabled at a namespace level, and SDK at a server level.
unit tests
=> Fill in SupportsSchedules field

common/namespace/handler.go, common/namespace/handler_GlobalNamespaceEnabled_MasterCluster_test.go, common/namespace/handler_test.go, common/namespace/replicationTaskExecutor.go, common/namespace/replicationTaskExecutor_test.go, common/namespace/transmissionTaskHandler.go, common/namespace/transmissionTaskHandler_test.go
1. Generate replication task when updating cluster list
2. Apply replication task when namespace exists
**Why?**
When removing a cluster from the cluster list, it should be updated in the to-be-remove cluster.
Unit tests
=> Generate replication task when updating cluster list

common/metrics/defs.go, common/metrics/tags.go, common/tasks/benchmark_test.go, common/tasks/interleaved_weighted_round_robin.go, common/tasks/interleaved_weighted_round_robin_test.go, common/tasks/priority.go, common/tasks/task.go, common/tasks/task_mock.go, service/history/configs/task.go, service/history/queues/executable.go, service/history/queues/executable_mock.go, service/history/queues/priority_assigner.go, service/history/queues/priority_assigner_test.go
- Add priority tag for task processing related metrics: task request, task_latency & task_latency_queue family (those showing latency for queuing & multiple attempts)
- Use task type tag instead of task category tag for task throttling metrics
- Make task priority strong type & move definitions to common/tasks package
**Why?**
- Improve task processing metrics
- Existing metrics
- Low, only changing metrics
- No.
=> Add priority tag for task processing metrics

common/metrics/defs.go, common/persistence/visibility/store/elasticsearch/processor.go, common/persistence/visibility/store/elasticsearch/processor_mock.go, common/persistence/visibility/store/elasticsearch/processor_test.go, common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_write_test.go
Update es processor to return future on duplicate request.
**Why?**
The visibility task may drop due to timeout and resubmit to the bulk processor. The second retry in the bulk processor may hit dedup logic and return success.
We should return the same future object for duplicated requests.
=> Handle visibility task timeout in bulk operation

service/history/timerQueueAckMgr.go
- Ensure timer max query level always equal to or above min query level
**Why?**
- When adding a new cluster, the initial remote cluster time is time.Time{}. The time (plus some offset) will be used as the timer max query level when attempting a read. However the min query level is from the overall queue ack level which is a quite recent time. So we have min query level > max query level, and the logic in timer ack manager will found there's nothing more to read and set min query level to be max query level. Now min query level becomes 0 and we will start to read from very beginning of the timer queue and encounter tombstone or resurrection issues.
- Note the fix here is not making sure min query level can't move backward to a lower max query level, instead ensuring max …
=> Ensure timer max query level never less than min query level

common/namespace/registry.go, service/worker/pernamespaceworker.go, service/worker/pernamespaceworker_test.go
perNamespaceWorkerManager didn't handle deleted namespaces correctly, it does now. The namespace state change callback gets an extra bool to tell to differentiate `NAMESPACE_STATE_DELETED` (which can be reversed) from actually not present in db anymore.
**Why?**
Deleting namespaces will be supported soon.
new unit test
If the worker continues running, it will just fail on all interactions with the namespace, so it shouldn't cause any harm.
=> Handle deleted namespaces in perNamespaceWorkerManager

common/authorization/interceptor.go
Pure refactoring - moving the code to get claims and authorize request into two utilities.
**Why?**
Improve code reuse.
Unit and local testing.
Pure refactoring so little risk.
No.
=> Refactor authorization interceptor by extracting utilities

config/dynamicconfig/development-cass.yaml, service/history/queueProcessor.go, service/history/queueProcessorFactory.go, service/history/queues/queue.go, service/history/queues/queue_mock.go, service/history/timerQueueActiveProcessor.go, service/history/timerQueueProcessorBase.go, service/history/timerQueueStandbyProcessor.go, service/history/transferQueueActiveProcessor.go, service/history/transferQueueStandbyProcessor.go, service/history/visibilityQueueProcessor.go
- Fix host level task scheduler start/stop
**Why?**
- Currently task scheduler start/stop is always done on shard level, even when the scheduler is a host level scheduler.
- When shard movement happens, the host level scheduler will also get stopped. 
- Tested locally using canary with both host level pool enabled and disabled. Also randomly closing shards.
=> Fix host level task scheduler start/stop

common/tasks/parallel_processor_test.go
- Fix flaky test `TestSubmitProcess_Stopped_FailSubmission`
**Why?**
- There's no guarantee that calling Submit() after Stop() will make the task get rescheduled immediately since worker goroutine shutdown is async. It's possible that a worker didn't get the shutdown notification immediately after Stop() is called and picks up the submitted task from task channel.
- Recent changes to parallel processor makes worker goroutine shutdown slightly slower than before (shutdown notification is propagated via another worker monitor goroutine). and makes ^ race condition in test visible.
```
go test -run TestParallelProcessorSuite -testify.m TestSubmitProcess_Stopped_Submission -count=10000 -v
```
=> Fix task parallel processor test

common/metrics/events_scope.go
Add lookup scope def for common service if not found for serviceIdx
**Why?**
operation tags
locally
None
No
=> also lookup scopedef by common if not found by service

common/metrics/events_scope.go, common/metrics/otel_event_handler.go, common/metrics/tally_event_handler.go
Remove caching recording functions
**Why?**
Fixing memory leak
locally, pprof heap dump with running canary
None
No
=> Remove caching objects to prevent leak

service/history/shard/context_impl.go
Fix getRemoteClusterInfo race condition
**Why?**
The getRemoteClusterInfo update the map if the item does not exist. We should acquire a writeLock.
Existing integration test
=> Fix getRemoteClusterInfo race condition

schema/elasticsearch/visibility/versioned/v2/index_template_v6.json, schema/elasticsearch/visibility/versioned/v2/index_template_v7.json, schema/elasticsearch/visibility/versioned/v2/upgrade.sh
Turn off indexing for `TemporalScheduleInfoJSON`, which is only used for passing data through and never for querying.
Modifying the versioned schema normally wouldn't be okay, but we haven't done a release with the new schema yet.
**Why?**
Maintaining an index for this field is useless, so we can disable it to reduce ES costs.
manual test
=> Don't index search attribute used for passing data through visibility

temporal/fx.go, temporal/server_option.go, temporal/server_options.go
Adding server option for metrichandler
**Why?**
To allow simple customization
Unit tests
None
No
=> Adding serveroption for metrics.MetricHandler

common/searchattribute/defs.go, schema/elasticsearch/visibility/versioned/v2/index_template_v6.json, schema/elasticsearch/visibility/versioned/v2/index_template_v7.json, schema/elasticsearch/visibility/versioned/v2/upgrade.sh
Remove unindexed fields from index schema template.
**Why?**
Existing unindexed fields (`Memo`, `MemoEncoding`, and `VisibilityTaskKey`) are not in index schema template. Let's follow the same approach for new `TemporalScheduleInfoJSON` field too.
No risks.
No.
=> Remove unindexed fields from index schema template

common/metrics/events.go
nil check and return noop
**Why?**
simplify init of metricHandler
this pattern is employed by consumers of this function.
unit-tests
None
No
=> check for nil config and return noop

service/history/queues/scope.go, service/history/queues/scope_test.go, service/history/tasks/range_test.go, service/history/tasks/test_util.go
- Add history queue scope definition and related methods
**Why?**
- Building blocks for multi-cursor queue
- Unit test
- N/A, not used
- No
=> Multi-cursor components: queue scope

service/history/queues/iterator.go, service/history/queues/iterator_test.go, service/history/queues/range.go, service/history/queues/range_test.go, service/history/queues/scope.go, service/history/queues/scope_test.go, service/history/queues/test_util.go, service/history/tasks/key.go
- Move task range definition to queues package
**Why?**
- Follow up for the comment [here](https://github.com/temporalio/temporal/pull/2973#discussion_r892955325)
- N/A, not used
- No
=> Move task range definition to queues package

common/predicates/all.go, common/predicates/all_test.go, common/predicates/and.go, common/predicates/and_test.go, common/predicates/empty.go, common/predicates/empty_test.go, common/predicates/not.go, common/predicates/not_test.go, common/predicates/or.go, common/predicates/or_test.go, common/predicates/predicates_test.go, service/history/queues/scope.go, service/history/queues/scope_test.go, service/history/tasks/predicates.go, service/history/tasks/predicates_test.go
- Add best effort Equals check for task predicates. Since the check won't try to re-arrange the predicates, the result will contains false negatives even if mathematically two predicates are equivalent.
- ^ is ok as 1. in most cases our predicates are quite simple and should be equal even when form is taken into consideration 2. When false negatives are returned we will simply not merge (attach) two queue slices and there's no cost for correctness and performance. (All it costs is some additional storage costs for storing an additional queue slice scope data, which is negligible)
- Rename `None` predicate to `Empty`
- Split implementations in `common/predicates` to separate files.
**Why?**
- Only two queue slices or queue scopes with equivalent predicate can be merged by …
=> Add equals check for task predicate

common/metrics/events.go, common/metrics/events_scope.go, common/metrics/events_test.go, common/metrics/events_userscope.go, common/metrics/metrics.go, common/metrics/runtime.go, common/sdk/metrics_handler.go, service/history/queues/executable.go, service/history/queues/priority_assigner.go, service/history/queues/rescheduler.go
Adding default MetricOptions where nil was passed
**Why?**
Avoids the overhead of scanning the stack to supply a namespace and helps adjust metric units where necessary
unit tests
None
No
=> add default metricoptions where nil

common/dynamicconfig/config.go, common/dynamicconfig/noop_client.go
improved error message
Because the existing message looks like an Error, but is really only a Debug "comment" and occurs with correct code.
N/A
N/A
NO
=> improve error message

service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/historyEngine3_eventsv2_test.go, service/history/historyEngine_test.go, service/history/timerQueueActiveTaskExecutor_test.go, service/history/timerQueueStandbyTaskExecutor_test.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/visibilityQueueTaskExecutor_test.go, service/history/workflow/mutable_state_impl_test.go, service/history/workflow/mutable_state_rebuilder_test.go, service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go, service/history/workflowTaskHandlerCallbacks_test.go
Rename `dt` and `di` variables to `workflowTask`/`wt`.
**Why?**
Leftover from `decisionTask` to `workflowTask` renames.
N/A
No risks.
No.
=> Rename dt and di variables to workflowTask/wt

service/history/historyEngine.go, service/history/historyEngine_test.go, service/history/workflow/query.go, service/history/workflow/query_registry.go, service/history/workflow/query_registry_test.go, service/history/workflow/query_test.go, service/history/workflowTaskHandlerCallbacks.go
Rename `queryTermination` to `queryCompletion`.
**Why?**
"Termination" is a bad word to indicate completed query. For me is sounds like something bad happened to query and it gets terminated just like `TerminateWorkflow` works. "Completion" sounds better for me.
N/A
No risks.
No.
=> Rename queryTermination to queryCompletion

develop/buildkite/docker-compose.yml, develop/docker-compose/docker-compose.yml
Update mysql image version to support `arm64`.
**Why?**
`mysql:8.0.19` doesn't have `linux/arm64` image and `make start-dependencies` gives an error when run on arm64 (i.e. Mac M1).
Run `make start-dependencies` on Mac M1.
No risks.
No.
=> Update mysql image version to support arm64

develop/docs/macos/cassandra.md
Updating Cassandra install guide to work with MacBook with ARM chip.
**Why?**
Default Cassandra installation comes with an old version of JNA jar file that doesn't include patches to work with Apple ARM chips (ie. M1).
Started Cassandra with `cassandra -f`, and Temporal server with `make start`.
No risks.
No.
=> Update Cassandra install guide for MacBook with ARM chip

common/persistence/serialization/task_serializer.go, service/history/replication/task_executor.go, service/history/replication/task_processor.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/tasks/delete_execution_task.go, service/history/tasks/delete_visibility_task.go, service/history/timerQueueTaskExecutorBase.go, service/history/timerQueueTaskExecutorBase_test.go, service/history/transferQueueTaskExecutorBase.go, service/history/workflow/delete_manager.go, service/history/workflow/delete_manager_mock.go, service/history/workflow/delete_manager_test.go, service/history/workflow/task_generator.go
Don't check delete workflow execution transfer task version.
**Why?**
`DeleteExecutionTask` transfer task is create when workflow is explicitly deleted with `DeleteWorkflowExecution` API call.
There is no need to check task version when processing this task because API request to delete executions is considered to be higher priority than
other processes which might resurrect execution.
Also removed version from `DeleteExecutionVisibilityTask` because it is not used by processor.
No risks.
Yes, for end to end namespace migration tests.
=> Don't check delete workflow execution transfer task version

service/history/queues/iterator.go, service/history/queues/range.go, service/history/queues/range_test.go, service/history/queues/scope.go, service/history/queues/slice.go, service/history/queues/slice_test.go, service/history/queues/test_util.go
- Add history queue slice definition and related methods
- Queue slice is built on top of queue scope and iterator. It's responsible for loading and tracking all tasks within its scope. It can also shrink its scope (range) upon request.
**Why?**
- Building blocks for multi-cursor queue
- Unit test
- N/A, not used
- No
=> Multi-cursor components: queue slice

service/history/shard/context_impl.go
Release shard lock earlier during delete workflow execution.
**Why?**
Delete workflow execution is 4 step process. Shard lock needs to be holded only during first 2 steps, not all 4.
Exisitng tests.
No risks.
No.
=> Release shard lock earlier during delete workflow execution

service/history/shard/context_impl.go
* Adjust shard acquire expiration from 5m to 8s
**Why?**
Setting is not right
N/A
N/A
N/A
=> Adjust shard acquire expiration

common/dynamicconfig/constants.go, service/history/configs/config.go, service/history/historyEngine_test.go, service/history/tests/vars.go, service/history/workflowTaskHandler.go
-  Cancel activity instead of returning an activity task to worker when schedule activity with eager execution command and request cancellation command are in the same workflow task.
- Rename the feature flag from local dispatch to eager execution
**Why?**
- Match the behavior when eager execution is disabled.
- Basically change the behavior of eager execution + cancel from performing operation schedule + start + cancel to schedule + cancel + start (no-op), so that activity will be cancelled instead of started and returned to worker.
- N/A, sdk is still development the feature?
- yes.
=> Cancel activity when eager execution and request cancellation are in the same WFT

common/tasks/benchmark_test.go, common/tasks/interleaved_weighted_round_robin.go, common/tasks/interleaved_weighted_round_robin_test.go
* Perf optimize interleaved weighted round robin scheduler
* Bypass scheduler if there is no other task
* Remove unnecessary shutdown check
**Why?**
```bash
before
BenchmarkInterleavedWeightedRoundRobinScheduler_Sequential-16    	 6610477	       176.0 ns/op	       8 B/op	       1 allocs/op
BenchmarkInterleavedWeightedRoundRobinScheduler_Parallel-16    	 3230086	       346.7 ns/op	       8 B/op	       1 allocs/op
after
BenchmarkInterleavedWeightedRoundRobinScheduler_Sequential-16    	26722878	        46.48 ns/op	       8 B/op	       1 allocs/op
BenchmarkInterleavedWeightedRoundRobinScheduler_Parallel-16    	 4259040	       267.4 ns/op	       8 B/op	       1 allocs/op
```
Updated tests & benchmark
N/A …
=> Perf optimize interleaved weighted round robin scheduler

common/dynamicconfig/constants.go, service/history/configs/config.go, service/history/queueProcessor.go, service/history/queues/executable.go, service/history/queues/executable_test.go, service/history/queues/rescheduler.go, service/history/queues/rescheduler_mock.go, service/history/queues/rescheduler_test.go, service/history/timerQueueActiveProcessor.go, service/history/timerQueueProcessorBase.go, service/history/timerQueueStandbyProcessor.go, service/history/transferQueueActiveProcessor.go, service/history/transferQueueStandbyProcessor.go, service/history/visibilityQueueProcessor.go
- Make task rescheduler has its own goroutine for rescheduling and run in background.
**Why?**
- Currently task rescheduling needs to be explicitly triggered and the trigging is done periodically. This create unnecessary timer/load when there's nothing to reschedule. It also means the task backoff period calculated won't be respected since rescheduling is periodic.
- In multi-cursor implementation, we need to handle the case where a timer task is loaded but not ready for process. In that case, we can directly send the task to rescheduler. But this approach can't work if rescheduling is periodic as that will greatly increase task latency.
- Added new test
- Rescheduler stop working in existing queue impl
**Is hotfix …
=> Run task rescheduler in background

service/history/shard/context_impl.go
This reverts commit e52d10e96ba7493fad09ad6325f2afe401dc1ff6.
**Why?**
Seem that it is by design to retry shard ownership assertion forever until shard ownership lost happen 
N/A
N/A
N/A
=> Revert "Adjust shard acquire expiration (#3032)"

common/persistence/sql/sqlplugin/sqlite/driver.go, common/persistence/sql/sqlplugin/sqlite/plugin.go, common/persistence/sql/sqlplugin/tests/sqlite_test.go, config/development-sqlite-file.yaml
Change in how SQLite dsn is constructed to match upstream driver
**Why?**
Support multiple pragma statements
Change in upstream driver for file uri
Updated unit tests
Local dev environment
None
Yes
=> add support for multiple pragma statements and driver syntax

common/persistence/dataInterfaces.go, host/xdc/integration_failover_test.go, service/history/nDCHistoryReplicator.go, service/history/nDCHistoryReplicator_test.go, service/history/replication/ack_manager.go, service/history/replication/task_processor.go, service/history/replication/task_processor_test.go
1. Handle sync workflow state task in dlq.
2. Backfill history when history check and handle ancestor branch information correctly.
**Why?**
Correctness issue
New unit tests and functional tests.
Yes.
=> Update backfill history in sync workflow state

service/history/nDCHistoryReplicator.go
Clean up history branch ancestor operation
**Why?**
Save copy ancestors
Unit tests
=> Clean up history branch ancestor operation

Makefile, common/archiver/s3store/mocks/generate.go, common/archiver/s3store/mocks/generate.sh
Move the `external-mocks` Makefile target to a script called by go:generate.
Get rid of the `mocks` target and just call `go-generate` (which does mostly mocks and also some other stuff).
**Why?**
Consistency, so that all code generation happens via go:generate and can be easily done per-package without the Makefile.
Ran make targets.
=> Move external-mocks to go:generate

service/worker/scheduler/workflow.go, service/worker/scheduler/workflow_test.go
Fix npe if update signal payload has a nil Schedule
**Why?**
This shouldn't happen with existing clients, but if it does, the workflow would get stuck due to failing workflow tasks.
unit test
=> Fix potential npe in scheduler workflow update signal

service/history/timerQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor.go
Fix error shadowing in standby executors.
**Why?**
`err` variable was recreated in `else` block and wasn't logged properly. 
No risks.
Yes, although error shadowing affects logging only.
=> Fix error shadowing in standby executors

service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor_test.go
- Handle unimplemented errors when calling verification api by skipping the verification
- Do not clear mutable state cache when verification api fails as there's no error in the current workflow.
**Why?**
- Improve error handling.
- Yes
=> Improve error handling for standby transfer task verification

service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor_test.go
- Handle workflow already completed error when verifying first workflow task scheduled
**Why?**
- We should not retry verification when workflow is already completed.
- Unit test
- Yes
=> Handle workflow already completed when verifying first workflow task scheduled

service/history/historyEngine.go
- Fix failover predicate in namespace failover callback
**Why?**
- If notification version in shard is X, we don't know if the failover queue processing for ns notification version X-1 is completed or not. 
- NOTE: we assume the processing for notification version X-2 is completed, which is not theoretically true. But true in reality when there's no continuous shard reload & namespace failover.
- More load on shard reload. Need to start failover queue as well.
=> Fix namespace failover callback

common/namespace/registry.go
- Do not hold lock when running namespace change callback
**Why?**
- Prevent deadlock in one shard from affecting all other shards on a host and block shard controller.
- No need to hold the lock anyway when running callback
- Yes
=> Do not hold lock when running namespace change callback

service/history/historyEngine.go, service/history/replication/ack_manager.go, service/history/replication/task_processor.go, service/history/replication/task_processor_manager.go, service/history/replication/task_processor_manager_test.go, service/history/replication/task_processor_test.go
1. Move replication task cleanup to processor manager.
2. Use less aggressive retry in fetching tasks
**Why?**
The current logic only do cleanup when there is remote cluster connected. If all remote cluster disconnect, it should cleanup all the tasks.
Unit tests
=> Move replication task cleanup to processor manager

common/persistence/visibility/store/elasticsearch/visibility_store.go, common/searchattribute/encode_test.go, common/searchattribute/encode_value.go, common/searchattribute/encode_value_test.go, host/elasticsearch_test.go
1. Search attributes map are encoded to `Payload` and then back to `map[string]interface{}`. When decoding `nil` values, they are currently being decoded to the respective zero value. This PR changes this behavior so that encoded `nil` values are decoded as `nil` values.
2. Just with change described above, fields with `nil` or empty slice value won't be added to ES document and essentially will be removed. This behaviour is similar to existing behaviour for empty slice values. However, I'm changing so that fields with `nil` or empty slice value are not even created.
**Why?**
This is to support removing search attributes from ES. For example, calling `UpsertSearchAttribute([]string{"CustomField": nil})` would delete the search attribute `CustomField`.
Closes #561.
**How …
=> Add ability to clear search attributes

service/worker/scheduler/spec.go, service/worker/scheduler/spec_test.go
In cases where there was exactly one future scheduled time, the jitter limit calculation didn't check that the following future time actually existed. This would result in a negative value being used, which would result in a potentially large jitter value (up to 50 days), even if no jitter was configured.
**Why?**
fixes the calculation
new unit test plus manual tests
This may break determinism for scheduler workflows, but it's still worth it to fix since it's a correctness issue. Impacted schedules can be deleted and recreated.
yes
=> Fix schedule jitter calculation bug

service/history/transferQueueStandbyProcessor.go
- Do not double execute close execution task if visibility archival is disabled
**Why?**
- For standby task that doesn't have side effect, we don't have to force execute it.
- Yes
=> Do not double execute close execution task if visibility archival is disabled

service/frontend/fx.go
Cherry-picked #3080 to release/v1.16.x
**Why?**
This fix is needed in v1.16
Unit/integration tests
I don't see any
Absolutely
=> Cherry pick pr3080 for 1.16

Makefile, tools/common/schema/types.go, tools/sql/README.md, tools/sql/clitest/setuptaskTest.go, tools/sql/handler.go, tools/sql/main.go
Add optional `--defaultdb` flag to sql tool to be used as default db for the tool to connect to.
**Why?**
To address issue #2890. It was attempted by PR #2892 but was reverted by PR #2949. 
Tested locally on both mysql and postgres, for commands `create`, `setup-schema`, `update-schema` and `drop`.
`make install-schema-mysql`
`make install-schema-postgresql`
The `--database`/`--db` local flag for create/drop is now removed. So any script trying to create/drop db will break. The fix is to use existing global flag `--database`/`--db`. 
`auto-setup` docker image scripts are changed [here](https://github.com/temporalio/docker-builds/pull/54).
No.
=> Add optional --defaultdb flag to sql tool

common/log/tag/values.go, host/onebox.go, temporal/fx.go
We got rid of fx logging with NopLogger in #2091, but that swallows some useful errors.
This integrates fx logging into our logging system, with most logs at Debug level, but errors at Error (and one at Info).
The code is adapted from https://github.com/uber-go/fx/blob/master/fxevent/zap.go, which is MIT-licensed. We already have the required attribution and copyright notice at the top of this file, so no additional attribution is needed (as far as I know).
**Why?**
So we can see errors from fx for debugging
Manual testing
Log spam, but fx shouldn't be doing anything after startup, and I verified that a successful startup doesn't log anything.
=> Do fx logging properly

common/metrics/defs.go, service/worker/deletenamespace/deleteexecutions/workflow.go, service/worker/deletenamespace/reclaimresources/activities.go, service/worker/deletenamespace/reclaimresources/workflow.go, service/worker/deletenamespace/reclaimresources/workflow_test.go
Fix `deleteexecutions` iterator.
**Why?**
Due to concurrency between `DeleteExecutionsActivity` and `GetNextPageTokenActivity` previous version could skip records.
Running locally with 20k workflow executions in namespace.
**Potential risks** 
No risks.
No, because workflow has retry policy and eventually all executions are deleted.
=> Fix deleteexecutions iterator

common/persistence/cassandra/errors.go, common/persistence/cassandra/errors_test.go, common/persistence/cassandra/mutable_state_store.go
Fix an issue where the history service would get stuck in a loop when reusing workflow ID's on top of ScyllaDB.
**Why?**
Closes https://github.com/temporalio/temporal/issues/2683.
First reproduced the issue by running Temporal on top of Scylla locally; then verified that the change fixed the issue. Ran Cassandra persistence tests to ensure that this change didn't break anything else.
As noted in the linked issue:
> Not sure if there are conditions when Cassandra might also return nullable rows.
If there are cases where we should be handling `nil` rows as real errors, this change would break that.
No.
=> Fix workflow ID reuse when running on ScyllaDB

service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/workflowTaskHandlerCallbacks.go, service/history/workflowTaskHandlerCallbacks_test.go
Background context: https://github.com/temporalio/temporal/issues/3062
In this draft, for the 2 verification APIs (verify first workflow task schedule and verify child result recorded)
- Return nil, when workflow already completed. 
- Return not found error when workflow not found. Basically when caller gets NotFound error it's always workflow not found, not workflow already completed.
**Why?**
- Improve error handling logic. make it easier to understand
- Unit test
- n/a
- yes.
=> Improve verification APIs error handling

service/history/handler.go, service/history/shard/controller_impl.go, service/history/shard/controller_test.go
PR #2745 changed the behavior of `GetShardByID` to not block on shard acquisition, where it did before. This changed the behavior of `acquireShards` in the shard controller to not limit concurrency at all. This restores the previous behavior of `acquireShards` and fixes the flaky test.
The `ctx` parameter to `GetShardByID` and `GetShardByNamespaceWorkflow` is removed since it's unused.
Also added some comments about blocking/lease acquisition behavior.
**Why?**
Restore previous behavior. We should have some limit on shard acquisition concurrency.
Existing tests
=> Fix concurrency of shard acquisition and flaky test

service/history/handler.go, service/history/replication/dlq_handler.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/shard/controller_impl.go, service/history/shard/controller_test.go, service/history/timerQueueActiveProcessor.go, service/history/timerQueueStandbyProcessor.go, service/history/transferQueueActiveProcessor.go, service/history/transferQueueStandbyProcessor.go, service/history/workflow/context.go, service/history/workflow/transaction_impl.go, service/history/workflow/transaction_test.go
Every use of `GetEngine` has a `Context` available, so we can just always use the `WithContext` version, and then we can rename it to just `GetEngine` to be clearer.
**Why?**
simpler interface
unit tests
not much
=> Make shard.GetEngine always take Context

common/metrics/api_metrics.go, common/metrics/api_metrics_test.go, common/metrics/defs.go, service/frontend/operator_handler.go
Fix metrics for operator service. Avoid duplication of the metrics from different places.
**Why?**
Metrics is handled by telemetry interceptor already, remove dup metrics from operation handler.
Also fix the operation tag on metrics emit by telemetry for operation service APIs.
Tested locally, verify metrics for operation API are emitted correctly.
service_requests{namespace="_unknown_",operation="OperatorDescribeCluster",service_name="frontend"} 1
service_error_with_type{error_type="serviceerror_Unimplemented",namespace="_unknown_",operation="OperatorDescribeCluster",service_name="frontend"} 1
No
No
=> Fix metrics for OperatorService

service/frontend/dcRedirectionHandler.go, service/history/queueProcessor.go, service/history/timerQueueProcessor.go, service/history/timerQueueProcessorBase.go
- Consume ratelimiting token from host level rate limiter first and then the shard level one.
- Check rescheduler size after ratelimiting check
**Why?**
- Avoid unnecessary ratelimiter reserve & cancel (for shard level ratelimiter)
- Avoid unnecessary dynamic config loading/checking
- yes
=> Fix queue rate limiting busy loop

client/admin/metric_client.go, client/admin/metric_client_gen.go, client/clientfactory.go, client/frontend/metric_client.go, client/frontend/metric_client_gen.go, cmd/tools/rpcwrappers/main.go
The grpc wrappers for frontend/admin clients used different code than for matching/history clients. This consolidates them all to use the matching/history version, which is more feature-ful: it logs errors, and adds an error type tag to `client_errors`.
**Why?**
Fixes #3117: this makes all uses of the `client_errors` metric have the same set of tags.
Also, having one version of the logic is simpler (even if the code is duplicated).
existing tests
=> Consolidate rpc client metrics logic

service/history/shard/controller_test.go
Add test that does random sequences of shard load/unload concurrenctly
**Why?**
To catch potential bugs in shard controller and shard context load/unload logic
is a test
=> Add fuzz-style test for shard controller

service/history/queues/rescheduler_test.go
- Fix task rescheduler flaky test
**Why?**
- In this test, if a mock task's reschedule time is very short and rescheduling happens before all tasks are added to the rescheduler, later task won't be able to be added because the rescheduler's lock is held by the reschedule loop, which is blocked on the un-buffered `taskCh` defined on L93.
=> Fix task rescheduler flaky test

common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Remove `RunId` from visibility query sort for ES v7.
**Why?**
Improve query performance
Manually sending queries to ES
Duplicate or missing entries when doing pagination.
Although this is unlikely because both closed time and start time has nano seconds precision in ES v7.
For ES v6 this is not changed because date has only milliseconds precision and collisions are more likely.
Could be.
=> Remove RunId from visibility query sort for ES 7

common/dynamicconfig/constants.go, service/frontend/workflowHandler.go, service/worker/common/interface.go, service/worker/pernamespaceworker.go, service/worker/pernamespaceworker_test.go, service/worker/scheduler/fx.go, service/worker/service.go
Rearrange per-namespace worker manager to always run all components in the same worker+client+task queue.
**Why?**
Reduces load when we have more than one component.
updated unit test
=> Run one per-ns worker per namespace instead of namespace × component

common/persistence/dataInterfaces.go, service/matching/matchingEngine_test.go, service/matching/taskGC.go, service/matching/taskReader.go, service/worker/scanner/taskqueue/handler.go
Check for task expiration after tasks come out of the task buffer, before they're dispatched. This is before the rate limiter is checked, so these tasks won't consume rate limit tokens.
**Why?**
Fixes #3150 
Modified unit test
=> Don't dispatch expired tasks from taskReader buffer

common/metrics/defs.go, service/matching/taskQueueManager.go
**Add a new metric counter `NoRecentPollerTasksPerTaskQueueCounter` to track # of AddTask calls when no recent pollers exist.**
[Issue](https://github.com/temporalio/temporal/issues/3144)
**Tested locally via prometheus**
=> Add metrics to detect no poller issue

host/onebox.go, service/worker/fx.go, service/worker/migration/fx.go, service/worker/scheduler/fx.go
Config worker use public frontend endpoint
**Why?**
Config worker use public frontend endpoint should use the endpoint from public client config.
=> Config worker use public frontend endpoint

common/config/config.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go, common/persistence/nosql/nosqlplugin/cassandra/translator/fixed_address_translator.go, common/persistence/nosql/nosqlplugin/cassandra/translator/fixed_address_translator_test.go, common/persistence/nosql/nosqlplugin/cassandra/translator/translator_plugin.go, docker/config_template.yaml, tools/cassandra/cqlclient.go, tools/cassandra/handler.go, tools/cassandra/main.go, tools/common/schema/types.go
This PR adds the possibility to specify so called address translator for Cassandra nodes. Address translation is well-known feature in Datastax Java driver as well as in gocql driver.
Address translation is used in case the client can not resolve the IP addresses which Cassandra gocql driver returns. This happens in case when, for example, Cassandra nodes are running behind some kind of a proxy or load balancer so internal IP addresses do not make sense to the client side. Address translator solves this so the addresses are meaningful.
In Temporal context, we need to run Cassandra nodes in Amazon PrivateLink setup. This is very much deployment specific but the basic idea is that you have a running Cassandra cluster in one VPC and temporal server in the other and you are …
=> add address translation to Cassandra persistence

common/metrics/config.go, common/metrics/tally_metrics_handler.go, common/metrics/tally_metrics_handler_test.go
- Switch back to tally.Timer instead of histogram for timer metrics. The reason is that when using histogram.RecordDuration, if the duration is higher than the max bucket defined, an Inf value will be added to the sum metric emitted and breaks the average calculation. When using histogram.RecordValue, if value is higher than the max bucket defined, no metric will be emitted for the sum metric, and make it inaccurate. Also for RecordValue, the value added to the sum metric is always the defined bucket boundary instead of the actual metric value. 
- tally.Timer implementation has none of the problems mentioned above.
- However there's no when to specify the buckets when emitting tally.Timer metric, and the default reporter bucket will be used. So wired up the code to …
=> Fix tally timer metric

common/persistence/nosql/nosqlplugin/cassandra/translator/fixed_address_translator_test.go
Fixed unit test for Cassandra fixed address translator.
**Why?**
Unit test was failing because the translator converts the IP to IPv4 while in the test it was not (the function to get the `temporal.io` IP is in IPv6).
Ran unit test.
No risks.
No.
=> Fix Cassandra fixed address translator unit test

service/worker/scanner/history/scavenger.go
Add more history scavenger heartbeat to prevent heartbeat timeout
**Why?**
When there are large number of history branch whose age is within check threshold, it could result in all of them get skipped and no heartbeat for a long time that could lead to heartbeat timeout and new activity will be retried but the old one won't notice until next branch get checked and heartbeat happens. 
eye balls.
No
=> additional history scavenger heartbeat

common/persistence/persistenceRateLimitedClients.go, common/persistence/persistenceRetryableClients.go
There was a git merge race condition lately between introducing the new
executionRetryablePersistenceClient definition and introducing the new
NewHistoryBranch interface function that was uncaught by the auto merge.
**Why?**
=> Add missing NewHistoryBranch

service/history/shard/context_impl.go
- Use detached context for shard context operations
**Why?**
https://github.com/temporalio/temporal/issues/3178
- Maybe
=> Use detached context for shard context operations

common/persistence/cassandra/history_store.go, common/persistence/client/fault_injection.go, common/persistence/dataInterfaces.go, common/persistence/history_manager.go, common/persistence/mock/store_mock.go, common/persistence/persistence-tests/historyV2PersistenceTest.go, common/persistence/persistenceInterface.go, common/persistence/sql/history_store.go, service/history/workflow/mutable_state_impl.go
=> Push serialization of history branch from history manager down to history store

service/frontend/workflowHandler.go, service/worker/scheduler/workflow.go
Prefix the workflow IDs of scheduler workflows with a constant string.
**Why?**
To avoid potential conflicts between user-chosen workflow IDs and schedule IDs, after we hide schedules from workflow visibility by default with "namespace divisions" in #3123.
manual test
If anyone has schedules created before this, they won't be able to interact with them through the schedule api, they'll have to terminate the workflows with the workflow api and recreate them.
maybe
=> Use a prefix for scheduler workflow ids

tools/tdbg/commands.go
* Default to unix time 0, instead of time.Time{}
**Why?**
UnixNano of time.Time is not well defined
```
Note that this means the result of calling UnixNano on the zero Time is undefined.
```
N/A
N/A
N/A
=> Default to unix time 0, instead of time.Time{}

service/history/queueProcessor.go, service/history/shard/context_impl.go, service/history/shard/controller_impl.go, service/history/timerQueueProcessor.go, service/history/timerQueueProcessorBase.go, service/history/transferQueueProcessor.go, service/history/visibilityQueueProcessor.go
* Fix shard close error type: unavailable -> shard ownership lost
**Why?**
Wrong error type
N/A
N/A
N/A
=> Fix shard close error type

service/history/fx.go, service/history/workflow/delete_manager.go, service/history/workflow/delete_manager_test.go, service/worker/archiver/client.go, service/worker/archiver/client_test.go
- The fix depends on https://github.com/temporalio/temporal/pull/3148
- Do not call history client to delete workflow execution after inline archival is done
- Get workflow close event (for getting close time) before attempting archival.
**Why?**
- When deleting workflow execution, we already held the workflow lock. Calling history client delete workflow execution will try to lock the workflow again, which is guaranteed to fail. 
- Old versions (before the linked PR) of archival workflow will delete history after history archival is done. If workflow close event is read after sending archival request, the history may already gone and result in infinity task retry.
- Unit test.
- Yes.
=> Fix inline history archival

common/util.go, service/history/queues/executable.go
- Allow task to be re-submitted (put to the end of the task channel) upon resource exhausted errors
(Persistence will prioritize frontend/API requests anyway, so this won't be an issue. )
- Reduce initial task reschedule interval, as now the task rescheduling is triggered based on needs, not periodically. Also reduced resubmitMaxAttempts now that the initial task rescheduling interval is reduced.
- Use different reschedule policy for ErrTaskRetry, which can only be resolve by waiting for replication to happen.
**Why?**
- Previous penalty for task processing upon resource exhausted error seems too high and greatly increased the task latency (after removing all the retries during task processing, done by the simplify retry PR).  
- Tested in test …
=> Improve task processing retry behavior

service/worker/archiver/activities.go, service/worker/archiver/activities_test.go, service/worker/archiver/handler.go
- Do not mark all activities errors as non-retryable 😞 
- Change the condition for what errors is non-retryable for workflow deletion, more specifically, workflow not ready error and context errors (like context deadline exceeded, since each new attempt get a new startToClose timeout) should be retryable.
**Why?**
- Bug fix
- Tested locally
- Updated unit test
- Yes.
=> Fix archival activities error handling

service/history/historyEngineInterfaces.go, service/history/historyEngineInterfaces_mock.go, service/history/queueProcessorBase.go, service/history/timerQueueProcessorBase.go
- Fix failover queue shutdown
**Why?**
- Failover queue shutdown doesn't follow the normal stop path. Instead stop is triggered from the ack manager. Currently this shutdown logic only shutdown the processor base, not the entire processor. This mean the failover queue worker pool is not stopped and lead to goroutine leak.
- Will do local test
- Yes.
=> Fix failover queue shutdown

service/frontend/workflowHandler.go, service/frontend/workflowHandler_test.go
Required for SDK to know whether it can send the server encoded failures.
=> Add EncodedFailureAttributes to supported capabilities

common/persistence/visibility/store/elasticsearch/client/client_factory.go, common/persistence/visibility/store/elasticsearch/client/client_v7.go, develop/buildkite/docker-compose-es8.yml, develop/buildkite/pipeline.yml, develop/buildkite/scripts/coverage-report.sh, host/testdata/es_v8_index_template.json
Added support for ES8 and added integration test with ES8 to buildkite pipeline.
**Why?**
N/A
Ran locally with ES8 and ran integration tests.
None.
No.
=> Add support for ES8

service/history/replication/task_processor.go
* Do not enqueue replication task to DLQ if shard shutdown
**Why?**
Avoid unnecessary noise
N/A
N/A
N/A
=> Do not enqueue replication task to DLQ if shard shutdown

common/testing/mocksdk/generate.sh
Update script `common/testing/mocksdk/generate.sh` to be compatible with MacOS.
**Why?**
Default `sed` in MacOS cannot match whole words, ie., `\<word\>` and `\bword\b` don't work.
This PR removed those whole words markers as it should work without as well (at least for now).
Re-generated the files and they are the same.
In the future, if the generated code includes the word `internal` as sub-string of any word, this might mess up.
No.
=> Make mocksdk/generate.sh compatible with macos

service/history/queues/queue_scheduled.go, service/history/queues/queue_scheduled_test.go, service/history/queues/reader.go, service/history/queues/reader_test.go
- Please check the in-line comment
**Why?**
- Please check the in-line comment
- Tested in test cluster
=> Multi-cursor: fix scheduled task precision issue

cmd/server/main.go, common/authorization/authorizer.go, common/config/loader.go
Creating the flag `--no-auth` to disable authorizer, ie., use the `noopAuthorizer` which allows everything. Also adding a warning log if no authorizer is set in config and the flag is missing.
**Why?**
Issue #3171: we want to make explicit that no authorizer is being used, and enforce in the future the use of an authorizer.
Started temporal server in different ways using `--no-auth` flag and the env var `TEMPORAL_NO_AUTH`.
No risks.
No.
=> Add `--allow-no-auth` flag to allow noopAuthorizer

Makefile
This commit allows SQL authentication override via env vars SQL_USER and SQL_PASSWORD,
and maintain the default values if those env vars are not set.
**Why?**
The tools/sql/README.md instructions ask user to pass in SQL
username/password via environment variables. However the scripts in
Makefile to install SQL schemas hard code username/password, effectively
rendering temporal-sql-tool's instructions invalid. This cause
confusion/frustration for end-users trying to set up Temporal the first
time.
I manually ran `make install-schema-sql` and `make install-schema-postgresql` and verified that the schemas were created successfully. I ran with both SQL_USER/SQL_PASSWORD env vars set and not set to make sure the expected behaviors are met.
**Potential …
=> Fix Makefile to match temporal-sql-tool's instructions

service/matching/matchingEngine.go, service/matching/task.go
- Use shorter timeout for recording workflow/activity task started.
**Why?**
- Please check in-line comment in the PR. Main idea is currently is using long poll context timeout which is too long.
=> Shorten timeout used for recording task started

common/membership/rpMonitor_test.go, common/membership/rpServiceResolver.go, common/membership/rp_cluster_test.go
Currently, `ringpopServiceResolver` listens for events from ringpop, translates them to our own types, and sends them to registered listeners on the `ringpopServiceResolver`. Events are sent when and only when it gets an event from ringpop.
But sometimes there can be an observable change to the hash ring without ringpop sending an event. This seems to happen during startup, when `refresh` gets called to rebuild the ring. `refresh` is called on every event from ringpop, but it's also called periodically, or after a failed lookup, and apparently those calls can cause observable changes also.
This change moves the generation of our events into `refresh`, so we're sure to always generate an event on any observable change. Also, the addresses in the event now have the grpc …
=> Send ringpopServiceResolver events on diffs instead of ringpop events

common/future/future_test.go
Added a new unit test for a subtlety of future.go
**Why?**
I'm about to rely on this behavior elsewhere.
`go test` + buildkite
None
No
=> Add a unit test for future.Get behavior

common/util.go, service/frontend/fx.go
Remove frontend handler retries.
**Why?** 
Retries on frontend handler level may lead to unexpected `InvalidArgument` errors. Closes #3282.
No risks.
Yes.
=> Remove frontend handler retries

tools/cassandra/README.md
Changes the README in the tools/cassandra directory. 
**Why?**
That README states the default consistency is `QUORUM`, but the config defaults to `LOCAL_QUORUM` at https://github.com/temporalio/temporal/blob/5ab8ab804fa3e0998f419260b4424154419428d9/common/config/config.go#L301
Just a README change
Potential misinformation if the behavior is not as described in the config comment and code [here](https://github.com/temporalio/temporal/blob/master/common/config/persistence.go#L146-L165) (I verified the code, but still, it's a new codebase)
No
=> fix cassandra tool consistency readme to reflect the config default

common/resource/fx.go, common/sdk/factory.go, common/sdk/factory_mock.go, go.mod, go.sum, host/onebox.go, service/frontend/adminHandler.go, service/frontend/adminHandler_test.go, service/frontend/operator_handler.go, service/frontend/operator_handler_test.go, service/worker/archiver/client.go, service/worker/archiver/client_test.go, service/worker/archiver/client_worker.go, service/worker/batcher/activities.go, service/worker/batcher/batcher.go, service/worker/parentclosepolicy/client.go, service/worker/parentclosepolicy/processor.go, service/worker/pernamespaceworker.go, service/worker/pernamespaceworker_test.go, service/worker/service.go, service/worker/worker.go
Use a new feature in https://github.com/temporalio/sdk-go/pull/881 to share a single grpc connection across all sdk clients in one service.
The GetSystemClient/NewClient methods now don't take a logger, they get it from fx. This was confusing anyway since there are several calls to GetSystemClient with differently-tagged loggers and the first one will "win".
**Why?**
Reduce resource usage on worker and frontend when using many sdk clients.
integration tests. will do another scale test later after some more related changes.
=> Share grpc connections across sdk clients

client/admin/client.go, client/admin/client_gen.go, client/clientBean.go, client/clientFactory_mock.go, client/clientfactory.go, client/frontend/client.go, client/frontend/client_gen.go, cmd/tools/rpcwrappers/main.go, common/config/config.go, common/membership/grpc_resolver.go, common/membership/interfaces.go, common/membership/interfaces_mock.go, common/membership/rpServiceResolver.go, common/resource/fx.go, common/rpc.go, common/rpc/rpc.go, common/rpc/test/rpc_localstore_tls_test.go, host/onebox.go, host/simpleServiceResolver.go, service/worker/fx.go
After splitting frontend rpc connections into local/remote, we can go further and push resolution and load balancing into grpc using a custom resolver. This lets us use the same mechanism for the SDK clients also.
This registers a grpc resolver using the `membership:` scheme, which takes a service name (`frontend`) and uses the service resolver (ringpop) to resolve it to a set of host+ports.
By default the existing `publicClient.hostPort` setting is used. If that setting is removed, then the new membership mechanism will be used.
**Why?**
- simplified configuration: don't need to configure an endpoint for frontend.
- consistency: internal connections to frontend use membership like connections to matching/history; sdk clients uses same mechanism as other clients.
**How …
=> Use custom grpc resolver for frontend connections

host/dynamicconfig.go, host/onebox.go, host/schedule_test.go, host/test_cluster.go, host/testdata/clientintegrationtestcluster.yaml, host/testdata/es_v7_index_template.json, host/testdata/es_v8_index_template.json, host/testdata/integration_elasticsearch_cluster.yaml, host/testdata/integration_namespace_cluster.yaml, host/testdata/integration_sizelimit_cluster.yaml, host/testdata/integration_test_cluster.yaml, host/testdata/ndc_integration_test_clusters.yaml, host/testdata/schedule_integration_test_cluster.yaml, host/testdata/xdc_integration_es_clusters.yaml, host/testdata/xdc_integration_test_clusters.yaml, host/versioning_test.go, service/frontend/service.go, service/frontend/workflow_handler.go, service/worker/pernamespaceworker.go, service/worker/scheduler/fx.go, service/worker/scheduler/workflow.go
- Switch the default for `frontend.enableSchedules` and `worker.enableScheduler` dynamic config to true.
- Add a few integration tests for schedules.
- Resolve `OverlapPolicy` to default value (skip) eagerly.
- Fix some bugs:
- update did not properly validate input or apply search attribute mapping
- describe did not undo search attribute mapping
- Integration test configuration changes
- remove override of tq partition count (so tqs will use structured default: 4, except 1 for per-ns worker)
- get rid of `enableindexer`, just use the presence of `esconfig` to turn on advanced visibility
- add `startworkeranyway` to force worker to be on (for scheduler)
- add missing search attributes to `testdata/es_v{7,8}_index_template.json`
- add timeout on shutdown. we can remove …
=> Enable schedules by default and add integration tests

service/history/queues/scheduler.go
- Improve task scheduler namespace change callback so that task channel weight update is only trigger upon namespace failover.
**Why?**
- Namespace registry will invoke the callback on every namespace cache refresh, even though there's no namespace update.
- Tested locally.
=> Improve task scheduler namespace change callback

service/history/nDCTaskUtil.go, service/history/queues/executable.go, service/history/queues/executable_mock.go, service/history/queues/executable_test.go, service/history/queues/executor_wrapper.go, service/history/queues/metrics.go, service/history/queues/queue_base.go, service/history/timerQueueActiveTaskExecutor.go, service/history/timerQueueActiveTaskExecutor_test.go, service/history/timerQueueStandbyTaskExecutor.go, service/history/timerQueueStandbyTaskExecutor_test.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/visibilityQueueTaskExecutor.go, service/history/visibilityQueueTaskExecutor_test.go
- Revert part of changes in https://github.com/temporalio/temporal/pull/3279
- Return necessary metrics tags from executor instead of let executor generate metric tags
**Why?**
- Executor doesn't know all the task type as there may be injected queues.
- Tested on test cluster
=> Add metrics tags back to task executor response

service/history/queues/queue_scheduled.go, service/history/timerQueueActiveTaskExecutor.go, service/history/timerQueueStandbyTaskExecutor.go, service/history/workflow/timer_sequence.go, service/history/workflow/timer_sequence_mock.go
- Use millisecond as precision when determine if timer has expired.
**Why?**
Background context here: https://github.com/temporalio/temporal/pull/3255
- Multi-cursor impl will truncate tasks visibility timestamp into millisecond so that tasks returns from cassandra are ordered.
- However, some task processing logic will use the truncated timestamp to check if a timer is expired or not. This will fail as task visibility timestamp has been truncated, but the time stored in mutable state is not. So when doing comparison, we need to truncate both.
- Note this won't make timer fire one millisecond before the schedule time as
- For multi-cursor, we manually added one ms back when scheduling the task
- For non multi- cursor, task timestamp is not truncated and if task timestamp …
=> Multi-cursor: fix timer task precision

service/history/queues/executable.go, service/history/queues/queue_base.go, service/history/queues/reader.go, service/history/queues/reader_group_test.go, service/history/queues/reader_test.go, service/history/queues/slice.go, service/history/queues/slice_test.go, service/history/queues/tracker.go, service/history/timerQueueFactory.go, service/history/transferQueueFactory.go, service/history/visibilityQueueFactory.go
- Shrink queue slice predicate when # of pending namespaces are low.
- Force create new queue slice every 5mins
**Why?**
- Shrink predicate is another way of checkpoint processing progress so that upon reload few # of tasks needs to be reprocessed
- Shrink predicate is only possible when all tasks for a slice has been loaded. But this may not be true for the last slice in default reader and new slice may keep merge into it. So force create new slice every 5mins, and rely on slice count monitoring & action to combine them if # of slices becomes large.
- Force creating new slice also means if task unloading is needed, we won't unload all tasks for a namespace at once. But can unload only tasks from some slices, while others are still in memory for processing.
**How did you …
=> Multi-cursor: shrink slice predicate

common/tasks/interleaved_weighted_round_robin_test.go, service/history/queues/queue_base.go, service/history/queues/queue_base_test.go
- Fix task deletion: previously task deletion will be skipped if there's no pending slices in the queue. Instead, when there's no pending slices, we should delete tasks up to (<) the min of non-readable range.
- Some code refactoring
- Also uncomment the code for emitting pending task metrics.
**Why?**
- Otherwise tasks may left in db undeleted.
- Added test. Tested in test cluster.
=> Multi-cursor: fix task deletion

common/util.go, service/history/queues/executable.go
- Slow down task scheduling upon resource exhausted based on the # of continuous resource exhausted errors
**Why?**
- Existing impl reschedules task too aggressively upon resource exhausted.
=> Slow down task scheduling upon resource exhausted

api/adminservice/v1/service.pb.go, api/historyservice/v1/service.pb.go, api/matchingservice/v1/service.pb.go, client/frontend/client_gen.go, client/frontend/metric_client_gen.go, client/frontend/retryable_client_gen.go, common/metrics/defs.go, go.mod, go.sum, host/workflow_delete_execution_test.go, service/frontend/configs/quotas.go, service/frontend/configs/quotas_test.go, service/frontend/dcRedirectionHandler.go, service/frontend/interface_mock.go, service/frontend/operator_handler.go, service/frontend/operator_handler_test.go, service/frontend/service.go, service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go
Move `DeleteWorkflowExecution` to workflow service.
**Why?**
https://github.com/temporalio/api/pull/233.
Move is a breaking change, exiting clients that use `DeleteWorkflowExecution` will stop to work, but this API is used by `tctl v2` only which is in beta.
No.
=> Move DeleteWorkflowExecution to workflow service

service/worker/service.go
Change default history scavenger min age to 60 days
**Why?**
Keep same behavior as 1.17.
=> Use 60 days as history scavenger min age

service/history/queues/mitigator.go, service/history/queues/mitigator_test.go, service/history/queues/monitor.go, service/history/queues/monitor_test.go, service/history/queues/reader.go
- Move queue alert dedup logic from mitigator to queue monitor
**Why?**
- The dudup logic in mitigator does work as: Alert is received from alert channel only after previously alerts's action has completed, so mitigator will never see duplicated alerts.
- New unit test. Tested locally.
=> Multi-cursor: move alert deduping to queue monitor

Makefile, service/history/queues/action_slice_predicate.go, service/history/queues/queue_base.go, service/history/queues/queue_base_test.go, service/history/tasks/predicates.go
- Add slice predicate action which will be run upon checkpointing queue state
**Why?**
- slicePredicateAction will move all slices in default reader, with non-universal predicate to the next reader so that upon restart task loading for those slices won't blocking loading for other slices in the default reader.
- Slice.ShrinkScope() will shrink its predicate when there's few namespaces left. But those slices may still in the default reader. If there are many such slices in the default reader, then upon restart task loading for other namespace will be blocked. So we need to move those slices to a different reader.
- Unit test
=> Multi-cursor: slice predicate action

go.mod, go.sum, service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go
Set upsert memo capability.
**Why?**
Indicate if the server support upsert memo
`make unit-test`
No.
No.
=> Set upsert memo capability

service/history/queues/action_slice_count.go
- Take slice predicate into consideration when compacting slices.
- Refactor slice count action implementation
**Why?**
- When compacting two slices, the resulting predicate will be the union of the two predicates. If one of them is Universal, then the resulting one will also be universal. In the worst case, this will make all slices in a reader to have universal predicate and causing all tasks to be reprocessed upon shard reload.
- Testing locally.
=> Multi-cursor: Improve slice count action

common/persistence/visibility/store/elasticsearch/client/aws.go, go.mod, go.sum
Remove ES6 client.
**Why?**
Elasticsearch v6 support is removed in #3184. This is just some leftover.
N/A
No risks.
No.
=> Remove ES6 client

common/persistence/visibility/store/elasticsearch/visibility_store.go, common/searchattribute/mapper.go, common/searchattribute/mapper_test.go, service/frontend/workflow_handler.go, service/history/workflowTaskHandler.go
Clone request if search attributes are mapped.
**Why?**
To insure idempotence of handler functions.
Exixting tests.
No risks.
No.
=> Clone request if search attributes are mapped

common/util.go, service/frontend/fx.go
Revert 'Remove frontend handler retries (#3285)'.
**Why?**
Frontend retries were removed in #3285 but the root cause was addressed in #3299. After discussion we decided to bring frontend retries back.
No risks.
No.
=> Revert 'Remove frontend handler retries (#3285)'

Makefile, service/history/api/update_workflow_util.go, service/history/historyEngine.go, service/history/workflowTaskHandlerCallbacks.go
* Move commonly used get & update function to api package
* Update history engine & workflow task handler accordingly
**Why?**
Better code structure
N/A
N/A
N/A
=> Move commonly used get & update function to api package

common/testing/mocksdk/client_mock.go, go.mod, go.sum, host/schedule_test.go
- Increase some timeouts in schedule integration test
- Bump sdk version to pick up fix for double-close
**Why?**
less flaky test
ran repeatedly locally
=> Tweak schedule test timeouts

common/persistence/persistenceRateLimitedClients.go
- Skip ratelimiting for persistence APIs that doesn't actually query DB.
**Why?**
- Those apis doesn't actually DB but consumes persistence ratelimiting token
- May cause more service busy errors upon service restart, when we are already seeing some persistence busy errors.
=> Skip ratelimiting for some persistence APIs

common/quotas/dynamic_rate_limiter_impl.go, service/matching/matcher.go
Add refresh method to dynamic rate limiter to force update rate
**Why?**
Fix the 1m delay for task queue rate limiter
=> Add refresh to force update dynamic rate limiter

common/dynamicconfig/constants.go, service/history/configs/config.go, service/history/fx.go, service/worker/archiver/client.go, service/worker/archiver/client_test.go
This moves a hard-coded timeout to a dynamic config and bumps up the default value from 300ms to 1 second (a fairly arbitrary choice).
**Why?**
To resolve https://github.com/temporalio/temporal/issues/2655
Manually by deploying this in a pre-prod environment. I also ran `docker-compose run unit-test make unit-test-coverage` and `docker-compose run integration-test-mysql make integration-test-coverage` locally.
Potential for previously failing calls to start succeeding with the higher default timeout and increase load related to archival.
No
=> Increase default sendArchiveSignal timeout and make it configurable

Makefile
Adding flag `--allow-no-auth` to `Makefile` commands to start server.
**Why?**
Future versions of temporal server will require this flag to be present to start it without authorizer.
Started server and no warning logs were shown.
No.
No.
=> Update Makefile to start server with `--allow-no-auth`

service/history/api/respondactivitytaskfailed/api.go, service/history/handler.go, service/history/historyEngine.go, service/history/historyEngine_test.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
* Move respond activity task failed to api package
**Why?**
N/A
N/A
N/A
=> Move respond activity task failed to api package

common/archiver/filestore/historyArchiver.go, common/archiver/filestore/historyArchiver_test.go, common/archiver/gcloud/historyArchiver.go, common/archiver/gcloud/historyArchiver_test.go, common/archiver/s3store/historyArchiver.go, common/archiver/s3store/historyArchiver_test.go
Return a "not found" error code instead of an "invalid argument" error when fetching history for archival-enabled namespaces that have no history.
I made these changes because they were requested here: https://github.com/temporalio/temporal/issues/2130
I also verified that all other references to the `archiver.ErrHistoryNotExist` return an invalid argument error, so this one was the odd one out.
I verified that all other usages of this same error message return the same error code. I modified the unit test which executes this logic to verify that the error code is "not found".
This modifies a user-facing API, so if someone depends on the existing error code, this could affect them.
This PR is not a hot fix candidate. However, it may be wise to notify the community about this change.
=> Return a "not found" error code for empty archival namespaces

common/util.go, service/history/api/create_workflow_util.go
Validate memo size against correct memo size limit
**Why?**
Use the right size limit for memo size validation
=> Enforce memo size limit during StartWorkflow

common/payload/payload.go, common/payload/payload_test.go, service/history/commandChecker.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go, service/history/workflowTaskHandler.go
Fixing the validation for memo size and search attribute size when upserting. The validation for them should be for the final map, not the upserting map.
**Why?**
It's bug that could make the memo/search attribute sizes grow beyond their limits.
Unit tests
Existing workflows that are taking advantage of this bug (ie, doing multiple upserts to store more data) will start to fail.
No.
=> Fix memo/search attribute size validation when upserting

service/history/queues/executable.go, service/history/queues/executable_test.go, service/history/timerQueueActiveProcessor.go, service/history/transferQueueActiveProcessor.go
- Skip task namespaceNotActive check in single queue mode
**Why?**
- When there's only one queue, we should not give up upon namespace not active error. A task should either be executed as active or verified as standby (though standby logic can decide to discard).
- Unit test
=> Skip task namespaceNotActive check in single queue mode

service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go, service/worker/batcher/workflow.go, service/worker/batcher/workflow_test.go
At the end of a batch operation, I've added a block of code that updates the workflow's memo with stats on the number of individual operations that succeeded or failed.
I made this change for https://github.com/temporalio/temporal/issues/3319
I added a unit test which verifies that we call UpsertMemo with the right map.
I think the worst case failure for this would be that all batch operations would start to fail if there's a bug with UpsertMemo.
=> Attaches success/error statistics to the batch operation workflow's memo

service/worker/scheduler/spec.go, service/worker/scheduler/spec_test.go, service/worker/scheduler/workflow.go
- Wrap time calculations in scheduler workflow in SideEffect
- Batch create uuids
**Why?**
We'd like the ability to change the behavior of `getNextTime` on existing inputs (e.g. to fix bugs) without breaking determinism of this workflow.
existing unit and integration tests
=> Calculate schedule times in sideeffect

.gitignore, Makefile, build/go.mod, build/go.sum, build/tools.go
Move build proto dependencies to separate `go.mod`.
**Why?**
To provide better control over build dependency versions.
Run locally and Buildkite.
No risks.
No.
=> Move build proto dependencies to separate go.mod

service/history/shard/controller_test.go
Use separate mock controller, and wait longer for engine stops
**Why?**
Make test less flaky
Ran hundreds of times locally
=> Make TestShardControllerFuzz less flaky

service/history/shard/context_impl.go
- Move notifyQueueProcessor to acquireShard
**Why?**
- Notify queue processor without hold the shard state lock
=> Move notifyQueueProcessor to acquireShard

service/history/queues/rescheduler.go
- Invoke timerGate.Update in a lock
**Why?**
- TimerGate.Update() is not a concurrent safe method, and caller must sync calls to this method.
- Checked all other invocation to Update as well.
=> Fix timerGate race condition in rescheduler

common/persistence/client/fault_injection.go
- Remove shardOwnershipLost error from fault injection execution store
**Why?**
- Existing implementation can't handle random shard ownership lost errors from some execution store api like rangeCompleteHistoryTasks. If returned, queue processor will shutdown itself without notifying the shard, as in this case shard context should get the same error as well from other operations. 
- Testing on test cluster
- N/A, fault injection is test code.
- No
=> Remove shardOwnershipLost error from fault injection execution store

common/dynamicconfig/constants.go, service/history/configs/config.go
These dynamic configs control whether we should ensure a execution or the visibility for that execution is closed before deleting the execution, or the visibility records, respectively.
=> Dynamic config

common/searchattribute/validator.go, common/searchattribute/validator_test.go, service/frontend/workflow_handler.go, service/history/historyEngine2_test.go, service/history/workflowTaskHandler.go
Changed search attribute validator to expect the map to contain field names instead of alias.
Changed error type in `ValidateSize` to `serviceerror.InvalidArgument` so it can go through gRPC correctly.
Fixed the validation for upsert search attribute as it was merging a map with field names with a map with alias names.
**Why?**
`ValidateSize` should be for field names instead of alias since field names are the values to be stored. In order to be consistent, `Validate` was also changed to expect the same input.
Small search attribute alias might increase in size as being mapped to field name, and fail the size validation.
No.
=> Change search attribute validator to expect field names instead of alias

common/payload/payload.go, common/payload/payload_test.go, host/elasticsearch_test.go
Fixing the function to merge map of payload. Keys with nil value or empty slice value are removed.
**Why?**
A bug was leaving keys with nil or empty slice value in the merged map when the first map is nil.
Added new unit tests to cover those cases.
No.
Yes.
=> Fix merge map of payload

common/util.go, service/history/consts/const.go, service/history/queues/executable.go, service/history/queues/executable_test.go, service/history/queues/metrics.go
Adds a retryable error for when we try to delete open executions. This was requested by @yycptt since we want a longer retry delay for this type of error.
=> Adds a retryable error for when we try to delete open executions

common/persistence/serialization/task_serializer.go, common/persistence/serialization/task_serializer_test.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/tasks/delete_visibility_task.go, service/history/workflow/delete_manager.go, service/history/workflow/delete_manager_test.go
Propagates the CloseVisibilityTaskId to the DeleteExecutionVisibilityTask, so that we can wait on the close visibility task to complete before we delete the execution visibility.
=> Propagate CloseVisibilityTaskId to DeleteExecutionVisibilityTask

service/history/visibilityQueueTaskExecutor.go, service/history/visibilityQueueTaskExecutor_test.go
Whenever we attempt to delete visibility records, with the new VisibilityProcessorEnsureCloseBeforeDelete option, we will now return an `ErrTaskRetry` error since the task should be retried since the task it's waiting on (the task to close the visibility records), might still finish soon.
=> Retry attempts to delete open visibility records

service/history/nDCActivityReplicator.go, service/history/replication/ack_manager.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go, service/history/workflow/timer_sequence.go
This PR fixes a [bug](https://github.com/temporalio/temporal/issues/3358) where the first event for a pending activity would set its LastHeartbeatTime to the event time. I tested the fix by writing a test which calls the `ReplicateActivityTaskStartedEvent` method which had this issue, and verifies that the `LastHeartbeatDetails` are nil (as long as they were previously nil). The biggest risk to this change is if someone was depending on `LastHeartbeatDetails` on their pending activities being non-nil.
=> Fixes an issue where last-heartbeat time was set to the first event's timestamp

service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go
Fix list batch operation to include division.
**Why?**
Need to use namespace division to show the batch operation.
Local test
=> Fix list batch operation to include division

common/rpc/interceptor/namespace_validator.go, common/rpc/interceptor/namespace_validator_test.go, common/rpc/interceptor/retry.go, service/frontend/fx.go, service/fx.go
Reorder interceptors 
**Why?**
1. Move interceptors that modify context between the retry interceptor and upstream.
2. Move namespaceValidatorInterceptor before ratelimiterInterceptor as it should not take rate limit quota.
local test
=> Reorder grpc interceptors

service/history/consts/const.go, service/history/tasks/delete_visibility_task.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueTaskExecutorBase.go
This is for https://github.com/temporalio/temporal/issues/3368. It adds a check to our transfer task processor which ensures that tasks are closed before deleting them.
=> Retry attempts to delete open workflow executions

service/worker/scheduler/calendar.go, service/worker/scheduler/calendar_test.go, service/worker/scheduler/spec.go, service/worker/scheduler/spec_test.go, service/worker/scheduler/workflow_test.go
- Add validation for structured calendar specs. This was already done for cron strings and calendar specs (and will now be done twice for them but that's okay).
- Improve error messages for invalid specs.
There are no behavior changes for valid calendar specs so there's no determinism risks. (Even if there was, we use sideeffect now.)
**Why?**
More and earlier validation, better error messages.
unit tests
yes
=> Validate structured calendar specs and improve error messages

common/namespace/registry.go, service/worker/pernamespaceworker.go, service/worker/pernamespaceworker_test.go
Check whether a namespace is active on this cluster before starting per-namespace worker.
**Why?**
No need to run workers for passive namespaces, save resources.
unit test and manual test
yes
=> Per-namespace workers should only run on active cluster

Makefile, go.mod, go.sum, tools/tdbg/app.go, tools/tdbg/app_test.go
* Set urfave/cli to v2.4.0
* test for verifying it processes flag values with comma (thx @dnr )
* Also sending a PR into urfave/cli to allow configuring the separator
**Why?**
The values for inputs, search attributes etc may contain comma
unit test
=> Ensure urfave/cli accepts flag values with comma

service/history/commandChecker.go
Log error of search attributes map size validation only when there's an error.
**Why?**
Size validation of search attributes map is always logging error even when there's no error.
Ran search attributes integration test before and after changes, and verified the logs are no longer showing up.
No.
Yes.
=> Log warning only when there is an error in SA size validation

common/persistence/persistence-tests/historyV2PersistenceTest.go, common/persistence/persistenceInterface.go, common/persistence/sql/history_store.go, common/persistence/sql/sqlplugin/history_tree.go, common/persistence/sql/sqlplugin/mysql/events.go, common/persistence/sql/sqlplugin/postgresql/events.go, common/persistence/sql/sqlplugin/sqlite/events.go
In this PR, I've added an implementation of the GetAllHistoryTreeBranches function for all of our SQL backends. 
I made these changes for https://github.com/temporalio/temporal/issues/3419. This change will allow the history scavenger to prune branches in clusters that use SQL backends for history storage. 
There are existing test suites which verify that we can fetch all history branches after creating some. However, those tests were disabled for non-Cassandra databases. I removed that constraint, and watched the tests fail (because the GetAllHistoryTreeBranches method just panicked before this change). I then applied my fix, and watched the tests pass. 
Worst case scenario, we somehow return the wrong data in GetAllHistoryTreeBranches, and that causes the scavenger to delete branches …
=> Implement GetAllHistoryTreeBranches for SQL persistence backends

service/history/nDCTransactionMgr.go, service/history/nDCTransactionMgr_test.go
Fix reset workflow in replication reapply
**Why?**
During a replication reapplication, we need to reset a closed workflow to re-apply the events. When there is failure of reset workflow, we should update the workflow with current. 
Added new unit test
=> Fix reset workflow in replication reapply

service/history/queues/executable.go, service/history/queues/metrics.go
- Use separate metric for resource exhausted error in task processing
**Why?**
- So that alert on task_errors won't be affected by resource exhausted errors.
=> Use separate metric for resource exhausted error in task processing

common/metrics/tally_metrics_handler.go, common/metrics/tally_metrics_handler_test.go
Fix exclude tags with withTags method
**Why?**
WithTags should not drop the excludeTag field
=> Fix exclude tags with withTags method

service/history/replication/ack_manager.go
* Properly handle min task ID > max task ID case by return unavailable error
**Why?**
During shard rebalancing, it is possible that a replication task poller contact new shard owner, then old shard owner: min task ID > max task ID; old shard owner should return unavailable error -> caller retry.
N/A
N/A
N/A
=> Properly handle min task ID > max task ID case when shard is re-balancing

service/history/historyEngine2_test.go, service/history/nDCHistoryReplicator_test.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_rebuilder.go, service/history/workflow/mutable_state_rebuilder_test.go, service/history/workflow/task_generator.go, service/history/workflow/task_generator_mock.go, service/history/workflow/task_refresher.go
- Fix `DeleteHistoryEventTask` and `WorkflowBackoffTimerTask`'s visibility timestamp when they are generated by workflow refresh
**Why?**
- Workflow refresh will use the refresh time instead of workflow close/start time to generated those two tasks.
- Tried workflow refresh locally and verified time for generated DeleteHistoryEventTask and WorkflowBackoffTimerTask
- Maybe
=> Fix timer task visibility timestamp for workflow refresh

service/history/api/replication/generate_task.go, service/history/api/replication/get_dlq_tasks.go, service/history/api/replication/get_tasks.go, service/history/api/replication/status.go, service/history/api/replicationadmin/get_dlq.go, service/history/api/replicationadmin/merge_dlq.go, service/history/api/replicationadmin/purge_dlq.go, service/history/handler.go, service/history/historyEngine.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
* Move replication APIs to api package
* Move admin replication APIs to dedicated package
* Move replication APIs to dedicated package
**Why?**
N/A
N/A
N/A
=> Move replication APIs to api package

service/history/api/reapplyevents/api.go, service/history/api/replication_util.go, service/history/handler.go, service/history/historyEngine.go
* Move reapply events to api package
**Why?**
N/A
N/A
N/A
=> Move reapply events to api package

service/history/api/removesignalmutablestate/api.go, service/history/api/respondactivitytaskcanceled/api.go, service/history/handler.go, service/history/historyEngine.go, service/history/historyEngine_test.go, service/history/shard/engine.go, service/history/shard/engine_mock.go
* Move remove signal from mutable state to api package
**Why?**
N/A
N/A
N/A
=> Move remove signal from mutable state to api package

service/history/queues/queue_base.go, service/history/replication/ack_manager.go, service/history/replication/ack_manager_test.go, service/history/replication/task_processor_manager.go, service/history/replication/task_processor_manager_test.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/shard/context_test.go, service/history/timerQueueAckMgr.go, service/history/timerQueueAckMgr_test.go, service/history/timerQueueActiveProcessor.go, service/history/timerQueueStandbyProcessor.go, service/history/transferQueueActiveProcessor.go, service/history/transferQueueStandbyProcessor.go, service/history/visibilityQueueProcessor.go
- Fix scheduled queue max read level update for single processor
**Why?**
- In single processor mode, there's only one queue using & updating the value in scheduledQueueMaxReadLevel[currentCluster]. However, then generating scheduled tasks, tasks visibility timestamp is compared to it's active cluster's max read level, which is never updated and is an old value. This is mean the generated task can potentially have an old timestamp and won't be loaded and processed by the scheduled queue processor.
- Unit test & Existing integration test.
- Should have no impact when multicursor and single processor is disabled.
- Yes.
=> Fix scheduled queue max read level update for single processor

service/worker/scanner/scanner.go, service/worker/scanner/scanner_test.go, service/worker/service.go
In this PR, I enabled the history scanner to delete unused history tree branches. In addition, I removed an else which made it impossible for the history scanner and task queue scanner to be on simultaneously (task queue scanner would take priority).
**Why?**
I made these changes for https://github.com/temporalio/temporal/issues/3419 in order to rule this out as an option for why disk usage is increasing so much over time for SQL backends.
I added a new test to the Scanner which verifies that we actually start the scavenger now regardless of the storage backend we're using.
The biggest risk I can think of is that this change could turn on the scavenger for NoSQL backends, and it could have a bug which causes it to remove …
=> Turns on the history scavenger for SQL backends

common/constants.go, host/xdc/integration_failover_test.go, service/history/ndc/history_replicator.go, service/history/shard/context_impl.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go
Fix sanitize mutable state after replication
**Why?**
1. The LastFirstTxnID should use the one from append history node. Otherwise, it will break getReverseHistory.
2. Sanitize closeTaskID and closeVisibilityTaskID in CreateAsClose case.
local test
=> Fix sanitize mutable state after replication

common/constants.go, service/history/ndc/history_replicator.go
Clean up duplicate empty task id
**Why?**
Clean up duplicate empty task id
=> Clean up duplicate empty task id

service/history/replication/task_processor.go
Update replication timestamp with no task
**Why?**
Currently, the replication acked timestamp will not be updated if there is no replication task. We should use the source cluster time if there is no replication task to indicate the replication is up-to-date.
Local test
=> Update replication timestamp with no task

common/metrics/defs.go, common/persistence/sql/sqlplugin/mysql/visibility.go, common/persistence/sql/sqlplugin/postgresql/visibility.go, common/persistence/sql/sqlplugin/sqlite/visibility.go, common/persistence/sql/sqlplugin/visibility.go, common/persistence/visibility/manager/visibility_manager.go, common/persistence/visibility/manager/visibility_manager_mock.go, common/persistence/visibility/store/elasticsearch/client/client.go, common/persistence/visibility/store/elasticsearch/client/client_mock.go, common/persistence/visibility/store/elasticsearch/client/client_v7.go, common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go, common/persistence/visibility/store/standard/cassandra/visibility_store.go, common/persistence/visibility/store/standard/sql/visibility_store.go, common/persistence/visibility/store/standard/visibility_store.go, common/persistence/visibility/store/visibility_store.go, common/persistence/visibility/store/visibility_store_mock.go, common/persistence/visibility/visibility_manager_dual.go, common/persistence/visibility/visibility_manager_impl.go, common/persistence/visibility/visibility_manager_rate_limited.go, common/persistence/visibility/visibility_manager_test.go, common/persistence/visibility/visiblity_manager_metrics.go, service/frontend/configs/quotas_test.go
Creating visibility API to get a single workflow execution by run id.
**Why?**
This will be used to get search attributes and memo from visibility for closed workflows.
Unit tests.
In SQL template query to get closed workflow by run id, I removed the filter to exclude running workflows. It means that, with this change, the query will return a record if the workflow is found by run id, but its status is running. I'm not sure where this specific query is used though.
No.
=> Create visibility GetWorkflowExecution API

common/persistence/sql/sqlplugin/mysql/events.go
Rewrite this query to use simple boolean expressions instead of tuple comparison.
**Why?**
For some reason mysql ends up using a full scan for this query even though the explain query plan looks reasonable.
Tested with pre-release build on pipelines.
yes
=> Rewrite mysql PaginateBranchesFromHistoryTree query

common/metrics/defs.go, service/history/workflow/context.go
Warning log on new event during set workflow
**Why?**
Warning log on new event during set workflow
=> Warning log on new event during set workflow

service/worker/scanner/scanner.go, service/worker/scanner/scanner_test.go, service/worker/service.go
Fix scanner start dep
**Why?**
It should get system client in start()
I tested with local start but it would be good to have functional test for the whole cluster.
=> Fix scanner start dep

common/persistence/cassandra/mutable_state_task_store.go, common/persistence/sql/execution_tasks.go, common/persistence/sql/execution_util.go, common/persistence/sql/sqlplugin/history_immediate_tasks.go, common/persistence/sql/sqlplugin/history_replication_tasks.go, common/persistence/sql/sqlplugin/history_scheduled_tasks.go, common/persistence/sql/sqlplugin/history_timer_tasks.go, common/persistence/sql/sqlplugin/history_transfer_tasks.go, common/persistence/sql/sqlplugin/history_visibility_tasks.go, common/persistence/sql/sqlplugin/interfaces.go, common/persistence/sql/sqlplugin/mysql/execution.go, common/persistence/sql/sqlplugin/postgresql/execution.go, common/persistence/sql/sqlplugin/sqlite/execution.go, common/persistence/tests/execution_mutable_state_task.go, schema/mysql/v57/temporal/schema.sql, schema/mysql/v57/temporal/versioned/v1.9/history_tasks_table.sql, schema/mysql/v57/temporal/versioned/v1.9/manifest.json, schema/mysql/version.go, schema/postgresql/v96/temporal/schema.sql, schema/postgresql/v96/temporal/versioned/v1.9/history_tasks_table.sql, schema/postgresql/v96/temporal/versioned/v1.9/manifest.json, schema/postgresql/version.go, schema/sqlite/v3/temporal/schema.sql, service/history/tasks/fake_task.go, service/history/tasks/utils.go
- Support arbitrary history task category in SQL persistence
**Why?**
- Currently only cassandra impl support arbitrary task category, need sql support as well since new task queue need to be supported by both cassandra and sql
- added unit test
- N/A. Currently no task category will use those code paths.
- no
=> Support arbitrary history task category in SQL persistence

common/metrics/otel_metrics_handler.go
Initialize the logger to prevent NPE's, since the logger is used.
=> initialize otelMetricsHandler logger

service/history/replication/ack_manager.go
Fix replication task nil case
**Why?**
1. Handle if the replication task is nil, we don't need to handle new run case.
2. We should generate replication task even if the workflow is closed.
=> Fix replication task nil case

common/payload/payload.go, common/util/util.go, service/worker/addsearchattributes/workflow.go, service/worker/scheduler/workflow.go
Port parts of #3408, `util.CloneMapNonNil`, to 1.18 release branch.
**Why?**
This isn't necessary if building the server from the repo unmodified, but if using the server as a library, a newer version of `golang.org/x/exp` might be pulled in, which requires these changes.
tested in master branch
yes
=> Port util.CloneMapNonNil to release branch

common/metrics/client.go, common/metrics/scope_test.go, common/metrics/tags.go, common/resource/resourceTest.go, service/history/workflow/mutable_state_impl_test.go, service/matching/matchingEngine_test.go, temporal/fx.go
- Add service name tag to metrics emitted using metrics handler
**Why?**
- Currently only metrics emitted using metrics client has service name tag, but we are deprecating metrics client and in favor of metrics handler.
- Tested locally and see metrics emitted by both metrics handler and metrics client have service name tag. 
- probably
=> Add service name tag to metrics emitted using metrics handler

Makefile, client/admin/client.go, client/frontend/client.go, client/history/client.go, client/matching/client.go, cmd/server/main.go, common/constants.go, common/debug/debug.go, common/debug/not_debug.go, host/context.go
Increase timeouts in debug mode.
**Why?**
Default RPC timeouts work great for production environments. While in server debugging mode it is almost impossible to step over the code with default values.
Setting `TEMPORAL_DEBUG` build constraint will increase most important timeouts (did I forget anything?) 100 times.
Debug integration tests locally. 
No risks.
No.
=> Increase timeouts in debug mode

service/history/configs/config.go, service/history/workflow/task_generator.go, service/history/workflow/task_generator_provider.go, service/history/workflow/task_generator_test.go
We now produce an archival task instead of a deletion timer task when an execution is closed.
**Why?**
I made these changes so that we can start consuming archival tasks to the archival queue.
I tested these changes by verifying the tasks generated by this method depending on all 4 combinations of `deleteAfterClose` and `durableArchivalEnabled`. 
If someone starts using this code right now, it won't work because there are still some other changes that need to happen. However, that should be mitigated by the fact that this is currently not available in our dynamic config.
No.
=> Generate ArchiveExecutionTask instead of DeleteHistoryEventTask whenever an execution is closed

common/dynamicconfig/constants.go, common/metrics/metric_defs.go, service/history/commandChecker.go, service/history/commandChecker_test.go, service/history/configs/config.go, service/history/workflowTaskHandlerCallbacks.go
I added a `checkIfNumChildWorkflowsExceedsLimit` method to our `workflowSizeChecker`.
**Why?**
In order to limit the number of child workflows is too large.
I added a large suite of unit tests.
This method isn't called anywhere in prod yet, so none.
No.
=> Add a tool to limit the number of pending child workflows

service/history/shard/context_impl.go
Keep acquireShard retrying except ShardOwnershipLostError or lifecycleCtx ended.
**Why?**
Resilient shard should not give up on other any other errors except ShardOwnershipLost error, for example should keep retry on timeout errors.
Manual test locally with fault injection enabled (slightly modification so it does not return shard ownership error).
No.
Yes.
=> Fix resilient shard

common/persistence/cassandra/schema_version_reader.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/iter.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/query.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go, tools/cassandra/cqlclient.go
Wrap `gocql.Iter` with custom wrapper.
**Why?**
To use custom `handelError` function to handle `ErrNoConnections` error and recreate session.
To temporally mitigate the error form https://github.com/gocql/gocql/issues/915.
No risks.
Yes.
=> Wrap gocql.Iter with custom wrapper

host/client_integration_test.go, service/history/historyEngine2_test.go, service/history/workflowTaskHandler.go
We now return an error whenever the number of pending child executions is too high.
**Why?**
I made this change to prevent our mutable state from becoming too large when there are too many child workflows.
I added an integration test that sets the limit to 1 and then tries to create a child workflow while there is another one pending. I also added a unit test that verifies the exact error message.
If this logic is faulty or the limit is too low, it could prevent new child workflows from being spawned.
Yes.
=> Return an error whenever we exceed the number of pending child executions

common/dynamicconfig/constants.go, common/metrics/metric_defs.go, service/history/commandChecker.go, service/history/commandChecker_test.go, service/history/configs/config.go, service/history/workflowTaskHandlerCallbacks.go
I removed the warning that we log when the number of child workflows is high.
**Why?**
I did this because we decided that it would be too noisy.
I tested this just by removing the test cases for warnings. Since there's no expected warning logs, the tests would fail if this change didn't work.
This dynamic config hasn't even been released yet, so there's no risk.
No.
=> Don't log a warning when the number of child workflows is high

common/headers/versionChecker.go, service/frontend/overrides.go, service/frontend/overrides_test.go, service/frontend/workflow_handler.go
Disable eager activity dispatch for buggy clients.
Known buggy implementations are Core based SDKs - TypeScript and Python.
The bug in Core was fixed in TS `1.4.4` and Python `0.1b3`.
**Why?**
The Core bug is pretty severe, it causes a panic on the Rust side stopping worker progress altogether.
The bug effects workflow-only workers which is relatively rare but still worth server side compensation.
=> Disable eager activity dispatch for buggy clients

common/dynamicconfig/constants.go, host/client_integration_test.go, service/history/commandChecker.go, service/history/commandChecker_test.go, service/history/configs/config.go, service/history/historyEngine2_test.go, service/history/workflowTaskHandlerCallbacks.go
I added item count limits on three other fields in our mutable state (pending activities, pending cancel requests, pending signals).
**Why?**
I made this change to ensure that our workflows don't become too large.
I just added the limits to our dynamic config, but they aren't enforced yet.
None.
No.
=> Add limits on other workflow fields

host/util.go
We now retry creating our elasticsearch index in our integration test setup.
**Why?**
This can fail because the delete operation that precedes it is not synchronous.
Will wait for CI to build.
Can't think of any.
No.
=> Retry CreateIndex in integration tests request upon failure

common/metrics/metric_defs.go, service/history/commandChecker.go, service/history/commandChecker_test.go, service/history/historyEngine2_test.go
I generalized our workflow size limit constraints to 4 fields (child workflows, activities, external signals, and cancel requests).
**Why?**
I made this change so that we can limit these fields which could potentially cause issues if they're too large.
I added unit tests.
These new methods aren't called yet.
No.
=> Add methods to check workflow size violations for several other fields

common/rpc/interceptor/namespace_count_limit.go
Making `frontend.namespaceCount` to be the max concurrent poller for each type (ie. activity and workflow pollers).
**Why?**
Currently, the config is for the total amount of pollers, which can make one type of poller to take all token while waiting in the long poll. This is prevent the other poller type to get tasks if there are pending tasks. This issue happens when there are more worker pollers than the maximum allowed by the server.
Started a worker with more pollers than the server allows it, and created a job to create many workflows. Currently, after a couple of minutes, almost all tokens are taken by activity pollers making workflow pollers to fail to get tasks. With this PR change, workflow pollers can get new tasks since now they don't …
=> Change max namespace count limit to per poller type

common/persistence/serialization/task_serializer.go, service/history/replication/task_executor.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/shard/context_test.go, service/history/tasks/close_task.go, service/history/tasks/delete_workflow_execution_stage.go, service/history/tasks/workflow_cleanup_timer.go, service/history/timerQueueTaskExecutorBase.go, service/history/timerQueueTaskExecutorBase_test.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueTaskExecutorBase.go, service/history/workflow/delete_manager.go, service/history/workflow/delete_manager_mock.go, service/history/workflow/delete_manager_test.go
Remember retention timer task state in memory for retry.
**Why?**
Delete workflow execution is 4 stages process, and if it is throttled by persistence rate limit, it would fail and the entire task will be retried.
In the retry, same steps will be redone even if some of them already succeed.
In this PR delte process stage is stored inside task while it stays in-memory and gets retried. This allow to avoid load amplification during failure case.
Save the stage in-memory only because persisting it will be too costly for the benefit.
New unit tests, existing integration tests.
No risks.
No.
=> Remember retention timer task state in memory for retry

common/dynamicconfig/constants.go, service/history/configs/config.go, service/history/visibilityQueueFactory.go, service/history/visibilityQueueProcessor.go, service/history/visibilityQueueTaskExecutor.go, service/history/visibilityQueueTaskExecutor_test.go
Adding a flag to enable/disable clean up when workflow is closed. The clean up is removing memo and search attributes from mutable state. This flag should only be enabled when using Elasticsearch as visibility store. Otherwise, you'll lose search attributes as it will be removed from mutable state, and it's not stored in visibility.
**Why?**
This feature was introduced without a flag, and it can possibly break existing workflows that depend on data in those maps, but they are not using advanced visibility.
Unit tests.
None.
No.
=> Add flag to enable workflow closed clean up

host/client_integration_test.go, service/history/workflowTaskHandler.go
We now fail any command that would exceed the sending workflow's capacity for pending signals.
**Why?**
To keep workflow state small.
I added an integration test similar to the other three.
Users that send a lot of signals in one command may see their workflows fail.
Notification required.
=> Enforce the per-workflow pending signal limit

service/history/queues/queue_base.go
- Keep multi cursor default reader always running
**Why?**
- otherwise when traffic is low, default reader will keep start/stop and generate lots of log message for starting/stopping which pollutes the log. 
=> Keep multi cursor default reader always running

common/dynamicconfig/constants.go
I changed the value of `VisibilityProcessorEnsureCloseBeforeDelete` from `history.transferProcessorEnsureCloseBeforeDelete` to `history.visibilityProcessorEnsureCloseBeforeDelete`.
**Why?**
I made this change because the original key used was a typo.
Code search.
Anyone that disabled `history.transferProcessorEnsureCloseBeforeDelete` in order to disable the `VisibilityProcessorEnsureCloseBeforeDelete` behavior, will now see it reset to true.
No.
=> Fix typo in dynamic config for VisibilityProcessorEnsureCloseBeforeDelete

common/log/config.go, common/log/zap_logger.go
I changed the Zap encoding of our logs to "console" instead of "json" during tests.
**Why?**
I made this change because it will give us more human-readable output when running tests, without affecting production. For example, stack traces will appear across multiple lines instead of a newline-escaped string on one line of JSON.
Logs with this change:
```
=== RUN   TestTransferQueueStandbyTaskExecutorSuite/TestProcessActivityTask_Pending
2022-11-21T10:44:48.580-0800	error	example error	{"logging-call-at": "transferQueueStandbyTaskExecutor.go:78"}
go.temporal.io/server/common/log.(*zapLogger).Error
/Users/michael.snowden/src/temporalio/temporal/common/log/zap_logger.go:144
go.temporal.io/server/service/history.newTransferQueueStandbyTaskExecutor …
```
=> Improve test log format

common/backoff/jitter.go, common/backoff/jitter_test.go, common/tasks/interleaved_weighted_round_robin.go, service/history/queueFactoryBase.go, service/history/queues/scheduler.go, service/history/timerQueueFactory.go, service/history/timerQueueProcessorBase.go, service/history/transferQueueFactory.go, service/history/transferQueueProcessorBase.go, service/history/visibilityQueueFactory.go, service/history/visibilityQueueProcessor.go
- Add randomization logic for throttle duration
- Allow using different max throttle duration for different scheduler (host v.s. shard)
**Why?**
- Because multiple schedulers share the same rate limiter, if they always tries to consume the token in the same order, it's possible that later scheduler never get any tokens and lead to starvation. 
=> Randomization and configuration for scheduler throttle duration

common/cluster/metadata.go, common/cluster/metadata_test.go, service/history/ndc/replication_task.go, service/history/workflow/mutable_state_impl.go
Handle unknown cluster in replication
**Why?**
We should handle this unknown cluster in replication so we can replication open workflow.
Local tests:
1. Describe/Admin Describe workflow after fully migration.
2. Reset workflow after fully migration.
3. Terminate workflow after fully migration.
4. Signal workflow after fully migration.
5. Get workflow history after fully migration.
6. Cancel workflow after fully migration.
In the worst case, the workflow after migration could be in a broken state.
No
=> Handle unknown cluster in replication

common/persistence/cassandra/test.go, common/persistence/sql/sqlPersistenceTest.go, tests/testhelper/source_root.go, tests/testhelper/source_root_test.go
Our GetRepoRootDirectory function now uses runtime.Caller instead of parsing the working directory.
**Why?**
The working directory may be totally different from the source directory, it also sometimes returns an error, and, most importantly, it doesn't work if there is "temporal" somewhere in the directory structure e.g. in `src/temporalio/temporal/temporal/some_test.go`.
I used the existing unit tests.
This is only used in tests, so CI should fail.
No.
=> Fix bug in GetRepoRootDirectory code

common/dynamicconfig/constants.go, host/client_integration_test.go, host/continue_as_new_test.go, service/history/configs/config.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/retry.go
Enforce a minimal interval between continue as new runs.
**Why?**
When users doing continue as new in a tight loop, it could cause trouble for server.
In all the cases that we encountered, it is always bug in user code that caused unintentional continue as new spin. 
New unit test. 
Also did manual test to verify tight loop result in 1 execution per second with default interval.
No
=> Enforce min interval for continue as new runs

host/schedule_test.go, service/worker/scheduler/workflow.go
Set catchup window default on create/update
**Why?**
This way, the default will be reported in describe output, so it's less confusing for users
unit test
=> Set default catchup window eagerly

common/authorization/interceptor.go, common/namespace/registry.go, service/frontend/adminHandler.go, service/frontend/operator_handler.go, service/frontend/versionChecker.go, service/history/api/queryworkflow/api.go, service/history/events/cache.go, service/history/events/notifier.go, service/history/replication/task_executor.go, service/history/shard/context_impl.go, service/history/shard/controller_impl.go, service/history/timerQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/workflow/cache.go, service/worker/replicator/namespace_replication_message_processor.go
Fix pattern on defer when emitting latency metrics.
**Why?**
Cannot call timer in defer directly.
Yes
=> Fix replication task execution latency

service/history/timerQueueProcessor.go, service/history/transferQueueProcessor.go
* During cluster disconnection, sync shard status invocation can be delayed and unable to find target passive processor. Instead of panic-ing, logic should log warn and move on.
**Why?**
See above
N/A
N/A
N/A
=> Do not panic if passive processor is missing

cmd/server/main.go, temporal/fx.go, temporal/server_test.go
We now return an error when FX fails to build the server.
**Why?**
I made this change so that we can verify that a new server can be instantiated for all services without failing, but that failures will be detected.
I tested this by adding unit tests for the happy path and an error path (invalid config path). I also ran it locally with race detection on.
This is a new error message, and some invalid configs may trigger this error path when they didn't before.
No.
=> Return an error when we fail to instantiate the server

service/frontend/workflow_handler.go
The query/signal loop in DescribeSchedule should abort after a few retries and return the latest result.
**Why?**
If a schedule is creating a lot of short-lived workflows (e.g. 1 per second) and workers are loaded, this can fail to converge.
integration test, manual test with additional sleep in query handle to force it to abort
This is returning out-of-date data about running workflows, but even if we think it's up-to-date, it might be out-of-date by the time the client sees it, so it can't really be a problem.
=> Set limit on DescribeSchedule query/signal loop

service/worker/scheduler/workflow.go, service/worker/scheduler/workflow_test.go
The scheduler workflow now doesn't set a timer (i.e. sleeps until a signal) if currently paused or out of remaining actions. In that case it wouldn't take any actions even if it did wake up, so there's no reason to wake up.
**Why?**
Reduces load, saves history events.
rearranged unit test
This is a change in workflow logic, but it's guarded by a new field in tweakables, which functions similarly to using the versioning api.
=> Don't wake up scheduler workflow when paused

common/metrics/metric_defs.go, service/worker/scanner/executions/mutable_state_validator.go, service/worker/scanner/executions/task.go
1. Skip history validation if the mutable state validation failed. 
2. Improve the execution scavenger task to continue iterate all records if error encounters.
**Why?**
1. fail fast if mutable state is corrupted. It indicates bugs or DB issues.
2. Improve the efficiency to scan all records.
No
=> Improve execution scavenger

common/rpc/interceptor/telemetry.go
Fix service_latency_nouserlatency
**Why?**
service_latency_nouserlatency should subtract user latency.
=> Fix service_latency_nouserlatency

common/persistence/visibility/visibility_manager_test.go, common/persistence/visibility/visiblity_manager_metrics.go
Remove empty visibility tag
**Why?**
The visibility tag is defined in visibilityTypeMetricsTag
=> Remove empty visibility tag

common/rpc/interceptor/caller_info_test.go, common/rpc/interceptor/namespace.go, common/rpc/interceptor/namespace_test.go
Use empty namespace metrics tag if namespace not found
**Why?**
To prevent misuse of invalid namespace metrics tag.
Add unit test
=> Use empty namespace metrics tag if namespace not found

service/history/shard/context_impl.go, service/history/shard/context_test.go
Adds a test that verifies a ShardOwnershipLostError is not retried, but a regular error is.
**Why?**
These are the only types of errors that acquireShard should not retry.
This is a test.
Just a test.
No.
=> Test that ShardOwnershipLostErrors are never retried

common/metrics/metric_defs.go, common/persistence/persistenceMetricClients.go
I added some metrics scopes for the archival queue.
**Why?**
I added these changes because our queue processor will crash if it can't find the metrics scope for the archival category.
I ran the archival queue in our integration testing environment and watched the errors go away.
This isn't wired into any production entry points. However, it will increase `NumCommonScopes`. It doesn't look like anyone is using this variable outside of tests, though.
No.
=> Add metrics scopes for the archival queue

common/config/config.go, common/persistence/client/fault_injection.go, common/persistence/client/targeted_fault_injection.go, common/persistence/sql/sqlPersistenceTest.go, host/acquire_shard_integration_test.go, host/integrationbase.go, host/test_cluster.go, host/testdata/acquire_shard_deadline_exceeded_error.yaml, host/testdata/acquire_shard_eventual_success.yaml, host/testdata/acquire_shard_ownership_lost_error.yaml, service/history/shard/context_impl.go
I added an integration test for the acquireShard method. To do this, I created a new targeted fault injection config.
**Why?**
I made this to give us more confidence in the acquireShard method.
With an integration test.
It looks like the FaultInjection config is only propagated to the persistence config in test_cluster, not anywhere else, so I don't think there's any risk to production.
No.
=> Add an integration test for acquireShard

common/backoff/jitter.go, common/dynamicconfig/constants.go, service/history/configs/config.go, service/history/tasks/category.go, service/history/workflow/task_generator.go, service/history/workflow/task_generator_test.go
1. I made the archival queue a scheduled queue instead of a timer queue.
2. I added a random delay to each task we produce
**Why?**
I did this to prevent us from having a ton of archive execution tasks arrive concurrently if many workflows close simultaneously.
I added unit tests that verify edge cases like setting the dynamic config upper bound to 0.
Does not run via any production entrypoints. 
No.
=> Add random delay to ArchiveExecutionTask

service/history/api/describeworkflow/api.go, service/history/workflow/relocatable_attributes_fetcher.go, service/history/workflow/relocatable_attributes_fetcher_test.go
I added a utility for fetching the memo and search attributes from a workflow, depending on whether the close visibility task is complete or not.
**Why?**
I made this change because we need this method in the new archival queue.
I tested this change by adding unit tests.
This could introduce a bug into the DescribeWorkflowExecution API since the extracted method is slightly different so that it only depends on a visibility manager and mutable state.
No.
=> Add a utility for reliably fetching search attributes and memo

service/worker/deletenamespace/deleteexecutions/workflow_test.go
We now skip Test_DeleteExecutionsWorkflow_ManyExecutions_NoContinueAsNew.
**Why?**
I did this because it is flaky.
```sh
master [$] ➜ go test ./service/worker/deletenamespace/deleteexecutions -race -count 100  -json | jq -s 'map(select(.Action == "fail" and .Test))'
[
{
"Time": "2022-12-07T23:19:58.608184-08:00",
"Action": "fail",
"Package": "go.temporal.io/server/service/worker/deletenamespace/deleteexecutions",
"Test": "Test_DeleteExecutionsWorkflow_ManyExecutions_NoContinueAsNew",
"Elapsed": 0.04
}
]
master [$] took 10.8s ➜ git checkout flaky-delete-test 
Switched to branch 'flaky-delete-test'
Your branch is up to date with 'origin/flaky-delete-test'.
flaky-delete-test [$] ➜ go test ./service/worker/deletenamespace/deleteexecutions -race …
```
=> Disable the Test_DeleteExecutionsWorkflow_ManyExecutions_NoContinueAsNew test because it is flaky

host/testdata/integration_elasticsearch_cluster.yaml, host/testdata/integration_namespace_cluster.yaml, host/testdata/schedule_integration_test_cluster_adv_vis.yaml, host/testdata/xdc_integration_es_clusters.yaml
We now use unique index names for ElasticSearch test configs.
**Why?**
Because this method is flaky, and my last effort to just retry the creation doesn't work. This lead to failed builds like [this one](https://buildkite.com/temporal/temporal-public/builds/6882).
CI
This method is in the host/ directory which is only used by tests.
No.
=> Fix flaky CreateIndex method

tools/sql/README.md
docs: add specific make step to README on the tools/sql path for creating easily temporal-sql-tool binary
I've added a specific make step to README on the tools/sql path 
so that users don't have to struggle to find the make step
improve README only
there is no potential risk because only editing README
no
=> docs: add specific make step to README on the tools/sql path

go.mod, go.sum
Update Go SDK to v1.19.0. Fixes a SDK bug that would cause non determinism in the schedule workflow when doing a stale replay.
=> Update Go SDK to v1.19.0

service/history/shard/controller_test.go
=> Fix flaky shard controller tests

.github/workflows/sdk-features-integration.yml
DRAFT while building
Add sdk-features coverage to PRs
=> Add sdk-features trigger to PRs

common/dynamicconfig/constants.go, common/persistence/history_manager.go, service/history/configs/config.go, service/history/replication/ack_manager.go
1. Use data loss error for corrupted data case.
2. Ability to bypass corrupted data in replication.
**Why?**
We should aware of the corrupted data but also need to ability to bypass this error so it will not block the replication.
This is a clean version of https://github.com/temporalio/temporal/pull/3691
local test.
No.
=> Handle data loss error in replication read history

host/archival_test.go
I created a separate test suite for the archival test.
**Why?**
I did this because I plan on re-using this test with the durable archival flag on, so making it its own suite will allow me to run it for each of the two settings.
Ran locally.
Just a test. I verified that this test still runs as part of `go test ./host`
No.
=> Separate archival integration tests into their own suite

common/dynamicconfig/constants.go, common/metrics/metric_defs.go, service/history/archival/archiver.go, service/history/archival/archiver_test.go, service/history/archival_queue_task_executor.go, service/history/archival_queue_task_executor_test.go, service/history/workflow/task_generator.go, service/history/workflow/task_generator_mock.go, service/history/workflow/task_generator_test.go
Added a processor which executes tasks on the archival queue. A followup PR will actually enable the queue factory.
**Why?**
I made these changes to enable the archival queue.
I tested this using unit tests because it's not actually hooked into prod yet.
No--it's not wired into main yet.
No.
=> Add an archival task executor

common/dynamicconfig/constants.go, service/history/archival_queue_factory.go, service/history/archival_queue_factory_test.go, service/history/configs/config.go, service/history/queues/priority_assigner_test.go
Adds an archival queue factory to create the archival queue.
**Why?**
I made this change to instantiate the archival queue.
I added a unit test.
Not used in production.
No.
=> Add an archival queue factory

host/archival_test.go
The archival integration test logic changed. Previously, it only checked for history and required the mutable state to be deleted. Now, it doesn't verify if the mutable state is deleted because that's done later, and it checks for both history and visibility archival records.
**Why?**
I made these changes because this is a more robust test, and it also will make it easier to adapt this test to durable archival, which does not delete records at the same time it archives them.
I ran it with `-count 5`. I also commented out the archival methods and verified that the tests failed with those methods commented out.
Just test.
No
=> Improve archival_test

service/history/tasks/archive_execution_task_test.go
The key from this task now has a fire time. I also added a small unit test for this.
**Why?**
This was a relic from when the archival queue was immediate, not scheduled. I made this change because this is incorrect.
I added a unit test.
Not used in prod yet.
No
=> Fix ArchiveExecutionTask key type

service/history/workflow/task_generator.go, service/history/workflow/task_generator_test.go
We now set the CanSkipVisibilityArchival flag when creating archival queue tasks.
**Why?**
This was a bug. We need to set this flag when using durable archival so that we don't archive visibility twice.
I added a statement in the unit test and verified that the test failed before this change.
Not used in prod yet.
No
=> Fix bug not setting CanSkipVisibilityArchival

common/persistence/visibility/store/elasticsearch/processor.go, common/persistence/visibility/store/elasticsearch/processor_test.go, common/persistence/visibility/store/elasticsearch/visibility_store.go, service/history/configs/config.go, service/history/visibilityQueueTaskExecutor.go, service/worker/deletenamespace/reclaimresources/activities.go
1. Fix ES bulk processor commit timeout. Effective value was 3s but it supposed to be 60s.
2. Decrease ES bulk processor commit timeout from 60s to 30s.
3. Visibility task execution timeout is still 3s and it is not respected by bulk processor which now has 30s commit timeout and may also spend some time waiting for bulk processor to accept the request.
4. ~~Increased default number of bulk processor workers from 1 to 2. Rationale: it should help with commit latency during traffic spikes and with "wait add" latency.~~ This goes to #3738 instead.
5. Change the way how `elasticsearch_bulk_processor_queued_requests` metric is emitted. It now shows number of pending requests after current bulk is processed.
**Why?**
Fixing bugs, improving overall ES write latency.
**How did …
=> Fix ES bulk processor commit timeout

service/history/archival_queue_task_executor.go, service/history/archival_queue_task_executor_test.go
This PR fixes a bug (on line 253) where we returned nil when there was an error generating the deletion timer task.
**Why?**
This is a bug.
I added a test that verifies that we return that error when it occurs. I also verified that the test fails before this change. I also added 100% test coverage to this file to catch any other potential bugs.
None
No
=> Fix bug where we return nil when there's an error in the archival queue

service/history/archival/archiver_test.go
I had a parallel test that looped over some configs, but I forgot to capture the range loop, so the behavior of the test was non-deterministic. I fixed it by capturing the range variable.
**Why?**
Because this was a bug (only in tests though).
I reran the test, with coverage, and I verified that the coverage is 94.2%. Before, only some tests were run so it was only 29%.
None
No
=> Fix range variable in archiver_test not being captured

service/history/configs/config.go, service/history/workflow/history_builder.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandler.go, service/history/workflowTaskHandlerCallbacks.go
Minor renames in `workflow_task_state_machine.go` and related files.
**Why?**
Prerequisite to bigger refactorings.
No risks.
No.
=> Workflow task state machine: minor renames

service/history/ndc/branch_manager.go, service/history/ndc/branch_manager_test.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/workflow_task_state_machine.go
Refactor transient workflow task state machine. Added `IsTransientWorkflowTask()` method to mutable state and use it everywhere to determinate if workflow task is transient or not.
Also significantly improved comments about transient workflow task state machine logic.
**Why?**
Consistent behaviour based on attempts count but not on event ids.
No risks.
No.
=> Refactor transient workflow task state machine

host/cancel_workflow_test.go, host/client_integration_test.go, host/cron_test.go, host/gethistory_test.go, host/max_buffered_event_test.go, host/onebox.go, host/schedule_test.go, host/test_cluster.go, host/workflow_failures_test.go, host/xdc/integration_failover_test.go
This fixes all of the issues errcheck warns us about in ./host except for those in `query_workflow_test.go` because those aren't as straightforward, so I want those to be reviewed separately.
**Why?**
This is for the effort to fix errcheck everywhere in OSS
CI
None
No
=> Fix errcheck in ./host/

common/persistence/dataInterfaces.go, common/persistence/sql/common.go, common/persistence/tests/sqlite_test.go
^
**Why?**
This will surface errors if we fail to close SQL databases in prod and in tests
Reran errcheck
None because this just logs the close error instead of failing
No
=> Fix errcheck in ./common/persistence/

service/worker/pernamespaceworker.go, service/worker/scheduler/workflow.go, service/worker/worker.go
We now surface errors from code within `service/worker`. 
1. We log an error when we fail to unregister a membership listener in the per-namespace worker
1. We log a fatal error when we fail to register the membership listener during startup
1. We log a fatal error whenever any SDK workers fail to start 
1. The scheduler will retry now whenever the side effect of creating a new UUID fails (this should be rare, but we still shouldn't ignore these errors).
**Why?**
I made these changes so that we don't silently swallow these errors. Additionally, this will enable us to run `errcheck` on this directory.
I tested this using the CI. However, I made sure that the not-so-important errors, like unregistering a membership listener, are only logged, not …
=> Fix errcheck in service/worker/

common/archiver/filestore/historyArchiver_test.go, common/archiver/filestore/util.go, common/archiver/filestore/visibilityArchiver_test.go, common/archiver/gcloud/connector/client.go, common/archiver/gcloud/connector/client_test.go, common/archiver/gcloud/historyArchiver.go, common/archiver/s3store/historyArchiver_test.go
^
**Why?**
For code quality
Reran errcheck
The listFiles method of our file store might start failing
No
=> Fix errcheck in ./common/archiver/

common/dynamicconfig/file_based_client_test.go, common/membership/grpc_resolver.go, common/membership/rpMonitor_test.go
^
**Why?**
Fixing all errcheck warnings
Reran errcheck
We may fail to start the GRPC resolver now when we can't add the listener
No
=> Fix errcheck in ./common/membership/

service/history/replication/ack_manager.go
Use latest replication task time as sync shard time
**Why?**
It should use latest replication task visibility time. This represents the lag on replication. If the replication task is empty, then it can use the cluster local time.
=> Use latest replication task time as sync shard time

.github/workflows/golangci-lint.yml, .golangci.yml, Makefile
In this PR, I added `golangci-lint` to our repo, consolidating our compatible linters with this linter aggregator. 
**Why?**
I made this change for a few reasons:
1. This linter aggregator has a GitHub action which shows violations in-line on PRs
2. This linter has a `--new` option which allows it to be applied only to new changes because we currently have a massive number of violations.
3. `golint` is deprecated
4. No actions were taken based on the issues raised by some of the previous linters--all of these warnings are blocking and actionable
I ran it locally and saw that only new errors were checked. I also tested it locally a few times using `act`. To test this in a real example, I created a new branch here and verified that the annotations …
=> Consolidate linters with golangci-lint

host/onebox.go, host/test_cluster.go
I removed the `Temporal` interface in `./host`, and I also made the `newTemporal` method unexported.
**Why?**
The `Temporal` interface was not used, and the `newTemporal` method returns an unexported type, so it should also be unexported.
CI
There could be some people who rely on this interface currently. However, the `temporalImpl` struct doesn't even implement this interface, so I'm not sure how they'd be using it.
No.
=> Remove unused Temporal interface

tools/cassandra/setupTask_test.go, tools/tdbg/app_test.go, tools/tdbg/dlq_commands.go, tools/tdbg/factory.go, tools/tdbg/util.go
^
**Why?**
For code quality
Reran errcheck
None
No
=> Handle unhandled errors in tools/

common/dynamicconfig/constants.go, service/history/api/describeworkflow/api.go, service/history/archival/archiver_test.go, service/history/archival/fx.go, service/history/archival_queue_task_executor_test.go, service/history/configs/config.go, service/history/fx.go, service/history/workflow/relocatable_attributes_fetcher.go, service/history/workflow/relocatable_attributes_fetcher_test.go
- I added a Module to the service/history/archival package and embedded it in the history module
- I also modified our existing tests to use this module instead of the raw constructor to improve test coverage
**Why?**
I made this change so that we can inject the required dependencies into the archival queue
I tested this by modifying our tests to use this module instead of the normal constructor, and I then checked test coverage as well. I also ran a simple `make start`. Additionally, this dependency isn't required anywhere yet, so it shouldn't actually be run in prod.
None.
No
=> Create an FX Module for Archival

common/quotas/multi_rate_limiter_impl_test.go, common/quotas/priority_rate_limiter_impl_test.go, common/rpc/context_test.go, service/frontend/workflow_handler_test.go
^
**Why?**
To avoid context leaks
I reran govet and saw that the only errors exist in the persistence tests dir. I may fix that later, but it will be a much larger diff.
None. These are just test files.
No
=> Fix some lostcancel errors

service/history/shard/context_impl.go, service/history/shard/context_test.go, service/history/shard/controller_test.go
=> Fix errcheck in service/history/shard

common/dynamicconfig/constants.go, host/archival_test.go, service/history/configs/config.go, service/history/queueFactoryBase.go
*Note: the merge base of this PR is a branch that contains commits from several of my other archival PRs. I will change the merge base to master and rerun the CI before landing this. I did this to unblock review of this PR*
I added an integration test that runs the archival suite with durable archival on and off.
**Why?**
I made these changes to enable us to add the archival queue with more confidence that it works.
There were only a few code changes, and all of them are covered by the integration test.
An OSS user may now turn on durable archival if they see this flag, and we haven't QA'd this within our own test clusters yet.
No. We should only send the notification when it's enabled by default.
=> Add an integration test for durable archival

service/history/archival/archiver.go, service/history/archival/archiver_test.go
Fixed a small perf. issue in the archiver.
**Why?**
We acquire 2 rate-limiter tokens when we only need one sometimes
Updated unit test
None
No
=> Fix token count in archival rate limiter

.github/workflows/golangci-lint.yml, .golangci.yml
I turned on every linter for Revive except a few handpicked ones that I thought weren't useful.
**Why?**
We don't want to enable some useless linters like `exported`, but having linters like `cyclomatic` for new code seem really useful.
I ran it locally. I also inspected the actual errors generated using this JQ query to see if they made sense:
```
golangci-lint run  --verbose --out-format=json --max-issues-per-linter=0 --max-same-issues 1 \
| jq '.Issues | map((.Text| split(": ") | {"Rule": .[0], "Value": .[1]}) + {"Key": "./\(.Pos.Filename):\(.Pos.Line)"}) | group_by(.Rule) | map({"Rule": .[0].Rule, Violations: ([.[]] | from_entries )}) | sort_by(.Violations | length)'
```
It's just a linter
No
=> Fine-tune the Revive linter

service/history/queues/scheduler.go
- Error from GetNamespaceByID needs to be handled as it will return nil ptr. Previously the code is calling GetNamespaceName which returns empty name if namespace not found and error can be ignored.
**Why?**
- Fix npe
- Yes.
=> Fix NPE in task channelWeightFn

common/persistence/tests/execution_mutable_state.go, common/persistence/tests/execution_mutable_state_task.go, common/persistence/tests/shard.go
In `common/persistence/tests/shard.go`, `ShardID` is not hardcoded, but auto-incremented, consistently with other test files in current directory.
**Why?**
Consistency and ground work for future features.
`make test`
None.
No.
=> Make persistence tests consistent in handling ShardID

.github/workflows/golangci-lint.yml
Changed linter workflow triggering condition to run on pull requests.
**Why?**
To have linter job status on PRs.
GitHub
The missing job runs on other conditions.
Revert.
=> Trigger golangci-lint on pull requests

common/util.go, service/history/archival_queue_task_executor_test.go, service/history/queues/executable.go, service/history/queues/executable_test.go, service/history/queues/metrics.go, service/history/queues/queue_base.go, service/history/queues/reader_test.go, service/history/queues/slice_test.go, service/history/timerQueueActiveTaskExecutor_test.go, service/history/timerQueueStandbyTaskExecutor_test.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/visibilityQueueTaskExecutor_test.go
- Capture task processing panic
**Why?**
- We have panic wrapper for api handlers. Adding similar logic for task execution logic to prevent service from crashing when panic happens when processing tasks. The task will stuck and keep retrying (when we have dlq, it should go there), but service can continue to run and other tasks/workflows can still make progress.
- Unit test
=> Capture task processing panic

common/metrics/metric_defs.go, common/namespace/namespace.go, common/namespace/registry.go, common/namespace/registry_mock.go, common/namespace/registry_test.go, service/history/historyEngine.go, service/history/queues/queue.go, service/history/queues/queue_base.go, service/history/queues/queue_mock.go, service/history/queues/rescheduler.go, service/history/queues/rescheduler_mock.go, service/history/queues/rescheduler_test.go, service/history/queues/scheduler.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go
- Deprecate old namespace change callback and use new namespace state change callback
**Why?**
- New task processing logic guarantees task execution and doesn't rely on handling namespace failover in an ordered fashion (based on namespace notification version)
- Existing test, will test failover/migration as well.
=> Deprecate old namespace change callback

common/cluster/metadata.go, service/history/replication/poller_manager.go, service/history/replication/poller_manager_test.go
Add a component to assign polling shards
**Why?**
To allow cross shard replication, the current limitations:
1. remove cluster shard count and local shard count must be multiples.
Add unit test
No
=> Add a component to assign polling shards

service/frontend/overrides.go, service/frontend/overrides_test.go
Apparently Python 0.1b1 also has a buggy implementation of eager activities, disable eager activity dispatch for that version.
=> Disable eager activities for Python 0.1b1 too

common/dynamicconfig/constants.go, service/frontend/fx.go, service/frontend/service.go
Add `internal-frontend.globalNamespaceRPS` and `internal-frontend.globalNamespaceRPS.visibility` to match the `frontend` versions of those configs, which divide their value among internal-frontend nodes.
**Why?**
"Global" namespace rps was divided among the number of "frontend" nodes, but for users using internal-frontend, that didn't make much sense, since the number of internal-frontend will likely be different from frontend, and the load will be different too.
Only the "global" versions were added, not "per-instance". If they are not set, internal-frontend will use the same per-instance configs as frontend (it will not fall back to the global frontend configs). To use a separate limit for internal-frontend, use the global versions.
CI …
=> Add separate dynamic config knobs for internal-frontend rate limiting

CONTRIBUTING.md
Add test definition in readme
**Why?**
Add test definition in readme
=> Add test definition in readme

service/frontend/adminHandler.go, service/frontend/adminHandler_test.go, service/frontend/operator_handler.go, service/frontend/operator_handler_test.go
Allow connect clusters with different shards
**Why?**
This is to support connect two clusters with different shard count.
Unit tests.
No
=> Allow connect clusters with different shards

common/persistence/cassandra/test.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go, common/persistence/persistence-tests/clusterMetadataManagerTest.go, common/persistence/persistence-tests/historyV2PersistenceTest.go, common/persistence/persistence-tests/metadataPersistenceV2Test.go, common/persistence/persistence-tests/queuePersistenceTest.go, common/persistence/sql/sqlplugin/tests/context.go, common/persistence/tests/execution_mutable_state.go, common/persistence/tests/execution_mutable_state_task.go, common/persistence/tests/history_store.go, common/persistence/tests/shard.go, common/persistence/tests/task_queue.go, common/persistence/tests/task_queue_task.go, common/persistence/tests/visibility_persistence_suite_test.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go, service/history/queues/queue_base.go, service/history/shard/context_impl.go, service/history/transferQueueTaskExecutorBase.go, service/matching/taskQueueManager.go
Add `debug.TimeoutMultiplier` to all timeouts.
**Why?**
For better debug expirience it is better to have longer timeouts to make sure that debugger doesn't stop on random `context deadline exceeded` errors.
No risks.
No.
=> Add debug.TimeoutMultiplier to all timeouts

service/history/historyEngine2_test.go, service/history/historyEngine_test.go, service/history/timerQueueActiveTaskExecutor_test.go
I added archival queue mocks to the history engine tests.
**Why?**
I noticed these tests were failing when the archival queue was enabled. This is a quick fix.
Reran tests with archival queue enabled
None, just tests
No
=> Add mock archival queue processors to history engine tests

common/metrics/metric_defs.go, service/history/archival_queue_task_executor.go, service/history/archival_queue_task_executor_test.go
After manual testing, I spotted a few issues in this code.
1. We fail the task if there are zero enabled targets for archival, which might happen if a task is produced and then archival is disabled before the task is executed. In this case, we should continue processing the task, skipping archival but generating the deletion task.
1. We are parsing archival URIs unconditionally here, but we should only parse them for enabled targets. We cannot assume that those URIs will be valid when the corresponding target is disabled.
**Why?**
Bug fixes
I modified the unit tests. I also reverted the code changes other than the test code and verified that the tests "URIs are not read for empty targets" and "both history and visibility archival disabled" …
=> Fix some bugs in the archival queue task executor

service/worker/scanner/scanner.go, service/worker/scanner/scanner_test.go
I modified the Stop() method of our scanners to cancel running attempts to start workflows.
**Why?**
I did this because it fixes a race condition which often occurs when the server is shutdown soon after starting. When the server is shutdown, the scanner may still be trying `startWorkflow`. This method utilizes an SDK client. However, when the server shutdown all of its services, it may shutdown the frontend handler before the scanner. As a result, all calls to the SDK client will fail, causing startWorkflow to fail. Currently, we retry startWorkflow a lot, so the scanner can currently enter a long-running retry loop. To fix this, we now cancel the retries as soon as the scanner is shutdown.
I added a test case which simulates the setup described …
=> Fix a rare deadlock in scanner.Stop

common/archiver/archivalMetadata.go, common/archiver/metadata_mock.go, common/archiver/metadata_mock_test.go, common/resourcetest/resourceTest.go, service/frontend/workflow_handler_test.go, service/history/archival_queue_task_executor.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/workflow/task_generator.go, service/history/workflow/task_generator_provider.go, service/history/workflow/task_generator_test.go
We now produce archival queue tasks only if archival and the archival queue are enabled.
**Why?**
Durable archival will soon be on by default, but there's only a point in producing these tasks if archival itself is enabled.
I wrote several new test cases in the task_generator.
This adds a new check to our task generator, and if there's an NPE at some point, that could break production. However, this will only happen if the archival metadata on the cluster or the namespace is nil.
No
=> Produce archival tasks conditionally

client/clientfactory.go, client/matching/client.go, common/dynamicconfig/constants.go
This dynamic config was introduced in 1.18 to use during the upgrade process and should be set everywhere by now.
**Why?**
Clean up old code.
CI
If users haven't manually set the dynamic config to false, they'll have disrupted task dispatch during the upgrade to 1.20.
=> Remove matching.useOldRouting dynamic config

common/persistence/sql/sqlplugin/mysql/cluster_metadata.go, common/persistence/sql/sqlplugin/postgresql/cluster_metadata.go, common/persistence/sql/sqlplugin/sqlite/cluster_metadata.go
In `GetClusterMembers`, fix the time fields, ie., call date time converter.
**Why?**
The times are stored in UTC in DB, but when reading, the time zone might not be set correctly. Calling the date time converter fixes it.
None.
No.
=> Fix time fields of rows from GetClusterMembers

.golangci.yml, Makefile
Tune linter config and `Makefile`.
**Why?**
Make developer experience better.
Run on Buildkite.
No risks.
No.
=> Tune linters

common/log/zap_logger.go
Add `TEMPORAL_TEST_LOG_FORMAT` and `TEMPORAL_TEST_LOG_LEVEL` environment variables to control test log output.
**Why?**
Sometimes you want to get json log output
Manually
No, only applies to tests
=> Add env vars to control log format and level for tests

service/worker/pernamespaceworker.go, service/worker/service.go, tests/dynamicconfig.go
Add `RefreshPerNSWorkerManager` to worker service, and `RemoveOverride` to integration test dynamic config.
**Why?**
These can be used to adjust dynamic config that applies to per-ns-worker or its components, for a single integration test. These will be used in upcoming PRs.
Used in upcoming PRs
Only used in tests
=> Add RefreshPerNSWorkerManager and RemoveOverride for tests

service/history/commandChecker.go, service/history/commandChecker_test.go
- Validate workflow run timeout, workflow task timeout and retry policy upon continue as new.
**Why?**
- https://github.com/temporalio/temporal/issues/3811
- Unit test
=> Fix continue as new validation

service/history/historyEngine.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go
- Remove ns from shard context handover map if it's no longer in handover state
**Why?**
- Tested in test cluster
=> Fix handover callback

service/frontend/workflow_handler.go, service/worker/scheduler/workflow.go, tests/schedule_test.go
The ListSchedules api depends on the memo fields of internal scheduler workflows. The memo is upserted by each workflow task, but before the first workflow task has run, it would be empty, so ListSchedules would return a schedule with no metadata, which is confusing. This adds an initial memo with the same contents that the first workflow task would have set.
**Why?**
So ListSchedules always returns a sensible result.
New integration test
=> Add initial memo to scheduler workflows

service/history/shard/context_impl.go, service/history/shard/controller_test.go
This change reverts a commit which added error-checking to service/history/shard, and it makes our code explicitly ignore those errors.
**Why?**
1. We don't want the controller to be aware of these errors
2. The usage of multierr may cause explicit error type checks to fail
3. Error logging is already in place
It's a small PR, so I verified the diff was only the intended changes, and you can see the `multierr` import is removed.
Nothing, reverting to the behavior in 1.19.
No
=> Revert #3755

common/searchattribute/validator.go, common/searchattribute/validator_test.go, service/frontend/workflow_handler.go, service/history/commandChecker.go, service/history/commandChecker_test.go, service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/workflowTaskHandler.go, service/history/workflowTaskHandlerCallbacks_test.go
Added index name to constructor of search attributes validator.
**Why?**
Validator functions already require index name which should be constant throughout the execution of the Server, so moving the constructor. It will avoid needing to keep track of index name and validator objects separately in the codebase in case the validator object is passed to other structs.
There shouldn't have any risks.
No.
=> Add index name to constructor of search attribute validator

cmd/server/main.go, temporal/server.go
If running without a `--service` flag (e.g. in development or a tiny test environment), don't run internal-frontend (and don't require it in the static config).
**Why?**
So that the new version works with old static config files.
Manually
Only affects running without `--service`, which shouldn't happen in production environments
=> Remove internal-frontend from default services

config/development-active.yaml, config/development-cass-archival.yaml, config/development-cass-es.yaml, config/development-cass.yaml, config/development-mysql-es.yaml, config/development-mysql.yaml, config/development-other.yaml, config/development-postgres-es.yaml, config/development-postgres.yaml, config/development-sqlite-file.yaml, config/development-sqlite.yaml, config/development-standby.yaml, temporal/server_test.go
Remove internal-frontend from development configs
**Why?**
Fix development config; we don't need this to test functionality during development
Manually, will add integration test for internal-frontend elsewhere
=> Remove internal-frontend from development configs

service/history/queueFactoryBase.go, service/history/queue_factory_base_test.go, service/history/tasks/category.go
We now only register the archival category when archival is enabled.
**Why?**
Because if this category exists when the archival queue processor isn't running, our code will panic when NotifyNewTasks is run.
I added an assertion in a unit test.
This may interfere with tiered storage.
No
=> Conditionally register archival category

service/history/historyEngine_test.go, service/history/workflowTaskHandler.go
- Check for workflow completion when eagerly starting activity 
**Why?**
- Eager start activity is done after all commands have been processed, which means workflow may already be closed. Then AddActivityTaskStarted will fail on immutability check since no event can be added after workflow close.
- Added unit test.
- Also reproed the issue locally and verified the fix resolves the issue.
- Can be
=> Fix activity eager execution on workflow close

go.mod, go.sum, service/frontend/errors.go, service/frontend/namespace_handler.go, service/frontend/operator_handler.go, service/frontend/operator_handler_test.go
Update operator handler commands over search attributes to work when using SQL DB.
**Why?**
Support for advanced visibility with SQL DB.
Tested commands in local run of server using SQL DB.
It's no-op for Elasticsearch.
No.
=> Update search attributes operator commands to handle aliasing

schema/sqlite/v3/visibility/schema.sql
Changed SQLite visibility schema to support advanced visibility:
- Added search attributes JSON map.
- Added generated columns to extract the search attributes fields from JSON.
- Changed indices.
**Why?**
Advanced visibility with SQL databases.
Started temporal using SQLite, and ran some samples.
No risks in production, only affects when using with SQLite.
No.
=> [Advanced Visibility with SQL] Changing visibility schema for SQLite

common/config/persistence.go, common/searchattribute/defs.go, temporal/fx.go
Register the pre-allocated custom search attributes when starting new instances of Temporal Server using SQL DB as visibility storage, or during the first start of the Server after upgrading to v1.20.
**Why?**
Support for advanced visibility using SQL DB: custom search attributes are pre-allocated and doing this automatically provides a more seamless experience to the user.
Start new Server before changes, and then after. Logs show the search attributes being registered successfully:
```
{"level":"info","ts":"2023-01-27T17:16:01.894-0800","msg":"Successfully registered search attributes.","component":"metadata-initializer","cluster-name":"active","logging-call-at":"fx.go:733"}
```
No.
No.
=> Handle updating cluster metadata search attributes info when using SQL DB

common/resource/fx.go, common/searchattribute/mapper.go, common/searchattribute/test_provider.go, common/searchattribute/validator.go, develop/buildkite/docker-compose.yml, develop/buildkite/pipeline.yml, develop/buildkite/scripts/coverage-report.sh, tests/integrationbase.go
Updated `searchattribute.MapperProvider` to support the mapper from namespace config.
Created wrapper mapper to be backwards compatible with custom search attributes registered while using SQL DB.
Added integration tests using mysql8 and postgres12 plugins.
**Why?**
This is the default mapper when using SQL DB for advanced visibility.
Existing unit tests. Needs more tests to cover new case, but postponing to another PR.
No.
No.
=> Implement default mapper for SQL visibility

common/searchattribute/manager.go, common/searchattribute/validator.go
Merge custom search attributes from the index name key with the empty string key in `searchattribute.Manager.GetSearchAttributes`.
**Why?**
There was a check to handle it in the search attribute validator, but there are many more calls to `GetSearchAttributes` in the codebase. In order for than to be backwards compatible, I'm merging with the contents in the empty string key.
Unlikely to have issue. The new index name key should be empty, so merging with the contents in the empty string key should be no-op.
One situation that might have issue is if the user is using Elasticsearch and there's the empty string key in cluster metadata. This might lead to unexpected results.
No.
=> Merge custom search attributes from index name with empty string key

service/history/replication/poller_manager.go, service/history/replication/poller_manager_test.go, service/history/replication/task_processor_manager.go
Return error if cluster metadata is invalid.
**Why?**
It should not panic as the cluster may not be found after disconnect.
Local test
=> Return error if cluster metadata is invalid

common/persistence/sql/sqlplugin/mysql/admin_v8.go
Add MySQL 8 admin overwriting `create_database` to create using the standard MySQL 8 charset.
**Why?**
Currently, it's using the MySQL 5.7, which uses old utf8 charset.
Unit tests.
None.
No.
=> Add MySQL 8 admin interface

docker/config_template.yaml
Fix docker config template to set up only one visibility store.
**Why?**
Having both standard and advanced visibility store configs make the Server to set up dual visibility store, which messes up with search attributes.
Build docker images, ran it, and checked logs.
No.
No.
=> Fix docker config template to set only one visibility

common/rpc/interceptor/telemetry.go, common/rpc/interceptor/telemetry_test.go
Prepend Admin/Operator to operation tag for operations from admin/operator handler. 
**Why?**
Certain operation from admin/operator has same name as the ones from workflow service, for example DeleteWorkflowExecution. We used to prepend Admin/Operator to the operation tag, but it was missed in last metrics refactoring. 
New unit test
No.
No
=> Overwrite operation for admin and operator APIs

common/persistence/sql/sqlplugin/interfaces.go, common/persistence/sql/sqlplugin/mysql/visibility_v8.go, common/persistence/sql/sqlplugin/tests/visibility.go, common/persistence/sql/sqlplugin/util.go, common/persistence/sql/sqlplugin/visibility.go, common/persistence/tests/visibility_persistence_suite_test.go, common/persistence/visibility/factory.go, common/persistence/visibility/store/query/converter.go, common/persistence/visibility/store/sql/pagination_token.go, common/persistence/visibility/store/sql/query_converter.go, common/persistence/visibility/store/sql/query_converter_factory.go, common/persistence/visibility/store/sql/query_converter_mysql.go, common/persistence/visibility/store/sql/query_converter_util.go, common/persistence/visibility/store/sql/visibility_store.go, common/searchattribute/defs.go
Implements the new advanced visibility store interface for SQL DB.
Implements new query converter.
Implements MySQL 8 query converter.
**Why?**
Advanced visibility for MySQL 8
Ran local server, and run tests based on the custom search attributes sample code.
None.
No.
=> Advanced visibility for MySQL

common/persistence/sql/sqlplugin/postgresql/typeconv.go, common/persistence/sql/sqlplugin/postgresql/visibility_v12.go, common/persistence/visibility/factory.go, common/persistence/visibility/store/sql/query_converter_factory.go, common/persistence/visibility/store/sql/query_converter_postgresql.go
Implement PostgreSQL query converter for advanced visibility.
Implement PostgreSQL `visibility_v12.go`, the DB interface for advanced visibility.
**Why?**
Support advanced visibility for PostgreSQL 12+.
Started local server, and ran samples with custom search attributes.
None, it only affects new use cases using `pluginName = postgres12`.
No.
=> Advanced visibility for PostgreSQL

common/persistence/sql/sqlplugin/sqlite/plugin.go, common/persistence/sql/sqlplugin/sqlite/typeconv.go, common/persistence/sql/sqlplugin/sqlite/visibility.go, common/persistence/tests/sqlite_test.go, common/persistence/visibility/factory.go, common/persistence/visibility/store/sql/query_converter_factory.go, common/persistence/visibility/store/sql/query_converter_sqlite.go
Implement SQLite query converter for advanced visibility.
Update `sqlite/visibility.go` DB interface to advanced visibility.
**Why?**
Support advanced visibility for SQLite.
Started local server, and ran samples with custom search attributes.
None, sqlite is supported only for dev, and mostly using in-memory database.
No.
=> Advanced visibility for SQLite

common/membership/rpMonitor_test.go
I changed the listen address in this test from 0.0.0.0 to 127.0.0.1
**Why?**
This was causing an annoying prompt on each test run for macOS: 
It's also totally unnecessary because we don't care about traffic coming from outside our host in this test.
I reran and verified that the prompt disappeared.
=> Listen for loopback instead of all incoming traffic in RP test

common/metrics/metric_defs.go, service/worker/scheduler/workflow.go
- Add some metrics to scheduler workflow
- Add max buffer size to prevent it from growing indefinitely
- Reduce some log levels
- Include namespace in logs
**Why?**
Observability
existing tests, mostly just adding metrics
=> Add metrics + max buffer size to schedule workflow

service/history/historyEngine2_test.go, service/history/workflow/workflow_task_state_machine.go, tests/update_workflow_test.go
Fix fail of speculative workflow task. If speculative workflow task is failing, corresponding WTScheduled and WTStarted events are added (similar to WTCompleted), and next workflow task is created as transient.
**Why?**
Consistency with normal workflow task.
Added new integration test.
No risks.
No.
=> Fix fail of speculative workflow task

common/persistence/visibility/store/sql/visibility_store.go
Remove search attributes keys with nil values.
**Why?**
Search attributes with nil values is the syntax to remove them. In practice, it just remove from the persistence map (ie., it won't store {"key": null} for example). Other than that, it was already working as expected.
Launched server, ran workflow to set search attribute, and then set to nil or empty list. Checked the database to confirm the keys are not there.
No.
No.
=> Remove search attributes with nil values

common/locks/condition_variable_impl.go, common/locks/condition_variable_test.go
* Conditional variable broadcast function should create channel with size 1, not 0
**Why?**
0 size channel does not guarantee ordering
when the conditional is initialized, [the signal channel is correctly initialized with size 1](https://github.com/temporalio/temporal/blob/v1.19.0/common/locks/condition_variable_impl.go#L49)
however (the bug) [incorrectly re-initialized the signal channel with size 0](https://github.com/temporalio/temporal/blob/v1.19.0/common/locks/condition_variable_impl.go#L67)
when a coroutine waits for notification, there is a time gap & lock gap between [accessing the signal channel](https://github.com/temporalio/temporal/blob/v1.19.0/common/locks/condition_variable_impl.go#L84) and [selecting on the signal …
=> Bugfix: conditional variable broadcast channel size

common/persistence/visibility/store/standard/cassandra/visibility_store.go, common/persistence/visibility/store/standard/sql/visibility_store.go, common/persistence/visibility/store/standard/visibility_store.go, common/searchattribute/manager.go, service/frontend/adminHandler.go, service/frontend/operator_handler.go, service/history/fx.go, tests/test_cluster.go
When using standard visibility, return empty string index name (`""`).
For search attribute operations, when the index name is an empty string, run the same workflow as before (try to register to cluster metadata).
**Why?**
Backward compatibility with standard visibility.
Start server with Cassandra, and tried to add search attributes.
None.
No.
=> Fix backward compatibility with std visibility when doing search attribute operations

common/persistence/visibility/store/sql/query_converter_mysql.go
MySQL select query for visibility change to do `LEFT JOIN` instead of `INNER JOIN`.
**Why?**
For backward compatibility, old workflows won't have a corresponding row in `custom_search_attributes` table, but they are valid workflows. Doing a left join makes sure that all executions are listed correctly.
Started Server using standard visibility, created workflows, upgraded DB schema to support advanced visibility, and restarted Server. Open UI to list all workflows, and now it's listing everything.
None.
No.
=> Fix MySQL visibility select query

client/matching/loadbalancer.go
Fix min/max mixup in matching client
**Why?**
We need to be able to use more than 1 partition :)
Eyeballs, will add a unit test later
=> Fix silly bug in matching client

common/persistence/visibility/defs.go, common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go, common/persistence/visibility/store/sql/visibility_store.go, common/searchattribute/encode.go, common/searchattribute/encode_test.go, common/searchattribute/encode_value.go, common/searchattribute/encode_value_test.go, common/searchattribute/stringify.go, common/searchattribute/validator.go, common/searchattribute/validator_test.go, service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go, service/history/commandChecker_test.go, service/history/historyEngine.go, service/history/historyEngine2_test.go, service/history/workflowTaskHandlerCallbacks_test.go
Implement strict mode to decode/validate search attributes. Strict mode don't allow list of values for the respective types. Only `KeywordList` is allowed.
It will be enabled by default when using SQL DB for visibility.
**Why?**
For now, we're still gonna let allow it for ES until the SDK start enforcing as well.
For SQL, it's not supported at all, so adding it to validation.
It's no-op for existing usages.
No.
=> Strict validation when using SQL DB for visibility

temporal/server_impl.go
Use max join time as start timeout.
**Why?**
https://github.com/uber-go/fx/pull/875/files
Fx fix the context timeout error. The server start timeout could be too short.
local test:
1. Make start
2. Kill the process
3. Immediately run `./temporal-server --env development-cass --allow-no-auth start --service frontend`
Consider for https://github.com/temporalio/temporal/issues/3826
=> Use max join time as start timeout

service/history/historyEngine_test.go, service/history/workflowTaskHandler.go, service/history/workflowTaskHandlerCallbacks.go
Rename `failCommand` to `failWorkflowTask` because it fails workflow task not command and extract other methods to better code reuse.
**Why?**
To reuse code to fail workflow task in different places.
No risks.
No.
=> Refactor failWorkflowTask method

service/history/workflowTaskHandler.go
Fail workflow task with `BadSearchAttributes` cause if search attributes mapper returned an error.
**Why?**
Just returning an error from `handleCommands` causes workflow task to timeout but not to fail, which is wrong.
Failing workflow task allow to write error message to the history and expose error message in WebUI/tctl.
Upcomming functional tests.
No risks but there is small behaviour change: WTFail event will be written to the history instead of WTTimeout.
No.
=> Fail workflow task with BadSearchAttributes cause if search attributes mapper returned an error

service/frontend/redirection_interceptor.go
* Reduce unnecessary log noise in redirection handler
**Why?**
admin handler & other future handler does not need redirection, reduce unnecessary noise
N/A
N/A
N/A
=> Reduce unnecessary log noise

common/persistence/visibility/store/sql/query_converter_mysql.go, schema/mysql/v8/visibility/schema.sql, schema/mysql/v8/visibility/versioned/v1.2/advanced_visibility.sql
Removing `namespace_id` from MySQL full text search index.
**Why?**
`namespace_id` cannot be included to the index since there's no easy way to enforce namespace id value with the actual query string to be matched.
Started server, and run workflows querying Text type search attribute. Checked that it return empty result when no word matches the content.
No risks.
No.
=> Fix MySQL visibility index for full text search

common/namespace/replicationTaskExecutor.go, common/namespace/transmissionTaskHandler.go, service/frontend/namespace_handler.go
Replicate custom search attributes aliases with namespace replication.
**Why?**
Custom search attributes aliases must be replicated together with other namespace config fields.
Elasticsearch integration tests running on top of SQL advanced visibility (upcomming PR).
No risks.
No.
=> Replicate custom search attributes aliases with namespace replication

common/rpc/interceptor/api_name.go, service/frontend/redirection_interceptor.go, service/frontend/redirection_interceptor_test.go
Call `RedirectionInterceptor` only for `WorkflowHandler`.
**Why?**
`RedirectionInterceptor` is not intended to be used by other than `WorkflowHandler` handler.
No risks.
No.
=> Call RedirectionInterceptor only for WorkflowHandler

common/persistence/visibility/store/sql/query_converter.go, common/persistence/visibility/store/sql/query_converter_mysql.go, common/persistence/visibility/store/sql/query_converter_postgresql.go, common/persistence/visibility/store/sql/query_converter_sqlite.go, common/persistence/visibility/store/sql/query_converter_util.go, schema/mysql/v8/visibility/schema.sql, schema/mysql/v8/visibility/versioned/v1.2/advanced_visibility.sql
Cast max datetime string to datetime type in MySQL COALESCE calls.
Refactor `getCoalesceCloseTimeExpr` to be part of `pluginConverter` interface.
**Why?**
MySQL coalesce with datetime and string results in a string, which can cause incorrect comparisons with datetime (eg: times `12:12:12` is different than `12:12:12.000`).
So, adding a `CAST` to max datetime so it's handled correctly as datetime type column.
This also fixes flaky tests in `TestMySQL8VisibilityPersistenceSuite`
Hard coded a time with leading zeros, and tests are now passing.
No risks.
No.
=> Fix MySQL visibility indexes with close_time column

common/persistence/visibility/store/sql/query_converter_postgresql.go, common/persistence/visibility/store/sql/query_converter_sqlite.go, common/persistence/visibility/store/sql/query_converter_util.go
Tokenize and build FTS query string for PostgreSQL and SQLite.
**Why?**
PostgreSQL and SQLite have a specific syntax for FTS query strings.
Start server, and ran workflow trying different query strings. Checked the built query is correct.
No risks.
No.
=> Tokenize and build FTS query string for postgres and sqlite

common/persistence/visibility/store/sql/query_converter.go, common/persistence/visibility/store/sql/visibility_store.go
Handle namespace division filter in the new SQL visibility store.
**Why?**
Copying logic from Elasticsearch visibility store/query builder (namespace division was previously ignored).
No risks.
No.
=> Handle namespace division filter in SQL queries

common/dynamicconfig/constants.go, service/frontend/service.go
Make frontend drain traffic time configurable
**Why?**
Make frontend drain traffic time configurable
=> Make frontend drain traffic time configurable

tests/eager_workflow_start_test.go, tests/integration_test.go
I realized that most of the E2E tests I wrote for this in the features repo should actually be integration tests.
=> Add integration tests for eager workflow start

common/membership/interfaces.go, common/membership/interfaces_mock.go, common/membership/rpMonitor.go, common/resourcetest/resourceTest.go, service/frontend/fx.go, service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go, tests/simpleMonitor.go
Frontend shouldn't return SERVING (for `temporal.api.workflowservice.v1.WorkflowService`) until it has initialized ringpop.
**Why?**
During this period any rpc sent to frontend that requires a history or matching backend will fail, so it shouldn't accept them.
Manually, will test in staging environment
=> Frontend health check waits until membership initialized

service/frontend/workflow_handler.go
Remove unnecessary aliasing/unaliasing of scheduled workflow search attributes.
**Why?**
They are getting unaliases when workflow is actually started.
Functional tests over sqlite. 
No risks.
No.
=> Remove unnecessary aliasing/unaliasing of scheduled workflow search attributes

docker/config_template.yaml
Handle setting up the correct plugin name for `mysql8` and `postgres12`.
**Why?**
Support advanced visibility with SQL db with docker.
Local build, and tested.
No risks.
No.
=> Support mysql8 and postgres12 dbs in docker config template

common/tasks/interleaved_weighted_round_robin_test.go
- Fix TestUpdateWeight
**Why?**
- Update channel was wrongly initialized with 0 capacity in test. Production code don't have this problem
`go test -run TestInterleavedWeightedRoundRobinSchedulerSuite -testify.m TestUpdateWeight -count=100`
no, only fixing test
no
=> Fix TestUpdateWeight

.golangci.yml, service/frontend/workflow_handler.go, tests/advanced_visibility_test.go, tests/namespace_delete_test.go, tests/schedule_test.go, tests/xdc/advanced_visibility_test.go
Address #3923 feedback.
**Why?**
Accently merged #3923 w/o addressing feedback.
No risks.
No.
=> Address #3923 feedback

common/metrics/metric_defs.go, common/persistence/persistenceMetricClients.go
Separate metrics on read history and read raw history
**Why?**
Read raw history are all system callers.
local test
=> Separate metrics on read history and read raw history

service/frontend/operator_handler.go
Iterate over the pre-allocated custom search attributes instead of the map from cluster metadata.
**Why?**
Cluster metadata might have custom search attributes created by user previously in standard visibility. With current logic, it's possible that an alias will be mapped to those custom search attributes created by the user instead of the pre-allocated ones created by Server.
Start server with std visibility, create search attribute, restart server with adv visibility, and create search attribute with same type. Checked it does not use the one I created previously.
No risks.
No.
=> Fix create custom search attribute with SQL DB

common/persistence/sql/sqlplugin/postgresql/visibility.go
Fix `ExecutionTime` rounding when using PostgreSQL.
**Why?**
`ExecutionTime` need to be properly converted to PostgreSQL datetime format using existing `ToPostgreSQLDateTime` function. 
Existing cron functional test should stop failing.
No risks.
No.
=> Fix ExecutionTime rounding when using PostgreSQL

common/persistence/visibility/store/sql/query_converter_mysql.go, common/persistence/visibility/store/sql/query_converter_postgresql.go, common/persistence/visibility/store/sql/query_converter_sqlite.go
Wrap user's visibility query string in parenthesis.
**Why?**
`AND` has precedence over `OR`, so without parenthesis, if the user's query contains `OR`, it might mix results with other namespaces.
Ran a few workflows in different namespaces, and queried with `OR` expressions.
No risks.
No.
=> Wrap user's visibility query string in parenthesis

common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Remove `isRecordValid` check from ES visibility store (related to ES6).
**Why?**
ES6 support has already been removed.
No risks.
No.
=> Remove isRecordValid check from ES visibility store

common/persistence/sql/sqlplugin/mysql/visibility.go, common/persistence/sql/sqlplugin/mysql/visibility_v8.go, common/persistence/sql/sqlplugin/postgresql/visibility.go, common/persistence/sql/sqlplugin/postgresql/visibility_v12.go, common/persistence/sql/sqlplugin/sqlite/visibility.go, common/persistence/sql/sqlplugin/visibility.go, common/persistence/visibility/store/sql/query_converter.go, common/persistence/visibility/store/sql/query_converter_factory.go, common/persistence/visibility/store/sql/query_converter_mysql.go, common/persistence/visibility/store/sql/query_converter_postgresql.go, common/persistence/visibility/store/sql/query_converter_sqlite.go, common/persistence/visibility/store/sql/visibility_store.go, tests/advanced_visibility_test.go
Implement support for `CountWorkflowExecutions` for advanced visibility with SQL DB.
**Why?**
Advanced visibility with SQL DB.
Enabled `TestCountWorkflow` functional test.
No risks.
No.
=> Support CountWorkflowExecutions for SQL DB

common/persistence/visibility/store/sql/query_converter.go, common/persistence/visibility/store/sql/query_converter_mysql.go, common/persistence/visibility/store/sql/query_converter_postgresql.go, common/persistence/visibility/store/sql/query_converter_sqlite.go, common/persistence/visibility/store/sql/query_converter_util.go
Refactoring SQL query converter:
- Better error messages.
- Util function to extract values from a SQL tuple.
- Rewrite `convertInExpr` in PostgreSQL query converter: change to non-recursive function.
**Why?**
- Better errors messages.
- Less code duplication.
- Better performance with non-recursive function.
No risks.
No.
=> Refactor SQL query converter

go.mod, go.sum
Update Go SDK to v1.21.1
Only change is the go worker will now retry for a short period on fatal errors.
=> Update Go SDK to v1.21.1

common/rpc/interceptor/namespace_validator.go, common/rpc/interceptor/namespace_validator_test.go, service/frontend/fx.go
* Set namespace on API if not present
* RespondQueryTaskCompletedRequest
* RespondWorkflowTaskCompletedRequest
* RespondWorkflowTaskFailedRequest
* RecordActivityTaskHeartbeatRequest
* RespondActivityTaskCanceledRequest
* RespondActivityTaskCompletedRequest
* RespondActivityTaskFailedRequest
**Why?**
Better compatibility
New tests
N/A
N/A
=> Set namespace on API if not present

service/worker/deletenamespace/reclaimresources/activities.go
Update `IsAdvancedVisibilityActivity` to include SQL DB that supports advanced visibility.
**Why?**
SQL DBs supporting advanced visibility supports `CountWorkflowExecutions`.
Probably none, not familiar with this code.
No.
=> Update IsAdvancedVisibilityActivity to include SQL DB

common/persistence/visibility/store/sql/query_converter.go, common/persistence/visibility/store/sql/query_converter_mysql.go, common/persistence/visibility/store/sql/query_converter_postgresql.go, common/persistence/visibility/store/sql/query_converter_sqlite.go
Wrap user's query string in parenthesis right after query converter is done parsing.
**Why?**
I had wrapped later in the plugin query converter, but I noticed that TemporalNamespaceDivision condition could be added before, and it could affect the user's query if not wrapped in parenthesis.
Writing query converter tests.
No risks.
No.
=> Fix wrap user query string in parenthesis

service/worker/deletenamespace/deleteexecutions/workflow.go, service/worker/deletenamespace/deleteexecutions/workflow_test.go
DeleteExecutions workflow: pass `nextPageToken` with `ContinueAsNewError`.
**Why?**
To prevent DeleteExecutions workflow to start from the begining with every "continue as new" iteration.
Modified existing test.
No risks.
No.
=> DeleteExecutions workflow: pass nextPageToken with ContinueAsNewError

common/persistence/visibility/defs.go, common/persistence/visibility/manager/visibility_manager.go, common/persistence/visibility/manager/visibility_manager_mock.go, common/persistence/visibility/visibility_manager_dual.go, common/persistence/visibility/visibility_manager_impl.go, common/persistence/visibility/visibility_manager_rate_limited.go, common/persistence/visibility/visiblity_manager_metrics.go, service/frontend/adminHandler.go, service/frontend/adminHandler_test.go, service/frontend/operator_handler.go, service/frontend/operator_handler_test.go, service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go, service/history/handler.go, service/history/historyEngine.go, service/worker/deletenamespace/reclaimresources/activities.go, service/worker/deletenamespace/reclaimresources/workflow.go, service/worker/deletenamespace/reclaimresources/workflow_test.go
Suport dual visibility in visibility persistence checks.
**Why?**
If dual visibility is enables, store name is not just a string but concatenated string. This PR changes it to the slice of stores and does a proper check.
No risks.
No.
=> Suport dual visibility in visibility persistence checks

service/frontend/service.go, service/worker/deletenamespace/deleteexecutions/activities.go, service/worker/deletenamespace/deleteexecutions/workflow.go, service/worker/deletenamespace/deleteexecutions/workflow_test.go, tests/namespace_delete_test.go
Delete workflow execution from visibility store even if it was deleted from main store.
**Why?**
`DeleteExecutions` workflow uses visibility store to list workflow executions to delete and if workflow execution was manually deleted from main store but not for visibility store, it gets stuck. With this change, in case of `NotFound` error, `DeleteExecutions` workflow will try to delete execution directly from visibility. If even this operation fails, workflow will exit with error and let caller (`ReclaimResources` workflow) to retry according to retry policy. 
Added functional test.
No risks.
No.
=> Delete workflow execution from visibility store even if it was deleted from main store

common/persistence/visibility/store/sql/query_converter.go
Pass pointer of slice element when calling `convertValueExpr` so it's converted in-place.
**Why?**
Query converter parses and changes expressions in-place, and all literal strings are expected to be converted to `unsafeSQLString`.
My previous PR https://github.com/temporalio/temporal/pull/3950 refactoring the code broke tuple parsing.
Writing unit tests.
No risks.
Yes.
=> Fix passing pointer of slice element in SQL query converter

service/history/queues/queue_base.go, service/history/queues/queue_base_test.go, service/history/queues/queue_immediate.go, service/history/queues/queue_scheduled.go, service/history/queues/queue_scheduled_test.go, service/history/queues/reader.go, service/history/queues/reader_test.go
- Only trigger scheduled queue lookahead when the default reader finishes loading. Currently, whenever read/write boundary is moved, a lookahead will be triggered.
**Why?**
- Lookahead when there're more tasks to load is unnecessary.
- If we want to pause a queue, we also don't want to lookahead to happen. Currently pause is achieved by setting pending task limit to 0, so reader won't load any task. However, the periodic 5m timer is still there for pushing the read/write boundary, so lookahead will still happen. With this change, those lookahead will also be gone.
Will test on test cluster
In worst case we may miss lookahead, and need to wait for the periodic poll timer to happen to load new tasks.
No.
=> Improve scheduled queue lookahead logic

common/membership/grpc_resolver.go, common/membership/hostinfo_provider.go, common/membership/rp.go, common/membership/rp_monitor.go, common/membership/rp_service_resolver.go, common/membership/rp_test_cluster.go
Made several unnecessarily-exported identifiers in the membership package unexported.
**Why?**
Information hiding.
The problems this change can cause should only happen at compile-time.
=> Make types not used outside of membership unexported

common/constants.go, common/persistence/tests/execution_mutable_state_task.go, service/frontend/adminHandler.go, service/history/queues/iterator.go, service/history/queues/iterator_test.go, service/history/queues/queue_base.go, service/history/queues/queue_base_test.go, service/history/queues/queue_immediate.go, service/history/queues/queue_scheduled.go, service/history/queues/queue_scheduled_test.go, service/history/queues/reader_test.go, service/history/queues/slice.go, service/history/queues/slice_test.go, service/history/replication/ack_manager.go, service/history/replication/ack_manager_test.go, service/history/replication/dlq_handler.go, service/history/replication/dlq_handler_test.go, tests/ndc/replication_integration_test.go
* Specify readerID on loading history tasks
**Why?**
* ReaderID is a hint for persistence implementation. See: https://github.com/temporalio/temporal/pull/3986
~~* The base of the PR contains https://github.com/temporalio/temporal/pull/3986 so that review is easier, will update base after that PR is landed.~~
* Unit test
* May cause additional loading when readerID changes on a iterator as buffered tasks inside the paging iterator will be discarded.
no
=> Specify readerID on loading history tasks

common/membership/config.go, common/membership/config_test.go, common/membership/ringpop/factory.go, common/membership/ringpop/factory_test.go, temporal/fx.go
The ValidateConfig method has moved from the ringpop package to the membership package.
**Why?**
The `temporal` package should not depend on RingPop. The ringpop.ValidateConfig method is used for all Membership configs, regardless of whether they are used in RingPop or not.
No semantic runtime changes here--the only error here could be from a compile-time dependency issue like a cycle.
=> Move RingPop config validation to membership package

service/history/workflow/mutable_state_impl.go, tests/xdc/integration_failover_test.go
Flush buffer event with single cluster namespace.
**Why?**
For namespace which update its cluster list from multi cluster to single cluster, it should still check buffer event and flush them if needed. This is the correct behavior of handling buffer events with different versions.
Updated integration test.
Yes.
=> Flush buffer event with single cluster namespace

common/persistence/cassandra/factory.go, common/persistence/cassandra/test.go, common/persistence/cassandra/version_checker.go, common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go, common/persistence/tests/cassandra_test_util.go, common/persistence/visibility/store/standard/cassandra/visibility_store.go, tools/cassandra/cqlclient.go
…method
Change commongocql.NewSession interface to allow user to pass in custom gocql.ClusterConfig.
**Why?**
Allows extension.
=> Refactor gocql.NewSession to allow passing in cluster config factory method

common/membership/interfaces.go, common/membership/ringpop/monitor_test.go, service/history/shard/controller_impl.go
I removed the HostsUpdated field from the ChangedEvent.
**Why?**
This field isn't used. It simplifies future Monitor implementations.
=> Remove unused HostsUpdated field from ChangedEvent

service/history/api/updateworkflow/api.go, service/history/workflow/cache/cache_test.go, service/history/workflow/context.go, service/history/workflow/context_mock.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/update/registry.go, service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go, tests/update_workflow_test.go
Move update registry from mutable state to workflow context.
**Why?**
When workflow task is failed, mutable state is cleared and refreshed. This also clears update registry which might have updates not related to failed workflow task.
This PR moves updated registry one level above -- to workflow context. This allows mutable state to be cleared w/o clearing update registry. 
Modified integration test.
No risks.
No.
=> Move update registry from mutable state to workflow context

common/persistence/visibility/store/sql/visibility_store.go
Convert `query.ConverterError` to `serviceerror.InvalidArgument`.
**Why?**
Query converter error should be non-retryable as it's from an user input.
Converting the error to `serviceerror.InvalidArgument` does the trick.
Started local server, and tried submitting List request through temporal CLI with invalid query, and now it returns the error message from query converter instead of `context deadline exceeded` message.
No risks.
No.
=> Convert query converter error to invalid argument

common/persistence/dataInterfaces.go, common/persistence/persistence-tests/persistenceTestBase.go, common/persistence/persistenceInterface.go, common/persistence/shard_manager.go, common/persistence/tests/execution_mutable_state_task.go, service/history/queues/queue_base.go, service/history/queues/queue_base_test.go, service/history/queues/queue_scheduled_test.go, service/history/queues/reader_group.go, service/history/queues/reader_group_test.go, service/history/replication/ack_manager.go, service/history/replication/ack_manager_test.go, service/history/replication/task_processor_manager.go, service/history/replication/task_processor_manager_test.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/shard/context_testutil.go, service/history/shard/controller_test.go
- Make shard info owner unique for each shard context object
- UpdateShard can also use this unique owner value to tell if it's a new shard context object
- Use shard owner in history task reader related api
**Why?**
- Persistence may need this information to tell which shard context object is issuing the request.
- Existing owner only contains host identity, which is not enough since shard context stop is async so it's possible that there're two or more shard contexts with the same shardID running on one host.
- Existing unit test
- Very low risk. No implementation is actually looking at the shard info owner field and it's only for information only right now.
- No.
=> Unique owner for each shard context object

service/history/workflowTaskHandler.go, tests/client_integration_test.go
Fix applies to this specific sequence of commands:
- `RequestCancelActivityTask`
- `CancelTimer`
- `CompleteWorkflowExecution`
Closes #4049
=> Fix UnhandledCommand error for workflow task completion in CancelTimer

service/history/api/describeworkflow/api.go, service/history/api/get_workflow_util.go, service/history/api/queryworkflow/api.go, service/history/api/reapplyevents/api.go, service/history/api/startworkflow/api.go, service/history/historyEngine_test.go, service/history/ndc/branch_manager.go, service/history/ndc/branch_manager_test.go, service/history/ndc/transaction_manager.go, service/history/ndc/transaction_manager_test.go, service/history/ndc/workflow.go, service/history/ndc/workflow_resetter.go, service/history/ndc/workflow_resetter_test.go, service/history/ndc/workflow_test.go, service/history/timerQueueActiveTaskExecutor.go, service/history/timerQueueActiveTaskExecutor_test.go, service/history/timerQueueStandbyTaskExecutor.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/task_generator.go, service/history/workflow/task_refresher.go, service/history/workflow/util.go, service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go, tests/max_buffered_event_test.go
Made few renames for better code readability:
1. `GetInFlightWorkflowTask` -> `GetStartedWorkflowTask` (same for `Has*`),
2. `GetWorkflowTaskInfo` -> `GetWorkflowTaskByID`,
3. `HasProcessedOrPendingWorkflowTask` -> `HadOrHasWorkflowTask`,
4. `GetPreviousStartedEventID` -> `GetLastWorkflowTaskStartedEventID`
**Why?**
Better readability.
No risks.
No.
=> Rename inflight WT to started WT

common/persistence/visibility/factory.go, common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go, service/frontend/service.go, service/history/configs/config.go, service/worker/service.go
Change dynamic config `system.visibilityDisableOrderByClause` to be per namespace.
**Why?**
Add more flexibility to disable `ORDER BY` per namespace.
No risks.
No.
=> Change disable order by dynamic config to per namespace

service/frontend/workflow_handler.go, service/worker/scheduler/spec.go, tests/schedule_test.go
Set end and step to default values in calendar specs returned through frontend api.
**Why?**
We do a little optimization to save space in memo for calendar specs, but it's confusing to return this through the api, so we should undo it at the frontend.
Changed integration test.
=> Set default values in returned calendar specs

common/metrics/metric_defs.go, common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Add counter to track custom order by usage in Elasticsearch.
**Why?**
No risks.
No.
=> Add counter to track custom order by usage in Elasticsearch

temporal/fx.go
Set cluster metadata version when saving custom search attributes when using SQL DB.
**Why?**
This fixes adding pre-allocated custom search attributes to SQL DB when migrating to Temporal Server 1.20
- Started Temporal Server 1.19, and added some search attributes.
- Started Temporal Server 1.20, and checked logs (successfully added pre-allocated custom search attributes), and was able to add search attributes through Temporal CLI. 
No risks.
Yes.
=> Fixing saving custom search attribute after upgrading SQL DB

common/persistence/visibility/store/sql/pagination_token_test.go
Check the page token is empty or not, instead of only checking if it's nil.
**Why?**
Bug (https://github.com/temporalio/temporal/issues/4053) reported showed that the page token can be an empty slice.
Added new unit tests, and checked the reported issue no longer happens.
No risks.
No.
=> Fix SQL visibility page token deserializer

service/worker/scheduler/activities.go, service/worker/scheduler/workflow.go
Add explicit context deadlines to local activities used by schedule workflow.
**Why?**
SDK doesn't currently apply StartToClose timeout properly (https://github.com/temporalio/sdk-go/issues/1066)
existing tests, manual testing of local activities with timeouts
yes
=> Add deadlines to schedule local activities

common/headers/caller_info.go, service/history/queues/executable.go, service/history/queues/executable_test.go
* Use preemptable caller type for low priority history tasks
**Why?**
* https://github.com/temporalio/temporal/issues/3874
* Does the task processing part of ^, still need to adjust the caller type used for queue readers (currently always background caller type). But the load from queue reader is much lower compared to processing.
* Preemptable caller type has the lowest priority when consuming persistence rate limiting token, so when system is under heavy load, those priority tasks will be rejected first.
* Unit test
=> Use preemptable caller type for low priority history tasks

service/history/api/startworkflow/api.go, service/history/workflow/cache/cache.go, service/history/workflow/cache/cache_mock.go, service/history/workflow/cache/cache_test.go
- Lock current workflow execution on StartWorkflowExecution
- Basically revert https://github.com/temporalio/temporal/pull/2872
**Why?**
- Block on workflow lock instead of shard lock -> prevent noisy neighbor issue
- Workflow lock latency will be subtracted when calculating service no-user latency -> reduce noisy alerts. 
- Add unit test
- Will try locally to see the metrics
- Yes.
=> Lock current execution on start workflow

common/membership/interfaces.go, common/membership/interfaces_mock.go, common/membership/ringpop/monitor.go, common/membership/ringpop/monitor_test.go, service/frontend/workflow_handler_test.go, tests/simpleMonitor.go
I removed the listener methods and get member count methods from the Monitor interface and the RingPop implementation.
**Why?**
They're not used (except once in a test).
=> Remove unused methods from Monitor interface

common/membership/interfaces.go, common/membership/interfaces_mock.go, common/membership/ringpop/monitor.go, common/membership/ringpop/monitor_test.go, service/frontend/adminHandler.go, service/frontend/workflow_handler_test.go, tests/simpleMonitor.go
I removed the Lookup method from the Monitor interface and its implementations.
**Why?**
It's redundant because you can just use GetResolver.
=> Remove Lookup method from Monitor interface

go.mod, go.sum, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go
- Handle max signal count limit for signal transfer task
- API change: https://github.com/temporalio/api/pull/265
**Why?**
- Limit total signal count per workflow
- Added unit test. Tested locally.
- Yes.
=> Handle max signal count limit for signal transfer task

service/history/shard/context_impl.go, service/history/shard/context_test.go
- Do not notify replication queue if max replication taskID is pending (maxInt64)
- This is only a problem when there're concurrent namespace migrations (one in handover, one in catch up stage) and when a shard seeing a namespace in handover state for the first time is also in an invalid state. 
- When is happens, there's a (small) chance the migration in wait catch up state will get stuck, because it thinks the replication taskID is maxInt64. This is not user impact. We just need to re-run the migration workflow.
**Why?**
- Bug fix
- Added unit test & existing integration test for migration
yes
=> Fix namespace handover replication queue notification

service/history/workflowTaskHandlerCallbacks.go, tests/onebox.go, tests/sizelimit_test.go, tests/testdata/integration_sizelimit_cluster.yaml, tests/testdata/integration_test_cluster.yaml
Flush buffer event when failing workflow task
**Why?**
When workflow task failed due to payload/search attribute size too large, it should flush buffer events before fail the workflow.
=> Flush buffer event when failing workflow task

common/archiver/filestore/queryParser.go, common/archiver/filestore/visibilityArchiver_test.go, common/archiver/gcloud/visibilityArchiver.go, common/archiver/gcloud/visibilityArchiver_test.go, common/archiver/s3store/util.go, common/archiver/s3store/util_test.go, common/archiver/s3store/visibilityArchiver.go, common/archiver/s3store/visibilityArchiver_test.go, common/archiver/util.go
We now allow empty queries to the s3 visibility archival backend. 
**Why?**
https://github.com/temporalio/ui/issues/572
I added unit tests for all of the different branches introduced. I also ran a manual end-to-end test verifying that this works for some locally archived workflows against my local stack instance. I verified that pagination works too: 
It's fixing a page that is currently broken, so it can't do much more harm.
=> Support empty queries when listing archived workflows

common/membership/interfaces.go, common/membership/interfaces_mock.go, common/membership/ringpop/factory.go, common/membership/ringpop/fx.go, common/membership/ringpop/monitor.go, common/membership/ringpop/test_cluster.go, service/worker/service.go
**Why?**
The Start and Stop methods of the Monitor shouldn't be required because it should be up to implementors how a monitor is started and stopped. Currently, our RingPop monitor already does this by using fx, so we don't even want users of the package to call Start and Stop in an adhoc manner.
I stepped through with a debugger and verified that the call to Start in the worker service was a no-op because start is already called as part of the fx lifecycle. I could not verify the Stop logic because I don't think Stop is even called when we shut down the server.
=> Remove common.Daemon from Monitor interface

common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go, common/persistence/visibility/store/query/converter.go
Better error message in ES query converter.
**Why?**
https://github.com/temporalio/temporal/issues/3494
```
$ tctl workflow list --query "ExecutionStatus = Running"
Error: Failed to list workflow.
Error Details: invalid query: unable to convert filter expression: unable to convert right side of "ExecutionStatus = Running": operation is not supported: column name on the right side of comparison expression (did you forget to quote "Running"?)
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
```
No risks.
No.
=> Better error message in ES query converter

service/history/workflowTaskHandlerCallbacks.go, service/matching/matchingEngine.go, tests/client_integration_test.go
Server would sent down full history when polling from original queue.
**Why?**
To avoid send workflow task with partial history if it is polling from original task queue.
New integration test
No
No
=> Auto clear stickiness

common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go
Add a few more errors to gocql session refresh logic
**Why?**
There are more than one error for Cassandra connection issue.
eye_balls
No
No
=> Reconnect on a few more gocql errors

common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Changed ElasticSearch Scan API to have no order (use "_doc"). 
**Why?**
Using sort order "\_doc" when using Scan API has some optimizations in ES that
makes it faster to iterate over all workflows. 
N/A
No
=> Change Scan API to have no Order(ES)

service/frontend/adminHandler.go, service/frontend/operator_handler.go
Fix error handling when adding search attributes.
**Why?**
Users cannot added search attributes because it's not checking nil value.
https://github.com/temporalio/temporal/issues/4145
Started server and added search attributes.
No.
Yes.
=> Fix error handling add search attributes

internal/nettest/package.go, internal/nettest/pipe.go, internal/nettest/pipe_benchmark_test.go, internal/nettest/pipe_test.go
I added a `PipeListener` utility that will make it easier to run tests involving net.Dialer (which is a lot of our tests). I plan to use this in tests for the `membership` package.
**Why?**
To make writing net code tests easier, faster and safer.
This package has 100% test coverage including goleak testing. In addition, net.Pipe is already commonly used for this purpose. I just couldn't find a good library that already does this, and does it properly.
=> Add a hermetic PipeListener for testing net code

service/worker/scheduler/workflow.go, service/worker/scheduler/workflow_test.go
Previously the workflow assumed that it would wake up at scheduled times while paused, but #3670 changed that, so now it might register "missed catchup window" when woken up after a pause. This fixes it to check paused first.
unit test
This is technically not a deterministic change, but it only affects logging, metrics, and fields in the schedule Info, which are not used by the logic itself, only returned by a query, so it should be safe.
=> Fix schedule catchup window metric calculation while paused

go.mod, go.sum
Update Go SDK to v1.22.1
Had to create a point release to patch some replay issues with Update, so not strictly relevant to the sever code base at this time.
=> Update Go SDK to v1.22.1

common/persistence/cassandra/history_store.go, common/persistence/client/fault_injection.go, common/persistence/dataInterfaces.go, common/persistence/execution_manager.go, common/persistence/history_manager.go, common/persistence/mock/store_mock.go, common/persistence/persistence-tests/historyV2PersistenceTest.go, common/persistence/persistenceInterface.go, common/persistence/sql/history_store.go, tests/archival_test.go
=> Split history tree insert from history node append

service/matching/version_sets.go
https://github.com/temporalio/api/pull/272
=> Remove version_set_id from CompatibleVersionSet

common/metrics/opentelemetry_provider.go
Doesn't seem like this field is actually used while `meter`, `config`, and `server` are:
https://github.com/temporalio/temporal/blob/cdd1a218f83aac371d15fa4ebe5739cf71e623cc/common/metrics/opentelemetry_provider.go#L126-L136
=> Remove unused exporter from openTelemetryProviderImpl

common/util.go, common/util_test.go, service/history/replication/poller_manager.go
* Add util to map shard IDs & UT
**Why?**
More utils
UT
N/A
N/A
=> Add util to map shard IDs

common/persistence/visibility/store/sql/query_converter.go, common/persistence/visibility/store/sql/query_converter_mysql.go, common/persistence/visibility/store/sql/query_converter_postgresql.go, common/persistence/visibility/store/sql/query_converter_sqlite.go, common/persistence/visibility/store/sql/visibility_store.go
Enabled Scan API in SQL visibility store. The Scan API does not support 'ORDER
BY' clause otherwise behaves the same as List API.
**Why?**
local test
No risks
NO
=> Enable Scan API in SQL visibility store

service/history/deletemanager/delete_manager.go, service/history/deletemanager/delete_manager_test.go, service/history/historyEngine.go, service/history/timerQueueFactory.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueFactory.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor_test.go, service/history/transferQueueTaskExecutorBase.go
Add visibility manager dependency to delete manager.
**Why?**
The goal is to remove `DefaultVisibilityIndexName` from history config, and get the index name from the visibility manager.
Unit test.
No risks.
No.
=> Add visibility manager dependency to delete manager

service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueTaskExecutorBase.go
* Use GetQueueAckLevel for transfer queue, since GetQueueClusterAckLevel should only be used by replication tasks
**Why?**
See above
N/A
N/A
N/A
=> Use correct API for transfer queue

service/matching/taskReader.go
Don't log if the error was ownership lost.
**Why?**
These "errors" are expected during task queue movement and misleading.
it's just a log
=> Don't log error for ownership lost in matching task reader

service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go, service/history/workflow/mutable_state_rebuilder.go, service/history/workflow/mutable_state_rebuilder_test.go, service/history/workflow/task_generator.go, service/history/workflow/task_generator_mock.go, service/history/workflow/task_refresher.go, service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go, tests/update_workflow_test.go
Convert speculative workflow task to normal when it is persisted.
**Why?**
Speculative workflow task is in-memory only. If new events come during speculative workflow task execution, they get buffered, and mutable state is persisted to database together with speculative workflow task. This shouldn't happen because when speculative workflow task is completed it gets cleared from memory only but not from database. Therefore, speculative workflow task needs to be converted to normal before it gets persisted.
Added unit and functional tests.
No risks.
No.
=> Convert speculative workflow task to normal when it is persisted

common/backoff/cron.go, common/backoff/cron_test.go
Fix cron for schedules that do not match any time
**Why?**
Some invalid cron spec would pass the cron library's parse validation, but they don't match to any time.
New unit test, and manual test:
```
$ tctl wf start --tq fake-tq --wt fake-wt --wtt 10 --cron "* * 31 2 *"
Error: Failed to create workflow.
Error Details: invalid CronSchedule, no time can be found to satisfy the schedule
```
No
Yes
=> Fix cron for schedules that do not match any time

common/persistence/visibility/store/sql/query_converter.go, common/persistence/visibility/store/sql/query_converter_mysql.go, common/persistence/visibility/store/sql/query_converter_postgresql.go, common/persistence/visibility/store/sql/query_converter_sqlite.go, common/persistence/visibility/store/sql/visibility_store.go
Reverts temporalio/temporal#4161
The Scan API with SQL DB should be the same as the List API as it needs a order to be able to paginate.
=> Revert "Enable Scan API in SQL visibility store"

common/clock/hybrid_logical_clock/hybrid_logical_clock.go, common/clock/hybrid_logical_clock/hybrid_logical_clock_test.go, service/matching/matchingEngine.go, service/matching/matchingEngine_test.go, service/matching/version_sets.go, service/matching/version_sets_merge.go, service/matching/version_sets_merge_test.go, service/matching/version_sets_test.go
Another PR for version set / user data replication.
=> Versioning data merge algo and hybrid logical clock utils

common/dynamicconfig/constants.go, service/frontend/errors.go, service/frontend/service.go, service/frontend/workflow_handler.go, tests/versioning_test.go
The feature is not ready yet and once it is, we'll still need a safe way to roll it out, hence this feature flag.
=> Add dynamic config flag to disable worker versioning

client/history/metadata.go, client/history/metadata_test.go, service/history/api/replication/stream.go, service/history/api/replication/stream_test.go, service/history/handler.go, service/history/replication/grpc_stream_client.go, service/history/replication/stream_receiver.go, service/history/replication/stream_receiver_monitor.go, service/history/replication/stream_receiver_monitor_test.go, service/history/replication/stream_receiver_test.go
* Rename source cluster key to client cluster key
* Rename target cluster key to server cluster key
**Why?**
Before this PR:
source cluster key means the source of the stream, but this usually means the target of replication data flow;
target cluster key means the target of the stream, but this usually means the source of replication data flow;
the meaning can be misleading
N/A
N/A
N/A
=> Rename some var names in replication stream logic

tools/cassandra/handler.go, tools/cassandra/handler_test.go, tools/cassandra/main.go
Fixed some checks to return an error instead of always returning a `nil`.
**Why?**
Bigfix
Unittest
That was made intentionally.
Revert
=> [WIP] Fix error return bug and some minor code style

service/frontend/errors.go, service/frontend/workflow_handler.go, service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go, service/matching/version_sets.go
- Copy build id to binary checksum when present
- Respect `use_versioning` for RespondWFTCompleted
- Enforce continuing to provide build id
- Remove some unused code
**Why?**
Implement more of the feature
Will be tested with overall feature tests
=> Copy build id to binary checksum when present

api/persistence/v1/executions.pb.go, common/cluster/metadata.go, common/persistence/serialization/blob.go, common/util.go, common/util_test.go, config/development-cluster-b.yaml, proto/internal/temporal/server/api/persistence/v1/executions.proto, service/history/api/replication/get_tasks.go, service/history/api/replication/stream.go, service/history/api/replication/stream_test.go, service/history/queues/mitigator.go, service/history/queues/queue_base.go, service/history/queues/queue_base_test.go, service/history/replication/stream_receiver_monitor_test.go, service/history/replication/task_processor_manager.go, service/history/replication/task_processor_manager_test.go, service/history/shard/compatibility.go, service/history/shard/compatibility_test.go, service/history/shard/context.go, service/history/shard/context_impl.go, service/history/shard/context_mock.go, service/history/shard/context_test.go, service/history/shard/context_testutil.go, service/history/shard/context_util.go, service/history/shard/context_util_test.go, service/history/shard/controller_test.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueTaskExecutorBase.go, service/history/visibilityQueueTaskExecutor.go, service/history/visibilityQueueTaskExecutor_test.go
* Mostly deprecate queue ack level in favor of queue state
* Additional compatibility logic for forward / backward compatibility
* Use queue state for replication acks
* Allow replication streams between clusters with different shard count
**Why?**
N/A
N/A
N/A
N/A
=> Attempt to unify queue state

common/authorization/claim_mapper.go, common/authorization/claim_mapper_mock.go, common/authorization/interceptor.go, common/authorization/interceptor_test.go
The no-op claim mapper doesn't require auth info (TLS or authorization header) and should be invoked all the time.
**Why?**
To be able to use internal-frontend without TLS.
unit test
=> Run no-op claim mapper even without auth info

common/authorization/default_jwt_claim_mapper.go, common/authorization/default_jwt_claim_mapper_test.go
Change defaultJWTClaimMapper treat namespace as case sensitive.
Change system namespace from `system` to `temporal-system` and make it case sensitive.
**Why?**
Namespace in temporal is case sensitive.
Unit test
If the JWT generator produce token using case insensitive namespace name, that will not work with this change.
No
=> defaultJWTClaimMapper treat namespace as case sensitive

temporal/fx.go, temporal/server.go
Previously there were two 60s timeouts when shutting down (one for fx and another separately waiting for the grpc services to stop). Now there's one 5 minute timeout.
**Why?**
We might want to set drain durations longer than one or two minutes. Fixes #4192.
Manually for now
=> Increase shutdown timeout to 5 minutes

temporal/fx.go, temporal/server_impl.go
Remove unused `dynamicconfig.Collection` in top level fx container
**Why?**
We only need a `dynamicconfig.Client` at the top level, the individual services each construct a `Collection`
integration tests
=> Remove unused dynamicconfig.Collection in top level fx container

temporal/fx.go, temporal/server_impl.go, temporal/server_option.go, temporal/server_options.go
- Move blocking start outside of fx lifecycle hook
- Propagate outer app Start/Stop context to inner Apps (currently just Background)
- Refactor StopService into proper method
- Other small cleanups
This leaves the shutdown timeout in the inner Apps: if we set a single timeout on the outer one, fx itself might abort shutdown and not give the inner ones time to finish, so I think it's more robust this way.
**Why?**
Simplify and correct usage of fx
Local testing, integration tests
=> Refactor fx Start/Stop usage

common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Change ES Scan API to not use PIT nor Scroll.
**Why?**
Remove PIT and Scroll completely: Elasticsearch PIT and scroll consumes lots resources, and can potentially slow down the cluster.
No.
No.
=> Remove usages of ES PIT and Scroll

api/matchingservice/v1/service.pb.go, common/metrics/tags.go, proto/internal/temporal/server/api/matchingservice/v1/service.proto, service/matching/taskQueueManager.go, service/matching/version_sets.go, service/matching/version_sets_merge.go, service/matching/version_sets_merge_test.go, service/matching/version_sets_test.go, service/worker/replicator/namespace_replication_message_processor.go
Rename imports: public protobuf packages end in `pb`, server protobuf packages end in `spb` (s for server)
**Why?**
consistency
=> Rename imports to match convention

service/history/queues/executable.go, service/history/queues/executable_test.go
-  Reset task attempt to 1 instead of 0
**Why?**
- Attempt count should always start from 1, which is more natural.
- added new unit test
yes
=> Fix task attempt reset

service/history/api/workflow_context.go, service/history/workflow/context.go, service/history/workflow/update/registry.go, service/history/workflow/update/registry_test.go
Introduce update.Storage
**Why?**
A slice of the MutableState API that the update.Registry can use for writing events and loading in-flight update information into memory. This is part of a larger refactor to the update package to encapsulate more behavior and be able to restore state from the event index kept in MutableState
No behavioral changes.
No
=> Introduce update.Storage

common/dynamicconfig/collection.go, common/dynamicconfig/collection_test.go, common/dynamicconfig/config/testConfig.yaml, common/dynamicconfig/file_based_client_test.go, common/primitives/timestamp/parseDuration.go, common/primitives/timestamp/parseDuration_test.go
If dynamic config is expecting a duration and gets a plain integer, interpret it as seconds instead of falling back to the default. For consistency, interpret strings that have a unit-less integer as seconds also.
**Why?**
Less surprising behavior for users. It's easy to leave out the "s" by accident when configuring a duration.
Unit tests and manual test.
Could change the behavior of currently-broken dynamic config files.
=> Allow plain int seconds for duration in dynamic config

service/history/shard/context_impl.go
* Do timeout check after shard lock acquired, not before
**Why?**
When shard lock contention occurs, caller coroutine can wait a long time before acquiring shard lock, consequent IO operation may not have enough timeout left.
N/A
N/A
Yes
=> Make shard ownership more resilient when shard is busy

service/history/workflow/workflow_test/mutable_state_impl_test.go
I added a unit test which verifies that we fail WFTs with event buffers that are too large.
**Why?**
To make it easier to add the event buffer byte size check to the CloseTransactionAsMutation.
I verify that the WFT attempt was incremented and the WFT-failed event in the history exists and looks correct.
Just a test.
No
=> Verify WFTs with large event buffers fail

common/dynamicconfig/collection.go
- Log the first 1000 errors and 1/1000 after, instead of 1/1000
- Log type conversion errors at Warn level instead of Debug
**Why?**
Make type errors in dynamic config more visible
Manually, there's no unit test for what gets logged
More log spam in debug level, but warn level should get more useful logs
=> Expose better logs for dynamic config conversion errors

service/worker/scanner/history/scavenger.go
Handle namespace not found in history scan
**Why?**
There is race condition:
1. Orphan history in history table.
2. The namespace is deleted.
When the history scanner hit a namespace is deleted, currently it just failed. The correct behavior is to ignore the namespace not found error and delete orphan history as the namespace is deleted.
=> Handle namespace not found in history scan

service/matching/taskQueueManager.go, service/matching/taskQueueManager_test.go, service/matching/taskReader.go, service/matching/taskWriter.go
- Replace signalFatalProblem with a real method unloadFromEngine
- Remove some unused code
**Why?**
Using a real method is easier to follow
existing tests
=> Small refactor to matching signalFatalProblem

schema/mysql/v57/temporal/versioned/v1.10/update_info_maps_table.sql, schema/mysql/v57/version.go, schema/mysql/v8/temporal/versioned/v1.10/update_info_maps_table.sql, schema/mysql/v8/version.go
Correct spelling of column name updat_id -> update_id
**Why?**
That's not how you spell it.
Ran `make install-schema-mysql` and `desc update_info_maps` to verify column name
FYI this these two lines are the only to instances of the string "updat_id" in the server repo.
We haven't released the server with this bug so I _think_ it's ok to modify the versioned sql in place. If not I can create v1.10.1
No
=> Correct spelling: updat_id -> update_id

common/dynamicconfig/constants.go, common/metrics/metric_defs.go, service/history/configs/config.go, service/history/workflow/history_builder.go, service/history/workflow/history_builder_test.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go, service/history/workflow/workflow_test/mutable_state_impl_test.go
Add a limit on the total size of the history events buffer. Here, size means the sum of the number of bytes of each HistoryEvent proto in the batch, as determined by protobuf.
**Why?**
Because we don't want to have huge mutable state objects.
I added test cases which verify that we force-flush and restart WFTs when this limit is exceeded.
There are risks that this will break users that somehow had huge event buffers, but that behavior would already degrade performance anyway.
I think we should definitely include a message about this new limit in the patch notes.
=> Event buffer size limit

service/history/archival/archiver.go, service/history/archival/archiver_test.go
We now populate search attributes with type information before archiving them.
**Why?**
This information is not always embedded in the fields themselves, e.g., for schedules. This fixes #4270 .
I reproduced the linked issue without this change, and then verified that it worked after this change. I repro'd by doing this:
1. Check out 1.20.2
2. Start a server pointing at pg12 and s3
3. Archive a scheduled workflow
4. Observe that an `invalid search attribute type: Unspecified` error is thrown before this change.
Unclear.
The community should be notified that this bug existed, and that they should upgrade to fix it.
=> Use search attribute type map in visibility archival

common/dynamicconfig/constants.go, go.mod, go.sum, service/matching/config.go, service/matching/liveness.go, service/matching/liveness_test.go, service/matching/taskQueueManager.go, service/matching/taskQueueManager_test.go
Change implementation of task queue liveness to use a timer instead of a goroutine
**Why?**
Simpler implementation, more accurate idle timeout
unit test
=> Simplify task queue liveness

cmd/server/main.go, go.mod, go.sum
This will automate the setting of `GOMAXPROCS` in Kubernetes/docker environments where it is not already set as part of the deployment.
`automaxprocs` library was added to set `GOMAXPROCS` to match the CPU limits set on a container. This is a no-op if `GOMAXPROCS` environment variable is already set, or if not running in a container.
**Why?**
Setting `GOMAXPROCS` to match resource limits (rather than the total core count of the node) allows Go to more efficiently use the available cores and reduces CPU throttling (eliminating it entirely if limits are set to an integer number of cores).
This issue was highlighted during benchmarking but probably effects a large number of real world Kubernetes deployments where CPU limits are set but `GOMAXPROCS` is not.
**How did you …
=> Add automaxprocs.

common/metrics/metric_defs.go, internal/effect/buffer.go, internal/effect/buffer_test.go, internal/effect/controller.go, internal/effect/immediate.go, internal/effect/immediate_test.go, service/history/api/updateworkflow/api.go, service/history/api/workflow_context.go, service/history/commandChecker.go, service/history/queues/memory_scheduled_queue_test.go, service/history/workflow/context.go, service/history/workflow/context_mock.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/update/export_test.go, service/history/workflow/update/registry.go, service/history/workflow/update/registry_test.go, service/history/workflow/update/state.go, service/history/workflow/update/update.go, service/history/workflow/update/update_test.go, service/history/workflow/update/util.go, service/history/workflow/update/validation.go, service/history/workflow/update/version.go, service/history/workflow/util.go, service/history/workflowTaskHandler.go, service/history/workflowTaskHandlerCallbacks.go, tests/update_workflow_test.go
- Write update.Update as a protocol state machine that encapsulates all message processing, validation, event writing, and metric emission related to an update.
- Make explicit the set of "Provisional" state transitions wherein the Update has recieved and reacted to a protocol message but cannot make externally observable changes like returning update outcomes to RPC callers until it knows that changes have been written to stable storage.
- The effect package is introduced as a utility to buffer and later apply or cancel a set of effects.
- With more responsibility in the Update type, UpdateRegistry is simplified.
- UpdateRegistry can restore its state (mainly in-flight Accepted updates) from MutableState.
- Update message validation is moved into the update package.
- …
=> Refactor the Update type to a state machine

common/searchattribute/test_provider.go, service/frontend/adminHandler.go, service/frontend/operator_handler.go, service/frontend/operator_handler_test.go
Fix adding multiple search attributes of same type at once.
Synched `AdminHandler`'s code to add search attributes.
Added unit tests to operator handler.
**Why?**
https://github.com/temporalio/temporal/issues/4160
When adding multiple search attributes of same type, it's missing a check to not use new mappings when trying to map a new search attribute. Eg: initially it maps `Key1` to `Field1` and then `Key2` to `Field1` again because it didn't check that `Field1` is unavailable after `Key1` was mapped.
Added multiple search attributes with same type using Temporal CLI and `tctl`.
No.
No.
=> Fix adding multiple search attributes of same type at once

service/frontend/service.go, service/history/configs/config.go, service/worker/service.go, tests/advanced_visibility_test.go
Change default value of dynamic config to disable `ORDER BY` clause to true.
**Why?**
We want to disable it by default as it's a potential performance bottleneck.
Existing calls using `ORDER BY` will return an error.
No.
=> Default disable order by clause support

service/history/workflow/update/update.go, service/history/workflow/update/update_test.go
Make better use of available data in the internals of WaitAccepted
**Why?**
Increase the number of cases in which we can return a full update outcome from WaitAccepted. Specifically, if the update is rejected then we can create an Outcome from the provided Failure.
New unit test here
low
No.
=> Improve Update.WaitAccepted

common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Manually build pagination query in ES when using default sorter.
**Why?**
In cases of deep pagination, manually building the pagination query works faster than using `search_after`.
No.
No.
=> Manually build ES pagination query for default sorter

service/history/api/pollupdate/api.go, service/history/api/pollupdate/api_test.go, service/history/api/updateworkflow/api.go, service/history/historyEngine.go, service/history/workflow/update/registry.go, service/history/workflow/update/registry_test.go, service/history/workflow/update/update.go, service/history/workflow/update/update_test.go, service/history/workflow/update/util.go
Enable async updates and implement the PollWorkflowExecutionUpdate API
**Why?**
Features are dope
New unit tests here, async update feature test in the features repo (not in main yet - waiting for this PR to land)
low but I will add a feature flag around async update requests in a subsequent PR
No
=> Async Updates and the Poll API

service/history/workflow/update/registry.go, service/history/workflow/update/registry_test.go, service/history/workflow/update/update.go, service/history/workflowTaskHandler.go, tests/update_workflow_test.go
Prevent a workflow from closing if there are workflow updates that have been admitted into the registry but which have not yet been seen by the workflow execution. Previous behavior was to prevent workflow close for any _incomplete_ updates.
**Why?**
Consensus that this is the desired behavior. If a workflow execution has seen the update, it has also had the opportunity to prevent itself from completing. If the workflow has not taken action to prevent completion when it had the chance then the server should assume that was intentional.
Unit and functional tests changed to expect new behavior
low
no
=> Prevent workflow close when updates are undelivered

common/dynamicconfig/constants.go, common/persistence/tests/visibility_persistence_suite_test.go, common/persistence/visibility/factory.go, common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go, service/frontend/fx.go, service/frontend/service.go, service/history/configs/config.go, service/history/fx.go, service/worker/fx.go, service/worker/service.go
Added a dynamic config to enable/disable manual pagination for Elasticsearch.
**Why?**
PR https://github.com/temporalio/temporal/pull/4271 enabled manual pagination for Elasticsearch by default. Adding a dynamic config to control it just in case something bad happens.
No.
No.
=> Create dynamic config to enable manual pagination for Elasticsearch

service/history/nDCStandbyTaskUtil.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/transferQueueStandbyTaskExecutor.go
Remove unneeded duration/seconds conversion.
**Why?**
Leftover from Cadence times.
No risks.
No.
=> Remove unneeded duration/seconds conversion

common/persistence/cassandra/metadata_store.go
This reverts commit 3cbab42bc9922d7fb01295f29ca77fe44f1b318a.
^
**Why?**
It was causing failures after running `make start`
I ran `git bisect` and it said this:
```
3cbab42bc9922d7fb01295f29ca77fe44f1b318a is the first bad commit
commit 3cbab42bc9922d7fb01295f29ca77fe44f1b318a
```
None
No
=> Revert "Fix partial namespace creation (#4267)"

service/history/api/get_workflow_util.go, service/history/api/resetstickytaskqueue/api.go, service/history/api/updateworkflow/api.go, service/history/transferQueueActiveTaskExecutor.go, service/history/transferQueueStandbyTaskExecutor.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/mutable_state_rebuilder.go, service/history/workflow/mutable_state_rebuilder_test.go, service/history/workflow/task_generator.go, service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go
Refactor task queue related methods of mutable state:
1. Renamed
- `ClearStickyness()` -> `ClearStickyTaskQueue()`,
- `IsStickyTaskQueueEnabled()` -> `IsStickyTaskQueueSet()`,
- `TaskQueue()` -> `CurrentTaskQueue()`.
2. Added:
- `SetStickyTaskQueue()`,
- `TaskQueueScheduleToStartTimeout()`.
Improved comments.
**Why?**
To concolidate logic related to timeout calulation.
Cleaner contract between mutable state and its consumers.
No risks.
No.
=> Refactor task queue related methods of mutable state

service/history/api/pollupdate/api_test.go, service/history/workflow/update/export_test.go, service/history/workflow/update/registry.go, service/history/workflow/update/state.go, service/history/workflow/update/update.go, service/history/workflow/update/update_test.go
- comments and spelling
- make Update onComplete callback optional and unexported
- improve unit test context cancellation cleanup
- remove atomic read/write for update.state type
**Why?**
I had made state reads and writes threadsafe back when it was observed from multiple threads but that has evolved to no longer be the case.
No behavioral changes so current unit tests suffice
low
No
=> Handful of minor changes to the update package

service/worker/scheduler/workflow.go, tests/schedule_test.go
Change default catchup window to 1 year (will only affect newly created schedules)
**Why?**
Better match user expectations: we shouldn't skip runs for short slowness/unavailability, other parts of temporal always attempt to catch up
=> Change schedules default catchup window to 1 year

common/dynamicconfig/constants.go, common/log/tag/tags.go, service/history/configs/config.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go
- Truncate activity failure before storing it in mutable state
- Introduced new warn & error limit for mutable state activity failure size
NOTE: this change should not break users (unless user has logic depend on workflow history). Activity failures stored in workflow mutable state is not visible to workflow code and can only be retrieved via describeWorkflowExecution. 
**Why?**
- Prevent large mutable state
- Yes.
=> Truncate activity failure in mutable state

service/worker/migration/activities.go
- Fix caller info used in migration activities.
- Most importantly, use CallerTypePreemptable (the lowest priority) when generating force replication tasks.
- Also use the type API (the highest priority) for all changes related to namespace config.
**Why?**
- Prevent migration traffic from impacting active user traffic on a cluster.
- When a cluster is at full capacity, force replication is not able to complete.
- Could be.
=> Fix caller info for migration activities

common/collection/indexedtakelist.go, common/collection/indexedtakelist_test.go, common/metrics/metric_defs.go, internal/protocol/naming.go, internal/protocol/naming_test.go, service/history/commandChecker.go, service/history/workflowTaskHandler.go, service/history/workflowTaskHandlerCallbacks.go, service/history/workflowTaskHandler_test.go
Handle ProtocolMessageCommands in WFT completion
**Why?**
ProtocolMessageCommands are references to messages in the same WFT and serve as a way to sequence command and message processing.
New unit tests here
Moderate - changes to command processing.
No
=> Handle ProtocolMessageCommands in WFT completion

common/archiver/filestore/historyArchiver.go, common/archiver/filestore/historyArchiver_test.go, common/archiver/gcloud/historyArchiver.go, common/archiver/gcloud/historyArchiver_test.go, common/archiver/historyIterator.go, common/archiver/historyIterator_mock.go, common/archiver/historyIterator_test.go, common/archiver/s3store/historyArchiver.go, common/archiver/s3store/historyArchiver_test.go, common/persistence/namespaceReplicationQueue.go, common/rpc/context.go, service/frontend/workflow_handler.go, service/history/api/queryworkflow/api.go, service/history/deletemanager/delete_manager.go, service/history/ndc/state_rebuilder.go, service/history/ndc/state_rebuilder_test.go, service/history/ndc/transaction_manager.go, service/history/ndc/transaction_manager_new_workflow.go, service/history/ndc/transaction_manager_new_workflow_test.go, service/history/ndc/transaction_manager_test.go, service/history/shard/controller_impl.go, service/history/transferQueueActiveTaskExecutor.go, service/history/workflow/context.go, service/history/workflow/context_mock.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/retry.go, service/worker/archiver/client.go, tests/workflow_test.go
- Fix context propagation in misc places
**Why?**
- Resolved some context.TODO()
- Make sure caller related information is available in context so persistence layer can do proper priority rate limiting.
- Less timeout for some operations like events reapply
- could be
=> Fix misc. context value propagation issues

service/history/api/updateworkflow/api.go, service/history/workflow/update/update.go
Fix mutable state access after workflow lock is released.
**Why?**
Workflow context and mutable state fields should not be accessed after workflow lock is released.
No risks.
No.
=> Fix mutable state access after workflow lock is released

common/dynamicconfig/constants.go, service/frontend/errors.go, service/frontend/service.go, service/frontend/workflow_handler.go
Add a config flag for enabling async updates
**Why?**
We are likely to enable updates but disable this _async_ flavor of update so split out a new config value.
Ran features test suite with and without property enabled. Async tests fails as expected.
Low
No
=> Add a config flag for enabling async updates

service/history/configs/config.go
Increase default number of Elasticsearch bulk processor workers to 2.
**Why?**
It should help with commit latency during traffic spikes and with "wait add" latency.
On different test clusters.
No risks.
No.
=> Increase default number of Elasticsearch bulk processor workers to 2

service/history/api/updateworkflow/api.go
As commented, a WorkflowKey built from request input may have a blank RunID so we overwrite the one built from the request with the fully specified value pulled (by value) from MutableState.
**Why?**
Causes cache misses and rebuilds on the worker side
Found via feature tests
low
no
=> Ensure workflow key is fully specified

service/history/api/updateworkflow/api.go, tests/update_workflow_test.go
Fix: use normal task queue if sticky worker unavailable during update workflow API call.
**Why?**
If matching replies with `StickyWorkerUnavailable` error, workflow task needs to be added to normal task queue.
Added new functional test.
No risks.
No.
=> Fix: use normal task queue if sticky worker unavailable during update workflow API call

service/history/historyEngine2_test.go, service/history/workflowTaskHandlerCallbacks.go
Don't return workflow task from `RecordWorkflowTaskStarted` if it is speculative and doesn't have any messages (empty).
**Why?**
To save an RPC call to worker and back.
Added new unit test.
No risks.
No.
=> Don't return workflow task if it is speculative and doesn't have any messages (empty)

service/history/historyEngine_test.go, service/history/workflowTaskHandlerCallbacks.go
Fix: `failWorkflowTask` returns wrong `nextEventBatchID` when failing speculative WT.
**Why?**
If current WT is speculative, fail will add 3 events, not 1. `nextEventBatchID` needs to be moved accordingly.
No risks.
No.
=> Fix: failWorkflowTask returns wrong nextEventBatchID when failing speculative workflow tasks

common/rpc/interceptor/telemetry.go, service/history/api/queryworkflow/api.go, tests/query_workflow_test.go
Fail query fast if workflow task attempt count >= 3.
**Why?**
This is to avoid fail query on transient error.
Updated integration test
No
No
=> Fail query fast if workflow task attempt greater or equals 3

service/matching/matcher.go, service/matching/matcher_test.go, service/matching/matchingEngine.go, service/matching/taskQueueManager.go, service/matching/taskReader.go
When tasks come out of the db, pass them through versioning redirection again because versioning data may have changed (default may be different for first wft, or "active" set id may be different). Also, be able to interrupt the head blocking task and re-resolve if versioning data changes.
**Why?**
to make things work
not yet
=> Redirect spooled tasks using versioning directive

service/history/configs/config.go, service/history/replication/bi_direction_stream.go, service/history/replication/bi_direction_stream_test.go, service/history/replication/stream_receiver.go, service/history/replication/stream_receiver_test.go
* Do not recreate gRPC stream if error occurs, instead, rely on periodical health check to re-create stream
**Why?**
Do not recreate gRPC stream since this will lead to resource leak
N/A
N/A
N/A
=> Bugfix: do not leak gRPC stream

tests/update_workflow_test.go
Add functional test for speculative workflow task in sticky task queue timeout.
**Why?**
When speculative WT is added to sticky task queue, but isn't picked up by sticky worker, it gets timed out, events are written to the history and new normal WT is created and added to the normal task queue.
This PR.
No risks.
No.
=> Add functional test for speculative workflow task in sticky task queue timeout

service/history/api/queryworkflow/api.go, service/history/api/updateworkflow/api.go
Fail workflow execution update fast if workflow task constantly fails.
**Why?**
If workflow task is constantly failing, the update to that workflow will also fail. Additionally, workflow update can't "fix" workflow state because updates (delivered with messages) are applied after events.
No tests.
No risks.
No.
=> Fail workflow execution update fast if workflow task constantly fails

common/metrics/metric_defs.go, common/persistence/visibility/store/elasticsearch/processor.go, common/persistence/visibility/store/elasticsearch/processor_test.go
Track the ES bulk response took field to track how long ES took to process the bulk request.
**Why?**
We can compare to the existing commit time and figure out how much is the network time.
No.
No.
=> Add metric to track ES bulk response took field

develop/buildkite/docker-compose-os2.yml, develop/buildkite/pipeline.yml, develop/buildkite/scripts/coverage-report.sh
Add functional test with OpenSearch 2
**Why?**
Test compatibility with OpenSearch 2
N/A
No risks.
No.
=> Add functional test with OpenSearch 2

schema/postgresql/v12/visibility/schema.sql, schema/postgresql/v12/visibility/versioned/v1.2/advanced_visibility.sql
Create btree_gin extension only if not exists
**Why?**
```go
ERROR   Unable to update SQL schema.    {"error": "error executing statement:pq: permission denied to create extension \"btree_gin\"", "logging-call-at": "handler.go:78"}
```
When using managed databases, it is not possible to create databases or extensions like that.
If the extension already exists, an error is thrown as well.
This change seems completely safe. Not a legal advice 😉
This change seems completely safe. Not a legal advice 😉
No
=> fix: create btree_gin extension only if not exists

common/metrics/tally_metrics_handler.go
Creating a subscope, even if it is `tmp.Scope.Tagged(nil)`, takes extra time.
Used this script to [benchmark](https://gist.github.com/k24dizzle/f652990a342214c539d348c46e831f41).
Before:
```
go test -benchmem -run=^$ -bench . -benchtime=10s
goos: darwin
goarch: arm64
pkg: test/prom13
BenchmarkCounter-10     67209068               170.4 ns/op            48 B/op          2 allocs/op
PASS
ok      test/prom13     11.812s
```
After:
```
go test -benchmem -run=^$ -bench . -benchtime=10s
goos: darwin
goarch: arm64
pkg: test/prom13
BenchmarkCounter-10     84332931               138.2 ns/op            48 B/op          2 allocs/op
PASS
ok      test/prom13     12.028s
```
=> Avoid making a subscope in tallyMetricsHandler if possible

common/cluster/metadata_test_config.go, service/history/replication/task_processor_manager_test.go, service/history/shard/compatibility.go, service/history/shard/compatibility_test.go
* When clusters have different shard count, logic should use mapping util for shard ID calculation e.g. local 8 shards, remote 4 shards; for local shard ID 5, corresponding remote shard ID is 1, not 5
**Why?**
Bugfix
UT
N/A
No, not released
=> Bugfix: backfill replication queue state read ID calculation

tests/integration_test.go, tests/testvars/test_vars.go, tests/update_workflow_test.go
Refactor `UpdateWorkflowExecution` functional tests.
**Why?**
To reduce code duplication, and make intend clear.
Run test.
No risks.
No.
=> Refactor UpdateWorkflowExecution functional tests

common/namespace/registry.go, common/namespace/registry_mock.go, common/namespace/registry_test.go, common/resource/fx.go, common/searchattribute/mapper.go
Added function to get custom search attributes mapper in namespace registry capable of bypassing the cache if the dynamic config `system.forceSearchAttributesCacheRefreshOnRead` is set to true.
**Why?**
https://github.com/temporalio/temporal/issues/4017
The purpose of the dynamic config is to be able to immediately use the search attributes after being created. However, due to how they work differently when using SQL databases, this flag was a no-op in this case, only working when using Elasticsearch as visibility store.
Started Temporal Server with MySQL, created search attributes, and immediately after started an workflow using the newly created search attributes. Before, it was always failing due to the namespace registry refresh interval. …
=> Add function to get custom search attributes mapper in namespace registry

go.mod, go.sum, tests/advanced_visibility_test.go, tests/versioning_test.go
We'll need to upgrade once more after sdk-go is released.
Just want to upgrade the code to use the latest defintions.
=> Update API and SDK to latest master

service/history/api/deleteworkflow/api.go, service/history/api/terminateworkflow/api.go, service/history/api/workflow_id_reuse_policy.go, service/history/ndc/workflow.go, service/history/ndc/workflow_resetter.go, service/history/ndc/workflow_resetter_test.go, service/history/ndc/workflow_test.go, service/history/timerQueueActiveTaskExecutor.go, service/history/workflow/context.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/util.go, service/history/workflowTaskHandlerCallbacks.go, tests/update_workflow_test.go
Use `WTFailed`.`EventId` as `completion_event_batch_id` when workflow is terminated or timed out.
**Why?**
When speculative WT is converted to normal during workflow termination `completion_event_batch_id` can't be calculated as `GetNextEventID`.
Modified existing function test.
No risks.
No.
=> Use WTFailed.EventId as completion_event_batch_id when workflow is terminated or timed out

common/backoff/retry.go, common/backoff/retry_test.go
- Return early if now + retry backoff period exceeds context deadline
**Why?**
- There's no reason to just wait until timeout happens
- Currently when timeout happens, caller (in other service/pod/host) with just get a context deadline exceeded error, instead it should get the error from last attempt.
=> Improve retry util

common/util.go, service/history/workflow/mutable_state_impl.go
- Only return ErrMissingXXX internal error when getEvent method failed with NotFound error to prevent task processing logic from silently drop the task/error. In all other cases, return the original error.
**Why?**
- If ErrMissingXXX is returned regardless of the actual error of getEvent, caller has no idea what's the actual issue. The error may due to resource exhausted, in which case caller should backoff more before retrying (for task processing a different error metric will be emitted). It can due to timeout, in which case the getEvent operation is retryable, but ErrMissingXXX is an internal error which means the operation is not retryable.
Existing tests
=> Fix mutable state get event error handling

client/matching/client.go, client/matching/client_gen.go, cmd/tools/rpcwrappers/main.go
Consider `GetTaskQueueUserData` a long poll for matching client timeout purposes, and raise the max long poll limit at the matching client level to 5m. (Task poll timeouts are still limited by the LongPollExpirationInterval dynamic config.)
**Why?**
Reduce the overhead of user data long polls.
manually
=> Allow GetTaskQueueUserData and matching long polls to use a 5m timeout

service/history/commandChecker.go, service/history/commandChecker_test.go, service/history/ndc/conflict_resolver.go, service/history/ndc/conflict_resolver_test.go, service/history/ndc/resetter.go, service/history/ndc/resetter_test.go, service/history/ndc/transaction_manager.go, service/history/ndc/transaction_manager_test.go, service/history/ndc/workflow_resetter.go, service/history/ndc/workflow_resetter_test.go, service/history/workflow/context.go, service/history/workflow/context_mock.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflowRebuilder.go, service/history/workflowTaskHandlerCallbacks.go, service/history/workflowTaskHandler_test.go, tests/ndc/ndc_integration_test.go, tests/ndc/replication_integration_test.go
* Use implicit contract, instead of multiple round trip updating history size in 2 different places
* Persistence layer will keep tract of history size & update history size
**Why?**
N/A
more tests
N/A
N/A
=> Rewrite some workflow history size calculation

common/persistence/visibility/store/elasticsearch/client/client.go, common/persistence/visibility/store/elasticsearch/client/client_mock.go, common/persistence/visibility/store/elasticsearch/client/client_v7.go, common/persistence/visibility/store/elasticsearch/visibility_store.go, common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go, develop/buildkite/pipeline.yml, develop/buildkite/scripts/coverage-report.sh
Add ES point in time to Scan API.
Simplified revert of PRs https://github.com/temporalio/temporal/pull/4223 and https://github.com/temporalio/temporal/pull/4249.
Disabled integration tests with OpenSearch 2: current Elasticsearch client is not compatible with OpenSearch 2 point in time API.
**Why?**
Scanning by `_doc` is not reliable if not using Scroll or point in time.
Changed unit tests.
No.
No.
=> Add ES point in time to Scan API

service/history/api/signal_workflow_util.go, service/history/api/signalwithstartworkflow/signal_with_start_workflow.go, service/history/api/signalwithstartworkflow/signal_with_start_workflow_test.go, service/history/api/signalworkflow/api.go, service/history/api/signalworkflow/api_test.go, service/history/consts/const.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_mock.go, service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go, tests/signal_workflow_test.go
=> Reject signal if workflow attempted to close

service/history/workflow/update/registry.go, service/history/workflow/update/registry_test.go, service/history/workflowTaskHandler.go, tests/update_workflow_test.go
Allow workflow to complete if there are updates in the registry.
**Why?**
If updates are keep coming but workflow reached to the completion (especially trying to do `ContinueAsNew`) it is better to allow workflow to complete.
Added new functional tests.
No risks.
No.
=> Allow workflow to complete if there are updates in the registry

common/backoff/retrypolicy.go, common/metrics/metric_defs.go, common/util.go, service/history/consts/const.go, service/history/queues/executable.go, service/history/queues/executable_test.go, service/history/timerQueueTaskExecutorBase.go, service/history/transferQueueTaskExecutorBase.go
- Do not retry task while holding the goroutine. <- the original intention, but currently retry policy with max attempts = 1 will retry once, so in total 2 attemtps.
- Re-purpose `task_latency` metric, to be in memory no-user latency. to prevent noisy alerts.
**Why?**
=> Improve task latency calculation and retry behavior

temporal/fx.go, temporal/server.go
Make `NewServerFx` more easily usable by alternate initialization code
**Why?**
Make it easier to embed server as a library
Manual tests
=> Make server fx init more extendable

service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go
Remove speculative workflow task restoration code.
**Why?**
Code was commented out but final design blocks WT restoration because validation logic depends on the registry which is also lost when shard moves.
No risks.
No.
=> Remove speculative workflow task restoration code

service/history/queues/executable.go, service/history/queues/executable_test.go
- Fix task inMemoryNoUserLatency 2.0
**Why?**
- HandleError() is not called when task error is nil
- Add more tests
- Verified on local dashboard.
=> Fix task inMemoryNoUserLatency 2.0

service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go, tests/update_workflow_test.go
Add test for heartbeat from speculative workflow task.
**Why?**
When worker sends heartbeat response for speculative WT, it gets converted to normal, all 3 WT events get written into the history and new normal WT is created. This should never happened though because update validation/processor handers shouldn't take more than WT `StartToClose` timeout.
This PR.
No risks.
No.
=> Add test for heartbeat from speculative workflow task

service/history/workflow/workflow_task_state_machine.go
Remove unneeded `FlushAndCreateNewBatch` call from `AddWorkflowTaskScheduleToStartTimeoutEvent`.
**Why?**
`AddWorkflowTaskScheduleToStartTimeoutEvent` is called `executeWorkflowTaskTimeoutTask` where it follows by `updateWorkflowExecution` which always will create a new batch.
No risks.
No.
=> Remove unneeded FlushAndCreateNewBatch call from AddWorkflowTaskScheduleToStartTimeoutEvent

service/history/workflow/update/update.go, service/history/workflow/update/update_test.go
Take acceptedEventID write out of commit callback
**Why?**
This value needs to be visible to the update completion message handler even in the case when the acceptance and completion come in the same message batch (i.e. workflow task).
Unit test changed to create the scenario in question
Low
No
=> Take acceptedEventID write out of commit callback

tests/integrationbase.go, tests/update_workflow_test.go
Add ability to add comments and event attributes one wants to assert to expected history in functional tests.
**Why?**
To improve tests maintainability and increase coverage. I am going to add more comments and attributes to other histories later.
Modified one test.
No risks.
No.
=> Comments and event attributes in expected history in tests

service/frontend/workflow_handler.go, service/matching/taskQueueManager.go, tests/versioning_test.go
Add more tests and followups from #4375:
- Rename `isVersioned` to `managesSpecificVersionSet`
- Test wtih `UseBuildIDForVersioning: false`
- Test dispatch with activities that fail or timeout (to test retry)
- Test activity with compatible version
- Test child workflow with compatible version
- Test query dispatch
**Why?**
More tests
More tests
=> More functional tests for worker versioning

service/matching/config.go
Looking up task-queue-specific dynamic config should use the base name
**Why?**
Fix bug
=> Use task queue base name for dynamic config

common/metrics/defs.go
The `MetricsType` isn't actually used anywhere other than `GetMetricType` which isn't called anywhere.
**Why?**
It's confusing that this exists when it doesn't do anything. It's already clear what the type of the metric is when this value is written, and no one is reading it.
Looking for references to it and using the CI. I also verified that this doesn't change the help text in the /metrics page, which still contains the metric type:
```
```
=> Remove unused MetricType concept

common/dynamicconfig/constants.go, service/matching/config.go, service/matching/matchingEngine.go, service/matching/matchingEngine_test.go, service/matching/taskQueueManager.go, service/matching/taskQueueManager_test.go, service/matching/taskWriter.go, tests/versioning_test.go
See PR title
**Why?**
Closes #4450 
User data is a new feature and effects every task queue load in matching. We need a way to disable it.
Unit tests and functional tests.
=> Add dynamic config to disable loading task queue user data

service/matching/db.go, service/matching/matchingEngine_test.go, service/matching/taskQueueManager.go, service/matching/taskQueueManager_test.go, tests/versioning_test.go
- Load user data from db only once on init
- Consolidate setting user data future in one function
**Why?**
- Root partition with no user data should only read it once
- Simplify code
Manually + new unit test
=> Refactor task queue user data loading

.golangci.yml, service/history/workflow/update/export_test.go, service/history/workflow/update/registry.go
^
**Why?**
Returning an unexported type from an exported method allows clients to use the object's exported methods without the need for authors to introduce another interface. It also allows users to use exported fields of the object, too, which isn't possible with interfaces. It also lets you use the opaque interface pattern for free.
I added a test violation and ran the linter with/without this change.
=> Disable revive.unexported-return linter

service/history/ndc/branch_manager.go, service/history/ndc/branch_manager_test.go, service/history/ndc/workflow.go
* Schedule a new workflow task after force flush buffer events
**Why?**
[#cadence/5006](https://github.com/uber/cadence/issues/5006)
N/A
N/A
N/A
=> Schedule a new workflow task after force flush buffer events

tests/taskpoller.go
Functional tests: Set `ReturnNewWorkflowTask` for task poller always to `true`.
**Why?**
All exeisting SDKs have this flag set to true and it's gonna be deprecated in future.
Run tests.
No risks.
No.
=> Functional tests: Set ReturnNewWorkflowTask for task poller always to true

service/worker/migration/force_replication_workflow.go, service/worker/migration/handover_workflow.go
**Why?**
Avoid client retry when input is invalid.
=> Return NonRetryableApplicationError if input is invalid in ForceReplicationWorkflow and NamespaceHandoverWorkflow

common/dynamicconfig/static_properties.go, common/util.go, service/matching/db.go, service/matching/matchingEngine.go, service/matching/matchingEngine_test.go, service/matching/taskQueueManager.go, service/matching/taskQueueManager_test.go, service/matching/taskReader.go, tests/versioning_test.go
- Use error from GetUserData for "drop task" decisions
- New workflows ("use default") can start on the unversioned queue when user data is disabled
- Buffered versioned tasks are not dropped, they're retried indefinitely
- Dispatch buffered tasks loop exits sooner on context canceled
- GetWorkerBuildIdCompatibility, etc. return error when user data disabled
**Why?**
- Consolidate logic, easier to understand
- Allow workflow to start when user data disabled
- Preserve tasks when possible
- Return error instead of misleading data
existing + new tests
=> Refactor matching operations when user data disabled

service/history/workflow/history_builder.go, service/history/workflow/history_builder_test.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/util.go, service/history/workflow/workflow_task_state_machine.go, service/history/workflowTaskHandlerCallbacks.go
Check if `WorkflowTaskFailed` event is `nil` when workflow completes.
**Why?**
To properly set `CompletionEventBatchId` in mutable state. Bug was introduced in #4392.
Didn't test.
No risks.
No.
=> Check if WorkflowTaskFailed event is nil when workflow completes

service/frontend/workflow_handler.go, service/frontend/workflow_handler_test.go, tests/client_integration_test.go
pass reset type params from `StartBatchOperationRequest` to
`StartBatchOperation`.
**Why?**
This is a bug, reset params should be passed further down the call stack.
Added Unit and integration tests.
N/A
No
=> Add missing reset type params

common/persistence/visibility/store/elasticsearch/processor.go, common/persistence/visibility/store/elasticsearch/processor_test.go
Moved the line recording ES bulk took time to after the err check
**Why?**
If err is not nil, then the response can be nil which can cause panic.
=> Record ES bulk took time after err check

client/clientBean.go, service/frontend/dcRedirectionPolicy.go
Change cluster not found error to unavailable error
**Why?**
This is internal misconfigured and should return unavailable error.
=> Cluster not found

client/matching/client_gen.go, cmd/tools/rpcwrappers/main.go
^
**Why?**
Was getting errors for this: 
Reran same test that triggered them `go test ./client/...`
=> Fix wrong format specifier in client_gen

common/dynamicconfig/constants.go, service/frontend/configs/quotas.go, service/frontend/configs/quotas_test.go
This was mentioned in the review for #4455 but was not addressed.
=> Apply stricter rate limiting for the RegisterNamespace API

service/matching/matchingEngine.go, service/matching/taskQueueManager.go, tests/versioning_test.go
Ensure that tasks with the "default" versioning directive get spooled in the unversioned queue as they not
associated with any version set until their execution is touched by a version specific worker.
"compatible" tasks OTOH are associated with a specific version set and should be stored along with all tasks for
that version set.
The task queue default set is dynamic and applies only at dispatch time. Putting "default" tasks into version set
specific queues could cause them to get stuck behind "compatible" tasks when they should be able to progress
independently.
=> Spool tasks with "default" versioning directive along with unversioned tasks

common/dynamicconfig/constants.go, service/history/configs/config.go, service/history/transferQueueActiveTaskExecutor_test.go, service/history/workflow/mutable_state.go, service/history/workflow/mutable_state_impl.go, service/history/workflow/mutable_state_impl_test.go, service/history/workflowTaskHandlerCallbacks.go
Build ids can have an arbitrary length of up to 255 bytes and the maximum search attribute size is 2k.
While reducing the _number_ of tracked build ids is possible, the approach taken in this PR is to truncate when exceeding the search attribute size limit and permits storing a lot of shorter build ids or a less longer ones.
=> Use search attribute size limit for BuildIds truncation

service/matching/taskQueueManager.go, service/matching/taskQueueManager_test.go, service/matching/taskWriter.go
- Wrap setting initialized futures
**Why?**
- Consolidate unload logic
existing tests
=> Wrap setting futures in taskQueueManager

common/dynamicconfig/constants.go, service/worker/scanner/build_ids/scavenger.go, service/worker/scanner/build_ids/scavenger_test.go, service/worker/scanner/scanner.go, service/worker/service.go, tests/advanced_visibility_test.go, tests/xdc/user_data_replication_test.go
Part 3 of the last minute refactoring of versioning data timestamps (see #4524 and #4526).
With this change, the scavenger uses the build id `became_default_timestamp` to determine whether it should be considered for removal.
From the documentation in code:
```
// If a build id was still default recently, there may be:
// 1. workers with that identifier processing tasks
// 2. workflows with that identifier that have yet to be indexed in visibility
// The scavenger should allow enough time to pass before cleaning these build ids.
```
Note that this is stacked on top of #4526 and only the last commit should be reviewed.
=> Prevent scavenger from removing build ids that were recently default for a set

service/history/workflow/context.go, service/history/workflow/update/registry.go, service/history/workflow/update/registry_test.go, service/history/workflowTaskHandler_test.go
- Use up to date mutable state in update registry
**Why?**
- Lifecycle for updateRegistry is different from mutable state.
- Tested on test cell
- yes
=> Update updateRegistry store on mutable state reload

temporal/server_test.go
I added a test which verifies that the server can run for 10 seconds without logging any new errors or warnings.
**Why?**
There have been several times where we've introduced regressions which are visible within a few seconds of starting the server. Ideally, we have a better test for this than just running the server for 10 seconds, but it's been several months since we've needed this test, and I haven't thought of anything else.
A recent regression is fixed in the commit here titled "Log fxevent.Run". I made an example branch just containing this new test which still has that regression, and you should be able to see this test fail there: https://buildkite.com/temporal/temporal-public/builds/10576
There may be some existing …
=> Add an error log detection test to the server

service/history/deletemanager/delete_manager.go, service/history/deletemanager/delete_manager_test.go
Check if it's using Cassandra visibility store before getting execution start/close time.
**Why?**
Start/close time is only needed for deletion if it's using Cassandra as visibility store.
Unit test.
No.
No.
=> Get execution start/close time when using cassandra visibility store

service/history/queues/executable.go, service/history/queues/executable_test.go
Handle get namespace by id error
**Why?**
Handle get namespace by id error
Yes.
=> Handle get namespace by id error

service/matching/matchingEngine.go, service/matching/matchingEngine_test.go, service/matching/task.go, service/matching/taskQueueManager.go
PollWorkflowTaskQueue returns a hint for the backlog on the task queue polled, which is measured (approximately) as tasks in the taskReader buffer or pending return to a poller. When matching a task that came from the db, the task itself would be counted in the backlog, since the backlog was recorded at match time, instead of after marking the task acked.
This measures the backlog after marking the task acked.
**Why?**
SDKs always poll on the sticky queue if there is a backlog, so they could incorrectly poll on the sticky queue when there are no tasks there and neglect the normal queue, causing a delay of up to the long poll interval.
manually for now
=> Measure backlog after completing current task

service/matching/matchingEngine.go, service/matching/matchingEngine_test.go, service/matching/taskQueueManager.go, service/matching/taskQueueManager_test.go
taskQueueManager tries to persist its state (ack level) one final time on unload. This is useless if it lost ownership since we know the write will fail. We can tell the difference and make it skip the call if it lost ownership.
Also don't log if it fails since we're unloading anyway.
**Why?**
Avoid useless persistence calls.
existing tests, new unit tests
=> Skip final task queue update if lost ownership

service/history/shard/context_impl.go
* Fix migration in mem ack aggregation, since sender based / receiver based aggregation cannot be unified
**Why?**
Bugfix
N/A
N/A
N/A
=> Fix migration in mem ack aggregation

temporal/server_test.go
1. We now use `ForServices(DefaultServices)` in the server test. 
2. In addition, we only check error messages while the server is starting and running, not while it is shutting down.
**Why?**
1. This test wasn't doing much without ForServices, which I mistakenly removed in a previous PR. It was just starting the server but no services.
2. The volume and variety of errors during shutdown is intractable
I ran it locally 10 times, and twice on the CI.
Could easily become a flaky test.
No
=> Use DefaultServices for server_test

common/membership/interfaces.go, common/membership/interfaces_mock.go, common/membership/ringpop/fx.go, service/frontend/fx.go, service/frontend/service.go, service/history/service.go, service/history/shard/controller_impl.go, service/history/shard/controller_test.go, service/matching/service.go, service/worker/service.go, tests/simple_monitor.go, tests/simple_service_resolver.go
This moves the membership monitor Start call from a fx lifecycle hook to each individual service's start method.
Note: this is on top of https://github.com/temporalio/temporal/pull/4506 , which is needed so that services can still get the hostinfo (server address) to use when they, eg, initialize their service tagged loggers.
**Why?**
In short, because a service instance shouldn't join ringpop, and hence begin to have requests forwarded to it, until it is ready to receive them. In internal testing, focusing on the impact of history service restarts/upgrades, we've seen requests suffer unnecessary delay because they were forwarded to a new history pod before it began accepting on its announced service address.
This has been tested in a staging …
=> move ringpop start call to service start

common/dynamicconfig/constants.go, service/history/configs/config.go, service/history/service.go
(On top of https://github.com/temporalio/temporal/pull/4510 )
When a history instance starts, support a configurable (defaulting to zero) delay before joining membership.
**Why?**
In environments where the history service is running via a Kubernetes Deployment, rolling restarts or image upgrades cause considerable shard movement, because the Deployment will simultaneously terminate one pod & create a new one. By configuring a non-zero delay on the order of seconds, the shard movement due to the terminating pod can be separated from the shard movement of the newly created pod. Overall, this reduces the impact to user api calls during the change.
This has been tested in a staging environment.
With the default setting of zero, no …
=> support delay before history joins membership

service/frontend/fx.go, service/frontend/service.go, service/history/fx.go, service/history/service.go, service/matching/fx.go, service/matching/service.go, service/worker/fx.go, service/worker/service.go, temporal/fx.go, tests/onebox.go
- Change the four main `Service` `Start` methods to no longer block
- But also run synchronously in fx lifecycle (except for the final `Serve` call)
- Use `fx.StartStopHook` to simplify code
- Get rid of `s.status` atomic ops since fx will serialize Start/Stop
- Get rid of `stopChan` as well
**Why?**
Allow more of service start/stop to be serialized by fx lifecycle, to avoid bugs when e.g. Stop is called while Start is still running.
manually and integration tests
=> Refactor fx service Start/Stop

service/history/service.go
This simplifies the logic inside history service stop, while still using the `ShutdownDrainDuration` config to allow answering requests while shutdown is in progress.
**Why?**
With this change, the only pause is immediately after leaving membership, and the duration of that pause is completely configurable. A pause at that point is useful, because it keeps the terminating instance up to respond with shard ownership lost errors to in-flight requests, and history clients will retry those requests quickly. 
This was tested in a staging environment.
ShutdownDrainDuration defaults to zero, so this change only impacts environments which intentionally set that config. For environments that do set it, it was previously gated by the …
=> wait for drain duration before stopping shard controller
