- service/history/workflow/task_generator_test.go
Fix flaky jitter test
**Why?**
Fix flaky jitter test
> Fix flaky jitter test

- develop/docker-compose/docker-compose.cdc.yml
- develop/docker-compose/docker-compose.yml
Update UI to v2.10.0 in `develop` >`docker-compose` > `docker-compose.yml` and `docker-compose.cdc.yml`.
**Why?**
Keep UI up to date.
n/a
n/a
No
> Update UI to v2.10.0

- common/util.go
Change deadline too short to failedPrecondition error.
**Why?**
This should not be invalid argument.
> Change deadline too short to failedPrecondition error

- develop/docker-compose/docker-compose.cdc.yml
- develop/docker-compose/docker-compose.yml
Update to use the latest version of the UI
**Why?**
Version 2.10.0 had a bug where reloading any page across the app would cause it to crash
Tested the UI image locally
N/A
No
> update development version of temporalio/ui to 2.10.1

- common/persistence/visibility/store/elasticsearch/client/client_v7.go
- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/searchattribute/defs.go
- common/searchattribute/encode_value.go
- common/searchattribute/name_type_map_test.go
- common/searchattribute/stringify.go
- service/history/workflow/mutable_state_impl.go
Updated existing keyword search attributes that can be a list to be of type keyword list.
**Why?**
Going forward, keyword list will be a different type of keyword.
None. It's only available for elasticsearch visibility, and in this case, it's a no-op.
No.
> Update type of keyword list search attributes

- service/history/replication/task_processor_manager.go
clean replication task processor after disconnect
**Why?**
> clean replication task processor after disconnect

- .golangci.yml
^
**Why?**
It's not very useful
> Disable unused-parameter linter

- .golangci.yml
^
**Why?**
Failures here are very rare and very difficult to do anything about
I added an unchecked Printf after making this change, and I verified that the linter didn't complain
> Ignore unhandled errors from fmt.Printf

- go.mod
- go.sum
Update SDK dependency to v1.21.0
**Why?**
Good dependency hygiene
Standard in-tree tests
Low
No
> Update SDK dependency to v1.21.0

- service/frontend/adminHandler.go
> Fix clientFactory build issue

- schema/mysql/v8/visibility/schema.sql
- schema/mysql/v8/visibility/versioned/v1.2/advanced_visibility.sql
Removed foreign key from MySQL visibility schema.
**Why?**
Compatibility with Vitess.
No risks.
No.
> Remove foreign key from MySQL visibility schema

- common/dynamicconfig/constants.go
- service/frontend/service.go
Update failure detect default time
**Why?**
Update failure detect default time to 0
> Update failure detect default time

- go.mod
- go.sum
- service/frontend/workflow_handler.go
- service/history/workflow/history_builder.go
- service/history/workflow/history_builder_test.go
- service/history/workflow/workflow_task_state_machine.go
Updated protos & propagated new SDK metadata field from WFT completion to corresponding event
**Why?**
Unlock feature-flagging capabilities for SDK
Verified field is propagated in existing unit test
None
> Propagate SDK Metadata & add capability

- common/tasks/interleaved_weighted_round_robin_test.go
- Fix UpdateWeight test
**Why?**
-  Fix flaky test
```
go test -race -run TestInterleavedWeightedRoundRobinSchedulerSuite -testify.m TestUpdateWeight -count=1000
```
> Fix IWRR scheduler UpdateWeight test

- common/persistence/visibility/store/sql/query_converter.go
- common/persistence/visibility/store/sql/query_converter_mysql.go
- common/persistence/visibility/store/sql/query_converter_postgresql.go
- common/persistence/visibility/store/sql/query_converter_sqlite.go
- common/persistence/visibility/store/sql/query_converter_util.go
Refactoring more code:
- Better error messages.
- Created type `saColName` that wraps `colName` for search attribute and includes the alias, field name, and type. This is to reduce duplication of error handling while parsing search attribute.
**Why?**
Code refactoring, better error messages.
Writing unit tests.
No risks.
No.
> Refactor SQL query converter

- common/persistence/visibility/store/sql/query_converter_mysql_test.go
- common/persistence/visibility/store/sql/query_converter_postgresql_test.go
- common/persistence/visibility/store/sql/query_converter_sqlite_test.go
- common/persistence/visibility/store/sql/query_converter_test.go
- common/searchattribute/test_provider.go
Add SQL query converter tests.
**Why?**
Add tests.
Added tests.
No risks.
No.
> Add SQL query converter tests

- common/membership/ringpop/factory.go
- common/membership/ringpop/factory_test.go
- common/membership/ringpop/fx.go
- common/membership/ringpop/hostinfo.go
- common/membership/ringpop/monitor.go
- common/membership/ringpop/monitor_test.go
- common/membership/ringpop/ringpop.go
- common/membership/ringpop/service_resolver.go
- common/membership/ringpop/test_cluster.go
- common/resource/fx.go
- temporal/fx.go
I moved all ring RingPop-related code from the membership package to the ringpop package.
I also addressed several linter warnings.
**Why?**
To separate interfaces from implementations.
> Move ringpop code from membership to ringpop package

- temporal/server_impl.go
> Fix comment above NewServerFxImpl

- service/history/queues/queue_base.go
- service/history/queues/queue_base_test.go
- service/history/queues/reader.go
- service/history/queues/reader_group.go
- service/history/queues/reader_group_test.go
- service/history/queues/reader_test.go
- service/history/replication/task_processor_manager.go
- service/history/replication/task_processor_manager_test.go
- Update history task reader progress
**Why?**
* Update progress is a hint for persistence implementation. See: https://github.com/temporalio/temporal/pull/3986
* The base of the PR contains https://github.com/temporalio/temporal/pull/3995 so that review is easier, will update base after that PR is landed.
- N/A, underlying impl is no-op right now
- No.
> Update history task reader progress

- common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go
> Extract cluster config logic into ConfigureCassandraCluster()

- common/persistence/cassandra/factory.go
- common/persistence/cassandra/test.go
- common/persistence/cassandra/version_checker.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go
- common/persistence/tests/cassandra_test_util.go
- common/persistence/visibility/store/standard/cassandra/visibility_store.go
- tools/cassandra/cqlclient.go
> Cherry pick commits

- tests/xdc/integration_failover_test.go
* Add more test for XDC
**Why?**
More test coverage
Test only
N/A
N/A
> Add more test for XDC

- common/persistence/cassandra/factory.go
- common/persistence/cassandra/test.go
- common/persistence/cassandra/version_checker.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go
- common/persistence/tests/cassandra_test_util.go
- common/persistence/visibility/store/standard/cassandra/visibility_store.go
- tools/cassandra/cqlclient.go
> Add astra interface refactoring on top of release/v.1.20.x

- service/history/commandChecker.go
Improve message sequence validator:
1. Validate sequence for specific `protocol_instance_id`.
2. Don't allow rejections come with `Response` or `Acceptance` messages.
**Why?**
Fix validatation logic.
Not tested.
No risks.
No.
> Improve message sequence validator

- common/timer/gate.go
- common/timer/local_gate.go
- common/timer/local_gate_test.go
- common/timer/remote_gate.go
- common/timer/remote_gate_test.go
- service/history/queues/queue_scheduled.go
- service/history/queues/queue_scheduled_test.go
- service/history/queues/rescheduler.go
Rename variables in `timer` package.
**Why?**
Consistency, better readability, typos.
N/A
No risks.
No.
> Rename variables in timer package

- common/persistence/visibility/defs.go
- common/persistence/visibility/manager_selector.go
- service/frontend/fx.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/task_refresher.go
- service/worker/fx.go
- tests/dynamicconfig.go
- tests/onebox.go
Rename visibility writing mode constants.
**Why?**
Better naming since advanced visibility features are now available with SQL DB.
No risks.
No.
> Rename visibility writing mode consts

- service/history/workflow/mutable_state_impl_test.go
- This test is added in https://github.com/temporalio/temporal/pull/4065, but https://github.com/temporalio/temporal/pull/4076 changes the logic and merged without rebasing on master so it doesn't see the added test.
**Why?**
> Fix test failure from merge conflict

- client/frontend/client_gen.go
- client/frontend/metric_client_gen.go
- client/frontend/retryable_client_gen.go
- common/metrics/metric_defs.go
- go.mod
- go.sum
- service/frontend/configs/quotas.go
- service/frontend/configs/quotas_test.go
- service/frontend/errors.go
- service/frontend/interface_mock.go
- service/frontend/redirection_interceptor.go
- service/frontend/redirection_interceptor_test.go
- service/frontend/workflow_handler.go
Most of this is codegen - hand-written part is mainly `workflow_handler.go` which does a small amount of boilerplate request validation and then returns an "unimplemented" gRPC error.
**Why?**
Making space for an implementation to follow.
Just need to compile now.
No risks.
No.
> Stub out new PollWorkflowExecutionUpdate API

- api/matchingservice/v1/request_response.pb.go
- api/matchingservice/v1/service.pb.go
- api/matchingservicemock/v1/service.pb.mock.go
- client/frontend/client_gen.go
- client/frontend/metric_client_gen.go
- client/frontend/retryable_client_gen.go
- client/matching/client_gen.go
- client/matching/metric_client_gen.go
- client/matching/retryable_client_gen.go
- cmd/tools/rpcwrappers/main.go
- common/metrics/metric_defs.go
- common/testing/mocksdk/client_mock.go
- go.mod
- go.sum
- proto/internal/temporal/server/api/matchingservice/v1/request_response.proto
- proto/internal/temporal/server/api/matchingservice/v1/service.proto
- service/frontend/configs/quotas.go
- service/frontend/configs/quotas_test.go
- service/frontend/interface_mock.go
- service/frontend/redirection_interceptor.go
- service/frontend/redirection_interceptor_test.go
- service/frontend/workflow_handler.go
- service/matching/configs/quotas.go
- service/matching/handler.go
- service/matching/matchingEngine.go
- service/matching/matchingEngineInterfaces.go
- service/matching/matchingEngine_test.go
- service/matching/version_sets.go
- service/matching/version_sets_test.go
- tests/versioning_test.go
Apply spelling correction from https://github.com/temporalio/api/pull/268
https://github.com/temporalio/temporal/pull/4081 should be merged first
**Why?**
Misspelling things looks pretty silly.
Purely mechanical
> Fix compatibility spelling

- service/worker/pernamespaceworker.go
Per-namespace worker refreshes on namespace state changes or membership changes, and reads dynamic config at that point, but it doesn't automatically respond to dynamic config changes. This makes it refresh every ten minutes even if there were no other changes.
**Why?**
So that we don't have to force a membership change for dynamic config to take effect.
tested manually, existing integration tests
> Refresh per-namespace worker periodically

- common/membership/grpc_resolver.go
- common/membership/interfaces.go
- common/membership/ringpop/hostinfo.go
- common/membership/ringpop/monitor.go
- common/membership/ringpop/service_resolver.go
> Fix some minor linter warnings in the membership package

- common/dynamicconfig/constants.go
- service/worker/scanner/executions/scavenger.go
- service/worker/scanner/executions/task.go
- service/worker/scanner/scanner.go
- service/worker/scanner/workflow.go
- service/worker/service.go
Add flag to enable execution scanner event Id validator.
**Why?**
To be able to disable event Id validator.
Local test.
No risks.
Yes.
> Add flag to enable execution scanner event Id validator

- develop/docker-compose/docker-compose.cdc.yml
- develop/docker-compose/docker-compose.yml
> Bump UI version

- common/persistence/sql/sqlplugin/visibility.go
- common/persistence/visibility/store/sql/visibility_store.go
- schema/mysql/v8/version.go
- schema/mysql/v8/visibility/schema.sql
- schema/mysql/v8/visibility/versioned/v1.3/add_history_size_bytes.sql
- schema/mysql/v8/visibility/versioned/v1.3/manifest.json
- schema/postgresql/v12/version.go
- schema/postgresql/v12/visibility/schema.sql
- schema/postgresql/v12/visibility/versioned/v1.3/add_history_size_bytes.sql
- schema/postgresql/v12/visibility/versioned/v1.3/manifest.json
- schema/sqlite/v3/visibility/schema.sql
Add history size bytes to advanced visibility with SQL DB.
**Why?**
Unit test. Also checked in UI the list API populated the history size bytes field.
No risks.
No.
> Add history size bytes to SQL visibility

- service/history/replication/bi_direction_stream.go
- service/history/replication/bi_direction_stream_test.go
* Fix data race in test
**Why?**
Fix data race
N/A
N/A
N/A
> Fix data race in test

- service/history/ndc/history_replicator.go
* Reduce the # of resend events if workflow is a reset workflow
**Why?**
Optimization
N/A
N/A
N/A
> Reduce the # of resend events if workflow is a reset workflow

- common/persistence/cassandra/history_store.go
- common/persistence/dataInterfaces.go
- common/persistence/history_manager.go
- common/persistence/persistence-tests/historyV2PersistenceTest.go
- common/persistence/persistenceInterface.go
- common/persistence/sql/history_store.go
> Cleanup redundant input args

- service/worker/scheduler/workflow.go
Use the same timer between iterations of the schedule workflow loop
**Why?**
Usually the previous timer would have expired, but in the case of signals (trigger, update, refresh, etc.) then we'd be creating excess timers, which would bloat history
Existing tests, manually verified behavior plus upgrade/downgrade to check for determinism bugs
> Reuse timer in schedule workflow

- Makefile
- common/dynamicconfig/constants.go
- config/development-cluster-a.yaml
- config/development-cluster-b.yaml
- config/development-cluster-c.yaml
- service/history/configs/config.go
- service/history/replication/executable_activity_state_task.go
- service/history/replication/executable_activity_state_task_test.go
- service/history/replication/executable_history_task.go
- service/history/replication/executable_history_task_test.go
- service/history/replication/executable_task.go
- service/history/replication/executable_task_initializer.go
- service/history/replication/executable_task_mock.go
- service/history/replication/executable_task_test.go
- service/history/replication/executable_task_tracker.go
- service/history/replication/executable_task_tracker_mock.go
- service/history/replication/executable_task_tracker_test.go
- service/history/replication/executable_workflow_state_task.go
- service/history/replication/executable_workflow_state_task_test.go
- service/history/replication/fx.go
- service/history/replication/stream_receiver.go
- service/history/replication/stream_receiver_monitor.go
- service/history/replication/stream_receiver_monitor_test.go
- tests/ndc/ndc_integration_test.go
* Properly handle replication task lifecycle by cancel task from task tracker
* Add more unit test for stream monitor
**Why?**
make replication task lifecycle clear
UT
N/A
N/A
> Properly handle replication task lifecycle

- service/history/workflow/task_generator.go
* Do not generate workflow timeout task if workflow is closed
**Why?**
Improve efficiency
N/A
N/A
N/A
> Do not generate workflow timeout task if workflow is closed

- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Addressing comments in https://github.com/temporalio/temporal/pull/4134
**Why?**
Unit tests
No risks
no
> Addressing comments in PR 4134

- go.mod
- go.sum
> Update Go SDK to v1.22.0

- common/persistence/cassandra/history_store.go
- common/persistence/history_manager.go
- common/persistence/persistenceInterface.go
- common/persistence/sql/history_store.go
> Switch from opaque branch token to branch info

- service/history/configs/config.go
- service/history/fx.go
- service/history/historyEngine.go
- service/history/historyEngine2_test.go
- service/history/queue_factory_base_test.go
- service/history/replication/stream_receiver_monitor_test.go
- service/history/tests/vars.go
- service/history/workflowTaskHandlerCallbacks_test.go
Remove `DefaultVisibilityIndexName` from history config.
**Why?**
Consolidate the way to get the index name from visibility manager.
No.
No.
> Remove DefaultVisibilityIndexName from history config

- service/history/queues/queue_base.go
- service/history/shard/context.go
- service/history/shard/context_impl.go
- service/history/shard/context_mock.go
- service/history/visibilityQueueTaskExecutor_test.go
* Rename UpdateQueueState to SetQueueState
**Why?**
The renamed API is a set API, not an update API
N/A
N/A
N/A
> Rename UpdateQueueState to SetQueueState

- service/history/commandChecker.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
- service/history/workflow/update/update.go
- service/history/workflowTaskHandler.go
- service/history/workflowTaskHandlerCallbacks.go
- tests/update_workflow_test.go
Validate message before write to history
**Why?**
To prevent duplicate update events show up in history
New integration test
No
No
> Validate messages against pending updates

- service/history/api/updateworkflow/api.go
- tests/update_workflow_test.go
Added functional test to cover sync update on sticky task queue
**Why?**
More tests
New test
No
No
> Test sync update on sticky task queue

- config/development-cass-es.yaml
- config/development-cluster-a.yaml
- config/development-cluster-b.yaml
- config/development-cluster-c.yaml
- config/development-mysql-es.yaml
- config/development-postgres-es.yaml
- docker/config_template.yaml
Update configs to use `visibilityStore` instead of `advancedVisibilityStore` for Elasticsearch.
**Why?**
No.
No.
> Update vis store dev configs

- common/persistence/visibility/store/sql/visibility_store.go
Call List API from Scan API and make them behave the same. 
**Why?**
Local test
No
> Call List API from Scan API for SQL visibility

- service/matching/db.go
- service/matching/taskQueueManager.go
- service/matching/taskQueueManager_test.go
- service/matching/taskqueue.go
- Small refactor of common condition into OwnsUserData
- Few other misc renames
**Why?**
readability, maintainability
unit tests
> Refactor to use OwnsUserData

- service/matching/matchingEngine.go
- service/matching/matchingEngine_test.go
- service/matching/pollerHistory.go
- service/matching/taskQueueManager.go
- service/matching/taskQueueManager_test.go
Store version capabilities from polls in poller info
**Why?**
debugability
no test yet, should add unit test
> Pass worker version capabilities through poller info

- docker/config_template.yaml
Update docker config template to set up ES secondary index.
**Why?**
https://github.com/temporalio/temporal/issues/3916
Build docker container, and checked it's setting up secondary index.
No.
No.
> Support ES secondary_visibility index in docker config template

- common/cluster/metadata_test_config.go
- common/util.go
- common/util_test.go
- service/history/replication/stream_receiver_monitor.go
- service/history/replication/stream_receiver_monitor_test.go
* Fix bug in shard ID mapping util & UT
* Fix stream receiver monitor & UT
**Why?**
Bugfix
New UT
N/A
N/A
> Bugfix shard ID mapping util & stream receiver monitor

- service/history/replication/stream_receiver_monitor_test.go
* Fix broken tests
**Why?**
N/A
N/A
N/A
N/A
> Fix broken tests

- common/authorization/default_authorizer.go
- common/authorization/default_authorizer_test.go
- common/authorization/interceptor_test.go
Block non admin role from access admin/operator APIs
**Why?**
For non system role, only admin (of their namespace) can access the admin/operator APIs
new unit tests
No
No
> Block non admin role to access system services

- service/history/api/replication/stream.go
- service/history/replication/bi_direction_stream_test.go
* Fix race condition in test
**Why?**
Test randomly fails
go test -timeout=240s -race -count=128 ./service/history/replication/ -run ^TestBiDirectionStreamSuite   
ok  	go.temporal.io/server/service/history/replication	1.463s
N/A
N/A
> Fix test race condition

- common/persistence/client/targeted_fault_injection.go
- common/persistence/persistenceRateLimitedClients.go
- common/persistence/visibility/store/elasticsearch/client/client_v7.go
- service/history/transferQueueActiveTaskExecutor.go
- service/matching/taskQueueManager.go
- tests/client_integration_test.go
- tests/xdc/integration_failover_test.go
- tools/sql/conn.go
Don't create an intermediate variable
Used [gopatch](https://github.com/uber-go/gopatch) for automation:
`return_err.patch`:
```
@@
@@
-err := ...
-return err
+return ...
```
Commands:
```
% gopatch -p return_err.patch ./...
```
**Why?**
Code style fix.
> Code style fix

- common/persistence/cassandra/queue_store.go
- common/persistence/namespaceReplicationQueue.go
- common/persistence/sql/execution.go
- common/persistence/sql/queue.go
- common/rpc/encryption/tlsFactory.go
- service/frontend/workflow_handler.go
- service/history/api/create_workflow_util.go
- service/history/api/signalwithstartworkflow/signal_with_start_workflow.go
- service/history/ndc/workflow_resetter.go
- service/history/replication/task_processor.go
- service/history/transferQueueActiveTaskExecutor.go
- service/history/workflowRebuilder.go
Code simplification.
Used [gopatch](https://github.com/uber-go/gopatch) for automation:
`return_err2.patch`:
```
@@
@@
-if err := ...; err != nil {
-	return err
-}
-return nil
+return ...
```
Commands:
```
% gopatch -p return_err2.patch ./...
```
**Why?**
Code style simplification and improved readability.
> Code style simplification and improved readability for returning errors

- service/history/queues/mitigator.go
> Remove noisy queue action log

- config/dynamicconfig/development-cass.yaml
- config/dynamicconfig/development-sql.yaml
Update dynamic configs related to visibility.
**Why?**
https://github.com/temporalio/temporal/pull/4095
See https://github.com/temporalio/temporal/pull/4095
No.
No.
> Update dynamic config related to visibility

- common/dynamicconfig/constants.go
- service/frontend/errors.go
- service/frontend/service.go
- tests/versioning_test.go
Address @dnr's comments from #4222
> Change dynamic config for worker versioning to be specific to data APIs

- tools/cassandra/handler.go
- tools/common/schema/updatetask.go
Added more debug logging to `temporal-cassandra-tool`.
**Why?**
Sometimes it reports success, but actually was not updating the schema.
Adding more debug logs for investigation.
CICD
Unknown.
Revert.
> Add more logging

- common/persistence/visibility/store/elasticsearch/client/client.go
- common/persistence/visibility/store/elasticsearch/client/client_mock.go
- common/persistence/visibility/store/elasticsearch/client/client_v7.go
Remove PIT and scroll from Elasticsearch client.
**Why?**
Elasticsearch PIT and scroll consumes lots resources, and can potentially slow down the cluster.
No.
No.
> Remove support for ES PIT and scroll in ES client

- go.mod
- go.sum
- schema/mysql/v57/temporal/versioned/v1.10/update_info_maps_table.sql
- schema/mysql/v8/temporal/versioned/v1.10/update_info_maps_table.sql
- service/matching/matchingEngine.go
- service/matching/version_sets.go
- tests/versioning_test.go
- tests/xdc/user_data_replication_test.go
Implement logic for matching on versioned queues. This is not quite right yet, further PRs will fix up various cases. Sending this chunk to show the basic approach.
**Why?**
Implement versioning
not yet
> Redirect to versioned queues in matching

- service/frontend/errors.go
- service/frontend/service.go
- service/frontend/workflow_handler.go
- Use GracefulStop in frontend, followed by Stop after a timeout.
- Repurpose requestDrainTimeout to be that timeout.
- Remove "shutting down" mechanism, since the window it would apply is basically nil.
**Why?**
Fixes #4202 
Manually, integration tests
> Use GracefulStop in frontend

- go.mod
- go.sum
Updated gocql version to v1.4
**Why?**
Address #4265 
CI
Breaking changes
Revert
> Bump gocql to v1.4

- common/persistence/visibility/store/elasticsearch/client/client_v7.go
Enable Elasticsearch body compression with GZip
**Why?**
It might help reduce/improve network traffic.
No.
No.
> Enable Elasticsearch body compression with gzip

- common/rpc/interceptor/telemetry.go
- common/rpc/interceptor/telemetry_test.go
- service/frontend/fx.go
- service/fx.go
- service/history/historyEngine_test.go
* Add server stream interceptor
**Why?**
N/A
N/A
N/A
N/A
> Add server stream interceptor

- common/dynamicconfig/constants.go
- service/history/configs/config.go
- service/history/workflow/context.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
- service/history/workflow/update/update_test.go
Add a per-workflow limit to in-flight updates
**Why?**
Limits keep servers running
New unit tests.
low risk
no
> Add a per-workflow limit to in-flight updates

- service/history/workflow/update/update_test.go
Improve error diagnostics in a unit test
**Why?**
Github is having problems this morning and appears to have dropped this final update to the previous PR.
n/a
none
no
> Improve Update.WaitAccepted - followup

- common/testing/mocksdk/client_mock.go
- go.mod
- go.sum
> Update Go SDK to v1.22.2

- service/history/replication/executable_activity_state_task.go
- service/history/replication/executable_history_task.go
- service/history/replication/executable_noop_task.go
- service/history/replication/executable_task_initializer.go
- service/history/replication/executable_task_tracker.go
- service/history/replication/executable_task_tracker_mock.go
- service/history/replication/executable_unknown_task.go
- service/history/replication/executable_workflow_state_task.go
- service/history/replication/fx.go
- service/history/replication/sequential_queue.go
- service/history/replication/stream_receiver_test.go
* Wire sequential task processor for replication
**Why?**
N/A
N/A
N/A
N/A
> Use sequential task processor for replication

- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Tag metric tracking custom order by with namespace.
**Why?**
Better able to identify the origin of the calls.
Unit tests.
No.
No.
> Tag metric tracking custom order by with namespace

- service/history/workflow/workflow_task_state_machine.go
- tests/update_workflow_test.go
Add functional test to terminate workflow with pending speculative workflow task.
**Why?**
There should be no surprises when workflow is terminated with speculative WT.
This PR.
No risks.
No.
> Add functional test to terminate workflow with pending speculative workflow task

- common/config/config.go
- config/development-cass-archival.yaml
- config/development-cass-es.yaml
- config/development-cass-s3.yaml
- config/development-cass.yaml
- config/development-cluster-a.yaml
- config/development-cluster-b.yaml
- config/development-cluster-c.yaml
- config/development-mysql-es.yaml
- config/development-mysql.yaml
- config/development-mysql8.yaml
- config/development-postgres-es.yaml
- config/development-postgres.yaml
- config/development-postgres12.yaml
- config/development-sqlite-file.yaml
- config/development-sqlite.yaml
- docker/config_template.yaml
Remove unused config field.
**Why?**
Unused, and confuses people.
build passed
No
No
> Remove unused toDC config

- service/history/shard/context_impl.go
- service/history/shard/context_test.go
> Do not generate scheduled task with timestamp in the past

- common/persistence/sql/sqlplugin/matching_task_queue.go
- common/persistence/sql/sqlplugin/mysql/task.go
- common/persistence/sql/sqlplugin/postgresql/task.go
- common/persistence/sql/sqlplugin/sqlite/task.go
- common/persistence/sql/task.go
- service/frontend/workflow_handler.go
- service/history/workflow/mutable_state_impl.go
- service/matching/matchingEngine.go
- service/matching/taskQueueManager.go
> Worker versioning leftovers

- service/history/workflowTaskHandler_test.go
Fix merge issues from PR #4317.
**Why?**
> Fix merge issues from PR 4317

- service/history/replication/ack_manager.go
- service/history/replication/task_processor_manager.go
* Fix prometheus metrics tags for replication code path
**Why?**
Bugfix
N/A
N/A
N/A
> Fix prometheus metrics

- develop/buildkite/Dockerfile
Updated CI builder base image to `temporalio/base-ci-builder:1.9.2`
**Why?**
Use the latest image
CI
CI builds stop working.
Revert
> Bump CI builder base version

- common/persistence/visibility/store/elasticsearch/converter_test.go
- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
- common/persistence/visibility/store/query/converter.go
- common/persistence/visibility/store/query/interceptors_test.go
- common/persistence/visibility/store/standard/converter.go
Change the return value to be `SearchParameters` instead of individual values.
**Why?**
Make it more flexible to add more values to the returned object.
Unit tests.
No.
No.
> Refactor ES query converter

- service/history/shard/context_impl.go
- service/history/shard/context_test.go
- Fix delete visibility task notification. Currently if add visibility task succeeds but later operations fails with error like resource exhausted, task notification is not sent.
**Why?**
- yes
> Fix delete visibility task notification

- tests/update_workflow_test.go
Add functional test for update with existing scheduled workflow task.
Also did some cleanup of existing tests.
**Why?**
New WT and existing started WT cases are already covered. This test to cover the case when update piggybacks existing scheduled WT.
Run it.
No risks.
No.
> Add functional test for update with existing scheduled workflow task

- common/backoff/retrypolicy_test.go
- Fix flaky TestDefaultPublishRetryPolicy
**Why?**
- Flaky test
```
➜ backoff (fix-TestDefaultPublishRetryPolicy) ✔ go test -run TestRetryPolicySuite -testify.m TestDefaultPublishRetryPolicy -count=100
PASS
ok      go.temporal.io/server/common/backoff    0.297s
```
- No.
> Fix TestDefaultPublishRetryPolicy

- service/history/queues/executable.go
- service/history/queues/executable_test.go
- Fix task inMemoryNoUserLatency (bug introduced when addressing the lint comment in https://github.com/temporalio/temporal/pull/4408/commits/6b6a999614e715b937f55edfae6e86149b384b3f#diff-b27a9e79bb5940003f23afc22d6890cf24b930ba0b578882fac927ff23f72b4cL241)
**Why?**
- Fix metric
- Improved corresponding unit test
> Fix task inMemoryNoUserLatency

- go.mod
- go.sum
- service/history/workflow/history_builder.go
- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- service/history/workflow/mutable_state_mock.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/update.go
- service/history/workflow/update/update_test.go
Write accepted event ID in update completion event
**Why?**
Observers of workflow history can stitch together update history by following this link.
New unit test here
Low
No
> Write accepted event ID in update completion event

- service/history/shard/controller_test.go
Adjust some of the shard controller tests to use the existing helper function `setupMocksForAcquireShard`.
**Why?**
This will limit the size of future PR's that may make further changes to shard controller tests.
Ran tests.
None.
No.
> use existing acquire shard test setup

- tests/update_workflow_test.go
Add functional test to deduplicate updates by ID.
**Why?**
If server receives update with the same ID, no new update is created but result of previous one is reused.
Run it.
No risks.
No.
> Add functional test to deduplicate updates by ID

- common/namespace/registry.go
- service/history/archival_queue_task_executor_test.go
- service/history/queues/executable.go
- service/history/queues/executable_test.go
- service/history/queues/executor_wrapper.go
- service/history/queues/executor_wrapper_test.go
1. Drop task when namespace is not on the cluster
**Why?**
No need to process tasks if the namespace is moving out of the cluster.
Unit tests
> Drop task when namespace is not on the cluster

- common/persistence/client/factory.go
- Add retryable client for persistence task manager
**Why?**
- Missed in a previous PR. All persistence manager should have a retryable client
> Add retryable client for persistence task manager

- service/frontend/workflow_handler.go
- tests/schedule_test.go
Hide BuildIds search attribute for schedules
**Why?**
It's not relevant for users since it represents the server worker
integration test
> Hide BuildIds search attribute for schedules

- tests/update_workflow_test.go
Add more asserts on history events attributes and clean up test comments.
**Why?**
To improve test coverage.
Run.
No risks.
No.
> Add more asserts on history events attributes

- config/dynamicconfig/development-cass.yaml
- config/dynamicconfig/development-sql.yaml
Enable workflow update is server ***development*** configs. Docker production config is not affected. Workflow update is still off by default.
**Why?**
Simplify testing env setup.
Run server locally.
No risks.
No.
> Enable workflow update is server development configs

- go.mod
- go.sum
- service/matching/version_sets.go
- service/matching/version_sets_test.go
Implement the operation added in https://github.com/temporalio/api/pull/297
**Why?**
Gotta implement bro
Added UTs
> Implement merge sets operation for Build IDs

- common/persistence/cassandra/history_store.go
- common/persistence/client/fault_injection.go
- common/persistence/dataInterfaces.go
- common/persistence/execution_manager.go
- common/persistence/history_manager.go
- common/persistence/mock/store_mock.go
- common/persistence/persistenceInterface.go
- common/persistence/sql/history_store.go
This is primarily a revert of cdd1a218f83aac371d15fa4ebe5739cf71e623cc
**Why?**
> Merge history tree insert with history node append

- service/history/api/updateworkflow/api.go
- service/history/workflowTaskHandlerCallbacks.go
- tests/update_workflow_test.go
Create normal workflow task if unseen events exist.
**Why?**
Speculative WT can't be used to deliver events to the worker.
New tests.
No risks.
No.
> Create normal workflow task if unseen events exist

- config/dynamicconfig/development-cass.yaml
Remove duplicate keys from dynamic config.
**Why?**
Auto merge error.
Run server.
No risks.
No.
> Remove duplicate keys from dynamic config

- common/metrics/defs.go
^
**Why?**
It doesn't do anything
> Get rid of MetricName type

- tests/versioning_test.go
- Add TestDescribeWorkflowExecution
- Make use of s.prefixed in versioning tests more consistent
**Why?**
Avoid test bugs with missing or double-application of prefix
is test
> Add TestDescribeWorkflowExecution to versioning tests

- tests/versioning_test.go
- Add a test for DescribeTaskQueue (poller info)
**Why?**
test
is test
> Add TestDescribeTaskQueue to versioning tests

- common/namespace/namespace.go
- service/matching/matchingEngine.go
- service/matching/taskQueueManager.go
Based on conversation with @wxing1292
> Only replicate user data for multi cluster setups

- common/metrics/metrics.go
- common/metrics/noop_impl.go
- common/metrics/otel_metrics_handler.go
- common/metrics/tally_metrics_handler.go
Get rid of wrong comment on otelMetricsHandler
Fix WithTags comment
Fix invalid Counter comment
**Why?**
Part of a larger stack of metrics changes to support type-safe metrics
> Fix some typos and comments in metrics package

- common/metrics/otel_metrics_handler.go
- common/metrics/otel_metrics_handler_test.go
^
**Why?**
We probably don't want to crash the entire server when this happens.
I added a unit test which verifies that we log errors when Otel fails. I also verified that the test fails before I made the change. I also verified that the server completely crashes without this change if I just add a static error in one of these methods.
Metrics misconfiguration issues may not surface as loudly in subsequent changes.
No
> Log errors instead of crashing in OTel metrics handler

- tests/update_workflow_test.go
Test update not found due to shard reload case.
**Why?**
Improve test coverage.
Run it.
No risks.
No.
> Test update not found due to shard reload case

- service/history/replication/stream_sender.go
- service/history/replication/stream_sender_test.go
- service/history/shard/context.go
- service/history/shard/context_impl.go
- service/history/shard/context_mock.go
* Add namespace migration support for replication stream, specifically supporting migration between clusters with different # of shards
**Why?**
Bugfix / support
N/A
N/A
N/A
> Add namespace migration support for replication stream

- service/history/workflow/history_builder.go
- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- service/history/workflow/mutable_state_mock.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
- service/history/workflow/update/update.go
- service/history/workflow/update/update_test.go
- service/history/workflow/update/util.go
- service/history/workflow/update/validation.go
- service/history/workflowTaskHandlerCallbacks.go
Remove usages of `AcceptedRequest` field.
**Why?**
`AcceptedRequest` and `RejectedRequest` fields will be removed from update messaging protocol.
Fix exisiting tests.
No risks.
No.
> Remove usages of AcceptedRequest field

- service/history/ndc/workflow.go
* Fix error checking
**Why?**
N/A
N/A
N/A
N/A
> Fix error checking

- service/worker/batcher/activities.go
- service/worker/batcher/workflow.go
Fixed a typo.
**Why?**
Typos are bad!
> Fix typo in batch reset 

- common/persistence/history_manager.go
- common/persistence/persistenceInterface.go
> Bring back branch token for branch deletion

- common/dynamicconfig/collection.go
- common/dynamicconfig/collection_test.go
> Add string dynamic config filter by namespace id

- service/history/queues/queue_base.go
- service/history/shard/context.go
- service/history/shard/context_impl.go
- service/history/shard/context_mock.go
- Perform task range completion on shard rangeID update
**Why?**
🤫 
🤫 
- One more request on shard reload
- Yes.
> Perform task range completion on shard rangeID update

- common/headers/versionChecker.go
Update version for the next release 1.22.0
Updated version to 1.22.0 for the next release
**Why?**
Preparation for the next release
None
Conflicts
No
> Update versionChecker.go for the next release

- temporal/fx.go
Update fxLogAdapter
**Why?**
New event type
manually
> Handle new fx event type

- common/membership/grpc_resolver_test.go
^
**Why?**
Just increasing test coverage.
> Add a test to our gRPC resolver

- service/history/queues/executor_wrapper.go
- Use lowest persistence priority for standby task execution logic
**Why?**
- Prevent standby tasks from impacting active tasks
- yes
> Use lowest persistence priority for standby tasks

- common/util.go
- common/worker_versioning/worker_versioning.go
- service/frontend/workflow_handler.go
- service/history/api/queryworkflow/api.go
- service/history/api/updateworkflow/api.go
- service/history/nDCStandbyTaskUtil.go
- service/history/timerQueueActiveTaskExecutor.go
- service/history/timerQueueActiveTaskExecutor_test.go
- service/history/timerQueueStandbyTaskExecutor_test.go
- service/history/transferQueueActiveTaskExecutor.go
- service/history/transferQueueActiveTaskExecutor_test.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/retry.go
- service/matching/matchingEngine.go
- service/matching/matchingEngine_test.go
- service/matching/taskQueueManager.go
- service/matching/taskQueueManager_test.go
- service/matching/taskReader.go
- tests/versioning_test.go
- Move some code into the `common/worker_versioning` package
- Fix some lint warnings and ignore some others
- Remove noisy log from closing taskReader (made worse by #4493 but the log isn't useful at all)
**Why?**
Code cleanup after feature develoment
Existing tests
> Versioning cleanup

- common/dynamicconfig/constants.go
- service/worker/scanner/build_ids/scavenger.go
- service/worker/scanner/build_ids/scavenger_test.go
- service/worker/scanner/scanner.go
- service/worker/service.go
- On error, skip task queue
- Make sure to exit on activity context canceled
- Add dynamic config for build id scavenger visibility rps
**Why?**
Make scavenger more robust and configurable
Existing tests
> Improve build id scavenger

- .golangci.yml
- service/worker/scanner/build_ids/scavenger_test.go
- tests/versioning_test.go
^
**Why?**
It's not useful in tests
I tested it in https://github.com/temporalio/temporal/commit/b606ee831d6a4e3e1b67ca8e37ae3b63695c02e0 which was failing with make lint before.
> Disable goerr113 in test files

- tests/update_workflow_test.go
Test speculative workflow task creation while completing previous workflow task.
**Why?**
To increase test coverage.
Run.
No risks.
No.
> Test speculative workflow task creation while completing previous workflow task

- schema/mysql/v8/visibility/versioned/v1.3/add_build_ids_search_attribute.sql
Fixed MySQL 8 upgrade script to schema v1.3.
**Why?**
Started Server with MySQL 8, and ran a workflow. Before, it was throwing visibility errors, now it doesn't.
No.
Yes
> Fix MySQL 8 upgrade script to schema v1.3

- .github/workflows/golangci-lint.yml
- .github/workflows/goreleaser.yml
- go.mod
Updated go version to 1.20
**Why?**
To use the latest version
CICD
Breaking changes
Revert
> Update go version to 1.20

- common/util_test.go
^
**Why?**
I'm trying to remove time.Sleep from all of our tests--this is really low-hanging fruit.
> Remove time.Sleep from util_test

- service/history/replication/task_processor_manager.go
Remove verbose logging.
**Why?**
This logging message is not useful.
> Remove verbose logging

- common/cluster/metadata.go
- common/cluster/metadata_test.go
- temporal/fx.go
Support cluster metadata customized tags
**Why?**
Allow static tagging cluster 
Local testing
No
> Support cluster metadata customized tags

- service/history/workflow/mutable_state_impl.go
Do not generate a visibility task for updating BuildIds if it's unchanged.
**Why?**
Excess visibility tasks.
will add unit tests
> Do not generate visibility task for unchanged BuildIds

- common/log/tag/zap_tag.go
- common/persistence/client/health_request_rate_limiter.go
Additional logging when dynamic health rate limiter rate is adjusted
**Why?**
> Log when health rate limiter value changes

- temporal/fx.go
- temporal/server_impl.go
Change nil metrics handle to no op handler
**Why?**
> Change nil metrics handle to no op handler

- tests/update_workflow_test.go
Align new functional tests with old ones.
**Why?**
Some bug fixes, better readability, consistency.
Run.
No risks.
No.
> Cleanup new update related functional tests

- service/matching/db.go
- service/matching/matching_engine.go
- service/matching/task_queue_manager.go
- service/matching/task_queue_manager_test.go
- service/matching/version_sets.go
- Move redirection logic into taskQueueManager, which simplifies it slightly
- Remove unused context argument from GetUserData() since it only returns the in-memory value
**Why?**
Refactoring in advance of some changes that make more sense when the code is here.
existing tests; there should be no behavior changes
> Move redirect logic into taskQueueManager

- service/worker/migration/activities.go
- Minor fixes in force replication verification  - Sleep first in verfication step 
- Remove RetryableTime error
**Why?**
> Minor fixes in force replication verification

- service/history/replication/executable_activity_state_task.go
- service/history/replication/executable_history_task.go
- service/history/replication/executable_task.go
- service/history/replication/executable_workflow_state_task.go
* Add more replication error logs
**Why?**
N/A
N/A
N/A
N/A
> Add more replication error logs

- service/history/fx.go
Assign fx pass in raw task converter
**Why?**
Assign fx pass in raw task converter
Found in functional test
> Assign fx pass in raw task converter

- tools/tdbg/commands.go
* Adjust CLI page size
**Why?**
N/A
N/A
N/A
N/A
> Adjust CLI page size

- common/persistence/persistence-tests/setup.go
- common/persistence/sql/sqlplugin/mysql/visibility.go
- common/persistence/sql/sqlplugin/mysql/visibility_v8.go
- common/persistence/sql/sqlplugin/postgresql/visibility.go
- common/persistence/sql/sqlplugin/postgresql/visibility_v12.go
- common/persistence/sql/sqlplugin/sqlite/visibility.go
- common/persistence/sql/sqlplugin/visibility.go
- common/persistence/tests/visibility_persistence_suite_test.go
- common/persistence/visibility/store/sql/query_converter.go
- common/persistence/visibility/store/sql/query_converter_mysql.go
- common/persistence/visibility/store/sql/query_converter_postgresql.go
- common/persistence/visibility/store/sql/query_converter_sqlite.go
- common/persistence/visibility/store/sql/query_converter_test.go
- common/persistence/visibility/store/sql/visibility_store.go
- tests/advanced_visibility_test.go
Support count group by when using SQL as visibility store.
**Why?**
Add unit tests.
No.
No.
> Support count group by in visibility with SQL

- develop/docker-compose/docker-compose.cdc.yml
- develop/docker-compose/docker-compose.yml
> Bump UI version to 2.17.1

- README.md
Replaced docker based server startup with Temporal CLI dev server.
**Why?**
Aligning server `README` with the docs.
N/A
No risks.
No.
> Update running server locally README

- tools/cassandra/handler.go
Remove debug logs from Cassandra schema upgrade tool.
**Why?**
The debug log contains cql config which includes password.
local test
No
No
> Remove debug logging from Cassandra schema update tool

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
Collapse duplicate visibility tasks
**Why?**
Currently we process the BinaryChecksum and BuildIds search attributes in parallel (until BinaryChecksum is deprecated) and generate an upsert visibility task for each. There are other rare situations where we might generate two upsert visibility tasks in a transaction, e.g. if a workflow changed binary checksum/build id and upserted a search attribute in the same task. In all cases, we only need one task per transaction since they'll do the same thing.
unit test, also manual testing and observed only one task being processed when expected
> Collapse duplicate visibility tasks

- common/archiver/s3store/visibility_archiver.go
- common/archiver/s3store/visibility_archiver_test.go
We now only return one record per workflow execution when listing archived workflows with the S3 storage backend.
**Why?**
To fix https://github.com/temporalio/temporal/issues/4432#issuecomment-1661078704. There's more details in the comments in the code as to why this bug happened and how it is fixed.
I modified our unit test to verify that we don't return any duplicates. The previous unit test was actually too permissive and allowed duplicates. I also manually verified this by restarting the server.
Before:
After:
The ability to list archived workflows when using S3 is already very new, as it was completely unsupported before, and the changes here are just isolated to that query path, so there is little to lose even if this …
> Fix bug causing duplicates when listing s3-archived workflows

- common/metrics/metric_defs.go
Add metric descriptions for schedule metrics
**Why?**
documentation
> Add descriptions for schedule metrics

- common/namespace/registry.go
- service/history/replication/eager_namespace_refresher.go
- service/history/replication/eager_namespace_refresher_test.go
Add eater namespace refresher POC.
**Why?**
Handle the situation where the namespace failover version in current cluster is smaller than the History event version from the source cluster.
N/A
N/A
No
> eager namespace refresher POC

- service/matching/matching_engine.go
- service/matching/matching_engine_test.go
Restore a small optimization that got lost in some refactoring: if we get a workflow task for a sticky queue that's not loaded because it hasn't had pollers in the idle timeout, we don't have to load the queue at all. Note that we would return StickyWorkerUnavailable in any case, since HasPollerAfter would return false.
**Why?**
small optimization
new unit test
> Do not load sticky queue if not loaded

- tools/common/schema/updatetask.go
Make cassandra schema update tool idempotent
**Why?**
So schema upgrade can be retried on partial failure case.
Tested locally, manually reset the schema_version back to older version and run the tool. Observed the logging of 'Duplicate update...'
No
No
> Make cassandra schema update idempotent

- common/persistence/visibility/factory.go
Remove debug logger from visibility manager.
**Why?**
It can print DB username and password.
No.
No.
> Remove debug logger from visibility manager

- service/history/ndc/activity_replicator_test.go
- service/history/ndc/workflow_resetter_test.go
- service/history/workflow/cache/cache.go
- service/history/workflow/cache/cache_test.go
- service/history/workflow/context.go
- service/history/workflow/context_mock.go
- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_mock.go
* Add corruption protection to ms
**Why?**
N/A
N/A
N/A
N/A
> Add corruption protection to ms

- go.mod
- go.sum
- service/frontend/workflow_handler.go
Set capability for count group by execution status
**Why?**
New feature.
No.
No.
> Count group by status capability

- common/payload/payload.go
- common/payload/payload_test.go
When merging map of payloads, if the `src` map contains `nil` value or an empty list, it should remove the key from the `dst` map. Fixing the comparison to check only the encoding type and the value instead of the proto value. This ensures that additional data in the metadata map won't affect the result.
**Why?**
^
No.
No.
> Fix delete search attributes in mutable state

- .github/workflows/features-integration.yml
- .github/workflows/semgrep.yml
- .github/workflows/trigger-publish.yml
- README.md
- develop/buildkite/README.md
Rename leftover `master` to `main`.
**Why?**
`master` branch was renamed to `main` but some places still reference `master`.
N/A
No risks.
No.
> Rename leftover master to main

- service/history/ndc/history_replicator.go
Generate transaction id for each event
**Why?**
Fix a bug where the TXN id is reused if multiple events are within 1 task
N/a
N/a
No
> Generate txn id for each event

- service/history/workflow/task_refresher.go
Update some task refresh logic to avoid unnecessary DB operations.
**Why?**
Update some task refresh logic to avoid unnecessary DB operations.
> Update some task refresh logic

- service/history/shard/controller_impl.go
This increases the maximum allowed shard linger time limit.
**Why?**
A larger time limit may be needed for very large clusters.
None.
> increase max allowed shard linger limit

- service/matching/matching_engine_test.go
- service/matching/version_sets.go
- Test improvements
- More function comments
**Why?**
Tests go faster and comments are good
unit tests
> Fix code review comments from #4762

- go.mod
- go.sum
> Update Go SDK to v1.24.0

- service/worker/migration/activities_test.go
- service/worker/migration/force_replication_workflow.go
- service/worker/migration/force_replication_workflow_test.go
> Add more argument validation for ForceReplicationWorkflow

- temporal/fx.go
Added URL and username to an error log
**Why?**
For better debugging experience
No logic change
None
No
> Add URL and username to ES connection error log

- service/history/api/reapplyevents/api.go
* Persist mutable state changes if any event is reapplied
**Why?**
Fix issue introduced in #4091, [ref](https://github.com/temporalio/temporal/pull/4091/files#r1306573612)
N/A
N/A
N/A
> Fix mutable state change not persisted bug

- temporal/server_test.go
1. I made the server error log test ignore messages containing "Unable to call"  or "service failures"
2. I refactored the test to only spit out unexpected logs instead of all logs
**Why?**
1. These kept appearing in flaky tests
2. When there were test failures, the logs were huge and hard to parse through
I added some unit test cases.
> Ignore 'Unable to call' messages in server error log test

- tests/client_integration_test.go
Added a new functional test to cover the case where a workflow finishes just after creating a timer/child-workflow/activity.
**Why?**
There is an edge case when a workflow starts a timer/child workflow/activity justs before finishing. A change was pushed earlier to handle this case. This test ensures that systems behaves normally in this casse.
Executed functional tests.
None
No
> Adding functional test to cover workflows finishing with deferred commands

- client/admin/metric_client_gen.go
- client/frontend/metric_client_gen.go
- client/history/metric_client_gen.go
- client/matching/metric_client_gen.go
- cmd/tools/rpcwrappers/main.go
- common/metrics/metric_defs.go
> Inline metrics scope names used in generated files

- common/dynamicconfig/constants.go
- service/history/configs/config.go
- service/history/history_engine2_test.go
- service/history/history_engine3_eventsv2_test.go
- service/history/history_engine_factory.go
- service/history/history_engine_test.go
- service/history/ndc/activity_state_replicator_test.go
- service/history/ndc/transaction_manager_test.go
- service/history/ndc/workflow_resetter_test.go
- service/history/replication/ack_manager_test.go
- service/history/timer_queue_active_task_executor_test.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/transfer_queue_active_task_executor_test.go
- service/history/transfer_queue_standby_task_executor_test.go
- service/history/visibility_queue_task_executor_test.go
- service/history/workflow/cache/cache.go
- service/history/workflow/cache/cache_test.go
- service/history/workflow/cache/fx.go
- service/history/workflow_task_handler_callbacks_test.go
Add feature flag for host level workflow cache
**Why?**
Add feature flag for host level workflow cache to protect the new component.
only config changes. Existing tests covers the case.
> Add feature flag for host level workflow cache

- service/history/replication/executable_task_converter.go
- service/history/replication/executable_task_tool_box.go
- service/history/replication/fx.go
- service/history/replication/stream_receiver.go
- service/history/replication/stream_receiver_monitor.go
- service/history/replication/stream_receiver_monitor_test.go
- service/history/replication/stream_receiver_test.go
Split replication executable tool box and task converter
**Why?**
Isolate fx in struct and task converter logic.
Code refactoring. Rely on existing unit tests.
> Split replication executable tool box and task converter

- common/dynamicconfig/constants.go
- common/quotas/dynamic.go
- service/history/configs/config.go
- service/history/queue_factory_base.go
- service/history/queue_factory_base_test.go
- service/history/queues/queue_scheduled_test.go
- service/history/queues/scheduler_quotas.go
- Make task scheduler rate limiter global
- Need to be updated after https://github.com/temporalio/temporal/pull/4803 is landed.
**Why?**
- Easier to config
> Make task scheduler rate limiter global

- service/history/configs/config.go
- service/history/replication/fx.go
- service/history/replication/sequential_queue.go
Fix replication sequential queue hash fn
**Why?**
Fix replication sequential queue hash input is workflow key not replication task
Local test
> Wf key hash

- service/history/ndc/history_importer.go
- service/history/ndc/history_replicator.go
- service/history/ndc/resetter.go
- service/history/ndc/resetter_test.go
- service/history/ndc/transaction_manager.go
- service/history/ndc/transaction_manager_existing_workflow.go
- service/history/ndc/transaction_manager_existing_workflow_test.go
- service/history/ndc/transaction_manager_mock.go
- service/history/ndc/transaction_manager_new_workflow.go
- service/history/ndc/transaction_manager_new_workflow_test.go
- service/history/ndc/transaction_manager_test.go
- service/history/ndc/workflow_state_replicator.go
Expose transaction manager
**Why?**
First step to isolate transaction manager logic
no logic changes
> Extend transaction manager

- .github/workflows/features-integration.yml
- .github/workflows/golangci-lint.yml
- client/matching/loadbalancer.go
- common/backoff/retry.go
- common/collection/concurrent_tx_map.go
- common/persistence/sql/sqlplugin/tests/history_transfer_task.go
- common/persistence/sql/sqlplugin/tests/history_visibility_task.go
- common/persistence/xdc_cache.go
- common/primitives/timestamp/time.go
- common/util.go
- common/util/util.go
- service/frontend/service.go
- service/frontend/task_reachability.go
- service/history/queues/action_slice_count.go
- service/history/queues/executable.go
- service/history/queues/scheduler_monitor.go
- service/history/replication/task_processor_manager.go
- service/history/shard/controller_impl.go
- service/matching/config.go
- service/matching/matching_engine_test.go
- service/matching/task_queue_manager.go
- service/worker/migration/activities.go
- service/worker/pernamespaceworker.go
- service/worker/pernamespaceworker_test.go
- service/worker/scheduler/spec.go
- service/worker/scheduler/workflow_test.go
- temporal/server_impl.go
Removed the custom utility functions `Min` & `Max` and replaced them with the new builtin functions. See https://tip.golang.org/ref/spec#Min_and_max
**Why?**
Less code!
A subtle implementation detail I missed?
No
> Use builtin min/max

- common/metrics/metric_defs.go
- common/persistence/client/fx.go
- common/persistence/client/health_request_rate_limiter.go
- common/persistence/client/quotas.go
Added a new metric for current dynamic rate limit rate multiplier
**Why?**
For visibility / alerting
Existing tests
None
No
> Add metric for dynamic rate limit multiplier

- tests/query_workflow_test.go
One "integration" test case from https://github.com/temporalio/temporal/pull/4867 slipped in.
**Why?**
Make build compile again.
> Rename "integration" tests to "functional" (2)

- service/worker/replicator/namespace_replication_message_processor.go
* Improve XDC logging
**Why?**
Improve XDC logging
N/A
N/A
N/A
> Improve XDC logging

- service/history/queues/monitor.go
- service/history/queues/slice.go
- service/history/queues/tracker.go
- Fixed some typos in names.
**Why?**
- It's a minor codebase improvement.
- `grep` confirms no occurrences of original strings in the codebase.
- Otherwise, I'm relying on the test suite to catch any mistake here.
- No risk, if there were a mistake it would cause compilation errors and would be detected before deploy.
- No
> Fix typos in struct field / variable names

- develop/buildkite/Dockerfile
Bump base-ci-builder image to 1.10.5
**Why?**
Use Go 1.20.10 which addresses https://www.nginx.com/blog/http-2-rapid-reset-attack-impacting-f5-nginx-products/
No.
No.
> Bump base-ci-builder image

- service/worker/scheduler/workflow.go
- service/worker/scheduler/workflow_test.go
Enable changes in #4911
**Why?**
Actually fix bug
Enabled tests from #4911
> Update Version in scheduler workflow

- common/dynamicconfig/constants.go
Mention that workflow update is well tested.
**Why?**
Comment said it is not tested or ready for production use.
I didn't, others did.
> Change comment in update's dynamic config

- .github/workflows/golangci-lint.yml
- .github/workflows/goreleaser.yml
Ensure latest Go version in GH workflows
**Why?**
> Ensure latest Go version in GH workflows

- internal/effect/immediate.go
- service/history/workflow/context.go
- service/history/workflow/update/export_test.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
- service/history/workflow/update/state.go
- service/history/workflow/update/update.go
- service/history/workflow/update/update_test.go
- service/history/workflow_task_handler_test.go
Exported/un-exported structs, fixed typos, removed unused code, re-ordered some test setup code.
**Why?**
Improve readability/cleanup.
Automated tests. No actual behaviour was changed.
N/A
No
> 🧹 Update Workflow nits

- service/history/api/describeworkflow/api.go
From the Go specification (https://go.dev/ref/spec#For_range):
> "3. If the map is nil, the number of iterations is 0."
`len` returns 0 if the map is nil (https://pkg.go.dev/builtin#len). Therefore, checking `len(v) > 0` around a loop is unnecessary, there won't be nil pointer exception. Example: https://go.dev/play/p/vRCsabx62Ef
**Why?**
`make test`
None.
No.
> describeworkflow: remove redundant `len` check

- service/history/shard/context_impl.go
- service/history/shard/controller_test.go
- Fix flaky test
- Reduce some misleading log messages (stopping when stopping or stopped is okay)
**Why?**
Flaky test and misleading logs bad
Ran > 500 times locally with -race
> Fix flaky TestShardControllerFuzz

- temporal/fx.go
> Fix misspelled word

- service/history/workflow/task_refresher.go
- service/history/workflow/task_refresher_mock.go
Add refresh task for close workflow
**Why?**
Add refresh task for close workflow
This is a subset of refresh all tasks
> Add refresh task for close workflow

- service/history/replication/fx.go
Fix replication task batching dc config
**Why?**
Reverse the logic.
test in local
n/a
n/a
> Fix replication task batching dc config

- service/worker/migration/activities.go
- service/worker/migration/activities_test.go
An optimization was added in https://github.com/temporalio/temporal/pull/4791 but we haven't found any real need to apply the optimization. Remove that optimization to reduce code complexity 
**Why?**
Simplify code logic
Unit tests
> Fail VerifyReplicationTask if any task is not found on remote cluster

- common/persistence/data_interfaces.go
- service/frontend/workflow_handler.go
- service/history/api/queryworkflow/api.go
- service/history/configs/config.go
- service/history/ndc/workflow_resetter.go
- service/history/queues/queue_base.go
- service/history/queues/reader.go
- service/history/shard/context_impl.go
- service/history/timer_queue_active_task_executor.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/task_generator.go
- service/history/workflow/transaction_impl.go
- service/history/workflow/workflow_task_state_machine.go
- service/matching/matching_engine.go
- Edited some comments (fixed some typos, eliminated some ambiguities, plus some other minor drive-by edits) 
**Why?**
- It's a minor codebase improvement (keeping the quality up will help avoid distraction while reading code and e.g. places where consecutive sentences didn't start with upper case / end with period were getting hard to read).
- N/A - visual inspection shows diff to be comments only
- No risk
- No
> Edit comments

- common/persistence/sql/sqlplugin/visibility.go
- common/persistence/tests/visibility_persistence_suite_test.go
- common/persistence/visibility/manager/visibility_manager.go
- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/sql/visibility_store.go
- common/persistence/visibility/store/visibility_store.go
- common/persistence/visibility/visibility_manager_impl.go
- common/searchattribute/defs.go
- common/searchattribute/defs_test.go
- schema/mysql/v8/visibility/schema.sql
- schema/mysql/v8/visibility/versioned/v1.4/add_execution_duration.sql
- schema/mysql/v8/visibility/versioned/v1.4/add_state_transition_count.sql
- schema/mysql/v8/visibility/versioned/v1.4/manifest.json
- schema/postgresql/v12/version.go
- schema/postgresql/v12/visibility/schema.sql
- schema/postgresql/v12/visibility/versioned/v1.4/add_execution_duration.sql
- schema/postgresql/v12/visibility/versioned/v1.4/add_state_transition_count.sql
- schema/postgresql/v12/visibility/versioned/v1.4/manifest.json
- schema/sqlite/v3/visibility/schema.sql
- service/history/visibility_queue_task_executor.go
Add ExecutionDuration and StateTransitionCount to SQL visibility schemas.
Add unit test to validate all system search attributes are mapped to SQL DB column name.
Moved StateTransitionCount to visibility Close request only.
**Why?**
Match features with Elasticsearch.
https://github.com/temporalio/temporal/issues/4942
Run unit tests.
No.
No.
> Add ExecutionDuration and StateTransitionCount search attributes to SQL schema

- service/history/replication/raw_task_converter.go
- service/history/replication/stream_sender.go
Update force replication with low priority context
**Why?**
Update force replication with low priority context
> Update force replication with low priority context

- service/history/shard/task_key_manager_test.go
- Fix shard task key manager tests
**Why?**
- Fix flaky tests
- `go test -run TestTaskKeyManagerSuite -testify.m TestSetTaskMinScheduledTime_WithPendingTask -count=100`
- N/A
- No.
> Fix shard task key manager tests

- common/rpc/interceptor/telemetry.go
Adjust action metrics
**Why?**
To reflect pricing change.
Run locally and verify metrics.
No
> Adjust action metrics

- common/headers/version_checker.go
Bump server version to 1.22.2
**Why?**
> Bump server version to 1.22.2

- service/history/transfer_queue_active_task_executor_test.go
- service/history/visibility_queue_task_executor.go
- service/history/visibility_queue_task_executor_test.go
Refactor `visibility_queue_task_executor.go`.
**Why?**
Reduce code duplication.
No.
No.
> Refactor visibility_queue_task_executor.go

- service/history/transfer_queue_standby_task_executor.go
- service/history/transfer_queue_standby_task_executor_test.go
- Propagate the underlying verification error to task executable for proper error handling and metrics.
**Why?**
- Propagate the underlying verification error to task executable for proper error handling and metrics.
- Unit test
> Propagate verification error in task processing

- service/worker/scheduler/workflow.go
Tweak schedule settings to activate changes in #4990 and #5034
**Why?**
Make it work
existing tests
> Activate changes in #4990 and #5034

- common/metrics/metric_defs.go
- common/rpc/interceptor/telemetry.go
- common/rpc/interceptor/telemetry_test.go
Add more action metrics for schedules and updates
**Why?**
Add more actions
eye_balls
No
No
> Add action metrics for schedule and updates

- common/persistence/sql/sqlplugin/visibility.go
- common/persistence/visibility/manager/visibility_manager.go
- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/sql/visibility_store.go
- common/persistence/visibility/store/visibility_store.go
- common/persistence/visibility/visibility_manager_impl.go
- common/searchattribute/defs.go
- service/history/visibility_queue_task_executor.go
- service/history/visibility_queue_task_executor_test.go
- tests/advanced_visibility_test.go
Store parent workflow execution in visibility
**Why?**
Added integration test
> Store parent workflow execution in visibility

- common/archiver/filestore/query_parser.go
- common/archiver/gcloud/query_parser.go
- common/archiver/s3store/query_parser.go
- common/persistence/visibility/store/elasticsearch/converter.go
- common/persistence/visibility/store/query/converter.go
- common/persistence/visibility/store/query/interceptors_test.go
- common/persistence/visibility/store/sql/query_converter.go
- common/persistence/visibility/store/sql/query_converter_mysql.go
- common/persistence/visibility/store/sql/query_converter_mysql_test.go
- common/persistence/visibility/store/sql/query_converter_postgresql.go
- common/persistence/visibility/store/sql/query_converter_postgresql_test.go
- common/persistence/visibility/store/sql/query_converter_sqlite.go
- common/persistence/visibility/store/sql/query_converter_sqlite_test.go
- common/persistence/visibility/store/sql/query_converter_test.go
- common/persistence/visibility/store/sql/query_converter_util.go
- common/persistence/visibility/store/standard/converter.go
- common/worker_versioning/worker_versioning.go
- develop/buildkite/third_party_deps.txt
- go.mod
- go.sum
- service/frontend/task_reachability.go
Replace xwb1989/sqlparser with forked temporalio/sqlparser
**Why?**
Unit tests
No.
No.
> Replace xwb1989/sqlparser with forked temporalio/sqlparser

- README.md
- docs/README.md
- docs/history-service.md
- docs/matching-service.md
- docs/workflow-lifecycle.md
- service/history/README.md
- Initial draft of system architecture / internal implementation docs for
- History Service
- Temporal overview
Links to rendered Markdown for review:
- [Temporal overview](https://github.com/dandavison/temporalio-temporal/tree/docs-history-service/docs)
- [History Service](https://github.com/dandavison/temporalio-temporal/blob/docs-history-service/docs/history-service.md)
- [Workflow Lifecycle](https://github.com/dandavison/temporalio-temporal/blob/docs-history-service/docs/workflow-lifecycle.md) [based on @yiminc's diagrams]
- No
> Initial docs draft: Overview, History Service, Workflow Lifecycle

- tests/namespace_interceptor_test.go
one test case added
**Why?**
cover requirement
run test, made sure that when assertion is incorrect the test will fail
no impact
No
> Add test to verify that NamespaceValidator will reject request if namespace name from task does not match name from request

- tests/dlq_test.go
- tools/tdbg/dlq_service.go
- tools/tdbg/dlq_v1_service.go
- tools/tdbg/dlq_v2_service.go
- tools/tdbg/flags.go
- tools/tdbg/tdbg_commands.go
- tools/tdbg/util.go
adding a command list for DLQ v2 in tdbg.
**Why?**
This command will help operators to find the DLQs that have messages.
Test with 100% coverage.
> Adding list queues command to tdbg

- docs/history-service.md
Fix some links that were accidentally given a commit hash from the wrong repo in #4950.
> Fix some broken links

- schema/elasticsearch/visibility/index_template_v7.json
- schema/elasticsearch/visibility/versioned/v6/index_template_v7.json
- schema/elasticsearch/visibility/versioned/v6/upgrade.sh
Add parent execution search attributes to ES mappings
**Why?**
PR https://github.com/temporalio/temporal/pull/5054 modified the SQL schemas to add parent execution to visibility. This one does for ES.
Unit Tests.
No.
No.
> Add parent execution search attributes to ES mappings

- tests/add_tasks_test.go
- tests/dlq_test.go
- tests/xdc/history_replication_dlq_test.go
I made all the variables that are accessed by multiple goroutines atomic in all the DLQ functional tests.
**Why?**
Initially, I left these as non-atomic types because I assumed that there would be no workflows running before the tests were started, but that's not true because, as soon as the server starts, there could be system workflows running like the history scanner, and that means they could read variables that our overriden task executor uses while the test itself is writing them.
Initially, the only race condition detected was in `add_tasks_test`, but I went through the other DLQ integration tests because they have similar implementations. I didn't run something like `go test -count 1000 ...` because that doesn't work with our functional …
> Fix race conditions in DLQ integration tests

- common/log/tag/tags.go
- develop/docs/dlq.md
- service/history/queues/dlq_writer.go
- service/history/queues/dlq_writer_test.go
- service/history/queues/queuestest/fake_queue_writer.go
Adding documentation on how to deal with messages that are added to DLQs.
**Why?**
This will help operators to find messages in DLQ, the reason why it got enqueued into DLQ etc.
It also has useful tdbg commands for deleting or re-enqueuing the messages from DLQ
> Adding documentation for dealing with DLQ messages

- service/history/workflow/retry.go
- service/history/workflow/retry_test.go
Long test split into list of shorter ones. I notice that descriptions in the tests do not correspond to what is test. I extracted backoff interval calculation from getBackoffInterval for easier testability. I will rewrite the tests next. 
**Why?**
so I can run each test case individually
run tests
none
no
> split long retry test into number of smaller ones

- common/headers/version_checker.go
^
We need to do this on main _before_  we cut 1.23.0-rc1
> Bump server version to 1.23.0

- service/frontend/redirection_interceptor.go
This allows us to differentiate between normal API call vs redirected API call on the server.
> Append xdc-redirection-api header to redirect request

- service/frontend/operator_handler.go
- service/frontend/operator_handler_test.go
When adding custom search attributes, filter out the existing ones from the request instead of returning an error.
Be able to add custom search attributes to secondary visibility when there's already a primary visibility with custom search attributes (ie, be able to sync custom search attributes).
Rewrote unit tests.
No.
No.
> Filter out existing search attributes when adding new ones

- common/persistence/visibility/store/sql/query_converter.go
Return invalid SQL syntax error to user.
Return user error.
PR: https://github.com/temporalio/temporal/issues/4978
PR repro steps return correct error.
No.
No.
> Return invalid SQL syntax error to user

- .github/workflows/create-tag.yml
- common/headers/version_checker.go
Github action to create a tag and it will update the Server version in `common/headers/version_checker.go` before tagging.
Automate tagging.
Ran the workflow locally
No.
No.
> Github action workflow to create tag

- .github/workflows/features-integration.yml
Fix permissions in features-integration GHA
> Fix permissions in features-integration GHA

- develop/docker-compose/docker-compose.cdc.yml
- develop/docker-compose/docker-compose.yml
Confirmed UI is at new version when served via docker-compose project.
> Update ui-server version in docker-compose files

- tests/cron.go
Adjusted cron test times to make it less prone to flakiness.
Test was flaky in certain persistence tests.
Ran the test and it didn't fail so far.
No.
No.
> Fix cron flaky test

- common/persistence/client/health_request_rate_limiter.go
Fix data race in `HealthRequestRateLimiterImpl`.
Data race identified in https://github.com/temporalio/temporal/actions/runs/7468305186/job/20325169296
Unit tests
No.
No.
> Fix data race in HealthRequestRateLimiterImpl

- common/dynamicconfig/constants.go
- service/history/configs/config.go
- service/history/replication/executable_history_task.go
- service/history/replication/executable_history_task_test.go
- tests/ndc/replication_migration_back_test.go
Add replicate local generated history events feature and gated with dynamic config
To support replicate events that generated by current cluster
Unit test and new integration test added
N/a
no
> Add replicate local generated history events feature

- service/frontend/fx.go
Related: https://github.com/temporalio/temporal/pull/5293
> Change auth order

- tests/signal_workflow.go
- tests/sizelimit.go
- tests/workflow_delete_execution.go
- tests/workflow_memo.go
- tests/workflow_visibility.go
Change tests querying ES to use `s.Eventually` instead of sleeping.
Less flakiness
Run tests.
No.
No.
> Refactor functional tests query ES to use s.Eventually

- common/dynamicconfig/constants.go
- common/persistence/visibility/defs.go
- service/frontend/dc_redirection_policy_test.go
- service/frontend/fx.go
- service/frontend/redirection_interceptor_test.go
- service/frontend/service.go
- service/frontend/workflow_handler_test.go
- service/history/configs/config.go
- service/history/fx.go
- service/history/queue_factory_base_test.go
- service/history/replication/stream_receiver_monitor_test.go
- service/history/tests/vars.go
- service/history/workflow_task_handler_test.go
- service/matching/config.go
- service/matching/fx.go
- service/matching/matcher_test.go
- service/matching/matching_engine_test.go
- service/matching/task_queue_manager_test.go
- service/worker/fx.go
- service/worker/service.go
- tests/dynamicconfig.go
- tests/onebox.go
Removing deprecated Visiblity dynamic configs.
They have been replaced with new ones.
People need to update their configs if they are using the old keys.
No.
> Clean up deprecated Visibilty dynamic configs

- internal/temporalite/freeport.go
- internal/temporalite/lite_server.go
In the description
I want to use this for Nexus callback tests
Not relevant
> Expose PortProvider from internal/temporalite

- common/log/tag/tags.go
- service/history/configs/config.go
- service/history/handler.go
- service/history/replication/stream_receiver.go
- service/history/replication/stream_receiver_monitor_test.go
- service/history/replication/stream_receiver_test.go
- service/history/replication/stream_sender.go
- service/history/replication/stream_sender_test.go
Add more tags for replication stack logs
To get more visibility especially when multiple clusters are connected
unit test
N/a
No.
> Add tags for replication stack logs

- service/worker/scheduler/activities.go
- service/worker/scheduler/spec.go
- service/worker/scheduler/spec_test.go
minor refacoring
I was refactoring while trying to understand the code, I think it will help other fellow developers to easier understand what is going on.
Run the tests.
Schedules will not work correctly.
No.
> Minor refactoring for readability

- common/dynamicconfig/constants.go
- common/persistence/visibility/defs.go
- common/searchattribute/validator.go
- common/searchattribute/validator_test.go
- service/frontend/service.go
- service/frontend/workflow_handler.go
- service/history/command_checker_test.go
- service/history/configs/config.go
- service/history/history_engine.go
- service/history/history_engine2_test.go
- service/history/workflow_task_handler_callbacks_test.go
Dynamic config to allow list of values for single value search attribute types.
Able to allow per namespace, ease migration.
No.
No.
> Dynamic config to allow list of values in search attributes

- .github/workflows/run-tests.yml
Run GHA workflow to run tests on PR's and release branches
Replace buildkite eventually.
> Run GHA tests on PRs and release branches

- common/dynamicconfig/constants.go
- service/history/configs/config.go
- Clean up unused queue processor configs
- Clean up unused queue processor configs
- Compile code
- N/A
- No.
> Clean up unused queue processor configs

- common/metrics/metric_defs.go
- service/history/ndc_task_util.go
- service/history/transfer_queue_active_task_executor.go
- Clean up unused queue processor metric scope
- Clean up unused queue processor metric scope
- Compile code
- N/A
- No
> Clean up unused queue processor metric scope

- common/namespace/replication_task_executor.go
- common/namespace/transmission_task_handler.go
1. Update logging in namespace replication error
Debugging
> Add logging in namespace replication error

- common/dynamicconfig/constants.go
- common/metrics/metric_defs.go
- service/history/configs/config.go
Prep work for Nexus callbacks.
> Add metrics and dynamic config constants for callbacks

- .github/workflows/run-tests.yml
Make sure "All Tests" run on PRs against this feature branch
> update run-tests pipeline from main

- common/dynamicconfig/constants.go
- common/log/tag/tags.go
- common/persistence/serialization/serializer.go
- common/persistence/visibility/store/elasticsearch/client/client.go
- common/persistence/visibility/store/elasticsearch/client/client_mock.go
- common/persistence/visibility/store/elasticsearch/client/client_v7.go
- service/history/archival_queue_factory.go
- service/history/configs/config.go
- service/history/queues/executable.go
- service/history/queues/executable_factory.go
- service/history/queues/executable_mock.go
- service/history/queues/executable_test.go
- service/history/queues/queue_base_test.go
- service/history/queues/queue_scheduled_test.go
- service/history/timer_queue_factory.go
- service/history/transfer_queue_factory.go
- service/history/visibility_queue_factory.go
- tests/test_cluster.go
> Cherry pick PRs for cr7

- .github/workflows/run-tests.yml
Add test status job to indicate if the tests were successful or not.
Easy to make tests a required check for merging PR
> Add test status job to GHA workflow

- tests/client_suite.go
> Fix flaky Test_InvalidCommandAttribute

- service/history/queues/executable.go
- service/history/queues/executable_test.go
I added back some metrics that were removed from DLQ writes when we removed the Executable DLQ Wrapper in #5033 
These were removed by mistake.
The more important metric, "dlq_writes" still exists, and that's what the docs reference for operators, so we're ok that these other ones were missed.
> Fix missing DLQ metrics

- common/testing/testvars/any.go
- common/testing/testvars/hash.go
- common/testing/testvars/rand.go
- common/testing/testvars/test_vars.go
- tests/update_workflow_test.go
Move `testvars` package to `common/testing`.
Need to use it outside of functional tests.
Run tests.
No risks.
No.
> Move testvars package to common/testing

- common/testing/historyrequire/history_require.go
- tests/activity.go
- tests/cancel_workflow.go
- tests/continue_as_new.go
- tests/functional.go
- tests/functional_test_base.go
- tests/sizelimit.go
Extract `historyrequire` package.
I plan to use this package outside of functional tests. There are still places with another custom code to assert on histories and I will replace it later.
Run tests locally.
No risks.
No.
> Extract historyrequire package

- common/testing/protoutils/any.go
- common/testing/runtime/goroutine.go
- tests/functional.go
- tests/update_workflow_test.go
Extract `common/testing/protoutils` package.
I plan to use this package outside of functional tests.
Run tests.
No risks.
No.
> Extract protoutils package

- common/testing/updateutils/update.go
- tests/functional.go
- tests/update_workflow_test.go
Extract `common/testing/updateutils` package.
Will be used outside of functional tests.
Run tests locally.
No risks.
No.
> Extract updateutils package

- common/testing/testvars/const.go
- common/testing/testvars/test_vars.go
- service/history/workflow_task_handler_callbacks_update_test.go
Unit tests for workflow update for `handleWorkflowTaskCompleted`.
Basic code coverage for `handleWorkflowTaskCompleted` when request has workflow update messages.
Run locally.
No risks.
No.
> Unit tests for workflow update for handleWorkflowTaskCompleted

- service/frontend/workflow_handler.go
unaliasXXXRequestSearchAttributes inlined and unaliasedAttributesFrom extracted
Number of similar functions can be merged into one.
Automated tests.
None
Yes.
No.
> Clearing The Way for UpdateSchedule 

- common/persistence/persistence-tests/persistence_test_base.go
- common/persistence/persistence-tests/setup.go
- common/persistence/sql/sqlplugin/mysql/db.go
- common/persistence/sql/sqlplugin/mysql/plugin.go
- common/persistence/sql/sqlplugin/postgresql/db.go
- common/persistence/sql/sqlplugin/postgresql/plugin.go
- common/persistence/tests/mysql_test.go
- common/persistence/tests/mysql_test_util.go
- common/persistence/tests/postgresql_test.go
- common/persistence/visibility/defs.go
- common/persistence/visibility/factory.go
- common/persistence/visibility/store/sql/query_converter_factory.go
- common/persistence/visibility/visibility_manager_test.go
- service/frontend/operator_handler_test.go
- service/worker/deletenamespace/reclaimresources/activities.go
- tests/flag.go
- tests/test_cluster.go
- tools/sql/main.go
- tools/tests/mysql_cli_test.go
- tools/tests/postgresql_cli_test.go
- tools/tests/test_data.go
Rename vars related to visibility.
Ease to read code.
No.
No
> Refactor var names related to visibility mysql8 and postgres12

- service/matching/incoming_nexus_service_manager.go
- tests/nexus_incoming_service_test.go
Fixing a few tests and a data race with Nexus incoming services
> fix tests and race

- service/frontend/workflow_handler.go
- service/worker/scheduler/workflow.go
- tests/schedule.go
Partial revert of commit #5447 (7f11cae45).
We're going to implement it in a slightly different way and want to do a release from main without having to retain this specific workflow logic.
existing tests
> Partial revert of #5447

- service/history/history_engine2_test.go
Added a test for Start Workflow + Terminate-if-Running.
Also refactored the existing test cases to make them more explicit, have less duplication, less clever looping.
Adding a test for Terminate-if-Running behavior for changing its behavior in an upcoming PR (related to https://github.com/temporalio/api/pull/359). 
Is test.
> Add Terminate-if-Running test

- .github/workflows/golangci-lint.yml
- .github/workflows/goreleaser.yml
- .github/workflows/run-tests.yml
Update GHA actions version
Old versions use node16 which reached EOL. New versions use node20.
> Update GHA actions version

- common/persistence/visibility/store/elasticsearch/query_interceptors.go
- common/persistence/visibility/store/elasticsearch/query_interceptors_test.go
- common/persistence/visibility/store/sql/query_converter.go
- common/persistence/visibility/store/sql/query_converter_test.go
- common/primitives/timestamp/parse_duration_test.go
Fix parse duration error type to be a ConverterError.
If the parsing failed, it's an issue with user input, not an internal error.
Added tests to make sure errors returned by this function is always a ConverterError.
> Fix parse duration error type

- api/persistence/v1/namespaces.pb.go
- common/collection/sorted_set_manager.go
- common/collection/sorted_set_manager_test.go
- common/nexus/outgoing_service_registry.go
- common/nexus/outgoing_service_registry_test.go
- common/rpc/request_issues.go
- common/rpc/request_issues_test.go
- common/rpc/test/rpc_localstore_tls_test.go
- proto/internal/temporal/server/api/persistence/v1/namespaces.proto
- tests/outgoing_service_registry_test.go
I reviewed the Nexus outgoing service registry code and found a few issues that this PR cleans up. None of them are functional, just performance / code structure.
> Refactor nexus.OutgoingServiceRegistry

- go.mod
- go.sum
Update Go SDK to official release v1.26.0
> Update Go SDK to official release

- .github/workflows/create-tag.yml
I updated our release notes template
To match how we actually format them, and to remove the commit list
> Improve our release notes template

- common/log/tag/tags.go
- service/history/workflow/context.go
- service/history/workflow/context_test.go
- tests/dynamicconfig.go
- Fix UpdateWithNew replication task merging logic
- Enable UpdateWithNew replication task merge in function tests
- Some sanity check in the logic is not valid
- Test new code path in functional tests
- Added unit tests.
- Existing ndc tests
- N/A
- N/A
- No
> Fix UpdateWithNew replication task merging logic

- service/history/workflow/context.go
- service/history/workflow/context_test.go
- Same as https://github.com/temporalio/temporal/pull/5592, fix some more cases.
- Those sanity check logic is not correct and those cases will be generated by the rest of the stack.
- Added new unit tests.
- N/A
- N/A
- No.
> Fix UpdateWithNew replication task merging logic 2

- service/history/queues/metrics.go
Fix metrics tag for in-memory queue.
In-memory queue `switch` was placed under wrong `case` statement by mistake.
Didn't test.
No risks.
No.
No.
> Fix metrics tag for in-memory queue

- common/rpc/test/rpc_localstore_tls_test.go
I originally just skipped one of these tests, but it looks like they might all be flaky: https://github.com/temporalio/temporal/actions/runs/8444339584/job/23129768812?pr=5608
> Skip all of TestLocalStoreTLSSuite

- common/metrics/metric_defs.go
- common/persistence/cassandra/nexus_incoming_service_store.go
- common/persistence/client/fault_injection.go
- common/persistence/data_interfaces.go
- common/persistence/data_interfaces_mock.go
- common/persistence/mock/store_mock.go
- common/persistence/nexus_incoming_service_manager.go
- common/persistence/persistence_interface.go
- common/persistence/persistence_metric_clients.go
- common/persistence/persistence_rate_limited_clients.go
- common/persistence/persistence_retryable_clients.go
- common/persistence/sql/nexus_incoming_service_store.go
- common/persistence/sql/sqlplugin/mysql/nexus_incoming_services.go
- common/persistence/sql/sqlplugin/nexus_incoming_services.go
- common/persistence/sql/sqlplugin/postgresql/nexus_incoming_services.go
- common/persistence/sql/sqlplugin/sqlite/nexus_incoming_services.go
- common/persistence/tests/nexus_incoming_service_suite.go
Added a new persistence layer API to get a Nexus incoming service by service ID.
To align with new API requirements
Updated existing tests
> Add GetNexusIncomingService persistence API

- common/persistence/client/persistence_rate_limited_clients_test.go
- common/persistence/persistence_rate_limited_clients.go
There was a compilation error in a previous commit that broke build.
Fixing that
Fixing build
Unit test
None
No
> Fixing build

- common/rpc/grpc.go
- service/frontend/fx.go
- tests/client_suite.go
Return Unavailable error (grpc code Unavailable) instead of ShardOwnershipLost (grpc code Aborted)
**Why?**
ShardOwnershipLost is server internal issue, this is unavailable from client point of view.
> Return unavailable from frontend instead of ShardOwnershipLost

- .github/workflows/golangci-lint.yml
- Makefile
Update golangci-lint version to v1.57.2.
Version v1.53.3 doesn't seem to work properly locally sometimes (it's crashing in another PR).
This latest version didn't crash on the other PR I'm working on.
No.
No.
> Update golangci-lint version

- common/namespace/replication_task_executor.go
- common/util.go
- config/development-cluster-a.yaml
- config/development-cluster-b.yaml
- config/development-cluster-c.yaml
- develop/docker-compose/docker-compose.cdc.darwin.yml
- service/history/api/getworkflowexecutionhistory/api.go
- service/history/historybuilder/event_store.go
- service/history/historybuilder/history_builder_test.go
- service/history/workflow/update/update.go
Miscellaneous edits of comments and docstrings
> Comments and docstrings

- common/dynamicconfig/constants.go
- service/frontend/errors.go
- service/frontend/service.go
- tests/functional.go
Adding feature flag for new MultiOps API.
To guard the API while it's still under development.
This PR was made ahead of the upcoming API change to make that PR smaller.
> MultiOps API feature flag

- .vscode/launch.json
Pull in a VSCode config from main into feature branch.
For debugging
> Add VSCode debugging to feature branch

- common/metrics/metric_defs.go
- common/metrics/tags.go
- service/frontend/fx.go
- service/frontend/nexus_handler.go
- service/frontend/nexus_http_handler.go
- tests/nexus_api_test.go
Added HTTP handler implementation for dispatching Nexus tasks by service ID
So that Nexus tasks can be dispatched
Updated functional tests
> Implement dispatching Nexus tasks by service ID

- service/history/api/pollupdate/api_test.go
- service/history/api/updateworkflow/api.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
- service/history/workflow/update/state.go
- service/history/workflow/update/update.go
- service/history/workflow/update/update_test.go
- service/history/workflow_task_handler_callbacks_update_test.go
- service/history/workflow_task_handler_test.go
- Rename `stateAdmitted` to `stateCreated`
- Rename `stateRequested` to `stateadmitted`
- Rename `Request` method to `Admit`
To match wait stages and events names.
No risks.
No.
No.
> Rename stateAdmitted to stateCreated

- service/history/archival_queue_task_executor.go
- service/history/ndc_task_util.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_task_executor_base.go
- service/history/transfer_queue_active_task_executor.go
- service/history/transfer_queue_standby_task_executor.go
- service/history/transfer_queue_task_executor_base.go
- service/history/visibility_queue_task_executor.go
- Export CheckTaskVersion util func
- Used in other repos
> Export CheckTaskVersion

- common/archiver/gcloud/connector/client.go
- common/cache/lru.go
- common/log/tag/tags.go
- common/namespace/registry.go
> chore: fix function names in comment

- common/dynamicconfig/constants.go
- tests/onebox.go
Remove unused dynamic config constants 
Preparation for a bunch of dynamic config refactoring
existing tests
> Remove unused dynamic config constants

- common/persistence/sql/sqlplugin/visibility.go
- common/persistence/visibility/manager/visibility_manager.go
- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/sql/visibility_store.go
- common/persistence/visibility/store/visibility_store.go
- common/persistence/visibility/visibility_manager_impl.go
- common/searchattribute/defs.go
- schema/elasticsearch/visibility/index_template_v7.json
- schema/elasticsearch/visibility/versioned/v7/index_template_v7.json
- schema/elasticsearch/visibility/versioned/v7/upgrade.sh
- schema/mysql/v8/version.go
- schema/mysql/v8/visibility/schema.sql
- schema/mysql/v8/visibility/versioned/v1.5/add_root_workflow_info.sql
- schema/mysql/v8/visibility/versioned/v1.5/manifest.json
- schema/postgresql/v12/version.go
- schema/postgresql/v12/visibility/schema.sql
- schema/postgresql/v12/visibility/versioned/v1.5/add_root_workflow_info.sql
- schema/postgresql/v12/visibility/versioned/v1.5/manifest.json
- schema/sqlite/v3/visibility/schema.sql
- service/history/visibility_queue_task_executor.go
- service/history/visibility_queue_task_executor_test.go
- tests/advanced_visibility.go
Add root workflow execution to Visibility
Follow up of https://github.com/temporalio/temporal/pull/5520.
Be able to list all workflows based on the root execution.
Modified existing tests to check the root workflow execution.
No.
No.
> Add root workflow execution to visibility

- common/dynamicconfig/constants.go
- service/frontend/errors.go
- service/frontend/service.go
- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
- tests/dynamicconfig.go
Removed feature flag for WorkflowIdConflictPolicy.
The feature flag only existed to make sure we address the internal billing changes first; which are now complete.
The feature is fully tested; but there is no SDK support yet.
> Remove WorkflowIdConflictPolicy feature flag

- common/dynamicconfig/constants.go
- service/frontend/service.go
- service/frontend/workflow_handler.go
- tests/callbacks_test.go
Validate callback URL length.
Prevent very long URL.
Added test.
No.
> Validate callback URL length

- service/history/configs/config.go
- tests/ndc/ndc_test.go
Enable streaming replication by default.
Tested locally.
> enable streaming replication by default

- service/history/workflow_task_handler_callbacks.go
Log info message when effects are cancelled.
To improve debugging expirience.
N/A
No risks.
No.
No.
> Log info message when effects are cancelled

- environment/env.go
Fixing a typo in a comment 🕵️
No
> Fixing a typo in a comment, no code changes

- service/frontend/workflow_handler.go
Extracted the validation of the Start Workflow operation into its own function.
To re-use it for the MultiOperation in an upcoming PR.
Unless I overlooked anything, there's no behavior change.
> extract Start Workflow validation

- service/frontend/workflow_handler.go
Extracted the validation of the Start Workflow operation into its own function.
To re-use it for the MultiOperation in an upcoming PR.
> extract Update Workflow validation

- common/dynamicconfig/constants.go
- common/persistence/client/fx.go
- common/persistence/client/persistence_rate_limited_clients_test.go
- common/persistence/client/quotas.go
- service/frontend/fx.go
- service/frontend/service.go
- service/fx.go
- service/history/configs/config.go
- service/history/fx.go
- service/matching/config.go
- service/matching/fx.go
- service/worker/fx.go
- service/worker/service.go
- temporal/fx.go
- temporal/server_impl.go
- Deprecate persistence priority rate limiting flag
- Those flags have been enabled by default for several releases and is stable.
- Won't be able to disable the feature in prod.
- N/A
- No.
> Deprecate persistence priority rate limiting flag

- service/history/workflow/update/registry.go
Rename update registry `admit` method to `checkLimits`.
Leftover from `stateAdmitted` to `stateCreated`.
Build.
No risks.
No. 
No.
> Rename update registry admit method

- go.mod
- go.sum
- service/frontend/errors.go
- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
- tests/workflow.go
Added Frontend validation for MultiOperationExecution requests.
What _hasn't_ changed (yet): History validation and per-operation Frontend validation.
To make sure MultiOperationExecution request is valid before passing it to History.
Added tests.
> Add MultiOperation frontend validation

- .github/workflows/create-tag.yml
Add option to update dependencies after creating a release
Prevent having stale dependencies.
> Add option to update dependencies after creating a release

- develop/docker-compose/docker-compose.yml
Update temporalio/ui docker image version
New ui features.
> Update temporalio/ui docker image version

- service/matching/physical_task_queue_manager.go
Add one more place where we check tasks for expiration: We already check in taskReader when we read from persistence before adding to the buffer, in physicalTaskQueueManager.ProcessSpooledTask after it comes out of the buffer, and in history at record started. This adds a check after a task comes out of a matcher, before it's passed to record started on history.
This is intended to catch a task that expires while being blocked in the matcher. It saves an rpc in that (rare) situation, and it also makes some of @alexshtin 's tests more reliable.
Existing unit+functional tests. I'll try to add a new unit test specifically for this after merging.
> Test for task expiration after matching

- .github/workflows/run-tests.yml
Follow up to #5815.
Same as #5815.
N/A
Cass+ES8 is not covered by xdc functional tests.
No.
No.
> Temporary disable xdc functional tests over Cass+ES8 persistence

- service/history/workflow/update/update.go
Check if update still in provisional state before commit.
If update got another terminal state (i.e. aborted) after it was set to `stateProvisinallyAccepted`, `OnCommit` callback will transition it to `stateAccepted`, which is wrong.
Non-provisional states must be set only from corresponding provisional states.
No risks.
No.
No.
> Workflow Update: check if update still in provisinal state before commit

- service/history/workflow/update/registry.go
- service/history/workflow/update/state.go
- service/history/workflow/update/update.go
Workflow Update: remove unused `UpdateFromStore` method.
After #5792 is merge `UpdateFromStore` method is not used and therefore can be removed.
No risks.
No.
No.
> Workflow Update: remove unused UpdateFromStore method

- service/history/workflow_task_handler_callbacks.go
> Release WF lock before returning build ID mismatch error

- service/history/api/pollupdate/api_test.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
- service/history/workflow/update/state.go
- service/history/workflow/update/update.go
- service/history/workflow/update/update_test.go
- service/history/workflow_task_handler.go
- service/history/workflow_task_handler_callbacks.go
- service/history/workflow_task_handler_callbacks_update_test.go
- service/history/workflow_task_handler_test.go
Simplify `update.Registry` interface:
- `Send` doesn't need `Store`
- `RejectUnprocessed` uses `effect.Controller` instead of `Store`
- State `stateProvisionallySent` is removed.
Remove unneeded complexity.
No risks.
No.
No.
> Workflow Update: simplify update.Registry interface

- service/frontend/workflow_handler.go
- service/history/api/multioperation/api.go
- service/history/api/startworkflow/api.go
- service/history/history_engine.go
- tests/workflow.go
Added support for workflow id conflict policies "terminate-existing" and "fail".
Complement the support for policy "use-existing".
Added new tests.
> MultiOperation support for terminate/fail conflict policy

- service/history/api/updateworkflow/api.go
Check is workflow is closing before admitting new update.
If workflow attempted to close itself on previous WFT completion, and has another WFT running, which most likely will try to complete workflow again, then don't admit new updates.
Also for consistency with signals.
Need to add new test.
No risks.
No.
No.
> Workflow Update: check is workflow is closing before admitting new update

- common/metrics/metric_defs.go
- service/frontend/workflow_handler.go
- service/history/api/updateworkflow/api.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/update.go
- service/history/workflow/update/util.go
Add a handful of helpful metrics/logs for UpdateWorkflowExecution.
To monitor feature in production better.
> Add additional Update Workflow metrics/logs

- service/history/api/deleteworkflow/api.go
- service/history/api/terminateworkflow/api.go
- service/history/api/update_workflow_util.go
- service/history/api/workflow_id_dedup.go
- service/history/api/workflow_lease.go
- service/history/ndc/workflow.go
- service/history/ndc/workflow_resetter.go
- service/history/timer_queue_active_task_executor.go
- service/history/workflow/context.go
- service/history/workflow/update/abort_reason.go
- service/history/workflow/util.go
- service/history/workflow_task_handler_callbacks.go
- tests/update_workflow.go
Abort all updates if workflow is terminated or timed out.
For better DX. W/o this PR updates will just timeout.
Need to add tests.
No risks.
No.
No.
> Workflow Update: abort all updates if workflow is terminated or timed out

- service/history/workflow/update/update_test.go
Rename `Requested` to `Admitted` state in unit tests.
Leftover after state renames.
N/A
No risks.
No.
> Workflow Update: rename Requested to Admitted state in unit test

- service/history/api/queryworkflow/api.go
Changing the order in which we check if the workflow has a WorkflowTaskStartedEvent and if the workflow has WorkflowTaskScheduled event.
It is better to have these checks in this order. Now the first condition checks if workflow has terminated before WorkflowTaskStartedEvent has been added.
This is needed as some SDKs will not be able to handle this condition. Refer: https://github.com/temporalio/temporal/pull/4867
Second condition checks if workflow is yet to have a WorkflowExecutionScheduled event. This can happen when a query has arrived before this event and this query can be retried after a while.
TestQueryWorkflow_ClosedWithoutWorkflowTaskStarted was also failing occasionally with this error.
```
Error "Workflow task is not scheduled yet." does not contain "Workflow execution closed …
```
> Fixing order of validations for QueryWorkflow

- tests/versioning.go
- Remove dependence on difference between cache TTL and visibility delay
- Make test cache TTL short so that test goes quickly
The variability in visibility delay was making it flake a lot 
Functional tests
Removes a bit of test coverage that will be moved into unit tests
> Fix reachability test flake: remove dependence on difference between cache TTL and visibility delay

- cmd/tools/gendynamicconfig/main.go
- common/dynamicconfig/collection.go
- common/dynamicconfig/collection_test.go
- common/dynamicconfig/config/testConfig.yaml
- common/dynamicconfig/file_based_client_test.go
- common/dynamicconfig/setting_gen.go
Replace namespace id with namespace name in destination dynamic config
Easier to reference namespace name instead of id.
> Replace namespace id with namespace name in destination dynamic config

- common/quotas/calculator/logged_calculator.go
- common/quotas/calculator/logged_calculator_test.go
- Add namespace tag in quota calculator
- Add namespace tag in quota calculator
> Add namespace tag in quota calculator

- service/history/api/pollupdate/api.go
- service/history/api/pollupdate/api_test.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
- service/history/workflow_task_handler.go
Removed superfluous return value from Update registry's `Find` method.
It's not needed.
> Simplify Update Registry interface

- service/worker/deletenamespace/deleteexecutions/workflow_test.go
Reenable `Test_DeleteExecutionsWorkflow_ManyExecutions_NoContinueAsNew` test.
Test was disabled in #3699 due to race condition. I used `atomic` and it constatnly passed.
```
go test ./service/worker/deletenamespace/deleteexecutions -race -count 100  -json | jq -s 'map(select(.Action == "fail" and .Test))'
```
> Reenable Test_DeleteExecutionsWorkflow_ManyExecutions_NoContinueAsNew test

- tests/update_workflow.go
Fix flaky `TestUpdateWorkflow_StaleSpeculativeWorkflowTask_ClearMutableState_Accepted` test and some minor improvements.
It is obvious.
> Fix flaky TestUpdateWorkflow_StaleSpeculativeWorkflowTask_ClearMutableState_Accepted test

- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_active_task_executor_test.go
- Fix activity failure message upon retry timeout
- https://github.com/temporalio/temporal/issues/5914
- Unit test
> Fix activity failure message upon retry timeout

- .github/workflows/create-tag.yml
Update dependencies from main branch.
The workflow step to update dependencies should update in main branch.
> GHA workflow: Update dependencies from main branch

- service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/update.go
- tests/update_workflow.go
Resurrect update request from Acceptance and Rejection message.
Better developer experience in case of shard moves, server restarts, or any other transient errors.
Modified tests.
No risks.
No.
Maybe for 1.24.0.
> Workflow Update: resurrect update request from Acceptance and Rejection message

- .github/workflows/run-tests.yml
Run tests in cloud branch
Verify cherry picked commits in cloud branch are good.
> Run tests in cloud branch

- tests/versioning.go
> Fix flaky TestFirstWorkflowTaskAssignment_SyncMatch

- cmd/tools/gendynamicconfig/main.go
- common/dynamicconfig/setting_gen.go
Generate type aliases for typed dynamic configs
It's missing aliases so dynamic config function types can be easily referenced.
> Generate type aliases for typed dynamic configs

- docs/Makefile
- docs/_assets/matching-context.svg
- docs/_assets/retries.d2
- docs/_assets/retries.svg
- docs/architecture/retry.md
Added a diagram to the retries.md docs.
To make it clearer what's going on.
> Tweak retry documentation

- common/persistence/history_manager.go
I updated all our `corrupted history event batch` errors and log messages to have the exact same wording.
With this change we can paste the error into our log aggregator and find the preceding log with additional context
I didn't
None
No
No
> Standardize messages for corrupt history event batches

- components/callbacks/executors.go
- components/callbacks/executors_test.go
- components/callbacks/fx.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- service/history/hsm/registry.go
- service/history/outbound_queue_active_task_executor.go
- service/history/outbound_queue_factory.go
- service/history/outbound_queue_standby_task_executor.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_standby_task_executor.go
Base implementation of the outbound standby task executor
> Outbound standby task executor base

- common/testing/testvars/test_vars.go
- service/history/api/respondworkflowtaskcompleted/api_test.go
- tests/client_suite.go
- tests/reset_workflow.go
- tests/update_workflow.go
- tests/update_workflow_sdk.go
- tests/user_metadata_test.go
- tests/workflow.go
- tests/workflow_delete_execution.go
- tests/xdc/history_replication_signals_and_updates_test.go
Changed initialization of testvars from
```
tv := testvars.New(s.T().Name())
```
to
```
tv := testvars.New(s.T())
```
Less typing.
> Use testing.T to initialize testvars

- CONTRIBUTING.md
- docs/development/testing.md
Create new `testing.md` with test-specific developer guidance.
It's still very short, happy to add anything else now if there is any - or just grow it over time.
To document testing patterns and agreements.
> Testing docs

- service/history/workflow/update/registry_test.go
> Fix flaky update registry test TestAbort

- common/persistence/tests/sqlite_test.go
Fix SQLite Test setup
Flaky test
> Fix SQLite Test setup

- service/matching/nexus_endpoint_client.go
Made a shallow copy of entries returned by ListNexusEndpoints
To avoid a data race in the gRPC handler
Existing functional tests
> Clone Nexus endpoint entries before returning

- tests/taskpoller.go
- tests/update_workflow.go
Refactor Workflow Update functional tests:
- Removed wrongly used `WithForceNewWorkflowTask` flag which should be used only for heartbeat
- Gave tests better names.
- Remove unrelated test code.
Make tests better.
Run tests.
No risk.
No.
No.
> Workflow Update: refactor functional tests

- common/metrics/tags.go
- components/callbacks/config.go
- components/callbacks/executors.go
- components/callbacks/executors_test.go
- components/callbacks/metrics.go
- components/callbacks/statemachine.go
- components/callbacks/statemachine_test.go
- components/nexusoperations/config.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/nexusoperations/metrics.go
- components/nexusoperations/statemachine.go
- components/nexusoperations/statemachine_test.go
- service/history/outbound_queue_factory.go
- service/history/workflow/task_generator_test.go
- [Add nexus/callback executor metrics and minor comment](https://github.com/temporalio/temporal/commit/e2b47334f79ce1373a9e28087584f30953073489)
- [Make callback/nexus operation retry policy configurable](https://github.com/temporalio/temporal/commit/9dae5870a79c228c28b22f7022a4c5bcbfbd8ba3)
> Misc Nexus work

- service/frontend/admin_handler.go
- service/frontend/admin_handler_test.go
Close admin server stream after erroring
Close admin server stream after erroring
> Close admin server stream after erroring

- tests/update_workflow.go
Fix flakiness of `TestUpdateWorkflow_FirstNormalScheduledWorkflowTask_AcceptComplete` test.
Falkiness is bad.
> Workflow Update: fix flaky functional test

- service/history/api/pollupdate/api_test.go
- service/history/api/respondworkflowtaskcompleted/api_test.go
- service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler.go
- service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler_test.go
- service/history/api/updateworkflow/api.go
- service/history/workflow/update/export_test.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
- service/history/workflow/update/update.go
- service/history/workflow/update/update_test.go
- revamped the `update_test.go` tests from the ground up
- removed unnecessary `context.Context` parameters
Ensure high test coverage (and remove duplicate tests).
There are no behavioral changes.
> Revamp Update package's unit tests (2/2)

- service/frontend/workflow_handler.go
Add simple validation for batch reset type in frontend.
Note this only validates that it's a known enum value, so that we don't have to change this whenever we add new reset types to the batch worker.
Eager validation is better. Invalid requests would end up as errors in the batch workflow, which are less visible and operationally noisy.
didn't
> Validate batch reset type in frontend

- common/metrics/metric_defs.go
- service/history/workflow/task_generator.go
- service/history/workflow/workflow_task_state_machine.go
Added new metric `workflow_task_convert_speculative_to_normal`.
To track conversion from speculative to normal WFT per namespace.
> Track converted speculative workflow tasks

- .github/workflows/run-tests.yml
- Makefile
- develop/upload-test-results.sh
Uploading test results to Buildkite for analytical purposes.
⚠️ This will not work for any PR from a fork (Temporal developer or not), due to GitHub's security model. It has to be a branch on this repo to run successfully (includes `main`, ofc).
To be able to analyze test flakiness.
Ran this PR and saw test run in Buildkite.
> Track flaky tests (redux)

- service/worker/scheduler/workflow.go
- service/worker/scheduler/workflow_test.go
Bump version to turn on recent workflow changes.
Fix bugs.
existing tests
nondeterminism errors
> Update schedule version to activate #5799 and #6028

- service/matching/matching_engine_test.go
- This seems to be a flaky one and might flake until UpdateState is not an atomic operation
- To not have CI complain on flaky tests
- Current CI
No
> Fixing flaky test which seems to be breaking randomly

- common/persistence/persistence_metric_clients.go
Log the type of persistence error.
If the type of error doesn't fall into the first switch case, we want to know its type.
> Log type of persistence error

- service/history/api/startworkflow/api.go
Fix missing workflow lock release when `LoadMutableState` returns error.
Small regression was introduced in #6097.
Nightly runs will test it.
No risks.
No.
No, code with #6097 is not released yet.
> Fix missing workflow lock release when LoadMutableState returns error

- service/history/replication/stream_sender_flow_controller.go
Fix replication sender rate limiter
There is a bug on usage that will cause the rate/burst not refreshing
test on local xdc
no risk.
n/a
yes but not urgent. Can wait for next release.
> Fix replication sender rate limiter

- components/callbacks/executors.go
- components/callbacks/executors_test.go
- components/callbacks/fx.go
- components/dummy/executors.go
- components/dummy/statemachine.go
- components/dummy/tasks.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/scheduler/executors_test.go
- components/scheduler/fx.go
- service/history/hsm/registry.go
- service/history/outbound_queue_active_task_executor.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_active_task_executor_test.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/timer_queue_task_executor_base.go
- service/history/timer_queue_task_executor_base_test.go
Timer standby executor for state machine tasks.
Added a `dummy` component for unit tests purposes.
> Timer standby executor for state machine tasks

- common/dynamicconfig/constants.go
- common/xdc/ndc_history_resender.go
- common/xdc/ndc_history_resender_test.go
- service/frontend/admin_handler.go
- service/history/configs/config.go
- service/history/replication/dlq_handler.go
- service/history/replication/fx.go
- service/history/replication/task_processor_manager.go
- service/history/timer_queue_factory.go
- service/history/transfer_queue_factory.go
Add batching on resend
To reduce state transition and tasks created during resend
Unit test
No risk.
n/a
yes.
> Add batching on resend

- common/metrics/metric_defs.go
- common/tasks/runnable_scheduler.go
- service/history/outbound_queue_factory.go
Export wait time metric from rate limited task runnable
> Export wait time metric from rate limited task runnable

- common/metrics/metric_defs.go
- common/tasks/dynamic_worker_pool_scheduler.go
- common/tasks/dynamic_worker_pool_scheduler_test.go
- service/history/outbound_queue_factory.go
Add metrics to dynamic worker pool scheduler:
- buffer size
- active workers
> Add metrics to dynamic worker pool scheduler

- components/callbacks/executors.go
- components/callbacks/executors_test.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
Also slightly refactored the callback executor to look more like the nexus operations executor.
> Add error logs for when a nexus or callback request fails

- common/metrics/metric_defs.go
- service/history/outbound_queue_factory.go
- service/history/queues/executable.go
Export metric to track when circuit breaker executable blocks requests
> Export metric to track when circuit breaker executable blocks requests

- service/history/consts/const.go
- service/history/statemachine_environment.go
- service/history/statemachine_environment_test.go
- service/history/timer_queue_active_task_executor_test.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/timer_queue_task_executor_base.go
- Handle zombie workflow in HSM framework
- Zombie workflow can not be updated.
- Unit test
> Handle zombie workflow in HSM framework

- service/history/ndc/workflow_state_replicator.go
Add len check when accessing the slice
To prevent the invalid access case
no risk.
n/a
yes.
> Fix backfillHistory function for reset case

- service/history/history_engine_test.go
- Fix panic in TestRespondActivityTaskFailedUpdateExecutionFailed
- The test is flaky and sometimes pass even when things are wrong
- https://github.com/temporalio/temporal/pull/6145 added Outbound queue to test task category which will be notified on acquireShard, which happens when shard request fail on unknown errors. Since outbound queue was not initialized before this PR, the test can run into an NPE. 
- However, since this queue notification logic happens in a background goroutine, if the test finishes before the notification happens, the test can pass.
> Fix TestRespondActivityTaskFailedUpdateExecutionFailed

- tests/versioning.go
- Fix data race: close worker that appends to `runIds2` before reading from `runIds2` in the validation for-loop
- Replace sleep with `s.Eventually` to make it more clear what the sleep is for exactly
flaky test due to data race
Tested locally, CI passed
Nothing, the test did not materially change.
Commented reason for change, so that we don't change it back and have a regression
No
> fix data race in TestVersioningFunctionalSuite/TestDispatchCron

- components/callbacks/statemachine.go
- components/callbacks/statemachine_test.go
- components/nexusoperations/statemachine.go
- components/nexusoperations/statemachine_test.go
- tests/xdc/nexus_state_replication_test.go
- Fix HSM CompareState impl
- Add xdc functional tests for nexus
- Fix & test hsm state replication
- New functional tests.
- N/A
- N/A
- No.
> Fix HSM CompareState impl

- common/namespace/namespace.go
- Namespace FailoverHistory Getter
- Namespace registry caller may need access to namespace failover history.
> Namespace FailoverHistory Getter

- common/xdc/ndc_history_resender.go
- common/xdc/ndc_history_resender_test.go
Add check for resend Events batch version
ReplicateHistoryEvents api only takes events with same version
Unit test
No risk
n/a
yes
> Add check for resend Events batch version

- .github/workflows/features-integration.yml
Add test status job with final result to features integration tests workflow.
Easy way to add to PR merge requirements.
> [GHA][features-integration] Add test status job with final result

- service/history/workflow/mutable_state_impl.go
Use single import for package.
Consistency.
> Fix import of History API 

- tests/add_tasks.go
- tests/advanced_visibility.go
- tests/archival.go
- tests/client_suite.go
- tests/describe_task_queue.go
- tests/dlq.go
- tests/functional.go
- tests/functional_test_base.go
- tests/functional_test_base_suite.go
- tests/gethistory.go
- tests/namespace_delete.go
- tests/nexus_endpoint_test.go
- tests/purge_dlq_tasks_api.go
- tests/schedule.go
- tests/sizelimit.go
- tests/tls.go
- tests/versioning.go
Hash test names instead of test suite name
Try to distribute the tests across the partitions instead of the test suite.
> Hash test names instead of test suite name

- common/dynamicconfig/file_based_client.go
- common/dynamicconfig/file_based_client_mock.go
- common/dynamicconfig/file_based_client_test.go
Change this interface to make it simpler and easier to reuse, and make it public.
Potential use by other dynamic config clients.
existing tests
> Refactor dynamic config file reader interface

- common/metrics/metric_defs.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/nexusoperations/metrics.go
- service/frontend/nexus_handler.go
- tests/nexus_api_test.go
- tests/xdc/nexus_request_forwarding_test.go
Add missing outcome tag to metrics handler in nexus start operation.
Some refactoring...
> Add missing outcome tag to metrics handler in nexus start operation

- docs/worker-versioning.md
> Clarify SDK support for Verisoning

- .github/workflows/run-tests.yml
Disable tests with Elasticsearch 8
Somehow it's broken in GHA
> [GHA tests] Disable tests with Elasticsearch 8

- common/circuitbreaker/circuitbreaker.go
- common/circuitbreaker/circuitbreaker_test.go
- service/history/configs/config.go
- service/history/outbound_queue_factory.go
Use dynamic config subscription for circuit breaker settings
Faster response to changes, simpler code
existing tests
> Use dynamic config subscription for circuit breaker settings

- .github/workflows/run-tests.yml
- develop/github/docker-compose.yml
- tests/test_cluster.go
Adjust ES settings in Docker container for GHA tests and re-enable tests with ES8.
Replaced the step running `docker compose up` with [hoverkraft-tech/compose-action](https://github.com/hoverkraft-tech/compose-action): it outputs the logs of the containers which can help with debugging.
Remove docker-cache from GHA tests: it's not triggering correctly.
Minor fixes in the code.
> Fix ES docker container for GHA tests

- service/history/workflow/cache/cache.go
Removing unused logger field. It's used in the closure, but not beyond that.
Simplify.
> Remove unused logger field

- go.mod
- go.sum
Update to pick up https://github.com/temporalio/ringpop-go/pull/15
> Update ringpop dependency

- common/metrics/metric_defs.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/workflow_task_state_machine.go
- tests/update_workflow.go
Single metric to track the "success" of a Speculative WFT (ie whether it prevents events to be written to History, or not).
Evaluate effectivenss of Speculative WFTs.
> Re-visit Speculative Workflow Task metrics

- common/dynamicconfig/collection.go
- common/tasks/fifo_scheduler.go
- common/tasks/fifo_scheduler_test.go
- service/history/configs/config.go
- service/history/queues/scheduler.go
- Use DC subscriptions in fifo scheduler
- I will do sequential scheduler in a separate PR.
- Simplify logic, avoid additional goroutines for polling dc update
> Use DC subscription in fifo scheduler

- common/finalizer/finalizer.go
- common/finalizer/finalizer_test.go
- common/metrics/metric_defs.go
- service/history/shard/context_impl.go
(1) Create pool after validation.
(2) Tracking metrics.
(1) Use fewer resources in case Finalizer is a noop. 
(2) Improve observability.
Extended existing tests.
> Create Finalizer pool after validation

- service/history/service.go
- service/matching/service.go
Enable gRPC reflection for history and matching services.
To improve debug expirience.
Tested with [evans](https://github.com/ktr0731/evans) locally:
No risks.
No.
No.
> Enable gRPC reflection for history and matching services

- common/dynamicconfig/constants.go
Update health check error percentage
use percentage 
Local testing
> Update health check error percentage

- common/tasks/sequential_scheduler.go
- common/tasks/sequential_scheduler_test.go
- service/history/configs/config.go
- same as https://github.com/temporalio/temporal/pull/6316 but for sequential scheduler
- Simplify logic, avoid additional goroutines for polling dc update
> Use DC subscriptions in sequential scheduler

- CONTRIBUTING.md
Fix go version in `CONTRIBUTING.md`.
Follow up to #6019.
> Fix go version in CONTRIBUTING.md

- tests/workflow.go
Rename test names to match behavior.
> Fix MultiOperation test name

- common/metrics/tags.go
- service/history/queues/executable.go
Add error type and resource exhausted cause to task error metrics
Be able to identify the error type and resource exhausted cause in task errors.
> Add error type and resource exhausted cause to task error metrics

- go.mod
- go.sum
> Upgrade api to v1.37.0

- service/frontend/workflow_handler.go
- tests/workflow.go
Added `Started` to the MultiOperation's StartWorkflow response.
So we can make appropriate billing decisions for MultiOperations.
> Add Started flag to MultiOperation

- service/history/api/recordworkflowtaskstarted/api.go
Fix stale mutable state check in `RecordWorkflowTaskStarted` API.
`RecordWorkflowTaskStarted` API didn't handle disappearance of speculative WFT properly and treated as stale mutable state. Actual staleness check is performed by vector clock and, in fact, is not needed here. I left it just in case and will remove later.
No risks.
No.
No.
> Fix stale mutable state check in RecordWorkflowTaskStarted API

- docs/admin/dlq.md
- tests/dlq.go
- tools/tdbg/dlq_service_test.go
- tools/tdbg/tdbg_commands.go
- tools/tdbg/tdbgtest/output_parsing_test.go
tdbg: default --dlq-version to v2 instead of v1
unit tests
> tdbg: default --dlq-version to v2 instead of v1

- common/persistence/cassandra/execution_store.go
- common/persistence/cassandra/factory.go
- common/persistence/cassandra/history_store.go
- common/persistence/cassandra/mutable_state_store.go
- common/persistence/cassandra/mutable_state_task_store.go
Removed some unused dependencies. Logger was not used in any of these objects.
Unused code.
Compiled and ran existing tests.
N/A
N/A
No
> [Persistence] Remove unused dependencies

- service/history/workflow/cache/cache.go
Added shard id to cache's finalizer's warning log.
To get better insights into which shard(s) have this issue.
> Add shard id to finalizer warning log

- docs/worker-versioning.md
Improve Version Set -> Rules API migration docs base on user feedback.
> New Versioning API clarifications

- common/tqid/task_queue_validator.go
- service/frontend/nexus_endpoint_client.go
Task Queue Validation Cleanup
- enums2 --> enumspb
- ValidateTaskQueueName --> Validate
- name --> taskQueueName
PR followup
> Task Queue Validation Cleanup

- components/nexusoperations/executors.go
- service/frontend/nexus_handler.go
Add logs to errors failing to parse links.
> [Nexus] Add logs when failed to parse links

- common/metrics/metric_defs.go
- common/metrics/tags.go
- common/persistence/visibility/factory.go
- common/persistence/visibility/visibility_manager_test.go
- common/persistence/visibility/visiblity_manager_metrics.go
- Added visibility index name for visibilityManagerMetrics tag
- To observe metrics for both primary and secondary visibility store
> Added visibility index name for visibilityManagerMetrics tag

- tests/reset_workflow.go
Add a functional test for "reset after timeout" scenario.
If was reported that this bug still exist. I think we need to have a functional test to cover this
In this PR only test changed.
No risk
> add func test for reset after timeout

- tests/describe_task_queue.go
- removed helpers which were not being used
- keeping code nice and clean
- exiting CI/CD run
none
- nope
> Removed non-required helpers

- common/tqid/task_queue_validator.go
- common/tqid/task_queue_validator_test.go
Only validate sticky queue normal name if it is set
Compatibility with older SDKs
Unit test
> Task Queue Validation Change

- components/dummy/tasks.go
- components/nexusoperations/executors.go
- components/nexusoperations/tasks.go
- service/history/ndc_standby_task_util.go
- service/history/outbound_queue_standby_task_executor.go
- service/history/queues/executable.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
Cherry picked #6472 on top of 120.
> State machine standby executor fixes (#6472)

- go.mod
Bump to latest patch version ([release page](https://go.dev/doc/devel/release)).
Bug fixes.
> Bump Go to 1.22.6

- common/dynamicconfig/constants.go
- service/history/configs/config.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- Track sub state machine tombstones in mutable state
- For new state-based replication stack
- Unit test
- N/A, feature flag not enabled.
> Track sub state machine tombstones

- common/finalizer/finalizer.go
- service/history/workflow/cache/cache.go
Make `Finalizer` release memory earlier.
See PR comment to explain the background.
Existing tests still pass.
Since `callbacks` is never read/written again after clearing it, it should be safe.
> Tweak Finalizer on eviction

- components/nexusoperations/statemachine.go
- components/nexusoperations/statemachine_test.go
- tests/nexus_workflow_test.go
Fixed a regression where we wouldn't deliver the operation cancel request if it is canceled just before we record it was started.
Added functional test.
> Fix operation cancel just before started

- tests/functional.go
- tests/update_workflow.go
Refactor `decodeString` to accept `require.TestingT`.
To be able to use with other test suites.
Compile.
No risks.
No.
No.
> Refactor decodeString to accept require.TestingT

- docs/architecture/effect-package.md
- docs/architecture/workflow-update.md
> Update Workflow docs editing

- docs/architecture/workflow-update.md
Workflow Update: update docs with recent code changes in #6477 and #6485. Also fixed some minors.
Keep doc up to date.
> Workflow Update: update docs with recent code changes

- common/testing/historyrequire/history_require.go
- tests/xdc/advanced_visibility_test.go
- tests/xdc/failover_test.go
- tests/xdc/history_replication_signals_and_updates_test.go
Add event Version support to `HistoryRequire` test helper.
It is more convenient to have version together with other history attributes. `Version` is optional. If it is not specified, it is considered to be `0` and not compared.
Run all tests.
No risks.
No.
No.
> Add event Version support to HistoryRequire test helper

- common/persistence/visibility/store/elasticsearch/processor.go
- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Fix error messages in Elasticsearch bulk processor:
- Remove task key from error message,
- Fix case and syntax.
Error messages should be consistent within the project and don't have unique data.
No risks. No code should depend on error message text.
No.
No.
> Fix error messages in Elasticsearch bulk processor

- service/frontend/admin_handler.go
Add log capture panic in deep health check
Safe handle panic
> Add log capture panic in deep health check

- tests/onebox.go
Just refactor some repeated code
easier to maintain
> Consolidate and clean up copyPersistenceConfig in functional tests

- common/dynamicconfig/memory_client.go
- common/dynamicconfig/memory_client_test.go
Support subscriptions in dynamicconfig.MemoryClient
Better more reliable tests
new unit test
> dynamicconfig.MemoryClient supports subscriptions

- tests/onebox.go
Instead of picking the first frontend for SDK clients, balance using the grpc resolver.
Make tests behave more like real code.
is tests
> Use membership resolver for SDK clients in functional tests

- common/persistence/client/fx.go
- common/persistence/execution_manager.go
- common/persistence/xdc_cache.go
- service/history/replication/raw_task_converter.go
1. Remove MaxEventId from cache key
2. Add NextEventID to cache value
For State based replication usage. So the events can be retrieved from cache
current unit test
cache may stop working.
n/a
no
> Refactor XDC cache

- common/headers/caller_info.go
- common/headers/caller_info_test.go
- common/headers/headers.go
- common/rpc/interceptor/redirection.go
- components/nexusoperations/config.go
- components/nexusoperations/workflow/commands.go
- components/nexusoperations/workflow/commands_test.go
Validate max header length and disallowed headers.
Protect the server.
Unit tests.
> Add Nexus Operation header validation

- go.mod
- go.sum
- tests/client_misc_test.go
Update go SDK to the latest.
To eliminate rare panic case in internal system worker.
Build.
No risks.
No.
No, these rare panics are recoverable by replay.
> Update go SDK to the latest

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
skip deletion if not exist when applying tombstones
unit test
> skip deletion if not exist when applying tombstones

- tests/acquire_shard_test.go
- Increase buffer size for log buffer in acquire shard functional tests.
- Actually log in those tests too, so it's easier to see what happened if they fail.
Hopefully make them less flaky.
is tests
> Fix flaky acquire shard tests

- .github/workflows/run-tests.yml
Skip altered test detection if no PR is associated with the run
No need to check for altered test without a PR context
> Skip altered test detection if in main

- service/history/replication/executable_task.go
- service/history/replication/executable_task_test.go
Use response of the SyncState API call for SyncState error.
unit test.
> Use response of the SyncState API call.

- service/history/api/forcedeleteworkflowexecution/api.go
- Fix force delete workflow warning message
- Remove unused function
- Vis record will always be deleted after standard visibility is deprecated
> Fix force delete workflow warning message

- service/history/ndc/replication_task.go
- service/history/ndc/replication_task_test.go
patch fix for PR to release v1.21.x https://github.com/temporalio/temporal/pull/6646
> Prevent Back and Forth Migration Workflow Edge Case 

- CONTRIBUTING.md
> Go version bump docs

- tests/nexus_test_base.go
Found here: https://github.com/temporalio/temporal/actions/runs/11473702877/job/31928413916#step:8:8773
> Do not panic in nexus test poller helper on not found errors

- common/persistence/sql/sqlplugin/db_handle.go
- common/quotas/dynamic.go
- go.mod
- service/matching/ack_manager.go
- service/matching/matcher_test.go
- tests/add_tasks_test.go
- tests/dlq_test.go
- tests/xdc/history_replication_dlq_test.go
- tests/xdc/nexus_state_replication_test.go
CI is failing for the original PR #5278.
I think that's due to that PR being open from the `main` branch in @serprex's fork.
I'll give credit to the original author when I merge.
> Replace go.uber.org/atomic with sync/atomic

- common/dynamicconfig/constants.go
- common/util.go
- service/history/archival_queue_factory.go
- service/history/configs/config.go
- service/history/outbound_queue_factory.go
- service/history/queues/executable.go
- service/history/queues/executable_factory.go
- service/history/queues/executable_test.go
- service/history/queues/queue_base_test.go
- service/history/queues/queue_scheduled_test.go
- service/history/timer_queue_factory.go
- service/history/transfer_queue_factory.go
- service/history/visibility_queue_factory.go
Reverts temporalio/temporal#6622
> Revert "Treat serviceerror.Internal as non-retryable"

- service/history/replication/sync_state_retriever.go
> fix cache boundary check

- service/matching/matching_engine.go
- service/matching/matching_engine_test.go
- service/matching/task_queue_partition_manager.go
- service/matching/task_queue_partition_manager_test.go
- service/matching/user_data_manager.go
- Use properly tagged logger for userDataManager.
- Add logging for source of modifications.
Better logging for debugging.
> Fix userDataManager logs

- service/history/ndc/workflow_state_replicator.go
- service/history/ndc/workflow_state_replicator_test.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
1. Properly handle tombstone batch when processing mutation task
2. Switch history branch when processing sync versioned transition task
bug fix
Unit test
No risk
n/a
no
> Fix state based replication bug

- common/telemetry/grpc_test.go
> Fix flaky OTEL test

- go.mod
Upgrades go to 1.22.7 to resolve several CVEs.
Bug fixes
Tested locally.
This is a backport to release/v1.25.x
> deps: upgrade go to 1.22.7

- service/history/workflow/mutable_state.go
Added some comments.
Makes it a bit easier to understand these calls.
> [Nit] Document transactionality of mutable state

- service/history/history_engine_test.go
Rename mockHistoryEngine to historyEngine in test.
The name with mock is very confusing, it make it looks like a mock, but it is not a mock, it is the actual historyEngineImpl under test.
N/A
No
No
No
> Rename mock history engine in test

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- initial commit
- add tests
Clear transition history when state tracking is diabled
To support disabling transition history
unit test
no risk, not enabled.
n/a
no
> Clear Transition history when state tracking disabled

- service/history/statemachine_environment.go
Check nil before validate
It will cause panic if without this check.
n/a
n/a
n/a
no
> Check nil before validate

- go.mod
- go.sum
- service/history/api/describeworkflow/api.go
- service/history/circuitbreakerpool/circuit_breaker_factory.go
- service/history/circuitbreakerpool/fx.go
- service/history/circuitbreakerpool/outbound_queue.go
- service/history/history_engine.go
- service/history/history_engine_factory.go
- service/history/outbound_queue_factory.go
- service/history/queue_factory_base.go
If a callback task, pending nexus operation task, or cancellation task is blocked, now it shows as `BLOCKED` state, and the `BlockedReason` gives the details about the circuit breaker.
Provide more information to user.
> [Describe API] Blocked state for callback, pending nexus operation, and cancellation infos

- service/history/workflow/update/update_test.go
Fix `immedate` typo.
English is not my first language.
N/A
No risks.
No.
No.
> Workflow Update: fix immedate typo

- service/history/api/respondworkflowtaskcompleted/api.go
- service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
Remove unused returned `error` from `RejectUnprocessed`.
For beauty and symmetry with another method which I will add in another PR.
Build.
No risks.
No.
No.
> Workflow Update: remove unused returned error from RejectUnprocessed

- common/persistence/visibility/store/errors.go
- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
Delete dead code
Less is better
Updated existing unit test
No
No
No
> Remove dead code around standard visibility

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
Fix track versioned transition history when close transaction
Bug fix
unit test
no risk
n/a
no
> Fix track versioned transition history

- config/dynamicconfig/README.md
Fixed README formatting
It didn't render correctly, which made it confusing to read.
n/a
n/a
✅
No
> readme: fix formatting

- service/history/replication/executable_task.go
- service/history/replication/executable_verify_versioned_transition_task.go
- service/history/replication/stream_sender.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/task_generator.go
1. Add first/next event at task generator
2. Create map when updateinfo is nil
bug fix
unit tetst
n/a
no risk
no
> Fix state based replication

- service/history/workflow/update/update.go
Refactor `WaitLifecyleStage` method.
I believe new version is easier to read. Also there is minor change in behaviour: if there are both future error and context error, then future error has a priority and returned from the `WaitLifecycleState`. It shouldn't matter in real life, but can simplify testing.
No risks.
No.
No.
> Workflow Update: refactor WaitLifecyleStage method

- tests/nexus_api_test.go
It's not guaranteed that we get a `context.DeadlineExceeded` error in this path, in busy CI we might get an upstream timeout error.
> Fix flake in TestNexusStartOperation_WithNamespaceAndTaskQueue_SupportsVersioning

- client/frontend/client_gen.go
- client/frontend/metric_client_gen.go
- client/frontend/retryable_client_gen.go
- common/rpc/interceptor/logtags/workflow_service_server_gen.go
- common/testing/mockapi/workflowservicemock/v1/service_grpc.pb.mock.go
- go.mod
- go.sum
- service/frontend/workflow_handler.go
Pull in UpdateWorkflowExecutionOptions and latest versioning-3 changes from api-go
> Pull in UpdateWorkflowExecutionOptions and latest versioning-3 changes from api-go

- service/history/tasks/sync_versioned_transition_task.go
Print raw task info when failed to convert
debug if failed
n/a
no risk
n/a
no
> Print raw task info when failed to convert raw task

- service/history/historybuilder/event_store.go
- service/history/historybuilder/history_builder_test.go
- service/history/workflow/mutable_state_rebuilder.go
Remove references to `EVENT_TYPE_WORKFLOW_EXECUTION_UPDATE_REJECTED`.
Not used.
> Remove EVENT_TYPE_WORKFLOW_EXECUTION_UPDATE_REJECTED

- service/matching/matcher_test.go
- tests/describe_task_queue_test.go
- tests/http_api_test.go
- tests/max_buffered_event_test.go
- tests/versioning_test.go
- tests/workflow_test.go
- tests/xdc/failover_test.go
- tests/xdc/nexus_state_replication_test.go
Reverts temporalio/temporal#6684
> Revert "Reenable flaky tests"

- tests/update_workflow_test.go
Added more tests around UwS: rejection, outcome polling and event history.
Expand UwS test coverage.
> Additional Update-with-Start tests

- tests/xdc/stream_based_replication_test.go
- tests/xdc/user_data_replication_test.go
Disable
```
TestStreamBasedReplicationTestSuite
TestUserDataTombstonesAreReplicated
```
flaky tests.
...
> Disable xdc flaky tests

- service/history/replication/executable_verify_versioned_transition_task.go
- service/history/replication/executable_verify_versioned_transition_task_test.go
- service/history/replication/sync_state_retriever.go
1. Fix VerifyVersionedTransitionTask
2. Fix sync state retriever for update
bug fix for state based replication
unit test
no risk
n/a
no
> Fix state based replication task

- common/testing/taskpoller/taskpoller.go
- tests/update_workflow_suite_base.go
- tests/update_workflow_test.go
Refactored Update-with-Start tests to use new TaskPoller (v2).
Easier to read tests.
> Use new TaskPoller in UwS tests

- service/history/api/startworkflow/api.go
Changed the error handling ordering.
I always found this code confusing. The success case is now at the bottom; the error handling nested.
> Rearrange error handling in Start Workflow

- service/history/api/multioperation/api.go
- service/history/workflow/cache/cache.go
- service/history/workflow/cache/cache_mock.go
- tests/update_workflow_test.go
Reverting cache changes from https://github.com/temporalio/temporal/pull/6783.
I'll fix it properly next!
Causes flaky test.
> Revert cache change

- tests/update_workflow_test.go
Added new test for MultiOps.
Code path was untested.
> Test Update error from MultiOps is returned

- service/history/replication/sync_state_retriever.go
- service/history/replication/sync_state_retriever_test.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
Fix tombstone tracking for state based replication
bug fix
uni test
no risk
n/a
no
> Fix tombstone tracking for state based replication

- service/frontend/workflow_handler.go
I stumbled upon this by accident as my IDE highlighted this.
I guess it was fine since this never crashed? But this change makes me feel better.
> UpdateWorkflowExecution err return

- service/history/api/create_workflow_util.go
- service/history/api/startworkflow/api.go
> Rename to CreateLeaseFunc

- service/history/workflow/mutable_state_impl.go
> Add line breaks to comment

- service/worker/deployment/deployment_util_test.go
- tests/deployment_test.go
- Refactored read-API functional tests
- To make existing happy-path tests more assertive 
- tests
- none, going to feature
> Refactored read-API functional tests

- common/rpc/interceptor/telemetry.go
- common/rpc/interceptor/telemetry_test.go
Added action metric tracking for MultiOperation.
Align with Cloud billing changes.
Added tests.
> MultiOperation action metric

- go.mod
- go.sum
Update with tagged API v1.43.0
We want to have tagged api dependencies in server releases.
> Update with tagged API v1.43.0

- tests/testcore/test_cluster.go
Follow-up to https://github.com/temporalio/temporal/pull/6915 - making sure clusters are started one-by-one.
To make sure there are no port allocation conflicts for parallel cluster starts.
It can slow down functional test execution. I haven't measured yet how long a cluster start takes.
If it turns out to be too long, I can go back to the drawing board on this.
> Fix port address race

- tests/versioning_3_test.go
> Fix flaky TestUnpinnedWorkflow

- tests/activity_api_update_test.go
- tests/testcore/functional_test_base.go
- tests/versioning_test.go
Extract common function into base class.
I'm panning to use it in the new suite, and that will be 3rd copy. Time to extract.
make unit-test
> extract comon helper into base class

- tests/activity_api_reset_test.go
> add functional tests for reset activity API

- docs/architecture/workflow-update.md
> Clarify maxTotalUpdates documentation

- tests/activity_api_pause_test.go
- tests/activity_api_reset_test.go
- tests/activity_api_update_test.go
Working on some comments for activity API functional tests
Code perfection...
> some code improvements for activity api tests

- common/dynamicconfig/constants.go
- service/frontend/nexus_handler.go
- service/frontend/nexus_handler_test.go
- service/frontend/nexus_http_handler.go
- service/frontend/service.go
Nexus request headers sanitization: it removes blacklisted headers before it's sent to the client's operation handler.
Unit test.
> [Nexus] Dynamic config to filter Nexus request headers

- common/rpc/interceptor/stream_error.go
- service/fx.go
Service error is not properly handled on replication, this is to fix it.
to handle shard ownership lost error and invalidate history client cache in frontend 
unit test
no risk
n/a
yes
> Fix grpc stream error convert

- service/history/workflow/update/registry.go
- tests/update_workflow_test.go
> Tweak Update rate limit error

- develop/docker-compose/docker-compose.cdc.yml
- develop/docker-compose/docker-compose.yml
Using the latest `grafana`, `temporalio/ui` and `prometheus` images for our local dev setup.
The current versions are 6+ months old.
Started locally.
> Latest UI, Grafana and Prometheus images

- common/dynamicconfig/constants.go
> enable ExecuteMultiOperation

- service/history/api/multioperation/api.go
- tests/update_workflow_test.go
Added lock release for closed Workflows.
Bug.
Added test.
> Fix MultiOperation: unlock terminated WF

- develop/docker-compose/docker-compose.darwin.yml
Open up Grafana Tempo's OTEL HTTP port, too.
It's useful to send traces via curl.
> Open Tempo OTEL HTTP port

- common/persistence/tests/execution_mutable_state.go
- Fix how branchToken is created and used in ExecutionMutableStateSuite
- More assertions
- Some variable rename
- The test was using the same branch token for multiple different runs and worked in a weird way (new record happens to overwrite old record in DB).
> Fix ExecutionMutableStateSuite

- common/testing/taskpoller/taskpoller.go
- docs/development/testing.md
Added new taskpoller to project's testing guidelines.
To recommend this behavior to newcomers.
> Include taskpoller in test guidelines

- common/persistence/client/fx.go
- common/persistence/persistence_interface.go
- common/persistence/telemetry/cluster_metadata_store_gen.go
- common/persistence/telemetry/data_store_factory.go
- common/persistence/telemetry/execution_store_gen.go
- common/persistence/telemetry/gowrap_template
- common/persistence/telemetry/nexus_endpoint_store_gen.go
- common/persistence/telemetry/queue_gen.go
- common/persistence/telemetry/queue_v2_gen.go
- common/persistence/telemetry/shard_store_gen.go
- common/persistence/telemetry/shared_store_gen.go
- common/persistence/telemetry/task_store_gen.go
- service/history/tasks/category.go
Added persistence span attributes.
Provide more details for debugging.
Ran it locally.
NOTE: Some persistence requests/responses contain encoded protobuf data. That will be addressed in a future PR.
> OTEL persistence attributes

- tools/testrunner/testrunner.go
Added log prefix to testrunner.
To make it easier to quickly search for its output in GH Actions output.
Also, to make it clear where a log message is coming from.
> Add log prefix to testrunner

- components/nexusoperations/completion.go
- components/nexusoperations/executors.go
- go.mod
- go.sum
- service/frontend/nexus_handler.go
- tests/nexus_workflow_test.go
Added handling for links in Nexus sync success responses
> Add handling for links in Nexus sync success responses

- service/history/replication/executable_task.go
Increase replication task retry expiration interval
Give it more chance of success when there is a persistence issue
n/a
no risk
n/a
no
> Increase replication task retry expiration interval

- tests/versioning_test.go
Fixing flaky test by increasing tight timeout.
> Fix flaky test TestDispatchCron

- tests/archival_test.go
Refactor: run archival tests in parallel with others.
After previous archival test refactoring it is now possible to run them in parallel.
Run tests.
No risks.
No.
No.
> Refactor: run archival tests in parallel with others

- go.mod
- go.sum
> Bump API version to v1.43.2

- go.mod
- go.sum
> Bump Nexus SDK v0.1.1

- go.mod
- go.sum
- service/frontend/workflow_handler.go
- service/worker/batcher/activities.go
- service/worker/batcher/workflow.go
Add a placeholder for batch unpause activities.
Part of batch activities API work.
existing tests
NA
> placeholder for batch unpause activities

- common/persistence/persistence-tests/persistence_test_base.go
- common/telemetry/config.go
- common/telemetry/grpc.go
- common/telemetry/grpc_test.go
- service/history/archival_queue_factory_test.go
- service/history/archival_queue_task_executor_test.go
- service/history/queue_factory_base_test.go
- service/history/queues/executable_test.go
- service/history/queues/memory_scheduled_queue_test.go
- service/history/queues/queue_base_test.go
- service/history/queues/queue_scheduled_test.go
- service/history/queues/reader_test.go
- service/history/queues/slice_test.go
- service/history/timer_queue_active_task_executor_test.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/transfer_queue_active_task_executor_test.go
- service/history/transfer_queue_standby_task_executor_test.go
- service/history/visibility_queue_task_executor_test.go
- temporal/fx.go
- temporal/server_impl.go
Introduces vars for the noop tracer and trace provider.
Communicates clearer what/where they are.
> OTEL noop vars

- common/persistence/client/fx.go
- common/telemetry/config.go
- common/telemetry/tags.go
- service/history/archival_queue_factory.go
- service/history/archival_queue_factory_test.go
- service/history/memory_scheduled_queue_factory.go
- service/history/outbound_queue_factory.go
- service/history/queues/executable.go
- service/history/timer_queue_factory.go
- service/history/transfer_queue_factory.go
- service/history/visibility_queue_factory.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/util.go
- temporal/fx.go
Moved all telemetry resource names to one place.
Having them in one place.
> Unify OTEL resource names

- service/matching/physical_task_queue_manager.go
- service/matching/physical_task_queue_manager_test.go
- service/matching/task_tracker.go
- service/matching/task_tracker_test.go
Just move some code around.
Separate concerns.
> Move taskTracker and circularTaskBuffer to new file

- common/dynamicconfig/constants.go
- service/matching/config.go
Remove this obsolete config.
It's not used anymore.
> Remove MatchingLoadUserData config

- common/persistence/cassandra/metadata_store.go
- service/frontend/namespace_handler.go
> Include namespace name in NamespaceAlradyExists error message

- service/worker/deployment/fx.go
- update old deployment component, for existing pre-release versioning-3 customers, so that it always registers itself when versioning-3 is enabled on the namespace
- fix any potential delays in worker registration in the near future
- existing suite of tests
- not a lot since this feature is still pre-release
- No
> update old deployment component

- docs/worker-versioning.md
> Deprecate Worker Versioning 2 (Rule Based Versioning) readme

- service/history/api/startworkflow/api.go
- service/history/api/workflow_id_dedup.go
- service/history/workflow/mutable_state_impl.go
> Refactor workflow id dedup, add callbacks to ms and update versioning override

- tests/testcore/functional_test_base.go
- tests/testcore/functional_test_suite.go
Refactor: remove unneeded fields from `FunctionalTestBase`.
Simplify function test base struct.
Build and run tests.
No risks.
No.
No.
> Refactor: remove unneeded fields from FunctionalTestBase

- service/history/ndc_standby_task_util.go
- service/history/timer_queue_active_task_executor.go
- service/history/transfer_queue_active_task_executor.go
Moved access to mutable state's `Priority` inside the lock, where applicable.
> Access Priority inside lock

- go.mod
- go.sum
Pick up https://github.com/temporalio/ringpop-go/pull/17
Fix bug
Ringpop unit tests
> Upgrade ringpop-go to fix locking bug

- service/matching/matching_engine.go
Follow-up from #7093: exclude `RESOURCE_EXHAUSTED_CAUSE_BUSY_WORKFLOW` from early return to client.
Busy workflow is really a "workflow" scope error, not namespace or system scope, so the argument that we shouldn't retry immediately doesn't apply.
there weren't specific tests for this
> Don't return BUSY_WORKFLOW on polls

- common/telemetry/grpc.go
Track grpc headers in OTEL _debug mode_.
Improve debugging experience.
Checked in Grafana.
Only enabled in debug mode.
> OTEL add grpc headers

- chasm/ref.go
Fix default sharding function.
Made a typo in my previous PR #7184.
> CHASM: Fix default sharding function

- tests/worker_deployment_test.go
> Test for Wrong Conflict Token

- chasm/ref.go
- chasm/registrable_component.go
- chasm/registrable_task.go
- chasm/registry.go
- chasm/registry_test.go
- Rename component/taskName to component/TaskType in chasm framework to avoid confusion.
> CHASM: Rename name to type

- service/worker/workerdeployment/client.go
- service/worker/workerdeployment/version_workflow.go
> pass only version from worker deployment client when starting version wf

- service/history/configs/config.go
- service/history/workflow/context.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
Using the new dynamic config subscribers in the Update registry.
To keep the Update registry's settings up-to-date.
Updated existing tests.
> Dynamic config subscriber in Update Registry

- service/history/configs/config.go
- service/history/workflow/context.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
Reverts https://github.com/temporalio/temporal/pull/7224 but keeps the bug fix.
Change was unnecessary.
> Remove Subscription from Update Registry

- service/worker/workerdeployment/client.go
> handle unset ramp with version verification

- service/history/ndc/events_reapplier_test.go
- service/history/ndc/workflow_resetter.go
- service/history/ndc/workflow_resetter_test.go
- service/history/workflow/util.go
- tests/reset_workflow_test.go
Reapply WorkflowExecutionOptionsUpdated history event in conflict resolution
> Reapply WorkflowExecutionOptionsUpdated history event

- service/worker/workerdeployment/client.go
- service/worker/workerdeployment/util.go
- service/worker/workerdeployment/workflow.go
- tests/deployment_version_test.go
- tests/worker_deployment_test.go
- make deletes idempotent
- added functional tests 
- also changes to functional test to make them have a stricter consistency check
> Deletes are now idempotent

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/retry.go
- tests/callbacks_test.go
Fix passing callbacks to continued as new workflow and retries.
> Fix passing callbacks to continued as new workflow and retries

- common/dynamicconfig/constants.go
- common/metrics/metric_defs.go
- service/history/configs/config.go
- service/history/workflow/context.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
- service/history/workflow/update/util.go
- tests/update_workflow_test.go
Added support for Update Registry to suggest CAN.
To allow Workflow to CAN before it reaches the Update limit.
> Update Registry suggest CAN

- service/worker/workerdeployment/client.go
- service/worker/workerdeployment/version_workflow.go
- reset drainageInfo to nil after workflow starts accepting new workflows again
- existing suite
> reset drainageInfo

- service/history/ndc_standby_task_util.go
- service/history/transfer_queue_standby_task_executor_test.go
Use namespace name to call describe workflow api
bug fix
n/a
no risk
n/a
no
> Fix describe workflow call at standby task verification

- service/worker/workerdeployment/version_workflow.go
- tests/worker_deployment_version_test.go
> ForceCAN bug fix

- common/nexus/failure.go
- components/nexusoperations/fx.go
> Export helper for setting Nexus failure source on context

- config/dynamicconfig/development-cass.yaml
- go.mod
- go.sum
The lib version accidentally went back in a previous PR. Fixing it here.
> Bump nexus-rpc/sdk-go tag to v0.2.0

- service/worker/workerdeployment/workflow.go
- tests/worker_deployment_test.go
- forceCAN for worker-deployment
- added test
> forceCAN for worker-deployment

- go.mod
- go.sum
> Bump API to v1.44.0

- common/metrics/opentelemetry_provider.go
- Log prometheus listener error at Warn level
- For backward compatibility. There might be some CI systems monitoring logs and fail tests on Error logs.
> Log prometheus listener error at Warn level

- tests/testdata/xdc_clusters.yaml
- tests/xdc/activity_api_test.go
- tests/xdc/base.go
- tests/xdc/failover_test.go
- tests/xdc/history_replication_dlq_test.go
- tests/xdc/history_replication_signals_and_updates_test.go
- tests/xdc/nexus_request_forwarding_test.go
- tests/xdc/nexus_state_replication_test.go
- tests/xdc/stream_based_replication_test.go
- tests/xdc/user_data_replication_test.go
- tests/xdc/visibility_test.go
Refactor: use slice of clusters in xdc tests.
To use `for` loops and simplify future join with `FunctionalTestBase`.
Run it.
No risks.
No.
No.
> Refactor: use slice of clusters in xdc tests

- client/frontend/client_gen.go
- client/frontend/metric_client_gen.go
- client/frontend/retryable_client_gen.go
- cmd/tools/getproto/files.go
- common/api/metadata.go
- common/rpc/interceptor/logtags/workflow_service_server_gen.go
- common/rpc/interceptor/redirection.go
- common/rpc/interceptor/redirection_test.go
- common/testing/mockapi/workflowservicemock/v1/service_grpc.pb.mock.go
- go.mod
- go.sum
- service/frontend/configs/quotas.go
Add stubs for workflow rules API.
Part of the workflow rules workstream
> Add Stubs for Workflow Rules

- tools/testrunner/junit.go
- tools/testrunner/testdata/junit-timeout-output.xml
Append `(timeout)` to test failure of timed out test.
So they can be easily spotted in the JUnit test output.
Adapted existing tests.
> Mark timed out tests

- .github/workflows/run-tests.yml
Update default runner to `ubuntu-latest` for the test workflow.
There's a warning of deprecation of `ubuntu-20.04`: https://github.com/actions/runner-images/issues/11101
> [GHA] Update default runner to ubuntu-latest

- api/deployment/v1/message.pb.go
- common/worker_versioning/worker_versioning.go
- proto/internal/temporal/server/api/deployment/v1/message.proto
- service/worker/workerdeployment/client.go
> format version string correctly in deployment API error messages

- service/frontend/namespace_handler.go
- service/frontend/namespace_handler_test.go
> Add unit tests for rules functions

- common/dynamicconfig/constants.go
- service/matching/config.go
- service/matching/physical_task_queue_manager.go
> Fix incomplete settings rename

- service/history/workflow/activity.go
- service/history/workflow/retry.go
Move function to the module where it is used.
Housekeeping. 
existing tests
> small refactoring

- common/testing/mocksdk/client_mock.go
- go.mod
- go.sum
- tests/nexus_workflow_test.go
Upgrade sdk-go to v1.33.0
Fix Nexus tests
> Upgrade sdk-go to v1.33.0

- service/history/replication/raw_task_converter.go
- service/history/replication/raw_task_converter_test.go
- service/history/replication/sync_state_retriever.go
- service/history/replication/sync_state_retriever_test.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_util.go
- Deep copy the `UpdatedSubStateMachines` field to avoid race condition
- Deep copy only the mutation instead of entire mutable state.
- Bug fix and performance improvement
- Unit test
- Could be for rolling out state based replication
> Fix get mutable state mutation

- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/state_machine_definition.go
move stateMachineDefinition into a separate file.
Move some static definitions to mutable_state_impl.go
Housekeeping.
existing tests.
> Refactoring. Clean multableState interface

- service/matching/ack_manager_test.go
- service/matching/backlog_manager.go
- service/matching/backlog_manager_test.go
- service/matching/db.go
- service/matching/forwarder_test.go
- service/matching/matcher_test.go
- service/matching/matching_engine_test.go
- service/matching/physical_task_queue_manager_test.go
- service/matching/task_queue_partition_manager_test.go
Fix unit tests in priority branch
Help make sure we didn't break anything
> Unit test fixes for subqueues

- common/namespace/namespace.go
- common/testing/mocksdk/client_mock.go
- service/history/workflow/activity.go
- service/history/workflow/matcher/activity_evaluator.go
- service/history/workflow/matcher/activity_matcher.go
- service/history/workflow/matcher/mutable_state_evaluator.go
- service/history/workflow/matcher/mutable_state_evaluator_test.go
- service/history/workflow/matcher/mutable_state_matcher.go
- service/history/workflow/matcher/mutable_state_matcher_test.go
- service/history/workflow/mutable_state_impl.go
- tests/activity_api_rules_test.go
> Add workflow rules support for RetryActivity. Add tests

- docs/development/testing.md
Explain use of `softassert` package.
> Describe softassert

- tests/describe_task_queue_test.go
- tests/versioning_3_test.go
- Versioning 3 tests: make tests individually time out on failure instead of blocking forever
- DescribeTaskQueue tests: use `require` in `EventuallyWithT` to avoid panics
make it more clear when/how tests fail
> Functional test improvements

- docs/architecture/workflow-update.md
Added documentation for the last two Update configs.
> Document new Update configs

- temporal/fx.go
Disabling OTEL error logging before startup _and_ after shutdown was initiated. 
Those logs are just noise.
Run before/after fix and saw these gone:
```
{"level":"warn","ts":"2025-03-06T11:44:31.484-0800","msg":"OTEL error","error":"traces export: the client is shutdown","service-error-type":"errors.errorString","logging-call-at":"/Users/stephan/Workspace/default/temporal/temporal/fx.go:877"}
```
> Suppress OTEL export errors during startup/shutdown

- common/clock/event_time_source.go
- service/matching/matcher_data.go
- service/matching/matcher_data_test.go
- service/matching/pri_forwarder.go
- service/matching/pri_matcher.go
- Add unit tests for matcherData and simpleLimiter
- Add fuzz test
- Fix a couple small bugs
- Rename MatchNextPoller to MatchTaskImmediately
test coverage
> Unit tests for matcher data

- .golangci.yml
- common/metrics/metric_defs.go
- common/metrics/tags.go
- service/history/ndc/activity_state_replicator.go
- service/history/ndc/activity_state_replicator_test.go
- service/history/replication/bi_direction_stream.go
- service/history/replication/executable_task.go
- service/history/replication/metrics.go
- service/history/replication/stream_receiver.go
- service/history/replication/stream_sender.go
- service/history/replication/stream_sender_test.go
- service/history/workflow/mutable_state_impl.go
Adding finer replication metrics
For better debugging purpose on replication stack
Those are mostly metric to add. I will verify them in cluster environment.
> Adding finer replication metrics

- docs/development/testing.md
Document how to use OTEL in tests.
> OTEL test docs

- common/dynamicconfig/constants.go
- common/metrics/metric_defs.go
- service/history/replication/ack_manager.go
Update replication task page size
Update replication task page size to align with other queue read size.
> Update replication task page size

- .codecov.yml
Disable Codecov GitHub checks.
Don't want to label PRs as failed because of code coverage diffs:
> Disable Codecov GitHub checks

- .codecov.yml
Disable Codecov GitHub status.
Not mark build as failed due to Codecov.
> Disable Codecov GitHub status

- README.md
Consolidate links for contributors in the README.
Remove dead links and streamline link discovery.
> Consolidate README

- service/worker/workerdeployment/workflow.go
- service/worker/workerdeployment/workflow_test.go
- Added tests for testing concurrent stale updates. 
- more testing coverage.
- Added new unit tests + existing suite
- None
- No
> versioning test: concurrent stale updates

- .github/workflows/trigger-version-info-service.yml
[GHA] Trigger version-info-service when releases are published
Automation
> [GHA] Trigger version-info-service when releases are published

- service/history/queues/executable.go
- Log only unexpected task processing error
- Prevent log spamming when task is keep failing with expected errors like resource exhausted.
- For expected errors, we still have metrics emitted.
> Log only unexpected task processing error

- go.mod
- go.sum
- tests/priority_fairness_test.go
Rewrite TestPriorityFairnessSuite using TaskPoller
Remove dependency on new SDK for merge
> Rewrite TestPriorityFairnessSuite using TaskPoller

- go.mod
- go.sum
> Bump API to 1.46.0

- common/dynamicconfig/memory_client.go
MemoryClient should release its own lock before notifying subscribers.
Lock ordering between Collection's subscriptionLock and MemoryClient's lock: they were taken in both orders which could result in a deadlock.
Existing tests. Note that MemoryClient is only used in test environments.
> Fix locking bug in dynamicconfig MemoryClient

- Makefile
- docs/development/testing.md
Increased OTEL_BSP_SCHEDULE_DELAY from 0 to 100ms.
Zero is too aggressive and leads to too much CPU usage.
> Increase OTEL_BSP_SCHEDULE_DELAY

- README.md
Fixed README badge links to not only look pretty but also redirect you.
Try it here: https://github.com/temporalio/temporal/blob/dcabb2df65fcdfe03c2dcdee869730ea7185a285/README.md
> Add README badge links

- common/metrics/metric_defs.go
- service/history/replication/executable_task.go
Fix replication metrics
mismatch tagging
> Fix replication metrics

- chasm/test_component_test.go
- chasm/test_library_test.go
CHASM: add `TestComponent` to use in unit tests.
Simple component with subcomponents and subfields to use in unit tests. Depends on #7532.
N/A
No risks.
No.
No.
> CHASM: add TestComponent to use in unit tests

- tests/workflow_reset_with_child_test.go
Fix flaky TestResetWithChild_AfterStartingChild test by getting reset event id in s.Eventually()
Unit test
> Fix flaky TestResetWithChild_AfterStartingChild

- common/metrics/metric_defs.go
- service/history/api/startworkflow/api.go
Emit metric for start workflow request deduped.
Fix possible double emitting eager execution denied counter.
> Emit metric for start workflow request deduped

- service/history/queues/executable.go
- service/history/queues/executable_test.go
- Treat all namespace scoped resource exhausted as task processing user error
- Namespace level persistence resource exhausted error should be considered as user error. Alerts based on `task_latency` metric also won't get triggered when one namespace's traffic got increased.
- This covers OPS as well 
- Unit test
> Treat all namespace scoped resource exhausted as task processing user error

- go.mod
- go.sum
Upgrade API to the last tagged version to prepare for the release.
> Use tagged API lib

- common/persistence/sql/sqlplugin/interfaces.go
- common/persistence/sql/sqlplugin/mysql/plugin.go
- common/persistence/sql/sqlplugin/postgresql/plugin.go
- common/persistence/sql/sqlplugin/sqlite/plugin.go
- common/persistence/sql/store.go
Remove duplicate code: three implementations of `CreateAdminDB` were exactly identical to the respective `CreateDB`.
DRY.
> Remove NewSQLAdminDB

- service/history/api/updateworkflowoptions/api_test.go
- Added a test case for `nil` input
- Made some minor test tweaks
> Tweak UpdateWorkflowOptions handler tests

- service/history/api/recordactivitytaskstarted/api.go
- tests/activity_api_rules_test.go
Add code to "recordactivitytaskstarted" api to run workflow rules and pause activity if needed.
To cover scenario when workflow rule should prevent activity from starting. 
Add functional test specifically to this scenario.
> Pause activity in recordactivitytaskstarted

- proto/internal/buf.yaml
- Followup to remove a buf.yaml exception
> Remove temporary buf.yaml exception

- .github/workflows/linters.yml
- .gitignore
- .gitmodules
- Makefile
Remove `temporalio-dashboards` submodule. Checkout and extract the dashboard from `tar` instead.
Remove top-level `.gitmodules` file (visually cluttering the top-level of the repo).
> Remove .gitmodules

- common/persistence/persistence-tests/cluster_metadata_manager.go
- common/persistence/persistence-tests/setup.go
- common/persistence/persistence_rate_limited_clients.go
- common/persistence/persistence_retryable_clients.go
- common/persistence/tests/sqlite_test.go
- service/history/shard/context_impl.go
- service/history/shard/controller_impl.go
- service/matching/matching_engine.go
- service/worker/batcher/activities_test.go
WISOTT
_cherry-picked from https://github.com/temporalio/temporal/pull/5723 (can't be merged because our build process doesn't like contributions from a forked `main` branch)_
> Fix some comments

- service/history/replication/stream_receiver.go
cherry-picking https://github.com/temporalio/temporal/pull/7614
> Use Submit on replication task scheduler to avoid dangling task

- common/headers/caller_info.go
- common/rpc/interceptor/caller_info.go
- common/rpc/interceptor/caller_info_test.go
- Validate incoming caller info headers
- Validate incoming caller info headers
- Unit tests
- Very low. Those headers are only used if namespace level persistence rate limit is specified, which is disabled by default.
> Validate incoming caller info headers

- service/worker/workerdeployment/version_workflow.go
- WISOTT
- We were emitting error logs even on successful calls to `syncSummary` - I don't think we want that!
> don't emit error logs all the time in deployment version sync summary!

- common/api/metadata.go
Added `DispatchByNamespaceAndTaskQueue`, `DispatchByEndpoint` and `CompleteNexusOperation` to Nexus service methods metadata.
It's necessary for custom authorizers.
Fixes #7596
> Add missing Nexus API's to metadata

- .github/workflows/linters.yml
- .gitignore
- .gitmodules
- Makefile
This reverts commit 9cffbc016d160916d479e5dbd9cdfe2b7c26f2dd.
It broke a build action
> Revert "Remove .gitmodules (#7589)"

- common/metrics/config.go
- common/metrics/config_test.go
Removing unused references to m3.
Unused
Removed the code & test
> Remove unused m3 references

- go.mod
- go.sum
- tests/nexus_workflow_test.go
Upgrade temporalio/sdk to v1.34.0
> Upgrade temporalio/sdk to v1.34.0

- service/worker/workerdeployment/client.go
- service/worker/workerdeployment/util.go
- service/worker/workerdeployment/version_workflow.go
- service/worker/workerdeployment/workflow.go
- tests/worker_deployment_version_test.go
- WISOTT
- Better user-experience. 
- Note: I shall be sending a follow-up PR removing any errors returned to the sdk as`Internal` errors when they are supposed to be returned as `FailedPrecondition`.
- Modified tests to check for this specifically.
> fix cryptic error message on on DeleteVersion

- api/persistence/v1/chasm.pb.go
- chasm/task.go
- chasm/test_component_test.go
- chasm/tree.go
- chasm/tree_mock.go
- chasm/tree_test.go
- proto/internal/buf.yaml
- proto/internal/temporal/server/api/persistence/v1/chasm.proto
- Generate physical tasks
- Carryover cluster local task status during replication
- CHASM task support
- Added unit tests
> CHASM: Generate physical tasks and carry over physical task status

- chasm/field_test.go
- chasm/registrable_task.go
- chasm/registry_test.go
- chasm/task_mock.go
- chasm/test_library_test.go
- chasm/test_task_test.go
- chasm/tree.go
- chasm/tree_test.go
- Implement AddTask functionality for CHASM
- This PR is on top of https://github.com/temporalio/temporal/pull/7606
- Unit tests
> CHASM: implement AddTask

- chasm/test_component_test.go
- chasm/tree.go
- chasm/tree_test.go
Addressed few TODOs in `tree.go` (mainly around deserialized to interface).
The time has come.
> CHASM: address TODOs for deserialize to interface

- chasm/tree.go
CHASM: children iterator: change "walker" pattern to iterator. 
More idiomatic go. Plan to use it in few other places.
> CHASM: children iterator

- api/historyservice/v1/request_response.pb.go
- proto/internal/temporal/server/api/historyservice/v1/request_response.proto
- service/history/api/multioperation/api.go
- service/history/api/startworkflow/api.go
Added Workflow Status to history's StartWorkflowExecutionResponse.
To prepare for https://github.com/temporalio/api/pull/580.
Tests will be added in the functional tests once the API is merged.
> Status in StartWorkflowExecutionResponse

- config/dynamicconfig/development-xdc.yaml
- service/history/ndc/workflow_state_replicator.go
- service/history/ndc/workflow_state_replicator_test.go
Add event consecutive check when handling sync state for state based replication
More safe guard if source is not behaving correctly when sending events.
unit test
no risk
n/a
yes.
> Add event consecutive check when handling sync state

- service/history/api/multioperation/api.go
- service/history/api/startworkflow/api.go
- tests/update_workflow_test.go
> Fix NPE in Start Workflow

- api/historyservice/v1/request_response.pb.go
- proto/internal/temporal/server/api/historyservice/v1/request_response.proto
- service/frontend/workflow_handler.go
- service/history/api/multioperation/api.go
- service/history/api/startworkflow/api.go
- tests/workflow_test.go
Generate link in start workflow API
Generate links to the event resulted from calling `StartWorkflowExecution`.
> Generate link in start workflow API

- .github/workflows/linters.yml
Pass Github token to `arduino/setup-protoc` action.
Avoid rate limiting error:
```
Error: Error: API rate limit exceeded for 20.102.199.133. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
> Pass github token to arduino/setup-protoc action

- service/frontend/workflow_handler.go
- tests/reset_workflow_test.go
- tests/update_workflow_test.go
- tests/workflow_test.go
Added `Status` to StartWorkflowResponse.
See https://github.com/temporalio/api/pull/580
> Return workflow status from start

- chasm/field.go
- chasm/field_test.go
- chasm/fields_iterator.go
- chasm/fields_iterator_test.go
- chasm/tree.go
CHASM: extract generic fields iterator.
Thanks for the idea @lina-temporal! I believe iterator is better than "walker".
To reduce code duplication and improve error messages.
> CHASM: extract generic fields iterator

- chasm/tree.go
- chasm/tree_test.go
- common/testing/testvars/any.go
CHASM: complete `CloseTransaction` implementation.
CHASM workstream.
> CHASM: close transaction

- client/matching/client.go
- common/persistence/history_manager.go
- service/history/api/getworkflowexecutionhistory/api.go
- service/history/interfaces/mutable_state.go
- service/history/interfaces/mutable_state_mock.go
- service/history/ndc/state_rebuilder.go
- service/history/ndc/state_rebuilder_mock.go
- service/history/ndc/state_rebuilder_test.go
- service/history/ndc/workflow_state_replicator.go
- service/history/ndc/workflow_state_replicator_test.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- service/history/workflow/task_refresher.go
- service/history/workflow/task_refresher_mock.go
- service/history/workflow/task_refresher_test.go
- service/history/workflow_rebuilder.go
> Make 132.2 patch

- common/rpc/interceptor/redirection.go
- components/nexusoperations/frontend/handler.go
- service/frontend/nexus_handler.go
> Add NamespaceTag for RedirectAPIInvocation

- components/scheduler/invoker.go
- components/scheduler/invoker_executors.go
- components/scheduler/invoker_executors_test.go
- components/scheduler/invoker_tasks.go
Remove leftover license headers.
Follow up to #7689.
> Remove leftover license headers

- common/persistence/versionhistory/version_histories.go
- common/persistence/versionhistory/version_history_test.go
- service/history/ndc/workflow_state_replicator.go
- service/history/ndc/workflow_state_replicator_test.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- Support no event case in state replicator.
- CHASM runs won't have events.
- Unit tests
> CHASM: Non-Workflow Mutable State P3 State Replicator

- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/nexusoperations/frontend/handler.go
- components/nexusoperations/link_converter.go
- components/nexusoperations/link_converter_test.go
- service/history/api/startworkflow/api.go
- service/history/workflow/mutable_state_impl.go
- tests/nexus_api_test.go
- tests/nexus_workflow_test.go
- tests/workflow_test.go
Copy nexus link converter from sdk-go
> Copy nexus link converter from sdk-go

- common/dynamicconfig/constants.go
- service/history/api/startworkflow/api.go
- service/history/configs/config.go
- service/history/workflow/mutable_state_impl.go
- tests/nexus_workflow_test.go
- tests/workflow_test.go
Dynamic config to enable generating request id reference links
> Dynamic config to enable generating request id reference links

- api/adminservice/v1/request_response.pb.go
- proto/internal/temporal/server/api/adminservice/v1/request_response.proto
- service/frontend/admin_handler.go
- tools/tdbg/flags.go
- tools/tdbg/task_queue_commands.go
- tools/tdbg/tdbg_commands.go
Allow querying other subqueues with tdbg tq list-tasks.
Debugging and other operational tasks.
> Add subqueue to tdbg tq list-tasks

- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
Validate links in completion callbacks
Missed validation of links in #7697
> Validate links in completion callbacks

- service/history/api/namespace.go
- service/history/api/replication/generate_task.go
allow passive to generate replication tasks
We skip active on cluster check before generating replication tasks
> allow passive to generate replication tasks

- tests/testcore/dynamic_config_overrides.go
Functional tests: remove dual visibility write.
Tests passed so it is apparently not needed.
> Functional tests: remove dual visibility write

- chasm/collection.go
- chasm/fields_iterator_test.go
- chasm/test_component_test.go
- chasm/test_library_test.go
- chasm/tree.go
- chasm/tree_test.go
- common/util.go
CHASM: Collection support.
Time has come.
> CHASM: Collection support

- service/worker/replicator/namespace_replication_message_processor.go
- service/worker/replicator/replication_message_processor.go
- service/worker/replicator/replicator.go
Update worker replication error logging
> Update worker replication error logging

- docs/architecture/workflow-update.md
Workflow Update: update doc to reflect recent changes in #7296.
Keep internal doc up to date.
> Workflow Update: update doc to reflect recent changes in 7296

- temporal/environment/env.go
- temporal/environment/env_test.go
- tools/cassandra/main.go
- tools/cassandra/setup_task_tests.go
- tools/sql/main.go
- improve comments
- removed useless comments
- unexport constants
Long awaited refactoring.
> Cleanup environment variables helpers

- common/dynamicconfig/constants.go
- config/dynamicconfig/development-cass.yaml
- service/frontend/service.go
- service/frontend/workflow_handler.go
- tests/testcore/dynamic_config_overrides.go
- tests/xdc/activity_api_test.go
Enable activity commands - remove feature flag.
preparing for GA
> remove feature flag for activity commands

- service/worker/migration/catchup_workflow.go
only error message
Fix error message for catchup input validation
no risk
> Fix error message for catchup input validation

- common/dynamicconfig/constants.go
- service/history/api/multioperation/api.go
- service/history/configs/config.go
Reverts temporalio/temporal#7839 - no longer needed.
> Revert "Add MultiOperation error logging"

- chasm/field_test.go
- chasm/path_encoder.go
- chasm/path_encoder_test.go
- chasm/ref.go
- chasm/tree.go
- chasm/tree_test.go
- Implement CHASM path encoder
- CHASM work stream
> CHASM: path encoder implementation

- common/dynamicconfig/constants.go
- common/metrics/metric_defs.go
- service/history/configs/config.go
- service/history/replication/fx.go
- service/history/replication/stream_sender.go
Add config flag for replication rate limiter
> Add config flag for replication rate limiter

- tests/update_workflow_test.go
Add test case for Update-with-Start test for closing Workflow.
Regression testing/documentation.
> Add Update-with-Start test for closing Workflow

- api/persistence/v1/chasm.go-helpers.pb.go
- api/persistence/v1/chasm.pb.go
- chasm/context.go
- chasm/engine.go
- chasm/engine_mock.go
- chasm/field.go
- chasm/field_test.go
- chasm/ref.go
- chasm/ref_test.go
- chasm/registrable_component.go
- chasm/tree.go
- chasm/tree_mock.go
- chasm/tree_test.go
- proto/internal/temporal/server/api/persistence/v1/chasm.proto
- service/history/chasm_engine.go
- service/history/chasm_engine_test.go
- service/history/timer_queue_active_task_executor_test.go
- Properly Implement Ref() method and populate all necessary fields
- Refactor ComponentRef and related methods
- CHASM workstream
> CHASM: Implement Ref method

- chasm/tree.go
- chasm/tree_test.go
- Bug fix to makeValidationFn.
> [CHASM] fix makeValidationFn parameters

- service/history/configs/task.go
- service/history/queues/scheduler.go
- Using default priority weight if not specified
- In case new priority levels got introduced and break existing things
> Using default priority weight if not specified

- common/headers/version_checker.go
- Update `release/v1.28.0` server version
> Update release/v1.28.0 ServerVersion tag

- service/matching/matching_engine.go
> Remove unused cache field

- chasm/engine.go
- chasm/engine_mock.go
- chasm/fx.go
- service/history/chasm_engine.go
- service/history/chasm_engine_test.go
- service/history/fx.go
- service/history/handler.go
- service/history/outbound_queue_factory.go
- service/history/queue_factory_base.go
- service/history/queue_factory_base_test.go
- service/history/timer_queue_factory.go
- service/history/transfer_queue_factory.go
- temporal/fx.go
- tests/testcore/onebox.go
- tests/testcore/test_cluster.go
- Wire up CHASM implementations
- CHASM workstream
- No risk. CHASM logic is still disabled via dynamic config
> [CHASM] Wire up

- common/persistence/tests/util.go
- Always run persistence tests
- Improve test coverage.
> CHASM: Always run persistence tests

- service/matching/physical_task_queue_manager.go
Include a log tag to differentiate between backlogManager (and subcomponents) and priBacklogManager.
Help debugging.
> Add log tag for matching backlog implementation

- service/history/chasm_engine.go
- service/history/fx.go
- Export engine fx module
- Needed in other repos
> CHASM: export engine fx module

- tools/cassandra/main.go
- tools/sql/main.go
> Use server version for sql and cassandra tools

- common/dynamicconfig/constants.go
- service/frontend/namespace_handler_test.go
The feature is moving to public preview.
> Turn on eager workflow start by default

- service/matching/backlog_manager_test.go
- service/matching/fair_backlog_manager.go
- service/matching/pri_backlog_manager.go
Port changes to priBacklogManager (from main) to fairBacklogManager on feature branch.
Tests don't work without this.
> Port backlog manager changes

- service/matching/fair_task_reader.go
Fix several bugs in fairTaskReader:
1. If we read tasks below the ack level, we should ignore them. This can happen if a read is concurrent with ack level movement.
2. If we drain the backlog completely, we can move the read level to the ack level. This maintains the invariant that the in-memory buffer is the range (ack level, read level].
3. If we read a task that we have already acked, we can ignore it (previously we were only ignoring unacked tasks). This happens if we evict and then reread ranges.
4. When we evict tasks that don't fit in the buffer because we inserted ones under them, we also have to evict acks above the end of the new buffer, otherwise we'll see those acks and use them to jump the ack level over the tasks that we evicted. (The code here is not the cleanest, I have an …
> Matching fairness: fix bugs in fairTaskReader

- common/persistence/visibility/visibility_manager_dual.go
Perform writes to dual visibility mode concurrently instead of sequentially.
Fixed shadow read context: shadow read requests were using the same context as the main request, so if the main request finishes earlier, the context would close, and fail the shadow request immediately. This PR copies the deadline so it has the same timeout, but it's a new context so it won't be using the main context.
General refactor of dual visibility code.
Each write buffers a Elasticsearch request, so executing sequentially makes the overall visibility task latency much higher.
> Perform concurrent writes with dual visibility

- go.mod
- go.sum
- Upgrade api to v1.51.0
- Upgrade api to v1.51.0
> Upgrade api to v1.51.0

- api/persistence/v1/executions.pb.go
- common/persistence/serialization/task_serializer.go
- common/persistence/serialization/task_serializer_test.go
- common/persistence/visibility/manager/visibility_manager.go
- proto/internal/temporal/server/api/persistence/v1/executions.proto
- service/history/deletemanager/delete_manager.go
- service/history/deletemanager/delete_manager_test.go
- service/history/interfaces/shard_context.go
- service/history/interfaces/shard_context_mock.go
- service/history/shard/context_impl.go
- service/history/shard/context_test.go
- service/history/tasks/delete_visibility_task.go
- service/history/visibility_queue_task_executor.go
- service/history/visibility_queue_task_executor_test.go
- Remove unused CloseTime field in delete visibility logic
- Clean up code
> Remove unused CloseTime field in delete visibility logic

- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
Use the default reason and identity for user-initiated workflow termination requests.
This is to make it easier to tell whether workflow is terminated by user or internal system (e.g. workflow terminated by history service due to history size limt)
> Default reason and identity for user-initiated workflow termination requests

- api/persistence/v1/executions.pb.go
- common/persistence/serialization/task_serializer.go
- common/persistence/serialization/task_serializer_test.go
- common/persistence/visibility/manager/visibility_manager.go
- proto/internal/buf.yaml
- proto/internal/temporal/server/api/persistence/v1/executions.proto
- service/history/deletemanager/delete_manager.go
- service/history/deletemanager/delete_manager_test.go
- service/history/interfaces/shard_context.go
- service/history/interfaces/shard_context_mock.go
- service/history/shard/context_impl.go
- service/history/shard/context_test.go
- service/history/tasks/delete_visibility_task.go
- service/history/visibility_queue_task_executor.go
- service/history/visibility_queue_task_executor_test.go
Reverts temporalio/temporal#8117
> Revert "Remove unused CloseTime field in delete visibility logic"

- proto/internal/buf.yaml
- Renable buf breaking check for executions.proto
> Renable buf breaking check for executions.proto

- .github/workflows/run-tests.yml
- develop/github/docker-compose.yml
Enable functional tests with OpenSearch 2 in CICD
Run compatibility with OpenSearch 2
> Enable functional tests with OpenSearch 2

- common/cluster/frontend_http_client.go
Picking HTTP request forwarding fix to release branch so that it can be referenced in our nightly pipelines. Issue is not serious enough to warrant a patch release at this time.
> Pick http forwarding fix

- service/history/workflow/update/errors_failures.go
> Fix typo in unprocessedUpdateFailure

- service/history/replication/executable_task.go
Log replication task details when processing takes too long
For operator investigation
no risk.
> Add log for slow replication tasks

- common/metrics/grpc_stats.go
- common/metrics/metric_defs.go
- common/rpc/multistats.go
- service/frontend/fx.go
- service/fx.go
- temporal/fx.go
Added gRPC connection metrics.
To gain insights into gRPC connections for operational purposes.
I'll be looking at the metric in our nightly pipeline to verify.
> gRPC connection metrics

- chasm/test_component_test.go
- chasm/tree_test.go
- Title
- Added a test since we intend to use this functionality.
> [CHASM] Add a test to show serializing/deserializing a pointer-to-an-interface works

- go.mod
- go.sum
Update api version to v1.53.0.
New api release.
> Updating api version to v1.53.0

- common/dynamicconfig/collection.go
Uses a `sync.Map` instead of explicit locking for the dynamic config cache.
This is a very read-heavy map that is used under high concurrency. Protecting it with a single lock can cause poor performance due to contention. A `sync.Map` is designed to handle this usage pattern much better than a map protected by a lock.
There is no change in functional behavior and no added risk of deadlocks or contention.
> Avoid locking when converting dynamic config values

- docs/architecture/workflow-lifecycle.md
- Add diagrams for server side states as workflows make progress
> Add more diagram for workflow lifecycle doc

- tests/callbacks_test.go
Adjusted the shutdown logic for Nexus completion servers in callback functional tests.
Reduce flakes.
> Adjust Nexus test server shutdown logic

- service/worker/migration/activities.go
- service/worker/migration/activities_test.go
- service/worker/migration/fx.go
- **Abstract workflow verifier for force replication workflow**
- **fix**
Abstract workflow verifier for force replication workflow
To allow user plugin custom verification logic
no risk.
> Abstract workflow verifier for force replication workflow

- service/history/historybuilder/history_builder.go
- service/history/historybuilder/history_builder_categorization_test.go
- service/history/historybuilder/history_builder_test.go
- service/history/workflow/mutable_state_impl.go
Added namespace tag to activity payload size metrics.
Gives us better searchability when investigating payload size.
> Added namespace tag to activity payload size metrics.
