temporalio/temporal

.github/workflows/trigger-publish.yml

Update trigger-publish GHA token management via GitHub App.
Following the https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow
**Why?**
Switching to org-level management
CI

Update trigger-publish GHA

---

service/history/api/consistency_checker.go
service/history/shard/context.go
service/history/shard/context_impl.go
service/history/shard/context_mock.go
service/history/shard/context_test.go
service/history/shard/controller_impl.go
service/history/shard/controller_test.go

When a shard context is stopped, it stores whether or not that was due to a shard ownership lost (SOL) error.
**Why?**
Upcoming changes to the shard controller will delay re-acquiring a shard that recently had an SOL error.
Tested locally & ci, and in a staging environment (with other changes).
None; this change is only used by tests.
No.

add stop reason for context

---

.golangci.yml

I disabled the `confusing-naming` linter, and I made the `unhandled-error` linter ignore calls to `fmt.Println`.
**Why?**
I disabled the `confusing-naming` linter because it's very common to have an exported method that calls an unexported method of the same name as a helper, and I don't find it confusing at all. I made the `unhandled-error` linter ignore calls to `fmt.Println` because you're kind of SoL in that case any way--what are you going to do if you can't even print?
I have a branch that violated these two rules, and then I ran `make lint` and saw the errors go away.

Disable confusing-naming linter and tune unhandled-error

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/tasks/archive_execution_task.go
service/history/tests/vars.go
service/history/workflow/task_generator.go
service/history/workflow/task_generator_test.go
tests/archival_test.go

I removed the durable archival flag which switches between the archival workflow and the archival queue.
**Why?**
Because we just use the archival queue unconditionally now, and the old code path is something like 5K lines, so being able to delete it will slim us down a lot.
Durable archival was [released in February](https://github.com/temporalio/temporal/releases/tag/v1.20.0) as part of 1.20.0. There was one bug that caused schedules-based workflows to not be archived, but that was fixed. Other than that, there have been no issues, and so I think it's been long enough, and it's been battle-tested enough that we can now remove its predecessor.
If there's a bug in the archival queue, we won't have a way to switch back to the …

Remove durable archival flag

---

common/cache/cache.go
common/cache/lru.go
common/cache/lru_test.go

I added a Clock to our LRU cache, and I modified our tests to use that instead of time.Sleep.
**Why?**
To make our tests faster, and to support time-skipping in the future
A flaky test here would probably make it hang forever. If someone uses clock.Sleep instead of clock.Advance in the future, that can happen.

Add a Clock option to our LRU cache

---

service/history/shard/context.go
service/history/shard/context_factory.go
service/history/shard/context_impl.go
service/history/shard/context_mock.go
service/history/shard/context_test.go
service/history/shard/context_testutil.go
service/history/shard/controller_impl.go
service/history/shard/controller_test.go
service/history/shard/fx.go

Edit: I moved this from "draft" to real PR.
This adds a shard context factory, which returns a `ControllableContext` that is the existing context interface plus the Pingable & FinishStop methods that the controller needs (but api request handling doesn't). The shard controller uses that to create contexts, instead of calling `newContext` directly.
This does not update the shard controller tests. The tests in controller_test.go should eventually change to test behavior at the new interface boundary, and some of the existing tests ought to be moved, likely to context's tests. 
**Why?**
It simplifies the shard controller, and removes the duplicate logic used to create a controller between the provider and `NewTestController`.
Unit & CI.
**Potential …

use a factory to create shard contexts

---

common/metrics/metric_defs.go
common/metrics/panic.go
service/history/handler.go

Emit panic metric if history service handler experience a panic
I want to emit metrics when handler experience panic so that I can create a dedicate alert.
this change should not change current behavior, only emit the new metric

emit history service panic metric for all requests

---

common/dynamicconfig/constants.go
service/frontend/fx.go
service/frontend/fx_test.go
service/frontend/service.go

I added an optional rate limit on the total RPS to across all frontend hosts.
**Why?**
To make it easier to write rate limits based on database resources, rather than frontend host resources.
I added a test which creates a gRPC server for the workflow service with this rate limiter, and then I sent traffic to it. I verified that the different rate limit configurations behave as-expected, and then I looked at the test coverage [here](https://buildkiteartifacts.com/1f9c9f7c-4305-42bc-b1ef-8ce362b961c6/a9393275-f704-4056-af35-70c39e6a54d3/0189288c-1b22-4c5a-9398-f12a57dc7e3f/0189288c-2998-4a77-9911-0727ca40fb85/.coverage/summary.out.html?response-content-type=text%2Fhtml&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQPCP3C7L6VEAMXXS%2F2023070 …

Add frontend global RPS limit

---

client/admin/metric_client.go
common/metrics/metric_defs.go
service/frontend/admin_handler.go
service/frontend/operator_handler.go

- service_request, latency, and errors metrics are already emitted by [telemetry interceptor](https://github.com/temporalio/temporal/blob/master/common/rpc/interceptor/telemetry.go#L148). Remove additional emits in api handler.
- Remove history size double emission since the metric is a histogram and supports aggregation. The existing code will actually cause one metrics name to have different set of tags.
- Remove unused metric scope definition.
**Why?**
- Fix metrics double emission in admin and operator handler
- Lose metrics for some admin and operator apis.
- No.

Fix metrics double emission in admin and operator handler

---

common/searchattribute/defs.go

Add BuildIds predefined search attribute to 1.20.x
**Why?**
In a rollback scenario, after upgrading to 1.21 and then back to 1.20, the new predefined search attribute BuildIds wouldn't be understood by the older version and would block visibility tasks. Adding this to the type map will make it able to process workflows with the search attribute.
manual rollback (cassandra+es, mysql, postgres)

Add BuildIds predefined search attribute

---

common/metrics/metric_defs.go
service/worker/migration/activities.go
service/worker/migration/activities_test.go
service/worker/migration/force_replication_workflow.go
service/worker/migration/force_replication_workflow_test.go
service/worker/migration/fx.go
service/worker/migration/handover_workflow.go

Add a verification step to check if generated workflow executions exist on target cluster. 
**Why?**
To ensure all generated replication tasks have been successfully applied on target cluster.
Unit tests + cluster tests
No

Add verification of replication tasks in force replication

---

common/persistence/persistence_metric_clients.go

* excluding history APIs that go to s3 from persistence health signals
* including time to record/aggregate health signals in persistence metrics
**Why?**
So that issues with s3 do not slow down the whole system
Existing tests
None
No

Exclude history APIs from persistence health signals

---

service/frontend/fx_test.go
service/frontend/service.go

We have cluster-wide and per-instance limits for some resources. If the cluster-wide limit is set, we compute the effective limit to be `globalLimit/numHosts`. However, we get the `numHosts` variable from the membership service resolver object. In some cases, this may return 0 hosts, and we want to avoid a division-by-zero error, so we interpret this as 1 host. However, this will cause the host to use the entire cluster-wide limit, which could cause us to exceed our desired rate limits. 
**Why?**
To avoid us DoS'ing ourselves. I also think this behavior is more intuitive.
There's already a test case for this. I watched it fail before this change, and then I fixed it.

Ignore global rate limit if there are no hosts

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/workflow/cache/cache.go

- Allow configurating history cache non-user context lock timeout
**Why?**
- Background task used to wait 1s on workflow lock. In 1.21 release we changed this to 500ms and effectively increased the penalty on workflows that schedules multiple activities or childworkflows at once.
- 500ms should be enough but just in case this change causes any negative effect in production, make it configurable so that we don't need to rollback. 
- Since most likely we don't need to change this value, to prevent accessing dynamic config too much in hot code path, changes to this config requires a service restart (actually shard load) to take effect.
- N/A
- yes

Allow configurating history cache non-user context lock timeout

---

go.mod
service/worker/migration/activities.go
service/worker/migration/force_replication_workflow.go
service/worker/migration/force_replication_workflow_test.go

**Why?**
Currently, the workflow will wait for all GenerateReplicationTasks activity to complete. The change will fail the workflow fast if any GenerateReplicationTasks activity failed. 
unit test and cluster test. 
No.

Fail force-replication fast if any GenerateReplicationTasks/GenerateAndVerifyReplicationTasks activity returns error

---

common/persistence/visibility/store/elasticsearch/client/client.go
common/persistence/visibility/store/elasticsearch/client/client_mock.go
common/persistence/visibility/store/elasticsearch/client/client_v7.go
common/persistence/visibility/store/elasticsearch/visibility_store.go
common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go

Add support for ES Scroll for Scan API.
This is a revert of https://github.com/temporalio/temporal/pull/4223 and https://github.com/temporalio/temporal/pull/4249.
**Why?**
ES 7.10 hosted in AWS is the OSS flavor, not the default one which includes support for PIT.
Add unit tests.
No.

Add support for ES Scroll for Scan API

---

service/history/consts/const.go
tests/signal_workflow_test.go

Do not use Unavailable error type for expected error cases.
**Why?**
To correctly reflect the error case.
eye_balls
No
No

Do not use Unvailable as error type for expected error cases

---

common/persistence/visibility/manager/visibility_manager.go
common/persistence/visibility/manager/visibility_manager_mock.go
common/persistence/visibility/store/elasticsearch/visibility_store.go
common/persistence/visibility/store/errors.go
common/persistence/visibility/store/sql/visibility_store.go
common/persistence/visibility/store/standard/cassandra/visibility_store.go
common/persistence/visibility/store/standard/sql/visibility_store.go
common/persistence/visibility/store/standard/visibility_store.go
common/persistence/visibility/store/visibility_store.go
common/persistence/visibility/store/visibility_store_mock.go
common/persistence/visibility/visibility_manager_dual.go
common/persistence/visibility/visibility_manager_impl.go
common/persistence/visibility/visibility_manager_rate_limited.go
common/persistence/visibility/visiblity_manager_metrics.go
common/searchattribute/validator.go
common/searchattribute/validator_test.go
service/frontend/workflow_handler.go
service/history/command_checker_test.go
service/history/history_engine.go
service/history/history_engine2_test.go
service/history/workflow_task_handler_callbacks_test.go

Add custom search attributes validation to `VisibilityStore` interface, and implements ES constraints.
**Why?**
Each store can have different constraint that might reject the value when inserting.
Eg: In ES, dates can only be between 1970 and 2262.

Custom search attributes validation per store

---

common/future/future_test.go

- Add runtime.gosched when future is not ready in future impl test
**Why?**
- Currently futureSuite can take 10min or 20mins on buildkite, e.g: https://buildkite.com/temporal/temporal-public/builds/11174#0189705c-75ea-40c8-95d7-38db366d4012/286
```
ok  	go.temporal.io/server/common/future	614.020s	coverage: 66.7% of statements
```
- To help golang scheduler switch goroutine.
- Running tests multiple time in buildkite and local and observed a time difference
Before
```
temporal|master ⇒ go test -v -race -count=1 ./common/future/... 
=== RUN   TestFutureSuite
=== RUN   TestFutureSuite/TestGetWhenContextCanceled
=== RUN   TestFutureSuite/TestSetGetReady_Parallel
=== RUN   TestFutureSuite/TestSetGetReady_Sequential
=== RUN …
```

Fix future TestSetReadyGet_Parallel

---

common/metrics/metric_defs.go
service/worker/migration/activities.go
service/worker/migration/activities_test.go
service/worker/migration/force_replication_workflow.go
service/worker/migration/force_replication_workflow_test.go

Divide GenerateAndVerifyReplicationTasks activity into two activities: GenerateReplicationTasks (reuse previous one) and VerifyReplicationTasks
**Why?**
Based on cluster tests, GenerateReplicationTasks is expensive (10ms latency for `GenerateLastHistoryReplicationTasks` call). In previous implementation, VerificationTasks runs after GenerateReplicationTasks and we only get ~60 RPS for GenerateAndVerifyReplicationTasks. By dividing the two, we can achieve ~100 RPS VerifyReplicationTasks for a single activity (bottleneck is still GenerateReplicationTasks because of 10ms latency). 
Also moved the special handling of WF not_found on target to VerifyReplicationTasks, which reduced # of `DescribeMutableState` call on source cluster. In previous implementation, …

Execute VerifyReplicationTasks as an individual activity

---

tests/versioning_test.go

- Fix flaky `TestDisableUserData_QueryTimesOut` (it should actually fail with `FailedPrecondition`)
- Other small test cleanups
**Why?**
Fixes #4640
is tests
Also tried a variation where the test workflow sleeps instead of completing. In that case the query ran on the sticky queue so it needed more sleep or to reset sticky to pass. I don't think we need to keep both variation though.

Fix flaky versioning integration test

---

service/worker/migration/force_replication_workflow_test.go

```
go test ./service/worker/migration -run TestForceReplicationWorkflow_VerifyReplicationTaskNonRetryableError -count 1000 -json | jq -s 'map(select(.Test and .Action == "pass")) | length'
1000
```
**Why?**

Fix flaky TestForceReplicationWorkflow_VerifyReplicationTaskNonRetryableError

---

service/worker/migration/force_replication_workflow.go

**Why?**
GenerateReplicationTasks and VerifyReplicationTasks runs in parallel. VerifyReplicationTasks runs every 2s. Verification is not instantaneous, which means for every batch, Verification can delay at least 5s. Increase batch size, reduce the ration of the delay in batch processing. 
Before the change, RPS for GenerateReplicationTasks + VerifyReplicationTasks is 30 RPS. With the change RPS is 90. 
Cluster test. 
Yes.

 Restore defaultListWorkflowsPageSize back to 1000 (from 100)

---

service/history/timer_queue_standby_task_executor.go
service/history/transfer_queue_standby_task_executor.go

* Return nil instead of task discarded error if namespace is invalid locally
**Why?**
Returning task discarded error will make metrics confusing
N/A
N/A
N/A

Return nil instead of task discarded error if namespace is invalid locally

---

tools/tdbg/commands.go

* Fix tdbg unable to dump all workflow raw history issue
**Why?**
Bugfix
N/A
N/A
N/A

Fix tdbg unable to dump all workflow raw history issue

---

.github/workflows/goreleaser.yml

Fixed Go version string.
**Why?**
The recommendation is based on the YAML parser's behavior, which interprets non-wrapped values as numbers and, in the case of version 1.20, trims it down to 1.2, which may not be very obvious.
GHA
Unknown
Revert

Fix Go version string goreleaser.yml

---

service/worker/replicator/namespace_replication_message_processor.go
service/worker/replicator/replicator.go
service/worker/service.go

- Handle `REPLICATION_TASK_TYPE_TASK_QUEUE_USER_DATA` in `putNamespaceReplicationTaskToDLQ`.
- Drop user data replication tasks for unknown namespaces.
**Why?**
In case the replication task cannot be applied, put it in the DLQ instead of blocking the namespace replication queue.
Dropping tasks for unknown namespaces seems desirable in cases where different namespaces are replicated to different sets of clusters using the global namespace replication queue.
I have not, there doesn't seem to be any existing tests for this path.
I can add some unit tests if reviewer feels it's worth it.

Put user data replication tasks in DLQ

---

service/history/shard/ownership_scaled_rate_burst.go
service/history/shard/ownership_scaled_rate_burst_test.go

I added a `shard.OwnershipScaledRateBurst`, which scales the `Rate` and `Burst` functions of a `quotas.RateBurst` object by the percentage of shards owned by the current history host, and a constant scale factor.
**Why?**
We will soon be adding some new rate limiters to the history service which need to scale with the workload of the current host.
I added 100% test coverage.
None. These are just additions.
No.

Add shard.OwnershipScaledRateBurst

---

common/quotas/delayed_request_rate_limiter.go
common/quotas/delayed_request_rate_limiter_test.go
common/quotas/noop_request_rate_limiter_impl_test.go
common/quotas/request_rate_limiter_delegator.go
common/quotas/request_rate_limiter_delegator_test.go

I added `quotas.DelayedRateLimiter`, which adds a delay before an input `quotas.RateLimiter` actually takes effect. I also added some utilities to make its implementation easier. The delayed rate limiter depends on the new rate limiter delegator and no-op rate limiter structs.
**Why?**
In some cases in the history service, we want to delay rate limiters for a short period after startup.
There is 100% test coverage for the new code.
None. These are just additions.
No.

Add quotas.DelayedRateLimiter

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/shard/controller_impl.go
service/history/shard/controller_test.go

This is a followup on a few review items from https://github.com/temporalio/temporal/pull/4659 :
* reduce number of configs needed for shard linger
* avoid creating static config functions in tests
* add some clarity to the max shard linger time limit
**Why?**

enable shard linger with time limit config

---

common/metrics/metric_defs.go
common/metrics/tags.go
service/matching/matching_engine.go

- Refactor loaded task queue gauge
- Call `tqm.Start()` and manage loaded task queue gauge outside of task queue map lock
- Add `versioned` tag representing whether a loaded tqm is for a specific version set
**Why?**
- Less contention on lock
- Get more data about how much feature is used
Existing tests can validate the refactoring, the metric is just a metric
For a versioned tqm, this counts it once as "unversioned" and once per version set as "versioned". That corresponds closely to the current implementation, but is a little unintuitive and could be misinterpreted.
If we change the implementation to do something like count a a versioned tqm once as "versioned" and not count version sets independently at all, then the …

Add versioned tag to loaded task queue gauge

---

service/history/shard/controller_impl.go
service/history/shard/controller_test.go
service/history/shard/fx.go
service/history/shard/ownership_based_quota_scaler.go
service/history/shard/ownership_based_quota_scaler_test.go
service/history/shard/ownership_test.go

I added code to the history/shard package which supplies the shard controller to the ownership-based rate limit quota scaler, so that it can be used to get the shard count. Basically, this PR adds the plumbing needed to propagate the shard count from the shard controller to the quota scaler, so that clients can just grab an `OwnershipBasedQuotaScaler` from the fx graph, and then call `scaler.ScaleRateBurst(rb)` without thinking about any other dependencies.
**Why?**
So that we can have rate limit quotas in the history service that scale with the approximate workload of the service.
I added tests which verify that shard counts are propagated to subscribers whenever acquire shards completes. I also verified that this does not block if the …

Provide a shard ownership-based rate limit quota scaler from the history/shard package

---

common/persistence/client/targeted_fault_injection.go
tests/testdata/acquire_shard_deadline_exceeded_error.yaml
tests/testdata/acquire_shard_eventual_success.yaml
tests/testdata/acquire_shard_ownership_lost_error.yaml

- Added `ResourceExhausted` and `Unavailable` errors to target fault injector error factory.
- Small renames.
**Why?**
To support more fault testing scenarios such as persistence rate limiting.
Run locally.
No risks.
No.

Add more errors to targeted fault injector

---

common/metrics/metric_defs.go
service/worker/migration/activities.go
service/worker/migration/activities_test.go
service/worker/migration/force_replication_workflow.go
service/worker/migration/force_replication_workflow_test.go

Reducing heart beat size (current payload size is 26K for 1000 executions). 
**Why?**
unit tests + cluster tests 

Reduce the heartbeat size of VerifyReplicationTasks activity

---

common/authorization/frontend_api.go

Add `GetWorkerBuildIdCompatibility` and `GetWorkerTaskReachability` to the read-only namespace API list.
**Why?**
To make these accessible to read-only clients.

Add worker versioning calls to read-only namespace APIs for authorizer

---

service/frontend/workflow_handler.go

Log actual error for get history data loss events

---

service/matching/task_reader.go
service/matching/task_validation.go
service/matching/task_validation_test.go

* Matching task validation
* Active namespace: try to dispatch first, then validate
* Passive namespace: try to validate first, if task is created long time ago
**Why?**
Speed up passive task validation
UT
N/A
N/A

Speed up passive task validation

---

service/matching/db.go
service/matching/matching_engine.go
service/matching/task_queue_manager.go
service/matching/task_queue_manager_test.go
tests/versioning_test.go

Instead of dropping versioned tasks when user data (and thus versioning) is disabled, send them to a "dlq" where they can be recovered later.
**Why?**
Simplify recovery from a situation where user data was turned off while versioned workflows were running. Note that the "dlq" will not be automatically loaded, so if the switch was disabled for > 5 minutes and then enabled, it's possible that the dlq taskQueueManager could be unloaded and the tasks would not be dispatched. To handle this, the dlq task queues can be manually loaded with any rpc, e.g. `DescribeTaskQueue`. This is still a semi-manual procedure, but better than refreshing workflow tasks, since it's easier to determine which task queues may be affected compared to workflows.
modified …

Send versioned tasks to dlq when user data disabled

---

Makefile

- Update `MAIN_BRANCH` to `main`. This is used by `goimports` and `lint` targets.
- Move `MERGE_BASE` and `MODIFIED_FILES` to target-specific variables on `goimports`, which is the only target that uses them. This saves two useless `git` invocations per run.
**Why?**
Keep Makefile up to date, optimize common operations.
manually

Update main branch in Makefile

---

common/metrics/metric_defs.go
service/worker/migration/activities.go
service/worker/migration/activities_test.go
service/worker/migration/force_replication_workflow.go

Source and target cluster handles workflow retention separately. For a workflow which is abort to be deleted,
it may be already deleted on target cluster but still exist on source, which cause verification delay.
We skip workflow of which retention time is close to current time to continue the verification.
**Why?**

Continue replication verification by skipping workflow which should be or soon to be deleted

---

service/worker/scheduler/workflow.go
service/worker/scheduler/workflow_test.go
tests/schedule_test.go

Enable changes from #4602 and #4685 
**Why?**
Fix bugs and operational issues
Existing tests from those PRs are re-enabled.
More bugs in schedule workflow logic that we'd need to work around

Enable new schedule workflow logic

---

service/history/workflow/mutable_state_impl_test.go
service/history/workflow/workflow_task_state_machine.go

In some cases we write a new WorkflowTaskScheduledEvent right before a WorkflowTaskStartedEvent in RecordWorkflowTaskStarted. In that case, the task queue name comes from RecordWorkflowTaskStarted, but that name comes from matching and may be a specific task queue partition, not the base name. We should write only the base name.
**Why?**
Fixes #4557
Unit test

Clean task queue name from matching before writing to WorkflowTaskScheduledEvent

---

common/dynamicconfig/constants.go
common/rpc/interceptor/concurrent_request_limit.go
common/rpc/interceptor/concurrent_request_limit_test.go
service/frontend/configs/quotas.go
service/frontend/fx.go
service/frontend/service.go

I added a new dynamic config flag called `frontend.globalNamespaceCount` which limits the number of concurrent pollers across the cluster.
**Why?**
Because the per-instance limit doesn't work well if there are many instances.
I added global instance limit tests to the concurrent request limit interceptor.
This is disabled by default, so it should have no behavioral impact unless turned on explicitly.
No.

Add frontend.globalNamespaceCount

---

service/matching/db.go
service/matching/matching_engine_test.go
service/matching/task_queue_manager.go

- Use a new user data state for "closed"
- Don't leave the channel closed
**Why?**
Avoids any possible race condition that might lead to double-close, and also returns a clearer error.
New unit test, ran existing unit test 50+ times

Avoid potential double close on userDataChanged

---

service/matching/matcher.go
service/matching/matching_engine.go
tests/activity_test.go
tests/taskpoller.go
tests/workflow_test.go

- Make `errNoTasks` private
- Remove unused `errPumpClosed`
- Give test framework taskpoller its own error
**Why?**
There's no reason these errors should be linked
Ran integration tests

Clean up some matching errors

---

service/frontend/configs/quotas.go

Adjust some API priorities. PollWorkflowExecutionUpdate should be low priority. RespondWorkflowTaskFailed and RespondQueryTaskCompleted should be the same priority as other Respond APIs.
**Why?**
PollWorkflowExecutionUpdate is not high priority API.
eye balls
No
No

Adjust API priorities

---

common/util.go

- Reduce frontend handler retry max attempts to 2
**Why?**
- https://github.com/temporalio/temporal/issues/4733
- 5 is too much since other layer will retry as well. e.g. persistence will retry 2 times, so it used to be 5*2 (and due to the max attempts bug 6*3)
- This value for frontend is currently higher than other handler because there's no frontend client retry layer, but actually our sdk will still perform retry which acts like the frontend client. 

Reduce frontend handler retry max attempts

---

common/backoff/retry_test.go
common/backoff/retrypolicy.go
common/backoff/retrypolicy_test.go
service/history/shard/context_test.go

- Fix retry policy max attempts calculation.
- NOTE: this is not related to activity/workflow retry, they have the correct behavior. See: https://github.com/temporalio/temporal/blob/main/service/history/workflow/retry.go#L94
**Why?**
- https://github.com/temporalio/temporal/issues/4732
- Updated unit test
- One less retry attempt for system failures.

Fix retry policy max attempts

---

service/matching/matching_engine.go
service/matching/task_queue_manager.go

Make `RedirectToVersionedQueueFor{Add,Poll}` return a tqm directly. This is just refactoring, almost no behavior changes (in one specific case, query with user data disabled, it may do an extra task queue load).
**Why?**
Refactoring in advance of future work.
Existing tests

Move getTaskQueueManager call into redirect methods

---

service/history/queues/queue_base.go
service/history/queues/queue_base_test.go

- A follow up of https://github.com/temporalio/temporal/pull/4528 to make sure we won't call range completion with 0 (empty) exclusive max task key. Otherwise persistence layer will reject the request and cause queue processor to skip persisting its state.
- ^ issue only happens in very care case (task processing doesn't make any progress for a new clsuter) and even if it happens there's no actual impact. Once the problem on the task processing side is fixed, the errors will be gone automatically. 
**Why?**
- see above
- Added unit test.

Improve task range completion prerequisite check

---

client/history/client.go
client/history/client_gen.go
cmd/tools/rpcwrappers/main.go

- Extension of #4708: error if more than one field with the desired name is found.
- Add explicit ignore list to handle known cases.
**Why?**
Prevent future bugs.
Ran and saw no code changes (except for moving some code back into `client_gen.go`) + existing integration tests.

Make client code generation safer

---

common/persistence/visibility/store/sql/query_converter_sqlite.go
common/persistence/visibility/store/sql/query_converter_sqlite_test.go

Fix SQLite FTS query expression builder when token contain dashes.
**Why?**
Dash (-) is a special char in the FTS expression, so the token need to be quoted to be escaped.
https://github.com/temporalio/temporal/issues/4729
Followed the repro instructions in the issue above, and it doesn't repro anymore, ie., no errors are thrown.
No.
No.

Fix SQLite FTS query expression with dashes

---

service/history/consts/const.go

- Turn ErrWorkflowClosing into a retryable error: resource exhausted with workflow busy cause.
- The error means workflow is about to close so the operation can not be applied at this time. But the operation will be able to be applied if workflow continues as new or get rejected if workflow completes. and by retrying, hopefully customer won't see the error (depending how fast they process their workflow task). 
**Why?**
- so that user doesn't have to retry on their end in most cases.
- resource exhausted error also won't be retried by service handler.
- Existing functional test

Turn ErrWorkflowClosing into a retryable error

---

common/metrics/otel_metrics_handler.go

- Register new callbacks for otel gauge only once instead of at each record. (We need callbacks because otel doesn't have a synchronous gauge yet, but it should happen soon and then we can get rid of this.)
- A few small optimizations to `attribute.Set` handling.
**Why?**
The current code seems to be leaking memory and causing other problems.
Tested on local machine with frequent scrapes for a couple hours, saw no slowdown. Also diffed scrape before/after change.

Improve otel gauge memory usage

---

api/persistence/v1/task_queues.pb.go
proto/internal/temporal/server/api/persistence/v1/task_queues.proto
service/matching/matching_engine.go
service/matching/matching_engine_test.go
service/matching/task_queue_manager.go
service/matching/version_sets.go

Load task queue managers for demoted version set ids
**Why?**
To handle the situation where we guess a set id for an unknown build id and end up with multiple set ids for a set (described in more detail in a comment)
New unit test (integration tests will follow with a later PR)

Load task queue managers for demoted version set ids

---

common/metrics/metric_defs.go
service/worker/migration/activities.go
service/worker/migration/activities_test.go

Previous logic skip workflow of which retention is within a range of current time. But we actually just need to skip workflow already passed retention time. 
**Why?**

Skip verifying workflow which has already passed retention time

---

service/worker/migration/activities.go

During force replication, namespace should exist on remote (target cluster). If namespace doesn't exist (due to operator error e.g.,), fail VerifyReplicationTasks activity fast. Otherwise, workflow will retry VerifyReplicationTasks activity infinitely. 
**Why?**

Return NonRetryableApplicationError if Namespace is not found on remote cluster during verify

---

go.mod
go.sum

Update API to v1.24.0

---

CONTRIBUTING.md
Makefile

Replace tctl with cli in CONTRIBUTING.md
Create update-cli Make target
**Why?**
We're deprecating tctl in v1.22
tested the update-cli make target
Nothing
No

Replace tctl with cli in CONTRIBUTING.md and Makefile

---

common/cache/lru.go

- Improve cache error type
**Why?**
- Return right error type to help system better handle the error: avoid unnecessary retries and retry slower.
- https://github.com/temporalio/temporal/issues/3802

Improve cache error type

---

service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_rebuilder.go
service/history/workflow/mutable_state_rebuilder_test.go
service/history/workflow/task_generator.go
service/history/workflow/task_generator_mock.go
service/history/workflow/task_generator_test.go
service/history/workflow/task_refresher.go

Use GetCloseTime for generate close event task
**Why?**
As we store the closed time in mutable state, we can get the close time from mutable state instead of reading it from history event.

Use GetCloseTime for generate close event task

---

service/matching/matching_engine.go
service/matching/version_sets.go
service/matching/version_sets_test.go

- In PersistUnknownBuildId, if the build id is already present but the guessed set id is not a set id of that set, add it to the set (previously it would leave the data unchanged).
- Get rid of the first unknown operation check in UpdateWorkerBuildIdCompatibility (unknown operations will error out in the mutation function anyway).
**Why?**
- The goal of PersistUnknownBuildId is to record that we spooled a task using a guessed set id. In the propagation lag case, PersistUnknownBuildId would see that a build id is present and not modify the data. If the build id was not the first one in its set, then we'd lose that guessed set id.
- We only need to check for unknown operations once, instead of updating the options switch with each new operation, we can just update the main …

Always persist guessed set id on unknown build id

---

common/api/metadata.go
common/api/metadata_test.go
common/authorization/default_authorizer.go
common/authorization/default_authorizer_test.go
common/authorization/frontend_api.go
common/rpc/interceptor/telemetry.go
common/rpc/interceptor/telemetry_test.go

- Add method metadata and unit test to check consistency
- Use metadata to implement default authorizer
- All AdminService requires System Admin role (including GetSearchAttributes)
**Why?**
- More consistent treatment of methods in default authorizer (includes service name)
- Avoid changing semantics if namespace field is added
- Allows ListSearchAttributes in OperatorService to namespace reader (fixes #4654 and #4783)
unit tests

Add method metadata and use for default authorizer

---

common/api/metadata.go

QueryWorkflow was marked as needing write access but it should be read-only.
**Why?**
QueryWorkflow doesn't change any workflow state.

Mark QueryWorkflow as read-only in api metadata

---

service/frontend/workflow_handler.go

Log warn if task queue kind not set
**Why?**
make sure all clients specify this value. otherwise, sticky queues will be treated as normal queues.
No logic change
None
No

Log warn if task queue kind not set

---

common/persistence/client/health_request_rate_limiter.go
common/quotas/clocked_rate_limiter.go
common/quotas/clocked_rate_limiter_test.go
common/quotas/dynamic.go
common/quotas/rate_limiter_impl.go
common/quotas/rate_limiter_impl_test.go
service/matching/matcher.go
service/matching/matching_engine_test.go

Our RateLimiterImpl now uses a ClockedRateLimiter instead of a raw go rate limiter which does not accept a clock.
**Why?**
To make unit testing / time skipping easier in the future, and to add some test coverage.
I added a bunch of unit tests for the ClockedRateLimiter.
1. If I missed something, we could be using system time instead of the clock, and it would make downstream issues harder to debug
2. If there's a bug here, we could end up with a fauly rate limiter which prevents any requests from going through
3. The tests aren't exactly trivial, so it could introduce a maintenance burden
No

Add a clocked rate limiter

---

service/matching/config.go
service/matching/matching_engine.go

Dynamic config settings `limit.versionCompatibleSetLimitPerQueue`, `limit.versionBuildIdLimitPerQueue`, and `limit.taskQueuesPerBuildId` can be configured by namespace.
**Why?**
More configurability
existing tests

Make versioning data limits configurable by namespace

---

common/metrics/metric_defs.go
common/persistence/cassandra/factory.go
common/persistence/cassandra/test.go
common/persistence/cassandra/version_checker.go
common/persistence/client/store.go
common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go
common/persistence/nosql/nosqlplugin/cassandra/gocql/session_test.go
common/persistence/tests/cassandra_test_util.go
common/persistence/visibility/factory.go
common/persistence/visibility/store/standard/cassandra/visibility_store.go
service/frontend/workflow_handler.go
tools/cassandra/cqlclient.go

What changed?
passing metrics handler all the way down to gocql Session and emit metric when refresh fails
Why?
So we can put alert on this metric and catch downstream Cassandra issues
How did you test it?
unit-test
Potential risks
None
Is hotfix candidate?
No

Emit metrics when gocql session refresh fails

---

client/matching/client.go
client/matching/loadbalancer.go
service/matching/forwarder.go
tests/versioning_test.go

- Fix forwarding of query tasks with a version directive.
- Use PickWritePartition for load-balancing query tasks.
- Fix the logic to force specific partitions for testing with forcing forwarding, used by versioning tests.
**Why?**
- The version directive was being omitted when forwarding queries, we need it to match versioned tasks correctly.
- Query tasks are new tasks, not polls, so they're on the "write" side from matching's point of view, even though they read data.
- Make the test test what it's supposed to.
integration tests

Fix QueryWorkflow forwarding on versioned queue

---

service/worker/scanner/build_ids/scavenger.go

In the build id scavenger, if `rateLimiter.Wait` returns an error (it would have to wait longer than the context deadline), then exit the activity.
**Why?**
The loop in the calling function only exits if the context deadline is actually exceeded, not if it would be exceeded shortly. So it would try the next task queue, which would hit the same error, etc. It should just exit early instead.
looked at code

Exit build id scavenger on rate limiter error

---

service/history/queues/executable.go
service/history/queues/executable_test.go

- Fix race condition in task in memory nouser latency calculation
- Once task is resubmitted or rescheduled, its internal state should not be accessed or updated. `common/tasks.Task` part of the Executable implementation is not designed to be thread safe.
**Why?**
- Bug fix
- Updated unit test to catch the case
- N/A
- no. the bug only impact latency metric calculation in error case.

Fix race condition for task latency calculation

---

common/dynamicconfig/constants.go
service/frontend/fx.go
service/frontend/service.go
service/fx.go
service/history/configs/config.go
service/history/fx.go
service/matching/config.go
service/matching/fx.go
service/worker/fx.go
service/worker/service.go

- Make persistence global rate limit config (including per namespace persistence limit) work. Break the fx cycle dependency between persistence factory and membership service resolver. 
- The global config won't take effect immediately after service start as when the rate limiter is first created, service resolver is not available. Per pod limit will be used instead. After 1m (dynamic rate limiter refresh interval), when dynamic rate limiter refreshes the its rate, it will found the service resolver is there and calculate the quota based on global limit and member count.
**Why?**
- Persistence global rate limit
- https://github.com/temporalio/temporal/issues/4806
- Manually started service and see `Initialized service resolver for persistence …

Persistence global rate limit

---

common/persistence/sql/sqlplugin/postgresql/admin.go

Added double quotes around database name in the create database query for PostgreSQL. 
**Why?**
The issue has been created on temporal-operator project (see: https://github.com/alexandrevilain/temporal-operator/issues/402). 
When we try to use the `temporal-sql-tool` `create` command with a database name containing hyphen(s), even if escaped in command, it throws the following error:  `pq: syntax error at or near \"-\"`. 
Before the fix:
```bash
$ go run ./cmd/tools/sql --endpoint="localhost" --port="5432" --user="temporal-aws-dev" --password="$TEMPORAL_DEFAULT_DATASTORE_PASSWORD" --database="temporal-aws-dev" --plugin="postgres" create
2023-08-05T20:44:58.957+0200    ERROR   Unable to create SQL database.  {"error": "pq: syntax error at or near …
```

Fix temporal-sql-tool database creation on postgresql when database name contains hyphen

---

service/history/archival_queue_task_executor.go
service/history/queues/active_standby_executor.go
service/history/queues/active_standby_executor_test.go
service/history/queues/executable.go
service/history/queues/executable_mock.go
service/history/queues/executable_test.go
service/history/timer_queue_active_task_executor.go
service/history/timer_queue_active_task_executor_test.go
service/history/timer_queue_standby_task_executor.go
service/history/timer_queue_standby_task_executor_test.go
service/history/transfer_queue_active_task_executor.go
service/history/transfer_queue_active_task_executor_test.go
service/history/transfer_queue_standby_task_executor.go
service/history/transfer_queue_standby_task_executor_test.go
service/history/visibility_queue_task_executor.go
service/history/visibility_queue_task_executor_test.go

- Make task executor return values a struct to comply with golang convention
**Why?**
- The metrics tags and the isActive flag are task execution metadata and needs to be populated even when the processing fails. Current definition make people think they are only valid when error is nil though. 

Improve task executor interface

---

tests/activity_test.go
tests/advanced_visibility_test.go
tests/archival_test.go
tests/cancel_workflow_test.go
tests/child_workflow_test.go
tests/continue_as_new_test.go
tests/cron_test.go
tests/describe_test.go
tests/gethistory_test.go
tests/relay_task_test.go
tests/reset_workflow_test.go
tests/signal_workflow_test.go
tests/sizelimit_test.go
tests/stickytq_test.go
tests/taskpoller.go
tests/transient_task_test.go
tests/update_workflow_test.go
tests/user_timers_test.go
tests/workflow_buffered_events_test.go
tests/workflow_delete_execution_test.go
tests/workflow_failures_test.go
tests/workflow_memo_test.go
tests/workflow_test.go
tests/workflow_timer_test.go
tests/workflow_visibility_test.go
tests/xdc/advanced_visibility_test.go
tests/xdc/integration_failover_test.go

- Refactored PollAndProcessWorkflowTask and all variations to use an options pattern.
- Added WithNoDumpCommands to disable printing commands.
**Why?**
- The stack of variations was getting annoying.
- And I wanted to add WithNoDumpCommands to make TestTransientWorkflowTaskHistorySize less flaky.
is tests

Refactor TaskPoller.PollAndProcessWorkflowTask

---

common/telemetry/config.go
common/util/util.go
service/worker/pernamespaceworker.go
service/worker/pernamespaceworker_test.go

Multiply these fields of SDK worker options by per-namespace worker multiplicity also:
- `MaxConcurrentLocalActivityExecutionSize`
- `MaxConcurrentWorkflowTaskExecutionSize`
- `MaxConcurrentActivityExecutionSize`
(Poller counts were already multiplied)
**Why?**
For bursty schedule workloads that get rate limited, LA or WFT task slots may fill up and slow down processing. These fields can already be adjusted independently, but using multiplicity as a single knob makes tuning easier and more intuitive.
unit test

Multiply per-ns worker task slots by multiplicity

---

service/history/replication/executable_history_task.go
service/history/replication/executable_history_task_test.go
service/history/replication/executable_task_converter.go
service/history/replication/executable_task_tool_box.go

Add lazy deserialization on history replication task
**Why?**
Batching functionality requires inspecting events details. So advancing the deserialization to task creation time to reduce back and force in des/ser
unit test
replication stack will not work
no

Add lazy deserialization on history replication task

---

service/frontend/workflow_handler.go
tests/schedule_test.go

DescribeSchedule now does just one workflow query. It still sends a refresh signal if it filters out closed workflows, but it doesn't wait to observe a state change after the signal.
**Why?**
This extra work (repeated query to observe state change after signal) was not really useful since we can just filter out the closed workflows directly, and it made the call more expensive than it needs to be.
existing integration tests

Simplify DescribeSchedule

---

common/clock/context.go
common/clock/context_test.go
common/persistence/tests/cassandra_test.go
common/persistence/tests/history_task_queue_manager_test_suite.go
service/history/queues/executable_dlq.go
service/history/queues/executable_dlq_test.go
service/history/queues/queuestest/executable_dlq_test_suite.go
service/history/queues/queuestest/fake_executable.go

I added an ExecutableDLQ struct which wraps Executables in such a way that terminal errors result in the task eventually being written to the database. It works by modifying the behavior of the executable after the first terminal error is encountered. When this happens, the Execute method is modified to instead attempt to write the task to the DLQ. We do this instead of writing to the DLQ inline so that we can reuse the upstream retry logic.
A follow-up PR will actually wrap our executables with this class; for now, the behavior in production isn't changed at all.
**Why?**
This is part of the write-path for the DLQ project. I made this a wrapper instead of putting it inline in the ExecutableImpl to keep things modular and reduce bloat.
There's …

Add an ExecutableDLQ to write history tasks to the DLQ

---

service/history/archival_queue_factory.go
service/history/queue_factory_base.go
service/history/queues/executable_factory.go
service/history/queues/executable_factory_test.go
service/history/queues/queue_base.go
service/history/queues/queue_base_test.go
service/history/queues/queue_immediate.go
service/history/queues/queue_scheduled.go
service/history/queues/queue_scheduled_test.go
service/history/queues/reader_test.go
service/history/queues/slice.go
service/history/queues/slice_test.go
service/history/timer_queue_factory.go
service/history/transfer_queue_factory.go
service/history/visibility_queue_factory.go
temporal/server_test.go

I added an `ExecutableWrapper` parameter to our queue factory fx graph.
**Why?**
This should make it possible to extend the behavior of history task processing. Specifically, I need this to add DLQ functionality to history tasks.
This is mostly dependency plumbing, but there is a unit test for the executable factory wrapper.

Add a pluggable ExecutableWrapper to our queue factories

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/dlq.go
service/history/dlq_test.go
service/history/queue_factory_base.go
service/history/queues/executable_factory.go

This is the final PR to actually wire up the history task DLQ. 
_Note about the PR structure: The merge base is dlq-5-base, but it will be changed to dlq-feature after https://github.com/temporalio/temporal/pull/4875 is merged. I did it this way because 4875 is a PR against main (because it's independent of the DLQ project), but this PR depends on both that and another PR in the dlq-feature branch._
**Why?**
I made this so that we can actually use the DLQ. All previous PRs were basically library code--this hooks it up to our main entry point.
There's an fx test which verifies that any executable we create will use the DLQ iff the dynamic config flag is on.
The dynamic config defaults to false, and I added a comment to not turn …

Wire up dynamic config-backed history DLQ

---

common/config/config.go
common/persistence/client/fault_injection.go
common/persistence/client/fault_injection_test.go

I implemented `FaultInjectionDataStoreFactory.NewQueueV2`.
**Why?**
We implement this for all data stores. We don't have an actual use-case yet, but it may be helpful later if we want integration tests that test that our system can work even if the new queue experiences some errors.
I added 100% test coverage.

Add FaultInjectionDataStoreFactory.NewQueueV2 implementation

---

common/persistence/client/bean_fx.go
common/persistence/client/factory.go
common/persistence/client/factory_test.go
common/persistence/data_interfaces.go
service/history/fx.go

I moved our `TaskQueueManagerProvider` to the persistence client module, where all the other "managers" are provided.
**Why?**
To keep things consistent.
I added a small unit test, but there isn't really much behavior here. There's also the existing test in `server_test.go` which will verify that the whole graph can still be built.

Provide HistoryTaskQueueManager from persistence module

---

common/metrics/metric_defs.go
service/history/dlq.go
service/history/dlq_test.go
service/history/queues/executable_dlq_observer.go
service/history/queues/executable_dlq_observer_test.go
service/history/queues/executable_dlq_test.go
service/history/queues/queuestest/fake_dlq.go

I added `queues.ExecutableDLQObserver` which adds logging and metrics to the history task DLQ.
**Why?**
In order for us to alert on things like high DLQ latency, high DLQ rate, or high DLQ failure rate.
There's 100% test coverage for the new code. 

Add ExecutableDLQObserver

---

common/metrics/metric_defs.go
common/metrics/tags.go
common/persistence/visibility/factory.go
common/persistence/visibility/visibility_manager_test.go
common/persistence/visibility/visiblity_manager_metrics.go

Change `visibilityTypeTag` to `visibilityPluginNameTag` as it provides more useful information.
`visibilityTypeTag` only tells if it's standard or advanced, and it's broken at this moment.
`visibilityPluginNameTag` will tell what's the visibility store it's using.
**Why?**
Provide more useful information about the visibility store.
Unit test.
No.
No.

Refactor visibility metrics tag

---

common/dynamicconfig/shared_constants.go
common/persistence/client/health_request_rate_limiter.go

Made dynamic rate limiting options for minimum and maximum rate multipliers into dynamic config options
Increased default minimum rate multiplier from 0.1 to 0.5
**Why?**
For easier control over dynamic rate limiting behavior
If reducing the rate limit below 50% does not improve system health, reducing it further is unlikely to help either
Existing tests
None
No

Make rate multi min and max dynamic

---

service/history/replication/executable_activity_state_task.go
service/history/replication/executable_activity_state_task_test.go
service/history/replication/executable_history_task.go
service/history/replication/executable_history_task_test.go
service/history/replication/executable_task.go
service/history/replication/executable_task_mock.go
service/history/replication/executable_task_test.go
service/history/replication/executable_workflow_state_task.go
service/history/replication/executable_workflow_state_task_test.go

* Handle XDC replication task retry error / not found error correctly
* When encountered not found, delete workflow abort replication task
* When encountered another retry error, retry one more time
**Why?**
Properly handle reset workflow & deleted workflow case
UT
N/A
N/A

Handle XDC replication task retry error / not found error correctly

---

service/history/workflow/task_refresher.go

Only refresh upsert visibility task for running workflows.
**Why?**
This can cause out of order visibility tasks to be refreshed (CLOSE task followed by UPSERT task).

Refresh upsert visibility task only for running workflows

---

service/frontend/fx.go

This PR changes the behavior of `RateLimitInterceptorProvider`. Instead of providing rate limiters to `NewRequestToRateLimiter`, we provide `RateBurst` functions. 
**Why?**
Because this was causing a bug:
_Impact:_
These dynamic configs are never updated after the server starts:
- `frontend.rps`
- `frontend.globalRPS`
- `frontend.rps.namespaceReplicationInducingAPIs`
Additionally, frontend.globalRPS is rendered completely unusable because it calculates the number of members to be 0 on startup, so it defaults to frontend.rps to avoid a division-by-zero when calculating the effective per-isntance limit: 
_Root cause:_
We construct a quota calculator [here](https://github.com/temporalio/temporal/blob/c7847968b309eb71edbe1da6f6cfa4d1c0b21341/service/frontend/fx.go#L305) . …

Use RateBurst in RateLimitInterceptorProvider

---

service/frontend/workflow_handler.go
service/frontend/workflow_handler_test.go

- Handle batch reset operation type so DescribeBatchOperation doesn't fail on reset
- Made DescribeBatchOperation not fail on future unknown types, just log a warning.
**Why?**
Fixes #4939.
There's no need to fail DescribeBatchOperation just because it can't map the string back into an enum.
Modified one of the unit tests to use that batch type (also tested with an unknown string and saw the log message)

Handle batch reset in DescribeBatchOperation

---

common/authorization/interceptor.go
common/authorization/interceptor_test.go
common/config/config.go
service/frontend/fx.go

Add static config options for changing the header names passed to the ClaimMapper. The ClaimMapper interface does not change.
(Note that as before, if the main header is not present, the ClaimMapper will not be called, even if the extra header is present. This can be overridden by implementing `AuthInfoRequired` on the ClaimMapper.)
**Why?**
Fixes #3362
New unit test

Allow customizing authorization header names

---

common/persistence/visibility/store/elasticsearch/client/client_v7.go
common/persistence/visibility/store/elasticsearch/client/config.go

New field `hosts` has been added to the Elasticsearch config. Now, it is possible to connect to a multi-node cluster. Possible fix for https://github.com/temporalio/temporal/issues/4890
**Why?**
To support Elasticsearch clusters with no load balancer.
Checked in staging env. I'd be happy to add a test, but I did not find where the connection configs are tested
No, since this is a new field, which will not affect existing Temporal installations.
No

Allow multiple hosts for elasticsearch

---

service/history/archival/archiver.go
service/history/archival/archiver_test.go

Handle cases of `nil` `HistoryArchivalURI` when performing visibility archival
See https://github.com/temporalio/temporal/issues/4879 for details
This PR is a suggested fix for https://github.com/temporalio/temporal/issues/4879
We are not fully familiar with the codebase so it's ok to close and make a better fix (or point us in the right direction; we are happy to make the patch)
Added a test that sets the URI to nil during visibility archival. It panics before the change and passes after
The risk is lower than before this fix. This is not, however, a comprehensive check on when similar panics can occur
This error has resulted in a P0 incident for us but it is also somewhat unlikely given it has not happened in such a long time. This _may_ bring down cloud clusters as well in theory.

Handle nil HistoryURI during visibility archival

---

common/rpc/interceptor/telemetry.go

Add action metric for batch of markers
**Why?**
Markers in one workflow task maybe counted as one action.

Emit action metrics for batch of markers

---

tests/functional_test_base.go
tests/functional_test_base_test.go
tests/onebox.go
tests/test_cluster.go

I added an option that allows user to add fx graph modification to individual services when starting them in the SetupSuite lifecycle stage of their integration tests.
**Why?**
This provides a super simple way to change test set ups or extract dependencies from the graph. It should make it a lot easier to write integration tests with more complex setups or assertions. I also need it for a subsequent PR that adds integration tests to the new DLQ. Specifically, I need a way to override the `ExecutableWrapper`, and I think this is simpler than adding it to the long and growing list of dependencies in the `TestClusterConfig`.
I added an integration test which sets this up and provides an `fx.Populate` option for the `primitives.ServiceName` variable …

Add a WithFxOptionsForService option for our integration tests

---

service/history/fx.go
service/history/queue_factory_base.go
service/history/queue_factory_base_test.go
service/history/shard/fx.go
service/history/shard/ownership_based_quota_calculator.go
service/history/shard/ownership_based_quota_scaler.go
service/history/shard/ownership_based_quota_scaler_test.go

- Make history persistence and task scheduler rate limiter become shard count aware
- Refactor OwnershipBasedQuotaScaler: deprecated OwnershipScaledRateBurst so that we won't have one background goroutine for each ownership scaled rate burst created.
**Why?**
- Handle the case where shard count is not balanced across hosts.
- Tested in test cell.

Shard count based rate limiting

---

cmd/tools/tdbg/main.go
tools/tdbg/app.go
tools/tdbg/app_test.go
tools/tdbg/commands.go
tools/tdbg/defs.go
tools/tdbg/dlq_commands.go
tools/tdbg/task_queue_commands.go
tools/tdbg/tdbg_commands.go
tools/tdbg/util.go
tools/tdbg/util_test.go

I got rid of the `cFactory` global variable in the `tdbg` package in favor of a parameter to the `NewCliApp` method. I also refactored the DLQ client to re-use some of its flag variables to keep the code a bit more DRY.
**Why?**
I need to override this variable in a unit test, and I don't want to do it globally because that would mean that the tests can't run in parallel.

Get rid of tdbg.cFactory global variable

---

client/history/metadata_test.go
common/locks/condition_variable_test.go
common/persistence/persistence-tests/persistence_test_base.go
common/persistence/tests/execution_mutable_state.go
common/persistence/tests/shard.go
common/persistence/tests/task_queue.go
common/persistence/tests/task_queue_task.go
common/shuffle/shuffle.go
common/util.go
service/frontend/service.go
service/history/api/consistency_checker_test.go
service/history/api/signalwithstartworkflow/signal_with_start_workflow_test.go
service/history/api/signalworkflow/api_test.go
service/history/queues/iterator_test.go
service/history/replication/stream_sender_test.go
service/history/replication/task_processor_manager_test.go
service/history/replication/task_processor_test.go
service/history/service.go
service/history/tasks/key_test.go
service/history/workflow/history_builder_test.go
service/history/workflow/mutable_state_rebuilder_test.go
service/matching/service.go
service/worker/service.go

Removed all calls to `rand.Seed` with a _random_ initialization value.
**Why?**
Less code is better.
[From the docs](https://pkg.go.dev/math/rand#Seed):
> If Seed is not called, the generator is seeded randomly at program startup.
> Prior to Go 1.20, the generator was seeded like Seed(1) at program startup. [...]
> Deprecated: **As of Go 1.20 there is no reason to call Seed with a random value**. [...]
According to the docs, this is a no-op change in terms of behaviour.
No.

🧹 remove calls to `rand.Seed`

---

.golangci.yml
common/persistence/visibility/store/sql/query_converter_sqlite.go
temporal/fx.go

1. There's a lot of duplicated code in `temporal/fx.go` where we convert the dependencies in `ServiceProviderParamsCommon` into `fx.Option`s. I simply extracted a method for this so that the duplication is avoided. 
2. I also increased the cyclomatic complexity threshold in our linter because it was complaining about the `ServerOptionsProvider` function, which is not complex in my opinion, just a little long.
**Why?**
We probably had the duplication originally because `fx.Decorate` didn't exist, so the customization that the frontend service does would've been impossible.
There's the existing `server_test.go`, which verifies that the `fx` graph builds and runs. 

Extract ServiceProviderParamsCommon.GetCommonServiceOptions

---

common/cluster/metadata.go
common/metrics/metric_defs.go
common/namespace/registry.go
service/history/shard/context_impl.go
service/history/shard/controller_impl.go

Rename go constants and metric names for latency metrics collected by deadlock detector.
**Why?**
There was some confusion between the two "shard lock latency" metrics. The other one is more useful since it's collected on every usage instead of once in a while, and both read and write locks. Renaming the deadlock detector ones makes it more clear where they're coming from.
Just renames.
The exported metric names are changing, so anyone using them will have to change. But it's unlikely anyone is using them since they were never documented. We can make a note in release notes.

Rename deadlock detector latency metrics

---

service/worker/scheduler/workflow.go
service/worker/scheduler/workflow_test.go

The end of each test is signaled by time instead of iteration count, which was really confusing.
**Why?**
Easier to write and maintain tests.
They now stop at exactly the right time and avoid spurious calls that would trigger panics.
is tests

Improve scheduler workflow unit test

---

service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_test.go

Collapse visibility tasks to minimize updates to visibility store.
The list of tasks is collapsed into a single one: START < UPSERT < CLOSE < DELETE.
**Why?**
Minimize updates to visibility store.
Probably not, each visibility task writes the entire record into the store, so the latest task should contain all the info to keep visibility up to date.
No.

Collapse visibility tasks

---

service/history/shard/task_key_generator.go
service/history/shard/task_key_generator_test.go
service/history/tests/vars.go

- Add task key generator for shard context
**Why?**
- Pull out logic related to task key generation/allocation to a component. Needed for later work for releasing shard lock on shard I/O. For the full change check: https://github.com/temporalio/temporal/tree/remove-shard-lock-v2/service/history/shard
- Unit test & tested in test cluster
- N/A, not wired up yet

No shard lock on I/O: task key generator

---

service/history/shard/task_request_tracker.go
service/history/shard/task_request_tracker_test.go
service/history/tests/vars.go

- Add task request tracker for shard context
**Why?**
- Pull out logic related to tracking pending task keys and inflight persistence requests. Needed for later work for releasing shard lock on shard I/O. For the full change check: https://github.com/temporalio/temporal/tree/remove-shard-lock-v2/service/history/shard
- Unit test & tested in test cluster
- N/A, not wired up yet

No shard lock on I/O: task request tracker

---

service/history/api/replication/generate_task.go
service/history/workflow/mutable_state.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_mock.go
service/history/workflow/task_generator.go
service/history/workflow/task_generator_mock.go

* GenerateMigrationTasks API should also propagate pending activity info
**Why?**
For namespace migration, history events as well as (updated) activity info both should be replicated
N/A
N/A
N/A

Fix GenerateMigrationTasks behavior

---

service/history/replication/batchable_task.go

Move unlock prior to the execute() finishing.
**Why?**
The underlying Execute() func usually involves I/O with DB and take longer time to execute. 
The Lock in the batchedTask is to prevent the batchTask accepting new Task when executing. We have `state` to prevent this happening, so we can unlock() before underlying Execute() and let the AddTask() fail faster.
N/a
N/a
No

Improve batchedTask enqueue efficiency

---

Makefile

The make target `proto` is quieter now when it succeeds (like most of our other Makefile targets).
```
$ make proto
Run buf linter...
Run api-linter...
Build proto files...
Run goimports for proto files...
Generate proto mocks...
Update license headers for proto files...
```
```
$ make proto
Install proto submodule...
git submodule update --init proto/api
Run buf linter...
Run api-linter...
- file_path: temporal/server/api/token/v1/message.proto
problems: []
- file_path: temporal/server/api/metrics/v1/message.proto
problems: []
- file_path: temporal/server/api/taskqueue/v1/message.proto
problems: []
- file_path: temporal/server/api/cluster/v1/message.proto
problems: []
- file_path: temporal/server/api/schedule/v1/message.proto
problems: []
- file_path: …
```

silence verbose `proto` target

---

common/dynamicconfig/constants.go
service/history/api/activity_util.go
service/history/api/consistency_checker.go
service/history/api/consistency_checker_test.go
service/history/api/get_workflow_util.go
service/history/api/queryworkflow/api.go
service/history/api/resetworkflow/api.go
service/history/api/startworkflow/api.go
service/history/configs/config.go
service/history/tests/vars.go
tests/onebox.go

- Grab current execution lock when consistency checker (used for serving api requests) need to get current runID.
**Why?**
- Prevent the case where large # of requests for the same workflowID try to get runID from db at the same time and cause hot shard problem.
- Ideally for requests with no runID, the current workflow lock should be hold for the entire lifetime of the request (or until the concrete record is locked), to prevent the race where current runID get changed after it's retrieved from DB. But that requires much larger change. This PR is just a short term hotfix for the issue.
- Updated existing tests.
- Reduced concurrency for requests targeting the same workflowID
- Yes.

Lock get current execution for API requests

---

service/worker/migration/activities.go
service/worker/migration/activities_test.go
service/worker/migration/force_replication_workflow.go
service/worker/migration/fx.go

Current code create a new AdminClient for every VerifyReplicationTasks activity invocation. Since there is no way to close a connection, it caused a leak. This change uses cached version for creating AdminClient.
**Why?**
unit tests + local cluster tests

Reuse cached RemoteAdminClient in VerifyReplicationTasks

---

common/metrics/metric_defs.go
service/history/workflow_task_handler.go
service/history/workflow_task_handler_test.go

(1) Added new single metric to track _all_ commands coming into the History Service.
(2) Marked previous per-command-metrics as deprecated (will be removed in future release).
(3) Added namespace tag to metric.  
**Why?**
Fixes https://github.com/temporalio/temporal/issues/4628
Used the debugger to inspect during a test:
Is there a better way?
No

Single metric for commands in History Service

---

service/history/dlq.go
service/history/dlq_test.go
service/history/queue_factory_base.go
service/history/queues/dlq_writer.go
service/history/queues/executable_dlq.go
service/history/queues/executable_dlq_observer_test.go
service/history/queues/executable_dlq_test.go
service/history/queues/queuestest/executable_dlq_test_suite.go
service/history/queues/queuestest/fake_queue_writer.go

I extracted a `DLQWriter` from our `ExecutableDLQ` type in the `queues` package.
**Why?**
For the replication DLQ, we don't want `ExecutableDLQ` because replication tasks track their state in a different way, and so they have an explicit `MarkPoisonPill` method. The `ExecutableDLQ` currently does 2 things:
1. Track whether this executable failed with a terminal error
2. If it did, try sending the task to the DLQ whenever we execute again
So, for replication tasks, I only need the second part. I went ahead and extracted that to its own type as some preparatory refactoring for the replication DLQ change.
This is already fully tested by `executable_dlq_test.go`.

Extract new queues.DLQWriter type

---

service/worker/fx.go
service/worker/service.go
tests/dlq_test.go
tests/functional_test_base.go
tests/xdc/base.go
tests/xdc/history_replication_dlq_test.go
tools/tdbg/dlq_service.go
tools/tdbg/dlq_v1_service.go

This change adds an integration test for the history replication DLQ. I also improved some error messages in replication that I found while writing this test.
**Why?**
It's mainly to help rolling out the new DLQ backend implemented using QueueV2
1. I'll need a similar test, so I can reuse a lot of this
2. I'll be refactoring some code in the replication stack, so this test verifies that I don't cause any regressions.
This test runs with streaming both enabled and disabled for replication, so it should work just fine once that's turned on by default.
This test is pretty invasive, relying on several assumptions about what types are used by the replication stack. However, this means we don't have any sleeps or retries in the …

Add a history replication DLQ test

---

common/persistence/persistence_interface.go
service/history/history_engine.go
service/history/history_engine_factory.go
service/history/replication/dlq_writer.go
service/history/replication/dlq_writer_test.go
service/history/replication/executable_activity_state_task.go
service/history/replication/executable_activity_state_task_test.go
service/history/replication/executable_history_task.go
service/history/replication/executable_history_task_test.go
service/history/replication/executable_noop_task_test.go
service/history/replication/executable_task_test.go
service/history/replication/executable_task_tool_box.go
service/history/replication/executable_unknown_task_test.go
service/history/replication/executable_workflow_state_task.go
service/history/replication/executable_workflow_state_task_test.go
service/history/replication/fx.go
service/history/replication/stream_receiver_monitor_test.go
service/history/replication/stream_receiver_test.go
service/history/replication/task_processor.go
service/history/replication/task_processor_manager.go
service/history/replication/task_processor_manager_test.go
service/history/replication/task_processor_test.go

I added a `DLQWriter` interface to the `replication` package, which takes a `WriteRequest` containing a `shard.Context`, a source cluster name, and replication task info, and writes a task to the DLQ. I also added a default implementation which uses our v1 queue supplied by the shard.
I also refactored `replication/fx.go` in two ways:
1. **Don't use `fx.Options`**: Its usage is discouraged in its documentation, and we can replace it by simply having a variadic call to `fx.Provide`, and adding lifecycle hooks for the scheduler in the provider instead of an `fx.Invoke` call.
2. **Keep providers un-exported**: I didn't see a reason for having these exported, and I think it just bloats the footprint of this package. It's clearer when you see that it just provides a few …

Add a replication.DLQWriter interface

---

common/dynamicconfig/constants.go
common/persistence/persistence-tests/persistence_test_base.go
common/persistence/serialization/serializer.go
common/persistence/serialization/task_serializer.go
service/history/configs/config.go
service/history/replication/dlq_writer.go
service/history/replication/dlq_writer_test.go
service/history/replication/executable_activity_state_task.go
service/history/replication/executable_history_task.go
service/history/replication/executable_workflow_state_task.go
service/history/replication/fx.go
service/history/replication/task_processor.go
tests/test_cluster.go
tests/xdc/base.go
tests/xdc/history_replication_dlq_test.go
tools/tdbg/tdbg_commands.go

This PR adds a dynamic config flag which controls the rollout of the persistence queue V2 backend for writing history replication tasks to the DLQ.
**Why?**
Our first priority of the queue v2 migration is to make it work for history replication tasks, so this PR adds the ability for us to roll that out.
I added branches to our history replciation DLQ integration test that turn on this dynamic config flag.

Add EnableHistoryReplicationDLQV2 dc

---

service/history/shard/task_key_manager.go
service/history/shard/task_key_manager_test.go

- Add task key manager for shard context
- This is a thin wrapper around task request tracker and task key generator. Shard context will use this component instead of talking to request tracker or key generator directly for allocating task key or getting the max read watermark for history task queues.
**Why?**
- Needed for later work for releasing shard lock on shard I/O. For the full change check: https://github.com/temporalio/temporal/tree/remove-shard-lock-v2/service/history/shard
- Unit test & tested in test cluster
- N/A, not wired up yet

No shard lock on I/O: task key manager

---

service/frontend/namespace_handler.go
service/frontend/namespace_handler_test.go

Fix create namespace replication task with one cluster
**Why?**
When creating namespace with one cluster, we don't need to create replication task.
New unit test
No

Fix create namespace replication task with one cluster

---

common/dynamicconfig/constants.go
service/worker/common/interface.go
service/worker/common/util.go
service/worker/deletenamespace/fx.go

Added new dynamic config map of options to set concurrency limits for the delete namespace activity worker: `worker.deleteNamespaceActivityLimitsConfig`
**Why?**
For finer-grained control over worker service resource usage
Existing tests
None
No

Set delete namespace activity concurrency limits

---

service/history/workflow_task_handler.go
tests/versioning_test.go

Only enable eager activity start if dynamic config enables it and workflow doesn't use versioning.
If a workflow _uses_ versioning, only allow eager activities which intend to use a compatible version since a
worker is obviously compatible with itself and we are okay dispatching an eager task knowning that there may be a
newer "default" compatible version.
Note that if `UseCompatibleVersion` is false, it implies that the activity should run on the "default" version
for the task queue.

Disable eager activities for incompatible versioned activities

---

common/metrics/metric_defs.go
service/history/replication/batchable_task.go

Change replication batch task metrics from counter to gauge
**Why?**
Counter is not what we need. From this metrics, we want to know in avg, how many tasks are batched together
n/a
n/a
no

Change replication batch task metrics from counter to gauge

---

service/worker/scheduler/workflow.go
service/worker/scheduler/workflow_test.go

Scheduler workflow uses server-sent suggestion for when to continue-as-new instead of fixed iteration count.
Note this is not enabled in this PR yet.
**Why?**
Automatically handle history size/event count too large conditions (or any future conditions added by the server), which we might get if we do more work than expected per iteration.
new unit tests, also replaced for loop with previous version to verify actual iteration count didn't change
The default history size suggestion is at 4MB, which we could hit after just a few large payload responses, and then we'd do continue-as-new more often than we might like.

Use ContinueAsNewSuggested in scheduler workflow

---

common/persistence/visibility/store/elasticsearch/query_interceptors.go
common/persistence/visibility/store/elasticsearch/query_interceptors_test.go
common/persistence/visibility/store/sql/query_converter.go
common/primitives/timestamp/parse_duration.go
common/primitives/timestamp/parse_duration_test.go

Support duration expression (eg: "1m", "20h") in SQL queries involving `ExecutionDuration`.
**Why?**
Better UX in advanced visibility with SQL (already supported with ES).
Raw field is in nanoseconds.
Created some workflows, and send some queries using those expression.
No.
No.

Parse ExecutionDuration for SQL queries

---

common/persistence/visibility/factory.go
common/persistence/visibility/store/elasticsearch/query_interceptors.go
common/persistence/visibility/store/elasticsearch/query_interceptors_test.go
common/persistence/visibility/store/elasticsearch/visibility_store.go
common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
common/persistence/visibility/store/query/converter.go
common/persistence/visibility/store/standard/converter.go
common/persistence/visibility/store/standard/converter_test.go
common/persistence/visibility/store/standard/query_interceptors.go
common/persistence/visibility/store/standard/visibility_store.go

Validate search attribute values in the SQL query to ES visibility store
**Why?**
Better error handling for UX
No.
No.

Validate search attributes values in queries to ES

---

tests/versioning_test.go

We now clear dynamicconfig overrides after each subtest rather than after all subtests have run.
**Why?**
Not doing so caused us to panic in certian conditions. I hit a specific ordering where:
- we force forwarding, setting the forced read partition to 5
- we run without forwarding, setting the number of partitions to 1
- our load balancer code ensured we had one partition then promptly tried to access the fifth partition
These tests look like they run in a deterministic order so I'm not entirely sure how we hit this, but it definitely happend.
This is hard to reproduce and only occurred once in buildkite; see [functional test with cassandra](https://buildkite.com/temporal/temporal-public/builds/13072#018b71a7-2fea-451e-86a2-ef0bcff602f2). …

Fix an ordering bug in matching behavior tests

---

tests/dlq_test.go
tests/xdc/history_replication_dlq_test.go
tools/tdbg/app.go
tools/tdbg/dlq_service.go
tools/tdbg/dlq_service_test.go
tools/tdbg/dlq_v1_service.go
tools/tdbg/dlq_v2_service.go
tools/tdbg/flags.go
tools/tdbg/task_encoder.go
tools/tdbg/task_encoder_test.go
tools/tdbg/tdbg_commands.go
tools/tdbg/tdbgtest/app.go
tools/tdbg/tdbgtest/output_parsing.go
tools/tdbg/tdbgtest/output_parsing_test.go

I added pluggable logic to decode DLQ tasks in tdbg. The default behavior uses the predefined set of categories in the server, deserializes them into protos, and then uses jsonpb to marshal them. However, for deployments with custom task categories, there is an option of extending this behavior.
Registering a custom task category will look something like this:
```go
package main
import (
"os"
"github.com/gogo/protobuf/proto"
commonpb "go.temporal.io/api/common/v1"
"go.temporal.io/server/service/history/tasks"
"go.temporal.io/server/tools/tdbg"
)
type (
myTaskDeserializer struct {
baseDeserializer tdbg.PredefinedTaskBlobDeserializer // the zero value is valid
}
myTaskCategoryRegistry struct {
baseRegistry tasks.TaskCategoryRegistry
}
)
var (
myTaskCategory = …
```

Decode DLQ tasks in tdbg

---

service/worker/scheduler/workflow.go
service/worker/scheduler/workflow_test.go

Add `force-continue-as-new` signal to schedule workflow, to force it to continue-as-new immediately.
**Why?**
This could be used to force all running schedules onto the newest version of the workflow code, to allow retiring older code paths.
unit test

Add force-continue-as-new signal to schedule workflow

---

Makefile

Pinning the `GOOS` and `GOARCH` for the `update-third-party-deps` Makefile target.
**Why?**
Without this, the user's local `GOOS` and `GOARCH` change the list - but it should align with the CI's system.
CI
Mismatch of `GOOS` / `GOARCH` in future CI agents?
No

Pin GOOS and GOARCH for `update-third-party-deps`

---

service/worker/migration/activities.go
service/worker/migration/activities_test.go
service/worker/migration/force_replication_workflow.go
service/worker/migration/force_replication_workflow_test.go
service/worker/migration/fx.go
service/worker/migration/handover_workflow.go

Reuse cached RemoteAdminClient in VerifyReplicationTasks (#4997)

---

service/worker/scheduler/workflow_test.go

Fix unit tests on release branch
**Why?**
The tests assumed that the change to not track ALLOW_ALL workflows was already active, but it's not on the release branch. So we just need mocks for WatchWorkflow.
is tests

Fix schedule workflow unit test

---

service/history/api/describeworkflow/api.go

Clone suspected mutating fields after a returning from DescribeWorkflowExecution.
**Why?**
Noticed panics in serialization of the `DescribeWorkflowExecutionResponse` object.
No tests added, assuming that normal test coverage is enough.
Haven't reproduced the issue, this is based on a hunch.
None that I can foresee.
Yes.

Hopefully avoid panic in DescribeWorkflowExecution

---

service/history/api/get_workflow_util.go

Add more logging message to monitor branch token update
**Why?**
better debugging.
only logging.

Add more logging message to monitor branch token update

---

tests/advanced_visibility_test.go
tests/dynamicconfig.go
tests/functional_test_base.go
tests/namespace_delete_test.go
tests/ndc/ndc_test.go
tests/onebox.go
tests/schedule_test.go
tests/test_cluster.go
tests/transient_task_test.go
tests/versioning_test.go
tests/xdc/advanced_visibility_test.go
tests/xdc/base.go

I cleaned up how we manage dynamicconfig overrides in our functional tests.
**Why?**
Forgetting to clean up after ourselves causes bugs (see #5046). By taking a `testing.T` as a parameter when overriding a value we can automatically clean up after ourselves when a test ends.
I added a separate path here for suite-wide config as there's currently an issue where a test can override a suite's value for a config then clear it, leaving us with _no_ value for the config rather than the value the suite specifies.
Functional tests
No

Automatically clear dc overrides after tests

---

common/persistence/visibility/defs.go

Allow list of keywords in dual visibility setting
**Why?**
Let dual visibility with Elasticsearch work with list of keywords for backwards compatibility.
No. Any setting involving standard visibility will work as usual: custom search attributes are just ignored and not persisted.
No.

Allow list of keywords in dual visibility setting

---

Makefile
develop/buildkite/pipeline.yml

Fix names of artifact paths to upload.
**Why?**
I mixed these up in a previous PR.

Fix output artifact names in coverage report in buildkite

---

schema/mysql/v8/visibility/schema.sql
schema/mysql/v8/visibility/versioned/v1.4/add_parent_workflow_info.sql
schema/mysql/v8/visibility/versioned/v1.4/manifest.json
schema/postgresql/v12/visibility/schema.sql
schema/postgresql/v12/visibility/versioned/v1.4/add_parent_workflow_info.sql
schema/postgresql/v12/visibility/versioned/v1.4/manifest.json
schema/sqlite/v3/visibility/schema.sql

Add parent workflow info to visibibility schema
**Why?**
Unit tests
No.
No.

Add parent workflow info to visibility schema

---

common/persistence/sql/queue_v2.go
common/persistence/sql/sqlplugin/mysql/queue_v2.go
common/persistence/sql/sqlplugin/postgresql/queue_v2.go
common/persistence/sql/sqlplugin/queue_v2_metadata.go
common/persistence/sql/sqlplugin/sqlite/queue_v2.go
common/persistence/sql/sqlplugin/tests/queue_v2.go
schema/mysql/v57/temporal/schema.sql
schema/mysql/v57/temporal/versioned/v1.11/queues.sql
schema/mysql/v8/temporal/schema.sql
schema/mysql/v8/temporal/versioned/v1.11/queues.sql
schema/postgresql/v12/temporal/schema.sql
schema/postgresql/v12/temporal/versioned/v1.11/queue_v2.sql
schema/postgresql/v96/temporal/schema.sql
schema/postgresql/v96/temporal/versioned/v1.11/queue_v2.sql
schema/sqlite/v3/temporal/schema.sql
schema/sqlite/v3/temporal/versioned/v0.3/queue_v2.sql
tests/dlq_test.go
tests/purge_dlq_tasks_api_test.go
tests/xdc/history_replication_dlq_test.go

Adding FOR UPDATE clause when fetching queueV2 metadata and removing unused field version from queue metadata.
**Why?**
If a queueV2 metadata row is fetched in a transaction, we have to place a lock on that row
to avoid another transaction reading from that line. This can happen when two threads are trying to 
delete messages from the queue. Two of them will update queue metadata and write it back. This will lead 
to a race condition. By adding 'FOR UPDATE' SQL clause, the first transaction will get an exclusive lock
on the row. The second transaction will wait until the first transaction is complete or rollback.
Also, removing the version field from QueueV2 metadata table. We will not be using this field since we are using sql transactions.
Unit …

Adding FOR UPDATE for SelectFromQueueV2Metadata

---

common/membership/ringpop/monitor.go
common/membership/ringpop/ringpop.go
common/membership/ringpop/service_resolver.go

I replaced the atomics we use to manage the membership monitor's state with a fine-grained latch that we hold while it's not safe for Start and Stop to run concurrently. The atomics used in the membership monitor's lifecycle functions weren't enough to prevent race conditions in either it _or_ the rings it manages.
**Why?**
The Start and Stop calls for the various subcomponents here aren't necessarily thread-safe, so we need to prevent the monitor from calling them concurrently. We hold this new lock as little as possible to prevent ringpop's bootstrap processes from stalling our application.
This was originally discovered by go's race detector as a race on the service resolver's WaitGroup: nothing prevented `Stop` from running concurrently with `Start`. It could begin …

Fix a race condition in the membership monitor's lifecycle

---

common/dynamicconfig/constants.go
service/history/api/consistency_checker.go
service/history/configs/config.go

- Add feature flag for shard ownership assertion
**Why?**
- It's a no-op in this codebase. If needed, the logic should live in persistence implementation so that the implementation meets the read-after-write consistency contract of the persistence interface.
- No.

Add feature flag for shard ownership assertion

---

api/persistence/v1/queues.pb.go
client/history/historytest/clienttest.go
common/persistence/client/factory.go
common/persistence/data_interfaces.go
common/persistence/history_task_queue_manager.go
common/persistence/history_task_queue_manager_test.go
common/persistence/tests/history_task_queue_manager_test_suite.go
proto/internal/temporal/server/api/persistence/v1/queues.proto
service/history/api/deletedlqtasks/deletedlqtaskstest/apitest.go
service/history/api/getdlqtasks/getdlqtaskstest/apitest.go
service/history/queues/dlq_writer.go
service/history/queues/dlq_writer_test.go
service/history/queues/executable_test.go
service/history/replication/dlq_writer_test.go
tests/dlq_test.go
tests/purge_dlq_tasks_api_test.go

This PR makes us use the shard ID of the task in the original cluster instead of the shard ID in the current cluster when merging DLQ'd replication tasks (or writing any task to the DLQ actually). 
**Why?**
The number of shards between any two clusters for a given namespace don't have to be the same. One has to be a multiple of the other, though. However, I noticed a bug when using our local xdc config with cluster-a and cluster-b:
```
"Error": "AddTasks failed while re-enqueuing tasks to shard 9 (type: dlq-error-type-invalid-request, retryable: false): Task is for wrong shard: index = 0, task shard = 25, request shard = 9",
```
This error was caused by the fact that the task in question has a different computed shard ID in cluster-b, where there are only 16 shards, than …

Use source cluster shard ID for DLQ

---

service/history/replication/dlq_writer.go
service/history/replication/dlq_writer_test.go
service/history/replication/executable_activity_state_task_test.go
service/history/replication/executable_history_task_test.go
service/history/replication/executable_noop_task_test.go
service/history/replication/executable_task_test.go
service/history/replication/executable_unknown_task_test.go
service/history/replication/executable_workflow_state_task_test.go
service/history/replication/fx.go
service/history/replication/noop_dlq_writer.go
service/history/replication/stream_receiver_monitor_test.go
service/history/replication/stream_receiver_test.go
service/history/replication/task_processor_manager_test.go
service/history/replication/task_processor_test.go
service/worker/dlq/workflow.go
service/worker/dlq/workflow_test.go
service/worker/fx.go
tests/xdc/history_replication_dlq_test.go

This PR adds support for re-enqueuing replication tasks from the DLQ back to their original queue for queue v2.
**Why?**
Currently, we only support re-enqueuing history tasks for queue v2. Support wasn't added for replication tasks immediately for 2 reasons:
1. Testing it is *much* more complicated
2. It requires the ability to connect to a remote cluster
In addition to unit tests, there's an integration test which uses tdbg merge with queue v1, v2, and replication streaming enabled and disabled. It does this:
1. Execute a workflow with replication tasks that we override to return terminal errors
2. Verify that they all end up in the DLQ using tdbg dlq read
3. Use tdbg dlq merge to re-enqueue them all
4. Verify that the workflow now completes in …

Support re-enqueuing DLQ'd replication tasks

---

common/archiver/s3store/README.md
common/archiver/s3store/history_archiver.go
common/archiver/s3store/visibility_archiver.go
common/config/config.go

Ability to configure a loglevel for AWS SDK, which is used during s3 archival. 
**Why?**
This is relevant if one want to troubleshoot s3 archival.
Tested locally
No risk, because by default it is turned `off`, so no change for existing deployments 
No

Ability to enable AWS SDK logging (#5051)

---

service/history/configs/config.go

🚀  This PR turns on the new history task DLQ by default.
**Why?**
Previously, if history tasks, e.g. transfer, timer, etc., failed with terminal errors (i.e. data corruption issues), we would drop the tasks completely 💀 . Now, we guarantee that they will be sent to the history task DLQ. We retry sends forever until they succeed. The history task DLQ supports operation via `tdbg` (under `cmd/tools/tdbg/main.go`). There is also a previous DLQ which only worked for replication and namespace replication tasks, but that one never worked for history tasks. As a result, there are two version of the dlq in tdbg. To use the new one, which is the only way to interact with the history task DLQ, you can run the following command: `tdbg dlq --dlq-version v2 <subcommand>`. The …

Enable the history task DLQ

---

client/history/client.go
client/history/client_test.go
client/history/connections.go
client/history/connections_mock.go
client/history/historytest/clienttest.go

This PR changes the behavior of `getAnyClientConn` to round-robin through the list of members in the history pool, instead of looking in the connection pool.
**Why?**
This fixes an issue where DLQ commands like merge would end up using zombie connections to history hosts that no longer exist. Why? This was part of a small optimization I was making. I figured that we would end up making the client pool large if we kept making connections to different hosts by running DLQ commands over and over when we can instead use any valid connection. However, we never remove connections to dead hosts from this pool, so that strategy doesn't work. Instead, we now round-robin through the list of members in the pool.
I added unit tests for both the connection …

Fix stale DLQ history clients

---

Makefile

In description
**Why?**
It make it hard to work with branches in the API repo.
I asked internally and have only gotten feedback supporting this change.
I did not, if CI passes, we will be good.
Some dependent project's build may break if the rely on this submodule being installed as part of the `make proto` step.
This is fine as there's no contract we'll be breaking.
No

Makefile: remove install-proto-submodule as a dependency to proto

---

common/log/tag/tags.go
common/metrics/metric_defs.go
service/history/queues/dlq_writer.go
service/history/queues/dlq_writer_test.go
service/history/queues/executable_test.go
service/history/replication/dlq_writer_test.go

Adding a metric when a task is written to DLQ.
Also added warning log with task details.
**Why?**
We will have to monitor this metric to see if there are any tasks in DLQ.
Tested locally by making a workflow task fail.

Adding metrics when a task is enqueued to DLQ

---

go.mod
go.sum

This PR updates our version of tchannel to one that contains this change: https://github.com/temporalio/tchannel-go/pull/7.
**Why?**
This should fix a rare race condition that happens where a tchannel is used while there are still handlers being added to it.
I didn't reproduce it actually, but it's a very small change, and the race condition is pretty clear to see.
The only other changes pulled in from this upgrade were changes to the go.mod in tchannel-go, which look pretty innocuous:
```
-    golang.org/x/net v0.0.0-20211015210444-4f30a5c0130f
-    golang.org/x/sys v0.0.0-20211019181941-9d821ace8654
+    golang.org/x/net v0.7.0
+    golang.org/x/sys v0.5.0
```
No, it can wait. This only comes up …

Fix tchannel race condition

---

common/persistence/visibility/store/elasticsearch/converter.go
common/persistence/visibility/store/elasticsearch/converter_test.go
common/persistence/visibility/store/query/converter.go
common/persistence/visibility/store/sql/query_converter.go
common/persistence/visibility/store/sql/query_converter_test.go
tests/advanced_visibility_test.go

Parse `STARTS_WITH` queries to visibility, and build queries to Elasticsearch and SQL.
**Why?**
Support prefix search in visibility queries.
Added unit tests, and integration tests.
No.
No.

Support STARTS_WITH in visibility queries

---

common/nexus/payload_serializer.go
common/nexus/payload_serializer_test.go
go.mod
go.sum

See description
**Why?**
The server should do best effort conversion between Nexus Content and Temporal Payloads so pure Temporal applications don't have to deal with the separate Nexus Content concept.
Added tests.
Non-standard content is converter into a Payload with metadata encoding of `unknown/nexus-content`. Users will need to prepare for that or their Nexus requests may fail.
I believe this is the best option we have to avoid lossy conversion and expose as much information and empower the application.
I considered using `binary/plain` for non-standard content but I'd rather not have these payloads accidentally slip into user's applications.
Far from it.

Implement Nexus Serializer for Temporal Payloads

---

.github/workflows/features-integration.yml

This repo now uses the official features repo, not my fork.
This needed to point at my fork temporarily so that I could release a new version of that repo (which relies on the server itself).

Use the official SDK and feature repos

---

temporal/fx.go
temporal/fx_test.go

Fix setting up pre-allocated search attributes when a secondary SQL visibility is added.
**Why?**
PR https://github.com/temporalio/temporal/pull/4531 removed code that did this.
Started single SQL visibility, and then added secondary SQL visibility. Checked cluster metadata, it looks right.
No.
No.

Fix set up search attributes in secondary SQL visibility

---

service/matching/matching_engine_test.go
service/matching/task_writer.go

I fixed a small and extremely rare race condition in matching. 
**Why?**
This was causing test failures e.g. https://buildkite.com/temporal/temporal-public/builds/13342#018bb7f8-c04f-4f91-b12b-ca4ce6336c1b
```
go test ./service/matching -run TestMatchingEngineSuite/TestAddTaskAfterStartFailure -count 100000
```
Rationale for why this happens is that there is a goroutine reading from `w.maxReadLevel`, and it may or may not read from it before we write to it if we wake it up with the w.sendWriteResponse call before setting the read level.

Fix matching read-level race condition

---

tests/functional_test_base.go

I turned off the history and task queue scanners for all the tests that use `FunctionalTestBase`.
**Why?**
None of the tests we run rely on them, they make extra overhead, and they also trigger some race conditions in several tests that override our task executors. Those race conditions will be fixed separately because those tests shouldn't depend on running in an environment with no system workflows, though.
I reran the tests/dlq_test which was triggering a race condition, slept for 5 seconds, and verified that no other workflow tasks were sent to the task executor except for the ones for the DLQ test itself.
This will mean we're testing the scanners themselves less, but they're already run as part of the `tests/server_test`, …

Don't enable system scanners in functional tests

---

tests/dlq_test.go
tests/xdc/history_replication_dlq_test.go
tools/tdbg/tdbgtest/output_parsing_test.go
tools/tdbg/util.go

This PR makes us use the `context.Context` provided to the CLI command, if one is provided, and it also makes our tests provide one. 
**Why?**
This way, tests can drive timeouts and cancellations when they run `tdbg` commands.
I just looked for references to `app.Run` in our code, and I switched them to `RunContext` wherever it was applicable (not needed for things that aren't I/O related like `tdbg decode`.

Propagate ctx throughout tdbg commands

---

common/persistence/history_branch_util.go
common/persistence/history_branch_util_mock.go
common/persistence/persistence-tests/history_v2_persistence.go
common/persistence/tests/history_store.go
service/history/ndc/workflow_state_replicator.go
service/history/workflow/mutable_state_impl.go

Include WorkflowID & RunID when initializing branch tokens

---

.github/PULL_REQUEST_TEMPLATE.md

- Place comments below section headings
- Use `## Foo` instead of `**Foo**`
- This reduces the amount of noise in the resulting git commit messages, because users will probably understand to delete the comment, replacing it with the requested content.
- `## Foo` is a minor cosmetic improvement over `**Foo**` when reading commit messages. It's quite a big change to the rendered appearance in GitHub, but hopefully people are OK with the new look; it's used by `sdk-go` also.
I used the template to write this PR intro.
None
No

Modify PR template to introduce less noise into commit messages

---

common/membership/interfaces.go
common/membership/interfaces_mock.go
common/membership/ringpop/service_resolver.go
common/util/util.go
common/util/util_test.go
service/frontend/task_reachability.go
service/worker/pernamespaceworker.go
service/worker/pernamespaceworker_test.go
tests/simple_service_resolver.go

To find number of per namespace workers we now use ringpop LookupN method instead of sequentially calling Lookup. The lookup key also changed: worker id was dropped from the hashed string.
Added util.SliceMap function and renamed util.SliceReduce to util.SliceFold
**Why?**
more evenly distribute work across ring
local testing only
not sure
no

make use of ringpop LookN method

---

service/history/api/get_workflow_util.go

1.22.3 build fix for cherry pick build error

1.22.3 build fix for cherry pick build error

---

service/history/api/get_history_util.go
service/history/api/startworkflow/api.go
service/history/history_engine.go
service/history/history_engine_test.go
tests/eager_workflow_start_test.go

Fixed a bug where per namespace search attributes weren't properly aliased in the workflow task's history returned in the eager workflow start path.
The SDK submitted a StartWorkflowExecution request with a `CustomKeywordField` search attribute and the workflow task returned contained a `Keyword04` attribute instead.
**Why?**
It's a bug, it needs fixing.
Locally reproduced the issue and verified the fix.
Also added a test that executes this path.
Can't think of any.
Considering the eager workflow start is still experimental, I don't think we need a hotfix.

Fix eager workflow start mapping of per namespace search attributes

---

service/history/workflow/mutable_state_impl.go

Keep approximate size of mutable state when activity cannot be restarted because of deadline exceeded or other error by nextBackoffInterval 
It is wrong behavior, the mutable state size was reduced before activity replaced
unit tests
not sure what persistence was doing with the wrong size
No

Mutable state approximate size should not change if we do not retry the activity

---

service/history/api/updateworkflow/api.go
service/history/tasks/workflow_task_timer.go
service/history/timer_queue_active_task_executor.go
service/history/workflow/mutable_state_rebuilder.go
service/history/workflow/mutable_state_rebuilder_test.go
service/history/workflow/task_generator.go
service/history/workflow/task_generator_mock.go
service/history/workflow/task_refresher.go
service/history/workflow/workflow_task_state_machine.go
tests/update_workflow_test.go

Add `ScheduleToStart` timeout for speculative WT on normal task queue.
**Why?**
`UpdateWorkflowExecution` API handler tries to add WT to matching directly. This call must be made outside of workflow lock and might fail (if matching is temporarily unavailable, for example). There is no good way to handle this error after lock was released. This is why I introduced this `ScheduleToStart` timeout for speculative WT on the normal task queue. This timeout will ensure that WT will be eventually added to matching and workflow won't stuck.
Also removed special flag which was used to skip transfer task creation when speculative WT is converted to normal before MS with speculative WT is persisted.
Both these speculative WT logic changes (timeout on normal and skip transfer task) …

ScheduleToStart timeout for speculative WT on normal task queue

---

common/persistence/client/quotas.go

-  Use API priority as the default persistence priority
- highest priority used to be API but is now "Operator". And operator level will use 0.2 * specified rate as the limit.

Fix default persistence request priority

---

common/persistence/client/health_request_rate_limiter.go

Always set the RPS of the dynamic rate limiter when it is refreshed
Previously it would only apply changes made to `rateFn` when the dynamic multiplier should be adjusted. The rate function should always be checked to pick up any changes to the maximum RPS dynamic config.
Existing tests
Extra rate limiting

Always set RPS on dynamic rate limiter refresh

---

service/worker/scheduler/workflow.go
service/worker/scheduler/workflow_test.go

Currently Schedule backfill start time is exclusive, this makes change makes it inclusive.
Exclusive schedule backfill start time is confusing. 
Added a new test.
Break existing developer's assumptions. To mitigate that, a new Workflow version has been introduced. Furthermore, the documentation will be updated.
No

Make Schedule backfill start inclusive

---

cmd/tools/cassandra/main.go
cmd/tools/sql/main.go
cmd/tools/tdbg/main.go

Return non-zero exit status when cli tools have bad arguments instead of ignoring the `app.Run` error
Make it possible to integrate tools into a wrapping script that needs to react to whether it succeeds or fails.
Tested exit status locally.
There may be scripts out there that are failing silently. They will now fail loudly, which is appropriate.
No

return non-zero exit status when cli tools have bad arguments

---

.github/workflows/create-tag.yml

Add option to create a draft release notes when creating a tag
Also fixed the step to create a tag to check if it already exists.
Help creating release notes.
Run workflow locally.
No.
No.

Add option to create a draft release notes when creating a tag

---

.github/workflows/create-tag.yml

Change `create-tag` workflow to use `secreats.GITHUB_TOKEN` instead of generating a token.
Not necessary to generate token.

Use GITHUB_TOKEN instead of generating token in create-tag workflow

---

go.mod
go.sum
service/history/api/describeworkflow/api.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_test.go
service/history/workflow/workflow_task_state_machine.go
tests/xdc/advanced_visibility_test.go
tests/xdc/user_data_replication_test.go

Add build id to reset points
To enable reset by build id in batch reset (maybe later individual workflow reset)
New unit tests

Add build id to reset points

---

temporal/fx.go
temporal/server_test.go

No longer providing custom frontend interceptors to history or matching fx graphs
Added an fx value group, `group:"frontendInterceptors"` to prevent custom frontend interceptors from being injected where they are not intended
Bug fix
Added an interceptor to `server_test.TestNewServer()` which will fail if supplied to any handler other than frontend
None
No

Do not provide custom frontend interceptors to history or matching

---

.github/workflows/create-tag.yml

Generate Github app token for create-tag workflow
The `GITHUB_TOKEN` doesn't trigger GHA events, and this workflow is pushing a commit which needs to trigger GHA events.

Generate Github app token for create-tag workflow

---

service/history/ndc/activity_state_replicator.go
service/history/ndc/activity_state_replicator_test.go
service/history/workflow/mutable_state.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_test.go
service/history/workflow/mutable_state_mock.go
service/history/workflow/mutable_state_rebuilder.go
service/history/workflow/mutable_state_rebuilder_test.go
service/history/workflow/workflow_task_state_machine.go
tests/xdc/failover_test.go

The MutableState functions called Replicate* are renamed to Apply*.
It's a common source of confusion; the functions have nothing to do with replication per se.
The replication code _uses_ some of these functions, but it is merely _applying_ data to MS.
Go compiler.
Unlikely: code using reflection to call them.
no

Rename MutableState Replicate* to Apply*

---

develop/buildkite/third_party_deps.txt
service/matching/ack_manager.go
service/matching/ack_manager_test.go
service/matching/matching_engine_test.go

I replaced the outstandingTasks map with an ordered treemap and optimized
completeTask to only scan what was necessary to update the ack level.
The old implementation of completeTask required a full scan of the task
map in order to move the ack level which had terrible performance. 
By storing tasks in an ordered set we can limit the scan's size by
stopping at the first unacked task.
This trades addTask performance for completeTask performance but since all 
added tasks are presumably completed we should be fine with 1/3 the 
performance on addTask for 227x the completeTask performance. With this
change both operations run in about the same amount of time.
Before:
```
$ go test -bench=AckManager ./service/matching/... -run=FooBarBaz
goos: darwin
goarch: arm64
pkg: …
```

Improve ackManager.completeTask performance by two orders of magnitude

---

Makefile

Added a step to re-generate gRPC API clients under `/client`.
Whenever proto files are re-compiled, the gRPC clients should also be re-generated.
Right now the developer has to manually invoke `go generate` (and know where to find them first).
Running `make proto` and `make update-proto` - and observing the clients being updated.
There could be some subtle ordering assumption in `update-proto` that is violated now?
No

Make target for generating service clients

---

common/dynamicconfig/constants.go
service/matching/config.go
service/matching/matching_engine.go

- Mark a tqm live when we're doing a long poll for user data.
- Adjust timeouts so that user data long poll is slightly less than idle unload timeout.
This prevents the annoying `task queue closed` errors from `GetTaskQueueUserData` by keeping a parent partition alive while a child is doing a user data long poll (i.e. as long as any children are loaded).
Mostly manually, with shortened timeouts. (There aren't currently good tests around the idle unload.)

Don't unload task queue while child is polling user data

---

service/history/configs/config.go
service/history/workflow_task_handler_callbacks.go
service/history/workflow_task_handler_callbacks_test.go
service/matching/matching_engine_test.go

Don't drop query results on heartbeat workflow task.
I also renamed confusing `workflowTaskHeartbeating` local var and added comments to explain WT heartbeat logic.
Currently, if SDKs completes WT with `ForceNewWorkflowTask` set to `true` and w/o specifying any commands or messages but query results, these query results are dropped by server and query is sent to worker again. After bunch internal discussion we don't see why server does it for queries while normally accepting commands and messages at the same time. So I decided to remove this "drop" for the parity with messages and commands. After all, currently, if all what workflow does is a local activity, there is no way to query it. 
Removed existing UT.
User code which relays on the fact that local activity must be completed before …

Don't drop query results on heartbeat workflow task

---

common/metrics/errors.go
common/metrics/tags.go

When reporting error type metrics we will now unwrap errors wrapped by fmt.Errorf
Seeing `*fmt.wrapError` in your error metrics isn't particularly helpful. This little loop will unwrap the error until either a non-fmt-error is returned or there's nothing left to unwrap
[I manually tested the code on the go playground](https://go.dev/play/p/HtPvAmdL82A)
None
No

Get the actual error type for fmt.Errorf errors

---

develop/buildkite/docker-compose.yml

Specify patch version of Cassandra image to use in buildkite.
It seems that the latest version (3.11.16) has some issues with buildkite (`Cassandra 3.0 and later require Java 8u40 or later.`)

Fix buildkite cassandra setup

---

common/auth/tls_config_helper_test.go
service/history/api/pollupdate/api_test.go
service/history/api/updateworkflow/api.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/update/cancel_reason.go
service/history/workflow/update/errors_failures.go
service/history/workflow/update/registry.go
service/history/workflow/update/registry_test.go
service/history/workflow/update/state.go
service/history/workflow/update/update.go
service/history/workflow/update/update_test.go
service/history/workflow/util.go
service/history/workflow_task_handler.go
service/history/workflow_task_handler_callbacks.go
service/history/workflow_task_handler_test.go
tests/update_workflow_test.go

Process update rejection and cancel incomplete updates when workflow is completing itself.
Update rejection messages are processed after commands and if there is a command to complete workflow those messages were not processed at all. This PR fixes it.
Also all not accepted updates are canceled if workflow completes itself.
Added new unit and functional tests.
No risks.
No.

Process update rejection when workflow is completing itself

---

.github/workflows/run-tests.yml
common/archiver/s3store/mocks/generate.sh
develop/github/docker-compose.yml
develop/github/mysql-init/init.sql
develop/github/postgresql-init/init.sql

Github workflow to run tests.
I couldn't add tests on `windows-latest` nor `macos-latest` at this moment.
In Windows, there are issues with filepaths in the archiver (eg: `file:///home/` vs `file:///c:\\`, note that in Windows, it needs a forward slash before the actual path `c:\\`, but it messes up with the actual path)
In MacOS, it doesn't have Docker installed by default.
Also, in both Windows and MacOS, some TLS related unit tests are failing.
Replace buildkite.
Ran in my fork: https://github.com/rodrigozhou/temporal/actions/runs/7401242980
No.
No.

Github workflow to run tests

---

common/persistence/serialization/serializer_test.go
common/persistence/tests/util.go
common/testing/fakedata/fakedata.go
common/testing/fakedata/fakedata_test.go
go.mod
go.sum
service/history/api/signalwithstartworkflow/signal_with_start_workflow_test.go

I migrated our usage of `gofakeit` to `go-faker`.
Because `go-faker` does not handle circular references, which we have in our `Failure` proto. See https://github.com/brianvoe/gofakeit/issues/281#issue-2071796056
I added a test which verifies that these cases are handled gracefully. I also removed the workaround we had for this in our `ActivityInfo` generator. 
By default, this is less performant than `gofakeit`. However, by calling `SetRandomMapAndSliceMaxSize(2)` (down from the default of 100), we have comparable performance (on the order of 100 micro seconds for large structs). 
No.

Migrate from gofakeit to go-faker

---

service/worker/scheduler/workflow.go

Remove a `.String()` call from a couple `logger.Debug` calls
In normal situations with log level set to info, these calls would be ignored, but the string would be constructed first. For schedule update, it may be quite large and this is a waste of time. To make things worse, this would even happen on replay.
existing tests

Remove detail from debug logs in schedule workflow

---

service/frontend/fx.go
service/frontend/workflow_handler.go
service/frontend/workflow_handler_test.go
service/worker/scheduler/fx.go
service/worker/scheduler/spec.go
service/worker/scheduler/spec_test.go
service/worker/scheduler/workflow.go

Add a cache for time.LoadLocation as used when compiling schedule specs.
This function can be relatively slow (it accesses the filesystem) and runs each time a schedule with a timezone is replayed, or more if there are updates with timezones too. The results should generally not change within the lifetime of a process, but just in case they do, the cache has a ttl.
existing tests
This is a dependency to a workflow function so we have to sneak it in in an awkward way. Note that previously it was just calling `time.LoadLocation` which is not deterministic either, so this isn't any worse, it's just a cache. We still guarantee determinism by calling methods on `cspec` in a side effect.

Add cache for time.LoadLocation

---

common/persistence/visibility/store/elasticsearch/query_interceptors.go
common/persistence/visibility/store/elasticsearch/query_interceptors_test.go

Fix Elasticsearch visibility query with `ExecutionStatus` when comparing to int.
It should auto convert the int code to the corresponding string (eg: 2 -> 'Completed')
Fixed unit tests
No.
No.

Fix visibility query with ExecutionStatus as int

---

service/history/replication/executable_activity_state_task.go
service/history/replication/executable_history_task.go

Remove unnecessary lock on executable history/activity task.
The replication stack is built on an assumption: only one go routine is processing replication tasks for a single workflow run.
So when batching task, all replication tasks are processed by single go-routine, so no race condition is expected. 
n/a
no, feature is not enabled
No.

Remove unnecessary lock on executable task

---

service/history/queues/dlq_writer.go
service/history/queues/executable.go
service/history/queues/memory_scheduled_queue.go
service/history/queues/mitigator.go
service/history/queues/queue_base.go
service/history/queues/queue_scheduled.go
service/history/queues/rescheduler.go
service/history/queues/scheduler_monitor.go

I updated all metric usage within our history service's queue code to use our new `metric.With` APIs.
See [the initial PR](https://github.com/temporalio/temporal/pull/5187) for details.
Existing tests
None.
No.

Update queue internals to use our new Metrics API

---

docker/config_template.yaml

Add the constant `postgres12_pgx` in the docker configuration template
Related PR : https://github.com/temporalio/docker-builds/pull/179
Support for `jackc/pgx` was added in #4913 but it wasn't possible to use it within the provided configuration template
Checked template generation with `dockerize`
Low risks, doesn't change default behavior
No

Add postgres12_pgx in docker config template

---

common/config/config.go
common/config/persistence.go
common/persistence/cassandra/version_checker.go
common/persistence/sql/version_checker.go
temporal/fx.go
tests/onebox.go

Replace `advancedVisibilityStore` config key with `visibilityStore`
`advancedVisibilityStore` is deprecated

Replace advancedVisibilityStore with visibilityStore

---

common/metrics/metric_defs.go
service/history/replication/executable_task.go

Change replication latency metrics definition and add a new metrics to replace old one.
To provide better visibility of replication lag
n/a
n/a
no.

Change replication latency metrics definition

---

.github/workflows/features-integration.yml

Proof that this is working is in the `feature-tests-dotnet` [CI output](https://github.com/temporalio/temporal/actions/runs/7575278907/job/20633643954?pr=5318) below.

Enable integration testing against dotnet SDK

---

.github/workflows/run-tests.yml

Cache docker images in GHA tests.
Docker pull have rate limits. Changing to pull only once per workflow.
https://github.com/temporalio/temporal/actions/runs/7504293030/job/20431126643
No.
No.

[GHA test] Cache docker images

---

service/history/api/consistency_checker.go
service/history/api/consistency_checker_test.go
service/history/api/respondactivitytaskfailed/api_test.go
service/history/api/startworkflow/api.go
service/history/workflow/cache/cache.go
service/history/workflow/cache/cache_mock.go
service/history/workflow/cache/cache_test.go

- Only return ReleaseFn when locking current workflow execution, not the workflow context.
- Workflow context of the current workflow is not supposed to be used by application logic. The fact that a workflow context is created is just an implementation detail of the cache.

Only return ReleaseFn when locking current workflow execution

---

config/development-cluster-a.yaml
config/development-cluster-b.yaml
config/development-cluster-c.yaml

- use `all-apis-forwarding` instead of `selected-api-forwarding` policy for local xdc development
- `all-apis-forwarding` policy forwards worker requests as well, so only one worker needs to be started for development instead of one worker for each cluster. 
- `all-apis-forwarding` is also what's used in production.

Use all-apis-forwarding for xdc development

---

common/dynamicconfig/constants.go
config/dynamicconfig/development-cass.yaml
config/dynamicconfig/development-sql.yaml
service/frontend/admin_handler.go
service/frontend/admin_handler_test.go
service/frontend/service.go

- Use separate flag for forwarding admin DeleteWorkflowExecution requests
- Originally I want to call the new flag "AdminHandlerAccessHistoryFraction", but there another admin requests "GetWorkflowExecutionRawHistoryV2" in admin handler (used by normal xdc logic) that should be controlled together with rest of the workflow history related APIs in workflow handler.  
- So that we can have the capability of deleting a corrupted workflow sooner in production. Decoupled with those workflow history related api, which may need more testing and rollout time.
- Tested admin delete locally with new flag set to 1.0

Use separate flag for forwarding admin DeleteWorkflowExecution requests

---

CONTRIBUTING.md
Makefile
develop/buildkite/README.md
develop/docker-compose/README.md
develop/docs/run_dependencies_host.md

Switch from `docker-compose` to `docker compose`.
`docker-compose` was deprecated some time ago.
Run locally.
No risks.
No.

Switch from docker-compose to docker compose

---

common/dynamicconfig/constants.go
service/history/archival_queue_factory.go
service/history/configs/config.go
service/history/timer_queue_factory.go
service/history/transfer_queue_factory.go
service/history/visibility_queue_factory.go

Remove the `history.queueMaxReaderCount` dynamic config in favor of a per queue config in the form of `history.{queue}QueueMaxReaderCount`
Nexus Callback and Operation multi-destination queues need to increase the default limit without applying the increased limit to other queues.
Ran existing tests.
Users may have altered the existing configuration in their production setup but that's highly unlikely and it should be fine to add a warning in the release notes to mention that the old value is no longer applied.

Per queue max reader count

---

service/history/callbacks/statemachine.go
service/history/callbacks/statemachine_test.go
service/history/statemachines/sm.go
service/history/statemachines/sm_test.go
service/history/tasks/callback_backoff_task.go
service/history/tasks/callback_task.go
service/history/tasks/task.go
service/history/tasks/task_mock.go

- Add a small statemachine library to history service
- Implement the callback state machine
More prep work for Nexus callbacks
I also ran this as part of the callback poc integration tests, but the rest of the work there is not quite ready to be merged.

Implement Callback State Machine

---

service/history/workflow/update/registry_test.go
service/history/workflow/update/update.go
service/history/workflow/update/update_test.go
service/history/workflow/update/validation.go

Add update acceptance message validation.
If SDK omitted these fields, they are not written into the history event, and then this partially filled history event will not be proceessed properly by SDK.
No risks, all current SDK should set these fields.
No.

Add update acceptance message validation

---

common/xdc/ndc_history_resender.go
common/xdc/ndc_history_resender_test.go
service/frontend/admin_handler.go
service/history/replication/dlq_handler.go
service/history/replication/fx.go
service/history/replication/task_processor_manager.go
service/history/timer_queue_factory.go
service/history/transfer_queue_factory.go

- change method signature
- Use replication history event handler for resend usecase
Use replication event handler for handling replication resend event
To allow passive side handle resend when migration ns back to original cluster
integration test
n/a

Use replication event handler for handling replication resend event

---

common/metrics/metric_defs.go
service/worker/scheduler/workflow.go

Add `schedule_action_delay` metric for the delay between when a scheduled workflow is supposed to start and when it did start.
Have a more accessible metric for schedule delay.
Manually

Add a metric for schedule delay

---

common/metrics/metric_defs.go

- Fix HistoryCacheGetOrCreateCurrent metric tag
- That's missed in a previous fix for metric tags: https://github.com/temporalio/temporal/pull/3579/files#diff-929edcb087a0a718eb68396d7c4c1508325ec9ee31a7633ee8c9ae7625658d56R1024

Fix HistoryCacheGetOrCreateCurrent metric tag

---

common/persistence/client/targeted_fault_injection.go

Include API name in fault injection error message. Instead of 
`fault injection error (0.050000): context deadline exceeded`
it will say 
`fault injection error at ReadHistoryBranch with 0.05 rate: context deadline exceeded`.
Simplify debugging.
Run.
No risks.
No.

Include API name in fault injection error message

---

Makefile
common/persistence/client/targeted_fault_injection.go
config/development-cass-es-fi.yaml

Add `persistence.TimeoutError` support to fault injection.
Real persistence store never returns `context.DeadlineExceeded` error but returns `persistence.TimeoutError` instead.
Run locally.
No risks.
No.

Add persistence.TimeoutError support to fault injection

---

common/searchattribute/defs.go
service/worker/deletenamespace/deleteexecutions/activities.go
service/worker/deletenamespace/deleteexecutions/workflow_test.go
service/worker/deletenamespace/reclaimresources/activities.go
service/worker/deletenamespace/reclaimresources/activities_test.go
service/worker/migration/activities.go
tests/functional_test_base.go
tests/namespace_delete.go
tests/schedule.go
tests/xdc/failover_test.go
tests/xdc/user_data_replication_test.go

Replacement for #4060 (can't reopen that one anymore).
Tweak ListWorkflows query in force-replication and delete namespace workflow to include other namespace divisions.
These workflows have to operate on all workflows in a namespace regardless of namespace division.
tested queries manually, added check in schedule integration test

Match all namespace divisions in internal workflows

---

service/history/ndc_task_util.go
service/history/timer_queue_task_executor_base_test.go
service/history/transfer_queue_active_task_executor_test.go

- Validate history task by shard clock
- Validation based on eventID is not good enough as certain operation does not generate events.
- E.g activity heartbeat timer will not be processed if a stale mutable state has no idea that the activity is started. Check based on eventID don't be able to catch this since there's no new event when starting the activity.
- Unit test
- More shard movement.
- Could be.

Validate history task by shard clock

---

common/persistence/serialization/serializer.go
common/persistence/visibility/store/elasticsearch/client/client.go
common/persistence/visibility/store/elasticsearch/client/client_mock.go
common/persistence/visibility/store/elasticsearch/client/client_v7.go
service/history/queues/executable.go
service/history/queues/executable_mock.go
tests/test_cluster.go

I added a sentinel interface for errors that we will use to immediately send a task to the DLQ
Having a sentinel (or marker) interface for this cleans up our implementation and let's us trivially extend it to support new kinds of terminal errors as we discover them
Existing tests
None
No

Add a sentinel interface for terminal task errors

---

service/history/queues/reader.go
service/history/queues/rescheduler.go
service/history/queues/rescheduler_test.go

- Do not set reschedule time for a scheduled task before it's fire time.
- Task can not be processed before it's scheduled time
- On failover however we need to immediately reschedule "all" tasks for the failover namespace since those tasks may have been retrying for a long time when running standby logic and backoff interval is too long. But if a task is not supposed to be processed yet, it should not be rescheduled.
- Unit test
- YES

Fix scheduled task rescheduling on failover

---

common/tasks/interleaved_weighted_round_robin.go
common/tasks/interleaved_weighted_round_robin_test.go

Flaky test: https://github.com/temporalio/temporal/actions/runs/7734357310/job/21088315026#step:4:162
The update to numInflightTask and the check in the test has race condition.
Added a wait step in scheduler shutdown logic to wait for the update before checking.
- Fix flaky test
- Longer task scheduler shutdown time upon service restart
- No.

Fix flaky test in iwrr scheduler suite

---

common/tasks/interleaved_weighted_round_robin.go
common/tasks/interleaved_weighted_round_robin_test.go

- Reset inflight task count in UpdateWeight test. That test manually increase the inflight task count to test dispatch logic, but there's no actual task for it. So the shutdown logic will be blocked on the non-existing inflight task.
- N/A
- No

Fix iwrr scheduler UpdateWeight test

---

common/persistence/serialization/serializer.go
service/history/queues/executable.go
service/history/queues/executable_mock.go
service/history/queues/executable_test.go

1. I refactored HandleErr so it's more obvious what processing is occurring
2. I updated the `TerminalTaskError.IsTerminalTaskError` interface to return a bool. When true, it's terminal and we'll send a task to the dlq
3. I added `serviceerror.DataLoss` to our list of unexpected, non-retryable service errors
The two cleanups are self-explanatory, but the third (DataLoss handling) is because those errors are non-recoverable and we should not block task processing because of them.
Existing tests
None
No

Improve handling of terminal task errors

---

.github/workflows/create-tag.yml

Fix check to create draft release notes in create-tag GHA job
Boolean inputs are actually strings with `'true'` of `'false'` values.

Fix check to create draft release notes in create-tag job

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/workflow/cache/cache.go
service/history/workflow/cache/cache_test.go

Keep history cache dynamic config backward compatible
Reuse the old dynamic config for shard level cache.

Keep history cache dynamic config backward compatible

---

service/history/api/consistency_checker.go
service/history/api/pollupdate/api.go
service/history/api/pollupdate/api_test.go
service/history/api/signalwithstartworkflow/signal_with_start_workflow.go
service/history/api/updateworkflow/api.go
service/history/api/workflow_context.go
service/history/workflow_task_handler_callbacks.go

Remove 3 methods from `WorkflowLease` interface. Following amazing #5386 rename PR.
Because they don't belong to `WorkflowLease` interface.
Build locally.
No risks.
No.

Remove 3 methods from WorkflowLease interface

---

common/backoff/jitter.go
common/backoff/jitter_test.go

FullJitter returns [0, input). Fix the test which verified the result in range of [0, 2*input).
Also simplify the FullJitter implementation. 
It was confusing what the range of the result should be.
Unit test
No
No

Fix FullJitter unit test

---

service/history/replication/executable_task.go
service/history/replication/executable_task_test.go

Handle data corruption in history resend.
1. When source cluster has a data corruption issue, it can ship partial data in resend history. With the two layers of resending (this is to handle resend across different workflow runs), this will cause a chain reaction. 
Unit tests

Handle data corruption in history resend

---

service/history/shard/context_impl.go
service/history/shard/context_test.go

`ContextImpl.updateShardInfo` now uses the `timeSource` already present on the `ContextImpl` struct.
While here I added tests for `updateShardInfo` as I'm going to change our shard update logic soon.
This let's us manipulate time when testing shard update scenarios (the behavior will change)
New unit tests
None
No

Update updateShardInfo to use the injected time source and test SetQueueState

---

service/history/api/create_workflow_util.go
service/history/history_engine2_test.go
service/history/history_engine3_eventsv2_test.go
service/history/history_engine_test.go
service/history/ndc/history_replicator.go
service/history/ndc/mutable_state_initializer.go
service/history/ndc/state_rebuilder.go
service/history/ndc/state_rebuilder_test.go
service/history/ndc/workflow_state_replicator_test.go
service/history/replication/ack_manager_test.go
service/history/timer_queue_active_task_executor.go
service/history/timer_queue_active_task_executor_test.go
service/history/timer_queue_standby_task_executor_test.go
service/history/transfer_queue_active_task_executor_test.go
service/history/transfer_queue_standby_task_executor_test.go
service/history/visibility_queue_task_executor_test.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_restart_activity_test.go
service/history/workflow/mutable_state_impl_test.go
service/history/workflow/mutable_state_rebuilder.go
service/history/workflow/mutable_state_rebuilder_test.go
service/history/workflow/test_util.go
service/history/workflow/workflow_test/mutable_state_impl_test.go
service/history/workflow_task_handler.go
service/history/workflow_task_handler_callbacks_test.go

This is a prefactor to populate NamespaceID/WorkflowID/RunID sooner when
initializing mutable state so they are available to other initialization
logic.

Populate NamespaceID/WorkflowID/RunID when initializing mutable state

---

common/dynamicconfig/constants.go
common/log/tag/values.go
common/persistence/persistence_metric_clients.go
common/rpc/interceptor/telemetry.go
common/rpc/interceptor/telemetry_test.go
common/tasks/dynamic_worker_pool_scheduler.go
service/frontend/service.go
service/frontend/workflow_handler.go
service/history/api/describeworkflow/api.go
service/history/callback_queue_active_task_executor.go
service/history/callback_queue_active_task_executor_test.go
service/history/callback_queue_factory.go
service/history/callback_queue_standby_task_executor.go
service/history/configs/config.go
service/history/queue_factory_base.go
service/history/queues/grouper.go
service/history/queues/grouper_test.go
service/history/queues/scheduler.go
service/history/task_executor_test.go
service/history/tasks/task_category_registry.go
service/history/tasks/utils.go
temporal/fx.go
temporal/fx_test.go
tests/callbacks_test.go
tests/functional.go
tests/test_cluster.go

- Add callback queue processor and missing boilerplate to allow callbacks to work E2E.
- Add dynamic configs to disable accepting callbacks on the frontend and starting the callback queue processor.
**Only review the last commit**, the rest is part of #5356 and #5362
This completes the E2E callback flow, part of the effort for integrating Nexus into the server.
I added integration tests and @MichaelSnowden stress tested it locally (with a slightly different branch of the code).
Not merging this into main just yet but we're close.
I don't see any risks as long we don't enable the new dynamic configs.

Basic E2E done for callback processor

---

client/admin/metric_client.go
client/frontend/metric_client.go
client/history/metric_client.go
client/matching/metric_client.go
common/log/tag/tags.go
common/log/tag/tags_test.go
common/metrics/tags.go
common/util/error_type.go
service/history/queues/executable.go
service/history/transfer_queue_active_task_executor.go
temporal/fx.go

1. Port the type unwrapping code from our metrics to our util package and use it
2. Rename tag.ErrorType to tag.ServiceErrorType and create a new tag.ErrorType
3. Report the type for all task errors we log
So that we know what type of unexpected errors we're encountering during task processing

Improve error type extraction for logs

---

common/collection/oncemap.go
common/collection/oncemap_test.go

Added a OnceMap collection to common.
> OnceMap is a concurrent map which lazily constructs its values. Map values are initialized on-the-fly, using a
> provided construction function only when a key is accessed for the first time.
I have a couple of uses for it in the nexus branch.

Add oncemap collection

---

common/persistence/tests/history_store.go

This replaces history store tests relying on completely random shard ids
with monotonically increasing shard ids across each test.
existing tests

Make history store tests use sequential shard ids

---

temporal/fx.go
temporal/server_option.go
temporal/server_options.go
temporal/server_test.go

Removed the `group:"frontendInterceptors"` fx tag from custom frontend interceptor parameter and result structs. Instead custom frontend interceptors are provided directly to the frontend fx app using `fx.Supply`
fx was not correctly injecting these and the value group was unnecessary
Manually
None
No

Fix custom frontend interceptor injection

---

common/testing/runtime/goroutine.go
tests/update_workflow_test.go

Fix flaky update test.
Depending on how go runtime schedules different goroutines, there is a chance that WFT is dispatched to worker before update reached the server.
Instead of sleep for short duration, tests use helper function `WaitGoRoutineWithFn` introduced in this PR. This function searches over call stacks of all goroutines for specific call. As soon as internal update handler code reached `WaitOutcome` function, it means that update handler got to the point where it waits for update results.
Run locally.
No risks.
No.

Fix flaky update test

---

common/metrics/metric_defs.go
common/persistence/cassandra/history_store.go
common/persistence/client/fault_injection.go
common/persistence/data_interfaces.go
common/persistence/data_interfaces_mock.go
common/persistence/execution_manager.go
common/persistence/history_manager.go
common/persistence/mock/store_mock.go
common/persistence/persistence-tests/history_v2_persistence.go
common/persistence/persistence_interface.go
common/persistence/persistence_metric_clients.go
common/persistence/persistence_rate_limited_clients.go
common/persistence/persistence_retryable_clients.go
common/persistence/sql/history_store.go
tests/archival.go

- Remove GetHistoryTree from persistence manager
- Prepare for the next change for store layer GetHistoryTree. https://github.com/temporalio/temporal/pull/5411
- Not used by application layer. 
- Not supported by the new history store implementation

Remove GetHistoryTree from persistence manager

---

common/persistence/cassandra/history_store.go
common/persistence/client/fault_injection.go
common/persistence/history_manager.go
common/persistence/mock/store_mock.go
common/persistence/persistence_interface.go
common/persistence/sql/history_store.go
common/persistence/tests/history_store.go

- Get history tree using branchToken instead of treeID in store layer.
- This change is based on https://github.com/temporalio/temporal/pull/5410
- TreeID does not contain enough information in the new history store impl.
- Existing impl

Persistence store GetHistoryTreeContainingBranch

---

common/dynamicconfig/constants.go
common/metrics/defs.go
common/metrics/metric_defs.go
service/history/configs/config.go
service/history/queues/queue_base.go
service/history/queues/reader.go
service/history/queues/reader_group_test.go
service/history/queues/reader_test.go
service/history/queues/slice.go
service/history/queues/slice_test.go
service/history/queues/tracker.go
service/history/shard/context.go
service/history/shard/context_impl.go
service/history/shard/context_mock.go
service/history/shard/context_test.go
service/history/shard/context_testutil.go
service/history/visibility_queue_task_executor_test.go

Our shard info update logic now monitors how many tasks have been completed across all queues. If enough changes have occurred it will persist changes to our database even if `ShardUpdateMinInterval` time hasn't elapsed since the last change. The time between updates and the number of tasks completed per update can be monitored using `tasks_per_shardinfo_update` and `time_between_shardinfo_updates` metrics.
While here I extracted the metric calculation from the updateShardInfo function.
In the previous code we'd stop updating metrics if we stopped updating shard info
which isn't the behavior we want. Now it's handled by a separate goroutine that
grabs the shard's read lock as needed.
Follow-up work will handle updating shard info based on replication task completion if it makes sense to. …

Only update shard info when enough tasks are acked or time has passed

---

service/history/api/create_workflow_util.go
service/history/api/signalwithstartworkflow/signal_with_start_workflow.go
service/history/api/startworkflow/api.go
service/history/history_engine2_test.go
service/history/timer_queue_active_task_executor.go
service/history/workflow/mutable_state.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_mock.go
service/history/workflow/mutable_state_rebuilder.go
service/history/workflow/mutable_state_rebuilder_test.go
service/history/workflow/test_util.go
service/history/workflow_task_handler.go

MutableState's `SetHistoryTree` has an unused parameter. (not used downstream either)
`ctx` often implies "side effect", sort of like the IO Monad, but there is no side effect here. 
Compiler.
I cannot see any. The change can easily be reverted if requirements change.
No

Remove `ctx` from SetHistoryTree

---

common/persistence/history_task_queue_manager.go
service/frontend/admin_handler.go
service/frontend/admin_handler_test.go

- Deprecate taskCategoryRegistry usage for DLQ Key on frontend
- Frontend should not use task category registry. That component should be used only by history service.

Deprecate taskCategoryRegistry usage for DLQ Key on frontend

---

service/matching/matching_engine.go

In description.
This field should never be nil as expected by the TS SDK.
This may happen if ScheduleActivityExecution was recorded in version 1.23 and the server was rolled back.

Ensure PollActivityTaskQueueResponse.ScheduleToCloseTimeout is not nil

---

service/history/command_checker.go

Run timeouts for schedule activity events events will always be valid.
In 1.22 we always had a valid run timeout when checking schedule activity events; even though it was a `*time.Duration` in the proto message we converted it to a full `time.Duration` value before validating the command. With the proto rework in 1.23 that was dropped and we pass the `*durationpb.Duration` through without checking it's validity.
This causes the TypeScript SDK to crash as it assumes that the ScheduleToStart and ScheduleToClose timeouts are always valid.
Since we can't force all our users to upgrade their SDKs for obvious reasons, we're going to ensure we behave just like we did in 1.22
I've confirmed that this change fixes the bug uncovered by our [TypeScript Hello World …

history: ensure that activity run timeouts are non-nil

---

service/matching/matching_engine.go
service/matching/matching_engine_test.go

GetTaskQueueUserData returns a successful "no change" when the task queue is closing, instead of an Unavailable error.
1. The caller will retry on both success and failure, so it doesn't really matter.
2. Returning success avoids misleading logs about errors (this was improved in #5227 but still happens on service deployment/restart).
3. More subtly, an unavailable error is actually retried by the server interceptor, which causes the task queue to be reloaded again. This can cause extra bouncing of task queues during deployment and increase latency. A success is not retried.
changed unit test, tested locally with matching restarts

GetTaskQueueUserData returns success on task queue closing

---

service/history/workflow/activity.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_restart_activity_test.go
service/history/workflow/task_generator.go
service/history/workflow/task_generator_mock.go

When scheduling activity task version from mutable state (which is the source of truth) used instead of activity
There is temporal coupling between task generation and activity update. The activity received in the function is actually an alias of the activity stored in the mutable state. If we update activity MS size will change and cause incorrect update size calculation. On other hand if we do not update activity, created task will have incorrect version.
Run tests.
Unknown.
No.
Yes

fix version in activity task generation.

---

common/telemetry/config.go
common/telemetry/env.go
common/telemetry/env_test.go
develop/docs/tracing.md
temporal/fx.go

- allow configuring a custom OTEL `service.name` prefix
- allow configuring an OTEL exporter via env vars (following the [OTEL spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options))
**Note that the OTEL exporter from the environment variables will only be created if there isn't already one from the config.** Creating an additional one wouldn't make any sense since the env variables would be applied to both anyways and there would not be any difference between them.
Addresses:
- https://github.com/temporalio/temporal/issues/4042
- https://github.com/temporalio/temporal/issues/4041
- our own (increasing) need to enable OpenTelemetry tracing without touching the Server config (for ad-hoc debugging when working …

OTEL setup via environment variables

---

service/matching/matcher.go

Followup to #5345: In addition to interrupting polls blocked in this matcher, interrupt polls that have been forwarded too.
When we unload a task queue we should interrupt all open requests on it. In practice it doesn't make a big difference (for stuck pollers) because if the parent also moves, it will interrupt the forwarded request, and if it doesn't, then the poll won't be stuck.
Local testing with matching restarts

Interrupt forwarded polls on task queue close

---

.golangci.yml
common/dynamicconfig/constants.go
common/membership/ringpop/factory.go
common/membership/ringpop/monitor.go
common/util/util.go
service/matching/config.go
service/matching/matching_engine.go
service/matching/service.go

Connect the changes in #5431 to dynamic config for matching.
Be able to adjust to membership changes faster.
mostly local testing, will test in test clusters before release
This dynamic config shouldn't be enabled before fully rolling out this release, otherwise some nodes will understand the new labels and some won't.

Use scheduled membership changes in matching and drop unload delay

---

temporal/server_impl.go

Instead of starting all services in one process in parallel, serialize the startup in a defined order, and the shutdown in the reverse order.
This reduces noisy error logs during both startup and shutdown.
I originally thought that serializing startup would be vulnerable to the problem fixed in #3100 but I couldn't reproduce it after a bunch of testing, so I think some other change in between must have also addressed that. If that problem reappears, though, an easy fix would be to start matching and history at the same time, and wait for them before moving on to frontend.
local server startup/shutdown
Generally multiple services in one process is only used in development, so this shouldn't have any effect on production.

Use explicit startup/shutdown order for development servers

---

go.mod
go.sum

Updating Go SDK to https://github.com/temporalio/sdk-go/tree/v1.25.1-unknown-flag to handle SDKPriorityUpdateHandling flag
Allow safe rollback
Testing was done on the SDK side
No
No
Yes

Update Go SDK to handle SDKPriorityUpdateHandling flag

---

service/frontend/service.go
service/frontend/workflow_handler.go
tests/advanced_visibility.go
tests/versioning.go
tests/xdc/user_data_replication_test.go

Use FrontendEnableWorkerVersioningRules flag for Versioning Rules API instead of previous FrontendEnableWorkerVersioningData flag
Because it's a new feature, so it makes sense to have a separate flag.
Versioning integration tests pass
None
There's a comment where the flag is defined
No

Use FrontendEnableWorkerVersioningRules flag

---

common/persistence/sql/sqlplugin/mysql/nexus_incoming_services.go
common/persistence/sql/sqlplugin/postgresql/nexus_incoming_services.go
common/persistence/sql/sqlplugin/sqlite/nexus_incoming_services.go
schema/mysql/v8/temporal/schema.sql
schema/mysql/v8/temporal/versioned/v1.12/manifest.json
schema/mysql/v8/temporal/versioned/v1.12/nexus_incoming_services.sql
schema/postgresql/v12/temporal/schema.sql
schema/postgresql/v12/temporal/versioned/v1.12/manifest.json
schema/postgresql/v12/temporal/versioned/v1.12/nexus_incoming_services.sql
schema/sqlite/v3/temporal/schema.sql
schema/sqlite/v3/temporal/versioned/v0.4/manifest.json
schema/sqlite/v3/temporal/versioned/v0.4/nexus_incoming_services.sql

Renaming the SQL nexus services table version table.
To make it more generic in case it is used for other table metadata in the future.
Existing tests

Rename SQL table `nexus_incoming_services_table_version` to `nexus_incoming_services_partition_status`

---

service/history/api/startworkflow/api.go
service/history/history_engine.go

Add a hook to Start Workflow, in-between Workflow Execution creation and its persistence.
In preparation of upcoming Update-with-Start changes.
The new `withStart` path will be used and tested in subsequent PRs.
The existing path is covered by existing tests.

Add "beforeCreateHook" hook to Start Workflow 

---

service/worker/scheduler/workflow.go
service/worker/scheduler/workflow_test.go

After an update, the schedule workflow goes back to the previous action/update and recomputes next times from there, instead of from the current time.
Fixes #4866. Fixes the situation where an update happens in between the nominal time and the jittered time of an action.
new unit test

Recalculate schedule times from previous action on update

---

.golangci.yml
service/history/historybuilder/history_builder_categorization_test.go

Expanded the lint exclusion rules to include not just functional tests but all tests.
When using subtests, it's easy to get an unhelpful "cyclomatic complexity" error.

disable cyclomatic/cognitive complexity for all tests

---

service/history/api/updateworkflow/api.go
service/history/history_engine.go

(1) Allow to run an Update operation with a custom `WorkflowLease`.
(2) Separate the WorkflowLease-specific step from the post-WorkflowLease steps.
This is a refactoring to enable Update-With-Start. It requires these two abilities mentioned above.
Existing test.

Allow Update to use custom workflow lease

---

common/searchattribute/encode_value.go
common/searchattribute/encode_value_test.go
common/util.go
service/frontend/workflow_handler.go
service/frontend/workflow_handler_test.go
service/history/command_checker.go

Add string validation for a few string fields
Since we disable utf8 string validation from proto level, we want to enforce minimal validation for some key fields.
Unit tests
No

Add validation for a few string fields

---

.github/workflows/stale.yml

Mark Pull Requests - but not Issues - as stale after 120 days.
Nudge author to either close or resurrect their PR from its slumber.
None. The "stale" label simply can be removed by the author; no PR is closed automatically.

Mark PRs as stale after 6mo

---

service/history/api/signalwithstartworkflow/signal_with_start_workflow.go
service/history/api/startworkflow/api.go
service/history/api/workflow_id_reuse_policy.go
service/history/history_engine2_test.go

- clearer distinction between the behavior for closed and running workflows
- name that isn't particular to workflowIdReusePolicy, but the more general issue of an "ID duplication"
Preparing for changes from https://github.com/temporalio/api/pull/359 by pulling this refactor in early, reducing the size of the change later.
Existing tests + added a test for Terminate-if-Running earlier in https://github.com/temporalio/temporal/pull/5483.

Refactor handler for workflowIdReusePolicy

---

tests/nexus_api_test.go

In description.
It's unsafe to use test suite helpers from goroutines. I didn't know that when I originally wrote these tests.
See test failure here:
https://github.com/temporalio/temporal/actions/runs/8177154337/job/22358369314?pr=5497
Ran tests a few times locally.

Fix race in nexus_api_test.go

---

common/membership/interfaces.go
common/membership/static/fx.go
common/membership/static/monitor.go
common/membership/static/service_resolver.go
tests/onebox.go

Moved the non-ringpop, static membership implementation into its own package.
First step in making it available to the Temporal dev server. I believe that'll make the dev server less flaky ("Not enough hosts to serve the request").
Is tests.

Move static membership out of tests

---

common/persistence/visibility/visibility_manager_impl.go

Fix execution duration calculation in Visibility
PR #4961 changed the definition of execution duration by accident.

Fix execution duration calculation in Visibility

---

common/persistence/sql/sqlplugin/interfaces.go
common/persistence/sql/sqlplugin/mysql/plugin.go
common/persistence/sql/sqlplugin/mysql/session/session.go
common/persistence/sql/sqlplugin/mysql/session/session_test.go

Attempting to configure a MySQL 8 Visibility database with go-sql-driver/mysql's `interpolateParams` option will now fail.
There are a number of reasons why this doesn't work right now so we're going to prevent it from happening while we discuss how much we should invest in fixing it. The current work to fix this is in https://github.com/temporalio/temporal/pull/5428
Added a new test
There should be none. Any user who has currently set up their database this way will already have encountered exciting errors like `Cannot create a JSON value from a string with CHARACTER SET 'binary'` and `Unable to parse ExecutionStatus value from DB`.
That's up for discussion

Ban the connect attr interpolateParams for MySQL 8 Vis dbs

---

common/metrics/metric_defs.go
service/history/queues/action.go
service/history/queues/action_pending_task_count.go
service/history/queues/action_reader_stuck.go
service/history/queues/action_slice_count.go
service/history/queues/action_slice_predicate.go
service/history/queues/mitigator.go
service/history/queues/mitigator_test.go
service/history/queues/queue_base.go
service/history/queues/reader_group.go
service/history/queues/reader_group_test.go

- Remove queue reader registration error handling logic
- This PR is a follow up of https://github.com/temporalio/temporal/pull/5420
- Queue reader creation is an in-memory operation and should always succeed. Those error handling logic was added for a deprecated design where upon creating a queue reader, the logic also needs to talk to persistence layer.
- Risk is low as those logic are never triggered. However, is a bug is introduced in this PR, task can be lost.
- N/A
- No

Remove queue reader registration error handling logic

---

tests/onebox.go

Unused function `newSimpleHostInfoProvider` was removed.
Unused. No references to it. 
compile check.
N/A
No

Remove unused function

---

common/enums/defaults.go
service/history/api/reapplyevents/api.go
service/history/api/resetworkflow/api.go
service/history/api/resetworkflow/api_test.go
service/history/ndc/transaction_manager.go
service/history/ndc/transaction_manager_test.go
service/history/ndc/workflow_resetter.go
service/history/ndc/workflow_resetter_mock.go
service/history/ndc/workflow_resetter_test.go
service/history/transfer_queue_active_task_executor.go
tests/reset_workflow.go

- Start honoring the new `reset_reapply_exclude_types` request field added in https://github.com/temporalio/api/pull/348 
- Change all reapply codepaths to specify excluded event types rather than included
- Pass the set of excluded types further down the stack
- Delete a pointless helper function
- We must honor the new request field because it is in the API and it is how we are going to control update reapply when we implement that
- The previous code was not future-proof: there were various codepaths passing `enumspb.RESET_REAPPLY_TYPE_SIGNAL` to mean "reapply everything". This PR changes those codepaths to pass an empty set of exclusions, which is robust to future additions of new reappliable event types.
- The actual work is done by `reapplyEvents`, and the excluded types had to be …

Migrate to reset reapply event type exclusions instead of inclusions

---

service/history/replication/stream.go
service/history/replication/stream_sender.go
service/history/replication/stream_sender_test.go
service/history/replication/stream_test.go

1. Fix stream_sender to return Stream error when there is error on stream
2. Avoid infinite retry on stream event loop wrapper
1. stream_sender's send/recv error is not properly wrapped, so the eventloop wrapper is retrying infinitely on the "rpc error"
2. Avoid the infinitely retry
Unit test
No risk.
n/a
Should only affecting 1.24.

Fix stream_sender retry logic

---

common/namespace/registry.go
common/namespace/registry_mock.go
common/namespace/registry_test.go

Add GetNamespaceWithOptions and GetNamespaceByIDWithOptions to namespace.Registry. The available options so far are: DisableReadthrough, to disable the readthrough cache behavior.
I have a use case where I want to avoid readthrough for a namespace that may not exist to avoid polluting the negative lookup cache (which would break integration tests that do an update right after a create). There are other ways to solve this problem but this seemed simplest. It also may be useful in cases where the caller is willing to accept false negatives in exchange for a guarantee of lower latency.
new unit test

Add GetNamespace[ByID]WithOptions

---

common/persistence/sql/sqlplugin/sqlite/plugin.go

Sort sqlite connect attributes to ensure a deterministic string so the sqlite pool logic works correctly.
I noticed a lot of `database is locked (5) (SQLITE_BUSY)` errors when using a local dev server, and tracked it down to multiple services having separate connection to the db. The sqlite connection pool is supposed to prevent this, but it depends on the mapping from `ConnectAttributes` to a string being deterministic. The code that constructed the string was iterating over a `map[string]string` without sorting the keys making it nondeterministic.
local testing, saw no more SQLITE_BUSY errors

Ensure we don't open sqlite multiple times

---

common/dynamicconfig/constants.go
config/dynamicconfig/development-cass.yaml
config/dynamicconfig/development-sql.yaml
service/matching/config.go
service/matching/matching_engine.go

Adding a sampled logging when a workflow query task times out.
Need this to be able to debug issues in the future when workflow queries timeout. 
Ran it locally with the sampling rate set to 1 and simulated a timeout. Observed that the data is logged.
N/A
No

Add sampled logging when workflow query task times out

---

common/archiver/s3store/README.md

Added permissions for s3 user on self-hosted archival configuration
I struggled to find any information about it. And managed to find it only in the source code.
I did not want to grant any unnecessary permissions to user that will only archive workflows.
I did not test these changes. Because, I changed only README file.
However, things that I wrote in documentation helped me to configure archival
-
-
No

docs(archival): Adds permissions for s3 archival

---

common/config/config.go
common/config/persistence.go
temporal/fx.go

Add back support for `advancedVisibilityStore` config key (partial revert of https://github.com/temporalio/temporal/pull/5307)

Revert advanced visibility store config

---

common/metrics/metric_defs.go
common/metrics/tags.go
service/matching/matching_engine.go
service/matching/matching_engine_test.go
service/matching/physical_task_queue_manager.go
service/matching/task_queue_partition_manager.go

Currently, `LoadedTaskQueueGauge` is a metric which counts the number of DB-level task queues (the total number of physicalTaskQueueManagers being created). Thus, there is not much visibility on the total number of other created instances, such as the total number of `taskQueuePartitionManagers`, the total number of `root` partitions and the total number of 'Workflow' based task queues. This PR aims to add these metrics for increased visibility.
These changes are being made for increased visibility which would help us understand the scale of our fleet better.
- Tested it locally by ensuring no tests have broken.
- Github CI/CD
No

Separating LoadedTaskQueueGauge into separate metrics for increased visibility

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/tests/vars.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/task_generator.go
tests/functional.go

> 	// EnableMutableStateTransitionHistory controls whether to record state transition history in mutable state records.
// The feature is used in the hierarchical state machine framework and is considered unstable as the structure may
// change with the pending replication design.

Add history.enableMutableStateTransitionHistory feature flag

---

common/persistence/visibility/store/elasticsearch/query_interceptors.go
common/persistence/visibility/store/elasticsearch/query_interceptors_test.go
common/persistence/visibility/store/query/util.go
common/persistence/visibility/store/query/util_test.go
common/persistence/visibility/store/sql/query_converter.go
common/persistence/visibility/store/sql/query_converter_test.go

Fix parse ExecutionDuration value as quoted integer.
It used to work when querying `ExecutionDuration='123'`.
Added tests.

Fix parse ExecutionDuration value as quoted integer

---

service/history/workflow_task_handler.go

Fail workflow task instead of run when command uses compatible version.
Failing the run is too harsh, this should've always failed just the task.
Relying on existing test coverage.

Fail workflow task instead of run when command uses compatible version

---

service/matching/matching_engine.go
tests/versioning.go

Require conflict token to always be correct, instead of accepting a nil conflict token as an "override"
Change the tests to reflect this
For better user experience
Changed existing functional tests to test new behavior
None
Update API Comments: https://github.com/temporalio/api/pull/375
No

Require conflict token for all versioning rule updates

---

common/dynamicconfig/constants.go
service/frontend/configs/quotas.go
service/frontend/fx.go
service/frontend/fx_test.go
service/frontend/service.go
tests/dynamicconfig.go
tests/versioning.go
tests/xdc/user_data_replication_test.go

Removing `frontend.namespaceBurst` and adding `frontend.namespaceBurstRatio` config.
Similarly replacing `frontend.namespaceBurst.visibility` and `frontend.namespaceBurst.namespaceReplicationInducingAPIs` with `frontend.namespaceBurstRatio.visibility` and `frontend.namespaceBurstRatio.namespaceReplicationInducingAPIs`.
With current configuration it is not possible to set a good default value for namespaceBurst.
If we don't want to allow burst, namespaceBurst should be equal to namespaceRPS. If the burst value is less than RPS, the effective RPS will be the value of burst.
This creates a problem when we need to change namespaceRPS for individual namespaces.  namespaceBurst should also be adjusted along with namespaceRPS.
Replacing namespaceBurst with namespaceBurstRatio will fix this …

Removing frontend.namespaceBurst and adding frontend.namespaceBurstRatio

---

common/nexus/routes.go
common/persistence/cassandra/execution_store.go
common/routing/route.go
common/routing/route_test.go
service/history/hsm/tree_test.go
service/matching/matching_engine_test.go

I accidentally renamed some comments when doing a refactor in https://github.com/temporalio/temporal/pull/5539/files. This PR reverts those changes. However, in doing this revert, I found some unnecessary comments in matching_test which I removed.

Fix comments broken by bad refactor

---

common/nexus/outgoing_service_registry.go

There was a small issue in #5523 where we check an "issue set" against nil in the outgoing service registry code. The issue set is supposed to track a list of request issues to form one big invalid argument error if its length is greater than zero. However, we had code that looked like this:
```go
if issues := getIssuesFromCommonRequest(req); issues != nil {
return nil, issues.GetError()
}
```
Which works because we return a nil issues set if there's no issues, but, technically, we could have a non-nil issues set with no issues, so it should instead be something like this:
```go
if err := getIssuesFromCommonRequest(req).GetError(); err != nil {
return nil, err
}
```

Don't compare an issueSet with nil

---

common/dynamicconfig/constants.go
common/persistence/visibility/visibility_manager_impl.go
common/searchattribute/defs.go
common/searchattribute/validator.go
common/searchattribute/validator_test.go
service/frontend/service.go
service/frontend/workflow_handler.go
service/history/command_checker_test.go
service/history/configs/config.go
service/history/history_engine.go
service/history/history_engine2_test.go
service/history/workflow_task_handler_callbacks_test.go

Dynamic config to suppress error when setting system search attributes
Create a way to prevent errors when new system search attributes are added, but there is already a custom search attribute registered with the same name.

Dynamic config to suppress error when setting system search attributes

---

common/dynamicconfig/constants.go
service/history/archival_queue_factory.go
service/history/configs/config.go
service/history/outbound_queue_factory.go
service/history/queues/executable.go
service/history/queues/executable_factory.go
service/history/queues/executable_test.go
service/history/queues/queue_base_test.go
service/history/queues/queue_scheduled_test.go
service/history/timer_queue_factory.go
service/history/transfer_queue_factory.go
service/history/visibility_queue_factory.go

Adding a new config history.DLQErrorSubStrings to specify substrings in task processing error strings.
If the error contains this substring, this task will be enqueued to DLQ.
Gives the ability to send tasks to DLQ based on errors.
Unit tests
None
None
No

Config to specify error substrings to DLQ task processing errors

---

service/matching/task_queue_partition_manager.go
service/matching/task_queue_partition_manager_test.go
tests/versioning.go

Fix unit test compilation issue, make commitBuildId test match new required conflict token, and add comment describing `PollTask` behavior

Fix CommitBuildId test and poller unit test

---

docs/admin/dlq.md

Adding history.TaskDLQUnexpectedErrorAttempts to DLQ documentation.
This feature will be released in 1.23.
None
No

Adding history.TaskDLQUnexpectedErrorAttempts in dlq doc

---

common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go
common/persistence/nosql/nosqlplugin/cassandra/gocql/session_test.go

Catch gocql panic
Gocql would panic when try to connect to 0.0.0.0
No
No

Catch panic during gocel session creation

---

tests/reset_workflow.go

Rewrite ResetWorkflow functional test.
This is the first of a sequence of PRs implementing reapply for update. The next PR is https://github.com/temporalio/temporal/pull/5573 (draft).
- Easier to understand
- Stronger assertions (explicit history assertions using `EqualHistory()`
- In a future PR I am extending this to test reapply of Updates; opening this PR first will make the Update changes easier to understand.
(Note for reviewers: the diff will be easier to understand in side-by-side mode)

update-reapply 1: Rewrite reset reapply-signals functional test

---

common/rpc/interceptor/telemetry.go
common/rpc/interceptor/telemetry_test.go

Adjust the Action metric for Start Workflow. This metric is used by OSS users to estimate their Cloud bill.
After https://github.com/temporalio/api/pull/359 was merged, a successful gRPC response from Start Workflow doesn't always result in an Action.
Added tests.
Low. It's only an internal metric.

Track Start Workflow actions correctly

---

temporal/fx.go

We forgot to use the next page token when loading all clusters in the cluster metadata loader during startup. This probably doesn't matter because most people don't have more than 100 clusters, but it looks like this code would trigger an infinite loop if that were the case.
You can see the infinite loop in action if you set the page size to 1 for the xdc cluster setup by running `make install-schema-xdc && make start-xdc-cluster-a` because it has 3 clusters, which means 2 remote clusters, so a page size of 1 will not get all clusters, causing the paginating iterator to call the func again. <img width="945" alt="image" src="https://github.com/temporalio/temporal/assets/5942963/11bb683c-588c-476f-9163-46405452755f">
If I actually use the paginationToken, you can see that the issue goes …

Use pagination token in loadClusterInformationFromStore

---

common/nexus/payload_serializer.go
common/persistence/serialization/serializer.go
common/persistence/tests/execution_mutable_state_task.go
common/persistence/visibility/visibility_manager_impl.go
plugins/callbacks/statemachine.go
service/history/ndc/mutable_state_initializer.go

Adding code to return DeserializationError when proto unmarshalling fails.
If task processing see DeserializationError, it can DLQ the task. These errors cannot be handled with retries.
This can happen if there are any invalid UTF8 characters in any proto strings.
Unit tests
None
No

Returning SerializationError when proto unmarshalling fails

---

go.mod
go.sum

Just a quick update of our `api` dep to get the new Cluster HTTP address. We need this for HTTP request forwarding. You can see that the diff in the `proto/api` submodule is small.

Update api-go to get Cluster HTTP address

---

temporal/fx.go

The `loadClusterInformationFromStore` function was written before we had generics, so it does some type-casting, and it also allocates a new slice to copy the `[]*persistence.GetClusterMetadataResponse` into a `[]interface{}`. We can now make this generic to be more readable and efficient.

Use generics in loadClusterInformationFromStore

---

Makefile

Fixed an issue where `make proto` fails due to untracked dependencies, leading to the deletion of generated code necessary for `go mod tidy`.
When `make proto` is executed, it invokes the `service-clients` target, which runs `go generate ./client/...`. This operation requires compiling code in the `.cmd/tools/rpcwrappers` package. If there is a missing dependency in `go.sum`, likely due to a recent dependency upgrade via `go get go.temporal.io/api@…`, the compilation and client generation fail. This failure occurs after the `clean-proto` target has already deleted the existing clients. Consequently, `go mod tidy` also fails because it cannot resolve dependencies on the now-missing `service-clients` output, such as `go.temporal.io/server/api/adminservicemock/v1`. 
A workaround is to …

Run go mod tidy in clean-proto

---

service/matching/version_rule_helpers.go
service/matching/version_rule_test.go

Check that ramp is set instead of not checking.
Rename function for better clarity, and add comment explaining reason.
Add test to catch this issue.
Because the broken check was causing valid redirect rule inserts to fail.
Added a unit test. Made sure it failed with the old code and succeeded with the new code.
None
Commented
No

Fix check that redirect rule source is not the target of a ramped assignment rule

---

common/nexus/routes.go
common/nexus/routes_test.go
service/frontend/configs/quotas.go
service/frontend/configs/quotas_test.go
service/frontend/nexus_http_handler.go
tests/nexus_api_test.go
tests/nexus_incoming_service_test.go

Changed Nexus HTTP routes from:
`/api/v1/namespaces/{namespace}/task-queues/{task_queue}/dispatch-nexus-task`
and
`/api/v1/services/{service}`
to:
`/api/v1/namespaces/{namespace}/task-queues/{task_queue}/nexus-operations`
and
`/api/v1/nexus/services/{service}/operations`
- Use resource centric URLs for consistency with the rest of the HTTP API.
- The `nexus` prefix is an important annotation in the service API.
This is all experimental and never released, safe to change still.

Change Nexus request routes

---

common/persistence/data_interfaces.go
common/persistence/execution_manager.go
common/persistence/persistence_interface.go
common/persistence/tests/execution_mutable_state_task.go
service/history/api/addtasks/api.go
service/history/api/addtasks/api_test.go
service/history/api/refreshworkflow/api.go
service/history/api/replication/generate_task.go
service/history/archival_queue_task_executor.go
service/history/archival_queue_task_executor_test.go
service/history/deletemanager/delete_manager.go
service/history/shard/context_impl.go
service/history/shard/context_test.go

- Remove runID from persistence addTasks request
- Not used. NamespaceID and workflowID could be used by some persistence implementation.
- A task may target a workflowID (a workflow chain) instead of an specific run of the workflow
- N/A, the field is not used.
- N/A
- No.

Remove runID from persistence addTasks request

---

service/history/configs/config.go
service/history/tests/vars.go

- Disable shard ownership assertion by default
- Shard ownership assertion is a no-op for OSS. The change is mainly for an internal rollout plan.

Disable shard ownership assertion by default

---

.github/workflows/run-tests.yml

Fix GHA tests results jobs to fail when tests are cancelled or skipped
When a indirect dependency fails, and tests are cancelled or skipped, the test result should fail, not pass.
Cancelled the `misc-checks` and checked the final result was a failure: https://github.com/temporalio/temporal/actions/runs/8511400629

Fix GHA tests job result to fail when individual tests are cancelled or skipped

---

common/dynamicconfig/constants.go
common/nexus/incoming_service_registry.go
common/nexus/incoming_service_registry_test.go

Added `nexus.IncomingServiceRegistry`
The registry is a wrapper for a cache of `serviceID->service` mappings. The cache is lazily loaded on first read and then kept up to date by a background thread that long polls on the matching service `ListNexusIncomingServices` API. On initial load only, if matching is unavailable, it falls back to reading directly from persistence.
This will be used to resolve `serviceID -> namespace + task queue` to support dispatching Nexus tasks by service ID.
New unit tests

Add Nexus incoming service registry

---

go.mod
go.sum
service/matching/matching_engine.go
tests/versioning.go

Return rules list in UpdateWorkerVersioningRules as in GetWorkerVersioningRules
To make the responses consistent for a better SDK experience
Updated functional tests.
None
Corresponding change in api has already landed
No

Return rules list in UpdateWorkerVersioningRules as in GetWorkerVersioningRules

---

common/persistence/tests/cassandra_test.go
common/persistence/tests/execution_mutable_state.go
common/persistence/tests/mysql_test.go
common/persistence/tests/postgresql_test.go
common/persistence/tests/sqlite_test.go
common/persistence/tests/util.go

Tests have been using bogus branch token bytes as oppose to properly initialized ones.

Replace bogus test branch tokens with properly initialized ones

---

common/log/tag/tags.go
common/persistence/history_manager.go

Possible data loss is now logged similarly in both the frontend and history pod
When investigating data loss alerts the frontend and history pod logged entirely different messages, making it difficult for the on-call engineer to find the information necessary to know whether the issue is transient or not.
In both recent cases they were transient read failures, but it took time to discover that because you needed to know about the persistence logs to diagnose it.
Now both will use the same terminology and casing, so a simple search for either "data loss" or the actual message will find both logs.
N/A
None
None
No

Ensure our logs for potential data loss can be easily found

---

common/dynamicconfig/constants.go
service/history/api/consistency_checker.go
service/history/configs/config.go
service/history/tests/vars.go
tests/onebox.go

- Deprecate EnableAPIGetCurrentRunIDLock flag and always perform the locking.
- Flag already enabled in prod for a long time and believe to be safe to always enable the locking logic.
- N/A
- N/A
- No changed required for OSS user.
- No.

Deprecate GetCurrentRunIDLock flag

---

service/history/workflow/fx.go
temporal/fx.go
tests/onebox.go

To allow extending the task generator.

Move NewTaskGeneratorProvider back to HistoryServiceProvider

---

service/frontend/workflow_handler.go
service/frontend/workflow_handler_test.go

Java SDK (and probably others) don't set the task queue kind when starting workflows. It makes no sense to, so that's eminently reasonable.
In fact, this warning is literally _only_ applicable to polls (maybe also list partitions? if so I can add it there too), but is blindly applied everywhere. 
This should reduce pointless logspam significantly.
Existing tests

Remove uninteresting and noisy warning about task queue kinds

---

common/log/tag/tags.go
common/log/tag/values.go
common/quotas/calculator/calculator.go
common/quotas/calculator/cluster_aware_quota_calculator.go
common/quotas/calculator/cluster_aware_quota_calculator_test.go
common/quotas/calculator/logged_calculator.go
common/quotas/calculator/logged_calculator_test.go
common/rpc/interceptor/concurrent_request_limit.go
common/rpc/interceptor/concurrent_request_limit_test.go
service/frontend/fx.go
service/frontend/fx_test.go
service/fx.go
service/history/fx.go
service/history/queue_factory_base.go
service/history/queue_factory_base_test.go
service/history/shard/ownership_based_quota_calculator.go
service/matching/fx.go
service/worker/fx.go

- Log computed per pod rate limiting value. Logs are only emitted when the values changes.
- Improve observability into the rate limiting value that's actually in use. 
- We previously set per pod value directly, but with global rate limit configs, the per pod value is calculated based on things like pod count, shard ownership etc. which means we don't know that the actual value that's applied. This PR logs those computed value to make validation and investigation a bit easier.
- Add unit test
- N/A. GetQuota() may be slower due to the additional value comparison, but that function is only evaluated once per minute
- N/A
- N/A

Logged Quota Calculator

---

common/persistence/client/bean.go

Check for optionally enabled nexus

---

common/dynamicconfig/constants.go
common/nexus/incoming_service_registry.go
common/nexus/incoming_service_registry_test.go
common/nexus/outgoing_service_registry.go
common/persistence/tests/cassandra_test.go
service/matching/matching_engine.go
service/matching/nexus_incoming_service_client.go

* Switched a few instances of `strings.Compare()` to `bytes.Compare()` because the strings utility is intentionally implemented in an inefficient way
* Renamed `matching.incomingNexusServiceManager` to `matching.nexusIncomingServiceClient` for symmetry with the naming of `frontend.nexusIncomingServiceClient` and to avoid confusion with the persistence-layer manager
* Added a test to make sure cassandra does not error when a service is deleted in the middle of paging
* Updated `nexus.incomingServiceRegistry` to respect the `frontend.enableNexusAPIs` dynamic config flag. Service data will only be initialized when this flag is true.
To improve Nexus service registry functionality and maintainability
Existing tests

Nexus service registry followups

---

service/frontend/errors.go
service/frontend/workflow_handler.go
service/history/api/pollupdate/api.go
service/history/api/pollupdate/api_test.go
service/history/workflow/update/registry_test.go
service/history/workflow/update/status.go
service/history/workflow/update/update.go
service/history/workflow/update/update_test.go
service/history/workflow_task_handler_callbacks_update_test.go
tests/update_workflow.go

Previously, if update didn't reach requested stage within internal server timeout `UNSPECIFIED` was returned. Now actual reached stage `ADMITTED` or `ACCEPTED` is returned.
Based on actual reached state caller can make a decision to retry `UpdateWorkflowExecution` API or start polling update result.
Add new unit tests.
No risks.
No.
No.

Workflow Update: return reached stage if requested stage is not reached

---

common/dynamicconfig/constants.go
common/persistence/client/fx.go
common/persistence/client/health_request_rate_limiter.go
common/persistence/client/persistence_rate_limited_clients_test.go
common/persistence/client/quotas.go
common/persistence/client/quotas_test.go
common/quotas/dynamic.go
common/quotas/dynamic_rate_limiter_impl.go
service/frontend/fx.go
service/frontend/service.go
service/fx.go
service/history/configs/config.go
service/history/fx.go
service/matching/config.go
service/matching/fx.go
service/worker/fx.go
service/worker/service.go

-  Allow configuring persistence rate limiter burst ratio, default is still 1, same as today.
- It's hard to set rate limit value without burst support. We allow incoming traffic to burst, but call to persistence can't burst, which often lead to persistence rate limited errors. 
- N/A, default burst is still 1, no behavior change by default.
- N/A
- No

Persistence Burst Ratio Config

---

common/enums/defaults.go

Revert change to default enum value made in #5360
We cannot deploy a change that both introduces a new value and starts using it as the default, since during rollout it may cause a frontend client on the new version to send a value that is unknown to a history node on the old version.
I didn't
No risk
This change should be cherry-picked onto current release candidates.

Revert change to default reapply type

---

.golangci.yml

Exhaustive will ensure that switches on enums are exhaustive
Godox is configured to fail when code contains FIXMEs. TODOs are allowed, but FIXMEs must be fixed prior to merge.
We have lots of enums and missing a case for a newly added variant (or missing cases in new switches) is a common source of bugs. If we want `default` clauses to satisfy this linter then we can specify `default-signifies-exhaustive: true` in its config.
As for godox: I know that I personally use FIXMEs as a reminder for things to do before merge, and I prefer it when tools yell at me for not doing so before I merge.
I ran `make lint` locally and ensured that nothing failed.
None
No
No

Enable the exhaustive and godox linters

---

common/config/config.go
common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go
common/persistence/nosql/nosqlplugin/cassandra/gocql/client_test.go
tools/cassandra/cqlclient.go

Exposes all gocql timeouts independently
When database hosts cycle or become unavailable, we hypothesize that shorter timeouts will speed up recovery
Unit test updates
Allows for more possible misconfigurations. However, current usage will remain unchanged.
Added doc comments, but if there's anything else to update, let me know
No

Support configuring gocql timeout and writetimeout

---

common/testing/historyrequire/history_require.go
tests/xdc/history_replication_dlq_test.go
tests/xdc/history_replication_signals_and_updates_test.go
tests/xdc/test_data.go

This is the 3rd PR in the update-reapply sequence.
**previous PR in sequence:** https://github.com/temporalio/temporal/pull/5573
**next PR in sequence:** https://github.com/temporalio/temporal/pull/5595
We did not have functional test coverage for split-brain scenarios causing conflict during history replication, so this PR adds that. It uses the injection techniques from `tests/xdc/history_replication_dlq_test.go` to control namespace and history replication task processing.
See https://github.com/dandavison/temporal/tree/main/conflict-resolution for shell functions reproducing similar scenarios using the CLIs.
Thanks @MichaelSnowden and @yycptt for advice and discussions regarding this PR.

update-reapply 3: Functional tests for split-brain replication scenarios and conflict resolution

---

service/matching/db.go
service/matching/matching_engine_test.go
service/matching/task_reader.go
service/matching/task_writer.go

This PR moves `max_read_level` inside of db so that `db` becomes the single source of truth for this variable. 
While working on #5593, we realized there were concurrency issues, such as deadlock, which were spinning up when `db` tried to read `max_read_level` for resetting the `approximateBacklogCounter`. Thus, moving `max_read_level` inside of db will solve that issue and shall also serve towards the purpose of making `db` the single source of truth for most shared resources in the near future.
Current unit tests.
None
No

Moved max_read_level inside of db

---

.gitignore
Makefile

All tooling is now installed to and used from a local binary directory. After these changes you'll never need to run `make install` or `make update-BLAH` to keep our tools up to date; Make will do that for you.
Keeping tool versions in sync across repos is a nightmare when each repo installs its tooling globally. To fix that we're going to install all our tools into a local bin directory and use those versions for everything.
This is set up using two directories: a local binary directory (.bin) and a stamp directory for state-tracking. The stamp directory is used for protoc plugins that need to be named a certain way; the stampfile is how we know if we've installed the right version.
I ran through our common makefile uses locally
None that I'm aware of
No
No

Improve tooling management

---

.github/workflows/trigger-publish.yml

I added cloud/* branches to the list of branches we sync to temporalio/docker-builds.
We want these to be auto-built and kept in sync for testing

Add cloud/* branches to trigger-publish

---

service/worker/scheduler/workflow.go
service/worker/scheduler/workflow_test.go

Activate schedule workflow logic changes. Some of this code is not in 1.23.0, but we can patch those PRs into 1.23.1 to support downgrades to the 1.23 series.
Fix bugs, support new features, make more efficient.
existing tests (on those PRs)
schedule workflow determinism errors

Activate schedule workflow changes in #5179, #5277, #5344, and #5381

---

service/history/api/signalwithstartworkflow/api.go
service/history/api/startworkflow/api.go

Set default for `WorkflowIdConflictPolicy` in History as well.
An issue can happen on downgrade where the Frontend is running a previous version that doesn't set the default but the newer History expects it.
Tested locally by commenting out the code in Frontend and History; ensuring it fails and then re-enabling the code in History to verify it fixes it.
None; if there is a policy already, nothing happens.

WorkflowIdConflictPolicy default on History

---

common/dynamicconfig/constants.go
service/matching/config.go
service/matching/matching_engine.go
service/matching/reachability.go
service/matching/reachability_test.go
service/matching/version_rule_helpers.go
service/matching/version_rule_test.go
tests/versioning.go

Add and enforce dynamic config chain limit for redirect rules
To limit scope of visibility queries and ensure that task matching using redirect rules can complete quickly.
Unit tests
None
Good error message is included
No

Add and enforce dynamic config chain limit for redirect rules

---

common/dynamicconfig/constants.go
service/frontend/workflow_handler.go
tests/versioning.go

Enforce dc.ReachabilityQueryBuildIdLimit for DescribeTaskQueue with ReportTaskReachability==true.
This is enforced in the frontend, because we have the information to enforce it there, so if we do it there we can return an error quickly without putting additional load on matching.
Optionally we could _also_ enforce it at the matching engine level to prevent attacks from any callers that use the API without going through the frontend, but I believe that that isn't necessary, since the main protection for overloading visibility will come from the rate limit not the build id limit. The length of the list of "active versions" could well exceed this limit, so we can't rely on this limit to strictly guarantee a short visibility query anyways, it just limits a portion of the queries from being …

Enforce dc.ReachabilityQueryBuildIdLimit for DescribeTaskQueue with ReportTaskReachability==true

---

service/matching/version_rule_helpers.go
service/matching/version_rule_test.go

- Define named version rule errors
- Add unit tests for errors that were previously untested
So that the error messages can be standardized when they are used repeatedly, and so that it is easier to tell whether all errors are covered by the unit tests
Unit tests

Define versioning rule errors and improve unit test coverage

---

service/matching/version_rule_helpers.go
service/matching/version_rule_test.go

- Define named version rule errors
- Add unit tests for errors that were previously untested
So that the error messages can be standardized when they are used repeatedly, and so that it is easier to tell whether all errors are covered by the unit tests
Unit tests

redo #5707: define versioning rule errors and improve unit test coverage

---

common/persistence/visibility/store/elasticsearch/converter.go
common/persistence/visibility/store/elasticsearch/converter_test.go
common/persistence/visibility/store/elasticsearch/visibility_store.go
service/frontend/workflow_handler.go
service/worker/scheduler/query.go
service/worker/scheduler/query_test.go
tests/schedule.go

Validate ListSchedulesRequest query field. It's only allowed to filter on custom search attributes and `TemporalSchedulePaused`.
Schedules is implemented as workflow at this moment, but we don't want to expose all the system search attributes available since the implmenetion might change, and those system search attributes might not exist anymore for the schedule.
No.

Validate ListSchedulesRequest query field

---

service/history/workflow_task_handler.go

Use correct deprecated metrics for per-command metrics.
This was broken in #5435, the deprecated metrics were collapsed to the new CommandCounter metric, but that double-counts them and makes labels inconsistent.
existing tests

Fix metrics in workflow task handler

---

service/history/ndc/events_reapplier.go
service/history/ndc/events_reapplier_test.go
service/history/ndc/workflow_resetter.go
service/history/ndc/workflow_resetter_test.go

Unify two very similar implementations of event-reapply: one used when resetting, and the other used during history event replication conflict resolution.
The duplication risked introducing bugs and made the codebase harder to understand and maintain.
Existing tests (including those being added in https://github.com/temporalio/temporal/pull/5595)
History replication / conflict resolution and WorkflowReset
No

Unify event-reapply implementations

---

docs/admin/dlq.md
tools/tdbg/util.go

I fixed a bug I introduced into the `dlq list` command for v2 DLQs and corrected a typo in our DLQ docs
Listing v2 DLQs panics since my protobuf changes, which means we don't have any automated tests for that functionality.
I tested it against a cluster with DLQs
None
Yes
No?

dlqv2: fix listing queues and correct docs

---

service/history/workflow/context.go

Use `c.MutableState` every time when possible (when it is not `nil`), and use passed `ms` only when `c.MutableState` is `nil`, which is the case only for `UpdateWithStart` scenario.
To prevent using of stale mutable state passed in `ms` parameter while creating update registry.
Existing tests and fault injection tests.
No risks.
No.
No.

Fix stale mutable state being captured in update registry

---

common/util.go
common/util_test.go

- Do not retry namespace level resource exhausted error in service clients
- Backoff & retry will increase API latency and trigger alerts.
- Namespace level resource exhausted error even if returned won't count against SLA.
- Unit test
- Yes.

Do not retry namespace level resource exhausted error in service clients

---

common/persistence/visibility/store/elasticsearch/client/client_v7.go

Set `track_total_hits = false` for all ES queries.
We don't care about the total number of hits, and it makes queries faster.

Disable ES track_total_hits

---

common/persistence/data_interfaces.go
common/persistence/data_interfaces_mock.go
common/persistence/nexus_incoming_service_manager.go
common/persistence/persistence_metric_clients.go
common/persistence/persistence_rate_limited_clients.go
common/persistence/persistence_retryable_clients.go

We thought we'd use this in the operator service but ended up with a simpler solution.

Remove unused GetNexusIncomingServicesTableVersion persistence method

---

service/worker/deletenamespace/reclaimresources/activities.go
service/worker/deletenamespace/reclaimresources/activities_test.go
service/worker/deletenamespace/reclaimresources/workflow_test.go

Followup to #5343, which didn't account for the situation where a namespace has no workflows in the default namespace division, but has some in another namespace division: The reclaim resources workflow first does a Count of workflows before it does List and deletes what it finds. The List was updated to search all divisions, but the initial Count was not.
Correctly delete namespaces in all cases
updated unit test, searched for all visibility manager calls and ensure they have a Query

Fix deleting namespaces with only workflows in other division

---

.github/workflows/create-tag.yml

I updated our release creation workflow to only add a `v` prefix to the tag name if it doesn't already have one
So we stop accidentally creating tags like `vv1.23.X`
I manually ran the code
None
No
No

Only add the `v` prefix if not already present

---

service/history/workflow/context.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/update/registry.go
service/history/workflow/update/state.go
service/history/workflow/update/update.go
tests/xdc/history_replication_signals_and_updates_test.go

This PR adds functional test coverage for various scenarios involving updates and history event replication:
**`TestConflictResolutionReappliesUpdates`**: this test passes without requiring further changes (the necessary work was done in the previous PRs addressing WorkflowReset and reapplying updates).
**`TestAcceptedUpdateCanBeCompletedAfterFailoverAndFailback`**, **`TestUpdateCompletedAfterFailoverCannotBeCompletedAgainAfterFailback`**: to make these tests pass, this PR modifies update registry mechanics: we now update the registry from mutable state every time we obtain the registry from the workflow context. This is needed because, when we failback to cluster 1 after a failover, cluster 1 already has a populated registry, which must be brought up to date with events in history …

update-reapply 4: Functional tests of scenarios involving updates and history replication

---

service/history/api/multioperation/api.go
tests/workflow.go

Adds support to MultiOperation to _not start_ a Workflow when it's running already and instead just _update_ it.
_Note that the error handling is still incomplete and will be addressed in a follow-up PR_
MultiOperation needs to update the workflow regardless of whether the workflow is running or not.
Added a new functional test.
Feature is still in development phase, ie behind feature flag.

MultiOperation update-only

---

service/history/workflow/mutable_state_impl.go

Set proper `ScheduleToStart` timeout in matching for speculative WFT.
Speculative WFT has `ScheduleToStart` timeout even on nornal task queue. This timeout is enforces in history service but wasn't used when WFT is added to matching.
No risks.
No.
No.

Set proper ScheduleToStart timeout in matching for speculative WFT

---

common/dynamicconfig/constants.go
service/frontend/service.go
service/frontend/workflow_handler.go
tests/callbacks_test.go

Enforce max number of callbacks that can be attached to a workflow
Prevent too many callbacks from making the mutable state size explode.

Enforce max number of callbacks per workflow

---

.github/workflows/features-integration.yml

Remove misleading version numbers from features CI integration.
These are not actually used when `docker-image-artifact-name` is set, which it always is in this workflow (if it wasn't, it wouldn't be testing with the server built from the PR, it would use the latest released cli dev server).
They're misleading.
CI

Remove misleading version numbers from features CI integration

---

service/worker/scheduler/workflow.go
service/worker/scheduler/workflow_test.go

If a schedule was paused and received a large number of signals (trigger, backfill, etc.), it wouldn't be able to continue-as-new and history size could grow past the suggested limit.
For various reasons the main loop receives and processes signals across iterations, with checking for CAN in between, so a wakeup due to a signal (instead of a timer) would prevent CAN. Refactoring is hard due to the determinism requirement, so the simplest fix is to do a second check.
New unit test

Fix schedule workflow to CAN after signals

---

common/testing/testvars/test_vars.go
service/history/workflow_task_handler.go
service/history/workflow_task_handler_callbacks.go
tests/client_suite.go

Make admitted updates prevent workflow completion, similar to how "buffered" signal events prevent workflow completion.
Product design decision: it should be possible to design workflows which continue-as-new without the risk of losing admitted updates. Also, makes behavior consistent with signal.
End-to-end test in PR using Go SDK.
Could break workflows using update.
No

Make admitted updates prevent workflow completion

---

common/persistence/tests/execution_mutable_state.go
common/persistence/tests/util.go

Execution mutable state tests only exercise the portion of logic related
to mutable state during CreateWorkflowExecution. Even though the tests
are meant to focus on mutable state, history event logic is integral
within the CreateWorkflowExecution implementation and therefore should
be exercised.
At the minimum, the execution stats pertaining to the associated history
events are no longer being dummy tested with always incrementing by 0.

Fill in companion history events for mutable state tests

---

service/frontend/service.go
service/frontend/workflow_handler_deprecated_test.go
service/history/configs/config.go
service/matching/config.go

This enables frontend+matching reading history through history service
This is the prereq for https://github.com/temporalio/temporal/pull/5797

Enable FE>history for reading history

---

README.md

Make link to CONTRIBUTING.md in the README slightly more explicit.
People outside server team sometimes need to run the server against `main` and it's not obvious how to.

Make link to CONTRIBUTING.md slightly more explicit

---

service/history/handler.go

Setting the vector clock on any `StartWorkflowExecutionResponse` inside the MultiOperation response.
(NOTE: there can only ever be one Start Workflow)
Vector clock needs to be set.
To be honest, I'm not sure how to.

MultiOperation: set vector clock

---

common/rpc/interceptor/telemetry.go
common/rpc/interceptor/telemetry_test.go

The `action` metric gives OSS users an estimate for the expected cost when moving to Cloud.
The metric is now tracking Update Workflow actions when receiving an accepted/rejected protocol message from the Worker - instead of the RPC request from the client.
_Additional context: When a Worker accepts or rejects an Update request, it sends back an Acceptance, Rejection or Outcome message._
Reflects upcoming Cloud bill change.
Added test cases.

UpdateWorkflow action metric on accept/reject

---

.github/workflows/run-tests.yml

Temporary disable xdc functional tests over SQL persistances.
xdc tests over SQL are constantly fails due to different connection errors such as
```
2024-04-30T16:51:34.847Z	error	Failed to get replication tasks	{"cluster-name": "active-adv-vis", "service": "worker", "component": "replicator", "component": "replication-task-processor", "xdc-source-cluster": "standby-adv-vis", "error": "last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:10134: connect: connection refused\"", "logging-call-at": "namespace_replication_message_processor.go:169"}
```
These errors need to be investigated and tests should be enabled back.
Cassandra is also flaky but not that bad.
GHA.
Replication over SQL is not tested in GHA.
No.
No.

Temporary disable xdc functional tests over SQL persistances

---

service/history/workflow/update/registry.go

Advance to more advanced state only from non-provisional state.
Without this check any access to `UpdateRegistry()` updates it from possible non yet persisted MS and advances updates to the states which are not persisted yet.
Manually. Didn't add new test because I am about to remove `UpdateFromStore()` soon.
No risks.
No.
No.

Workflow Update: advance to more advanced state only from non-provisional state

---

service/history/configs/config.go
service/history/queues/executable.go

- Add UnexpectedErrorAttempts tag to some logs.
- Reduce default value for history.TaskDLQUnexpectedErrorAttempts to 70
More consistent logs. Also 100 attempts take +2hrs which is to long. 50 attempts take about 16 minutes.
None
none
none
no

Improve DLQ Logs

---

service/matching/matching_engine.go

Fix panic when the partition being unloaded is not found in the map.

Add missing null check when unloading partition manager

---

service/history/workflow/context.go
service/history/workflow/update/registry.go
service/history/workflow/update/registry_test.go
service/history/workflow_task_handler_test.go

Clear update registry when mutable state failover version changes.
Update registry must stay in sync with mutable state. If mutable state was changed because of fail over, update registry must be updated. The easiest way to do it, is clear registry and rebuild from new version of mutable state.
No risks.
No.
No.

Clear update registry when mutable state failover version changes

---

service/history/workflow/context.go
service/history/workflow/update/registry.go
service/history/workflow/update/registry_test.go
service/history/workflow_task_handler_test.go

Replace `getStoreFn()` with `store`.
After #5792 there is no need for call back function because update registry is always using up to date WF context.
Existing tests and nightly pipelines.
No risks.
No.
No.

Workflow Update: replace getStoreFn() with store

---

common/nexus/incoming_service_registry.go
tests/client_suite.go
tests/nexus_api_test.go

Switch to using `EventuallyWithT` instead of `time.Sleep` to make sure that Nexus incoming services are loaded into memory before executing tests.
Flakey :(

Fix flakey Nexus functional tests

---

.golangci.yml

I updated our linter rules to forbid the usage of time.Sleep in new tests.
Note that our linters can be ignored but _please don't_ :(
This has been a source of race conditions and flaky tests historically. If you've a good reason to use `time.Sleep` in your test (we have some) then you can override and/or ignore this, but you should otherwise default to using `require.Eventually` or `assert.Eventually`.
I applied the following diff:
```diff
diff --git a/service/fx.go b/service/fx.go
index 3b024069c..52cf3e4bf 100644
--- a/service/fx.go
+++ b/service/fx.go
@@ -26,6 +26,7 @@ package service
import (
"sync/atomic"
+	"time"
"go.uber.org/fx"
"google.golang.org/grpc"
@@ -168,6 +169,8 @@ func getUnaryInterceptors(params GrpcServerOptionsParams) []grpc.UnaryServerInte
interceptors = …
```

Add linter rule to grumble when time.Sleep is used in tests

---

tests/client_suite.go

Clean up a test, similar to https://github.com/temporalio/temporal/pull/5794. No functional changes.

Clean up buffered signal test

---

service/history/workflow/mutable_state_impl.go
service/history/workflow/update/registry.go
service/history/workflow/update/update.go
tests/update_workflow.go

Sort update requests by order of admission when sending to worker.
The order in which updates are sent to the worker affects execution semantics (consider the initial, synchronous portion of the handler: for this section of code, update B can see changes made to workflow state by update A iff update B is executed after A by the worker).
Furthermore, it is possible for a user to know in which order the server has received the updates (the client can poll for admitted status), and even without polling, if they are re-using the same client they will expect admission order to match send order. Thus, the user may reasonably have expectations for the order of execution by the worker based on happens-before relations among their update requests.
Test in PR
The test in the PR has a non-zero false …

Send update requests to worker in admission order 

---

docs/admin/dlq.md

Adding documentation for the config flag history.TaskDLQErrorPattern in docs/admin/dlq.md.
No

Adding documentation for history.TaskDLQErrorPattern flag

---

service/history/workflow/update/registry.go

Remove mutex from update registry.
All access to registry is done within WF lock and extra lock is not needed. There are accesses to updates outside of WF lock (like `WaitLifecycleState`) but registry lock doesn't protect these calls and they are thread safe.
Run existing tests with race detector enabled and also fault injection pipeline.
No risks.
No.
No.

Workflow Update: remove mutex from update registry

---

service/history/workflow/update/registry.go
service/history/workflow/update/registry_test.go

Return `NotFound` error to the pollers of outcome of accepted updates of completed workflows.
If workflow is completed and update was left in `Accepted` stage it will never go `Completed`, therefore there is no reason to wait for update result.
No risks.
No.
No.

Workflow Update: return NotFound error to the pollers of outcome of accepted updates of completed workflows

---

service/history/api/reapplyevents/api.go
service/history/history_engine_test.go
service/history/ndc/events_reapplier.go
service/history/ndc/events_reapplier_mock.go
service/history/ndc/events_reapplier_test.go
service/history/ndc/transaction_manager.go
service/history/ndc/transaction_manager_test.go
service/history/ndc/workflow_resetter.go
service/history/ndc/workflow_resetter_test.go
service/history/workflow/update/registry.go
tests/xdc/history_replication_signals_and_updates_test.go

Skip reapplying an `UpdateAdmitted` event if an update with that ID already exists.
In a split-brain scenario it is possible for both clusters to accept an update with the same ID. Prior to this PR, conflict resolution would create an `UpdateAdmitted` event via a reapply, despite the fact that the update ID conflicts with the other update. This state would not be correct: the update registry can only hold one of them and it would not be possible to interact with both updates (i.e. the worker will not be able to accept/reject/complete both of them).
- We have a function that takes a slice of events and decides whether to "reapply" them.
- It is called during `WorkflowReset` (might need to reapply a signal/update in the portion of history being lost) and on conflict resolution (might need …

Prevent reapplying an update with a conflicting ID

---

common/dynamicconfig/client.go
common/dynamicconfig/collection.go
common/dynamicconfig/collection_test.go
common/dynamicconfig/config/testConfig.yaml
common/dynamicconfig/file_based_client.go
common/dynamicconfig/file_based_client_test.go

Add destination filter to dynamic config. It also filters by namespace ID instead of namespace name because of how the existing outbound task key is built.
Be able to create specific dynamic configs by destination.

Add destination to dynamic config filter

---

service/history/api/multioperation/api.go
service/history/api/updateworkflow/api.go

Moved the cache write before the persistence write.
The code has a comment to explain it.
I have a test runner that concurrently executes MultiOperations.

MultiOperation: write to cache before persist

---

common/dynamicconfig/constants.go
common/log/tag/tags.go
service/matching/config.go
service/matching/matching_engine.go
service/matching/version_rule_helpers.go
service/matching/version_rule_test.go
tests/versioning.go

Rename RedirectRuleMaxChainLength to RedirectRuleMaxUpstreamBuildIDs
Because it is more clear than "chain"
Existing unit and functional tests
None
See dynamic config comments
No

Rename RedirectRuleMaxChainLength to RedirectRuleMaxUpstreamBuildIDs

---

.github/workflows/run-tests.yml
tests/xdc/advanced_visibility_test.go
tests/xdc/base.go
tests/xdc/failover_test.go

- Wait until test clusters are connected.
- Add worker stop() calls to reduce noisy "connection refused" logs.
If workflows are executed before two test clusters are connected, the existing tasks will not be replicated to standby cluster.
Local test and github checks.

fix flaky xdc test (TestWorkflowReplicationTaskFailure)

---

service/history/queues/dlq_writer.go
service/history/queues/dlq_writer_test.go

Adding task category to dlq_writes metric.
To understand the category of task when it is enqueued to DLQ.
Unit tests.
None
No

Adding task category to dlq_writes metric

---

common/persistence/tests/execution_mutable_state.go

When ConflictResolveWorkflowExecution detects a conflict, the current
logic has the side effect of leaving garbage history data behind. This
change disables asserting against the expected data in the database and
will be addressed later on.

Remove assertion against history data during conflict tests

---

service/history/workflow/update/update.go
service/history/workflow_task_handler.go
tests/update_workflow.go

Remove quotes from error messages.
Error messages with quotes don't look good in UI:
No risks.
No.
No.

Workflow Update: remove quotes from error messages

---

common/persistence/client/fault_injection.go
common/persistence/client/fault_injection_errorgenerator.go
common/persistence/client/targeted_fault_injection.go
config/development-cass-es-fi.yaml

Added new fault injection error `ExecuteAndTimeout`.
While working on this, I also figured out that fault injection code required refactoring and renames. I will do it in separate PR.
`ExecuteAndTimeout` is a special error which emulates case, when client got a `Timeout` error, but operation actually reached persistence and was executed successfully.
Run locally.
No risks.
No.
No.

Fault Injection: execute operation while still returning an error to the caller

---

service/history/workflow/update/update.go
service/history/workflow/update/update_test.go

Allow transition from `stateAdmitted` to `stateAccepted`.
See comment in the code:
> 	// Normally update goes from stateAdmitted to stateSent and then to stateAccepted,
// therefore the only valid state here is stateSent.
// But if update registry is cleared after update was sent to the worker,
// it will be recreated by retries in stateAdmitted, and then worker can accept previous (cleared) update
// with the same UpdateId. Because it is, in fact, the same update, server should process this accept message w/o error.
// Therefore, stateAdmitted is also a valid state.
Added new unit test.
No risks.
No.
No.

Workflow Update: allow transition from stateAdmitted to stateAccepted

---

service/history/replication/stream.go
service/history/replication/stream_test.go

Disconnect stream when shard is closed.
When shard is closed, replication stream should not retry on that
unit test
n/a
n/a
Yes

Should disconnect stream when shard is closed

---

common/rpc/interceptor/namespace_rate_limit.go
service/frontend/fx_test.go

- Bypass namespace rate limit interceptor if namespace name cannot be retrieved
- Calls like GetSystemInfo doesn't contain namespace name and today's logic will use empty string `""` as the namespace name and go through a rate limiter for that `""` namespace
- Run server locally

Bypass namespace rate limit interceptor if namespace name cannot be retrieved

---

tests/xdc/history_replication_dlq_test.go

Fixing flaky TestWorkflowReplicationTaskFailure by increasing timeout.
It looks like test timeout is not enough for the history events to get replicated and DLQed.
Increasing the timeout from 30s to 1m. 
No

Fixing flaky TestWorkflowReplicationTaskFailure

---

service/history/replication/stream.go

Make service ShardOwnerShipLost Error non retryable for replication stream
To include both service/persistence ShardOwnerShip lost error
unit test
n/a
n/a
yes

Make service ShardOwnerShipLost Error non retryable for replication stream

---

service/matching/task_writer.go

Eliminate data race in task_writer that caused some functional tests to fail. I believe the race did not impact the functionality, only that the runtime was not happy with it.

fix task_writer data race

---

common/membership/interfaces.go
common/membership/interfaces_mock.go
common/membership/ringpop/service_resolver.go
common/membership/static/service_resolver.go
common/quotas/calculator/cluster_aware_quota_calculator.go
common/quotas/quotastest/fake_instance_counter.go
service/frontend/fx_test.go
service/fx.go

Use `AvailableMemberCount` instead of  `MemberCount` when computing per-host rate limits.
Frontend hosts that are draining shouldn't be counted for this purpose, otherwise we could overcount and set per-host rate limits too low.
existing tests, didn't test this specifically yet

Use AvailableMemberCount when computing member count for rate limits

---

service/history/workflow/mutable_state_impl.go

I was seeing these warnings in logs and figured out that buffered events shouldn't be cached:
```
one or more ids is invalid in event cache	{"shard-id": 4, "address": "127.0.0.1:7231", "wf-id": "c98130b3-fa2a-45ce-bb59-99ad9319fd68", "wf-run-id": "dfe3b762-a12e-403f-950b-73fe8f37ae47", "wf-namespace-id": "d845a676-2988-47a3-aee8-f495e09ef65c", "wf-history-event-id": -123, "logging-call-at": "cache.go:124"}
```

Fix: Don't cache buffered events in MutableStateImpl.AddHistoryEvent

---

tests/activity.go
tests/advanced_visibility.go
tests/archival.go
tests/cancel_workflow.go
tests/child_workflow.go
tests/continue_as_new.go
tests/cron.go
tests/describe.go
tests/gethistory.go
tests/relay_task.go
tests/reset_workflow.go
tests/signal_workflow.go
tests/sizelimit.go
tests/stickytq.go
tests/taskpoller.go
tests/transient_task.go
tests/update_workflow.go
tests/user_timers.go
tests/workflow.go
tests/workflow_buffered_events.go
tests/workflow_delete_execution.go
tests/workflow_failures.go
tests/workflow_memo.go
tests/workflow_timer.go
tests/workflow_visibility.go
tests/xdc/advanced_visibility_test.go
tests/xdc/failover_test.go
tests/xdc/history_replication_signals_and_updates_test.go
tests/xdc/stream_based_replication_test.go

The `TaskPoller` we use in the tests takes a `workflowTaskHandler` which has 5 parameters. But all of them come from `PollWorkflowTaskQueueResponse` anyway - so might as well use that directly.
Shortens the function's interface.
And most handlers don't use _any_ of the parameters anyway.
Is nothing but tests.

Simplify TaskPoller's WorkflowTaskHandler

---

service/history/api/respondworkflowtaskfailed/api.go
service/history/api/respondworkflowtaskfailedrequest/api.go
service/history/history_engine.go
service/history/workflow_task_handler_callbacks.go

Extracted handler for `RespondWorkflowTaskFailedRequest` out of `workflow_task_handler_callbacks.go` into its own file.
Remaining ones will be moved in follow-up PRs.
There's no clear benefit to grouping the WFT API handlers all in the - poorly named - file. The PR makes this consistent with the existing API handlers now.
Pure refactoring, no behavior change.

Extract RespondWorkflowTaskFailedRequest handler

---

service/history/api/scheduleworkflowtask/api.go
service/history/history_engine.go
service/history/workflow_task_handler_callbacks.go

Extracted handler for `ScheduleWorkflowTask` out of `workflow_task_handler_callbacks.go` into its own file.
There's no clear benefit to grouping the WFT API handlers all in the - poorly named - file. The PR makes this consistent with the existing API handlers now.
Pure refactoring, no behavior change.

Extract ScheduleWorkflowTask handler

---

service/history/api/recordworkflowtaskstarted/api.go
service/history/api/verifychildworkflowcompletionrecorded/api.go
service/history/history_engine.go
service/history/workflow_task_handler_callbacks.go

Extracted handler for `RecordWorkflowTaskStarted` out of `workflow_task_handler_callbacks.go` into its own file.
There's no clear benefit to grouping the WFT API handlers all in the - poorly named - file. The PR makes this consistent with the existing API handlers now.
Pure refactoring, no behavior change.

Extract RecordWorkflowTaskStartedRequest handler

---

tests/workflow.go

Fixing flakiness of MultiOperation test where workflow id conflict policy is "terminate".

Fix flaky MultiOperation test

---

go.mod

Specify minor version of Go compiler
It's now required. See https://github.com/golang/go/issues/65568
`go mod tidy && make bins`
None
No

Specify Go compiler minor version

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/outbound_queue_factory.go

Dynamic config for the outbound queue group limiter settings
Have the config dynamic instead of hard typed in the code.

Dynamic config for the outbound queue group limiter settings

---

common/dynamicconfig/constants.go
service/worker/scheduler/activities.go
service/worker/scheduler/fx.go

Add a config for the "1 second" limit on local activity sleep due to rate limit.
Also rename some stuff to be more readable.
We want to adjust this to tune rate limiting behavior.
will test manually

Add config for scheduler local activity sleep limit

---

components/callbacks/config.go
components/callbacks/executors.go
components/callbacks/executors_test.go
components/callbacks/fx.go

Dynamic config for request timeout in callbacks component
Be able to config by destination.

Dynamic config for request timeout in callbacks component

---

components/nexusoperations/config.go
components/nexusoperations/executors.go
components/nexusoperations/executors_test.go

Change nexus operations request timeout dynamic config to filter by destination
Be able to config request timeout by destination.

Change nexus operations request timeout dynamic config to filter by destination

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/outbound_queue_factory.go

Dynamic config for the outbound queue host scheduler task rps
Be able to config by destination.

Dynamic config for the outbound queue host scheduler task rps

---

common/backoff/retry.go
common/backoff/retry_test.go
common/backoff/retrypolicy.go
common/backoff/retrypolicy_test.go
service/history/queues/queue_base.go
service/history/queues/reader.go
service/matching/task_reader.go
service/worker/pernamespaceworker.go

- `ConcurrentRetrier`: deleted, not used anywhere
- `TwoPhaseRetryPolicy`: deleted, not used anywhere
- `SystemClock`: replaced with `clock.TimeSource`
Less code is good.
Compiler.

Delete unused retry implementations

---

service/history/api/verifyfirstworkflowtaskscheduled/api.go
service/history/api/verifyfirstworkflowtaskscheduled/api_test.go
service/history/history_engine.go
service/history/workflow_task_handler_callbacks.go
service/history/workflow_task_handler_callbacks_test.go

Extracted handler for `VerifyFirstWorkflowTaskScheduledRequest` out of `workflow_task_handler_callbacks.go` into its own file.
There's no clear benefit to grouping the WFT API handlers all in the - poorly named - file. The PR makes this consistent with the existing API handlers now.
Pure refactoring, no behavior change.

Extract VerifyFirstWorkflowTaskScheduledRequest handler

---

common/circuitbreaker/circuitbreaker.go
common/circuitbreaker/circuitbreaker_test.go
common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/outbound_queue_factory.go
service/history/queues/executable.go

Circuit breaker with dynamic settings: it takes a function that is evaluated whenever `Allow` is called, and if any change happened, then it replaces the circuit breaker with the updated changes (previous state is lost). This makes possible to have the circuit breaker automatically update after a dynamic config change.
Added dynamic config for outbound queue circuit breaker.
Be able to config by destination.

Circuit breaker with dynamic settings

---

service/history/hsm/tree.go

Fixes a panic observed in functional tests:
```
nexus_workflow_test.go:161: 
Error Trace:	/home/runner/work/temporal/temporal/tests/nexus_workflow_test.go:161
Error:      	Received unexpected error:
panic: Cache encountered dirty mutable state transaction
Test:       	TestClientFunctionalSuite/TestNexusOperationCancelation
```
I ran the tests in a loop with logging and found out the source.
Ran it again in a loop for a few minutes to verify the fix.

Fix panic in Nexus functional tests

---

tests/activity.go
tests/archival.go
tests/describe.go
tests/gethistory.go
tests/reset_workflow.go
tests/signal_workflow.go
tests/sizelimit.go
tests/taskpoller.go
tests/update_workflow.go
tests/workflow.go
tests/workflow_buffered_events.go
tests/workflow_failures.go
tests/xdc/failover_test.go

The TaskPoller we use in the tests takes a activityTaskHandler which has 5 parameters. But all of them come from PollActivityTaskQueueResponse anyway - so might as well use that directly.
Shortens the function's interface. Less verbose.
Is nothing but tests.

Simplify TaskPoller's ActivityTaskHandler

---

docs/architecture/retry.md

Adding a short doc to give a basic overview of the gRPC retry behavior.
Note that this could/should also include the task processing retry behavior, but I'm not familiar enough with it to write that right now.

Add docs describing retry behavior

---

service/history/api/recordworkflowtaskstarted/api.go

Fix prometheus warning message by adding `namespace` tag.
```
{"level":"warn","ts":"2024-05-14T15:14:32.598-0700","msg":"error in prometheus reporter","error":"a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"AccessHistoryNew\", help: \"AccessHistoryNew counter\", constLabels: {}, variableLabels: {operation,namespace,service_name}} has different label names or a different help string","logging-call-at":"config.go:432"}
```
Note: code will be removed very soon.
Set of tags must be the same on the same metric. I hope it fixes #5897.
Run it locally and checked logs with eyeballing.

Fix prometheus warning message

---

.github/workflows/stale.yml

Following [the documentation](https://github.com/actions/stale?tab=readme-ov-file#recommended-permissions), adding permissions to this GitHub action.
The "label stale PR" GitHub Action I've added doesn't work since it [doesn't have permissions](https://github.com/temporalio/temporal/actions/runs/9087827866/job/24976300438#step:2:2041):
```
Error: [#5265] Error when creating a comment: Resource not accessible by integration
```
I can't?

Add permission for staleness GitHub Action

---

service/history/api/respondworkflowtaskcompleted/api.go
service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler.go
tests/update_workflow.go

Improve "update not found" error message.
Also change `nonRetryable` flag on failure to `false` (meaning that failure is retryable). This failure is not used by the code, but just goes to the history and shows up in UI. Because WFT failures are retryable, setting it to `false` is more accurate.
When update is not found while handling messages from worker, it is most likely means that update registry was cleared but retries on the caller side will recreate it. I am trying to phrase it in the way it clearly says that it is not an user error.
N/A
No risks.
No.
Yes, to 1.24.0.

Workflow Update: improve "update not found" error message

---

common/rpc/interceptor/namespace.go

We now only log the type of the request we failed to find namespace details on rather than the contents of the request, which required expensive reflection.
This is an expensive error path otherwise. We discovered we spent more time in this error path than in our actual logic when running an experiment
None
No

Dump only the type of request when we fail to find Namespace info

---

service/history/workflow/update/update_test.go

Fix flaky `TestWaitLifecycleStage` test by increasing timeout which shouldn't fire 5 times. With former 2x buffer on slow runners user timeout expires before `WaitLifecycleStage` is called.
Test flakiness is bad.
Run it.

Fix flaky TestWaitLifecycleStage test

---

common/persistence/visibility/store/elasticsearch/converter.go
common/persistence/visibility/store/elasticsearch/converter_test.go
common/persistence/visibility/store/elasticsearch/visibility_store.go
common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
common/persistence/visibility/store/query/converter.go
common/persistence/visibility/store/query/interceptors_test.go
service/frontend/workflow_handler.go
service/worker/scheduler/query.go
service/worker/scheduler/query_test.go

- ElasticSearch query converter now uses term query if the search attribute is of type KEYWORD or KEYWORD_LIST 
- otherwise, it uses match query to support type TEXT matching in custom search attribute
- added `searchattribute.NameTypeMap` in `comparisonExprConverter` to support this
- Improvement in performance: term query is generally faster than match query
- modified converter and elasticsearch unit tests accordingly to use term query

Modified elasticsearch to use term query for keyword matching

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/replication/executable_activity_state_task.go
service/history/replication/executable_history_task.go
service/history/replication/executable_task.go
service/history/replication/executable_workflow_state_task.go
service/history/replication/executable_workflow_state_task_test.go
service/history/replication/fx.go
service/history/replication/raw_task_converter.go

add dynamic config for history.ReplicationTaskApplyTimeout
We encountered "context deadline exceeded" when retrieving events from tiered storage. Make this timeout configurable to unblock migration.

add dynamic config for history.ReplicationTaskApplyTimeout

---

service/matching/physical_task_queue_manager.go
service/matching/task_queue_partition_manager.go
service/matching/task_queue_partition_manager_test.go
service/matching/version_rule_helpers.go
service/matching/version_rule_test.go

Make sure redirect rule source Build IDs are loaded as long as the terminal Build ID in that chain is being polled. Also, rejecting pollers of such source Build IDs with a `NewerBuildExists` error.
So that user can safely stop old worker and their backlog keeps being processed no matter how old.
If too many Build IDs are involved in a chain, all of them will be loaded all the time as long as the last one of them is getting pollers. We have a limit on the size of a redirect chain so this is controlled.
None.
No. But candidate cherry-pick into 1.24.0 OS release.

Keep redirect source queues loaded

---

service/history/workflow/cache/cache.go

- "Fix" current workflow lock release
- Just to follow the pattern for all other places.
- Doesn't really matter what value is passed in here since the error is just for determining if mutable state should be cleared or not. However, there's no mutable state for current workflow (we are just using it as a lock), so nothing to clear. As long as the lock is released, we are good.
- No

Fix current workflow lock release

---

service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_test.go

Workflow Update: return error if update is completed w/o accepted event.
`UpdateCompleted` event should always be preceded but `UpdateAccepted` event. Otherwise there is a bug in server or SDK. Error should be returned instead of swallowing error.
No risks.
No.
No.

Workflow Update: return error if update is completed w/o accepted event

---

cmd/tools/gendynamicconfig/main.go
common/dynamicconfig/collection.go
common/dynamicconfig/collection_test.go
common/dynamicconfig/config/testConfig.yaml
common/dynamicconfig/file_based_client_test.go
common/dynamicconfig/setting.go
common/dynamicconfig/setting_gen.go
go.mod
go.sum

Add more flexible generic typed dynamic config. This can be used to replace lists and maps in a convenient and safe way.
A lot of the work is done by https://pkg.go.dev/github.com/mitchellh/mapstructure to convert from the output of yaml.Unmarshal to arbitrary structs.
I'll follow up this PR with another one to convert most of our current uses of maps to structs.
Support more data types and remove a bunch of boilerplate code.
unit tests

Add generic typed settings

---

common/rpc/interceptor/namespace_validator.go
common/rpc/interceptor/namespace_validator_test.go

Exclude `DescribeHistoryHost` requests from namespace interceptor. Fixes #5933.
`Namespace` field is optional on the request, and it should be processed regardless of presence or namespace state.
Tested with `tdbg history-host describe --history-address <history-host-ip:port>`
Probably not, I don't know how common or urgently the history host describe command is needed.

Allow DescribeHistoryHost requests without namespace set

---

common/dynamicconfig/collection.go
common/dynamicconfig/collection_test.go
common/dynamicconfig/file_based_client.go
common/dynamicconfig/file_based_client_test.go
common/dynamicconfig/find_match_test.go

Move most unit tests to external package, except two for an internal helper function.
To write tests as an client to the package would use it, which usually produces better tests.
is tests

Move most dynamicconfig tests to external package

---

service/matching/ack_manager.go
service/matching/ack_manager_test.go
service/matching/backlog_manager.go
service/matching/physical_task_queue_manager.go
service/matching/physical_task_queue_manager_test.go
tests/describe_task_queue.go

- `approximateBacklogCounter` to be available via legacy `DescribeTaskQueue` API
- Legacy `BacklogCountHint` is removed. I propose that the new `approximateBacklogCounter` is a better estimate for task backlog and has been replaced.
- Functional test checking if the in-memory backlog counter is updated as expected
- Updated unit tests which were dealing with the legacy API
- It is better to emit the more accurate backlog counter, which in this case, would be `approximateBacklogCounter`.
- Current CI/CD tests
- Functional test added
None since this is merging into my own feature branch.
No

Made approximateBacklogCounter available via legacy API

---

service/history/api/reapplyevents/api.go
service/history/api/signalwithstartworkflow/signal_with_start_workflow.go
service/history/api/update_workflow_util.go
service/history/archival_queue_task_executor.go
service/history/archival_queue_task_executor_test.go
service/history/history_engine_test.go
service/history/ndc/buffer_event_flusher_test.go
service/history/ndc/events_reapplier_test.go
service/history/ndc/workflow.go
service/history/ndc/workflow_resetter.go
service/history/ndc/workflow_resetter_test.go
service/history/ndc/workflow_test.go
service/history/timer_queue_standby_task_executor.go
service/history/timer_queue_task_executor_base.go
service/history/timer_queue_task_executor_base_test.go
service/history/transfer_queue_active_task_executor.go
service/history/transfer_queue_active_task_executor_test.go
service/history/transfer_queue_standby_task_executor.go
service/history/transfer_queue_task_executor_base.go
service/history/visibility_queue_task_executor.go
service/history/workflow/mutable_state.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_mock.go
service/history/workflow/workflow_task_state_machine.go

- Account for state only changes in LastWriteVersion
- ^ also means LastWriteVersion could change after workflow is closed.
- NOTE: this PR is stacked on top of https://github.com/temporalio/temporal/pull/5860
- Account for state only changes
- Existing tests & new unit tests

Account for state only changes in LastWriteVersion

---

tests/versioning.go

Fix TestDescribeTaskQueueEnhanced flake by adding count with query
There is a slight delay between when the Workflow Execution first shows up in visibility and when the search attribute is updated. The previous `s.Eventually` condition was not specific enough, so it allowed the test to proceed when the search attribute had not landed yet, leading to a false reachability result.
Tested locally, will trust it if CI passes.
Worst case, this doesn't fix the flake. But based on my understanding of the issue, it will.
n/a
no

Fix TestDescribeTaskQueueEnhanced flake by adding count with query

---

common/cache/lru.go
common/cache/lru_test.go
common/namespace/registry.go
common/persistence/xdc_cache.go
service/history/events/cache.go
service/history/workflow/cache/cache.go
service/matching/poller_history.go
service/matching/reachability.go
service/worker/scheduler/spec.go

We had added metrics handler in LRU cache for more visibility into its size and eviction times.
But for this to work, we had to provide a metrics handler with cache type tag. This is confusing as it is not obvious to provide this tag when passing a metrics handler. This has created some issues recently.
Most users of this cache object do not need metrics. Removing metrics handler from lru.New() function and adding a separate function lru.NewWithMetrics() for consumers who need metrics.
To remove confusion in LRU creation.
Unit tests
None
No

Removing metrics handler from lru.New()

---

service/history/queues/executable.go

Changing log level for unexpected errors to warning in task processing.
Sometimes errors like shard ownership lost fills log with stack traces, making it harder to read.
The stack trace printed in the log corresponds to this logging line rather than the actual stack where the error happened.
So this stack trace is not very useful anyways.
Making the log easier to read.
None
No

Changing log level for unexpected errors

---

service/history/replication/stream_sender.go

Add retry on replication sender for single replication task
We should not rely on stream retry if there is error on DB throttling. Stream retry will re-send task from ACK level, if ACK level is left behind and progressing slow, we will repeat the resend process again and again. This is not a good use of resource.
relying on current test.
no
n/a
yes

Add retry on replication sender for single replication task

---

service/history/workflow/mutable_state_impl_restart_activity_test.go
service/history/workflow/mutable_state_impl_test.go
service/history/workflow/retry.go

Workflows can now return an application error with NextRetryDelay option to customize when the workflow will be retried again.
```
return temporal.NewApplicationError(
"some retryable error",
"SomeType",
temporal.ApplicationErrorOptions{NextRetryDelay: 2 * time.Minute},
)
```
Currently Activity tasks can customize the next retry time. This is bringing the same feature to workflow tasks as well.
Also added a test to assert next retry delay customization in activities.
No

Handle NextRetryDelay option in workflow failures

---

service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler.go
service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler_test.go

In this PR we are attaching the user metadata if found in the command to the corresponding history events that are being created. 
Users need a way to set arbitrary information on workflows and events. This would be later used in the clients to build custom tooling (ex: UI showing additional information about a timer event etc)
N/A. It is backward compatible. 
N/A
No

Attach user metadata from commands to corresponding history events

---

common/persistence/tests/cassandra_test_util.go
common/persistence/tests/execution_mutable_state.go
common/persistence/tests/mysql_test.go
common/persistence/tests/mysql_test_util.go
common/persistence/tests/postgresql_test.go
common/persistence/tests/postgresql_test_util.go
common/persistence/tests/sqlite_test.go
common/persistence/tests/util.go

I replaced all panics in the persistence tests with calls to `testing.T.Fatalf` so they're easier to find.
I also updated the SQLite setup to log the error itself and not `%+v` of the error tag wrapper
To make these failures easier to find and/or possible to diagnose. We ate the error in https://github.com/temporalio/temporal/actions/runs/9199422279/job/25304258612 so I don't know why it flaked
No

Replace test setup panics with t.Fatalf

---

service/history/api/updateworkflow/api.go
service/history/workflow/workflow_task_state_machine.go

Always use speculative workflow task for updates.
Always use speculative workflow task for updates and make decision on dropping it to `RespondWorkflowTaskCompleted` handler. In future, this will allow to introduce SDK capability to handle case when WFT can disappear even if it carried events to SDK. 
At first, I thought that there is minimal risk of WFT being scheduled and completed on different hosts during deployment, but even this minimal risk doesn't exist because speculative WFT stays only in the host memory and can't be scheduled and completed on different hosts. So "No risks".
No.
No.

Always use speculative workflow task for updates

---

service/history/api/describeworkflow/api.go
service/history/api/signalwithstartworkflow/convert.go
service/history/historybuilder/history_builder.go
tests/user_metadata_test.go

We are now handling the User Metadata attached in the start workflow requests.
Users need a way to set arbitrary information on workflows and events. This would be later used in the clients to build custom tooling (ex: UI showing additional information about a timer event etc)
Added new functional tests
N/A
N/A
No

Handle User Metadata in workflow start requests

---

common/metrics/tags.go
service/matching/matching_engine.go
tests/versioning.go

Properly check report pollers and report reachability flags in enhanced DescribeTaskQueue.
This is a bug.
none.
none.
yes.

Properly check report pollers and report reachability flags

---

common/config/config.go
common/persistence/sql/sqlplugin/mysql/plugin.go
common/persistence/sql/sqlplugin/postgresql/plugin.go

SQL config now supports passing a connect function.
It's currently not possible to embed a Temporal server to a host application where the database connection is managed by the host application and is provided as a database connector. This allows the host application to pass a db connector rather than the the individual sql config strings.
I have embedded this code into a custom application and verified that the connector is working properly.
This is a non-breaking change with very minimal risks.
No.

Support sql connector

---

service/matching/backlog_manager_test.go
service/matching/matcher.go
service/matching/matching_engine.go
service/matching/matching_engine_test.go
service/matching/physical_task_queue_manager.go
service/matching/physical_task_queue_manager_mock.go
service/matching/task_reader.go
tests/describe_task_queue.go

Added functionality to emit the create time, from now, of a given backlog via the `DescribeTaskQueue` API.
- Unit test
- Integration test
None, merging to feature.
No

added backlog head create time metric + unit and integration test

---

service/matching/ack_manager.go
service/matching/ack_manager_test.go
service/matching/backlog_manager.go
service/matching/physical_task_queue_manager.go

Conversation from @dnr and @ShahabT, over [here](https://github.com/temporalio/temporal/pull/5934#discussion_r1610692023), made me realize that the legacy backlog hint is required. Since the updated backlog counter is an overestimate, it could result in a case where a worker keeps on polling a sticky queue even when there are no tasks in the backlog. Thus, it is better and safer to restore this.
- Existing suite of tests.
No, merging to feature and restoring previously pushed changes.
No

Restoring legacy backlog hint

---

.golangci.yml
common/testing/testvars/test_vars.go
service/history/api/respondworkflowtaskcompleted/api_test.go
service/history/workflow/update/export_test.go
service/history/workflow/update/registry.go
service/history/workflow/update/registry_test.go
service/history/workflow/update/store.go
service/history/workflow/update/store_mock_test.go
service/history/workflow/update/update.go
service/history/workflow/update/update_test.go
tests/client_suite.go
tests/reset_workflow.go
tests/update_workflow.go
tests/update_workflow_sdk.go
tests/user_metadata_test.go
tests/workflow.go
tests/workflow_delete_execution.go
tests/xdc/history_replication_signals_and_updates_test.go

To make sure the update package tests are in tip top shape.
All tests (and production code changes are purely cosmetic).

Revamp Update package's unit tests (1/2)

---

common/log/tag/tags.go
service/history/replication/executable_activity_state_task.go
service/history/replication/executable_activity_state_task_test.go
service/history/replication/executable_history_task.go
service/history/replication/executable_history_task_test.go
service/history/replication/executable_task.go
service/history/replication/executable_task_tracker.go
service/history/replication/executable_workflow_state_task.go
service/history/replication/executable_workflow_state_task_test.go

Add Max retry Attempts when putting replication task to DLQ
When failed to put task to DLQ, the task will stay at ExecutableTaskTracker and will block the ACK level. In a extreme case where DLQ component is down, the poison pill task will stay and accumulate in ExecutableTaskTracker.
Unit test
Nothing
n/a
Yes.

Add Max retry Attempts when putting replication task to DLQ

---

go.mod
go.sum

Fixes: https://github.com/temporalio/temporal/issues/2703
Bumped tchannel-go version.
This allows Temporal to build for FreeBSD.
Cross compiled for FreeBSD.

Bump tchannel-go to allow building on FreeBSD.

---

common/persistence/tests/visibility_persistence_suite.go
common/persistence/visibility/factory.go
common/persistence/visibility/store/elasticsearch/client/config.go
common/persistence/visibility/store/elasticsearch/visibility_store.go
common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
service/frontend/fx.go
service/history/fx.go
service/matching/fx.go
service/worker/fx.go
temporal/fx.go
tests/onebox.go

- moved ES processor initialization to visiblity store constructor
- create ES client in ES visibility store constructor
- add private field `httpClient` in elasticsearch config and use config to create `esClient` directly in visibility store 
- this will enable creating separate esClients for primary/secondary visibility store
- not optimal to initialize the ES processor/client outside of the Elasticsearch visibility store
- verified that ES processor is being initialized within ES visibility store locally

refactor ES constructor: moved ES processor/client initialization to visiblity store ctor

---

common/authorization/authorizer.go
service/frontend/nexus_handler.go
tests/nexus_api_test.go

When dispatching Nexus requests, the endpoint name should be taken into consideration for auth purposes along with the namespace.

Add NexusEndpointName to authorizer CallTarget

---

service/history/hsm/tree.go
service/history/hsm/tree_test.go
service/history/workflow/task_refresher_test.go

Previously on transitions marked the tree as dirty.
This was okay because we never added a child without immediately transitioning but was technically incorrect.

Mark HSM tree as dirty on AddChild

---

service/matching/physical_task_queue_manager.go
service/matching/physical_task_queue_manager_test.go

Restore behavior added in #5345, that got lost in merging.
See #5345 
added unit test

Fix interrupting poll on partition unload

---

Makefile

Add goimports to go-generate in makefile
$(GOIMPORTS) needs to be a dependency of go-generate, otherwise make go-generate fails.
run it. make sure mocks are generated
N/A
N/A
No

Fix go-generate - provide goimports

---

service/history/api/respondworkflowtaskcompleted/api_test.go

Moved the initialization of the dependencies out of the test into the test setup; to ensure it is run for every test.
And used `SetupSubTest` to ensure it's run for every sub-test.
One test ("Write Failed") was affecting the other test ("GetHistory Failed") because the shard was being re-acquired after the first one simulated a write error.

Fix flaky workflowtaskcompletedhandlersuite

---

service/history/ndc/workflow_state_replicator.go
tests/xdc/stream_based_replication_test.go

Fix reset workflow case with force replication
bug when force replication 2+ reset workflows
new integration test

Fix reset workflow case with force replication

---

common/dynamicconfig/collection.go
common/dynamicconfig/collection_test.go

Convert more numerical types in dynamic config.
Types besides `int` and `float64` generally won't show up using the default yaml-based dynamic config client, but other clients (e.g. static clients for test or dev server) might use different concrete types.
Added a few more unit tests
This may make some configurations work where they didn't work before, but shouldn't change the behavior of any working configuration.

Allow more numeric types in dynamic config

---

.github/workflows/run-tests.yml

Downgrading Github `All Tests` actions to use `ubuntu-20.04` instead of `ubuntu-latest`
It seems we started hitting an issue with Github's action runners. These errors seem to appear most often when runners are killed because they are using too much CPU or memory, but we have been unable to conclusively say what might have caused an increase in resource usage.
Downgrading the ubuntu version worked for others and seems to be working for us.
For more info:
* https://github.com/actions/runner-images/issues/6709
* https://github.com/actions/runner-images/discussions/7188
* Users reported a similar issue with ubuntu-24.04 runners (not yet GA): https://github.com/actions/runner-images/issues/9848
Reran all PR check jobs several times

Change runner image to ubuntu-20.04

---

common/persistence/data_interfaces.go
common/persistence/history_branch_util.go
common/persistence/history_branch_util_mock.go
common/persistence/history_branch_util_test.go
common/persistence/history_manager.go
common/persistence/persistence-tests/history_v2_persistence.go
common/persistence/persistence_interface.go
common/persistence/tests/history_store.go
service/history/ndc/branch_manager.go
service/history/ndc/branch_manager_test.go
service/history/ndc/resetter.go
service/history/ndc/resetter_test.go
service/history/ndc/workflow_resetter.go
service/history/ndc/workflow_resetter_test.go
service/history/ndc/workflow_state_replicator.go
service/worker/scanner/history/scavenger_test.go

Pass new run ID into the new branch token initialization.
Replace ForkBranchToken with NewBranchToken in InternalForkHistoryBranchRequest. The new branch token is derived from the base branch token and contains the updated set of ancestors.

Replace base branch token with new branch token in fork request

---

common/config/config.go
common/config/persistence.go
common/persistence/visibility/factory.go
temporal/fx.go

Remove deprecated `advancedVisibilityStore` config key.
Undoing the PR https://github.com/temporalio/temporal/pull/5549.
It's deprecated, and replaced with `secondaryVisibilityStore`.

Remove deprecated advancedVisibilityStore config key

---

service/history/api/respondworkflowtaskcompleted/api.go

Always use speculative workflow task for updates from `RespondWorkflowTaskCompleted` handler.
Follow up to #5921.
No risks (see #5921).
No.
No.

Workflow Update: always use speculative workflow task for updates from RespondWorkflowTaskCompleted handler

---

service/history/replication/executable_activity_state_task.go
service/history/replication/executable_activity_state_task_test.go
service/history/replication/executable_history_task.go
service/history/replication/executable_history_task_test.go
service/history/replication/executable_noop_task.go
service/history/replication/executable_task.go
service/history/replication/executable_task_converter.go
service/history/replication/executable_task_test.go
service/history/replication/executable_unknown_task.go
service/history/replication/executable_workflow_state_task.go
service/history/replication/executable_workflow_state_task_test.go

Do not emit replication lag metrics for low priority tasks
Low priority tasks processing maybe delayed, we should not emit replication lag metrics as it will create some unnecessary noise.
unit test.
nothing.
n/a
No.

Do not emit replication lag metrics for low priority tasks

---

common/api/metadata.go
common/metrics/metric_defs.go
common/rpc/interceptor/telemetry.go
common/rpc/interceptor/telemetry_test.go

Polling for workflow execution history has significantly longer latency. Splitting the metrics for the bimodal behavior reflects latency metrics more accurately.

Disambiguate metrics for getting vs polling workflow execution history

---

common/config/persistence.go

- modified persistence validation to support having secondary visibility store through `secondaryVisibilityStore` config key
- user can set dual ES visibility via 
1. the existing indices.secondary_visibility key (backwards compatibility); or
2. using the secondaryVisibilityStore and setting another data store config
- restrictions:
- they must be mutually exclusive
- ES config must be same except for `indices.visibility` in case of using secondaryVisibilityStore config (this is because we still have the global ES client)

Support having secondary visibility store through `secondaryVisibilityStore` config key

---

cmd/tools/gendynamicconfig/main.go
common/dynamicconfig/setting_gen.go

Make old types aliases to new generic types.
Simplify code, reduce volume of generated code.
existing tests

Simplify dynamic config code generation

---

common/cluster/frontend_http_client.go

Fix panic during cluster-b start
Should check nil pointer.
```
./temporal-server --env development-cluster-b --allow-no-auth start
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x104e3cd68]
goroutine 553 [running]:
go.temporal.io/server/common/cluster.(*FrontendHTTPClientCache).evictionCallback(0x140008a76e0, 0x14000b455e8?, 0x14000dae120)
/Users/hai/dev/github.com/temporalio/temporal/common/cluster/frontend_http_client.go:120 +0xe8
go.temporal.io/server/common/cluster.(*metadataImpl).refreshClusterMetadata(0x14000b831e0, {0x106d2b1a0?, 0x14000944ba0?})
/Users/hai/dev/github.com/temporalio/temporal/common/cluster/metadata.go:484 +0x79c
go.temporal.io/server/common/cluster.(*metadataImpl).Start(0x14000b8 …
```

fix panic during cluster-b start

---

service/matching/matcher_test.go

- `matcher_test.go` consisted of a test which intended on checking if the actual value of the backlog age differs from the expected by a delta 
- However, the test was using `InEpsilon` instead of `InDelta`. This fixes that.
- For correct functionality.
Unit test
- None
No

Changed unit test to now use InDelta instead of InEpsilon

---

service/history/workflow/activity.go
service/history/workflow/mutable_state_impl_restart_activity_test.go

When an activity specifies `next_retry_delay` in the application failure, we should be ignoring the max interval set in the retry policy. This PR allows it.
The intention of the application here is to override the retry policy and customize the next attempt time. 
https://github.com/temporalio/api/blob/5b356b506e0b86ba26dc6f795bfb011eeb4dfa6e/temporal/api/failure/v1/message.proto#L49
N/A
N/A
No

Next retry delay should not be bounded by retry policy MaximumInterval

---

schema/mysql/v8/version.go
schema/mysql/v8/visibility/schema.sql
schema/mysql/v8/visibility/versioned/v1.6/fix_root_workflow_info.sql
schema/mysql/v8/visibility/versioned/v1.6/manifest.json
schema/postgresql/v12/version.go
schema/postgresql/v12/visibility/schema.sql
schema/postgresql/v12/visibility/versioned/v1.6/fix_root_workflow_info.sql
schema/postgresql/v12/visibility/versioned/v1.6/manifest.json
schema/sqlite/v3/visibility/schema.sql

Fix SQL visibility root workflow fields in schema: they are supposed to be not null.
The schema set the root workflow fields as nullable, but the code was assuming to be not null.
GH Issue: https://github.com/temporalio/temporal/issues/6050
Start Temporal v1.23.1, create some workflows, update the schemas in v1.24.0, upgrade Temporal v1.24.0:
- reproduced the error
- applied this fix, and the error was gone.

Fix SQL visibility root workflow fields in schema

---

components/nexusoperations/executors.go
components/scheduler/executors.go
service/history/hsm/tree.go

Renamed and refactored `Node.CheckIsParentRunning` to `CheckRunning`.
Leaks a bit less details about state machine being embedded in a workflow. This same check will later also be used to validate run state for top level machines.

Refactor hsm CheckRunning

---

common/metrics/metric_defs.go
service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler.go

In #4995 we introduced a new unified metric covering all command types processed by the history service. The old individual command type metrics were deprecated at that time. This PR removes the deprecated metrics entirely.
Migration to the new unified metric has been completed.
`make unit-test`
Missing a consumer/monitor/dashboard that had been making use of the deprecated metrics, thereby impairing observability

Remove deprecated metrics from history service commands

---

common/dynamicconfig/collection.go
common/dynamicconfig/collection_test.go

Use strconv.ParseBool to convert strings to bools in dynamic config.
Be more flexible in case someone quotes a bool.
unit test

Accept strings for bool in dynamic config

---

service/history/replication/ack_manager.go
service/history/replication/stream_sender.go

Change GetReplicationTasksIter context timeout handling
The current context handling is assuming all replication tasks should be handled within context deadline, this is not achievable when the range of iter is large, i.e. during catchup stage, the range of [min, max] could be very large, it is not appropriate to use the same context for every iterator call. 
N/a
n/a
no
no

Change GetReplicationTasksIter context timeout handling

---

components/callbacks/executors.go
components/nexusoperations/executors.go
components/scheduler/executors.go
service/history/hsm/registry.go
service/history/hsm/tasks.go
service/history/ndc_standby_task_util.go
service/history/outbound_queue_factory.go
service/history/outbound_queue_standby_task_executor.go

Outbound standby task executor. Currently, it doesn't need an executor for each component, and only needs concurrent task to implement a `Validate` function to check if the task is still valid.

Outbound standby task executor

---

cmd/server/main.go
cmd/tools/gendynamicconfig/main.go
common/dynamicconfig/collection_test.go
common/dynamicconfig/file_based_client.go
common/dynamicconfig/file_based_client_test.go
common/dynamicconfig/registry.go
common/dynamicconfig/setting_gen.go

Added a process-wide registry for dynamic config settings and perform more validation on file load. Files that were successfully loaded before will still be loaded (for now), but more warnings may be logged. Eventually we can make some of the checks stricter.
Added a top-level CLI command to validate dynamic config files.
Catch more errors, set up structure for doc generation and user-defined validation.
unit tests

Add dynamic config registry and validation

---

service/matching/matching_engine_test.go

- Fix for a flaky test
- The test breaks since UpdateState is not an atomic operation (yet) and ownership transfers could lead to an incorrect value of the counter.
- None
No

Fixing flaky test

---

service/matching/matching_engine_test.go

Force GC to make sure all the acked tasks are cleaned up before validating the count.

Fix backlog count flaky test

---

common/persistence/persistence-tests/persistence_test_base.go

Increase namespace enqueue retry
Flaky test

Increase namespace enqueue retry

---

service/history/api/startworkflow/api.go

Return an error if mutable state can't be loaded.
To prevent using invalid mutable state, which can lead to panic.
N/A
N/A
Yes(?)

return an error if mutable state can't be loaded

---

service/history/ndc/workflow_state_replicator.go
service/history/ndc/workflow_state_replicator_test.go

Acquire workflow lock during backfill history
Stream replication processes WorkflowRun concurrently. This could lead to concurrent append history node on same node id and write dirty history node into the table.

Acquire workflow lock during backfill history

---

common/rpc/grpc.go

Printing the actual error when interceptor fails to add resource exhausted error cause to grpc headers.
We were priting the resource exhausted error in this case. This is not useful to find why this operation failed.
Unit test
No

Printing actual error when interceptor fails to add headers to response

---

service/history/ndc/workflow_state_replicator.go
service/history/ndc/workflow_state_replicator_test.go

Acquire workflow lock during backfill history
Stream replication processes WorkflowRun concurrently. This could lead to concurrent append history node on same node id and write dirty history node into the table.

Cherry-pick: Acquire workflow lock during backfill history (#6088)

---

common/nexus/endpoint_registry.go
common/util.go
common/util/util.go
service/matching/task_reader.go
service/matching/user_data_manager.go

Move this utility function.
`common` has too many dependencies and this doesn't need any. Avoids import cycles.
Just moving code

Move common.InterruptibleSleep to util

---

.github/workflows/run-tests.yml
develop/upload-test-results.sh

Separate test execution and test result upload. And check XML file exists.
Previously introduced here https://github.com/temporalio/temporal/pull/6049
make aborts execution when the previous target fails. Oops.
Scenarios:

Fix GHA upload-test-results

---

schema/cassandra/temporal/versioned/v1.10/manifest.json
schema/cassandra/temporal/versioned/v1.10/nexus_incoming_services.cql
schema/cassandra/temporal/versioned/v1.11/manifest.json
schema/cassandra/temporal/versioned/v1.11/nexus_endpoints.cql
schema/cassandra/version.go
schema/mysql/v8/temporal/versioned/v1.12/manifest.json
schema/mysql/v8/temporal/versioned/v1.12/nexus_incoming_services.sql
schema/mysql/v8/temporal/versioned/v1.13/manifest.json
schema/mysql/v8/temporal/versioned/v1.13/nexus_endpoints.sql
schema/mysql/v8/version.go
schema/postgresql/v12/temporal/versioned/v1.12/manifest.json
schema/postgresql/v12/temporal/versioned/v1.12/nexus_incoming_services.sql
schema/postgresql/v12/temporal/versioned/v1.13/manifest.json
schema/postgresql/v12/temporal/versioned/v1.13/nexus_endpoints.sql
schema/postgresql/v12/version.go
schema/sqlite/v3/temporal/versioned/v0.4/manifest.json
schema/sqlite/v3/temporal/versioned/v0.4/nexus_incoming_services.sql
schema/sqlite/v3/temporal/versioned/v0.5/manifest.json
schema/sqlite/v3/temporal/versioned/v0.5/nexus_endpoints.sql
schema/sqlite/version.go

Restored schema scripts for `nexus_incoming_services`
Added new schema revisions to drop `nexus_incoming_services` tables and create `nexus_endpoint` tables
OSS v1.24 was released using an older schema change from before incoming services were renamed to endpoints, so we need to keep that to avoid breaking schema upgrades

Fix Nexus endpoint storage schemas

---

service/history/api/respondworkflowtaskcompleted/api.go
service/matching/version_sets.go
tests/versioning.go

- Remove build id from RecordWorkflowTaskStarted calls for sticky queue tasks.
- When old versioning is used, delay in UserData propagation to sticky queue may make the sticky WFT invalid when it wants to start. this will result in delay in workflow executions because the sticky WFT will be dropped and WF will be blocked until a new normal task gets scheduled (5secs). Note that this is still much better that the workflow getting stuck which happens in 1.24.0 and 1.24.1 fixed by https://github.com/temporalio/temporal/pull/6095.
Unit tests will be added.
None.
None.
No.

Remove build id from sticky recordWorkflowTaskStarted

---

tools/tdbg/commands.go
tools/tdbg/flags.go
tools/tdbg/tdbg_commands.go

Renamed `tdbg decode task` flag from `--task-type` to `--task-category`
The value has always been plumbed through to the category fields; this aligns the flag's name to where the value's been used. No functional change. 
- make bins
- 
```
$ go run cmd/tools/tdbg/main.go decode task -h                                                                                                                                                                                 tdbg_cli_flag_taskcat * ] 11:12 AM
NAME:
tdbg decode task - Decode a history task blob into a JSON message.
USAGE:
tdbg decode task [command options] [arguments...]
OPTIONS:
--binary-file value       file with data in binary format.
--task-category-id value  Task category ID (see the history/tasks package) (default: 0)
....
``` …

rename flag tdbg decode task --task-type to --task-category

---

tools/tdbg/tdbg_commands.go

Fixes up a few leftover references to 'task type' from #6123.

fix a few other references to 'task type' over 'task category' in tdbg

---

common/testing/testvars/test_vars.go
service/history/api/queryworkflow/api.go
tests/query_workflow.go

Before: if there was not workflow task scheduled just fail.
After: check if query will actually time out while waiting, and if it will not - wait.
To reduce avoidable failures. 
Query shouldn't fail if it can wait until successful conditions will be met.
Extend existing functional test to cover both situations.
N/A
N/A
No

When querying workflows during backoff, check if query can wait

---

common/failure/failure.go
common/failure/failure_test.go
common/util/strings.go
common/util/strings_test.go

Truncate could split strings in the middle of utf-8 codepoints.
Also, not all strings in the failure were truncated and depth of failures (at least structure) was not limited.
Avoid invalid utf-8 in strings.
unit tests
This could drop more information from Failures than before.

Fix truncation of Failures

---

common/timer/validation.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_test.go

- Drop scheduled tasks if it's scheduled to run far in the future ( duration > 99 year )
- What if we want to recover those timers? 
- Do a namespace migration, that will re-create all the timers. 
- There's no point creating those timers. They just consume storage spaces. Persistence implementations also don't have a good way for handling them. 
- https://github.com/temporalio/temporal/pull/4775 capped all timer settings to MaxAllowTimer for new workflows. But if workflows are created before that check is added, we may still create timers for those large durations. E.g. the new logic added for creating workflow execution timeout timer based on the persisted workflow execution expiration time.
- NOTE: all capped timers will be dropped as well.
- Yes

Drop scheduled tasks if duration too long

---

common/clock/event_time_source.go
common/clock/event_time_source_test.go
common/clock/time_source.go
common/clock/time_source_test.go
internal/goro/adaptive_pool.go
internal/goro/adaptive_pool_test.go

- Add a utility to manage a pool of goroutine workers.
- Add NewTimer to the TimeSource interface.
To use this for dynamic config subscription callbacks. It can also be used in the deadlock detector (where the pattern was taken from and expanded).
unit tests

Add adaptive worker pool

---

components/callbacks/config.go
components/nexusoperations/completion.go
components/nexusoperations/config.go
components/nexusoperations/events.go
components/nexusoperations/executors.go
components/nexusoperations/executors_test.go
components/nexusoperations/helpers_test.go
components/nexusoperations/statemachine.go
components/nexusoperations/statemachine_test.go
components/nexusoperations/workflow/commands.go
service/history/hsm/events.go
service/history/workflow/mutable_state_rebuilder.go
service/history/workflow/mutable_state_rebuilder_test.go
service/history/workflow/task_generator_test.go
tests/nexus_workflow_test.go
tests/test_cluster.go
tests/xdc/base.go
tests/xdc/failover_test.go
tests/xdc/nexus_request_forwarding_test.go
tests/xdc/nexus_state_replication_test.go

- Added hooks to apply Nexus events during replication
- [Fix max retry interval for operations and callbacks](https://github.com/temporalio/temporal/commit/f6c15221c8640897b76fda5471b301d097572c8d)
- Added unit test and XDC test

Apply Nexus history events during replication

---

service/history/handler.go

Adds logging for when the history service recieves the DeleteWorkflowExecution request. Previously, these were logged as part of the retention timer firing from the timer queue processor.
Gives us more visibility on DeleteWorkflowExecution up-front, instead of when the task is processed later. 
```
$ TEST_ARGS="-v -run TestFunctionalSuite -testify.m TestDeleteWorkflowExecution_CompetedWorkflow" make functional-test
=== RUN   TestFunctionalSuite
2024-06-13T12:33:58.519-0700	info	created database	{"database": "test_0613193358_rge", "logging-call-at": "test.go:182"}
2024-06-13T12:33:59.371-0700	info	loaded schema	{"logging-call-at": "test.go:205"}
=== RUN   TestFunctionalSuite/TestDeleteWorkflowExecution_CompetedWorkflow
======================================================================== …
```

add log line for DeleteWorkflowExecution when request hits HistoryService

---

service/worker/scheduler/workflow.go
service/worker/scheduler/workflow_test.go

In #6028/#5381, our scheduler's run loop accounted for update requests that occur between nominal and actual/jittered times. The run loop will correctly skip over action times who are scheduled prior to the schedule's update time (such as when a schedule is recalculated to a new spec). This PR updates `getFutureActionTimes` (used as part of the scheduler's describe and list operations) to account for action times preceding the update time, as well as to properly reflect the number of remaining actions in a schedule.
- Updated unit tests for both limited actions (`TestLimitedActions`) as well as filtered update times (`TestUpdateNotRetroactive`). `TestUpdateNotRetroactive` is the test that goes red when the [parallel condition in the …

Scheduler Bugfix: getFutureActionTimes should ignore actions prior to update time, respect RemainingActions counter

---

common/metrics/metric_defs.go
common/metrics/tags.go
common/persistence/persistence_metric_clients.go
common/persistence/visibility/visiblity_manager_metrics.go
common/rpc/interceptor/telemetry.go
service/history/replication/task_processor.go

Add scope tag to resource exhausted error metric
so we can tell if the resource exhaust is due to namespace quota or due to system limit
persistence_errors_resource_exhausted{namespace="system",operation="GetClusterMembers",resource_exhausted_cause="PersistenceLimit",resource_exhausted_scope="System",service_name="history"} 1
service_errors_resource_exhausted{namespace="temporal_system",operation="DescribeNamespace",resource_exhausted_cause="RpsLimit",resource_exhausted_scope="System",service_name="frontend"}

Tag resource exhausted error metrics with scope

---

common/cluster/fx.go
common/cluster/metadata.go
common/cluster/metadata_mock.go
common/deadlock/deadlock.go
common/namespace/registry.go
common/namespace/registry_mock.go
common/pingable/pingable.go
common/resource/fx.go
service/history/shard/context.go
service/history/shard/context_impl.go
service/history/shard/context_mock.go
service/history/shard/controller.go
service/history/shard/controller_impl.go
service/history/shard/controller_mock.go
service/history/shard/fx.go

Moving an interface.
Avoid import cycles: I want to use this from dynamicconfig which can't depend on common.

Move pingable interface to separate package

---

service/history/workflow/context.go

Removing CompletionStats from state transition count metric.
This metric was added recently and caused confusion for some users.
None
No

Removing completion stats for state transition count

---

common/metrics/metric_defs.go
common/metrics/tags.go
service/history/shard/context_impl.go

Adding priority metrics to shard semaphore metrics.
To understand more about how different priority requests are treated at shard io semaphore.

Adding priority scope to shard semaphore metrics

---

components/nexusoperations/config.go
components/nexusoperations/workflow/commands.go
components/nexusoperations/workflow/commands_test.go

Operational flexibility, allows deprecating callback URLs and tokens.
This will be even more important when we support callback token encryption and want to limit the lifetime of an encryption key.

Add DC to limit schedule-to-close timeout of a Nexus operation

---

components/callbacks/executors_test.go
components/nexusoperations/executors.go
components/nexusoperations/executors_test.go
service/history/queues/executable.go

Wrap nexus task executor error for circuit breaker: it needs to return `DestinationDownError` for the circuit breaker to trip.

Wrap nexus task executor error for circuit breaker

---

service/history/ndc/state_rebuilder.go

Fix ms rebuilder log version value
The log current print out the pointer address. we need to see the version number.

Fix ms rebuilder log version value

---

common/metrics/metric_defs.go
service/history/historybuilder/event_store.go
service/history/historybuilder/history_builder_test.go

Tag `inordered_buffered_events` metric with completed event type. And also include Nexus events in the metric.
To get better visibility on where in ordered events are coming from.
Didn't test.
No risks.
No.
No.

Tag inordered_buffered_events metric with completed event type

---

common/metrics/defs.go

Fix metrics defs to unhide stack trace of caller
This way, we can see in the stack trace where the metric is defined.

Fix metrics defs to unhide stack trace of caller

---

components/nexusoperations/completion.go

This check was missing and caused indefinite callback retries.

Check workflow running for Nexus completion API

---

service/history/replication/executable_task.go

Revert the change that mark shardonwership error as non retryable
This is creating unnecessary DLQ messages
n/a
no
no
Yes

Fix error handling on replication task

---

common/metrics/metric_defs.go
common/tasks/dynamic_worker_pool_scheduler.go

Export more metrics from dynamic worker pool scheduler:
- enqueued tasks
- dequeued tasks
- rejected tasks
Counters reseted between export intervals

Export more metrics from dynamic worker pool scheduler

---

config/dynamicconfig/development-cass.yaml
config/dynamicconfig/development-sql.yaml

We removed this prefix from all of the routes but forgot to modify the development configs.

Remove /api/v1 from development DC

---

service/history/workflow/update/registry_test.go

I think the problem was that it didn't wait long enough to receive the abort (from `Clear()`). Now with the wait stage, I expect this to be fixed.

Fix flaky update.TestClear test

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/shard/context_impl.go
service/history/shard/context_test.go

1. Add ShardFirstUpdateInterval config setting
2. Initialize shard lastUpdated according to that setting
3. Slightly change the logic in updateShardInfo
In a situations when shard is (re)created again and again shard update (and thus storing shard progress) can be delayed.

Add first shard update interval

---

service/history/queues/executable.go

Ensure that this task is retried less aggressively and does not go to the DLQ.

Return ResourceExhausted error on circuit breaker rejection

---

.github/workflows/run-tests.yml
Makefile

Before this change, if a test suite was stuck, the GHA would forcibly kill the test process. But that meant there was no insight into what it was stuck on.
Now, by stopping the test run before the GHA times out, it will print the stuck tests.
To allow debugging stuck tests.

Timeout test run before GHA

---

service/history/outbound_queue_active_task_executor.go
service/history/outbound_queue_standby_task_executor.go
service/history/queues/metrics.go

Needed in a few different scenarios. Specifically the executable needs a more accurate way to extract the tag.

Expose GetOutboundTaskTypeTagValue

---

tests/update_workflow.go

Fix flaky `TestUpdateWorkflow_ValidateWorkerMessages` test.
Falkiness is bad.
Run it. Only once though.

Fix flaky TestUpdateWorkflow_ValidateWorkerMessages test

---

service/history/historybuilder/event_store.go

Use scheduled/initiated event Id for `out_of_order_buffered_events` metric.
In case if both started and completed events are buffered, `event.GetEventID()` always returns `-123` (buffered event Id) and it is incorrect to use it as a map key.
Run in test environment.
No risks.
No.
No.

Use scheduled/initiated event Id for out_of_order_buffered_events metric

---

components/callbacks/statemachine.go
components/callbacks/statemachine_test.go
components/nexusoperations/statemachine.go
components/nexusoperations/statemachine_test.go
components/scheduler/statemachine.go
service/history/hsm/hsmtest/sm.go
service/history/hsm/tree.go
service/history/workflow/mutable_state.go

This will be used in the temporary sync HSM replication task to determine whether a state is "newer" and should be synced.
Unit tests.

Implement CompareState for Nexus and Callback machines

---

common/serviceerror/obsolete_dispatch_build_id.go
common/worker_versioning/worker_versioning.go
components/nexusoperations/tasks.go
service/history/api/recordworkflowtaskstarted/api.go
service/history/api/respondworkflowtaskcompleted/api.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_test.go
service/history/workflow/workflow_task_state_machine.go
service/matching/task_queue_partition_manager.go
service/matching/version_sets.go
tests/versioning.go

- Prevent setting MS sticky queue if it belongs to an obsolete build ID. (In case WF has moved to a new build ID since the last WFT started).
- Improve sticky queue check in `processBuildIdRedirectInfo` at WFT start time to compare the sticky TQ name and not only if the sticky queue is set in the MS.
- Setting obsolete sticky queue can cause workflow tasks to go back to the previous build ID.
- The old code did not catch edge cases when a sticky queue of an older build ID wants to start a WFT when WF is already moved to a sticky queue on a newer build id.
For this to work properly, I'm assuming all the SDK versions that support versioning will set the task queue kind in poll request.
none.
No.

Fix flakiness in TestRedirectWithConcurrentActivities

---

components/callbacks/statemachine.go
components/callbacks/tasks.go
components/nexusoperations/executors.go
components/nexusoperations/executors_test.go
components/nexusoperations/fx.go
components/nexusoperations/statemachine.go
components/nexusoperations/statemachine_test.go
components/nexusoperations/tasks.go
tests/xdc/nexus_state_replication_test.go

- Fallback to endpoint name in task executor
- Fix metrics to use endpoint name instead of ID (regression from #6118)
- Signature of ClientProvider changed and no longer requires resolving the nexus endpoint
- Renamed `nexusoperations.InvocationTask.Destination` to `EndpointName`
- Renamed `nexusoperations.CancelationTask.Destination` to `EndpointName` 
A temporary workaround for not implementing endpoint replication, and endpoint ID being a UUID set by
the system, try to get the endpoint by name to support cases where an operator manually created an
endpoint with the same name in two replicas.
This practice is not recommended in production use cases and when replication is implemented, if endpoints are defined with the same name and different IDs and two replicas, they'll need to nuke …

Fallback to endpoint name in task executor

---

Makefile

Randomize the execution order of tests.
```
-shuffle off,on,N
Randomize the execution order of tests and benchmarks.
It is off by default. If -shuffle is set to on, then it will seed
the randomizer using the system clock. If -shuffle is set to an
integer N, then N will be used as the seed value. In both cases,
the seed will be reported for reproducibility.
```
Tests should be able to run in any order. Shuffling the test runs on every run uncovers these inter-test dependencies, if we have any. It's good testing hygiene. 
This can increase the number of flaky tests.

Shuffle tests

---

service/history/history_engine_test.go
service/history/tests/vars.go

- Speed up long poll tests
Before
```
--- PASS: TestEngineSuite (42.01s)
--- PASS: TestEngineSuite/TestGetMutableStateLongPoll (2.00s)
--- PASS: TestEngineSuite/TestGetMutableStateLongPollTimeout (20.00s)
--- PASS: TestEngineSuite/TestGetMutableStateLongPoll_CurrentBranchChanged (20.00s)
```
After
```
--- PASS: TestEngineSuite (3.01s)
--- PASS: TestEngineSuite/TestGetMutableStateLongPoll (1.00s)
--- PASS: TestEngineSuite/TestGetMutableStateLongPollTimeout (1.00s)
--- PASS: TestEngineSuite/TestGetMutableStateLongPoll_CurrentBranchChanged (1.01s)
```

Speed up long poll tests

---

components/nexusoperations/workflow/commands.go
components/nexusoperations/workflow/commands_test.go
service/history/api/respondworkflowtaskcompleted/api.go
service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler.go
service/history/workflow/command_handler.go
tests/sizelimit.go

When a workflow task is being acknowledged as completed by the history service, the payload size is validated. Previously, a payload size exceeding the limit would result in a workflow failure (usually indicating a failure from the application code). Now, payload size limit breaches result in workflow termination (indicating a failure originated from the service).
This helps customers delineate between failures originating from their application (via SDK call) and failures originating from the Temporal service/backend. 
- `make unit-test`. The [existing tests](https://github.com/temporalio/temporal/blob/main/service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler_test.go#L264-L268), which validate the correct failure messages are set from the handler, continues to …

terminate (instead of fail) workflows whose tasks fail to complete due to payload size limit breach

---

common/dynamicconfig/constants.go
service/history/api/signalwithstartworkflow/signal_with_start_workflow.go
service/history/api/startworkflow/api.go
service/history/api/workflow_id_dedup.go
service/history/api/workflow_id_dedup_test.go
service/history/configs/config.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_test.go

Make WorkflowIdReuseMinimalInterval to be per-namespace, rather then single global setting.
Also remove ContinueAsNewMinInterval setting (by reusing WorkflowIdReuseMinimalInterval setting).
This effectively makes ContinueAsNewMinInterval setting be per-namespace as well
To have more flexibility in configuring this setting.
Update unit-tests.
N/A
No

Change WorkflowIdReuseMinimalInterval setting to be per namespace

---

service/frontend/nexus_endpoint_client.go
tests/nexus_api_test.go
tests/nexus_endpoint_test.go
tests/nexus_workflow_test.go
tests/xdc/nexus_request_forwarding_test.go

Made the Nexus endpoint name validation regex more restrictive.
Bug

Fix Nexus endpoint name validation regex

---

common/cluster/frontend_http_client.go
common/config/config.go
common/membership/grpc_resolver.go
common/membership/grpc_resolver_test.go
common/membership/resolver.go
common/resource/fx.go
common/rpc.go
common/rpc/rpc.go
common/rpc/test/http_test.go
common/rpc/test/rpc_localstore_tls_test.go
components/callbacks/fx.go
components/nexusoperations/fx.go
internal/nettest/rpc_factory.go
tests/onebox.go

Fixed the mechanism to get a local frontend HTTP client to use a similar approach to getting a gRPC client.
Now we'll use a dedicated user provided config or default to membership lookup.
Added unit tests and ran existing functional tests.

Fix local frontend HTTP client creation

---

common/nexus/endpoint_registry.go
common/tqid/task_queue_id.go
service/matching/matching_engine.go
service/matching/matching_engine_test.go
service/matching/nexus_endpoint_client.go

For ListNexusEndpoints, in matching, check if node is ownership of the nexus endpoints table when a request comes in and abort polls if ownership is lost.
Faster feedback when membership changes.
Added unit tests and fixed existing tests.

Check ownership of nexus endpoints table in matching

---

service/history/replication/raw_task_converter.go
service/history/replication/raw_task_converter_test.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_test.go
tests/xdc/nexus_state_replication_test.go

- Drop SyncHSM task on conversion if there are buffered events
- Generate syncHSM task when clearing buffered events
- Can't sync HSM state when there are buffered events as states may depend on those events. Otherwise, later when those events are flushed and replicated, they can't be applied in the target cluster as the state has already been updated.
- Unit tests
- Functional test from @bergundy

Fix SyncHSM for buffered event case

---

common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go

Modifies gocql error handling introduced in https://github.com/temporalio/temporal/pull/4132 to avoid recreating the gocql session on transient connection errors. 
Recreating the session adds latency and isn't necessary when connections are closed or reset. 
Ran a prod-like workload and periodically restarted cassandra nodes. With the patch applied, we observed a reduction in p50 and p99 latency across persistence operations. For instance, here are p50 and p99 request latencies for `StartWorkflowExecution`. The patch was applied for cassandra restarts at 20:00 and then removed for cassandra restarts at 21:00. 
No
No

Avoid recreating gocql session on transient connection errors

---

components/nexusoperations/statemachine.go
service/history/hsm/tree.go
service/history/hsm/tree_test.go
service/history/workflow/task_generator.go
service/history/workflow/task_refresher.go

- Record SM task transition count on transition
- [Accept operation transition from backing off to started](https://github.com/temporalio/temporal/pull/6216/commits/bb1156ce8768fc4aa7523faacef7c9f523d4dd5a)
During replication, multiple event batches may be applied at a time, generating non-concurrent tasks with an invalid transition count.
Also accept the transition because state replication is lossy and we can't rely on the machine to transition to scheduled before started.
Yes.

Record SM task transition count on transition

---

Makefile
common/metrics/consts.go
common/metrics/defs.go
common/metrics/defs_base.debug.go
common/metrics/defs_base.go
common/metrics/registry.go

Added the build tag `debug` that builds the metric definition with the location of the metric definition.
Add `GetResisteredMetricsDefinitions` to the `debug` build tag to retrieve the metrics registry.

Add GetRegisteredMetricsDefinitions

---

components/nexusoperations/frontend/handler.go
service/frontend/nexus_handler.go

This is considered transient recoverable state and should only happen when there's race when resolving the namespace before forwarding the request.

Translate NamespaceNotActive error in nexus completion API to retryable unavailable error

---

service/history/history_engine.go
service/history/queue_factory_base.go
service/history/shard/context_testutil.go
service/history/tasks/task_category_registry.go
temporal/fx.go
temporal/fx_test.go
tests/test_cluster.go

There are some case when disabling nexus where outbound tasks will still be generated, we'd like to keep those tasks and avoid notifying the processor instead of the current behavior where the server would panic.
This also addresses a panic that could happen when enabling nexus on a running server.
Ran the server locally with continuous nexus load, disabled nexus via dynamic config, restarted the server, re-enabled nexus and checked that things are functioning properly.

Always register outbound category, make outbound processor registration conditional

---

common/dynamicconfig/constants.go
service/history/api/startworkflow/api.go
service/history/configs/config.go
service/history/tests/vars.go

- Add a feature flag for workflowIDReuse start time validation, default to **_disabled_**
- The start time validation introduces one more db read for start workflow operation. This can be avoided by adding the start time to workflow execution state.
- Also we should only get workflow start time when TerminateIfRunning policy is used.
- Existing functional test `TestStartWorkflowExecution_Terminate`
- Yes

Add feature flag for workflowIDReuse start time validation

---

common/dynamicconfig/constants.go
service/history/api/startworkflow/api.go
service/history/configs/config.go
service/history/tests/vars.go

- Add a feature flag for workflowIDReuse start time validation, default to **_disabled_**
- The start time validation introduces one more db read for start workflow operation. This can be avoided by adding the start time to workflow execution state.
- Also we should only get workflow start time when TerminateIfRunning policy is used.
- Existing functional test `TestStartWorkflowExecution_Terminate`
- Yes

Add feature flag for workflowIDReuse start time validation (#6231)

---

common/dynamicconfig/constants.go

Set `matching.backlogNegligibleAge` to five seconds by default to enable balanced partitions.
This config stop forwarding tasks and pollers once the backlog age in the child partition exceeds 5 seconds. By doing so we ensure that all partitions are treated equally when the task queue starts to accumulate backlog. It's expected that the backlog age difference among all partitions should stay around this 5 seconds value.
Feature already tests in prod.
None.
None.
No.

Enable balanced partitions by default

---

common/dynamicconfig/constants.go
common/metrics/metric_defs.go
common/nexus/endpoint_registry.go
common/nexus/endpoint_registry_test.go
components/nexusoperations/fx.go
service/frontend/fx.go

Add read-through cache for nexus endpoints by ID.
Note that this isn't done for getting an endpoint by name yet as it because that API is only used during command validation, where a cache miss it will fail a workflow task to automatically retried later.
Better testing experience.
Added a unit test.

Add readthrough cache for nexus endpoints by ID

---

common/testing/runtime/goroutine.go
tests/functional.go
tests/update_workflow.go

Fix flaky Workflow update functional tests.
It turned out that some tests don't complete updates and leave them hanging w/o asserting on result (result is not important for those tests). But this false unblocks `runtime.WaitGoRoutineWithFn` calls in other test earlier w/o waiting for specific updates reaching `WaitLifecycleStage` on server. I changed all tests to complete updates and added check to tear down function to validate that there is no "hanging" updates left.
This, unfortunately, means that tests that use `runtime.WaitGoRoutineWithFn` helper can't be run in parallel.
Run tests.

Fix flaky Workflow update functional tests

---

service/history/queues/executable.go
service/history/queues/executable_test.go

We have use cases (e.g. nexus) where we wrap errors to provide more context and we expect those errors to be non-retryable.
Using `errors.As` is also more idiomatic in Go.

Do not retry tasks that result in wrapped NotFound errors

---

service/history/queues/metrics.go

Prefix outbound task type tag value in metrics
It was missing the "Outbound" prefix that identifies that tasks as outbound tasks.

Prefix outbound task type tag value in metrics

---

tests/advanced_visibility.go
tests/functional_test_base.go
tests/namespace_delete.go
tests/test_cluster.go

Wait for ES to be ready when setting up the index
Wait for setup to complete internally instead of needing to wait in the test suite setup.

Wait for ES to be ready when setting up the index

---

cmd/tools/gendynamicconfig/main.go
common/dynamicconfig/collection.go
common/dynamicconfig/setting_gen.go

Inline slices representation constraint precedence in generated code.
This saves an allocation per dynamic config call.
Existing tests + bench.

Avoid allocation of dynamic config constraint precedence

---

common/dynamicconfig/constants.go
service/history/replication/stream_receiver.go
service/history/replication/stream_receiver_flow_controller_test.go
service/history/replication/stream_receiver_test.go
service/history/replication/stream_sender.go
service/history/replication/stream_sender_flow_controller.go

1. Add log for replication stream flow control
2. Change backpressure default threshold  from 50 to 500
1. To get more visibility when back pressure kicked in
2. To let back pressure happened less often
n/a
no risk, gated by a dc.
n/a
yes

Add logs when replication stream is paused due to flow control

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/outbound_queue_standby_task_executor.go

Wrap retryable errors from the outbound standby queue tasks with `DestinationDownError`.
`DestinationDownError` will trigger the circuit breaker, and minimizing discarding standby tasks prematurely.

[Outbound queue] Wrap retryable error from standby queue with DestinationDownError

---

service/history/api/updateworkflow/api.go
tests/update_workflow.go

Return previous Update result even if WF is already closed.
Closing https://github.com/temporalio/temporal/issues/6085
Added functional test.

Allow UpdateWorkflowExecution against a completed workflow

---

common/quotas/clocked_rate_limiter.go
common/quotas/dynamic_rate_limiter_impl.go
common/quotas/multi_rate_limiter_impl.go
common/quotas/rate_limiter.go
common/quotas/rate_limiter_impl.go
common/quotas/rate_limiter_mock.go

Add TokensAt() method to quotas.RateLimiter interface.
This method is useful to get the number of tokens that will be available at a future time point.
It is available in golang's rate.Limiter. We just have to expose it.
Unit tests
None
No

Add TokensAt method to quotas.RateLimiter interface

---

service/history/api/respondworkflowtaskcompleted/api.go

Uses the `Message()` method over `causeErr` directly in the workflow task completion handler.
`Message()` is used throughout, handles `nil` `causeErr`
`make test`

Use wtFailedCause.Message() over causeErr directly

---

tests/test_cluster.go

Allow up to 2 minutes for ES index to become yellow

---

common/cache/cache.go
common/cache/lru.go
common/cache/lru_test.go
service/history/api/respondworkflowtaskcompleted/api_test.go
service/history/api/verifyfirstworkflowtaskscheduled/api_test.go
service/history/history_engine2_test.go
service/history/history_engine3_eventsv2_test.go
service/history/history_engine_factory.go
service/history/history_engine_test.go
service/history/ndc/activity_state_replicator_test.go
service/history/ndc/hsm_state_replicator_test.go
service/history/ndc/transaction_manager_test.go
service/history/ndc/workflow_resetter_test.go
service/history/replication/ack_manager_test.go
service/history/shard/context.go
service/history/statemachine_environment_test.go
service/history/timer_queue_active_task_executor_test.go
service/history/timer_queue_standby_task_executor_test.go
service/history/transfer_queue_active_task_executor_test.go
service/history/transfer_queue_standby_task_executor_test.go
service/history/visibility_queue_task_executor_test.go
service/history/workflow/cache/cache.go
service/history/workflow/cache/cache_test.go
service/history/workflow/cache/export_testing.go

Adds two lifecycle callbacks for workflow cache: OnPut and OnEvict.
Prerequisite for https://github.com/temporalio/temporal/pull/6090
tl;dr We need to track workflow contexts per shard in order to clear them when the shard closes. This is the first step towards that goal.
No actual behavior change is introduced here yet. The callbacks have a new unit test.
No new behavior, therefore no risk expected.

Add lifecycle callbacks for workflow cache

---

tests/dynamicconfig.go

Disable frontend error masking in functional tests.
When test fails it is easier to debug if original error is logged/returned.
Run with some broken functionality and got original message.

Disable frontend error masking in functional tests

---

client/history/client_gen.go
cmd/tools/rpcwrappers/main.go
common/rpc/interceptor/namespace_validator.go
service/frontend/errors.go
service/frontend/workflow_handler.go
service/history/api/respondworkflowtaskcompleted/api.go
service/history/handler.go

Convert deserialization errors on task tokens to serviceerror.InvalidArgument. The error returned by the serializer is a raw proto error and should be translated before returning from rpc handlers.
more accurate metrics
didn't

Use NewInvalidArgument consistently for deserializing task token

---

docker/config_template.yaml

The bindOnIP values in the docker configuration template is wrapped with a string.
When attempting to listen on IPv6 in Docker without this change present, the colons in the IP address are interpreted as part of the YAML. The strings added allow IPv6 bind addresses to work properly.
I have not verified this change but I came across this issue when trying to configure Temporal for IPv6, and this fix is similar as for other projects I've come across.
The Temporal server docker image would be broken.
N/A
Yes

Escape BIND_ON_IP values for IPv6

---

common/rpc/interceptor/namespace_validator.go
common/rpc/interceptor/namespace_validator_test.go

allowed namespace states for describing mutable state of workflow.
In some cases, deleted namespaces may not have their resources cleaned up right away. In these cases, its still useful to allow a workflow under the deleted namespace to be described.
- Hardcode variable to delay namespace cleanup
- Create workspace
- Create worker/workflow
- Delete namespace
- Wait for cache to expire
- Describe workflow
No foreseeable risks. Preexisting protections against reading unauth/unauthz workflows still exists.
Documentation remains accurate
No

allow describe of workflow under deleted but existing namespace

---

common/metrics/metric_defs.go
go.mod
go.sum
service/history/api/describeworkflow/api.go
service/history/timer_queue_task_executor_base.go
tests/nexus_workflow_test.go

- Upgrade API to 1.36.0
- Upgrade Nexus SDK to 0.0.8
- Add more specific metric for state machine timer errors
- Expose Nexus operation scheduled event ID in workflow describe response
Prep for `1.25.0-rc.0` release

Nexus 117 prep

---

common/metrics/metric_defs.go
service/history/queues/metrics.go
service/history/timer_queue_active_task_executor.go
service/history/timer_queue_standby_task_executor.go
service/history/timer_queue_task_executor_base.go
service/history/timer_queue_task_executor_base_test.go

- Add `state_machine_timer_skips` metrics
- Fix `state_machine_timer_processing_failures` to be emitted on failures instead of skips

Fix state machine timer task metrics

---

common/dynamicconfig/collection.go
common/dynamicconfig/collection_test.go
common/dynamicconfig/file_based_client_test.go
common/dynamicconfig/fx.go
common/dynamicconfig/static_client.go
service/frontend/fx.go
service/frontend/workflow_handler_test.go
service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler_test.go
service/history/fx.go
service/matching/fx.go
service/worker/fx.go

- Use an explicit Start for dynamicconfig.Collection (in addition to Stop)
- Use fx hooks for Start/Stop
- Make it clear that StaticClient should be static
- Use thread-safe client in dynamic config unit tests
Fix thread-safety and cleanup
existing tests

Fix lifecycle for dynamicconfig Collection

---

service/matching/matching_engine.go
service/matching/matching_engine_test.go
service/matching/task_queue_partition_manager.go

If, while adding tasks, poller with a sticky queue failed because history service return "resource exhausted" error - move this task to backlog queue.
“Workflow is busy” is an resource exhausted error returned from history service
To reduce the pressure on history service if it is in busy state.
Add unit test to cover both cases.
N/A
N/A
No

move failed syncmatch tasks to the backlog

---

service/history/workflow/context.go

Refactored use of individual logging calls to use tagged loggers instead.
`logger` is passed down into the Update registry where we need every log line to be tagged with the Workflow ID, Run ID and Namespace ID.
Added test log lines and verified they are tagged correctly.
That `c.MutableState.GetExecutionInfo()` does not equal the workflow key.

Tagged logger for Update registry

---

service/history/api/respondworkflowtaskcompleted/api.go
service/history/workflow/mutable_state_impl.go
service/history/workflow/util.go

We [previously updated RespondWorkflowTaskCompleted](https://github.com/temporalio/temporal/pull/6180) to terminate on certain non-retryable errors (payload size exceeded) instead of fail. Termination indicates that the failure was sourced from the service, rather than the customer code/SDK. The change inadvertedly resulted in the wrong `CompletionEventBatchID` being written into mutable state, since both `failWorkflowTask` and `TerminateWorkflow` allocate a new event batch. `CompletionEventBatchID` should be set to the batch started in `failWorkflowTask`, but it was overridden from `TerminateWorkflow`. 
When replication to another cluster was involved, or the events cache is otherwise evicted, `MutableState.GetCompletionEvent()` was no longer able to load the failed event, as the …

Fix: RespondWorkflowTaskCompleted should the workflow termination event into the same event batch as the workflowtask failure event

---

service/history/ndc_task_util.go
service/history/tasks/utils.go
service/history/tasks/workflow_task_timer.go
service/history/workflow/cache/cache_test.go
service/history/workflow/context.go
service/history/workflow/mutable_state_impl.go
tests/update_workflow.go

Fix speculative WFT timeout task executor.
There was a bug when type of workflow task was determined from mutable state. This is wrong because when workflow context is cleared and mutable state is reloaded, speculative workflow task is lost but corresponding timeout timer task still can be executed. This PR fixes it twice:
1. on workflow context clear, in memory timeout task is also removed (if WFT is not there, there is nothing to timeout),
2. mutable state is never reloaded in timer task executor for speculative WFT.
Also fixed few minor logging issues found during investigation.
No risks.
No.
Maybe.

Fix speculative WFT timeout task executor

---

common/log/tag/tags.go
common/log/tag/zap_tag.go
common/namespace/replication_task_executor.go
components/scheduler/executors.go
service/history/api/respondworkflowtaskcompleted/api.go
service/history/api/respondworkflowtaskcompleted/api_test.go

Clear sticky task queue on speculative WFT error.
If, while completing WFT, error is occurred and returned to the worker then worker will clear its cache. New WFT will also be created on sticky task queue and sent to worker. Because worker doesn't have a workflow in cache, it needs to replay it from the beginning, but sticky WFT has only partial history. Worker will request full history using `GetWorkflowExecutionHistory` API. This history doesn't have speculative WFT events. If WFT is speculative, then worker will see inconsistency between history from it and full history, and will fail WFT.
To prevent unexpected WFT failure, server clears stickiness for this workflow, next WFT will go to normal task queue, and will have full history attached to it.
This is NOT 100% bulletproof solution …

Clear sticky task queue on speculative WFT error

---

service/history/api/updateworkflow/api.go
tests/update_workflow.go

Make sure that `WorkflowExecution` is set.
If the user sends an Update request to a closed Workflow and that Update was already complete earlier, the response is missing the `WorkflowExecution`.
Updated existing test.
Maybe.

Fix missing Workflow Execution on completed Update

---

service/history/api/get_workflow_util.go

Clone mutable state fields before returning them from `GetMutableState` internal API.
Result of `GetMutableState` is used outside of workflow lock and, therefore, all fields of it MUST be copied by value from `mutableState` fields.
No risks.
No.
No.

Clone mutable state fields before returning them from GetMutableState internal API

---

common/log/slog_test.go
common/log/zap_logger.go
common/log/zap_logger_test.go

We are now logging full file path in `logging-call-at` tags in log entries.
Currently it records just the file name which is not sufficient to identify the exact location where the logging is happening. There could be multiple files with same name (ex: api.go)
Ran the server and observed the log lines in console
+
unit tests
No

Include full file path in logging-call-at field

---

service/history/workflow/mutable_state_impl.go
service/history/workflow/mutable_state_impl_test.go

- Fix execution timer status carryover upon continueAsNew
- Basically use NewMutableStateInChain in AddContinutAsNewEvent
- This code path was missed in https://github.com/temporalio/temporal/pull/5588
- New unit test
- Yes.

Fix execution timer status carryover upon continueAsNew

---

service/history/replication/raw_task_converter.go

check replicationTask to avoid panic
In some cases, ConvertReplicationTask may return nil replicationTask. We need to check that when setting RawTaskInfo.

fix panic when replicationTask is nil

---

service/history/ndc_task_util.go
service/history/timer_queue_task_executor_base_test.go
service/history/transfer_queue_active_task_executor_test.go
tests/continue_as_new.go
tests/dynamicconfig.go

- Fix task generation validation: make sure runID matches before doing the validation 
- Note this is a stacked PR on top of https://github.com/temporalio/temporal/pull/6325
- Task generation is scoped to a run, while tasks can be across runs.
- Tested locally
- New functional test
- Yes

Fix task generation validation

---

common/api/metadata.go
common/api/metadata_test.go
common/rpc/interceptor/namespace_validator.go
common/rpc/interceptor/namespace_validator_test.go

Allow all `adminservice` APIs for namespace in `Deleted` state.
`adminservice` APIs mostly are used but `tdbg` tool, which might be used even for namespaces in `Deleted` state. For example, when delete failed and manual intervention is needed.
No risks.
No.
No.

Allow all adminservice APIs for namespace in Deleted state

---

common/deadlock/fx.go
common/dynamicconfig/constants.go
service/history/shard/context_impl.go

- Run checks every 60s instead of 30s.
- Increase grace period for shard lock and shard io semaphore checks.
These are a little too sensitive and can fire when persistence is slow for an extended time. The longer timeouts will still catch true deadlocks in a reasonable amount of time.
didn't

Reduce sensitivity of deadlock detector

---

common/persistence/visibility/store/elasticsearch/query_interceptors.go
common/persistence/visibility/store/elasticsearch/visibility_store.go
common/searchattribute/test_provider.go
service/frontend/workflow_handler.go
service/worker/scheduler/query.go
service/worker/scheduler/query_test.go

Set the base name interceptor for the query validation of ListSchedules.
Mapped custom search attributes need to be mapped for the query converter to work properly.

Fix ListSchedules query validation

---

develop/buf-breaking.sh

Fix buf-breaking script to account for already merged commit
Re-running GHA run-tests for old commits can fail if there are changes to proto files in main branch after the commit you're trying to test.

Fix buf-breaking script to account for already merged commit

---

common/dynamicconfig/constants.go
service/frontend/admin_handler.go
service/frontend/health_check.go
service/frontend/health_check_test.go
service/frontend/service.go

Add history deep health check into admin api
wire up admin deep health check with history deep health check
unit test

Add history deep health check into admin api

---

common/metrics/metric_defs.go
service/worker/scheduler/activities.go
service/worker/scheduler/workflow.go
service/worker/scheduler/workflow_test.go

1. Add new metric ScheduleActionAttempt. Increment it every time schedule is trying to start workflow.
2. Increment ScheduleActionErrors metric only if it is not WorkflowExecutionAlreadyStarted error.
If the user do multiple schedule starts for the same workflow, consecutive starts will fail because workflow already started. This is expected behavior. 
ScheduleActionErrors intention is to capture server error, and this is not a server error.
At the same time we may want to know how many actions user takes, thus new ScheduleActionAttempt metric was added.

Don't emit schedule metrics if workflow already running

---

service/history/replication/stream_sender.go

Add lock when sending replication task to stream
prevent concurrent send when multi-tiered processing stack enabled
n/a
no risk. feature is not enabled by default
n/a
yes.

Add lock when sending replication task to stream

---

common/dynamicconfig/constants.go
service/history/configs/config.go
service/history/outbound_queue_factory.go

Add `history.outboundQueuePendingTasksMaxCount` and `history.outboundQueuePendingTaskCriticalCount` dynamic configs.
The outbound queue runs tasks for multiple destinations with varying latency and availability. We may need more control over the number of pending tasks to prevent situations where tasks for unavailable destinations block tasks that should be okay to process.

Add outbound queue specific pending task limits

---

api/persistence/v1/executions.pb.go
common/persistence/cassandra/errors.go
common/persistence/cassandra/mutable_state_store.go
common/persistence/data_interfaces.go
common/persistence/sql/errors.go
common/primitives/timestamp/time.go
proto/internal/temporal/server/api/persistence/v1/executions.proto
service/history/api/startworkflow/api.go
service/history/history_engine2_test.go
service/history/workflow/mutable_state_impl.go
tests/admin.go

1. Populate StartTime filed when CurrentWorkflowConditionFailedError error happens
2. Use workflow start time from WorfklowExecutionState/CurrentWorkflowConditionFailedError (so avoid loading mutable state)
3. Add tests to verify that StartTime field in WorfklowExecutionState is populated
4. Refactor some dedup tests.
5. Mark StartTime in ExecutionInfo as deprecated.
To allow blocking frequent restarts without loading mutable state (and thus without latency increase)
Add some unit tests, modify existing unit tests.
No

Use start time to dedup executions start

---

common/dynamicconfig/collection.go
common/dynamicconfig/collection_test.go

Add mapstructure hook to parse enum names into values.
So we can use string enum names instead of integers in dynamic config, for enum-typed values.
unit test

Parse proto enums in dynamic config

---

common/persistence/cassandra/history_store.go
common/persistence/cassandra/metadata_store.go
common/persistence/cassandra/util.go
common/persistence/nosql/nosqlplugin/cassandra/gocql/batch.go
common/persistence/nosql/nosqlplugin/cassandra/gocql/interfaces.go
common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go

- Removed the existing unused interface `gocql.Batch`.
- Exported `gocql.batch`. This was the only implementation of the above interface.
- Fixed few references and types.
This interface was unused. i.e there were no other implementations other than `gocql.batch`. 
Existing tests
N/A
N/A
No

Remove gocql.Batch interface
