- service/history/replication/raw_task_converter.go
- service/history/replication/raw_task_converter_test.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- service/history/workflow/mutable_state_util.go
- Perform mutable state sanitization in source cluster during replication, instead in the target cluster.
- Any new, cluster specific fields added to mutable state can't be sanitized by the target cluster if target cluster is running an old version. But those unknown fields will still be persisted and decoded properly later when target cluster got upgraded. Then those new, cluster specific fields essentially bypassed sanitization and will cause bugs since the value is only valid within the cluster that generates the value. 
- Unit tests
> Source cluster mutable state sanitization

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/task_refresher.go
- Record task generation clock only when Nexus is enabled
- This is for preventing the task generation clock value get replication across clusters without being sanitized. 
If source cluster is new and recorded the value, but target cluster is old but doesn't know about this field, this unknown field could (during migration) be replicated and persisted in the target cluster. Even if we perform sanitization in the source cluster, it's still possible that during the deployment shard moves to an old host in the source cluster.  
- This new field is mainly for making sure Nexus can work properly, so we don't have to use it when nexus is disabled.
Now the upgrade/downgrade story looks like the following:
(Assuming we perform source cluster sanitization: …
> Record task generation clock only when Nexus is enabled

- common/clock/event_time_source.go
- common/clock/event_time_source_test.go
Updates the `NewTimer` logic in our clock testing package to ensure that the correct time is sent on a `Timer`'s channel, even after `Reset`
This is the behavior of `Timer` in the stdlib, so it matches expectations of users
Updated unit tests
None, this only affects tests
> Fix incorrect time sent on test Timer channel

- service/frontend/errors.go
- service/frontend/workflow_handler.go
Don't allow UpdateWorkflow request options `FirstExecutionRunId` and `WorkflowExecution.RunId` for MultiOperation.
Those Update options `FirstExecutionRunId` and `WorkflowExecution.RunId` don't make sense for Update-with-Start, as the RunID cannot be known as the caller doesn't know if a Workflow is actually running or not.
I intend to add a comment to the proto API, too.
> Don't allow RunID in Update MultiOperation

- common/util.go
- common/util_test.go
- service/history/replication/raw_task_converter.go
- service/history/workflow/mutable_state_impl.go
- Drop unknown fields when replicating workflow state
- This is to prevent a newly introduced, cell specific field got accidentally replicated to the target cluster after source cluster rolling back. 
- Unit test
> Drop unknown fields when replicating workflow state

- common/persistence/execution_manager.go
- common/persistence/tests/execution_mutable_state.go
- tests/cancel_workflow.go
Don't pass the `GetCurrentExecution` not found error up to non-persistence caller; use a custom error message instead.
Fixes https://github.com/temporalio/temporal/issues/4118
Added tests.
Breaks anyone checking for that exact string (which they shouldn't do).
> Fix workflow not found error message

- api/taskqueue/v1/message.pb.go
- proto/internal/temporal/server/api/taskqueue/v1/message.proto
- service/matching/task_queue_partition_manager.go
- service/matching/user_data_manager.go
- tests/versioning.go
When a query is forwarded to parent partition, allow the parent to chose build ID itself rather than using the one selected by child partition.
This fixes a race condition in which query comes to the child right after User Data is updated but before the child partition has the latest User Data. In that case child may select a stale build ID that no longer has workers. When forwarding the request to parent, we want to give the parent a second chance to fix the child's mistake.
This fixes the flakes in the following SDK test: https://github.com/temporalio/sdk-go/blob/master/test/worker_versioning_test.go#L885
Made sure the SDK test passes 10 consecutive times.
None.
None.
No.
> Evaluate versioning rules in parent partition for forwarded Queries and Nexus tasks

- common/testing/testvars/any.go
- tests/update_workflow.go
Add more test for different workflow completion commands.
Only `COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION` case was covered before. This PR adds `COMMAND_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION` and `COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION` cases which should behave exactly the same (in term of dealing with workflow updates). It also proves that besides very specific edge case described in #6375 workflow updates and "continue as new" work together as expected.
Run locally.
N/A
No.
No.
> Workflow Update: add more test for different workflow completion commands

- service/history/history_engine.go
Reduce noise when nexus is disabled. Tested by disabling nexus and grepping the output.
> Don't log an error when task processor isn't registered on shard reload

- common/dynamicconfig/constants.go
- common/rpc/interceptor/namespace.go
- common/rpc/interceptor/telemetry.go
- common/rpc/interceptor/telemetry_test.go
- components/nexusoperations/frontend/handler.go
- service/frontend/fx.go
- service/frontend/nexus_handler.go
- service/frontend/service.go
- service/history/configs/config.go
- service/history/fx.go
- service/history/history_engine_test.go
- service/matching/config.go
- service/matching/fx.go
Added namespace-filtered dynamic configuration that allows us to enable additional error logging for a specific set of namespaces to aid in investigatory work.
When investigating certain issues, additional request error logging is beneficial. Having the logging enabled at all times, however, is too noisy.
unit tests
> Knob for logging all rpc errors for a namespace

- service/matching/physical_task_queue_manager.go
- service/matching/physical_task_queue_manager_test.go
- tests/describe_task_queue.go
- tests/describe_task_queue2_test.go
- tests/functional_test_base.go
Fix the condition that checks for forwarded polls when tracking dispatched tasks. Previously, it was checking if the task is forwarded instead of checking if the poll is forwarded.
To calculate dispatch rate correctly.
Improved tests to validate stats for all combinations of poll and task being forwarded or not in combination with force or allow sync. Total 8 combinations.
None.
None.
No hotfix, but should be patched in 1.25 OSS release.
> Fix TQ dispatch rate for forwarded polls

- tests/reset_workflow.go
Refactored `testResetWorkflowSignalReapplyBuffer`. Using a few of the newer helper functions.
No behavior change.
Done as part of another PR that's not merged yet; might as well merge this now.
> Refactor reapply signal on reset test

- service/frontend/nexus_endpoint_client.go
- tests/functional_test_base.go
- tests/nexus_api_test.go
- tests/nexus_endpoint_test.go
- tests/nexus_workflow_test.go
- tests/xdc/nexus_request_forwarding_test.go
We realized during pre-release that users expect dashes rather than underscores and the new regexp would allow using endpoint names as host names if that use case comes up.
> Modify nexus endpoint name regexp to accept dashes instead of underscores

- service/frontend/errors.go
- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
Return a validation error when using `WorkflowStartDelay` option in MultiOperation Start.
The option is incompatible (ignored right now); this makes it explicit.
> WorkflowStartDelay is invalid for MultiOperation

- components/nexusoperations/statemachine.go
- tests/xdc/nexus_state_replication_test.go
Allow operation state machine to transition from CANCELED to CANCELED state.
Requesting to cancel an operation that wasn't started yet will transition the machine to canceled state immediately.
During replication the NEXUS_OPERATION_CANCELED event is applied in the CANCELED state and should be a no-op.
There's a discrepancy in the active and standby code paths at the moment but it's a bit tricky to unwind and doesn't seem critical enough to align those paths.
Added an XDC test.
> Fix replication of nexus operations that are canceled before started

- components/nexusoperations/config.go
We currently store sub state machines in mutable state's execution info which does not support partial updates.
The large update sizes are causing excess persistence load.
This restriction should be lifted when we change the persistence model.
> Limit nexus operation on a mutable state instance to 30

- common/metrics/metric_defs.go
- service/history/api/signalwithstartworkflow/signal_with_start_workflow.go
- service/history/api/signalwithstartworkflow/signal_with_start_workflow_test.go
- Emit metric and log when signalWithStart request skips workflow start delay
- Gather data before changing the signalWithStart behavior on existing workflow with start delay.
- Tested locally.
- N/A, only emitting metric and log
- N/A
- No
> Emit metric and log when signalWithStart request skips workflow start delay

- common/xdc/ndc_history_resender.go
- common/xdc/ndc_history_resender_test.go
- service/history/replication/eventhandler/resend_handler.go
- service/history/replication/eventhandler/resend_handler_test.go
Fix ndc resender batching logic when handling empty event version
Without this, event with empty version will be batched with events with other version
unit test
no risk.
n/a
yes
> Fix ndc Resender when history event has empty version

- service/matching/reachability.go
- service/matching/reachability_test.go
- service/matching/task_queue_partition_manager_test.go
- service/matching/version_rule_helper_test.go
- service/matching/version_rule_helpers.go
- service/matching/version_rule_test.go
- tests/versioning.go
- treat both rampPercentage=100 and ramp=nil as 'fully-ramped' assignment rule
- convert ramp=nil to rampPercentage=100 on insert and replace
- remove the references to "unconditional" and "conditional" assignment rules and just use the terms fully-ramped vs partially-ramped everywhere
- customers are confused by the requirement that a ramp percentage of 100 is not allowed
- having two terms for the same thing is confusing
> Consider rampPercentage=100 as 'fully-ramped' assignment rule

- service/history/transfer_queue_active_task_executor.go
- service/history/transfer_queue_active_task_executor_test.go
Propagating usermetadata to child workflow. This is a fix for https://github.com/temporalio/temporal/issues/6412
Currently the usermetadata is attached to the event that initiates the child workflow (`enumspb.EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_INITIATED`). But when we actually start the child workflow, we were not passing the user metadata object form this event in the parent to the child workflow. This is now fixed by passing the user metadata object in the child workflow creation request in the transfer task that creates child workflow.
Added unit test to ensure the user metadata object is passed in the start child workflow request.
N/A
N/A
No
> [UserMetadata] Copy metadata when creating child workflow

- service/history/workflow/cache/cache.go
Reduce log level of shard finalizer warning.
It's being logged more often than expected.
The reason why it's logging excessively isn't clear, so more investigation is needed. But this will mitigate the symptom for now.
Debug is not logged in production.
Yes.
> Reduce finalizer log level

- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/nexusoperations/link_converter.go
- components/nexusoperations/link_converter_test.go
- tests/nexus_api_test.go
- tests/nexus_workflow_test.go
Update nexus link converter
Sync with code in SDK.
> Update nexus link converter

- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/nexusoperations/statemachine.go
- components/nexusoperations/statemachine_test.go
- components/nexusoperations/tasks.go
- components/nexusoperations/workflow/commands_test.go
Changed the operation cancelation logic to not cancel the operation if the operation hasn't been started yet.
Before this change canceling an operation would add a NEXUS_OPERATION_CANCELED event and immediately transition to the `Canceled` state, which had issues with replication and buffered events. E.g. the `Started` event would be applied before the `CancelRequested` event on one cluster and then applied in reverse order when replicating to another cluster.
Example history batch taken from a test cluster contains these events:
```
EVENT_TYPE_WORKFLOW_TASK_COMPLETED
EVENT_TYPE_NEXUS_OPERATION_CANCEL_REQUESTED
EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED
EVENT_TYPE_NEXUS_OPERATION_STARTED // <-- this had to be buffered
EVENT_TYPE_WORKFLOW_TASK_SCHEDULED …
```
> Fix replication issues with nexus operations and cancelation requests

- common/dynamicconfig/constants.go
- common/predicates/and.go
- common/predicates/and_test.go
- common/predicates/empty.go
- common/predicates/not.go
- common/predicates/not_test.go
- common/predicates/or.go
- common/predicates/or_test.go
- common/predicates/predicates.go
- common/predicates/predicates_test.go
- common/predicates/universal.go
- service/history/archival_queue_factory.go
- service/history/configs/config.go
- service/history/outbound_queue_factory.go
- service/history/queues/queue_base.go
- service/history/queues/queue_base_test.go
- service/history/queues/reader.go
- service/history/queues/reader_test.go
- service/history/queues/scope.go
- service/history/queues/scope_test.go
- service/history/queues/slice.go
- service/history/queues/slice_test.go
- service/history/tasks/predicates.go
- service/history/tasks/predicates_test.go
- service/history/timer_queue_factory.go
- service/history/transfer_queue_factory.go
- service/history/visibility_queue_factory.go
Add dynamic config to limit multi-cursor predicate size.
There are two separate configs:
- `history.queueMaxPredicateSize` for all history queues except for the outbound queue - set to unlimited by default to avoid changing behavior
- `history.outboundQueueMaxPredicateSize` for the outbound queue - set to 10K by default
Limit the size of the shard info record. In stress test scenarios we've seen this record grow to over 10MB.
This should be applied to any server deployments enabling Nexus workloads.
> Add dynamic config to limit multi cursor predicate size

- tests/xdc/failover_test.go
- tests/xdc/user_data_replication_test.go
Removed some skips in xdc functional tests that were checking `UsingSQLAdvancedVisibility()`
We are always using advanced visibility now, so this flag is just for checking whether visibility persistence is SQL or ES, not for checking whether advanced visibility is being used at all.
XDC functional tests are only run using cass+es persistence, so these tests were never getting exercised.
> Unskip xdc tests expecting advanced visibility

- components/dummy/tasks.go
- components/nexusoperations/executors.go
- components/nexusoperations/tasks.go
- service/history/ndc_standby_task_util.go
- service/history/outbound_queue_standby_task_executor.go
- service/history/queues/executable.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
1. Fixed state machine timer standby executor to not discard validated concurrent tasks. The intent was that a validated task should be kept.
2. Fixed outbound standby executor logic that was supposed to wrap an `ErrTaskRetry` with a `DestinationDownError`. This also made the executor logic much easier to follow.
3. Moved `node.CheckRunning()` checks into the `task.Validate()` method for concurrent tasks so they can be discarded when the workflow is closed by the standby executors. (We need a similar check for non-concurrent tasks, I'll fix this in a refactor that gets rid of the concept of concurrent tasks).
4. Fix grammar in a log line when a task is skipped.
> State machine standby executor fixes

- client/history/client.go
Invalid Shard Owner Lost error in streaming
When SOL error returned, we should invalid the history client in replication stream.
> Invalid Shard Owner Lost error in streaming

- common/persistence/client/factory.go
Update namespace replication queue retry policy
The condition failure is due to concurrent write to namespace replication queue and we should retry on this one.
> Update namespace replication queue retry policy

- common/testing/testvars/any.go
- common/testing/testvars/test_vars.go
- service/history/api/respondworkflowtaskcompleted/api_test.go
- tests/update_workflow_sdk.go
Default `RunID` to empty string in `testvars` test utility package.
- Random values should come from `Any()` substruct
- Empty `RunID` is most common case and should be used by default.
- Setting `RunID` in SDK functional tests leads to data race.
Run tests.
> TestVars: default RunID to empty string

- common/testing/testvars/any.go
- common/testing/testvars/test_vars.go
- service/history/api/respondworkflowtaskcompleted/api_test.go
- service/history/workflow/update/state.go
- service/history/workflow/update/update.go
- service/history/workflow/update/update_test.go
- tests/update_workflow.go
- tests/update_workflow_sdk.go
Return Update outcome even if `ACCEPTED` stage was requested but Update was accepted and completed on the same WFT.
To provide better DX and return the most advanced reached stage.
Existing tests + added functional test.
No risks.
Server doc needs to be updated.
No.
> Workflow Update: return outcome if available, even if accepted was requested

- common/rpc/interceptor/telemetry.go
- service/history/ndc/resetter.go
- service/history/ndc/resetter_test.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_active_task_executor_test.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/timer_queue_task_executor_base.go
- service/history/timer_queue_task_executor_base_test.go
- service/history/workflow/mutable_state_impl.go
- tests/reset_workflow.go
* Add validation checks for workflow run timeout. 
* Add tests that will trigger workflow run timoeout to reprooduce "timeout after reset" problem
* Previous fix fixed only "execution timeout", 
* test didn't capture the case when workflow immediately ends after reset by run timeout (as opposite to execution timeout)
Add a functional test that verifies that negative scenario is triggered without a fix (workflow times out either by execution timeout or by run timeout without a fix)
No (?)
> Fix reset after timeout for workflow run timeout

- service/history/ndc/workflow_state_replicator.go
- service/history/ndc/workflow_state_replicator_test.go
When backfill history via sync workflow state replication task, it acquires the current run id lock to make sure no concurrent backfill on history. Add the optimization to reduce the locking scope to the same history tree.
We need this backfill history lock only for workflows share the same history tree. This only happens on reset workflows.
> Optimize locking on backfill history

- .github/workflows/run-tests.yml
- Makefile
- tests/xdc/base.go
- tests/xdc/nexus_request_forwarding_test.go
- tests/xdc/nexus_state_replication_test.go
* Increased eventually condition max wait times in `nexus_request_forwarding_test`
* Refactored the assertions in `waitForClusterConnected` to make sure it is not returning early
* Increased xdc test GHA timeout to 30 minutes to avoid GHA timeouts and to see which tests are taking too long (test timeout is 25m but if GHA times out first, we don't get any results)
To make the suite less flakey
Reran CI tests multiple times
Reran CI tests with shuffle seed that failed previously: `1725994791135537251`
> Fix Nexus xdc test flakiness

- common/testing/historyrequire/history_require.go
- service/history/ndc/events_reapplier.go
- service/history/ndc/events_reapplier_test.go
- service/history/ndc/workflow_resetter.go
- service/history/ndc/workflow_resetter_test.go
- service/history/workflow/update/registry.go
- tests/xdc/history_replication_signals_and_updates_test.go
Check completed Updates when reapplying Updates. Bug fix for #5833.
Internal Update registry map contains only admitted and accepted but not completed Updates. Previously `Contains` method (which btw breaks `update.Registry` abstraction) didn't check completed Updates.
Added functional test.
No risks.
No.
No.
> Workflow Update: check completed Updates when reappyling Updates

- service/history/replication/stream_receiver_monitor.go
1. move panic capture to inside of monitor loop, so check can be retried after panic
2. Check low priority even if high priority stuck
Improve stability of monitor loop
unit test
n/a
n/a
no
> Replication stack monitor to check both high priority and low priority queue

- .github/workflows/run-tests.yml
- tests/xdc/advanced_visibility_test.go
- tests/xdc/base.go
- tests/xdc/stream_based_replication_test.go
Fix xdc test timeout failures by ensure test clusters are connected and synced before operations.
If clusters are not connected or not synced yet, replication tasks will not be synced to target cluster. So if there is any check waiting for the specific replication task, the check will stuck.
reran tests.
> fix xdc test timeout failures

- internal/temporalite/lite_server.go
- schema/sqlite/setup.go
Add search attributes param to sqlite.NewNamespaceConfig.
Ability to start Temporal from the CLI with custom search attributes.
Address https://github.com/temporalio/temporal/issues/6195
Modified the CLI to not call `registerSearchAttributes`, pass it directly to `NewNamespaceConfig`.
> Add search attributes param to sqlite.NewNamespaceConfig

- common/persistence/sql/sqlplugin/db_handle.go
Fixes #6514 
I fixed a bug in our sql `DBHandle` that could cause us to never reconnect to the database when an issue occurs.
We should only update the last refresh time when we actually refresh. As written we always update the last refresh time even when we don't refresh.
If _every_ attempt to reconnect happens within
`sessionRefreshMinInterval` of the last attempt, the server will _never_ actually reconnect as it will just keep bumping the last refresh...
Existing tests
None
No changes
Absolutely (cc @yiminc)
> sql: Only update last refresh time when we refresh

- go.mod
- go.sum
Pick up PR https://github.com/dgryski/go-farm/pull/21
Fixes bug that could cause crashes (potential crash sites are actually in ringpop but this version will be used).
See linked PR for more details.
Existing tests
> Update go-farm dependency to pick up bug fix

- tests/ndc/ndc_test.go
- tests/ndc/replication_migration_back_test.go
- tests/ndc/replication_task_batching_test.go
Fix `replicationspb` import name in tests
consistent naming
> Fix replicationspb import name in tests

- common/collection/sync_map.go
Change SyncMap.PopAll to clone+clear the contained map instead of creating a new one.
Swapping the map makes SyncMap not copyable, and it's intended to be copyable (like a regular map reference).
existing test
> Fix SyncMap.PopAll if SyncMap is copied

- common/collection/sync_map_test.go
I realized it's easy to make a test for #6557 without direct access to compare m.contents.
prevent regressions
> Add test for #6557

- common/enums/defaults.go
- tests/reset_workflow.go
- tests/xdc/history_replication_signals_and_updates_test.go
Change default `ResetReapply` enum value to `ALL_ELIGIBLE`.
Reverts temporalio/temporal#5688, i.e. after this PR we will have the behavior described in https://github.com/temporalio/temporal/pull/5360. This means both signals *and* updates will be reapplied by default during resets and coinflict resolution, which is the product behavior we want.
- #5360 attempted to introduce a new proto enum value and start using it as the default
- However, that is not a valid single-deploy change, since it can cause a frontend client on the new version to send a value that is unknown to a history node on the old version.
- Therefore #5688 reverted the change to the default, allowing the new proto enum value to be introduced to the codebase
- This PR is deployable iff all clusters that we deploy to have …
> Revert "Revert change to default reapply type"

- client/client_bean.go
- client/client_bean_mock.go
- tests/onebox.go
- ClientBean no longer eagerly establishes connections on creation. These connections get immediately deleted by the cluster metadata callback that's registered right after. They'll be created on-demand very soon anyway.
- Remove SetRemoteAdminClient and have functional tests interpose mock admin clients through the client factory instead of mutating maps in ClientBean. This is more reliable since connections get added/removed from the maps.
More reliable tests
existing tests
> Clean up client bean + mock admin clients in functional tests

- common/dynamicconfig/memory_client.go
- common/dynamicconfig/memory_client_test.go
- tests/functional_test_base.go
- tests/namespace_delete.go
- tests/onebox.go
- tests/schedule.go
- tests/test_cluster.go
- tests/update_workflow.go
- tests/xdc/nexus_request_forwarding_test.go
- dynamicconfig.MemoryClient.OverrideValue now returns a cleanup function to undo the override.
- There is no more RemoveOverride.
- Refactor some functional test code to use cleanup functions.
temporalImpl.overrideDynamicConfigByKey tried to undo the override it made, but if other code called RemoveOverride, things would get confused. Also, it was annoying to remove overrides in the middle of a test.
The new implementation of overrides is a list of pairs instead of a map, so they're clearly ordered. Removing one clears just that one, but later ones would still take effect.
existing tests + new test
> Improve dynamic config memory client removing overrides

- go.mod
retract v1.26.0 and v1.26.1
v1.26.0 was accidentally published. v1.26.1 retracts that version and itself.
N/A
no
no
no
> retract v1.26.0 and v1.26.1 in all future versions

- components/callbacks/executors.go
- tests/callbacks_test.go
Callback last attempt complete time was not being set on success, this fixes that:
> Fix callback last attempt complete time not being set on success

- common/nexus/endpoint_registry.go
- common/nexus/endpoint_registry_test.go
Correctly handle a sequence of enable, disable, enable in nexus endpoint registry without double-close on the ready channel.
avoid crash
new unit test
> Fix enable/disable in nexus endpoint registry

- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
- service/matching/matching_engine_test.go
- ShutdownWorker is implemented in FrontendService by forwarding to `ForceUnloadTaskQueue` in Matching.
- Will be used by workers to indicate their sticky queue is no longer being polled
- new test
- new API that exposes `ForceUnloadTaskQueue`. If callers were to abuse the operation, they could force history being reloaded as the sticky queue is cleared.
- New docs on the API
- No
> ShutdownWorker frontend implementation

- service/worker/batcher/fx.go
- service/worker/common/interface.go
- service/worker/common/interface_mock.go
- service/worker/pernamespaceworker.go
- service/worker/scheduler/fx.go
- tests/schedule.go
- Use dynamic config subscription for `schedulerNamespaceStartWorkflowRPS`.
- Simplify test that uses it.
Faster reaction to changing rate limit and can simplify test.
updated functional test
> Subscription for schedulerNamespaceStartWorkflowRPS

- common/metrics/metricstest/task_queues_test.go
- common/metrics/task_queues.go
- common/tqid/task_queue_id.go
- service/history/api/recordactivitytaskstarted/api.go
- service/history/api/recordworkflowtaskstarted/api.go
- service/matching/handler.go
- service/matching/matching_engine.go
- service/matching/task_queue_partition_manager.go
Refactored code to emit the same number of tags in the task_schedule_to_start_latency metric.
Previously we were using both GetPerTaskQueueFamilyScope and GetPerTaskQueuePartitionScope for the same metric, now we only use GetPerTaskQueuePartitionTypeScope.
None.
None.
No.
> Consistent tags for `task_schedule_to_start_latency` metric

- service/history/workflow/mutable_state_impl.go
Populate StartTime in mutable state execution info
We cannot delete from there yet: downgrade breaks.
Start with change, and downgrade temporal works as it should.
> Fix write start time to execution info

- docs/architecture/in-memory-queue.md
- docs/architecture/message-protocol.md
- docs/architecture/speculative-workflow-task.md
Edited remaining Update Workflow docs not already covered by https://github.com/temporalio/temporal/pull/6486.
> Update Workflow docs editing

- tools/tdbg/commands.go
- tools/tdbg/decode_commands.go
`tdbg`: fallback to encode history to text if JSON encoding failed.
Under some weird circumstances JSON encoding might not work but it is still useful to see as much data as we can. Text marshaling seems always work.
Run `tdbg` for problematic blobs with wrong durations.
No risks.
No.
No.
> tdbg: fallback to encode history to text if JSON encoding failed

- common/persistence/visibility/store/elasticsearch/client/client_v7.go
Remove track_total_hits from Scroll API
`track_total_hits` cannot be disable in Scroll API.
Issue: https://github.com/temporalio/temporal/issues/6566
> Remove track_total_hits from Scroll API

- tools/tdbg/commands.go
- tools/tdbg/commands_test.go
Fix tdbg `getCategory` to be case insensitive.
> Fix tdbg getCategory to be case insensitive

- service/history/replication/raw_task_converter.go
- service/history/replication/raw_task_converter_test.go
- service/history/replication/sync_state_retriever.go
- service/history/replication/sync_state_retriever_mock.go
Fix raw_task_converter lock usage when converting sync versioned transition task
Not holding the lock when doing io for reading history events from cache
unit test
no risk. Feature not enabled.
no.
no
> Fix raw_task_converter lock

- common/persistence/persistence_metric_clients.go
- common/util/error_type.go
Add special handling for `context.Canceled` and `context.DeadlineExceeded` error types.
When logging or emitting metrics, `errors.errorString` error type is not useful. Changing `context.deadlineExceededError` to `context.DeadlineExceeded` also for consistency.
No risks.
No.
No.
> Add special handling for context.Canceled and context.DeadlineExceeded error types

- common/nexus/failure.go
Map gRPC Canceled to Nexus HandlerError Internal.
Ensure that requests that end up canceled get retried.
Tested manually by forcing history service to return a Canceled error.
> Treat gRPC Canceled code as retryable when converted to a nexus handler error

- service/matching/matcher_test.go
- Fixes flaky `MatcherTestSuite/TestForwardingWhenBacklogIsYoung`
- I noticed this unit test was flaking by running the test about 3000 times.
- This was happening because it was not using proper synchronization to ensure that poller and consumer forwarding was done. (tldr - the existing `time.sleep` were not sufficient sometimes which is why the test was throwing errors)
- To resolve flakiness. 
- I ran the modified test 30000 times and it passed.
None
I don't think so, since this is a unit test.
> Fix flaky test: TestForwardingWhenBacklogIsYoung

- common/nexus/payload_serializer.go
- common/nexus/payload_serializer_test.go
- common/testing/mocksdk/worker_mock.go
- go.mod
- go.sum
- service/history/workflow/mutable_state_impl.go
- tests/nexus/nexus_workflow_test.go
Improve conversion of payloads with empty metadata and nil workflow results to Nexus Content.
NOTE: This also upgrades the Go SDK from 1.27.0 to 1.29.1 to test Nexus via the SDK.
Handle a couple of edge cases that weren't properly handled before.
The fix in `mutable_state_impl.go` is the more critical one and may cause surprising behavior in the SDKs.
Added tests.
> Nexus: Better handling of nil and empty payloads

- tests/advanced_visibility_test.go
- tests/namespace_delete_test.go
- tests/namespace_interceptor_test.go
- tests/nexus_api_test.go
- tests/nexus_endpoint_test.go
- tests/nexus_test_base.go
- tests/nexus_workflow_test.go
- tests/reset_workflow_test.go
- tests/update_workflow_sdk_test.go
- tests/update_workflow_suite_base.go
- tests/update_workflow_test.go
- tests/workflow_visibility_test.go
Moved all functional test files into a single `testa` folder/package.
Tooling problem. `go` doesn't allow to control the overall level of parallelism. It has separate options for "number of packages in parallel" and "number of parallel tests in each package".
> Move all functional tests into the same folder

- common/dynamicconfig/constants.go
- service/frontend/service.go
- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
Add validation for both link size and number of links per request.
Also refactored `workflow_handler_test.go` so a single test can be executed at a time and removed the use of `pborman/uuid` in this file.
Accepting unbounded inputs is a security risk.
Unit tests.
> Add validation for links on StartWorkflowExecution request

- tests/nexus_workflow_test.go
Fix one of the nexus func tests.
Something changed in the format of the error message. As the result test start failing.
No
> fix failing nexus func test

- components/callbacks/executors.go
This error check was redundant as it was already handled prior to the block, improving readability and maintaining clean, efficient error handling.
This error check was redundant as it was already handled prior to the block, improving readability and maintaining clean, efficient error handling.
Tested locally with existing unit tests to ensure the task executor continues functioning as expected without introducing new errors.
There is a minimal risk of breaking error handling logic in taskExecutor, though the changes are straightforward and should have no functional impact.
No updates required in documentation, as this is an internal refactor that does not affect behavior or interfaces.
No, this is not a hotfix candidate.
> Refactor: Remove redundant error check in task executor in executors.go

- Makefile
- tests/acquire_shard_test.go
- tests/describe_task_queue_test.go
- tests/http_api_test.go
- tests/max_buffered_event_test.go
- tests/update_workflow_sdk_test.go
- tests/versioning_test.go
- tests/workflow_test.go
- tests/xdc/failover_test.go
- tests/xdc/history_replication_signals_and_updates_test.go
- tests/xdc/nexus_state_replication_test.go
Skipped all known flaky tests.
```
go.temporal.io/server/tests TestVersioningFunctionalSuite/TestDispatchChildWorkflow
go.temporal.io/server/tests TestWorkflowTestSuite/TestWorkflowTaskAndActivityTaskTimeoutsWorkflow
go.temporal.io/server/tests TestVersioningFunctionalSuite/TestDispatchCron
go.temporal.io/server/tests TestHttpApiTestSuite/TestHTTPAPIHeaders
go.temporal.io/server/tests TestVersioningFunctionalSuite/TestDispatchActivityFailOld
go.temporal.io/server/tests/xdc TestNexusStateReplicationTestSuite/TestNexusOperationEventsReplicated
go.temporal.io/server/tests TestVersioningFunctionalSuite/TestDispatchActivityTimeoutOld
go.temporal.io/server/tests TestVersioningFunctionalSuite/TestDispatchContinueAsNewUpgrade
go.temporal.io/server/tests …
```
> Skip all known flaky tests

- service/history/timer_queue_active_task_executor.go
- tests/update_workflow_sdk_test.go
Fix abort updates if workflow is timed out.
`executeWorkflowRunTimeoutTask` handler has 2 successful exit points: when there is no new run created and when there is a new run. Previously updates were aborted only in 2nd case and with wrong error. Non retryable `AbortReasonWorkflowCompleted` should be used when there is no new run is created and `AbortReasonWorkflowContinuing` where there is new run. In this case admitted updates will be retried on new run.
Added new functional tests.
No risks.
No.
No, bug impact should be very small and timeout update on timed out workflow is not too bad experience.
> Workflow Update: fix abort updates if workflow is timed out

- components/nexusoperations/events.go
- components/nexusoperations/events_test.go
- service/history/api/resetworkflow/api.go
- service/history/api/resetworkflow/api_test.go
- service/history/hsm/events.go
- service/history/ndc/workflow_resetter.go
- service/history/ndc/workflow_resetter_mock.go
- service/history/ndc/workflow_resetter_test.go
- tests/reset_workflow_test.go
replacing `map[enumspb.ResetReapplyExcludeType]bool` with `map[enumspb.ResetReapplyExcludeType]struct{}`
- Small space saving
- More conventional Go.
N/A
N/A
No
> Nit: map<struct> instead of map<bool>

- tests/nexus_workflow_test.go
Fixed variable name.
Readability
Compile
N/A
N/A
No
> nit: fix variable name

- tests/reset_workflow_test.go
Fixing the bug introduced in https://github.com/temporalio/temporal/pull/6639. I had missed the negations.
Tests are broken.
Ran the tests in `tests/reset_workflow_test.go` locally and ensured they all run fine.
N/A
> Fix broken tests from https://github.com/temporalio/temporal/pull/6639

- service/history/deletemanager/delete_manager.go
- service/history/workflow/fx.go
- service/history/workflow/task_generator_provider.go
- temporal/fx.go
- tests/testcore/onebox.go
This is based on @yycptt's idea:
Only do write on global taskGeneratorProvider if non-default.
Provide the default TaskGeneratorProvider (it can be overridden with fx.Decorate).
This allows multiple independent servers to run in the same process without tripping the race detector, e.g. for integration testing, as long as the implementation is not overridden.
existing tests
> Refactor global taskGeneratorProvider to avoid races

- .github/workflows/run-tests.yml
Run Test Status job always
Our PRs are gated on this job passing. When it was not running always, it was possible to merge a PR with broken tests.
> Run test-status always

- service/history/api/get_workflow_util.go
Add consistency check on mutable state when long poll history
The long pull request can reach a stale shard and the version history won't be compatible.
> Add consistency check on mutable state when long poll history

- service/matching/matcher.go
- service/matching/matcher_test.go
- Try to make TestAvoidForwardingWhenBacklogIsOld less flaky
- Add TestAvoidForwardingWhenBacklogIsOldButReconsider to check the "reconsider forwarding after waiting for a poll" behavior.
Less flaky tests
ran them a lot
> Fix flaky TestAvoidForwardingWhenBacklogIsOld and add new test

- tests/update_workflow_sdk_test.go
Fix functional tests flakiness by waiting for history to get to specific state before moving forward.
Flakiness is bad. Follow up to #6621.
Run tests 100 times with
```
go test -run ^TestUpdateWorkflowSdkSuite$ -count=100
```
Some flakiness sources are still there. `historyrequire` package needs to be improvement to address it.
No.
No.
> Workflow Update: fix functional tests flakiness

- Makefile
upgrade golangci-lint to v1.60.3
Panic when `make check`:
```
make check
Check license header...
Downloading github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1
Linting code...
INFO golangci-lint has version v1.59.1 built with go1.23.2 from (unknown, modified: ?, mod sum: "h1:CRRLu1JbhK5avLABFJ/OHVSQ0Ie5c4ulsOId1h3TTks=") on (unknown) 
INFO [config_reader] Used config file .golangci.yml 
WARN [lintersdb] The name "goerr113" is deprecated. The linter has been renamed to: err113. 
WARN [lintersdb] The name "vet" is deprecated. The linter has been renamed to: govet. 
INFO [lintersdb] Active 9 linters: [err113 errcheck exhaustive forbidigo godox goimports govet revive staticcheck] 
INFO [loader] Go packages loading at mode 575 …
```
> upgrade golangci-lint to avoid panic

- .github/workflows/run-tests.yml
- Makefile
- service/matching/backlog_manager_test.go
- tests/update_workflow_sdk_test.go
- tests/versioning_test.go
Follow up to #6634, the following tests are still flaky:
```
TestVersioningFunctionalSuite/TestDispatchRetry
TestUpdateWorkflowSdkSuite/TestUpdateWorkflow_TimeoutWorkflowAfterUpdateAccepted
```
Also increased XDC timeout to 40 minutes since those tests occasionally time out.
> Disable more flaky tests

- components/callbacks/tasks.go
- components/dummy/tasks.go
- components/nexusoperations/executors.go
- components/nexusoperations/tasks.go
- components/scheduler/executors.go
- components/scheduler/tasks.go
- service/history/hsm/executor.go
- service/history/hsm/hsmtest/task.go
- service/history/hsm/registry.go
- service/history/hsm/tasks.go
- service/history/outbound_queue_factory.go
- service/history/outbound_queue_standby_task_executor.go
- service/history/statemachine_environment.go
- service/history/statemachine_environment_test.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/timer_queue_task_executor_base.go
- service/history/workflow/task_generator.go
- service/history/workflow/task_generator_test.go
Remove the `Concurrent` method from the `hsm.Task` interface in favor of a `Validate` function for every task.
After gaining experience with the framework and internal discussions, we decided this approach is easier to grasp and makes eliminates the need to sanitize fields from the task when generating refs for RPCs.
> Remove concept of concurrent HSM tasks

- common/metrics/metrics.go
- common/metrics/metrics_mock.go
- common/metrics/metricstest/capture_handler.go
- common/metrics/noop_impl.go
- common/metrics/otel_metrics_handler.go
- common/metrics/tally_metrics_handler.go
- service/history/historybuilder/history_builder_categorization_test.go
- service/history/workflow/metrics.go
Extend metrics.Handler interface to include a batching feature which enables implementations to send "wide events". Batch the mutable state metrics.
Send a single metrics "event" where possible rather than several.
Unit tests.
None expected.
Nothing in `docs/` to update. Release notes to come.
No
> Batch Mutable State Metrics

- .github/workflows/run-tests.yml
- Makefile
- Change CI order to pre-build in one step, and let other functional tests depend only on that (instead of all of misc checks)
- Do manual caching of Go dependencies and build products so later steps can share results of earlier steps, and the overall cache size is much smaller
- Start dependencies earlier in job to hopefully be more stable
- Make test timeout tighter since they run faster now
Shorten critical path, speed up CI
> Only pre-build functional tests and use per-build cache

- tests/schedule_test.go
- Extend timeouts on some schedule functional tests
- Allow ListSchedules to return extra schedules instead of exactly 1
- Clean up with t.Cleanup()
less flaky tests
> Clean up schedule functional tests and extend timeouts

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
sync all activities when disabling state-based replication
We may dropped some tasks before disabling state-based replication. So when disabling always needs to sync all activities.
unit tests.
> sync all activities when disabling state-based replication

- develop/github/docker-compose.yml
Run cassandra with smaller heap (2GB) in CI. Default (on standard GHA workers) comes out to 4GB, so this is 1/2 of what it was before.
Try to reduce CI flakiness.
> Reduce cassandra heap size in CI

- .github/workflows/run-tests.yml
This PR causes our CI test runs to upload the test output, containing junit XML, as GitHub artifacts.
The motivation for doing this is that it opens the way to using junit XMLs to study test result history, for example to identify tests whose failure patterns indicate that they are flaky. It also allows people to develop alternative ways to view test results, and to study test times to find slow tests, etc.
> Upload test results as GitHub Actions artifacts

- common/testing/historyrequire/history_require.go
- common/testing/historyrequire/history_require_test.go
- tests/testcore/functional_test_base.go
- tests/update_workflow_sdk_test.go
- tests/xdc/advanced_visibility_test.go
- tests/xdc/failover_test.go
- tests/xdc/history_replication_signals_and_updates_test.go
Improve `historyrequire` test helper. Added:
```go
EqualHistoryEventsSuffix()
EqualHistoryEventsPrefix()
ContainsHistoryEvents()
WaitForHistoryEvents()
WaitForHistoryEventsSuffix()
```
and corresponding `History` functions.
To support this (especially `*Suffix` functions), I had to make `EventID` field optional. And to differentiate between `EventID` and `Version` I had to prefix version with `v`. This are valid histories to require:
```
1 v1 WorkflowExecutionStarted
2 v1 WorkflowTaskScheduled
3 v1 WorkflowTaskStarted
v1 WorkflowExecutionStarted
v1 WorkflowTaskScheduled
v1 WorkflowTaskStarted
1 WorkflowExecutionStarted
2 WorkflowTaskScheduled
3 WorkflowTaskStarted
WorkflowExecutionStarted
WorkflowTaskScheduled
WorkflowTaskStarted
```
Also used it in few places to fight with test falkines. …
> Improve historyrequire test helper

- tests/nexus_workflow_test.go
`require` makes tests panic in eventually blocks.
> nexus_workflow_test: Use assert instead of require in EventuallyWithT blocks

- docs/architecture/workflow-update.md
- service/history/workflow/update/abort_reason.go
- service/history/workflow/update/abort_reason_test.go
- service/history/workflow/update/errors_failures.go
- service/history/workflow/update/registry_test.go
- service/history/workflow/update/update.go
- service/history/workflow/update/update_test.go
- tests/update_workflow_sdk_test.go
- tests/update_workflow_test.go
Abort updates with failure if update was accepted but workflow completes.
Accepted Updates are failed with special server failure because if a client knows that Update has been accepted, it expects any following requests to return an Update result (or failure) but not an error. There can be different types of Update failures coming from worker and a client must handle them anyway. It is easier and less error-prone for a client to handle only Update failures instead of both failures and not obvious `NotFound` errors in case if the Workflow completes before the Update completes.
It is some sort of breaking change for very narrow case though.
TBD
No.
> Workflow Update: abort updates with failure if update was accepted but workflow completes

- go.mod
WISOTT
PS: base-builder is already 1.23.2 (see [link](https://github.com/temporalio/docker-builds/blob/ca17b250c72eb42018855c13d59588fb7229c4f4/docker/base-images/base-builder.Dockerfile#L4))
PPS: other docker-build jobs use this project's `go.mod` to install the correct Go version (see [search](https://github.com/search?q=repo%3Atemporalio%2Fdocker-builds%20go.mod&type=code))
PPPS: same for goreleaser (see [link](https://github.com/temporalio/temporal/blob/main/.github/workflows/goreleaser.yml#L23))
Security.
> Bump Go to 1.23.2

- components/nexusoperations/executors.go
Remove `MachineTransitionCount` from the state machine reference in the Nexus completion token because older server versions use it to verify that the ref is valid only if the state machine hasn't transitioned since the ref was generated.
> Fix Nexus completion token to be compatible with older server versions

- common/testing/testvars/test_vars.go
- tests/update_workflow_suite_base.go
- tests/xdc/history_replication_signals_and_updates_test.go
Fix flaky `TestHistoryReplicationSignalsAndUpdatesTestSuite`.
Tests were flaky because WFT poller didn't wait for Update to reach the server and might poll for WFT w/o Update request message.
Run. And they passed here 3 times. There might be some other flakes though.
No risks.
No.
No.
> Fix flaky TestHistoryReplicationSignalsAndUpdatesTestSuite

- service/matching/matcher_test.go
- tests/describe_task_queue_test.go
- tests/http_api_test.go
- tests/max_buffered_event_test.go
- tests/versioning_test.go
- tests/workflow_test.go
- tests/xdc/failover_test.go
- tests/xdc/history_replication_signals_and_updates_test.go
- tests/xdc/nexus_state_replication_test.go
Reenabled all tests marked with `Skip("flaky test")`.
To get the coverage back. Now that #6668 is merged we should hopefully be less affected by these flakes.
> Reenable flaky tests

- components/nexusoperations/workflow/commands.go
- components/nexusoperations/workflow/commands_test.go
More intuitive experience and consistent with activities.
Unit test.
> Ignore RequestCancelNexusOperation commands if operation completion is buffered

- .github/workflows/run-tests.yml
Also increased retention to 28 days.
Avoid strict version pinning so we can get updates and bug fixes.
> Use latest minor of actions/upload-artifact@v4

- service/history/shard/context_impl.go
Remove emitting history_size metric without namespace tag.
This was causing metrics tag inconsistency. In all other places, we include namespace tag for this metric.
No
> Fix metrics tag for history_size

- components/nexusoperations/frontend/handler.go
- service/frontend/nexus_handler.go
Add namespace tag to metricsHandlerForInterceptors in nexus operationContext and requestContext.
TelemetryInterceptor.RecordLatencyMetrics() is called with this metrics handler. In all other places, metrics handler passed to this function has namespace tag.
No
> Fix metrics tag inconsistency in nexus handler

- service/history/replication/executable_task.go
- service/history/replication/task_executor.go
Add NamespaceTag and ServiceRoleTag when emitting ClientRequests and ClientLatency from replication task executor. We include these tags when we emit these metrics from other places. Prometheus does not support this tag inconsistency.
To fix tag inconsistency.
No
> Fix metrics tag inconsistency in replication task executor

- service/history/api/multioperation/api.go
- tests/update_workflow_test.go
- tests/workflow_test.go
MutableState is assigned to the workflow context to prevent it from re-initializing later in task processing.
Polling for an Update result from an Update-with-Start returned a NotFound error.
This is due to inconsistent use of MutableState: the worker responses in task processing uses a different MutableState than the poll request from the user. There was no problem while the update was in the registry, but once it completed and is transferred to MS, the inconsistency was observable by the user when polling.
Added new tests.
Yes.
> Fix Update-with-Start poll of completed Update

- service/history/ndc_task_util.go
- service/history/queues/metrics.go
- service/history/timer_queue_active_task_executor.go
Add NamespaceTag and TaskTypeTag to task_skipped metric. These two tags are emitted from executable.go. This is causing a metrics tag inconsistency during namespace handover.
Fix metrics tag inconsistency.
None
> Fix task_skipped metrics tag inconsistency

- service/history/api/multioperation/api.go
- tests/update_workflow_test.go
Fixes Update-with-Start deduping behavior for `FAIL`.
For `FAIL`, the behavior was not correct in that it didn't attempt to dedup the request; it just failed immediately.
Added new tests.
> Fix Update-with-Start deduping

- common/rpc/interceptor/rate_limit.go
- service/frontend/configs/quotas.go
- service/frontend/configs/quotas_test.go
Previously, all DescribeTaskQueue requests use visibility rate limiter, which is too restrictive for non-reachability requests. Fix that by checking in the interceptor.
So that people interested in only the backlog data don't have to be rate-limited as if they are querying reachability when they are not.
> Send non-reachability DescribeTaskQueue requests through frontend rate limiter

- service/history/ndc/workflow_state_replicator.go
- service/history/replication/executable_verify_versioned_transition_task.go
- service/history/replication/executable_verify_versioned_transition_task_test.go
- service/history/workflow/context.go
1. Fix verify replication task sync state error
2. Fix context merge new run task logic
unit test and test on test clusters
no risk, feature not enabled
n/a
no
> Fix bug on state based replication code path

- service/frontend/configs/quotas.go
- service/frontend/fx_test.go
Prevent frontend burst value going below 0 in NewNamespaceRateBurst()
If the rate value is too small, the burst value can become 0. This will block all requests. This can happen for rate limiters with small global RPS values(eg. namespaceReplicationInducingAPIs rate limiter) in a cluster with large number of frontend instances.
No
> Prevent frontend burst value going below 1

- service/matching/matching_engine.go
- tests/xdc/base.go
- tests/xdc/user_data_replication_test.go
- Take last writer for V2 versioning metadata
- Improve user data replication tests
Merging for V2 wasn't implemented
> Fix versioning V2 replication and improve tests

- tests/xdc/failover_test.go
TestForceMigration_* should create its namespace on one cluster and then update to cross clusters.
More accurately tests the desired scenario.
> Fix force migration tests to start namespace disconnected

- .github/workflows/run-tests.yml
Added GitHub Action to publish test summaries; using https://github.com/mikepenz/action-junit-report.
Finding the failed tests in the GitHub Action logs is very tedious. This step prints a summary of the failed tests for quick consumption by the developer.
Example: https://github.com/temporalio/temporal/actions/runs/11636133070?pr=6594
_NOTE: the GHA attempts to write annotate but cannot do that successfully since the JUnit XML reports Go packages, no Go file paths. I filed an issue with the GHA asking for an option to disable them. But in the meantime, they are harmless - albeit a bit annoying._
> Summarize test results

- service/history/archival_queue_factory_test.go
- service/history/queues/executable.go
- service/history/queues/executable_factory.go
- service/history/queues/metrics.go
- service/history/queues/scheduler.go
- service/history/queues/speculative_workflow_task_timeout_queue.go
- Remove executable.taggedMetricsHandler. 
- Always init executable.metricsHandler with the full set of metric tags needed to prevent tag mismatch issue.
- Prevent tag mismatch issue.
- It looks like the task_errors_throttled metric could be emitted before taggedMetricsHandler is really tagged with the right set of tags.
- Run server locally.
> Fix task executable metrics tags

- service/history/workflow/state_machine_timers.go
- service/history/workflow/state_machine_timers_test.go
Deduplicate HSM timers if they come from the same state machine and have the same type to support regenerating tasks in the state based replication path.
Note, this can also be applied for the pre-state-replication path. I may follow up with a PR that changes how that path works but it's not critical since we're deprecating this framework.
Note that technically tasks can have a data field and there immediate tasks that can't be deduped this way but there aren't any uses where that's relevant and we're not expecting to expand usage.
> Dedupe HSM timers

- components/callbacks/statemachine.go
- components/dummy/statemachine.go
- components/nexusoperations/statemachine.go
- components/nexusoperations/statemachine_test.go
- components/scheduler/statemachine.go
- service/history/hsm/hsmtest/sm.go
- service/history/hsm/sm.go
- service/history/hsm/tree.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/task_refresher.go
This reverts commit 2bfca0d9a1bdf16200594c38146e2b1a005005f8.
The approach taken in #6728 made this change obsolete.
> Revert "Use previous state in hsm RegenerateTasks (#6710)"

- common/dynamicconfig/constants.go
- service/matching/config.go
- service/matching/matching_engine.go
- service/matching/matching_engine_test.go
- Added a flag before we drop matching tasks with `Internal/DataLoss` errors.
- CDS sometimes returns “Internal” error instead of “Unavailable”
- This could pose to be a problem since matching currently drops tasks with `Internal` Errors. 
- Existing suite of tests
- None since there were no previously emitted metrics verifying the dropping of any matching tasks due to internal/dataloss error.
No
> added a flag when dropping non-retryable matching tasks

- service/history/api/queryworkflow/api.go
- service/history/history_engine_test.go
Do not clear mutable state when query failed
QueryWorkflow won't alter mutable state, so it is safe to not clear ms when query failed.
Exiting behavior would clear mutable state on failed query, which delete all pending buffered queries and is not desired.
Update existing tests to verify that buffered query still exists after a failed query.
No
No change.
No.
> Do not clear mutable state when query failed

- .github/workflows/run-tests.yml
To avoid rate limiting by GH (as recommended in the action's README).
> Use GITHUB_TOKEN in arduino/setup-protoc action

- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/elasticsearch/visibility_store_validation_test.go
- common/persistence/visibility/store/errors.go
- common/persistence/visibility/store/sql/visibility_store.go
- common/persistence/visibility/store/visibility_store.go
Return InvalidArgument error for invalid search attribute input
Existing error is converted into errors.errorString is convert to grpc Unknown code.
Added new unit test
No
No
No
> Return InvalidArgument error for invalid search attributes

- service/history/workflow/mutable_state_impl.go
Fix closeTransactionTrackLastUpdateVersionedTransition
In a case where we closed transaction without changing mutable state, the state transition will not be updated.
n/a
no risk
no
no
> Fix closeTransactionTrackLastUpdateVersionedTransition

- tools/tdbg/tdbg_commands.go
- Rename alias for tdbg history-host from `h` to `his`
- `h` is used by the built in help command
```
COMMANDS:
workflow, w      Run admin operation on workflow
shard, s         Run admin operation on specific shard
history-host, h  Run admin operation on history host
taskqueue, tq    Run admin operation on taskQueue
membership, m    Run admin operation on membership
dlq              Run admin operation on DLQ
decode           Decode payload
help, h          Shows a list of commands or help for one command
```
In the version of `"github.com/urfave/cli/v2"` we are using right now it's ok. But in the latest version  v2.27.5, this duplication will result in an error when running tdbg commands.
- Tested locally.
- Technically a breaking change for tdbg users
> Rename alias for tdbg history-host

- service/frontend/service.go
In title. The warning is logged with a recommended action.
> Add warning if nexus is enabled and HTTP port is disabled

- .golangci.yml
- common/testing/runtime/goroutine.go
- common/tqid/task_queue_id.go
- components/callbacks/hsm_invocation.go
- components/callbacks/nexus_invocation.go
- components/callbacks/statemachine.go
- components/callbacks/statemachine_test.go
- components/nexusoperations/completion.go
- components/nexusoperations/frontend/handler.go
- components/nexusoperations/statemachine.go
- components/nexusoperations/statemachine_test.go
- components/scheduler/statemachine.go
- service/frontend/nexus_handler.go
- service/history/hsm/hsmtest/backend.go
- service/history/hsm/tree_test.go
- service/history/workflow/task_generator_test.go
- service/matching/task_queue_partition_manager.go
- service/matching/user_data_manager.go
- tests/advanced_visibility_test.go
- tests/schedule_test.go
- tests/stickytq_test.go
- tests/testcore/client_suite.go
- tests/update_workflow_test.go
- tests/versioning_test.go
turned off linter goerr113
causing excessive linter errors and challanges
PR build
fix messy error handling later
N/A
Nope
> remove linter goerr113 and nolint comments/annotations

- common/persistence/client/factory.go
- common/persistence/persistence_retryable_clients_test.go
Added `serviceerror.DataLoss` to `IsPersistenceTransientError()` so that we can retry on these errors. The number of times to retry is configured by the retry policy (which is max 2 attempts)
We've observed that the persistence layer may not always be reliable especially when you read immediately after writing. With this change we retry once before giving up.
If the retry policy is modified in the future, we may retry more than once.
N/A
No
> Retry on DataLoss error from persistence layer

- service/worker/deletenamespace/reclaimresources/activities.go
- service/worker/deletenamespace/reclaimresources/activities_test.go
- service/worker/deletenamespace/reclaimresources/workflow.go
- service/worker/deletenamespace/reclaimresources/workflow_test.go
Standard visibility was removed from server in v1.24 release. This is to clear dead code.
Less is better.
eye_ball
NDE on replay
No
No
> Delete code for standard visibility from DeleteNamespace workflow

- docs/architecture/workflow-update.md
- service/history/api/respondworkflowtaskcompleted/api.go
- service/history/workflow/update/abort_reason.go
- service/history/workflow/update/export_test.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/state.go
- service/history/workflow/update/update.go
- service/history/workflow/update/update_test.go
Delay Update abortion with effects package.
To address race condition case when Update is accepted and WF is completed on the same WFT. In this scenario Update result waiters should have similar experience as if Update was failed with error on the same WFT, meaning that even waiters for `Accepted` stage should get Update result (which is abort failure). Previous implementation had race condition and those waiter might get Update failure, or "Update is accepted" response.
No risks.
Yes, updated.
No.
> Workflow Update: delay Update abortion with effects package

- common/util.go
- common/util_test.go
- `CreateHistoryStartWorkflowRequest` will now deep copy the `request` structure when `LastCompletionResult` or `ContinuedFailure` are set. 
To avoid sending those payloads twice, `CreateHistoryStartWorkflowRequest` unsets those fields on the internal forwarded request struct. This is done by directly mutating the `request` parameter. When the workflow handler calls into `CreateHistoryStartWorkflowRequest` and fails, the internal retry handler will retry the request, but the fields have already been unset on the reused `request` object. Subsequent retries from the internal handler will therefore be missing these fields without additional consideration. 
- New test
- A minimal performance difference because of the deep copy.
- No 
- No
> Clone payloads in CreateHistoryStartWorkflowRequest to avoid losing payloads on retry

- common/tasks/weighted_channel.go
There is a possible data race when last updated time is accessed by the cleanupLoop in InterleavedWeightedRoundRobinScheduler while another goroutine is updating that value. Fix this by making LastActiveTime an atomic variable.
Unit tests.
No
> Fix data race in WeightedChannel

- common/dynamicconfig/cachedvalue.go
- common/dynamicconfig/constants.go
- common/util/wildcard.go
- common/util/wildcard_test.go
- common/wildcard.go
- service/frontend/http_api_server.go
- service/frontend/service.go
- tests/http_api_test.go
Add a dynamic config to restrict which HTTP `Host` header values are allowed in HTTP API requests.
Prevent DNS rebinding attacks.
Added a functional test.
> Add dynamic config to control allowed Host headers

- common/tasks/interleaved_weighted_round_robin_test.go
Fix TestDeleteInactiveChannels flakiness.
We read the current time before the despatch loop and resue it. Added a small wait in the test for the dispatch loop to finish after advancing the time.
This will make sure that a dispatch loop has finished before next set of tasks are processed. Otherwise dispatch loop might set old lastActive time for channels.
No
> Fix TestDeleteInactiveChannels flakiness

- common/persistence/sql/sqlplugin/sqlite/driver.go
- common/persistence/tests/sqlite_test.go
Use an sqlite connection that has ResetSession() and IsValid() implemented.
If these methods are not implemented, sql library will close the connection when the context is cancelled during a transaction. We will lose the database if this happens.
IsValid() will always return true in this case. We should always have a valid database connection, otherwise we would have already lost the database. Similarly ResetSession() does nothing.
Tried to reproduce the issue by cancelling a transaction context.
None
No
> Fix sqlite connection closed issue

- Makefile
Disable `gotestsum` re-runs.
`gotestsum` has a bug that reports test failures with exit code 0, making the GHA job succeed.
See https://github.com/gotestyourself/gotestsum/issues/423
Test failure results in GHA job failure.
> Disable gotestsum rerun

- common/testing/historyrequire/history_require.go
Before
```
Error:      	Not equal: 
expected: 4
actual  : 5
Test:       	TestResetWorkflowTestSuite/TestResetWorkflowAfterTimeout
Messages:   	Length of expected(4) and actual(5) histories is not equal
```
After
```
Error:      	Not equal: 
expected: 4
actual  : 5
Test:       	TestResetWorkflowTestSuite/TestResetWorkflowAfterTimeout
Messages:   	Length of expected(4) and actual(5) histories is not equal: 
1 WorkflowExecutionStarted
2 WorkflowTaskScheduled
3 WorkflowTaskStarted
4 WorkflowTaskCompleted
5 WorkflowExecutionCompleted
```
Help understand why the length was different; without firing up a debugger.
> Print actual events in HistoryRequire helper

- service/history/api/multioperation/api.go
- service/history/api/startworkflow/api.go
- service/history/history_engine.go
Introducing a new StartOutcome type. It signals the kind of start that was performed.
I considered various other options (like sentinel error types and adding a new field to the proto), but then decided on this.
This is needed for making Terminate-Existing work, since there it's important to distinguish between "deduped" and "reused".
See https://github.com/temporalio/temporal/pull/6783
> Return StartOutcome from Workflow Start

- temporaltest/server.go
Added a `GetFrontendHostPort()` method to the TestServer
For situations where you want to know the port that the test server is running on outside of typical use of client.Client
Tested locally
None
there is currently no documentation for TestServer aside from inline comments
no
> Add GetFrontendHostPort() method to TestServer

- service/history/api/pauseactivity/api_test.go
- service/history/api/updateactivityoptions/api.go
- service/history/api/updateactivityoptions/api_test.go
- service/history/ndc/workflow_resetter.go
- service/history/ndc/workflow_resetter_test.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_standby_task_executor.go
- service/history/worker_versioning_util.go
- service/history/workflow/activity.go
- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_mock.go
- service/history/workflow/task_refresher.go
- service/history/workflow/timer_sequence.go
- service/history/workflow/timer_sequence_test.go
1. I change  every UpdateActivity to UpdateActivityWithCallback everywhere in the code.
2. I removed old UpdateActivity
3. I rename UpdateActivityWithCallback to UpdateActivity
4. Fix tests, etc.
Old UpdateActivity was not actually working. ActivityInfo in pending activities is a pointer, so calculating size was wrong. Few other reasons.
unit tests
With this change the size of mutable state is calculated properly. This means that in some cases it may change, thus becoming larger then before, and trigger some errors.
No
> Refactoring: rename UpdateActivityWithCallback method on mutable state to UpdateActivity

- common/dynamicconfig/constants.go
- docs/architecture/speculative-workflow-task.md
- docs/architecture/workflow-update.md
- service/history/api/respondworkflowtaskcompleted/api_test.go
- service/history/configs/config.go
- service/history/workflow/workflow_task_state_machine.go
Drop speculative WFT even if it had events.
Special compatibility flag was [added](https://github.com/temporalio/api/pull/467) to `RespondWorkflowTaskCompletedRequest`. If this flag is set to true, then server can drop speculative WFT with update rejections, even if it shipped events to the worker. SDK support will be added later.
No risks. Compatibility flag is used to support backward compatibility and don't drop speculative WFT if worker doesn't support it (old go SDKs).
Yes, updated.
No.
> Workflow Update: drop speculative WFT even if it had events

- service/history/workflow/mutable_state_impl.go
Change delimiter for pause info search attribute from "." to ":
This is what we agree on.
> change delimeter for paused info search attribute

- go.mod
- go.sum
Pick up race fix from https://github.com/temporalio/ringpop-go/pull/16
fix rare data race
will be tested in CI, release validation
low, the previous code already obtained the same rlock on the same path, so there shouldn't be any risk of new deadlocks
> Pick up ringpop-go#16 fix

- common/testing/taskpoller/taskpoller.go
- tests/activity_test.go
- tests/testcore/taskpoller.go
- tests/update_workflow_test.go
Added support for activity tasks in new TaskPoller.
Also, added support for providing a custom poll request (instead of various options).
Not Ported:
- activity task cancellation was not ported over; not a single existing test seems to be using it
- handling activity tasks by ID is only used twice across the entire codebase; not ported over for now
Two existing tests have been ported over: one with a successful task response and one with a failure.
> Support for Activity tasks in TaskPoller

- service/history/api/multioperation/api.go
- service/history/workflow/cache/cache.go
- service/history/workflow/cache/cache_mock.go
- tests/update_workflow_test.go
ℹ️ Depends on https://github.com/temporalio/temporal/pull/6795
Support for Terminate-Existing workflow conflict policy in Update-with-Start.
Complete UwS' conflict policy support.
Re-enabled Terminate-Existing functional tests.
> Update-with-Start with policy Terminate-Existing

- Makefile
- cmd/tools/test-runner/main.go
- go.mod
- go.sum
- tests/callbacks_test.go
- tools/testrunner/testdata/junit-attempt-1.xml
- tools/testrunner/testdata/junit-attempt-2.xml
- tools/testrunner/testrunner.go
- tools/testrunner/testrunner_test.go
Added a test-runner command for rerunning tests and modified the Makefile to use the new command.
gotestsum is supposed to do this but it is buggy: https://github.com/gotestyourself/gotestsum/issues/423.
If this runner works well we can stop using gotestsum if we choose but I would probably recommend using it since it claims to do exactly what we need. 
An alternative would be to either generate test reports using JSON output or using https://github.com/jstemmer/go-junit-report to create junit XML reports.
- Ran functional tests multiple times locally
- Added unit tests to the runner
> Create test-runner command for rerunning tests

- tools/common/schema/setuptask.go
- tools/common/schema/updatetask.go
The setuptask and updatetask uses `path.Join` when `embed.FS` is used as the file system.
When using `filepath.Join` on Windows environment, the forward slashes are converted to back slashes. However, `embed.FS` always expects the paths to be composed with forward slashes. This causes the setuptask and updatetask to fail in Windows environment.
Tested locally on a Windows environment.
Schema setup and update tasks can break.
All good.
No
> Update schema setuptask and updatetask to use path.Join when using embed.FS

- service/history/api/updateactivityoptions/api.go
- service/history/ndc/workflow_resetter.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_standby_task_executor.go
- service/history/worker_versioning_util.go
- service/history/workflow/activity.go
- service/history/workflow/activity_test.go
- service/history/workflow/cache/cache_test.go
- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/task_refresher.go
- service/history/workflow/timer_sequence.go
1. Add return parameter (error) to the activity updater.
2. Comment TestHistoryCacheConcurrentAccess_Pin unit test
3. Removed "ActivityState" function :). Not sure how I end up with that one but it is not needed.
1. Activity updater can fail, but there was no way to return an error.
2. If was not just failing on fresh main, but also stuck.
unit tests
> Add return error for activity updater

- service/history/api/create_workflow_util.go
- service/history/api/multioperation/api.go
- service/history/api/signalwithstartworkflow/signal_with_start_workflow.go
- service/history/api/startworkflow/api.go
- service/history/history_engine.go
- tests/update_workflow_test.go
Changed how MultiOps integrates with the Workflow Starter.
Specifically, it creates a cached-based, locked workflow context for a workflow start now. The approach before was error-prone and difficult to understand.
Data race.
> Fix data race in MultiOps API

- service/history/api/multioperation/api.go
- service/history/api/pollupdate/api.go
- service/history/api/pollupdate/api_test.go
- service/history/api/reapplyevents/api.go
- service/history/api/recordworkflowtaskstarted/api.go
- service/history/api/respondworkflowtaskcompleted/api.go
- service/history/api/respondworkflowtaskcompleted/api_test.go
- service/history/api/update_workflow_util.go
- service/history/api/updateworkflow/api.go
- service/history/ndc/transaction_manager.go
- service/history/ndc/transaction_manager_test.go
- service/history/ndc/workflow_resetter.go
- service/history/timer_queue_active_task_executor.go
- service/history/workflow/context.go
- service/history/workflow/context_mock.go
Removes the `fallbackMutableState` from the workflow context's `UpdateRegistry` method.
Not needed anymore. Once https://github.com/temporalio/temporal/pull/6858 is merged, the MutableState should always be present in the workflow context.
> Remove `ms` parameter from UpdateRegistry

- service/history/workflow/cache/cache.go
- service/history/workflow/cache/cache_mock.go
Remove `Put` method from workflow cache.
Not needed anymore after https://github.com/temporalio/temporal/pull/6850.
> Remove `Put` cache method

- service/history/transfer_queue_active_task_executor.go
Use `ErrWorkflowCompleted` instead of literal.
Consistency.
The original is "Workflow execution already completed." but now it's "workflow execution already completed"
> Use ErrWorkflowCompleted consistently

- service/history/workflow/workflow_task_state_machine.go
Fix possible NPE in `AddWorkflowTaskStartedEvent`.
If error is returned `workflowTask` can be nil and accessing `.Attempt` on it will cause NPE.
Didn't test.
No risks.
No.
No.
> Fix possible NPE in AddWorkflowTaskStartedEvent

- tools/testrunner/testrunner.go
- Do not rerun tests if there are more than 10 failures in a single suite. This threshold can later become configurable as needed.
- Add a sanity check to ensure test-runner reruns all failed tests as expected.
For confidence, this is a new tool and I don't trust it yet. The threshold is
> Test runner improvements

- service/matching/matcher_test.go
- tests/describe_task_queue_test.go
- tests/http_api_test.go
- tests/max_buffered_event_test.go
- tests/versioning_test.go
- tests/workflow_test.go
- tests/xdc/failover_test.go
- tests/xdc/nexus_state_replication_test.go
This reverts commit 5d793621dd40d518e18ae6058c3d3163ff1b63ce.
Now that we can rerun failures automatically, we can enable these flaky tests.
> Revert "Revert "Reenable flaky tests" (#6813)"

- service/frontend/workflow_handler.go
- tests/update_workflow_test.go
Trim the user-facing MultiOperation error message.
In https://github.com/temporalio/temporal/pull/6848 I added more error details; but decided while that's helpful for internal debugging (the error message is printed in the logs), I prefer not to expose the fairly noisy/verbose message to customers. They can still find the details inside the error and extract them (which is what the SDKs do).
Adjusted test.
> Trim MultiOperation error message

- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_standby_task_executor.go
- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- service/history/workflow/mutable_state_mock.go
- service/history/workflow/task_refresher.go
- service/history/workflow/timer_sequence.go
- service/history/workflow/timer_sequence_test.go
Add new api for updating timer task status
We need to distinguish the user data update and timer task status update because we don't need to update state transition when the change is task status update change. 
unit test
n/a
n/a
no
> Add mutable state api to update activity/timer task status

- tests/xdc/stream_based_replication_test.go
Fix flaky xdc stream based replication test and re-enable it.
When state-based replication is enabled, if there are workflow tasks in fly and namespace failover version changes, these workflow tasks will be failed. This will generate events and replication tasks.
Unit test.
> fix flaky xdc stream based replication test

- common/rpc/interceptor/telemetry.go
- common/rpc/interceptor/telemetry_test.go
- Do not log resource exhausted error by default
- From our metric data, logging the resource exhausted error consume 2% out of 11.9% cpu for handling a request (StartWorkflowExecution)
- We can still see resource exhausted logs by turning on `system.logAllReqErrors`
> Do not log resource exhausted error by default

- service/history/transfer_queue_active_task_executor.go
Pass VersioningOverride of parent to `StartWorkflowExecutionRequest` for child workflow
Because if a user is overriding a workflow's deployment, we expect that they want to override to apply to children too, since user is likely doing a canary test or debugging something.
Working on a test. I expect all existing child workflow execution tests to pass with no change.
> Make ChildWorkflowExecution inherit versioning override of parent

- service/history/api/multioperation/api.go
- service/history/api/startworkflow/api.go
Return `serviceerror.Unavailable` when the start of an Update-with-Start attempt is _deduped_ (same as for reused).
Otherwise, an invalid response is returned in this case (ie `nil`).
I don't know how to write _reliable_ functional test for this. A unit test is also difficult since that would require some mocking which is not available.
I crafted a test that demonstrates the fix is working as intended, but it relies on a hack: https://github.com/temporalio/temporal/compare/main...stephanos:temporal:uws-race-fix-test#diff-f5e0cf22c1120ffc0815f192fe6eca5ef9c52cb3b2eba52926bfd733c9f5af27R5255
> Fix Update-with-Start invalid response

- common/rpc/rpc.go
- tests/testcore/onebox.go
- tests/testcore/test_cluster.go
- tests/testcore/utils.go
Instead of using fixed ports in functional tests, use randomized ports.
The nested map is ... not pretty but effective. Happy to throw more design at it, if needed.
When starting two or more clusters (e.g. xdc tests), different hosts have to be used for the ports not to collide; which causes issues on at least MacOS.
> Randomize test ports

- service/worker/deployment/deployment_client.go
- tests/versioning_3_test.go
Deployment client retries on multi-operation errors.
Errors such as "MultiOperation could not be executed: Start failed: Workflow was not started: StartReused" are expected when there are concurrent pollers, and retry should fix them. We don't want to fail user's poll due to these errors.
> Deployment clinet to Retry on multi-operation errors

- components/callbacks/executors.go
- components/callbacks/hsm_invocation.go
- components/callbacks/nexus_invocation.go
- components/callbacks/tasks.go
- components/nexusoperations/tasks.go
- service/history/hsm/tasks.go
- service/history/statemachine_environment_test.go
- Fixed the callback executor to not fail a task on retryable error (a regression introduced while refactoring to support HSM callbacks)
- No longer use `ValidateNotTransitioned` in task validation logic. We can deprecate the `transition_count` field on the state machine node proto after this.
The first fix is a simple bug fix, the second change is for unblocking the state replication efforts.
Leveraged existing tests.
> Nexus callback and task validation fixes

- service/history/ndc/events_reapplier.go
- service/history/ndc/workflow_resetter.go
- service/history/ndc/workflow_resetter_test.go
Do not reapply cancellation in reset operation.
Cancellation should only be reapplied for conflict resolution. For reset, we should not reapply cancel request.
> Not reapply cancellation on reset

- service/history/api/create_workflow_util.go
- service/history/api/multioperation/api.go
- service/history/api/signalwithstartworkflow/signal_with_start_workflow.go
- service/history/api/startworkflow/api.go
- tests/update_workflow_test.go
Fixed bug where UwS does not work for a closed workflow even though the reuse policy is `ALLOW_DUPLICATE`.
Bug.
Added new tests.
I kept the changes to the non-UwS path to an _absolute_ minimum. I don't believe it changes the non-UwS behavior in any way.
> Fix Update-with-Start for closed workflow

- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/elasticsearch/visibility_store_write_test.go
Make sure the generated docID for ES is valid utf8 when workflow ID is too long
Without proper handling, the result could be invalid utf8 string and ES would encode them result in doc ID longer than 512 limit.
unit test
No
No
Maybe
> Fix ES docID when workflowID contains multi-bytes unicode

- common/util.go
- common/util_test.go
- service/history/api/multioperation/api.go
- service/worker/deployment/deployment_client.go
Changing client and handler behavior to retry MultiOperations if it contains an operation that itself is retryable.
There are transient issues that require a retry; and should not be returned to the client immediately as-is.
MultiOperations are never nested anywhere; so there's no real threat of endless loops.
> Fix Update-with-Start serviceerrors

- common/dynamicconfig/constants.go
- service/frontend/fx.go
- service/frontend/operator_handler.go
- service/frontend/operator_handler_test.go
- service/frontend/service.go
Avoid breaking callers.
Added unit test assertions.
> Prevent a namespace from being deleted if it is the target of a Nexus endpoint

- tests/deployment_test.go
Increase context deadline from 10s --> 15s in occasionally flaky DescribeDeployment test that fails with context deadline exceeded.
Increase timeout from 5s --> 10s in occasionally flaky TestBatchUpdateWorkflowOptions test that fails because the list of batch workflows was still 0 after 5s. This flake only occurs in cassandra test clusters, so I think this is just a visibility eventual consistency issue, not anything that can be sped up.
To reduce observed test flakiness.
Currently running 100x in CI.
> Increase timeouts in flaky DeploymentSuite tests

- service/history/api/updateactivityoptions/api.go
- tests/activity_api_update_test.go
1. Add some basic unit tests for activity update.
2. Small bug fix.
To build some functional test coverage  for the activity API
> some func tests for update activity

- common/metrics/metric_defs.go
- service/history/ndc_standby_task_util.go
- service/history/replication/executable_sync_versioned_transition_task.go
- service/history/timer_queue_factory.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/transfer_queue_factory.go
- service/history/transfer_queue_standby_task_executor.go
- service/history/transfer_queue_standby_task_executor_test.go
Remove passive task resend logic
Resend is best effort
unit test
passive task may disappear
no document
no
> Remove passive task resend logic

- service/matching/matcher_test.go
Fixed a Data race in Matcher Test
To enable normal developement
make unit-test
none, its a test.
N/A
No
> fix data race in TestBacklogAge

- common/primitives/uuid.go
- service/history/api/startworkflow/api.go
I changed our RunID generation to use [UUIDv7](https://buildkite.com/resources/blog/goodbye-integers-hello-uuids/) instead of V4 by default.
UUIDv7s have a timestamp as their prefix, which will help us optimize the physical storage layout of our workflow-related data.
Existing tests
I don't believe there are any
Not necessary.
No
> Change RunIDs to use UUIDv7

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
Fix start child workflow replication
We need to replicate the uuid, so the child workflow will not stuck after failover
n/a
n/a
n/a
no
> Fix start child workflow replication

- service/history/transfer_queue_active_task_executor.go
- service/history/transfer_queue_active_task_executor_test.go
This PR prevents the parentClosePolicy from triggering when a currently running execution was terminated due to reset.
This is needed to implement the "Reconnect" reset policy.
N/A
N/A
No
> [Reset] Ignore ParentClosePolicy when a parent is closed due to reset

- common/dynamicconfig/constants.go
- service/history/api/reapplyevents/api.go
- service/history/api/resetworkflow/api.go
- service/history/configs/config.go
- service/history/history_engine.go
- service/history/history_engine_test.go
- service/history/ndc/transaction_manager.go
- service/history/ndc/transaction_manager_test.go
- service/history/ndc/workflow_resetter.go
- service/history/ndc/workflow_resetter_mock.go
- service/history/ndc/workflow_resetter_test.go
- service/history/transfer_queue_active_task_executor.go
Added a dynamic config (default `false`) to gate the resetting with pending children feture.
The feature is still in development. So we don't want to expose it yet.
Existing tests since it's just wiring the config.
N/A
N/A
No
> [Reset] Dynamic config to allow resetting with pending children

- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/nexusoperations/statemachine.go
- tests/xdc/nexus_state_replication_test.go
Cancel Nexus operation only after the operation has started.
Can only cancel operation after it has started.
Updated unit test.
> [Nexus operations] Cancel only after Operation started

- service/history/ndc/workflow_resetter.go
- service/history/ndc/workflow_resetter_test.go
- service/history/workflow/context.go
reapply wf terminated event for conflict resolution
During conflict resolution, EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED should be reapplied to current branch.
unit test.
> reapply wf terminated event for conflict resolution

- tests/max_buffered_event_test.go
TestBufferedEventsMutableStateSizeLimit was written in the assumption that max buffered event size is 16MB. But the default value has changed to 2MB.
Rewriting this test to fix this. Added a check to make sure that the test will fail if the limit is changed again.
This test is flaky. This fix might help with that.
None
No
> Fix TestBufferedEventsMutableStateSizeLimit

- service/history/workflow/activity.go
- service/history/workflow/mutable_state_impl.go
- tests/activity_api_pause_test.go
- tests/activity_api_update_test.go
Add functional tests to test Pause/Unpause activity API.
To have test coverage
No
> add functional tests for pause/unpause activity API

- common/nexus/endpoint_registry.go
min wait variable needed to be initialized outside the loop for the increasing wait time to actually take effect.
> Fix Nexus endpoint registry min wait

- .vscode/launch.json
A new config entry to allow VSCode debugger to connect to a local running instance of server.
Makes it easy to quickly connect and breakpoint a dev server. No need to restart the server in debugger everytime.
Tested it manually
N/A
N/A
No
> [VSCode] Config to connect debugger to a running server instance

- .golangci.yml
- common/dynamicconfig/constants.go
- service/matching/config.go
- service/matching/matching_engine.go
- service/matching/physical_task_queue_manager_test.go
- service/matching/user_data_manager.go
- service/matching/user_data_manager_test.go
The task queue user data owner reads from the db periodically after the first read, to catch writes that may have been made by the old owner during ownership change, or in general by any bugs.
Membership isn't strongly consistent so an old owner of task queue user data might complete or even start a write after a new owner has done its initial read. This would be detected on an attempted update, but user data is updated rarely so the stale data could persist for a long time.
new unit tests
> Refresh user data from db periodically

- common/nexus/failure.go
- common/tasks/dynamic_worker_pool_scheduler.go
- common/testing/mocksdk/client_mock.go
- components/nexusoperations/completion.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/nexusoperations/frontend/handler.go
- components/nexusoperations/fx.go
- components/nexusoperations/statemachine.go
- components/nexusoperations/statemachine_test.go
- go.mod
- go.sum
- service/frontend/nexus_handler.go
- service/frontend/nexus_handler_test.go
- service/history/handler.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/workflow_test/mutable_state_impl_test.go
- service/matching/matching_engine.go
- tests/nexus_api_test.go
- tests/nexus_workflow_test.go
- tests/xdc/nexus_request_forwarding_test.go
- tests/xdc/nexus_state_replication_test.go
- Rehydrate Temporal Failures from Nexus operation errors.
- Upgrade the Nexus and Temporal Go SDKs.
- [Fix data race in DynamicWorkerPoolScheduler](https://github.com/temporalio/temporal/pull/6967/commits/da34e3777a29b73ae1ba533403983d9171f22a8a).
- [Add Request-Timeout header in matching](https://github.com/temporalio/temporal/pull/6967/commits/d83c480d01232225c1646e168c62a2f7ec7abe96) in addition to the lower case `request-timeout` header.
- On par debugging experience with child workflows and activities.
Added a bunch of functional tests. Note that the tests also cover the SDK.
> Nexus error rehydration

- common/nexus/failure.go
- common/nexus/nexustest/server.go
- tests/nexus_workflow_test.go
- Fix a couple of occasional panics in Nexus functional and unit tests.
- Remove default failure message for unsuccessful operations.
> Various small nexus fixes

- common/dynamicconfig/constants.go
Change replication ReplicationLowPriorityTaskParallelism config default to 1
When creating workflow, we need to hold workflow lock, so 1 makes more sense
n/a
no risk
n/a
no
> Change replication ReplicationLowPriorityTaskParallelism config default to 1

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
When applying an UpdateAccepted event to the MS, use the `protocolInstanceId` instead of the Update ID from the `acceptedRequest` attributes.
See code comment.
Extended/modified existing tests.
> Handle missing Update `acceptedRequest`

- common/dynamicconfig/constants.go
- common/persistence/sql/nexus_endpoint_store.go
- service/matching/config.go
- service/matching/matching_engine.go
- service/matching/matching_engine_test.go
- service/matching/nexus_endpoint_client.go
Added a background routine to `matching/nexus_endpoint_client` which checks whether the last known table version has changed.
In rare cases, when a new node acquires ownership it may miss in-flight updates from the previous owner and has no way of detecting this inconsistency.
Existing tests
> Refresh Nexus endpoints from db periodically

- service/worker/deletenamespace/deleteexecutions/activities.go
- service/worker/deletenamespace/reclaimresources/workflow.go
Delete Namespace: send delete executions heartbeats from separate go routine.
Following best practices heartbeats should be sent outside of main activity function in case if operation takes longer than expected. Also `DeleteExecutionsActivity` doesn't send heartbeats on every deleted execution but sends accumulated result every 5 seconds.
Existing tests and manual run.
No risks.
No.
No.
> Delete Namespace: send delete executions heartbeats from separate go routine

- service/worker/deletenamespace/activities.go
- service/worker/deletenamespace/workflow.go
- service/worker/deletenamespace/workflow_test.go
- tests/xdc/failover_test.go
Delete Namespace: block for replicated namespace.
Disable namespace deletion if namespace is replicate because:
- If namespace is passive in the current cluster, then WF executions will keep coming from
the active cluster and namespace will never be deleted (`ReclaimResourcesWorkflow` will fail).
- If namespace is active in the current cluster, then it technically can be deleted (and
in this case it will be deleted from this cluster only because delete operation is not replicated),
but this is confusing for the users, as they might expect that namespace is deleted from all clusters.
Added unit and functional tests.
Replicated namespaces can't be deleted anymore and must be disconnected first.
No.
No.
> Delete Namespace: block for replicated namespace

- common/log/slog.go
- Always carry over the embedded `zapLogger`.
- Ensure `handler` is never `nil`.
- Allow extracting an underlying `slog.Logger`.
Realized there are some issues using custom loggers, like the one used by the CLI.
> Fix a couple of issues in the slog adapter

- service/worker/deletenamespace/deleteexecutions/workflow_test.go
- service/worker/deletenamespace/reclaimresources/workflow_test.go
- service/worker/deletenamespace/workflow_test.go
Delete Namespace: set `SdkLogger` in tests.
Default workflow logger doesn't support log tags that are widely used in server codebase. It is substituted with `SdkLogger` in real setup but not in unit tests which makes logs look weird. 
Run tests.
No risks.
No.
No.
> Delete Namespace: set SdkLogger in tests

- common/metrics/metric_defs.go
- service/frontend/operator_handler.go
- service/worker/deletenamespace/activities.go
- service/worker/deletenamespace/activities_test.go
- service/worker/deletenamespace/deleteexecutions/activities.go
- service/worker/deletenamespace/deleteexecutions/workflow.go
- service/worker/deletenamespace/errors/errors.go
- service/worker/deletenamespace/fx.go
- service/worker/deletenamespace/reclaimresources/activities.go
- service/worker/deletenamespace/reclaimresources/workflow.go
- service/worker/deletenamespace/workflow.go
1. Remove useless metrics.
2. Add useful metrics with useful tags (`namespace`).
3. Improve comments and log messages.
Make `DeleteNamespaceWorkflow` metrics more useful:
- Use `reclaim_resources_namespace_delete_failure` and/or `reclaim_resources_delete_executions_failure` to alert on `ReclaimResources` workflow failures.
- Use `delete_executions_success` and `delete_executions_failure` to track `DeleteExecutions` workflow progress.
Existing tests and few manual runs.
If someone uses old metrics (I see no reason for it), they won't work anymore. 
No.
No.
> Delete Namespace: cleanup logs and metrics

- service/history/ndc/workflow_state_replicator.go
Do not call back fill events when replication task does not contain any events
It is causing DLQ
n/a
n/a
n/a
yes
> Do not call back fill events when replication task does not contain any events

- components/nexusoperations/events.go
- components/nexusoperations/events_test.go
- components/nexusoperations/helpers_test.go
- components/nexusoperations/statemachine.go
- components/nexusoperations/statemachine_test.go
- components/nexusoperations/workflow/commands.go
- components/nexusoperations/workflow/commands_test.go
- service/history/workflow/task_generator_test.go
- tests/xdc/nexus_state_replication_test.go
Add deletion calls for Nexus operation nodes once they reach a terminal state (Completed, Failed, Canceled, Timed Out). Previously, terminal operations lingered in the state machine, potentially causing confusion and wasting resources. In addition, this PR addresses previously existing TODOs related to node cleanup.
- **Automatic Node Deletion on Terminal States:**  
Operations are now removed from the state machine immediately after they complete, fail, cancel, or time out.
- **Handler Updates:**  
The command handlers (schedule and cancel) now reflect the new terminal state deletion. Attempts to cancel an operation that has already reached a terminal state will produce a clear, non-retryable error.
- **Tests for Terminal State Deletion:**  
Introduced two new test suites:
- …
> Nexus: Delete state machine on terminal state -- Part 3

- go.mod
- go.sum
- service/history/api/queryworkflow/api.go
- service/matching/matching_engine.go
- tests/query_workflow_test.go
Attach a Failure object from query failures to the QueryFailure serviceerror.
Allows encryption of failure messages and stack traces.
See also temporalio/api/pull/503.
> Query Failure

- service/frontend/workflow_handler.go
- tests/nexus_api_test.go
Prevent invalid data from entering the system.
Added tests for the known cases where this can occur.
> Ensure Nexus Failure is JSON serializable

- tools/testrunner/testrunner.go
The numerical comparison wasn't working as expected.
> Change test-runner sanity check to verify no missing test cases

- common/dynamicconfig/constants.go
- service/frontend/errors.go
- service/frontend/operator_handler.go
- service/frontend/operator_handler_test.go
- service/worker/deletenamespace/activities.go
- service/worker/deletenamespace/errors/errors.go
- service/worker/deletenamespace/fx.go
- service/worker/deletenamespace/workflow.go
- service/worker/deletenamespace/workflow_test.go
- tests/namespace_delete_test.go
Protect critical namespaces from deletion.
Safety net to prevent deletion of critical namespaces. Use:
```yaml
worker.protectedNamespaces:
- value:
- critical_namespace
- just_very_important_namespace
```
dynamic config to list critical namespaces.
Added unit and functional tests.
Change in `DeleteNamespace` workflow is not backward compatible (added new local activity), but this is a very short lived workflow (it starts actual deletion in abandon child mode) and shouldn't bring any real problems.
No.
No.
> Delete Namespace: protect critical namespaces from deletion

- service/history/workflow/mutable_state_impl.go
- Make IsResetRun check backward compatible by check if mutableState.ExecutionInfo.OriginalRunID is empty
- OriginalRunID is a new field in mutable state and if empty can't be used to tell if workflow is a reset run or not.
> Make IsResetRun check backward compatible

- .github/workflows/run-tests.yml
* Add page_num parameter to GH jobs API url.
* remove some debug lines
* remove pipefail
The default number of returned jobs is 30, and we may have more then that.
With pipefail (as I understand it) we can be in a situation when job_id is set to the pipeline errors.
Without it it will be empty. Empty is better then a random error.
> increase the number of returned jobs

- tests/nexus_workflow_test.go
Found and fixed a case where we block on a channel, which may cause a test to hang.
> Ensure nexus_workflow_test cases do not hang

- service/worker/deletenamespace/errors/errors.go
- service/worker/deletenamespace/reclaimresources/workflow.go
- service/worker/deletenamespace/reclaimresources/workflow_test.go
Delete Namespace: ability to update sleep duration.
SRE experience improvement. Sometimes namespace delete delay is set to the large duration by mistake and there was no way to change it after WF is started.
Use:
```bash
temporal workflow update execute --namespace temporal-system --name update_namespace_delete_delay --workflow-id temporal-sys-reclaim-namespace-resources-workflow/default-deleted-93f5e --input '"10h"'
```
to update delay to the new value (10 hours, in the example above) or:
```bash
temporal workflow update execute --namespace temporal-system --name update_namespace_delete_delay --workflow-id temporal-sys-reclaim-namespace-resources-workflow/default-deleted-93f5e --input '"0"'
```
to remove delay completely.
Please note that new delay is started from the moment it is set, …
> Delete Namespace: ability to update sleep duration

- common/dynamicconfig/constants.go
- service/frontend/fx.go
- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
- service/history/tests/vars.go
- tests/callbacks_test.go
- tests/testcore/client_suite.go
- tests/testcore/functional.go
- tests/testcore/functional_test_base.go
- tests/xdc/nexus_request_forwarding_test.go
- tests/xdc/nexus_state_replication_test.go
- Change the `system.enableNexus` dynamic config default to `true`.
- Remove test overrides for that dynamic config.
- Return false for Nexus enabled in `GetSystemInfo` if the HTTP server is disabled.
> Enable Nexus by default

- service/frontend/operator_handler.go
- service/frontend/operator_handler_test.go
- service/frontend/service.go
- service/worker/deletenamespace/activities.go
- service/worker/deletenamespace/activities_test.go
- service/worker/deletenamespace/fx.go
- service/worker/deletenamespace/reclaimresources/activities_test.go
- service/worker/deletenamespace/workflow.go
- service/worker/deletenamespace/workflow_test.go
Delete Namespace: move Nexus endpoint validation to workflow.
Consolidate all delete namespace validation logic in one place.
Modified existing and new unit tests.
This is a breaking change for `DeleteNamespace` workflow. But this workflow is very short lived and chances of being upgraded while running are very low.
No.
No.
> Delete Namespace: move Nexus endpoint validation to workflow

- service/frontend/operator_handler.go
- service/frontend/operator_handler_test.go
- service/worker/deletenamespace/activities.go
- service/worker/deletenamespace/deleteexecutions/activities.go
- service/worker/deletenamespace/deleteexecutions/workflow.go
- service/worker/deletenamespace/deleteexecutions/workflow_test.go
- service/worker/deletenamespace/errors/errors.go
- service/worker/deletenamespace/reclaimresources/activities.go
- service/worker/deletenamespace/reclaimresources/workflow.go
- service/worker/deletenamespace/reclaimresources/workflow_test.go
- service/worker/deletenamespace/workflow.go
- service/worker/deletenamespace/workflow_test.go
- tests/namespace_delete_test.go
Clean up errors in delete namespace workflows:
1. Use `FailedPrecondition` instead of `InvalidArgument` where it makes more sense.
2. Add helpers to construct `ApplicationError`s of different type.
3. Remove `unable to execute activity` error which was wrongly used in many places.
4. Few minor cleanups.
Simplify and unify error handling in delete namespace workflows.
Modified tests. Manual runs.
No risks.
No.
No.
> Delete Namespace: clean up errors

- common/persistence/history_manager.go
- Log branchToken on potential data loss error. The logged branchToken is in base64 format and can be decoded with the command below. The treeID is usually the workflow runID. Also the branchToken is constructed by persistence layer, so there could be additional info re. the workflow in the branchToken.
```
./tdbg decode proto --type temporal.server.api.persistence.v1.HistoryBranch --hex-data "$(echo "CiQwMTkzZTY1OC1lZjc0LTc1ZDAtYTU4NS1hZWI0MzZlYThmNDESJDAxOTNlNjU4LWVmNzQtNzYyNi05ZTlmLWI1ODAwMGI2MjNkMQ==" | base64 --decode | hexdump -ve '/1 "%02x"')"
{
"treeId": "0193e658-ef74-75d0-a585-aeb436ea8f41",
"branchId": "0193e658-ef74-7626-9e9f-b58000b623d1"
}
```
- We recently introduced retry for data loss errors in persistence client, but that also means application logic may not see those …
> Log branchToken on potential data loss error

- common/headers/version_checker.go
Part of the release process now that `v1.26.2` is out.
> Update ServerVersion to next minor

- service/history/ndc/activity_state_replicator.go
- service/history/ndc/activity_state_replicator_test.go
- tests/xdc/activity_api_test.go
Add replication tests for activity API. Activity is started in one cluster, fail, paused, and then replicated to another cluster.
To make sure that Paused state is replicated.
> Add replication test to the activity API

- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- tests/nexus_workflow_test.go
HandlerError rehydration requires the latest Go SDK and isn't yet supported in Java, this change prevents breaking existing SDK users.
> Change Nexus HandlerError rehydration to use ApplicationFailure

- service/history/replication/task_executor.go
fix inconsistent label cardinality error
`inconsistent label cardinality: expected 3 label values but got 4 in prometheus.Labels{"multi_region_namespace":"true", "operation":"SyncActivityTask", "service_name":"history", "temporal_service_type":"history"}`
`inconsistent label cardinality: expected 4 label values but got 5 in prometheus.Labels{"multi_region_namespace":"true", "namespace":"app-1996-frontline-uat.pfayb", "operation":"SyncActivityTask", "service_name":"history", "temporal_service_type":"history"}`
> fix inconsistent label cardinality error

- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_mock.go
Remove MutalbleState interface dependency on some other interfaces in `components/callbacks`
1. It is not needed.
2. Preparing mutable state to move into separate folder, with other interfaces.
existing tests
> Remove mutable state dependency on callbacks

- tests/testcore/onebox.go
In functional tests, use the ClientStatsHandler, too (in additional to the ServerStatsHandler).
Without the ClientStatsHandler, the spans don't track their parent span ID correctly. Which makes it impossible to connect the spans again.
Notice how the spans are all connected from Frontend to History:
> Use ClientStatsHandler in func tests

- service/history/queues/executable_test.go
Adding namespace handover test case for queues.*executableImpl.shouldResubmitOnNack
Related to [7047](https://github.com/temporalio/temporal/pull/7047), i've accidentally deleted my fork.
Better coverage.
Run unit test locally
> Adding namespace handover test case for history executable

- service/history/api/create_workflow_util.go
- service/history/api/multioperation/api.go
Refactored MultiOperation handler. Based on https://github.com/temporalio/temporal/pull/7018.
Code hygiene.
Existing tests. There are no (intended) behavior changes.
> MultiOperation handler refactoring

- service/worker/batcher/activities.go
- service/worker/batcher/activities_test.go
Add "Status='Running'" to the query for certain batch operation types.
Note - if query is empty or already contains 'Status' cause - it will not be added.
There is no need to run those operations on not-running workflows, but omitting this cause can significantly increase run time.
add unit test
N/A
May be...
No
> Modify incoming batch query to select only running workflows for certain batch operations

- tests/deployment_test.go
- Increase max concurrent batch jobs from 1 to 3 in DeploymentTestSuite
- Sleep and retry if max concurrent batch operations is hit
`TestDeploymentSuite/TestBatchUpdateWorkflowExecutionOptions_SetPinnedThenUnset` was flaking due to "Max concurrent batch operations is reached"
> Fix `TestDeploymentSuite/TestBatchUpdateWorkflowExecutionOptions_SetPinnedThenUnset` flake

- service/worker/deletenamespace/activities.go
- service/worker/deletenamespace/fx.go
- service/worker/deletenamespace/workflow.go
- service/worker/deletenamespace/workflow_test.go
- tests/xdc/failover_test.go
Delete Namespace: fix validation of replicated namespace.
Namespace should be deletable when:
1. It is active in the current cluster (even if replicated),
2. Doesn't belong to current cluster (current cluster was removed from cluster list).
Added new tests, existing tests, manual run.
No risks.
No.
No.
> Delete Namespace: fix validation of replicated namespace

- service/matching/ack_manager.go
- service/matching/backlog_manager.go
- service/matching/matching_engine_test.go
Removes the reference to BacklogManager from AckManager.
Removes circular dependency.
Existing tests. No behavior change is expected.
> Remove BacklogManager from AckManager

- docs/architecture/workflow-update.md
Workflow Update: fix doc on when `WorkflowUpdateAbortedErr` is returned.
Make doc in-sync with code.
N/A
N/A
It is it.
No.
> Workflow Update: fix doc on when WorkflowUpdateAbortedErr is returned

- tests/reset_workflow_test.go
- tests/update_workflow_suite_base.go
- tests/update_workflow_test.go
Refactor: return `runID` from `startWorkflow` instead of new `testvars` instance.
While reviewing versioning3 functional tests, I found out that pattern when `tv` is getting reassigned from `startWorkflow` helper doesn't work there because of concurrency issues. And although this is not a case for Workflow Update functional tests, I want to follow same pattern in all functional tests.
Run them.
No risks.
No.
No.
> Refactor: return runID from startWorkflow instead of new testvars instance

- components/callbacks/executors.go
Previously we were using the call context which can timeout and prevent saving the callback result if the call times out.
> Use task context to save the callback result

- tests/testcore/client_suite.go
- tests/testcore/functional.go
Fix functional subtest execution.
Credits to @stephanos for the brilliant idea!
Previously, if there is a assert failure (like `s.Equal`) in subtest, it failed entire test and stoped executing other subtests. Error message went to parent test as well, while subtest failed with wired message "subtest paniced". This is because we override `s.Assertions` in every test with `require.New` and it calls `FailNow` when condition is not meet. Same thing must to be done for every subtest. And every test helper which depends on `s.T()`.
Simulate failure of some sub tests and checked results.
No risks.
No.
No.
> Fix functional subtest execution

- common/testing/testvars/test_vars.go
- tests/versioning_3_test.go
Fix `testvars` usage in versioning3 tests.
Use `testvars` as intended.
Run it.
No risks.
No.
No.
> Fix testvars usage in versioning3 tests

- service/matching/backlog_manager.go
- service/matching/matching_engine.go
Return ResourceExhausted directly to client if we get it from history on RecordTaskStarted.
If history is overloaded and we retry immediately, we can end up in a loop where we keep matching tasks and sending them to history, increasing load on history and also persistence as we cycle tasks to the end of the queue. Returning the error effectively inserts the client in this loop, slowing it down.
existing tests
yes
> Handle ResourceExhausted from RecordTaskStarted in task poll

- service/history/configs/quotas.go
- service/history/configs/quotas_test.go
- Use caller type to determine history requests priority
- Right now the priority feature is only used for prioritizing operator requests, but doesn't help with background requests increase case which can cause user requests to be throttled as well.
> Use callerType to determine history requests priority

- common/dynamicconfig/constants.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
If the maximum in-flight limit for updates is zero, disable the check.
Preparation to move towards a payload-based check. Having the option to turn this limit off is useful.
Added test.
> Allow disabling the Updates in-flight limit

- service/history/queues/queue_scheduled.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_active_task_executor_test.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/timer_queue_task_executor_base.go
- service/history/transfer_queue_standby_task_executor.go
- service/history/transfer_queue_standby_task_executor_test.go
- service/history/workflow/cache/export_testing.go
- Handle system time move backward case in timer task processing by using max(now(), task visibility timestamp)
- Monotonic time is used in time.Time comparison only when both operands have monotonic time value. In our case, the timestamp stored/derived in/from mutable state doesn't have monotonic, thus the comparison logic will use wall clock time to decide if a timer task should be processed. If wall clock move backwards (after we verifies that now() > task visibility timestamp when submitting the task to the task scheduler), the timer task will be dropped and cause workflow to stuck.
- Unit tests
- In worst case, we will execute a timer task logic earlier than expected.
- Could be. But the bug should be very rare as the use millisecond precision when doing time comparison in timer task …
> Handle system time move backward case in timer task processing

- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_active_task_executor_test.go
Return error from task executor if workflow back of timer is not fired.
To prevent outer layers to count no-op timers as fired.
Existing unit test
No
Yes
> Return error if workflow backoff timer is not fired

- service/history/queues/queue_immediate.go
- service/history/queues/queue_immediate_test.go
- service/history/queues/queue_scheduled.go
- service/history/queues/queue_scheduled_test.go
- service/history/shard/context.go
- service/history/shard/context_impl.go
- service/history/shard/context_mock.go
- Wrap ExecutionManager.GetHistoryTasks in shard context to handler shardOwnershipLost errors.
- Will need to follow up and audit all usage of this method and other methods on execution manager. This PR is only for fixing the issue we are seeing.
- If shard has no (api) traffic, and ownership already got lost in the background (from some persistence implementations). Task processing can get stuck forever trying to load tasks and see this shard ownership lost error.
- Unit test
> Handle shard ownership lost when reading history tasks

- tests/archival_test.go
- tests/testcore/functional_test_base.go
- tests/testcore/onebox.go
- tests/testcore/test_cluster.go
- tests/testdata/acquire_shard_deadline_exceeded_error.yaml
- tests/testdata/acquire_shard_eventual_success.yaml
- tests/testdata/acquire_shard_ownership_lost_error.yaml
- tests/testdata/client_cluster.yaml
- tests/testdata/es_cluster.yaml
- tests/testdata/ndc_clusters.yaml
- tests/testdata/tls_cluster.yaml
- tests/testdata/xdc_adv_vis_clusters.yaml
- tests/testdata/xdc_adv_vis_es_clusters.yaml
- tests/testdata/xdc_clusters.yaml
- tests/workflow_delete_execution_test.go
Refactor: move all archival related scaffolding to `ArchivalSuite`.
There was some archival related code in `FunctionalTestBase` which is used only be `ArchivalSuite`. No reason to have it the base struct.
Run tests.
Removed `Skip` for one archival tests. Added `Eventually` there. Run it multiply times and it never failed. If it start fail, might be skipped again.
No.
No.
> Refactor: move all archival related scaffolding to ArchivalSuite

- service/history/api/startworkflow/api.go
- service/history/configs/config.go
- tests/workflow_test.go
Make WorkflowIdConflictPolicy TerminateExisting follow the WorkflowIdReusePolicy after an _unsuccessful_ termination.
NOTE: The frontend change was made in https://github.com/temporalio/temporal/pull/7099
When the termination from TerminateExisting fails, the user would expect the WorkflowIdReusePolicy to be applied as the Workflow is not running.
Well ... there's no way to test this well right now. There are no unit tests; and the functional test cannot be written without the use of [testhooks](https://github.com/temporalio/temporal/pull/6938) since there is no other way to simulate the race condition here.
I manually added a `sync.Once` into the code that terminates the workflow and can confirm the expected behavior.
> Follow ReusePolicy AllowDuplicateFailedOnly with TerminateExisting

- service/worker/pernamespaceworker.go
- Add periodic refresh back to `perNamespaceWorkerManager`
- Pass full `refreshArgs` to `getWorkerAllocation` and use `ns` from `args`
- Rename fields in `workerAllocation`
- Small optimization to building the component set + options string
- The dynamic config subscriptions only reacted to the two settings directly used by `perNamespaceWorkerManager`, not the enabled/disabled settings in components.
- `getWorkerAllocation`/`getLocallyDesiredWorkers` was reading `w.ns` which is technically a data race since `w` is not locked there.
- The fields are not used outside the package.
existing tests
> Add periodic refresh back to per-namespace worker manager

- tests/add_tasks_test.go
- tests/advanced_visibility_test.go
- tests/archival_test.go
- tests/deployment_test.go
- tests/dlq_test.go
- tests/gethistory_test.go
- tests/namespace_delete_test.go
- tests/purge_dlq_tasks_api_test.go
- tests/schedule_test.go
- tests/testcore/flag.go
- tests/testcore/test_cluster.go
- tests/testdata/cluster.yaml
- tests/versioning_3_test.go
- tests/versioning_test.go
- tests/xdc/advanced_visibility_test.go
- tests/xdc/test_data.go
Refactor: remove `cluster.yaml` config.
It is the same as `es_cluster.yaml` but doesn't have `esConfig` section. The intent was to use this config file when Elasticsearch is not used. But this section is not used if SQL persistence is used, so there is no harm to always use `es_cluster.yaml`.
I am going to significantly decrease number of config files for functional tests (if not remove them all). This is small step in this direction.
Run tests.
No risks.
No.
No.
> Refactor: remove cluster.yaml config

- service/history/api/unpauseactivity/api.go
- service/history/workflow/activity.go
- service/history/workflow/activity_test.go
Add a jitter (duration) to the UnpauseActivity functions.
part of batch API work. It may be unsafe to unpause many activities at once.
Jitter allows to "spread" starting of unpause activities over a specified period of time.
unit tests
N/A
N/A
N/A
> Add jitter to UnpauseActivity functions

- components/nexusoperations/events.go
- components/nexusoperations/events_test.go
- components/nexusoperations/workflow/commands.go
- components/nexusoperations/workflow/commands_test.go
- tests/xdc/nexus_state_replication_test.go
Reinstate what was reverted in https://github.com/temporalio/temporal/pull/7024
Add deletion calls for Nexus operation nodes once they reach a terminal
state (Completed, Failed, Canceled, Timed Out). Previously, terminal
operations lingered in the state machine, potentially causing confusion
and wasting resources. In addition, this PR addresses previously
existing TODOs related to node cleanup.
- **Automatic Node Deletion on Terminal States:**  
Operations are now removed from the state machine immediately after they
complete, fail, cancel, or time out.
- **Handler Updates:**  
The command handlers (schedule and cancel) now reflect the new terminal
state deletion. Attempts to cancel an operation that has already reached
a terminal state will produce a clear, non-retryable error.
- **Tests …
> Nexus: Delete state machine on terminal state -- Part 3 (#6984)

- common/persistence/client/fx.go
- common/telemetry/config.go
- common/telemetry/grpc.go
- common/telemetry/tags.go
- service/history/archival_queue_factory.go
- service/history/archival_queue_factory_test.go
- service/history/archival_queue_task_executor_test.go
- service/history/memory_scheduled_queue_factory.go
- service/history/outbound_queue_factory.go
- service/history/queue_factory_base.go
- service/history/queues/executable.go
- service/history/queues/executable_factory.go
- service/history/queues/executable_test.go
- service/history/queues/memory_scheduled_queue_test.go
- service/history/queues/queue_base_test.go
- service/history/queues/queue_scheduled_test.go
- service/history/queues/reader_test.go
- service/history/queues/slice_test.go
- service/history/queues/speculative_workflow_task_timeout_queue.go
- service/history/timer_queue_active_task_executor_test.go
- service/history/timer_queue_factory.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/transfer_queue_active_task_executor_test.go
- service/history/transfer_queue_factory.go
- service/history/transfer_queue_standby_task_executor_test.go
- service/history/visibility_queue_factory.go
- service/history/visibility_queue_task_executor_test.go
Added support for OpenTelemetry (OTEL) to task processing.
To extend the OTEL coverage and gain insight into task processing.
Ran Grafana Tempo locally:
I don't expect any negative performance impact on task processing because most operations are noops.
> OTEL in task processing

- service/worker/batcher/activities.go
Extract parameters from batch unpause activity request, convert them to ManageActivity params, and call ManageActivity API.
To connect batch unpause to a single API.
existing tests
N/A.
N/A
No
> populate params for unpause batch operation

- service/history/api/resetactivity/api.go
- service/history/workflow/activity.go
- service/history/workflow/activity_test.go
- tests/activity_api_reset_test.go
Subj. Add "unpause" flag to the reset activity function.
Feature request. Reset activity should be able to also unpause the activity.
unit test. Also add/modify func tests
N/A
N/A
No
> Add unpause to reset activity

- .github/workflows/trigger-publish.yml
This commit references a repository GitHub actions variable, `SHOULD_TRIGGER_DOCKER_BUILD`, and only triggers a docker build if this variable is set to `true`. This is to prevent forks of this repository from triggering builds in the `temporalio/docker-builds` repository, which is almost certainly not what those forks want.
> Only trigger Docker builds if explicitly enabled in repository config

- service/frontend/admin_handler.go
- service/frontend/operator_handler.go
- service/frontend/workflow_handler.go
- service/history/handler.go
- service/matching/handler.go
Embed `Unimplemented*ServiceServer` instead of `Unsafe*ServiceServer` in all gRPC handlers.
Embedding `Unimplemented*ServiceServer` is the right way to keep backward compatibility with future interface changes.
Build and run.
No risks.
No.
No.
> Embed Unimplemented*ServiceServer instead of Unsafe*ServiceServer

- tools/testrunner/testrunner.go
Previous behavior was to not retry if number of failures was more than 10. We want to be more forgiving.
> Retry tests with previous attempt args if more than 10 tests fail

- common/rpc/interceptor/namespace_validator.go
Remove read workflow API during namespace handover
Read workflow data during namespace handover could lead to read-after-write inconsistency.
> Remove read workflow API during namespace handover

- tests/xdc/base.go
- tests/xdc/failover_test.go
Wait for clusters to be synced instead of using Sleep. Make sure second run is started before failover.
Current implementation depends on the timing which is not reliable.
Repeatedly run the test locally and no failure found.
> fix flaky xdc test TestCronWorkflowCompleteAndFailover

- common/testing/testhooks/test_impl.go
Handle nil TestHooks in Get.
This could happen when running unit tests with `test_dep`, for example.
Ran matching tests with and without `test_dep` tag.
> Handle nil TestHooks

- components/scheduler/config.go
- components/scheduler/generator_executors_test.go
- components/scheduler/helper_test.go
- A few tweaks and additional helpers to the tests. Most importantly, replaced fakeEnv's time.Now() with a mock.
- Config values updated
- I need to be able to manually advance fakeEnv's time in the Executor tests.
- go test -v
- None, HSM scheduler isn't in use yet
- no
- no
> [Scheduled Actions V2] Tweaks to the test helpers and default configs

- service/history/workflow/update/update.go
- tests/update_workflow_test.go
Moved check for `registryClearedErr` out of `if u.accepted.Ready()...` block.
Stay tuned! :-)
Run flaky test 1000 times.
No risks.
No.
No.
> Workflow Update: check registryClearedErr in a proper place

- cmd/tools/genrpcserverinterceptors/main.go
- common/rpc/interceptor/logtags/admin_service_server_gen.go
- common/rpc/interceptor/logtags/history_service_server_gen.go
- common/rpc/interceptor/logtags/matching_service_server_gen.go
- common/rpc/interceptor/logtags/workflow_service_server_gen.go
- common/rpc/interceptor/logtags/workflow_tags.go
- common/telemetry/grpc.go
Added support for our OTEL interceptor to parse tags from the gRPC response (not just the request).
Without annotating the responses, traces from calls like `PollWorkflowTaskQueue` cannot be queried for since the ID is only on the response but not the request.
Verified in Tempo:
There is one other caller of `Extract`, but they are only feeding in the request payload. So no behavior change is expected.
> OTEL annotates gRPC responses

- components/nexusoperations/completion.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/nexusoperations/statemachine.go
- components/nexusoperations/statemachine_test.go
- service/history/workflow/mutable_state_impl.go
- tests/nexus_workflow_test.go
- tests/xdc/nexus_state_replication_test.go
We didn't go through the same code path in active and passive clusters and never deleted the state machines as intended.
Added a functional test.
> Actually delete HSMs on Nexus completion

- common/metrics/metric_defs.go
- common/metrics/runtime.go
Add 2 new metrics reporting runtime memory information for the number of GC's since program start, and the total time spent in GC pauses.
While there were some existing metrics for these values, they were reported as a histogram and timer, and interpretation of them is complex. Reporting these values without any extra processing will make using them easier.
Ran locally & verified that these metrics were present via a local prometheus setup.
No.
> add gauge metrics for gc count and pause

- service/history/queues/executable.go
Include the task data in the OTEL span when OTEL debug is enabled.
Help with debugging/learning the system.
Checked in Grafana.
Example:
```
"payload": {
"NamespaceID": "a9aac188-6188-41f0-b7de-16ef62cb7193",
"RunID": "0194af8c-df6d-7829-9c35-a88cc288da89",
"ScheduledEventID": 2,
"TaskID": 1048633,
"TaskQueue": "TestUpdateWorkflowSuite/TestUpdateWorkflow_CompleteWorkflow_AbortUpdates/update_admitted_workflow_completed_task_queue",
"Version": 0,
"VisibilityTimestamp": "2025-01-29T00:53:52.621907Z",
"WorkflowID": "TestUpdateWorkflowSuite/TestUpdateWorkflow_CompleteWorkflow_AbortUpdates/update_admitted_workflow_completed_workflow_id"
}
```
Only enabled in debug mode.
> Include task payload in OTEL debug

- service/history/timer_queue_standby_task_executor_test.go
Fix test TestProcessWorkflowRunTimeout_Pending.
This test was flaky, and relying on the test suite `now` variable to be very close to the mutable state start time. If the difference is less than 1ms, I think the test passes.
> Fix test TestProcessWorkflowRunTimeout_Pending

- common/dynamicconfig/constants.go
- common/membership/ringpop/factory.go
- service/history/configs/config.go
- service/history/service.go
Add `history.alignMembershipChange` to allow history to use aligned membership changes also.
Better behavior during restarts/deployments.
not yet
> Add history.alignMembershipChange setting

- common/persistence/persistence_interface.go
Added a few `,omitempty` across the data persistence types on list and map fields.
Some of these may never be empty, but it's easier to just annotate them all. 
When these types are JSON serialized (for debugging/observability), the empty fields are just noise.
Checked OTEL output.
No _meaningful_ behavior change is expected.
> Omit empty persistence fields in JSON

- internal/effect/buffer.go
- service/history/api/respondworkflowtaskcompleted/api.go
Reduce logging on `WFTCompletedHandler.Invoke` error. Now it is emitted only when effects were actually cleared. 
Remove noisy logs.
Didn't test.
No risks.
No.
No.
> Reduce logging on WFTCompletedHandler.Invoke error

- service/worker/migration/handover_workflow.go
- service/worker/migration/handover_workflow_test.go
- tests/xdc/failover_test.go
Reconfig the maximumHandoverTimeoutSecondto 30s but change the actual input to 10s  for the default tests.
> Quick fix to reconfig maximumHandoverTimeoutSeconds

- service/worker/deletenamespace/fx.go
- service/worker/deletenamespace/reclaimresources/activities.go
- service/worker/deletenamespace/reclaimresources/activities_test.go
- service/worker/deletenamespace/reclaimresources/workflow.go
- service/worker/deletenamespace/reclaimresources/workflow_test.go
Delete Namespace: read cache refresh interval from dynamic config instead of hardcoded const.
`cacheRefreshInterval` used to be a const, and it was kinda ok to duplicate it in delete namespace WF code. But now it is coming from dynamic config, and WF should read it from there too.
Modified existing unit tests.
No risks.
No.
No.
> Delete Namespace: read cache refresh interval from DC

- service/history/api/queryworkflow/api.go
Add workflow_status tag to workflow query metrics
So we can tell what percentage of workflow query are made to closed workflows.
Local test, and verify seeing metrics like:
direct_query_dispatch_non_sticky_success{operation="QueryWorkflow",service_name="history",workflow_status="Completed"} 1
> Add workflow status tag to query workflow metrics

- service/frontend/admin_handler.go
- service/frontend/admin_handler_test.go
- service/history/handler.go
- service/history/handler_test.go
Update DescribeHistoryHost to check shard ownership
When providing shard id to describe history host, it needs to check shard ownership to make sure it connect to the correct history host.
New unit test
> Update DescribeHistoryHost to check shard ownership

- service/worker/batcher/workflow.go
- tests/activity_api_batch_unpause_test.go
Add functional tests for batch activity unpause.
Part of activity API work.
By adding tests.
No risks.
Not documented.
No.
> Activity API: functional tests for batch activity unpause

- common/nexus/failure.go
- components/nexusoperations/completion.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- go.mod
- go.sum
- service/frontend/nexus_handler.go
- service/history/handler.go
- service/history/workflow/mutable_state_impl.go
- tests/nexus_api_test.go
- tests/nexus_workflow_test.go
- tests/xdc/nexus_request_forwarding_test.go
- tests/xdc/nexus_state_replication_test.go
- Reverted https://github.com/temporalio/temporal/pull/7051
- Upgraded the Nexus Go SDK to include recent changes
- Update usage of deprecated Nexus SDK APIs
- Handle `HandlerError.Retryable()`
> Nexus error reyhdration pt2

- service/history/api/create_workflow_util.go
- service/history/api/recordworkflowtaskstarted/api.go
- service/history/api/respondworkflowtaskcompleted/api.go
- service/history/api/respondworkflowtaskcompleted/api_test.go
- service/history/api/verifyfirstworkflowtaskscheduled/api_test.go
- service/history/history_engine_test.go
- service/history/ndc/workflow_resetter.go
- service/history/ndc/workflow_resetter_test.go
- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- service/history/workflow/mutable_state_mock.go
- service/history/workflow/update/registry.go
- service/history/workflow/workflow_task_state_machine.go
- service/history/workflow/workflow_test/mutable_state_impl_test.go
Refactoring to allow Update registry to allow suggesting CAN.
Preparation for implementation. "Make the change easy, then make the easy change".
> Update Registry suggest CAN refactor

- common/persistence/persistence_interface.go
Omitting redundant persistence data blobs.
Since the original data is already there, serializing the blobs is not useful. Removing it reduces noise.
> OTEL omit redundant persistence blobs

- service/history/ndc/history_replicator.go
- service/history/replication/executable_backfill_history_events_task.go
- service/history/replication/executable_sync_versioned_transition_task.go
- service/history/replication/executable_verify_versioned_transition_task.go
- service/history/replication/raw_task_converter.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/task_generator.go
1. Improve logging on replication task execution
2. Check versioned transition existence before reading it. (avoid panic)
3. When SyncState returning `nil` error and 'false` doContinue, ignore the task instead of keep retrying. Otherwise this will cause DLQ.
4. release workflow lock before `convertTaskEquivalents`, otherwise deadlock.
Fix on state based replication
Ran tasks on test clusters
n/a
n/a
no
> Fix on state based replication

- service/matching/user_data_manager.go
- service/worker/workerdeployment/client.go
- tests/deployment_version_test.go
- tests/worker_deployment_test.go
- Changed areas of code in the deployment client whereby we were using update-with-start instead of update
- We don't want users to create workflows on operations like setCurrent/setRamping - we advice users to first create them by registering your workers
- Bunch of tests have been modified and the suites now pass
> update with start -> update

- common/metrics/config.go
- common/metrics/config_test.go
- common/metrics/consts.go
- common/metrics/defs.go
- common/metrics/opentelemetry_provider.go
- common/metrics/otel_metrics_handler.go
- common/metrics/otel_metrics_handler_test.go
- common/metrics/otel_options.go
- common/metrics/otel_options_test.go
- common/metrics/tally_metrics_handler_test.go
- Add backward compatibility configs for tally to otel migration
- There are some breaking changes when switching from tally to otel metric framework.
1. Unit name will be appended to the metric name
2. `_total` will be appended to counter metrics
3. Timer metric will be emitted as milliseconds instead of seconds
This PR adds configs for controlling both behaviors when using otel framework so that the behavior will be the same as tally.
- Unit tests
- Tested locally with various combination of configurations.
- No risk by default. If new options are enabled, timer metric value may be wrong or not bucketed correctly.
- No.
> Add backward compatibility configs for tally to otel migration

- common/metrics/config.go
- common/metrics/config_test.go
- Always use OTEL as metric handler
- Deprecate Tally metrics framework
- Will test locally and also monitor CI
- Metric could be different and break existing dashboard & alerting systems for existing tally users.
- No. We keep the behavior unchanged for tally users.
- No
> Always use OTEL as metric handler

- service/history/workflow/task_generator.go
- service/history/workflow/task_generator_test.go
- service/history/workflow/task_refresher.go
Delete state machine timers every time we close a transaction on mutable state.
Part of the work on state machine deletion
Unit tests
> Cleanup state machine timers on machine deletion

- service/history/workflow/context.go
- service/history/workflow/update/registry.go
- service/history/workflow/update/registry_test.go
Enforce the configurable inflight size limit for Updates.
Instead of only using a fixed number of inflight Updates, a size-based approach is more helpful.
The limit is at 10MB right now. But will likely be lowered very soon.
Added tests.
> Enforce Update Registry size limit

- service/history/workflow/mutable_state_impl.go
Copying `executionInfo.ChildrenInitializedPostResetPoint` over into new run in continue-as-new operation.
This is needed so that we can apply appropriate reset policy (if needed) to children started in new runs.
manual test.
N/A
Documentation pending.
No
> [Reset] Carry over ChildrenInitializedPostResetPoint when continue-as-new

- common/metrics/metric_defs.go
- common/metrics/tags.go
- common/nexus/failure.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/nexusoperations/fx.go
- service/frontend/nexus_handler.go
- service/frontend/nexus_http_response_writer.go
- tests/nexus_workflow_test.go
Propagating the Nexus response header `Temporal-Nexus-Failure-Source` to the outbound queue executor.
This header is included as a label on the outbound queue metrics so that we can exclude expected user errors from our alerts.
> Propagate Nexus failure source header to outbound executor metrics

- common/persistence/persistence-tests/cluster_metadata_manager.go
- common/persistence/persistence-tests/metadata_persistence_v2.go
Improved persistence tests to account for differing behavior of some persistence backends.
These tests made assumptions about persistence that don't necessarily apply to all persistence backends. Specifically the tests assumed:
- All persistence backends return a final empty page when paginating results
- All persistence backends are guaranteed to expire TTL'd records (nearly) instantly upon expiration.
Ran the tests with various persistence backends
This is a test-only update
No changes.
No
> Improve cluster metadata and metadata persistence tests

- service/worker/deletenamespace/deleteexecutions/workflow.go
- service/worker/deletenamespace/deleteexecutions/workflow_test.go
- service/worker/deletenamespace/reclaimresources/workflow.go
- service/worker/deletenamespace/reclaimresources/workflow_test.go
Delete Namespace: add `stats` query to `DeleteExecutionsWorkflow`.
`DeleteExecutionsWorkflow` is long running Workflow which can run for hours. After namespace is marked as deleted there is no easy way to find out how many Workflow Executions were in it and how many left to delete. New query handler will return all current statistics.
No risks. Workflow code changes are backward compatible.
No.
No.
> Delete Namespace: add stats query to DeleteExecutionsWorkflow

- common/persistence/cassandra/matching_task_store.go
- common/persistence/data_interfaces.go
- common/persistence/persistence_interface.go
- common/persistence/sql/task.go
- common/persistence/task_manager.go
- common/persistence/tests/task_queue_user_data.go
- common/stream_batcher/batcher.go
- service/matching/matching_engine.go
Following from #7039, the batch update isn't required to be transactional. The persistence interface returns an error if any failed, but update success is reported individually.
ease adaptation to less-transactional stores
updated integration test
> Allow batched user data updates to succeed individually

- tests/xdc/failover_test.go
Fix flaky `TestForceMigration_ResetWorkflow` test.
Completion of `ForceReplication` Workflow doesn't mean that all replication tasks are delivered and processed on standby cluster. Test needs to wait for replication queue to drain before making assertions.
Run it.
No risks.
No.
No.
> Fix flaky TestForceMigration_ResetWorkflow test

- common/dynamicconfig/constants.go
As of https://github.com/temporalio/temporal/pull/7254 a total in-flight payload size limit is enforced. The default is 10MB right now, this PR makes it 20MB.
As the max payload size for Updates is 2MB and the current Update in-flight limit is 10, the effective limit right now is (about) 20MB.
By enforcing a payload-based limit, we can raise the total in-flight update limit from 10 to ... more, eventually.
But we decided to couple these together, ie increasing the in-flight number when introducing the in-flight size limit.
Therefore we'll set it to be a noop effectively for now.
> Change total in-flight update payload size limit

- common/metrics/config.go
- common/metrics/opentelemetry_provider.go
- Log error instead of panic for existing tally users when prometheus listener can't be created.
- No behavior change for existing OTEL users
- For backward compatibility
> Log prometheus listener error by default

- common/worker_versioning/worker_versioning.go
- service/history/api/respondworkflowtaskcompleted/api.go
- service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler.go
- service/history/workflow/mutable_state_impl.go
- service/worker/deployment/deployment_reachability.go
- service/worker/deployment/deployment_reachability_test.go
- service/worker/workerdeployment/client.go
- service/worker/workerdeployment/version_workflow.go
- tests/versioning_3_test.go
- tests/worker_deployment_test.go
Making sure the following SAs are populated correctly for Versioning v3.1
- TemporalWorkerDeployment 
- TemporalWorkerDeploymentVersion 
- TemporalWorkflowVersioningBehavior
- BuildIds
> Test and fix Deployment SAs

- tests/testcore/functional_test_base.go
- tests/testcore/test_cluster.go
- tests/xdc/activity_api_test.go
- tests/xdc/base.go
- tests/xdc/failover_test.go
- tests/xdc/history_replication_dlq_test.go
- tests/xdc/history_replication_signals_and_updates_test.go
- tests/xdc/nexus_state_replication_test.go
- tests/xdc/stream_based_replication_test.go
- tests/xdc/user_data_replication_test.go
Refactor: remove `clusterNames` field from `xdcBaseSuite`.
It can come from `testCluster` itself and passing both of them all over the code was annoying.
Run tests.
No risks.
No.
No.
> Refactor: remove clusterNames field from xdcBaseSuite

- components/nexusoperations/completion.go
- components/nexusoperations/config.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- components/nexusoperations/frontend/fx.go
- components/nexusoperations/frontend/handler.go
- service/frontend/service.go
- service/frontend/workflow_handler.go
- tests/nexus_api_test.go
- tests/nexus_workflow_test.go
Validate the Nexus operation tokens don't exceed a configured length in all APIs that accept it.
Also tidied up code in `completions.go` where we applied the start event no via the event definition, skipping the `MachineTransition` call. There won't be any behavior change since this transition did not generate tasks.
It's dangerous for us to accept strings without limiting their length.
Added all of the relevant tests.
> Validate Nexus operation token

- service/history/api/respondworkflowtaskcompleted/api.go
- service/history/workflow/update/abort_reason.go
- service/history/workflow/update/errors_failures.go
- service/history/workflow/update/update.go
- tests/update_workflow_test.go
Workflow Update: abort updates with non-retryable error if WFT fails unexpectedly.
If WFT fails while worker is trying to complete it (because of different size limit violations, or bug in SDK, or other validation errors), server clears Update registry and aborts Updates with retryable `Unavailable` error. Internal retries recreate Update and new WFT. If workers keeps sending same malformed/invalid response then WFT fails again and all of these repeats in the loop until client timeout.
Things are getting worse if Update message is the cause of the WFT failure. In this case, because retries of Update and WFT are not synced, not every WFT got Update message, and empty WFT completes successfully. This means that it starts to jump back and forth between completed and failed state and never …
> Workflow Update: abort updates with non-retryable error if WFT fails unexpectedly

- Makefile
- common/persistence/tests/sqlite_test.go
- tools/tdbg/dlq_service_test.go
Run persistence integration test again.
They should be running 🙃 Somehow they were omitted when either `gotestsum` or `go test` parse the space-separated list of packages to test.
> Run integration tests again

- common/metrics/config.go
- common/metrics/config_test.go
This reverts commit c156e8467987dc8a919a1ed4437464713d5c2175.
- Revert "Always use OTEL as metric handler (#7265)"
- StatsD still needs tally to function
- OTEL metric handler doesn't support Prefix and the same customized/default sanitization logic as tally
> Revert "Always use OTEL as metric handler (#7265)"

- tests/worker_deployment_test.go
- fix `TestWorkerDeploymentSuite/TestForceCAN_NoOpenWFS`
- no one likes ❌ on their CI status bar
- Ran it locally
- Ran it 50 times against postgres + cassandra in CI
> fix a versioning 3.1 flake 

- service/history/ndc/transaction_manager_existing_workflow.go
- service/history/ndc/transaction_manager_existing_workflow_test.go
Remove check that prevent passive update workflow after workflow closed
The assumption is no longer hold as Nexus callback could update workflow even after workflow is closed.
n/a
no risk
n/a
no
> Remove check that prevent passive update workflow after workflow closed

- common/metrics/metric_defs.go
- service/history/handler.go
- service/history/ndc/activity_state_replicator.go
- service/history/ndc/activity_state_replicator_test.go
- service/history/ndc/history_replicator.go
- service/history/ndc/hsm_state_replicator.go
- service/history/ndc/hsm_state_replicator_test.go
- service/history/ndc/transaction_manager_new_workflow.go
- service/history/ndc/transaction_manager_new_workflow_test.go
- service/history/ndc/workflow_state_replicator.go
- service/history/replication/dlq_handler.go
- service/history/replication/eventhandler/resend_handler.go
- service/history/replication/executable_activity_state_task.go
- service/history/replication/executable_backfill_history_events_task.go
- service/history/replication/executable_history_task.go
- service/history/replication/executable_history_task_test.go
- service/history/replication/executable_sync_hsm_task.go
- service/history/replication/executable_sync_versioned_transition_task.go
- service/history/replication/executable_task.go
- service/history/replication/executable_task_mock.go
- service/history/replication/executable_verify_versioned_transition_task.go
- service/history/replication/executable_workflow_state_task.go
- service/history/replication/fx.go
- service/history/replication/stream.go
- service/history/replication/task_processor_manager.go
Introduce ErrDuplicate at replication code path to distinguish duplicated replication task
To better emit replication lag metrics
test will be added later.
> Identify duplicated replication task and skip emitting lag metrics for duplicated replication task

- components/nexusoperations/config.go
- components/nexusoperations/workflow/commands.go
- components/nexusoperations/workflow/commands_test.go
Made `component.nexusoperations.disallowedHeaders` a global setting so it can be efficiently cached and fixed the usage of the default value.
The previous behavior was to append to the default value which is wrong.
> Fix Nexus disallow header dynamic config usage

- service/history/statemachine_environment.go
- service/history/statemachine_environment_test.go
add a condition check for transition history to decide if fallback is needed.
Handle the case where when task generated there is transition count but when processing tasks, the transition history is cleared because of disabling transition history. 
unit test
n/a
n/a
no
> Fix validateStateMachineRef when transition history is cleared

- service/matching/backlog_manager_test.go
- service/matching/forwarder.go
- service/matching/matcher.go
- service/matching/matching_engine.go
- service/matching/physical_task_queue_manager.go
- service/matching/physical_task_queue_manager_test.go
- service/matching/poller_history.go
Include all poll metadata (including rate limit request) in forwarded activity polls.
This has no real behavior change (the rate limit should be the same on all partitions already), but it fixes the rate limit reported in poller info for the root partition, which was getting cleared on forwarded polls and creating confusion.
> Include rate limit in forwarded activity poll

- common/metrics/metric_defs.go
- common/metrics/tags.go
- components/nexusoperations/config.go
- components/nexusoperations/metrics.go
- service/frontend/nexus_handler.go
- service/frontend/nexus_http_handler.go
- service/frontend/service.go
Add configuration that controls which additional metric tags are included with Nexus operation metrics
> Add configuration to enrich Nexus operation metrics

- service/history/transfer_queue_active_task_executor.go
- service/history/transfer_queue_active_task_executor_test.go
The parent will skip applying parent close policy only when it is reset and if we are taking the new reset flow (i.e `AllowResetWithPendingChildren` config is enabled)
This fixes a bug I introduced in https://github.com/temporalio/temporal/pull/6935. I am skipping the parent close policy whenever a parent is reset. This was done under the assumption that the server never allowed a parent to be reset which has a pending child. Unfortunately this assumption is not true and the server allowed resetting of parents with pending children in some cases. And in these cases the parent would apply the given parent close policy to the child. So, this change restores the original behavior.
Additionally we need to further fix this by skipping parent close policies only to children that were started …
> [Reset] Skip parent close policy only if the parent is reset and we are using the new reset flow.

- tests/nexus_workflow_test.go
The test started workflow that weren't cleaned up, causing extra requests to be generated making it harder to verify the metrics.
This fix makes it slightly better but not perfect.
> Reduce chance of flakes in TestNexusSyncOperationErrorRehydration

- service/worker/workerdeployment/client.go
- service/worker/workerdeployment/workflow.go
- tests/worker_deployment_test.go
- Building the worker deployment memo after the workflow has started rather than building it as part of the start-request. This should be done because we update the `routingConfig` when the workflow starts, which makes the memo outdated, hence leading to ListWorkerDeployment calls with stale data. 
- Also realized we may not need to build initial memo since Upsert takes care of adding `and` updating.
- Right now, there is a bug when users would ListDeployments without a current version being set. The expected answer in this scenario would be that current version is `__unversioned__` but the routingConfig shows to be empty.
- This happens because ListDeployments gets information from the memo stored inside the worker deployment workflows. Rigt now, the memo was being updated before the …
> RoutingInfo memo fix

- common/primitives/timestamp/duration.go
- common/primitives/timestamp/duration_test.go
- common/retrypolicy/retry_policy.go
- components/nexusoperations/workflow/commands.go
- service/frontend/namespace_handler.go
- service/frontend/workflow_handler.go
- service/history/api/command_attr_validator.go
- service/history/api/create_workflow_util.go
- service/worker/scheduler/spec.go
Adding back a cap for durations at 250 years.
To prevent serialization errors for very large proto durations.
New unit test
> Add back 250 year max duration cap

- service/history/ndc/hsm_state_replicator.go
- service/history/ndc/hsm_state_replicator_test.go
The node may not be found if the state machine was deleted in terminal a state and this cluster is syncing from an older cluster that doesn't delete the state machine on completion and we need to be backwards compatible with the previous release.
> Ignore state machine not found errors when syncing the HSM tree

- common/dynamicconfig/constants.go
- service/matching/config.go
- service/matching/physical_task_queue_manager.go
- service/matching/poller_history.go
- service/worker/workerdeployment/client.go
- service/worker/workerdeployment/version_workflow.go
- tests/worker_deployment_test.go
- tests/worker_deployment_version_test.go
- PollerHistoryTTL is now a dynamic config
- Versioning-3.1 tests required setting a low value for this config in order for some tests to work - right now, those tests were excluded from CI runs and that's not good.
- Unskipped the tests that were being skipped previously.
> Making poller history a dynamic config

- service/history/api/getworkflowexecutionhistory/api.go
- tests/xdc/history_replication_signals_and_updates_test.go
Retry to get workflow result when current branch changed. 
When current branch is changed, if caller is waiting for workflow result, we should not return error. Instead, we should get workflow result from the new branch.
unit test.
> Retry to get workflow result when current branch changed

- service/history/ndc/history_replicator.go
- service/history/replication/executable_activity_state_task.go
- service/history/replication/executable_history_task.go
1. Fix ReplicationHistoryEvents API
2. When cancel the task, also mark it as unbatchable
Fix the issue where the task are mistakenly deduped.
> Fix replication task batching race condition bug

- service/worker/workerdeployment/client.go
- service/worker/workerdeployment/util.go
- service/worker/workerdeployment/version_workflow.go
- tests/worker_deployment_test.go
- tests/worker_deployment_version_test.go
- Deleting a version that is draining should never be possible.
- modified a test to now test for this specific behaviour
> deletes not possible on "draining" workflows

- tests/testcore/functional_test_sdk_suite.go
- Allow suites using FunctionalTestSdkSuite to override client or worker options
- Default the SDK logger to the test logger
- More flexibility for tests
- Consistent logging
> Allow setting client/worker options in FunctionalTestSdkSuite

- service/matching/backlog_manager.go
- service/matching/matching_engine.go
- service/matching/physical_task_queue_manager.go
- service/matching/physical_task_queue_manager_interface.go
- service/matching/physical_task_queue_manager_mock.go
- service/matching/task_queue_partition_manager.go
- service/matching/task_queue_partition_manager_interface.go
- service/matching/task_queue_partition_manager_mock.go
Remove String methods from matching structs and interfaces.
These were just for debugging, but they're not really useful for that.
> Remove String methods from matching structs

- service/history/ndc/workflow_state_replicator.go
- service/history/ndc/workflow_state_replicator_test.go
Set history builder when no events appended
When new history branch is forked and assigned as current branch, we may not need to append events there but we should set history builder to update next event ID, otherwise the next eventId in mutable state does not match the version history.
i.e. 
local mutable state version history [100, 1], got a replication task to sync mutable state up to [80,1]. In this case, we will fork a new branch, but no event appended.
If we don't have this fix, the replication task will be landed in DLQ.
unit test
no risk
n/a
yes
> Set history builder when no events appended

- common/dynamicconfig/constants.go
Setting the dynamic config to true by default.
We want to make this feature turned on by default.
Flipped the flag and reset the workflow with a child. Verified that the reset goes through and parent makes progress when the reset-point is in between child init & completed events.
This is a new feature. If things don't work as expected then we can flip this flag back to false (globally of by namespace)
N/A
Yes
> [Reset] Set AllowResetWithPendingChildren to true by default

- service/matching/backlog_manager.go
- service/matching/physical_task_queue_manager.go
- service/matching/physical_task_queue_manager_interface.go
- service/matching/physical_task_queue_manager_mock.go
- service/matching/pri_matcher.go
- service/matching/pri_task_reader.go
- tests/versioning_3_test.go
- Use tqCtx in priTaskMatcher
- Clean up contexts in priTaskReader
- Small refactoring in priTaskReader
Followup from #7360 in priority branch
> Consolidate matching contexts in new matcher also

- tests/versioning_test.go
- These two tests keep on flaking and can be skipped since they are testing old versioning behaviour
- The flaky test report is spammed with versioning test and can be reduced.
> skipping old versioning tests

- common/metrics/config.go
- common/metrics/config_test.go
- common/metrics/opentelemetry_provider.go
- Support metric prefix in OTEL
- NOTE: this is a breaking change for OTEL users who current have the `Prefix` field set but also expect NOT to see the prefix in the emitted metric name.
- It's needed for backward compatibility for existing tally users as now we always otel implementation under the hood.
- It was missed when doing OTEL implementation initially. 
- Unit test
- Tested locally
> Support metric prefix in OTEL

- service/worker/workerdeployment/version_workflow.go
- tests/worker_deployment_test.go
- tests/worker_deployment_version_test.go
- Right now, when the child drainage workflow signals the version workflow that its drained, the future representing the child workflow is not updated.
- This is really bad as it is causing errors when rolling back onto a version that was previously drained.
- Also, ignore drainage signals if version is ramping or current, since the signal could arrive late
- Fixing errors
- Existing suite of tests + Shahab's demo shall test this too
- Added functional test that breaks without this fix and passes with the fix
Yes, I think?
> clear drainage future when drained, ignore drainage signals if version is current or ramping

- service/worker/deletenamespace/reclaimresources/workflow.go
#7215 introduced incompatible change in reclaim resources workflow code (extra local activity call). If new version is rolled out while previous workflow is running, it will generate NDE. This PR adds proper version check (patch API) to avoid it.
Bug fix.
Run upgrade locally.
No risks.
No.
Yes.
> Delete Namespace: fix incompatible change in reclaim resources workflow

- service/worker/workerdeployment/client.go
- `DescribeTaskQueueEnhanced` requests, in the frontend, have taskQueueType overridden to Workflow. Since worker-deployment activities directly call matching, it is important to set this field to Workflow.
- I noticed an error whereby I was filling the request structure with the missing task-queue's type rather than the workflow type. This was resulting in errors like:
```  msg="matching client encountered error" service=worker error="DescribeTaskQueue must be called on the root partition of workflow task queue if api mode is DESCRIBE_TASK_QUEUE_MODE_ENHANCED" service-error-type=serviceerror.InvalidArgument  ```
- This is not desirable and the PR aims to fix that. Note, requesting the correct type for the task-queue in a DescribeTaskQueueEnhanced call is done by filling in the field: …
> Attempt to fix random describe errors

- common/namespace/nsregistry/registry.go
- common/namespace/registry.go
- common/namespace/registry_mock.go
- service/history/handler.go
- service/history/handler_test.go
Change "cache" with "map" in nsRegistry.
There is no cache in registry per se. There is no adding one entry at a time, or removing one entry at a time.
Practically it is just a map. This makes code cleaner. 
Existing test.
Can't think of anything realistic.
> Replace cache with map in namespace registry

- components/scheduler/spec_processor.go
- service/worker/scheduler/spec.go
- service/worker/scheduler/spec_test.go
- service/worker/scheduler/workflow.go
- Fix handling of start time in schedule specs that could result in GetNextTime returning the time that it was given.
- Introduce a SpecVersion as part of tweakables but separate from workflow logic version to control this behavior.
- Non-workflow logic can always use the latest version.
- Workflow logic is initialized with the fixed version, which is technically not downgrade-compatible, but it should affect very few workflows.
This would lead to incorrect results and infinite loops.
new unit test, manual replay tests
This was done in a way to be upgrade-compatible, but is not downgrade-compatible for workflows that hit this edge case after the upgrade.
> Fix start time calculation in schedule spec

- components/nexusoperations/completion.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
The SDK requires a cause on failures with `HandlerFailureInfo` to properly reconstruct a `HandlerError` object.
Added a unit test.
> Always populate cause on nexus HandlerError

- components/scheduler/spec_processor.go
- service/worker/scheduler/spec.go
- service/worker/scheduler/spec_test.go
- service/worker/scheduler/workflow.go
Revert part of #7389, the spec version mechanism is unnecessary since GetNextTime is always called in a side effect.
simplify
existing tests
> Remove schedule spec version

- common/nexus/endpoint_registry.go
- common/nexus/endpoint_registry_test.go
Change Nexus endpoint registry backoff logic to allow faster reload.
Specifically, we don't wait between polls if the data changes now, and we don't back off exponentially when no changes occur. In the worst case where the remote has a bug, we will poll the registry every second, which is roughly what the current namespace registry refresh interval is but since there won't be any changes, no new data should be transmitted and our in memory cache should stay valid and won't cost any CPU to reconstruct.
The previous logic was causing high delays in test scenarios where endpoints were created very frequently, causing the refresh loop to back off more with every successful attempt. The more tests we added the longer it took to refresh the endpoints, causing later tests to eventually time out.
> Change Nexus endpoint registry backoff logic to allow faster reload

- service/history/workflow/context.go
- Set workflowContext.MutableState only when mutable state is not nil
- The case won't happen today as `NewMutableStateFromDB` never returns nil, but could happen in the future.
- Prevent potential NPE when the interface value is not nil but points to a nil value. 
- Tested in cicd
- N/A
- N/A
- No
> Fix potential NPE in workflow context

- chasm/tree.go
- CHASM: define exported Tree methods
- CHASM tree is the core of the entire CHASM framework. Although its own implementation is complex, by defining its exported method, we can unblock the work needed in mutable state, chasm engine & replication
- N/A, not actual implementation in this PR.
> CHASM: define exported Tree methods

- common/testing/protoassert/pretty_print.go
- tests/workflow_test.go
Fix flaky tests `TestStartWorkflowExecution_UseExisting_OnConflictOptions`.
Fix proto assert library bugs.
Callbacks in the describe workflow response is not in the same order as they are added.
> Fix flaky test TestStartWorkflowExecution_UseExisting_OnConflictOptions

- service/worker/workerdeployment/client.go
- tests/worker_deployment_version_test.go
- Returning NonRetryable errors when version to be deleted is current/ramping.
- To not lock workflow state.
- Modified existing tests by reducing the context timeout value and noticing things pass. Moreover, added another operation after a delete request such as the one mentioned above to verify workflow is not in a locked state.
> Non-Retryable error returned when deleting current/ramping version

- common/authorization/default_token_key_provider.go
- go.mod
- go.sum
Update go-jose lib
v2 is deprecated, v3 is in maintenance mode, v4 is current active version.
build and existing tests
No
No
No
> Update go-jose lib

- service/history/api/recordchildworkflowcompleted/api.go
- service/history/history_engine2_test.go
Check ChildFirstExecutionRunId only if exists in request.
Reason: If one server is using old version and doesn't have ChildFirstExecutionRunId in request, the check will fail.
If one server is using old version and doesn't have ChildFirstExecutionRunId in request, the check will fail.
unit test.
> check ChildFirstExecutionRunId only if exists in request.

- service/worker/workerdeployment/client.go
- tests/worker_deployment_test.go
- Sorting version summaries in DescribeWorkerDeployment calls with the newest version coming at the top.
- Correctness and better user functionality.
- Added a new functional test + modified an existing one.
> Sorting version summaries in DescribeWorkerDeployment calls

- tests/nexus_workflow_test.go
Add functional test for attaching callbacks in Nexus operations
> Add functional test for attaching callbacks in Nexus operations

- service/history/ndc/events_reapplier.go
- service/history/ndc/events_reapplier_test.go
Do not schedule workflow task after reapplying events if wf is no longer running
After reapplying events (TERMINATED), workflow is no longer running. We should not schedule any workflow task after that.
unit test.
> Do not schedule workflow task after reapplying events if wf is no longer running

- service/history/fx.go
- service/history/shard/context.go
- service/history/shard/context_factory.go
- service/history/shard/context_impl.go
- service/history/shard/context_mock.go
- service/history/shard/context_testutil.go
- Wires up CHASM registry to shard context
- It's needed throughout history service
> [CHASM] Wire ChasmRegistry into shard.Context

- common/log/tag/tags.go
- common/softassert/softassert.go
- common/testing/testlogger/testlogger.go
- tests/deployment_test.go
- tests/schedule_test.go
- tests/testcore/functional_test_base.go
- tests/testcore/functional_test_sdk_suite.go
- tests/tls_test.go
- tests/versioning_test.go
- tests/worker_deployment_version_test.go
- Added a new function `softassert.That` that logs an error if the provided condition is false
- Added `testlogger.Testlogger` (copied and slightly modified from our internal repository) to functional tests
To allow developers to verify pre- and post-conditions in their code.
**Why not panic?** Maybe in the future. For now, we're happy with finding these failed assertions in functional tests.
**What about nightlies/long-haul tests?** I've filed a ticket to detect a failed assertion there and surface them as an alert.
Planted a failing assertion.
**The error log:**
```
logger.go:146: 2025-03-04T20:50:08.578Z	ERROR	log/zap_logger.go:154	Unexpected Error log encountered: failed assertion: wake called twice	{"host": "127.0.0.1:35427", "component": "matching-engine", "wf-task-queue-name": …
```
> Assertion function

- tests/versioning_3_test.go
- `Versioning3FunctionalSuite` creates a large number of deployments in a single namespace. It is important to override the limit to not make the suite fail.
- Ran this locally and it works. Existing CI.
> Fix Versioning3FunctionalSuite to run locally

- common/log/zap_logger.go
- common/testing/testlogger/testlogger.go
Ports `TEMPORAL_TEST_LOG_FORMAT` and `TEMPORAL_TEST_LOG_LEVEL` to testlogger.TestLogger.
To not break developer setups.
> Port previous NewTestLogger flags over

- common/log/tag/tags.go
- common/nexus/trace.go
- common/resource/fx.go
- components/nexusoperations/executors.go
- components/nexusoperations/frontend/handler.go
- service/frontend/fx.go
- service/frontend/nexus_handler.go
- service/frontend/nexus_http_handler.go
- service/history/fx.go
Added additional tracing logs for forwarded Nexus HTTP requests.
Forwarded requests create a new request so they were not copying over the `httptrace.ClientTrace` set in the executors.
> Add HTTP tracing to forwarded Nexus requests

- common/dynamicconfig/constants.go
- service/matching/config.go
- service/matching/pri_matcher.go
- service/matching/pri_task_reader.go
- Add dynamic config for `matching.getTasksReloadAt`
- Add dynamic config for `matching.backlogTaskForwardTimeout`
tuning ability
> Move two settings into dynamic config

- service/matching/config.go
- service/matching/physical_task_queue_manager.go
- service/matching/unloadcause_string_gen.go
- tests/priority_fairness_test.go
When `MatchingUseNewMatcher` changes, unload task queue (and let it get reloaded).
Easily enable/disable new matcher without manually reloading task queues.
New functional test to flip back and forth, manually verified reload was happening.
> Reload task queues on change to new matcher setting

- service/matching/matcher_data.go
- service/matching/physical_task_queue_manager.go
- service/matching/pri_matcher.go
- service/matching/pri_task_reader.go
> Use assertion function

- common/persistence/cassandra/matching_task_store.go
- common/persistence/data_interfaces.go
- common/persistence/sql/task.go
- service/matching/db.go
- Track last changed time and last written time in taskQueueDB.
- Skip write in SyncState when unchanged, unless it's been over 12 hours. Note this only applies to the new backlog manager.
Avoid unnecessary persistence operations, improve scalability
will be tested in load tests for new matcher/backlog manager
> Avoid unnecessary task queue metadata writes

- service/worker/workerdeployment/util.go
- service/worker/workerdeployment/version_workflow.go
- Right now, entity workflows related to versioning have infinite number of retries happening. In the case of an unforeseen error, this might leave our internal entity workflows locked and might require manual intervention.
- The activity context, being used in all of the activities related to the worker-deployment workflows, now has a maximum number of attempts set to 5. This shall ensure that on the eve of an unforeseen error, the deployment workflow will unlock itself after a maximum time of ~5 mins. [ ~5 mins calculated by doing math involving backoff coefficient, initial interval and maximum attempts ]  
- To not lock our own workflows.
- Current Suite of tests to verify nothing is broken.
> stop infinite activity retries in the entity workflows

- tests/versioning_3_test.go
Reenable new matcher for versioning 3 tests. This works now after various fixes on the branch and on main.
Test coverage
> Reenable new matcher for versioning 3 tests

- service/history/replication/stream.go
- service/history/replication/stream_receiver.go
- service/history/replication/stream_sender.go
- service/history/replication/stream_test.go
Apply backoff retry for application error in replication stream
use backoff retry on application errors i.e. resource exhausted error
> Apply backoff retry for application error in replication stream

- README.md
Before
After
Improve the first impression of a visitor:
- "All Tests" badge is either green (which doesn't really mean much); or is red due to a flaky test (which looks bad)
- "Codecov" badge looks worse than it is: it should be yellow but is orange.
- "Codecov" badge updates in real-time; meaning it shows lower numbers during a test run 
- use consistent lowercase letters
> Overhaul badges

- common/metrics/metric_defs.go
- common/rpc/interceptor/telemetry.go
- common/rpc/interceptor/telemetry_test.go
- Make service_errors cover only unexpected errors
- Easier to alert on the # of service errors. Without this change, we need use `service_error_with_type` and exclude a long list of expected error types. 
- `service_error` before this change is already very close to unexpected change but not quite, this PR basically make those two things the same.
- Unit tests
> Make service_errors cover only unexpected errors

- service/matching/backlog_manager.go
- service/matching/pri_backlog_manager.go
- service/matching/pri_task_writer.go
- service/matching/task_writer.go
Prevent data race when accessing task writer's `taskIdBlock`.
> Prevent taskIdBlock data race

- service/history/replication/stream.go
- service/history/replication/stream_sender.go
Return error for non retry case in stream sender
recvSyncReplicationState can return stream error or sol error
> Return error for non retry case in stream sender

- common/persistence/sql/execution.go
- common/persistence/sql/execution_state_map.go
- common/persistence/sql/execution_util.go
- common/persistence/sql/sqlplugin/history_chasm.go
- common/persistence/sql/sqlplugin/interfaces.go
- common/persistence/sql/sqlplugin/mysql/execution_maps.go
- common/persistence/sql/sqlplugin/postgresql/execution_maps.go
- common/persistence/sql/sqlplugin/sqlite/execution_maps.go
- common/persistence/sql/sqlplugin/tests/history_execution_chasm.go
- common/persistence/tests/mysql_test.go
- common/persistence/tests/postgresql_test.go
- common/persistence/tests/sqlite_test.go
- common/persistence/tests/util.go
- schema/mysql/v8/temporal/schema.sql
- schema/mysql/v8/temporal/versioned/v1.17/add_chasm_node_maps.sql
- schema/mysql/v8/temporal/versioned/v1.17/manifest.json
- schema/mysql/v8/version.go
- schema/postgresql/v12/temporal/schema.sql
- schema/postgresql/v12/temporal/versioned/v1.17/add_chasm_node_maps.sql
- schema/postgresql/v12/temporal/versioned/v1.17/manifest.json
- schema/postgresql/v12/version.go
- schema/sqlite/v3/temporal/schema.sql
- schema/sqlite/v3/temporal/versioned/v0.9/add_chasm_node_maps.sql
- schema/sqlite/v3/temporal/versioned/v0.9/manifest.json
- schema/sqlite/version.go
SQL persistence support has been added for CHASM nodes. 
- A new `chasm_node_maps` table has been added to SQL schemas
- SQL test suites updated
- SQL execution manager/util updated
- SQL plugins for `chasm_node_map` table
- We've landed Cassandra persistence support for CHASM nodes, this brings SQL support up to parity.
- New tests ran on all SQL plugins
- `go test -v ./...`
- No application paths write chasm_node_maps yet, but change does involve a schema change
> [CHASM] SQL persistence for CHASM nodes

- common/softassert/softassert.go
- service/matching/ack_manager_test.go
- service/matching/backlog_manager.go
- service/matching/backlog_manager_test.go
- service/matching/db.go
- service/matching/forwarder_test.go
- service/matching/matcher_data_test.go
- service/matching/matching_engine_test.go
- service/matching/physical_task_queue_manager.go
- service/matching/physical_task_queue_manager_test.go
- service/matching/pri_backlog_manager.go
- service/matching/pri_task_reader.go
- service/matching/task_queue_partition_manager_test.go
- service/matching/task_validation_test.go
- service/matching/user_data_manager_test.go
Re-using existing unit test suites for new priority/backlog/forwarder and:
- fixes two data races
- uses testlogger.Testlogger
Incompatible tests are skipped: `s.T().Skip("not supported by new matcher")`. They can either be ported or left as-is in follow-up PRs.
Increase test coverage.
A handful of tests had to be slightly tweaked to make them compatible. It's possible there are regressions in flakiness.
> Re-use unit tests

- service/matching/physical_task_queue_manager.go
- service/matching/pri_metrics_handler.go
Tag metrics belonging to the new priority path separately.
The priority-related metrics can now be viewed in isolation to drill down into priority-specific behavior.
We still emit the regular metric as before, as to not skew alerting and dashboards.
Checked in local Grafana.
> Track Priority metrics separately

- .golangci.yml
- common/persistence/cassandra/matching_task_store.go
- service/matching/ack_manager.go
- service/matching/backlog_manager_test.go
- service/matching/db.go
- service/matching/matcher_data_test.go
- service/matching/physical_task_queue_manager.go
- service/matching/pri_backlog_manager.go
- A few lint fixes.
- Remove forbid warning about time.After, this is no longer true in Go 1.23.
> Lint fixes for priority

- service/history/replication/raw_task_converter.go
- service/history/replication/raw_task_converter_test.go
- service/history/workflow/mutable_state_impl.go
Backward compatible support for this commit: https://github.com/temporalio/temporal/commit/c49995f27
When replicating between different version of temporal, specifically replicating from version does not ^ above commit and to version has ^ commit, the activity retry policy will be override to 0 value and will cause activity fail after failover. 
tested locally with different version of temporal
no risk.
n/a
yes
> Ignore updating activity retry policy for backward compatible

- service/history/handler.go
Start stream sender before register
The stream monitor could invalid the stream sender before it starts and create a dangling sender.
> Start stream sender before register

- common/primitives/timestamp/duration.go
Reduced max proto duration cap from 250 to 100 years.
ElasticSearch can only handle datetimes up to ~2262
Existing tests
> Reduce max proto duration cap to 100 years

- common/dynamicconfig/constants.go
- config/dynamicconfig/development-cass.yaml
- config/dynamicconfig/development-sql.yaml
- config/dynamicconfig/development-xdc.yaml
- service/history/tests/vars.go
- tests/testcore/dynamic_config_overrides.go
- Enable execution timeout timer by default
- it's been several server releases since this feature is merged, it's safe to enable it by default now without any backward compatibility concerns
- Will remove the flag after next oss release if not issue reported about it.
- Very low. Already enabled in all production envs
> Enable execution timeout timer by default

- chasm/tree.go
- chasm/tree_test.go
- common/persistence/transitionhistory/transition_history.go
- service/history/ndc/history_replicator.go
- service/history/ndc/hsm_state_replicator.go
- service/history/replication/executable_verify_versioned_transition_task.go
- service/history/replication/sync_state_retriever.go
- service/history/statemachine_environment.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/state_machine_timers.go
- service/history/workflow/state_transition_history.go
- service/history/workflow/state_transition_history_test.go
- service/history/workflow/task_refresher.go
- Implement chasmTree.Snapshot method
- Move workflow.CompareVersionedTransition to transitionhistory package to avoid cycle dependency. 
- Unit test
> CHASM: Snapshot implementation

- chasm/tree.go
- chasm/tree_test.go
- Implement ApplyMutation & ApplySnapshot methods of CHASM Tree
- Introduced a mutation field shared by the entire tree for tracking all the mutation happened so far in a transaction.
- CHASM implementation
- Unit test
> CHASM: Apply chasm nodes mutation and snapshot

- chasm/field.go
- chasm/field_test.go
- chasm/field_type.go
CHASM: use `chasm.Field` instead of `*chasm.Field`.
Non-pointer type looks more natural in component definition and there is no reason to support both of them.
No.
No.
No.
> CHASM: use chasm.Field instead of *chasm.Field

- common/backoff/retrypolicy.go
- common/backoff/retrypolicy_test.go
Subj.
Replace rand.Seed with `rand.New(rand.NewSource`
rand.Seed will be no-op in 1.24. and tests using rand.Seed will start failing.
Existing tests
No, current rand.Seed/rand.Intn implementation is a wrapper around globalRand singleton.
> Preparing for go 1.24 - remove rand.Seed from tests

- tests/testutils/tls.go
- tests/tls_test.go
We use 512 key in tests, this generate an error in go 1.24 for some reason.
`rsa1024min=0` GODEBUG setting suppresses this error.
We already use it in other places in the code.
Also removed t.Parallel()
Otherwise go 1.24 generate and error in func test.
t.Parallel() can't be used with t.Setenv
By running test with go 1.24
None.
Though we probably should be using same key length we use in prod.
> disable RSA key length error in test

- service/history/workflow/update/errors_failures.go
- tests/update_workflow_test.go
> Fix error message

- chasm/component.go
- chasm/tree.go
- chasm/tree_mock.go
- chasm/tree_test.go
CHASM: deserialize `ChasmNode` into tree node `value`. This is only first version with few TODOs to be resolved soon.
CHASM worksream.
No risks.
No.
No.
> CHASM: deserialize ChasmNode into tree node value

- chasm/export_test.go
- chasm/library.go
- chasm/library_mock.go
- chasm/registrable_component.go
- chasm/registrable_task.go
- chasm/registry.go
- chasm/registry_test.go
- chasm/test_library_test.go
CHASM: include library name in fully qualified component/task type name.
Type of `RegistrableComponent` is stored inside `ChasmNode.Metadata` and required to look up go type for proper deserialization. Therefore returned value must be fully qualified type name, not just type name.
Modified existing unit tests.
No risks.
No.
No.
> CHASM: include library name in fully qualified component/task type name

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/retry.go
- service/history/workflow/util.go
- tests/callbacks_test.go
Bugs fixed in the PR
1. If a callback is attached to a cron workflow, it would never call it.
2. If a workflow retries (failed or timed out), the completion callbacks would not be called and only the callbacks in the `WorkflowExecutionStarted` event would be copied to the new workflow.
The fixes:
1. Cron workflow will call the completion callbacks upon completion, unless they are retried.
2. When a workflow is retried, copy all attached callbacks to the new workflow.
Added functional tests, and verified that they fail in main, but passes with this PR.
> Fix handling of completion callbacks in retry and cron cases

- service/history/workflow/mutable_state_impl.go
This PR sets the dirty flags so that we can correctly replicate the state changes related to Reset operation. 
In most cases when a workflow is reset, the corresponding state changes will be replicated since there are other changes in the workflow that would trigger a sync. However, in the cases when we reset a workflow that was already closes/terminated, there won't be any other state changes made in the workflow that will trigger a replication. With this change we take care of replicating the state when there are any reset related stat changes.
Note that I'll be using `isResetStateUpdated` to cover a few additional fields in an upcoming PR. So kept the flag name generic. 
1. Setup local XDC with cluster-a & cluster-b.
2. Make cluster-a active.
3. Reset a closed workflow.
4. Inspect the …
> [Reset] Set flags for replication

- service/history/timer_queue_active_task_executor.go
- tests/activity_api_rules_test.go
Add code to pause the activity while processing activity retry task.
Part of the workflow rules efforts. This is another place where we need to check rules related to the activity.
Add functional test.
N/A.
N/A.
> Pause activity by rules in executeActivityRetryTimerTask

- client/history/caching_redirector.go
- client/history/caching_redirector_test.go
- client/history/client.go
- common/dynamicconfig/constants.go
In the history client caching redirector, limit the time that a cached client will be used after a membership update signals the shard has moved, defaulting to 30 seconds.
The redirector already removed entries that fail with timeouts or shard ownership lost. However, the impact of timeouts can be high, especially when an old shard owners address is unreachable. This manifested as high tail latencies for API calls after history restarts.
Added a unit test & in a test setup.
> expire cached entries in history client

- components/nexusoperations/frontend/handler.go
- service/frontend/nexus_handler.go
- service/history/configs/quotas.go
Fixed propagating headers from incoming context to outgoing context for Nexus HTTP requests.
Bug fix. Headers used for rate limiting were not being set appropriately.
> Fix Nexus context header propagation

- common/metrics/metric_defs.go
- service/history/workflow/mutable_state_impl.go
Add metric for paused activities. Metric is emmited every time pause state changed to "true"
With introduction of workflow rules pausing activity can become "mass" operation, and no initiated by direct user request.
Thus users need to know about it.
N/A
> Add metric for paused activities

- Makefile
Added Makefile target `update-dependencies-major`.
It lists all _major_ version upgrades and performs them; compared to `update-dependencies` which only updates _minor_ versions.
To assess major version upgrades and perform them, if needed.
Example output:
```
Major version upgrades available:
github.com/golang-jwt/jwt/v4: v4.5.1 [latest v5.2.2]
github.com/sony/gobreaker: v1.0.0 [latest v2.1.0]
github.com/urfave/cli: v1.22.16 [latest v2.27.6]
Update dependencies (major versions only) ...
go get github.com/golang-jwt/jwt/v5@v5.2.2
go: added github.com/golang-jwt/jwt/v5 v5.2.2
common/authorization/default_jwt_claim_mapper.go:32:2 github.com/golang-jwt/jwt/v5
common/authorization/default_jwt_claim_mapper_test.go:37:2 github.com/golang-jwt/jwt/v5 …
```
> Make target to update major versions

- common/testing/otellogger/otellogger.go
- go.mod
- temporal/fx.go
- temporal/server_test.go
Gracefully handling the case where the OTEL trace provider shutdown times out.
Before this change, it would propagate the "context deadline exceeded" error to fx and it would fail the entire functional test. But now it swallows that error on shutdown.
Failure to shut down OTEL should not affect the functional test outcome.
> Handle OTEL shutdown timeout

- go.mod
- go.sum
- service/history/api/describeworkflow/api.go
We are now exposing `ResetRunID` in WorkflowExtendedInfo field in DescribeWorkflowExecutionResponse.
This is needed so that UI can point to the new run when viewing a run that was reset.
Manually ran the UI server locally. Examined the response to DescribeWorkflowExecution
N/A
N/A
No
> Populate ResetRunId in historyservice.DescribeWorkflowExecutionResponse

- tests/testcore/functional_test_base.go
Setting worker binary checksum manually in functional tests.
Slightly faster functional test startup.
**Before**
**After**
> Set Worker binary checksum in test

- go.mod
- go.sum
- service/history/workflow/activity.go
- service/history/workflow/activity_test.go
- service/history/workflow/mutable_state_impl.go
- tests/activity_api_pause_test.go
- tests/activity_api_reset_test.go
In DescribeWorkflow, for pending activities, introduce PAUSE and PAUSE_REQUESTED states.
To clearly distinguish between "activity is paused on the server but running on the worker" vs "activity is paused on the server and not running on the worker"
Add unit tests.
Some existing scripts, that rely on "activity is running means State == STARTED" may stop working.
> add PAUSED and PAUSE_REQUESTED to activity state

- components/nexusoperations/statemachine.go
Populating request ID in `NexusOperationCancelRequestCompleted` and `NexusOperationCancelRequestFailed` events.
Missed in last PR
> Populate request ID in Nexus cancellation request events

- schema/embed.go
- tools/common/schema/updatetask.go
- tools/sql/README.md
Use `path.Join()` instead of `filepath.Join()`
#7454
Tested locally
None
None
No
> Fix sql tool error in windows

- service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler.go
This comment would help me, because I always forget where to find the Nexus handlers.
> Add comment containing location of Nexus handlers

- service/worker/workerdeployment/client.go
- service/worker/workerdeployment/util.go
- service/worker/workerdeployment/workflow.go
- tests/worker_deployment_version_test.go
- `FailedPrecondition` Errors from the deployment workflows are returned as `FailedPrecondition` from the deployment client.
- Right now, if a user were to call SetCurrent/SetRamping and our internal deployment workflows were to throw a FailedPrecondition error, the deployment client would convert them to `Internal` errors which in-turn would be masked by gRPC interceptors. 
- The error message would be super vague and something like (inside actual):
- Altered existing tests to check for this.
> fix cryptic error message for FailedPrecondition failures

- go.mod
- go.sum
There is a new version of tally released. So bumping the version to see if the security vulnerability is fixed in the latest version. 
If the issue is fixed, this would buy us more time to completely deprecate and remove tally.
N/A
> Bump tally to latest version

- tests/versioning_3_test.go
- tests/versioning_test.go
Previously, the test helper confirming that a version had propagated out to each task queue partition only checked that the version existed in the tq user data, not whether the version had the expected routing info. 
I changed that so that it only returns success if the ramping version is ramping in the tq, current is current in the tq, etc.
I also added more checks after each routing config change operation in the failing `TestVersioning3FunctionalSuite/TestUnpinnedWorkflowWithRamp_ToUnversioned/NoTaskForwardNoPollForwardAllowSync` test, so that if there is an issue with task queue propagation that caused the error:
```
versioning_3_test.go:1856: 
Error Trace:	/home/runner/work/temporal/temporal/tests/versioning_3_test.go:1856
Error:      	Received unexpected error:
failed to poll …
```
> Versioning tests: make task queue propagation check more specific, skip flaky v2 cron test

- service/history/replication/stream_receiver.go
Use Submit on replication task scheduler to avoid dangling task
The scheduler implementation does not support TrySubmit then Submit call. If we call in this sequence, it will cause dangling task.
Verified at test cluster
no risk. This is to revert a change that introduce a month ago
n/a
yes
> Use Submit on replication task scheduler to avoid dangling task

- api/persistence/v1/executions.pb.go
- go.mod
- go.sum
- proto/internal/temporal/server/api/persistence/v1/executions.proto
- service/history/api/pauseactivity/api.go
- service/history/api/pauseactivity/api_test.go
- service/history/api/recordactivitytaskstarted/api.go
- service/history/timer_queue_active_task_executor.go
- service/history/workflow/activity.go
- service/history/workflow/activity_test.go
- service/history/workflow/mutable_state_impl.go
- tests/activity_api_pause_test.go
- tests/activity_api_rules_test.go
* Add proto messages for PauseInfo to ActivityInfo (basically the same as in API)
* Populate PauseInfo for activities paused manually
* Populate PauseInfo for activities paused by the rules
* Populate PauseInfo in DescribeWorkflow response
* Add tests (mostly functional).
Part of the activity commands work. If activity is paused - users should be able to get quick answer to "Who/When/Why" questons.
Add functional tests
> Populate PauseInfo for activities in DescribeWorkflow response

- components/nexusoperations/executors.go
- go.mod
- go.sum
Populating ScheduledEventID on NexusOperationCancelRequestCompleted and NexusOperationCancelRequestFailed events.
Depends on API PR (see for more details): https://github.com/temporalio/api/pull/572
> Populate ScheduledEventID on NexusOperationCancelRequestCompleted|Failed

- go.mod
- go.sum
Bumping API version to `v1.48.0`
> Bump API to v1.48.0

- chasm/tree.go
- chasm/tree_test.go
CHASM: set and use `valueState` field.
`valueState` indicates if `value` and `serializedNode` are the same and call to `serialize`/`deserialize` methods can exit earlier and save on serialization/deserialization cost.
Modified existing unit tests.
No.
> CHASM: set and use valueState field

- service/history/workflow/transaction_impl.go
Skip error logs CreateWorkflowExecution for ResourceExhausted errors
This can lead to large amount of logging. And it is not very useful
> Skip error logs CreateWorkflowExecution for ResourceExhausted errors

- .github/workflows/linters.yml
- .github/workflows/run-tests.yml
- Makefile
- service/worker/deployment/deployment_workflow.go
- service/worker/migration/force_replication_workflow.go
- service/worker/scheduler/workflow.go
- service/worker/workerdeployment/workflow.go
- Add `make workflowcheck` and run it in CI checks
- Fix issues in existing system workflows. These fixes should not cause replay errors, because the ordering of map keys did not change which Temporal history events were generated, nor does switching from `time.Now()` to `workflow.Now()`
- Scheduler has replay unit tests that should catch any issues introduced by these changes
- Worker Deployment also has replay unit tests
- Deployment isn't used by any customers, so the lack of replay tests doesn't matter
- Replication workflow does not have replay tests, but the only change there was `time.Now()->workflow.Now()`
Force replication workflow gets an NDE because `time.Now()` was replaced with `workflow.Now()`
> Add Workflow static check to CI

- service/frontend/nexus_handler.go
- tests/nexus_api_test.go
- tests/xdc/nexus_request_forwarding_test.go
Better observability.
Updated existing tests.
There may be alerts depending on these values, they will need to be adjusted.
> Add error type as suffix to nexus handler metrics

- .github/workflows/create-tag.yml
Increasing the scope of the token.
The existing token blocks triggering the GHA when the release is published. However, the `api` repo has similar GHA and it works. The only difference I see is that the token is generated with repo owner scope.
> [GHA] Change GH token permissions in create-tag.yml

- .github/.golangci.yml
- common/cache/lru.go
Forbid use of panics in new code
We had an incident because of a panic, so we want to only add panics if we are very sure panic-ing is the right thing to do. If people need to add a panic they can bypass the linter with a forbidigo comment as we do for time.Sleep
I introduced a new panic and saw the linter catch it https://github.com/temporalio/temporal/actions/runs/14503587534
> forbid panics in linter

- service/history/api/getworkflowexecutionhistory/api.go
Log workflows that has empty history in persistence.
To identify these workflows.
> Log workflows with empty history

- components/nexusoperations/config.go
- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- tests/testcore/functional_test_sdk_suite.go
Putting NexusOperationCancelRequest[Completed|Failed] behind a feature flag.
So that we can wait to enable it until it will not cause issues with migration or rollback.
> Put NexusOperationCancelRequest[Completed|Failed] behind a feature flag

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
create new map if SubStateMachinesByType is nil after applySnapshot.
SubStateMachinesByType in replication task might be nil (due to proto.Clone of empty map). 
unit test and local test.
> new map if SubStateMachinesByType is nil

- common/clock/context.go
- common/stream_batcher/batcher.go
- common/stream_batcher/batcher_test.go
There was a potential deadlock in stream batcher after an Add call timed out. Make the channel buffered to fix it.
Bug
Unit tests
> Fix bug in stream batcher after timeout

- components/nexusoperations/events.go
- components/nexusoperations/executors.go
- tests/nexus_workflow_test.go
Added application logic for NexusCancelRequest[Completed|Failed] events
To support event-based replication
Existing tests
> Add application logic for NexusCancelRequest[Completed|Failed] events

- components/nexusoperations/executors.go
Use initialVersionedTransition as ms versionedTransition for state machine reference in the Nexus completion token.
When workflow switches branches, the ms versionedTransition in Nexus completion token may become stale and cannot pass the check when completion callback is triggered.
> use initialVersionedTransition for Nexus completion token

- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
- Validate workflow task attempt in standby task processing
- We have a same logic for active timer task, but not in standby.
- This is only needed in  state-based replication world where transient workflow task (attempt > 1) state will be replicated as well. Previously In history-based replication world, the attempt count in standby should always be 1  since transient workflow task has no events and won't be replicated, so the attempt check is not necessary. In state-based replication world, each replicated attempt will generate a start_to_close timeout timer and without this check, timer for previous attempt will keep doing verification and eventually get dropped and trigger alerts. No impact to the workflow though.
- Unit test
- It worst case, after failover, workflow task can't …
> Validate workflow task attempt in standby task processing

- common/namespace/namespace.go
- go.mod
- go.sum
- proto/internal/temporal/server/api/persistence/v1/executions.proto
- service/frontend/namespace_handler.go
- service/frontend/namespace_handler_test.go
- service/frontend/workflow_handler.go
- service/history/workflow/activity.go
- service/history/workflow/mutable_state_impl.go
- tests/activity_api_rules_test.go
Server-side implementation of this API PR:
https://github.com/temporalio/api/pull/577
Add Identity/Reason to pause info in activity was paused by the rule.
Add "created_by_identity/Description" to CreatewWorkflowRule API
Fix tests.
Product requert.
Existing tests. 
N/A
> Populate pause info for rule-induced activity pause

- common/dynamicconfig/constants.go
- common/persistence/cassandra/mutable_state_store.go
- common/persistence/data_interfaces.go
- common/persistence/operation_mode_validator.go
- common/persistence/sql/execution.go
- common/persistence/tests/execution_mutable_state.go
- service/history/configs/config.go
- service/history/history_engine2_test.go
- service/history/interfaces/mutable_state.go
- service/history/interfaces/mutable_state_mock.go
- service/history/ndc/activity_state_replicator.go
- service/history/ndc/activity_state_replicator_test.go
- service/history/ndc/hsm_state_replicator.go
- service/history/ndc/hsm_state_replicator_test.go
- service/history/statemachine_environment.go
- service/history/statemachine_environment_test.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_standby_task_executor.go
- service/history/visibility_queue_task_executor.go
- service/history/visibility_queue_task_executor_test.go
- service/history/workflow/context.go
- service/history/workflow/context_test.go
- service/history/workflow/mutable_state_impl.go
- Support update closed workflow by mutation
- Today, any updates (e.g. update callbacks after workflows & update branch token. With CHASM, there will be more cases) for closed workflows require persisting the entire mutable snapshot using the `SetWorkflowExecution` persistence API in order to skip the current record validation. 
- Application logic is complex and have to call different APIs based on workflow state
- Performance is also bad as we are writing unnecessary data when persisting a snapshot, even if they haven't been mutated.
- Unit & persistence integration tests
- No.
> Support updating closed workflows by mutation

- chasm/task.go
- chasm/task_mock.go
- chasm/tree.go
- chasm/tree_test.go
- Remove invalid tasks for CHASM component when closing transaction.
- Changes are on top of: https://github.com/temporalio/temporal/pull/7621
- CHASM  task processing logic
> CHASM: remove invalid tasks

- common/testing/protoassert/assert.go
Fix call to `assert.Fail` in `protoassert`
Bug fix: instead of getting details of the failed assertion, the test log was reporting a panic due to improper call to `assert.Fail`.
> Fix call to assert.Fail in protoassert

- service/history/api/multioperation/api.go
- service/history/api/updateworkflow/api.go
- tests/update_workflow_test.go
**⚠️ Before this is merged, the `StartWorkflowExecutionResponse` API needs to have a new field `Running` added to it.**
When UwS is applied to a closes Workflow where the requested Update (identified by its Update ID) has already been completed, return the Update outcome.
Note that this only applies to the current execution; not any previous execution.
Align UwS behavior with Update; a regular Update also returns its outcome from a closed Workflow.
New tests.
> Update-with-Start returns closed workflow's Outcome

- client/matching/client.go
Copy matching client proto messages to route to a specific partition instead of mutating the original ones.
Avoids validation and other problems on internal retries.
existing tests
> Don't mutate in matching client

- tests/update_workflow_sdk_test.go
- tests/update_workflow_test.go
Workflow Update: remove `UpdateWorkflow` prefix from functional tests names.
Since these tests are in dedicated test suite, this prefix doesn't make sense any more.
Build and run.
> Workflow Update: remove UpdateWorkflow prefix from functional tests names

- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
update workflow task only when the task is updated when applying replication task
Always updating workflow task will cause versionedTransition to be cleared in standby side.
unit test.
> update workflow task only when the task is updated

- common/testing/historyrequire/history_require.go
- tests/client_misc_test.go
- tests/testcore/functional_test_sdk_suite.go
Refactor: remove custom helpers from functional tests.
There are standard `s.Eventually` and project wide `historyrequire` package.
Run them.
I am not sure about timing which I put there. I tried to be conservative but if it is too aggressive, times need to be bumped up.
> Refactor: remove custom helpers from functional tests

- api/persistence/v1/executions.pb.go
- common/persistence/cassandra/errors_test.go
- common/persistence/serialization/blob.go
- common/persistence/serialization/serializer_test.go
- common/persistence/sql/execution_util.go
- common/persistence/sql/sqlplugin/tests/history_current_execution.go
- common/persistence/tests/util.go
- proto/internal/temporal/server/api/persistence/v1/executions.proto
- service/history/api/describeworkflow/api.go
- service/history/history_engine2_test.go
- service/history/historybuilder/event_store.go
- service/history/historybuilder/history_builder.go
- service/history/historybuilder/history_builder_categorization_test.go
- service/history/historybuilder/history_builder_test.go
- service/history/workflow/mutable_state_impl.go
- tests/describe_test.go
- tests/nexus_workflow_test.go
- tests/workflow_buffered_events_test.go
Add event ID to `RequestIDInfo`.
Also added `RequestIdInfos` to `DescribeWorkflowExecutionResponse`.
Be to able to find which event was added by the give request ID.
> Add event ID to RequestIDInfo

- service/history/api/multioperation/api.go
- tests/update_workflow_test.go
Make UwS attach to any in-flight Update before applying Start operation (like termination).
Allows to complete in-flight Update instead of terminating the Workflow.
Added test.
> Update-with-Start attach to in-flight Update

- api/persistence/v1/executions.pb.go
- proto/internal/temporal/server/api/persistence/v1/executions.proto
- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
- service/history/api/describeworkflow/api.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/util.go
- tests/callbacks_test.go
Handle links in Nexus callbacks.
Links in `StartWorkflowRequest` will dedup the links that are also in Nexus callbacks.
Nexus links are gonna be associated with the Nexus callbacks, and they will follow the callback when there is a continue-as-new or retries.
Added tests
> Handle links in Nexus callbacks

- api/historyservice/v1/request_response.pb.go
- api/matchingservice/v1/request_response.pb.go
- proto/internal/temporal/server/api/historyservice/v1/request_response.proto
- proto/internal/temporal/server/api/matchingservice/v1/request_response.proto
- service/frontend/workflow_handler.go
- service/history/api/recordactivitytaskstarted/api.go
- service/matching/matching_engine.go
- tests/workflow_test.go
1. Add activity retry policy to the PollActivityTaskQueueResponse (in OSS proto)
2. Add activity retry policy to the RecordActivityTaskStartedResponse (in OSS proto)
3. Populate activity retry policy in RecordActivityTaskStartedResponse, and propagate it to the PollActivityTaskQueueResponse.
1. Customer request.
2. We already have retry_policy in PollActivityTaskQueueResponse in API, but we never populate it.
For reference: https://github.com/temporalio/temporal/issues/6502
Modify existing tests.
> Populate RetryPolicy in PollActivityTaskQueueResponse

- common/persistence/history_manager.go
- service/history/api/getworkflowexecutionhistory/api.go
Handle no events in workflow history.
To prevent panics in case of data corruption.
> Handle no events in workflow history

- api/persistence/v1/executions.pb.go
- common/persistence/versionhistory/version_histories.go
- proto/internal/temporal/server/api/persistence/v1/executions.proto
- service/history/ndc/workflow.go
- service/history/ndc/workflow_test.go
- service/history/replication/executable_verify_versioned_transition_task.go
- service/history/replication/raw_task_converter.go
- service/history/replication/sync_state_retriever.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- service/history/workflow/mutable_state_rebuilder.go
- service/history/workflow/mutable_state_rebuilder_test.go
- service/history/workflow/mutable_state_state_status.go
Changes are mainly on replication side:
- Update mutable state GetCurrentVersion/StartVersion/CloseVersion() methods
- Update mutable state executionInfo.LastEventTaskID. and make sure it's updated even if a transition doesn't generate any events.
- Update state based replication logic to handle no event case (more changes in https://github.com/temporalio/temporal/pull/7700).
- CHASM runs may not have events at all. We need to make sure logic continue to work in that case.
- Will have functional tests later when CHASM is ready to ensure things can work e2e.
> CHASM: Non-Workflow Mutable State P1 

- chasm/component.go
- chasm/component_mock.go
- chasm/field_test.go
- chasm/fields_iterator_test.go
- chasm/test_component_test.go
- chasm/tree.go
- chasm/tree_mock.go
- chasm/tree_test.go
- service/history/deletemanager/delete_manager.go
- service/history/deletemanager/delete_manager_mock.go
- service/history/deletemanager/delete_manager_test.go
- service/history/interfaces/chasm_tree.go
- service/history/interfaces/chasm_tree_mock.go
- service/history/interfaces/mutable_state.go
- service/history/interfaces/mutable_state_mock.go
- service/history/ndc/buffer_event_flusher_test.go
- service/history/ndc/workflow.go
- service/history/ndc/workflow_test.go
- service/history/replication/task_executor.go
- service/history/transfer_queue_active_task_executor.go
- service/history/transfer_queue_active_task_executor_test.go
- service/history/transfer_queue_task_executor_base.go
- service/history/workflow/context.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- service/history/workflow/noop_chasm_tree.go
- service/history/workflow/task_refresher.go
- Support force termination of CHASM runs. 
- Generate retention timers for CHASM runs.
- Get rid of assumptions in workflow.Context and replication that the run is always a Workflow and runs workflow specific logic.
- CHASM
> CHASM: Non-Workflow Mutable State P2 Force Termination

- chasm/tree.go
- chasm/tree_mock.go
- chasm/tree_test.go
- service/history/interfaces/chasm_tree.go
- service/history/interfaces/chasm_tree_mock.go
- service/history/tasks/utils.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_active_task_executor_test.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/timer_queue_task_executor_base.go
- service/history/workflow/noop_chasm_tree.go
- Added physical pure task processing logic to the timer queue executors.
- Pending; **PR is in draft**
> [CHASM] timer queue pure task processing logic

- service/history/api/updateworkflowoptions/api.go
- service/history/api/updateworkflowoptions/api_test.go
- Expose `updateworkflowoptions.MergeAndApply()`
- Minor refactors
Need `updateworkflowoptions.MergeAndApply()` so that we can update options at the time of workflow reset.
> Refactor updateworkflowoptions package

- common/dynamicconfig/constants.go
Set MaxWorkers for dynamic config subscription callback to 1e9 so there's no effective limit.
A batch of subscription callbacks are enqueued (though not called) while holding a lock. If a callback somehow makes a call back into dynamic config subscriptions, then it would have to wait for the batch to finish enqueueing. If there's more than MaxWorkers of those, that would cause a deadlock. We don't need to impose a limit on workers here.
> Remove cap for dynamic config callback pool

- chasm/tree.go
- chasm/tree_mock.go
- chasm/tree_test.go
- service/history/interfaces/chasm_tree.go
- service/history/interfaces/chasm_tree_mock.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_active_task_executor_test.go
- service/history/timer_queue_standby_task_executor.go
- service/history/timer_queue_standby_task_executor_test.go
- service/history/timer_queue_task_executor_base.go
- service/history/workflow/noop_chasm_tree.go
- I originally expected to use this interface for side effect tasks as well, but I think having a more specific name would be better. Open to suggestions.
- 
`LogicalTaskExecutor` -> `NodeExecutePureTask`
- Original name is too broad
> Rename internal CHASM task processing interface

- client/matching/client.go
- common/log/tag/tags.go
- common/log/tag/zap_tag.go
- common/persistence/visibility/visiblity_manager_metrics.go
- common/rpc/interceptor/mask_internal_error.go
- common/rpc/interceptor/telemetry.go
- components/scheduler/generator_executors.go
- service/history/shard/context_impl.go
- service/history/workflow/update/util.go
- temporal/fx.go
This PR adds easy access to Zap's Stringer and Stringers fields.
`Stringer` fields are more efficient than `String` field. In the OSS repo alone we have 22 separate invocations of `tag.NewStringTag(..., foo.String())` which would be better served by using a Stringer tag. This only calls `String` (which can be expensive) when the line is actually emitted.
Meaning fewer wasted cycles when calling `String()` for debug-level logs.
> chore: Add Stringer tags

- common/log/tag/tags.go
- common/log/tag/zap_tag.go
I've changed _some_ of the tags I altered in #7738 back to StringTags from StringerTags and added usage recommendations to the StringerTag (and StringersTag) methods.
@prathyushpv rightly pointed out that some of the tags I changed in #7738  are applied to the loggers themselves and not just the messages. This means that the `String()` method will be invoked _every time_ a log is to be emitted. This incurs extra allocations etc. etc.
> chore: be smarter about when to use Stringer vs String

- common/dynamicconfig/constants.go
Enable DLQ V2 for replication.
This feature is tested and ready now.
> Enable DLQ V2 for replication

- go.mod
- go.sum
- service/history/workflow/activity.go
- service/history/workflow/activity_test.go
Populate activity options in DescriveWorfklow request.
Corresponding API PR:
https://github.com/temporalio/api/pull/586
* Activity options can be changed, and right now there is no way to know that.
* Requirement in UI.
> Add activity options to the pending activity info

- service/history/workflow/mutable_state_impl.go
Check if rule is expired.
We have expiration time. After that time rule shouldn't be applied.
> add rule expiration check

- service/matching/matcher.go
- service/matching/pri_matcher.go
Split poll_latency and task_dispatch_latency metrics by simple priority level.
Observability, to have stats on throughput and latency by level.
> Add task_priority label to task_dispatch_latency and poll_latency

- api/replication/v1/message.pb.go
- proto/internal/temporal/server/api/replication/v1/message.proto
- service/history/ndc/workflow_state_replicator.go
- service/history/ndc/workflow_state_replicator_test.go
- service/history/replication/sync_state_retriever.go
- service/history/replication/sync_state_retriever_test.go
Fix State based replication first task handling
Previously, we made an assumption that it is always safe to return mutation for first replication task, but it is not true.
When there is replication lag, the workflow may make some progress and tombstone batch is capped. If we still blindly return mutation, completed statemachine may still looked pending on the passive side. 
No risk, the feature is not launched yet.
> Fix State based replication first task handling

- common/dynamicconfig/constants.go
- service/frontend/namespace_handler.go
- service/frontend/namespace_handler_test.go
- service/frontend/service.go
Remove oldest expired workflow rule is more space is needed.
Add per namespace config options to limit the number of rules.
Auto-cleanup expired rules. We keep them in case user still want to use them, but we don't want to fail adding new rule.
> remove old rules when more space is needed

- service/frontend/namespace_handler.go
- service/frontend/namespace_handler_test.go
Rename funciton.
Change eviction condition.
Working on comment from https://github.com/temporalio/temporal/pull/7752
I fixed that, but merge before I realize I didn't push them.
> Follow up for exriped rules

- api/historyservice/v1/request_response.pb.go
- common/dynamicconfig/constants.go
- proto/internal/temporal/server/api/historyservice/v1/request_response.proto
- service/history/api/verifychildworkflowcompletionrecorded/api.go
- service/history/configs/config.go
- service/history/history_engine.go
- service/history/history_engine2_test.go
- service/history/shard/context_testutil.go
- service/history/transfer_queue_standby_task_executor.go
- service/history/transfer_queue_standby_task_executor_test.go
Resend parent for standby child completion verification.
In the case that standby fails to verify child completion when parent workflow is not found or not ready, standby should request resend parent from active so standby can finish verification earlier.
New calls will be made to active. But this will only happen after the new config maxLocalParentWorkflowVerificationDuration. So impacts to active will be low.
> Resend parent for standby child completion verification

- api/replication/v1/message.pb.go
- proto/internal/temporal/server/api/replication/v1/message.proto
- service/history/ndc/workflow_state_replicator.go
- service/history/ndc/workflow_state_replicator_test.go
- service/history/replication/sync_state_retriever.go
- service/history/replication/sync_state_retriever_test.go
Fix State based replication first task handling
Previously, we made an assumption that it is always safe to return
mutation for first replication task, but it is not true.
When there is replication lag, the workflow may make some progress and
tombstone batch is capped. If we still blindly return mutation,
completed statemachine may still looked pending on the passive side.
No risk, the feature is not launched yet.
_Describe what has changed in this PR._
_Tell your future self why have you made these changes._
_Any change is risky. Identify all risks you are aware of. If none, remove this section._
> Cherry-pick cc0b0840b7631dfa40138acd3314933de2f5d776

- common/archiver/README.md
- common/archiver/constants.go
- common/archiver/filestore/history_archiver.go
- common/archiver/filestore/history_archiver_test.go
- common/archiver/filestore/visibility_archiver.go
- common/archiver/filestore/visibility_archiver_test.go
- common/archiver/gcloud/history_archiver.go
- common/archiver/gcloud/history_archiver_test.go
- common/archiver/gcloud/visibility_archiver.go
- common/archiver/gcloud/visibility_archiver_test.go
- common/archiver/interface.go
- common/archiver/provider/provider.go
- common/archiver/provider/provider_mock.go
- common/archiver/s3store/history_archiver.go
- common/archiver/s3store/history_archiver_test.go
- common/archiver/s3store/visibility_archiver.go
- common/archiver/s3store/visibility_archiver_test.go
- common/resource/fx.go
- service/frontend/namespace_handler.go
- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
- service/history/archival/archiver.go
- service/history/archival/archiver_test.go
- tests/archival_test.go
- tests/testcore/test_cluster.go
Refactor how archival subsystem gets its dependencies to work better with fx:
- Remove service type maps (archivalProvider is already service-specific)
- Remove "bootstrap" structs and just pass around dependencies
The service type maps were causing issues like #7631, and are unnecessary.
> Refactor archival fx initialization

- common/deadlock/deadlock.go
- common/deadlock/deadlock_test.go
- common/metrics/metric_defs.go
- Add counter metric for total suspected deadlocks
- Add gauge metric for current unresolved suspected deadlocks
These could be used in alerting or health checking.
> Add metrics for suspected deadlocks

- error.txt
- service/worker/workerdeployment/client.go
- service/worker/workerdeployment/util.go
- tests/versioning_3_test.go
increasing timeouts for breaking test + making the deploymentClient retry on the error returned when an update is admitted but the workflow is closing.
- trying to put a band-aid over the breaking func test
> Fixing flake caused by the auto-restart versioning feature

- common/worker_versioning/worker_versioning.go
- service/worker/workerdeployment/client.go
Ensure that ListWorkerDeployments never returns a nil RoutingConfig.
Nightly run revealed nil pointer panic when ListWorkerDeployments calls AddV32RoutingConfigToV31 on a RoutingConfig in the memo.
When a worker deployment entity workflow starts, we immediately populate the routing config and upsert that to the memo, but it's possible to have a race between the workflow existing in Visibility, but before the memo was upserted. This PR ensures that if the memo is nil when List is called, we return a non-nil routing config and deployment info.
If this doesn't solve the bug (ie. because memo is empty instead of nil) then we will find out in tonight's nightly
> Ensure that RoutingConfig is never nil

- common/config/persistence.go
Allow dual ES clusters in visibility config
Allow to set a different Elasticsearch cluster as secondary Elasticsearch visibility store.
Created two ES clusters as two docker containers, modified the server config with dual visibility enabled, and ran some sample workflow. Verified that visibility records are written to both ES clusters and that the server can read from both of them
Adding search attributes might be not add to the secondary ES
> Allow dual ES clusters in visibility config

- tests/update_workflow_test.go
Added a test for Update-with-Start.
Code coverage showed that there was no test for deduping a running Workflow.
> Update-with-Start dedup test

- service/worker/migration/activities.go
- force-replication workflow will no longer forward ListWorkflowExecutions() to the Active cell
- The force-replication workflow is used to ensure all workflows are replicated from the local cell (where the workflow is run) to a target cell.
- Part of force-replication is a call to ListWorkflowExecutions() which determines the workflows that need to be forwarded.
- Historically this workflow was always run on the Active cell, so forwarding never occurred.
- As of recently, we plan to run force-replication from the Passive cell.
- For the Passive cell to know which workflows need to be forwarded, we can not have the ListWorkflowExecutions() be forwarded to the Active cell
> force-replication ListWorkflows executes on local cell (disable forwarding)

- service/worker/scheduler/spec.go
- service/worker/scheduler/spec_test.go
Stop searching for a matching schedule time after year 2100.
If all matching times are also excluded, then the loop in GetNextTime would never return.
Fixes #7793.
> Limit schedule exclude time search

- service/worker/workerdeployment/workflow.go
1. Added strategic logging points to track workflow state:
- At workflow start in `run()`
- Before continue-as-new transitions
- During SetCurrent version updates
- During memo updates
2. Updated validator functions to use nil-safe Get notation:
- `validateStateBeforeAcceptingRampingUpdate`
- `validateStateBeforeAcceptingSetCurrent`
- `validateDeleteVersion`
- `validateDeleteDeployment`
1. The logging changes will help diagnose nil pointer errors we're seeing in canary tests by:
- Tracking the state of `RoutingConfig` throughout the workflow lifecycle
- Verifying state preservation during continue-as-new transitions
- Monitoring state changes during updates
- Confirming state persistence in the memo
2. The nil-safe Get notation changes make the code more defensive by:
- Preventing nil …
> Add defensive logging and nil-safe access in WorkerDeployment workflow

- service/matching/matching_engine.go
- service/matching/task_queue_partition_manager.go
- service/matching/task_queue_partition_manager_interface.go
- service/matching/task_queue_partition_manager_mock.go
Replaced the ad-hoc cache in partition manager with the existing (common) cache component.
DRY. Plus, I need to cache a separate cache key/value pair and didn't want to duplicate everything for that cache again.
> Cache component in PartitionManager

- common/metrics/metric_defs.go
- common/metrics/tags.go
- common/worker_versioning/worker_versioning.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- metrics for DeploymentTransition + VersioningOverride
- versioning-0.32
- a little new to this side of the code involving versioning so a bit scared about doing things wrong, hopefully I am not
> Versioning Metrics pt2: DeploymentTransition + VersioningOverride

- service/history/api/respondworkflowtaskcompleted/api.go
- service/history/workflow/workflow_task_state_machine.go
In an edge case in versioning we wanted to make sure that a new WFT is generated after processing the previous WFT completed event. The new WFT was added in `afterAddWorkflowTaskCompletedEvent` which is run before processing commands.
Now moved it to the api handler which is anyways taking care of similar cases to create new WFT task after completion of the previous one.
The old logic causes issues because it adds the new WFT before the events generated from commands.
> Do not add start WFT before processing commands

- service/worker/workerdeployment/workflow.go
- The canary seems to be erroring out cause there are multiple `syncState` calls where an empty version is being passed. Now, we don't know for sure who and from where these strings are being passed, but to mitigate these failures, I have added some extra checks so that the `syncState` activity doesn't run with empty strings.
- to stop the canary from complaining 
- none
> stop potential empty string versions being passed to our syncVersion calls

- common/metrics/config.go
- common/metrics/metricstest/metricstest.go
- common/metrics/opentelemetry_provider.go
- common/metrics/otel_metrics_handler.go
- common/metrics/otel_metrics_handler_test.go
Moved `WithoutUnitSuffix`, `WithoutCounterSuffix` & `RecordTimerInSeconds` configs under `metrics.prometheus` config
These configs are specific to prometheus + OTel 
N/A
> [metrics] move prometheus specific configs under metrics.prometheus config

- common/dynamicconfig/constants.go
- service/history/api/multioperation/api.go
- service/history/configs/config.go
Added a log for every MultiOperation error in history.
Track down a race condition.
Since it's only logging errors, I expect the log volume to be reasonable/low.
> Add MultiOperation error logging

- common/dynamicconfig/constants.go
- service/history/configs/config.go
- service/history/history_engine_factory.go
- service/history/workflow/cache/cache.go
- service/history/workflow/cache/fx.go
- Remove shard level workflow cache logic and always use host level workflow cache.
- Simplify code. Host level workflow cache has been enabled by default for a long time.
> Remove shard level workflow cache logic

- chasm/context.go
- chasm/field.go
- chasm/field_type.go
- chasm/test_component_test.go
- chasm/tree.go
- chasm/tree_test.go
- service/history/chasm_engine.go
- service/history/chasm_engine_test.go
CHASM: Add basic `ComponentPointer` support to CHASM component.
Part of CHASM workstream. Few things are still pending:
1. `RefC` and `RefD` should return error.
2. Implementation of `RefC` and `RefD` needs to be revisited. It is not clear if it is possible to implement w/o deserializing entire component starting from root and all the way down, because `n.value` is needed to compare with passed argument.
3. Dangling pointers protection is not implemented.
> CHASM: ComponentPointer support

- tests/cancel_workflow_test.go
- tests/nexus_api_test.go
- tests/signal_workflow_test.go
- tests/testcore/functional_test_base.go
Refactor: rename `foreignNamespace` to `externalNamespace`.
Better readability.
> Refactor: rename foreignNamespace to externalNamespace

- service/matching/physical_task_queue_manager.go
- service/worker/workerdeployment/client.go
- tests/worker_deployment_test.go
The check to enforce number of Worker Deployments remain within the limit for a NS could also prevent adding new versions to existing deployments when user has just enough deployments that reach the limit but not exceed it.
Fixing unexpected behavior.
None.
> Fix max deployment count check to not block new versions

- common/metrics/tags.go
- nightly pipelines caught that the workflow_query_success_count was being emitted with variable tag key for non user-defined query types
- to make these pipelines pass
- None
> fixing workflow_query_success_count tag mismatch

- service/history/fx.go
- service/history/handler.go
- service/history/replication/batchable_task.go
- service/history/replication/batchable_task_mock.go
- service/history/replication/executable_task_tracker.go
- service/history/replication/executable_task_tracker_mock.go
- service/history/replication/fx.go
- service/history/replication/quotas.go
- service/history/replication/stream_sender.go
- service/history/replication/stream_sender_test.go
Add rate limiter on low priority replication tasks
This gives the ability to wire up rate limiter on replication stack.
> Add rate limiter on low priority replication tasks

- .github/workflows/run-tests.yml
Bumped resources for func tests against Cass.
We've seen func tests on Cass time out. This is an attempt to see if bumping the resources fixes the issue.
> Run Cass tests on larger machines

- service/history/api/respondworkflowtaskcompleted/api.go
Server sends new wft in response of preious wft completion. This should not happen if the next wft is supposed to go to a different worker version.
When there is a transition, workflow could fall into an infinite loop of workflow tasks because they never go to the right worker.
will be verified in Nightlies.
None
> Do not bypass task generation when version changes

- Makefile
- api/history/v1/message.pb.go
- api/historyservice/v1/request_response.pb.go
- api/matchingservice/v1/request_response.pb.go
- api/token/v1/message.pb.go
- common/persistence/serialization/serializer_test.go
- common/util.go
- proto/internal/temporal/server/api/history/v1/message.proto
- proto/internal/temporal/server/api/historyservice/v1/request_response.proto
- proto/internal/temporal/server/api/matchingservice/v1/request_response.proto
- proto/internal/temporal/server/api/token/v1/message.proto
- service/history/api/get_history_util.go
- service/history/api/get_workflow_util.go
- service/history/api/getworkflowexecutionhistory/api.go
- service/history/api/recordworkflowtaskstarted/api.go
- service/history/api/respondworkflowtaskcompleted/api.go
- service/history/history_engine_test.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/workflow_task_state_machine.go
- service/matching/matching_engine_test.go
- tests/advanced_visibility_test.go
- tests/cancel_workflow_test.go
- tests/client_misc_test.go
- tests/relay_task_test.go
- tests/update_workflow_test.go
- tests/versioning_3_test.go
- tests/workflow_failures_test.go
- tests/workflow_task_test.go
This reverts commit 5fc3fb21c4e556750e8dc5c8a2e27f92833ef3b4.
Reverts the change to return transient and speculative WFT events.
Started seeing new error like this
"history_events: premature end of stream, expectedLastEventID=4424 but no more events after eventID=4422" in pipelines which was not there before.
> Revert "Include transient and speculative WFT events in GetWorkflowExecutionHistory response (#7732)"

- chasm/test_component_test.go
- chasm/tree.go
- chasm/tree_test.go
- service/history/interfaces/chasm_tree.go
- service/history/interfaces/chasm_tree_mock.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_impl_test.go
- service/history/workflow/noop_chasm_tree.go
- service/history/workflow/task_refresher.go
- Support full task refresh
- It is a very useful troubleshooting tool for handling lost tasks and unblock stuck state machines. With this case the existing `RefreshWorkflowTasks` API will work on CHASM run as well. Of course we may want to rename that api or create a new one.
- Full task refresh is also needed in replication stack under conflict resolution case as today's conflict resolution logic calls full refresh which updates the task generation lock and invalidates all previous generated tasks. 
- We can do better in replication stack and use partial task refresh instead (e.g. refresh from lca of the versioned transition), and/or bypass some task refresh logic when the run is a CHASM run instead of workflow. But that's outside the scope of this PR. We need full task refresh any way …
> CHASM: support full task refresh

- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
- service/worker/batcher/activities.go
- service/worker/batcher/workflow.go
We had missed copying over the `BatchOperationReset.PostResetOperation` to `ResetParams` in the workflow handler. Additionally since this proto message contains `oneof` we need to perform manual protobuf marshal/unmarshal to avoid json serialization/deserialization issues.
This parameter is needed to support post reset operations like updating versioning in a batch operation.
N/A
> Add workflowpb.PostResetOperation to ResetParams in batch operations

- common/persistence/history_manager.go
- service/history/ndc/workflow_state_replicator.go
Allow reading history reverse when mutable state does not have LastFirstEventTxnId set
LastFirstEventTxnId maybe not set because of replication.
No risk.
> Allow reading history reverse when mutable state does not have LastFirstEventTxnId set

- service/frontend/workflow_handler.go
- service/frontend/workflow_handler_test.go
- service/worker/batcher/activities.go
- tests/workflow_reset_test.go
I was not decoding the post reset operation message properly in the batch workflow activity. I should have used `protojson.Unmarshal` (instead of op.Unmarshal() which uses proto.Unmarshal())
Added functional test to cover the batch reset operation end-to-end 
Fixes a bug I introduced in https://github.com/temporalio/temporal/pull/7911
> Reset+version_move: fix decoding bug and add functional test

- service/history/archival_queue_factory.go
- service/history/archival_queue_factory_test.go
- service/history/history_engine.go
- service/history/memory_scheduled_queue_factory.go
- service/history/outbound_queue_factory.go
- service/history/queue_factory_base.go
- service/history/queue_factory_base_test.go
- service/history/timer_queue_factory.go
- service/history/transfer_queue_factory.go
- service/history/visibility_queue_factory.go
- Remove workflowCache from QueueFactory interface
- Address old TODO, pave the road for moving QueueFactory interface into history/queues package.
> Remove workflowCache from QueueFactory interface

- common/finalizer/finalizer.go
- common/metrics/metric_defs.go
Reduce info logging of Finalizer component.
Not that useful (anymore) actually; replaced it with a metric to still have some observability.
> Reduce Finalizer logging

- .github/workflows/run-tests.yml
Follow-up to https://github.com/temporalio/temporal/pull/7871; covers sqlite tests as well.
Complete coverage.
> Enable OTEL for sqlite GHA test runs

- common/persistence/sql/execution_state_map.go
- service/history/workflow/mutable_state_impl_test.go
- Fixes an NPE in the write path for CHASM nodes without a `Data` field.
- [*] added new unit test(s)
> [CHASM] bug fix: NPE in SQL persistence layer when persisting types with a nil Data field

- chasm/tree.go
- Fixes a bug where archetype was missing from a generated Ref
> [CHASM] set ref archetype in SideEffect executor

- service/matching/matching_engine.go
- tests/describe_task_queue_test.go
Added test to verify DescribeTaskQueue Stats are cached.
Regression testing.
> Add DescribeTaskQueue Stats cache test

- common/persistence/data_interfaces.go
- proto/internal/temporal/server/api/persistence/v1/tasks.proto
- schema/cassandra/temporal/schema.cql
- service/matching/backlog_manager.go
- service/matching/backlog_manager_test.go
- service/matching/db.go
- service/matching/matching_engine_test.go
- service/matching/physical_task_queue_manager.go
- service/matching/physical_task_queue_manager_test.go
- service/matching/pri_backlog_manager.go
- service/matching/pri_task_reader.go
- service/matching/pri_task_writer.go
- service/matching/task.go
- service/matching/task_queue_partition_manager_test.go
- service/matching/task_writer.go
- tests/priority_fairness_test.go
- tests/testcore/flag.go
- Consolidate task ids into `writeTaskRequest` instead of separate slice.
- Factor out some common code in `newPhysicalTaskQueueManager`.
- Factor out `taskResponse.err()`.
- Move code out of select in `getTasksPump`.
- Add a `UseCassandraPersistence` test helper.
- Remove some obsolete structs and functions.
- Rename some test functions.
- Update some comments.
These are a bunch of small changes from the fairness feature branch that can apply to main immediately, which will make reviewing/merging that branch easier.
> Small matching cleanups

- common/dynamicconfig/constants.go
- common/persistence/client/fx.go
- common/persistence/health_signal_aggregator.go
- common/persistence/noop_health_signal_aggregator.go
- common/persistence/persistence_metric_clients.go
Removed per-shard and per-namespace per-shard RPS warning logs since they are no longer valuable.
> Remove per-shard RPS warn logs

- api/persistence/v1/tasks.pb.go
- api/taskqueue/v1/message.go-helpers.pb.go
- api/taskqueue/v1/message.pb.go
- common/dynamicconfig/constants.go
- common/metrics/metric_defs.go
- common/persistence/cassandra/factory.go
- common/persistence/cassandra/matching_task_store.go
- common/persistence/cassandra/matching_task_store_user_data.go
- common/persistence/cassandra/matching_task_store_v1.go
- common/persistence/cassandra/matching_task_store_v2.go
- common/persistence/client/factory.go
- common/persistence/client/fx.go
- common/persistence/data_interfaces.go
- common/persistence/faultinjection/data_store_factory.go
- common/persistence/mock/store_mock.go
- common/persistence/persistence-tests/persistence_test_base.go
- common/persistence/persistence_interface.go
- common/persistence/sql/factory.go
- common/persistence/task_manager.go
- common/persistence/telemetry/data_store_factory.go
- common/persistence/tests/cassandra_test.go
- proto/internal/temporal/server/api/persistence/v1/tasks.proto
- proto/internal/temporal/server/api/taskqueue/v1/message.proto
- schema/cassandra/temporal/schema.cql
- service/matching/db.go
- service/matching/matching_engine.go
- service/matching/physical_task_queue_manager.go
- service/matching/pri_backlog_manager.go
- Add pass number fields to some protos.
- Implement pass handling in task store v2.
- Remove TTLs from task store v2.
- Add some error checking to prevent misuse.
- Add support for using LIMIT in the GetTasks query.
- Rename some things.
Start implementing matching task fairness.
> Matching fairness update persistence and protos

- .vscode/launch.json
add the `-tags=test_dep` to the VSCode launch configuration
Debug fails with a build error
```sh
Build Error: go test -c -o /Users/seankane/git/github.com/temporalio/temporal/tests/__debug_bin1525033192 -gcflags all=-N -l .
testcore/onebox.go:204:39: undefined: testhooks.NewTestHooksImpl
testcore/onebox.go:857:23: undefined: testhooks.Set (exit status 1)
```
No change to production code, only configuration
> fix(vscode): add build tags to single functional test debugging

- service/matching/db.go
Reset backlog age when backlog count becomes zero.
Backlog age metric remains non-zero even after the backlog is empty. This PR fixes that.
None
> Reset backlog age when backlog count becomes 0

- api/persistence/v1/executions.pb.go
- proto/internal/temporal/server/api/persistence/v1/executions.proto
- service/history/interfaces/mutable_state.go
- service/history/interfaces/mutable_state_mock.go
- service/history/replication/sync_state_retriever.go
- service/history/workflow/context.go
- service/history/workflow/mutable_state_impl.go
- tests/xdc/failover_test.go
Add SuccessorRunId in ms and use that to get new run when generating sync state result.
If the workflow is terminated because of `WORKFLOW_ID_CONFLICT_POLICY_TERMINATE_EXISTING`, NewExecutionRunId is not set in the mutable state. In this case, Sync state is not able to get the new run info. The new run will not be replicated to the target cluster.
> fix missing new run

- common/headers/version_checker.go
- We're releasing 1.28, main should point to 1.29.
> Bump main version to 1.29

- tools/testrunner/junit.go
- tools/testrunner/junit_test.go
- tools/testrunner/testdata/junit-empty.xml
- tools/testrunner/testrunner.go
(1) Testrunner won't report parents like `TestCallbacksSuite` from `TestCallbacksSuite/TestWorkflowCallbacks_InvalidArgument`.
(2) Testrunner will still write JUnit file even if missing test case is detected.
re (1): Less verbose; reporting parents doesn't add anything.
re (2): JUnit file is still valid + helpful and should be written.
> TestRunner skips reporting parent test cases

- api/matchingservice/v1/request_response.go-helpers.pb.go
- api/matchingservice/v1/request_response.pb.go
- api/matchingservice/v1/service.pb.go
- api/matchingservice/v1/service_grpc.pb.go
- api/matchingservicemock/v1/service_grpc.pb.mock.go
- client/matching/client_gen.go
- client/matching/metric_client_gen.go
- client/matching/retryable_client_gen.go
- common/dynamicconfig/constants.go
- common/rpc/interceptor/logtags/matching_service_server_gen.go
- go.mod
- go.sum
- proto/internal/temporal/server/api/matchingservice/v1/request_response.proto
- proto/internal/temporal/server/api/matchingservice/v1/service.proto
- service/frontend/workflow_handler.go
- service/matching/configs/quotas.go
- service/matching/handler.go
- service/matching/matching_engine.go
- service/matching/matching_engine_interfaces.go
- service/matching/task_queue_partition_manager.go
- service/worker/workerdeployment/activities.go
- service/worker/workerdeployment/client.go
- tests/task_queue_stats_test.go
- tests/testcore/functional_test_base.go
- tests/worker_deployment_version_test.go
Added task queue stats reporting to DescribeWorkerDeploymentVersion API.
To allow inspecting backlog etc of task queues of a particular worker version.
> Add Stats to DescribeWorkerDeploymentVersion

- service/matching/matching_engine.go
Always go through matching client to query `DescribeTaskQueue` endpoint.
Ensure ownership is correct; a shortcut to the local partition doesn't account for that.
> Always issue RPC in DescribeVersionedTaskQueues

- Makefile
- common/archiver/gcloud/connector/client_delegate.go
- common/archiver/gcloud/connector/client_test.go
Stripped Google Cloud Storage's gRPC dependencies out for builds via the Makefile.
Reduce binary size by 16MB; and reduces build times a little (ie linking).
**Before**
```
-rwxr-xr-x@ 1 stephan  staff   119M Jun 30 11:23 temporal-server
```
**After**
```
-rwxr-xr-x@ 1 stephan  staff   103M Jun 30 11:24 temporal-server
```
Yes, since there are no end-to-end tests, if anyone started using `storage.NewGRPCClient` that would fail silently. I added a (crude) test to catch that.
> Exclude Google Cloud Storage gRPC packages

- service/history/api/verifychildworkflowcompletionrecorded/api.go
- service/history/transfer_queue_standby_task_executor.go
- service/history/workflow/test_util.go
Only resend parent when wf has transition and handle the case when source cluster has transition history disabled.
Currently we only use state-based SyncState to resend parent wf. That requires the wf has transition history enabled.
> only resend parent when wf has transition

- service/history/api/respondworkflowtaskcompleted/workflow_task_completed_handler.go
Extract fairness key from activity ID.
For testing purposes only.
It will be removed before merging to `main`; but even if it's not, the identifier was carefully chosen to minimize overlap with users'.
> Extract fairness key from activity ID

- .github/workflows/create-tag.yml
Fixed the `update-deps` step of creating a tag.
This step is post-creation of new tag, and it's to update the deps in the main branch.
> Fix update dependencies after create tag GHA

- common/dynamicconfig/constants.go
- service/matching/config.go
- service/matching/matching_engine.go
- service/matching/matching_engine_test.go
Removing the dynamic config for `matching.dropNonRetryableTasks` and enable scraping of the metric
We want to scrape this metric and alerts for spikes
_Potentially_ this metric could have high cardinality but this is not expected
> config: enable dropNonRetryableTasks prometheus metric

- service/matching/db.go
When updating ack level for the classic backlog manager, keep the ack level of subqueue zero in sync with the old top-level AckLevel field (used for backwards compatibility).
The periodic sync and sync on unload would previously write the backwards-compatible field, but would only update subqueue zero in memory, to be written on the _next_ update. This made the sync on unload partially ineffective and could lead to needing to scan large ranges on queue reload.
Testing note: This behavior regressed in #7372, but the test that was supposed to catch the regression, `TestTaskQueueManager_CyclingBehavior`, didn't catch it because the test framework had other bugs. Those bugs are being fixed separately in #8016 so this one is easier to cherry-pick.
> Keep subqueue ack level in sync in taskQueueDB

- .github/workflows/run-tests.yml
- .github/workflows/trigger-publish.yml
Introduces `feature/*` as a branch pattern for running tests and publishing Docker images.
The idea is to have a way for long-running feature branches to be tested more easily. This requires the Docker images to be published. Mixing this with the `cloud/*` or `release/*` branch pattern is not ideal as it's confusing and has problematic branch protection settings.
Follow-up work in https://github.com/temporalio/docker-builds/pull/283.
> Feature branch pattern

- service/history/replication/stream_receiver.go
- service/history/replication/stream_receiver_test.go
Use low priority scheduler for Replication SyncWorklfowState task
To serialize sync workflow state task when force replicating closed workflows. 
no risk.
> Use low priority scheduler for sync state task

- service/worker/scheduler/workflow.go
- service/worker/scheduler/workflow_test.go
Bump the `Version` of the `TweakablePolicies` for scheduler component
Patches bug in scheduler
None aware of
> chore: bump the scheduler version for TriggerImmediatelyTimestamp bug

- service/history/replication/executable_task.go
Fix NPE when emit duplicated replication task metrics
To avoid npe
no risk.
> Fix NPE when emit duplicated replication task metrics

- service/matching/config.go
- service/matching/user_data_manager_test.go
Fix GetUserDataRetryPolicy to retry forever.
The default for retry policies is to give up after 1 minute. For the get user data loop, if we give up then we'll just retry immediately, which is fine, but on error we should follow the backoff schedule.
> GetUserDataRetryPolicy should retry forever

- service/history/handler.go
Convert persistence.TimeoutError to serviceerror.DeadlineExceeded errors in history handler.
Frontend handler will mask these errors if they are not converted to service errors.
> Convert persistence.TimeoutError to servicererror.DeadlineExceeded

- service/matching/backlog_manager_test.go
- service/matching/fair_backlog_manager.go
- service/matching/fair_task_writer.go
- service/matching/physical_task_queue_manager.go
Use a separate counter per subqueue in fairTaskWriter.
It works better:
1. Semantically, we want fairness to apply per priority level (tasks from different levels can't really block each other since they go in sequence).
2. Each subqueue has a separate ack level, and the level is determined by the counter, so it makes sense to have separate counters.
> Use separate counter per subqueue

- common/headers/version_checker.go
- Manually updating the server version here since the createTag GH workflow failed due to this branch having an untagged api dependency :sigh:
- hotfix
- None
> Cloud/v1.29.0 136 -update server version

- common/dynamicconfig/constants.go
- service/matching/config.go
- service/matching/fair_task_writer.go
- service/matching/fairness_util.go
- service/matching/matcher_data.go
- service/matching/matcher_data_test.go
- Add support for per-key rate limits that are scaled by weight (so maintaining dispatch in the same order that tasks are read in).
- Refactor simpleLimiter to split parameters and ready time.
Support simple per-key limits.
This uses an LRU cache to track recent tasks by fairness key, default size 2000. With target dispatch rate of 1000 tasks/second/partition, that corresponds to at least 2 seconds of keys (equal in the worst case of fully uniform key distribution, which is unlikely). That means that rates >= 0.5 tasks/second/key/partition should be handled accurately (2 tasks/second/key for default 4 partitions). To handle even lower rates, partition count and task size can be tuned.
> Matching fairness per-key rate limits

- service/frontend/nexus_http_handler.go
More control for custom registry implementations.
> Allow nexus registry to indicate that a not found error is retryable

- chasm/archetype.go
- chasm/lib/workflow/workflow.go
- chasm/ref.go
- chasm/ref_test.go
- chasm/tree.go
- chasm/tree_test.go
- service/history/api/consistency_checker.go
- service/history/api/consistency_checker_mock.go
- service/history/chasm_engine_test.go
- service/history/interfaces/chasm_tree.go
- service/history/interfaces/chasm_tree_mock.go
- service/history/interfaces/workflow_context.go
- service/history/interfaces/workflow_context_mock.go
- service/history/ndc/transaction_manager.go
- service/history/ndc/transaction_manager_mock.go
- service/history/replication/raw_task_converter.go
- service/history/statemachine_environment.go
- service/history/workflow/cache/cache.go
- service/history/workflow/cache/cache_mock.go
- service/history/workflow/context.go
- service/history/workflow/mutable_state_impl_test.go
- service/history/workflow/noop_chasm_tree.go
- CHASM: Make Archetype strongly typed
- Make it easier to tell what value needs to be passed when calling a function expecting an archetype as argument.
> CHASM: Make Archetype strongly typed

- go.mod
- go.sum
- service/history/historybuilder/event_factory.go
- tests/eager_workflow_start_test.go
Set the `EagerExecutionAccepted` flag to true on `WorkflowExecutionStartedEventAttributes` to indicate that the client requested eager execution and the server has permitted it (the dynamic config is on, and there's no start delay).
For debugging purposes.
> Add EagerExecutionAccepted to WorkflowExecutionStartedEventAttributes

- client/frontend/client_gen.go
- client/frontend/metric_client_gen.go
- client/frontend/retryable_client_gen.go
- cmd/tools/getproto/files.go
- common/api/metadata.go
- common/dynamicconfig/constants.go
- common/rpc/interceptor/logtags/workflow_service_server_gen.go
- common/rpc/interceptor/redirection.go
- common/rpc/interceptor/redirection_test.go
- common/testing/mockapi/workflowservicemock/v1/service_grpc.pb.mock.go
- go.mod
- go.sum
- service/frontend/configs/quotas.go
- service/frontend/service.go
- service/frontend/workflow_handler.go
Add stubs for worker commands.
Corresponding API PR: https://github.com/temporalio/api/pull/612
Unblock SDK team.
> stubs for Fetch/Update worker config

- service/frontend/workflow_handler.go
- service/worker/batcher/activities.go
- service/worker/batcher/workflow.go
The `Identity` field is changed from a hardcoded `batch unpause` to the value provided by the client.
Consistency with other activity batch requests 
Minimal, identity is not exposed to users or used by internal systems
> fix: use rpc identity value for batch unpause activities

- common/metrics/tags.go
- service/matching/physical_task_queue_manager.go
- service/matching/pri_matcher.go
- service/matching/pri_task_reader.go
- service/matching/task_reader.go
add "task expire state" tag to the "ExpiredTasksPerTaskQueueCounter" metric.
Possible states - "read", "process", "memory"
For fairness, we remove TTL. We expect that this will lead to reading too many expired tasks.
To be sure we want a metrics tag that will allows us to separate tasks that are expired when we read them from other tasks.
> add expired tasks state to the metric

- service/history/transfer_queue_active_task_executor.go
- service/history/transfer_queue_active_task_executor_test.go
- service/history/transfer_queue_standby_task_executor.go
- service/history/transfer_queue_standby_task_executor_test.go
Now checking if the activity is paused or if the stamp is outdated before dispatching a matching task.
Prevents unnecessary creation and retrying of tasks in matching queues.
N/A
> Check if activity is paused or stamp mismatch in processActivityTask()

- api/matchingservice/v1/request_response.pb.go
- api/taskqueue/v1/message.pb.go
- go.mod
- go.sum
- proto/internal/temporal/server/api/matchingservice/v1/request_response.proto
- proto/internal/temporal/server/api/taskqueue/v1/message.proto
- service/matching/matching_engine.go
- service/matching/task_queue_partition_manager.go
- service/matching/task_queue_partition_manager_test.go
- service/worker/workerdeployment/client.go
- tests/task_queue_stats_test.go
Adding a breakdown of stats per-priority levels to the two APIs that return task queue stats already.
New API is defined here: https://github.com/temporalio/api/pull/611.
> TaskQueue per-priority stats in API

- service/worker/workerdeployment/workflow.go
- tests/worker_deployment_test.go
- Made `RampingVersionPercentageChangedTime` visible to a client (be it the worker-controller or an operator carrying out a `DescribeDeployment` call) from the `RoutingConfig`.
- Safe deploys correctness. Also, this is a big bug. I'm very sorry for skipping over this.
- None, improves the feature. Tested my changes out as well.
> make `RampingVersionPercentageChangedTime ` visible

- service/frontend/configs/quotas.go
- Prioritize APIs for worker heartbeat & completion in frontend rps rate limiter
- Make them the same priority as other change state APIs
- Upon throttling, rejecting those progress APIs could result in workflow/activity/nexus task failure/timeout which means more work for the system to retry those operations and consume more namespace RPS to process the retries.
> Prioritize worker progress APIs

- common/cache/cache.go
- common/cache/lru.go
- common/cache/lru_test.go
- common/dynamicconfig/constants.go
- common/dynamicconfig/shared_constants.go
- service/history/configs/config.go
- service/history/workflow/cache/cache.go
- service/history/workflow/cache/fx.go
This adds support to the lru cache to actively expire entries older than the TTL, by spawning a background goroutine that periodically deletes old entries. A dynamic config, off by default, is added that can enable this feature for the workflow cache.
This can reduce the memory usage, and associated Go GC resource usage, for workflow entries that won't be utilized since they are past their TTL.
Also running this in test setups to verify expected memory reduction.
> support background entry removal for workflow cache

- api/adminservice/v1/request_response.pb.go
- common/dynamicconfig/constants.go
- proto/internal/temporal/server/api/adminservice/v1/request_response.proto
- service/frontend/admin_handler.go
- service/worker/migration/activities.go
- service/worker/migration/activities_test.go
- service/worker/migration/fx.go
- Add capability to generate migration task via frontend.
- We don't really have per namespace rate limiting on history client, going through frontend allow us to rate limiting migration traffic per namespace and protect the cluster.
- Feature is behind a feature flag, so should be safe.
- The feature flag can only be enabled after the change in the admin handler (for forwarding the target cluster field) is deployed.
> Ability to generate migration task via frontend

- common/persistence/cassandra/version_checker.go
- common/persistence/sql/version_checker.go
- temporal/fx.go
- tools/cassandra/version_tests.go
- tools/sql/clitest/version_tests.go
Changes version compability checks to pass the real logger, so that the error messages would be seeing in the log
Before, the error was generic and there were no logs indicating the real error (see https://github.com/temporalio/temporal/issues/7939):
```
sql schema version compatibility check failed: unable to read DB schema version keyspace/database: temporal error: no usable database connection found
```
With this change, the log would contain the actual error:
```
{"level":"error","ts":"2025-07-25T15:30:49.660-0700","msg":"sql handle: unable to refresh database connection pool","error":"pq: no pg_hba.conf entry for host \"127.0.0.1\", ...
```
The alternative solution would be to return the error, but the design of common/persistence/sql/sqlplugin/db_handle.go suggests we hold the …
> Log errors when doing version compatibility check for Cassandra and SQL

- common/authorization/default_jwt_claim_mapper.go
This PR aims to add a limit to the number of parts when splitting an `Authorization` header `Bearer $token` values. 
This is useful for limiting potential abuses from maliciously crafted header values. 
I don't think there's any major risk here?
> Limit the number of parts allowed for auth token

- common/persistence/cassandra/matching_task_store.go
- common/persistence/cassandra/matching_task_store_queue.go
- common/persistence/cassandra/matching_task_store_user_data.go
- common/persistence/cassandra/matching_task_store_v1.go
- common/persistence/cassandra/matching_task_store_v2.go
- common/persistence/sql/sqlplugin/matching_task_queue.go
- common/persistence/sql/sqlplugin/mysql/task_queues.go
- common/persistence/sql/sqlplugin/postgresql/task_queues.go
- common/persistence/sql/sqlplugin/sqlite/task_queues.go
Remove some code duplication for cassandra matching task queue persistence by rewriting v2 to v1 queries.
Switch same scheme for SQL queries to use the v2 table name in the base query and rewriting v1.
Use panic instead of returning an invalid query.
Remove code duplication.
> Consolidate cassandra task queue management queries

- common/priorities/priority_util.go
- common/priorities/priority_util_test.go
Handle fairness fields in priorities.Merge
> Handle fairness in priorities.Merge

- components/callbacks/fx.go
Adding error to log message when failing to get an HTTP client for a remote cluster for a callback request.
> Include error when failing to get callback HTTP client

- service/matching/backlog_manager.go
- service/matching/config.go
- service/matching/db.go
- service/matching/fair_backlog_manager.go
- service/matching/fair_task_reader.go
- service/matching/fair_task_writer.go
- service/matching/physical_task_queue_manager.go
- service/matching/pri_backlog_manager.go
- service/matching/pri_task_reader.go
- service/matching/pri_task_writer.go
- service/matching/task_writer.go
Added new types `subqueueKey` and `priorityKey`.
Instead of int/int32, the types help with documentation and incorrect usage.
> Add subqueueKey and priorityKey types

- common/cluster/frontend_http_client.go
Setting `ForceAttemptHTTP2=true` for remote frontend HTTP clients. Local FE clients already set this.
ForceAttemptHTTP2 is the default except when providing a custom Dial , DialTLS , DialContext , or TLSClientConfig to prevent breaking older code: https://github.com/golang/go/issues/14275
We set this parameter to true for local clients, so when TLS is enabled and a failover happens, callback requests will fail because the cluster uses a local frontend to make the request with HTTP2 which is then forwarded using HTTP1.x and causes a malformed response.
> Set `ForceAttemptHTTP2=true` for remote frontend HTTP clients

- api/persistence/v1/executions.go-helpers.pb.go
- api/persistence/v1/executions.pb.go
- proto/internal/temporal/server/api/persistence/v1/executions.proto
Adding proto changes to capture pause information. This contains 2 main objects:
1. WorkflowPauseInfo: A container to capture pause information in a given workflow. Adding this for future compatibility. The intention is to use this container for other workflow level pause information like timeouts, signals, child workflows etc.
2. ActivityPauseInfo: A container to capture pause information for a given activity type. Since individual activity types can be paused, we need to capture the pause state, identity & reason for better debugging.
Note: Sending just the proto changes so that we can work on implementation in parallel.
To implement pause activity and eventually pause workflow feature. Need this space to save the state information.
N/A
> [Pause] - Add WorkflowExecutionInfo.pause_info proto

- common/priorities/priority_util.go
- common/priorities/priority_util_test.go
- service/frontend/workflow_handler.go
- service/history/api/command_attr_validator.go
Add validation for Priority metadata.
Negative keys/weights are ignored but we should reject requests with too-long keys.
> Validate Priority metadata

- common/dynamicconfig/constants.go
- service/worker/scanner/executions/task.go
- service/worker/scanner/executions/task_test.go
- service/worker/scanner/scanner.go
- service/worker/scanner/scanner_test.go
Break out of the loop, when iteration through mutable states fails
Previously, we continued to iterate, leading to the panic: https://github.com/temporalio/temporal/issues/8037
> Break out of pagination in scavenger on errors

- common/persistence/serialization/codec.go
- common/persistence/serialization/codec_test.go
Don't catch `Data: nil` in test; let it fall through to decoder. The decoder will return an error. An error is the better choice than a `nil` response since that signals to the user that the decoded data is usable/valid.
Follow-up to https://github.com/temporalio/temporal/pull/8111; an internal test expects an error instead of `nil`.
Hard to believe that returning nil and using un-decoded data is a good/valid alternative.
> Decode of nil data

- client/matching/retryable_client.go
- client/matching/retryable_client_gen.go
- cmd/tools/genrpcwrappers/main.go
- common/resource/fx.go
- common/util.go
Allow frontend->matching poll requests to retry up to their context timeout instead of just once.
On matching service deployments, a busy new matching node may hit its persistence rps limit trying to acquire new task queues and be unable to accept polls.
> Allow more retries for matching client polls

- client/frontend/client_gen.go
- client/frontend/metric_client_gen.go
- client/frontend/retryable_client_gen.go
- common/api/metadata.go
- common/rpc/interceptor/logtags/workflow_service_server_gen.go
- common/rpc/interceptor/redirection.go
- common/rpc/interceptor/redirection_test.go
- common/testing/mockapi/workflowservicemock/v1/service_grpc.pb.mock.go
- service/frontend/configs/quotas.go
- service/frontend/nexus_handler.go
- service/frontend/workflow_handler.go
- tests/nexus_api_test.go
- tests/nexus_test_base.go
* Renamed Get -> Fetch for Nexus external caller APIs
* Removed direct Nexus task dispatch by task queue
> Nexus remove direct dispatch + rename Get to Fetch

- common/nexus/failure.go
- service/frontend/workflow_handler.go
For Nexus gRPC APIs, when the Nexus client returns a HandlerError that is the fault of the server, that error is converted back to a `serviceerror`
So that metrics and SLAs are tracked appropriately
> Convert Nexus HandlerError back to serviceerror for gRPC APIs

- service/history/replication/executable_verify_versioned_transition_task.go
- service/history/replication/executable_verify_versioned_transition_task_test.go
Fix VerifyVersionedTransition Task
Without fix, there is risk of success the task without verifying.
no risk.
> Fix VerifyVersionedTransition Task

- common/dynamicconfig/collection.go
Removed warning logs for shared dynamic config structures
Was failing integration tests
> Remove dynamic config warnings for shared structures

- service/worker/migration/fx.go
- service/worker/migration/handover_workflow.go
- service/worker/migration/handover_workflow_test.go
Adding minimum timeout require in system workflow
The system workflow needs to have sufficient time to execute the defer logic.
> Adding minimum timeout require in system workflow

- service/worker/batcher/activities.go
Batch workflows were panicking because executions can be nil, but there is no check to prevent nil pointer exception.
Prevent nil-ptrs
NA
> fix: handle nil ptr in batch processing

- cmd/tools/codegen/helpers.go
- cmd/tools/codegen/helpers_test.go
- cmd/tools/getproto/main.go
- common/archiver/gcloud/util.go
- common/archiver/s3store/visibility_archiver.go
- common/authorization/default_jwt_claim_mapper.go
- common/headers/version_checker.go
- common/persistence/data_interfaces.go
- common/persistence/history_task_queue_manager.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go
- common/persistence/sql/sqlplugin/sqlite/visibility.go
- common/persistence/visibility/store/sql/query_converter_util.go
- common/persistence/visibility/store/sql/query_converter_util_test.go
- common/telemetry/env.go
- common/util/proto.go
- common/util/wildcard.go
- components/callbacks/config.go
- components/callbacks/config_test.go
- components/nexusoperations/frontend/handler.go
- service/frontend/nexus_handler.go
- service/worker/scheduler/calendar.go
- tools/cassandra/handler.go
This PR aims to avoid usage of [`strings.Split`](https://pkg.go.dev/strings#Split) where possible in favor of better string splitting techniques, speficially: [`strings.SplitN`](https://pkg.go.dev/strings#SplitN) and [`strings.SplitSeq`](https://pkg.go.dev/strings#SplitSeq) where appropriate. 
There was also a [`strings.Fields`](https://pkg.go.dev/strings#Fields) change I made to use [`strings.FieldsSeq`](https://pkg.go.dev/strings#FieldsSeq) instead, and another for S3 to use the [`path`](https://pkg.go.dev/path) package instead of [`strings.Split`](https://pkg.go.dev/strings#Split).
[`strings.SplitN`](https://pkg.go.dev/strings#SplitN) and [`strings.SplitSeq`](https://pkg.go.dev/strings#SplitSeq) are often better options in many cases, and can be _partially_ detected using …
> Use better string splitting techniques where possible

- .github/.golangci.yml
- common/contextutil/deadline.go
- common/contextutil/deadline_test.go
- common/metrics/grpc_test.go
- common/rpc/grpc.go
- common/rpc/interceptor/frontend_service_error.go
- common/rpc/interceptor/frontend_service_error_test.go
- common/testing/rpctest/transport_stream.go
- service/frontend/fx.go
- service/frontend/fx_test.go
- service/history/api/get_workflow_util.go
- service/matching/matching_engine.go
- service/matching/physical_task_queue_manager.go
- service/matching/user_data_manager.go
Added a "soft timeout" (language used by Workflow Update) to `GetWorkflowExecutionHistory` long polls.
We don't want to terminate the long poll connection but instead keep it alive by sending a response back just before the timeout. The idea is that this will prevent connections from opening/terminating repeatedly (ie connection churn). 
I was only able to verify this manually by forcing a timeout in the server and verifying that instead of a deadline exceeded I saw a result. I'll assume this will work since the existing code already tried doing just exactly that, but it didn't do it well.
> GetWorkflowExecutionHistory long poll soft timeout

- common/dynamicconfig/constants.go
- common/rpc/interceptor/namespace_rate_limit.go
- service/frontend/fx.go
- service/frontend/fx_test.go
- service/frontend/nexus_handler_test.go
- service/frontend/service.go
Remove the config key frontend.reducePollWorkflowRequestPriority.
We recently added a change to assign lower priority values to GetHistoryRequests which wait for the workflow to finish.
This config was added as safety switch to disable this change. It has been a few months since this and it is working as expected. So we do not need this config.
> Remove the config key frontend.reducePollWorkflowRequestPriority

- common/metrics/metric_defs.go
- service/history/api/respondactivitytaskcanceled/api.go
- service/history/api/respondactivitytaskcompleted/api.go
- service/history/api/respondactivitytaskfailed/api.go
- service/history/api/respondactivitytaskfailed/api_test.go
- service/history/timer_queue_active_task_executor.go
- service/history/timer_queue_active_task_executor_test.go
- service/history/workflow/metrics.go
Changes activity metrics
- **activity_e2e_latency** → Deprecated, as it measures individual attempts rather than true end-to-end latency, and replaced with clearer **activity_start_to_close_latency**
- **activity_start_to_close_latency**: Measures the latency from activity start to close (per attempt).
- **activity_schedule_to_close_latency**: Measures true end-to-end duration, including retries and backoff.
- **activity_success**: Counts the number of succeeded activities. Aligned with the existing **workflow_success** counter.
- **activity_fail**: Counts final failures for activities. Similar to **workflow_failed,** although it doesn’t include retries.
- **activity_timeout**: Incremented on the final activity timeout (including ScheduleToStartTimeout), tagged by `timeout_type`. Aligned …
> Record various activity metrics

- common/rpc/interceptor/namespace_rate_limit.go
- service/frontend/configs/quotas.go
Reduce PollWorkflowExecution API priority to 5.
A spike in PollWorkflowExecution requests should not block other Poll* APIs stalling workflow progress.
> Reduce PollWorkflowExecution priority

- chasm/component.go
- chasm/test_component_test.go
- Force component to implement LifecycleState method
- Remove LifecycleStateUnspecified definition
- Component author should always think about and specify the component's lifecycle state, that's a core concept in the framework. Default implementation doesn't really work.
> CHASM: force component to implement LifecycleState method

- common/persistence/nosql/nosqlplugin/cassandra/gocql/interfaces.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/query.go
Adding interface methods to Set Idempotency and SpeculativeRetryPolicy on gocql queries
We want to experiment with setting speculative retry policy in queries from cds to allow for faster detection of faulty nodes and return result before timeout by trying a different node.
> Adding interface methods for setting Idempotency and SpeculativeRetryPolicy on the underlying gocql query

- tests/versioning_3_test.go
I was not detecting the retryable "task queues not found in proposed current version" error correctly, which meant that the SetCurrent operation was not retried, even when it should have been retried.
Basically, this "fix" didn't actually work because I was not detecting the error correctly: https://github.com/temporalio/temporal/commit/8939899df70b20a4570f9311afd3558d00616e13
To reduce flakiness
> Improve ChildWF_CrossTQ flake - retry on missing task queues error

- service/matching/config.go
- service/matching/matcher.go
- service/matching/matcher_data.go
- service/matching/matcher_data_test.go
- service/matching/matching_engine_test.go
- service/matching/physical_task_queue_manager.go
- service/matching/pri_matcher.go
- service/matching/ratelimit_manager.go
- service/matching/ratelimit_manager_test.go
- service/matching/task_queue_partition_manager.go
- tests/task_queue_test.go
Reverts temporalio/temporal#8263 which reverted https://github.com/temporalio/temporal/pull/8135
So this is https://github.com/temporalio/temporal/pull/8135 plus a fix for flaky tests.
Comparing the results of the test runs (4 each) for the original (1st commit) and fix (2nd commit), I can only conclude that the issue has been addressed.
> TaskQueue Fairness Rate Limit redo

- common/authorization/interceptor.go
- common/authorization/interceptor_test.go
- common/dynamicconfig/constants.go
- service/frontend/fx.go
- service/frontend/nexus_handler_test.go
- service/frontend/service.go
Added a new dynamic config to control whether the frontend authorization interceptor should expose errors returned by the `Authorizer` component. Previously (now default), if the `Authorizer` returned an error, the intercepter would always return a generic `PermissionDenied` error without details.
Authorizers may fail with errors that should not be translated into `PermissionDenied`
> Add dc to expose Authorizer errors

- common/dynamicconfig/constants.go
- service/history/configs/config.go
- service/history/replication/executable_task.go
- service/history/replication/executable_task_test.go
- tests/ndc/replication_migration_back_test.go
- tests/ndc/replication_task_batching_test.go
- tests/xdc/stream_based_replication_test.go
Remove Eager Refresh Namespace Dynamic Config
The feature is enabled for long time and we can enable it by default and no dc is required.
no risk.
> Remove Eager Refresh Namespace Dynamic Config

- config/dynamicconfig/development-cass.yaml
- config/dynamicconfig/development-sql.yaml
- config/dynamicconfig/development-xdc.yaml
The config was commented out in our development config files but has been removed from the codebase since v1.18.
> Remove frontend.enableClientVersionCheck commented configs

- go.mod
- go.sum
Cherry pick the change Updating api version to v1.53.0 (#8289)
Release needs a tagged API version
> Update api version to v1.53.0

- service/frontend/fx.go
Enable HTTP API on internal frontend if HTTP port is configured.
Closes #7386
Ran the server with all services:
```
go run ./cmd/server --env development-sqlite --allow-no-auth start --service internal-frontend --service ...
```
Added an `internal-frontend` config to `config/development-sqlite.yaml` and removed the `frontend` HTTP port:
```
-      httpPort: 7243
+  internal-frontend:
+    rpc:
+      grpcPort: 7236
+      membershipPort: 6936
+      bindOnLocalHost: true
+      httpPort: 7246
```
Ran the Go Nexus sample.
> Enable HTTP API server on internal frontend

- components/nexusoperations/executors.go
- components/nexusoperations/executors_test.go
- Changed failure source to use correct context.
- Handled request timeouts avoid exposing internal info to user. 
In the nexus executor, the ctx when setting the failure source is not using the call ctx, but the original request context. This should be switched to use the call ctx for consistency. 
During executor request timeouts, we should not expose internal info to the user. To address it, we are setting a new error with a message that doesn't contain  such info.
> Changed nexus executor failure source to use correct context.

- service/history/api/signalwithstartworkflow/signal_with_start_workflow.go
- service/history/api/startworkflow/api.go
- service/history/api/workflow_id_dedup.go
- service/history/history_engine2_test.go
- Extend workflowID reuse interval to closed workflows
- Current check only applies to conflict policy & running workflows, which can really prevent users from generating hot workflowIDs.
- 
- This is a hot fix, will follow up with new functional tests in a different PR.
- This feature is disabled by default.
> Extend workflowID reuse interval to closed workflows

- common/persistence/sql/sqlplugin/mysql/visibility.go
- common/persistence/sql/sqlplugin/postgresql/visibility.go
- common/persistence/sql/sqlplugin/sqlite/visibility.go
- common/persistence/sql/sqlplugin/visibility.go
- common/persistence/visibility/store/sql/visibility_store.go
Move converting `time.Time` values for `Datetime` type search attributes to the DB plugin code. 
This gives more flexibility for the plugin implementation to deal with it as needed.
> Refactor Visibility SQL parsing search attributes for DB write

- common/nexus/failure.go
- components/nexusoperations/frontend/handler.go
- service/frontend/nexus_handler.go
- tests/nexus_api_test.go
- tests/nexus_workflow_test.go
Adapt the Nexus handler code to be compatible with the `frontend.exposeAuthorizerErrors` dynamic config introduced in #8276 
This was missed as part of the initial implementation.
Added new functional test(s)
> Support exposing authorizer error in Nexus APIs

- config/docker.yaml
- docker/config_template.yaml
> Add internal HTTP port in docker config templates

- tests/callbacks_test.go
Remove the `WorkflowRunTimeout` from test workflow
Potential cause of flaky tests
Testing only
> tests: remove WorkflowRunTimeout from nexus test

- tests/testcore/onebox.go
Added functionality to override the dynamic config client log level to INFO for all services in the functional tests. 
The dynamic config client introduced in #7052 logs "No such key in dynamic config, using default" at DEBUG level every time a dynamic config key is checked without an override. This creates extremely noisy logs during testing as it fires for many dynamic config checks, making it difficult to see relevant test output and debug information.
This approach:
- Only affects the dynamic config client logging, not the main service logs
- Only applicable to tests not production code
> Reduce dynamic config client log level to INFO to address noisy debug logging

- service/history/api/respondactivitytaskcanceled/api.go
- service/history/api/respondactivitytaskcompleted/api.go
- service/history/api/respondactivitytaskfailed/api.go
- service/history/api/respondactivitytaskfailed/api_test.go
- service/history/timer_queue_active_task_executor.go
Adding new `versioning_behavior` tag to the newly added activity metrics so we can compare activity failure and timeout rates between users using versioning vs the ones who don't.
above.
None. new tag has only 3 values (low cardinality)
> Add versioning behavior tag to activity metrics

- .github/workflows/run-tests.yml
~Removed crash reporting from unit tests.~
Bumped unit test job timeout.
~Unit tests don't emit JUnit reports; so when they fail it's reported that they "crashed".~
Make sure test-runner has enough time for re-runs.
> Bump unit test timeout

- common/persistence/query_util.go
- common/persistence/query_util_test.go
- schema/postgresql/v12/visibility/schema.sql
- schema/postgresql/v12/visibility/versioned/v1.2/advanced_visibility.sql
- tools/common/schema/updatetask.go
`CREATE EXTENSION` sql query is replaced with a pgsql script that checks for the existence of the extension programatically.
`CREATE EXTENSION` can cause issues in environment where creating extensions are limited to certain users. (e.g. Azure)
I've ran the updated schema setup in both environments where btree_gin is installed and and not installed.
Regression in visibility database setup.
Not needed.
No
> fix(schema): check for extension before creating

- tests/worker_registry_test.go
Heartbeat registration can happen as part of PollNexusTaskQueue API as well. This is an optimization to piggy back on the long poll instead of sending a separate heartbeat.
In addition, made changes to existing test to verify the heartbeat result.
Increase coverage.
None.
> Add functional test to verify heartbeat is registered via PollNexusTaskQueue API.

- common/persistence/cassandra/mutable_state_task_store.go
- common/persistence/data_interfaces.go
- common/persistence/sql/execution_tasks.go
Add a field to CompleteHistoryTaskRequest that suggest that this request can be ignored by persistence layer if needed.
Cassandra's MutableStateTaskStore will ignore the request if BestEffort is set to true.
This allows persistence layer to ignore requests if it can negatively impact underlying storage.
> Add BestEffort field to CompleteHistoryTaskRequest

- chasm/field.go
- chasm/field_test.go
- chasm/tree.go
- chasm/tree_test.go
- Improve sync sub component logic so that syncing only happens when the node is dirty. Instead of always sync when node is deserialized. 
- Allow doing multiple transitions and sync sub component step per transaction.
> CHASM: Improve sync sub component logic

- chasm/tree.go
- chasm/tree_test.go
- Support Immediate Pure Task and run them in the same transaction as they are generated.
- Depends on https://github.com/temporalio/temporal/pull/8399
- Currently immediate pure task is the only way for component to run logic that depends on things that are not part of component states (e.g. logger, metrics handler, other util structs)
> CHSAM: Support Immediate Pure Task

- tests/nexus_api_test.go
Nexus test poller:
- Ignore empty Nexus task responses, this may happen on slow CI
- Ignore not found errors when posting a task completion, it may be happen on slow CI
This background poller has been seen to panic in certain edge cases
> Nexus poller test edge case fixes

- service/history/replication/sync_state_retriever.go
- service/history/replication/sync_state_retriever_test.go
Skip sending newRuninfo when new run is not created in current cluster
If new run is not created at current cluster, it means the transaction is not happened at current cluster, so the current cluster should no include new run in the current run replication task.
no risk.
> Skip sending newRuninfo when new run is not created in current cluster

- common/dynamicconfig/constants.go
- service/history/archival_queue_factory.go
- service/history/configs/config.go
- service/history/outbound_queue_factory.go
- service/history/queues/action.go
- service/history/queues/action_move_group.go
- service/history/queues/action_pending_task_count.go
- service/history/queues/action_reader_stuck.go
- service/history/queues/action_slice_count.go
- service/history/queues/action_slice_predicate.go
- service/history/queues/mitigator.go
- service/history/queues/mitigator_test.go
- service/history/queues/queue_base.go
- service/history/queues/queue_base_test.go
- service/history/queues/reader.go
- service/history/queues/reader_test.go
- service/history/queues/scope.go
- service/history/queues/slice_test.go
- service/history/tasks/predicates.go
- service/history/tasks/predicates_test.go
- service/history/timer_queue_factory.go
- service/history/transfer_queue_factory.go
- service/history/visibility_queue_factory.go
- Introduced a new "move (task) group" action replacing the "incorrect" slice-predicate action. See inline comment for how it works.
- Improve task Predicate AND/OR calculation to reduce predicate size.
- Skip empty slices when adding queue slices to readers.
- Better namespace isolation.
- The new action can be disabled via dc.
> Improve multi-cursor actions

- common/persistence/history_manager.go
- common/persistence/history_manager_util.go
- common/softassert/serviceerror.go
- common/softassert/softassert.go
- service/frontend/workflow_handler_test.go
- service/history/api/get_history_util.go
- service/history/api/getworkflowexecutionhistory/api.go
- service/history/replication/executable_task.go
- service/history/replication/executable_verify_versioned_transition_task.go
Added a new helper `UnexpectedDataLoss` to combine logging and error construction in one go.
And applied it everywhere since I assume every DataLoss is _unexpected_.
Just like https://github.com/temporalio/temporal/pull/8388 it combines the two affordances of `softassert.Fail` and constructing an error.
> softassert serviceerror.DataLoss helper

- .github/workflows/flaky-tests-report.yml
Change flaky tests to run only on Wednesdays
Get a better signal and avoid alert fatigure.
N/A
> Change flaky tests report schedule to Wednesdays

- chasm/statemachine.go
Pre-requisite for porting the HSM components to CHASM.
> Port the state machine minimal abstraction from HSM to CHASM
