temporalio/temporal

- cmd/server/temporal/server.go
- common/persistence/persistenceRateLimitedClients.go
These were not caught as I (incorrectly) assumed the integration tests ran through these server initialization paths.
> Runtime bug fixes for ClusterMetadata initialization

- service/frontend/accessControlledHandler.go
- service/frontend/dcRedirectionHandler.go
- service/frontend/workflowHandlerGRPC.go
Old Thrift version of `health` service was used before. Now it used proto version.
> Use gRPC healthservice from frontend handler 

- common/membership/rpMonitor_test.go
- common/membership/rpServiceResolver.go
- common/membership/rp_cluster_test.go
- common/resource/resourceImpl.go
- common/service/config/config.go
- common/service/config/ringpop.go
This allows Temporal services to broadcast a different IP address to be connected on by other members of the cluster. This enables multi-host setups to listen on 0.0.0.0, but still requires a static address at runtime (Dynamic methods or DNS is not supported).
`BroadcastAddress` is configured under the `ringpop` configuration section and accepts any valid IPv4 address.
This is implements a Custom Host Identity from -  https://github.com/temporalio/temporal/issues/83
> Add Ringpop 'BroadcastIp' configuration option

- service/frontend/workflowHandler.go
- service/frontend/workflowHandler_test.go
Found that if service received headers through gRPC (`workflowHandlerGRPC`), YARPC in matching and history services can't read it. Set them manually as temporary solution.
> Fix YARPC context propagation

- host/activity_test.go
- host/archival_test.go
- host/cancelworkflow_test.go
- host/client_integration_test.go
- host/continueasnew_test.go
- host/elasticsearch_test.go
- host/gethistory_test.go
- host/integration_test.go
- host/ndc/replication_integration_test.go
- host/queryworkflow_test.go
- host/signalworkflow_test.go
- host/sizelimit_test.go
- host/taskpoller.go
- host/xdc/elasticsearch_test.go
- host/xdc/integration_failover_test.go
I did too aggressive renames last time (#113) and did not realized that most of errors in the logs are actually `.Info`, not `.Error`.
> Fix integration test log messages

- common/persistence/sql/sqlClusterMetadataManager.go
- common/persistence/versionHistory.go
- common/testing/history_event_test.go
- common/testing/history_event_util.go
- host/client.go
- host/ndc/nDC_integration_test.go
- host/ndc/replication_integration_test.go
- host/onebox.go
- host/testcluster.go
Mostly mechanical changes from Thrift packages (`shared`, `history`) to proto packages (`commonproto`, `historyservice`, `enums`).
> Migrate nDC integration tests to history gRPC client

- common/persistence/cassandra/cassandraClusterMetadata.go
- common/persistence/persistence-tests/clusterMetadataManagerTest.go
Also reduce workload of Paging test so there is less risk of TTL expiry
> Cassandra GetClusterMembers - Explicitly set pagingToken to nil when no records found

- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/cassandra/cassandraPersistenceUtil.go
- common/persistence/dataInterfaces.go
- common/persistence/persistence-tests/executionManagerTest.go
- common/persistence/persistence-tests/executionManagerTestForEventsV2.go
- common/persistence/persistence-tests/persistenceTestBase.go
- common/persistence/sql/blob.go
- common/persistence/sql/sqlExecutionManager.go
- common/persistence/sql/sqlExecutionManagerUtil.go
- common/persistence/sql/sqlHistoryManager.go
- common/persistence/sql/sqlMetadataManagerV2.go
- common/persistence/sql/sqlTaskManager.go
- common/persistence/sql/sqlplugin/interfaces.go
- common/persistence/sql/workflowStateMaps.go
- common/persistence/sql/workflowStateNonMaps.go
- common/primitives/uuid.go
- proto/persistenceblobs/persistenceblobs.proto
- proto/sqlblobs/sqlblobs.proto
- schema/cassandra/cadence/schema.cql
- schema/cassandra/cadence/versioned/v1.0/schema.cql
- service/history/historyEngineInterfaces.go
- service/history/nDCTaskUtil.go
- service/history/replicationTaskProcessor.go
- service/history/replicationTaskProcessor_test.go
- service/history/replicatorQueueProcessor.go
- service/history/replicatorQueueProcessor_test.go
- service/history/transferQueueProcessorBase.go
- tools/cli/adminKafkaCommands.go
Roughly same changes as ShardInfo - https://github.com/temporalio/temporal/pull/136
- Convert sql thrift usage of sqlblobs.ReplicationTaskInfo to persistenceblobs.ReplicationTaskInfo proto
- Cassandra now uses data/encoding to persist the proto file
- Serialization still happens at store level and will need to be migrated to manager, so for now Cassandra imports the SQL serializer
- As ReplicationTask used to meet the queueTaskInfo interface, the interface was changed to meet the raw types of IDs (string uuid -> []byte uuid) and int types (int->int32).
- The non-proto tasks needed (timer and transfer) to meet this new interface as well and runtime conversions were added, but they will eventually be converted to protos as well.
> ReplicationTask Proto Persistence

- Dockerfile
We no longer need SSH_PRIVATE_KEY argument while generating docker
images.
> Dockerfile updates after open sourcing the repo

- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/cassandra/cassandraPersistenceUtil.go
- common/persistence/dataInterfaces.go
- common/persistence/persistence-tests/executionManagerTest.go
- common/persistence/persistence-tests/executionManagerTestForEventsV2.go
- common/persistence/persistence-tests/persistenceTestBase.go
- common/persistence/sql/blob.go
- common/persistence/sql/sqlExecutionManager.go
- common/persistence/sql/sqlExecutionManagerUtil.go
- proto/persistenceblobs/persistenceblobs.proto
- proto/sqlblobs/sqlblobs.proto
- schema/cassandra/cadence/schema.cql
- schema/cassandra/cadence/versioned/v1.0/schema.cql
- service/history/nDCStandbyTaskUtil.go
- service/history/nDCTaskUtil.go
- service/history/queueAckMgr_test.go
- service/history/transferQueueActiveProcessor.go
- service/history/transferQueueActiveProcessor_test.go
- service/history/transferQueueProcessorBase.go
- service/history/transferQueueStandbyProcessor.go
- service/history/transferQueueStandbyProcessor_test.go
- Converting TransferTask pogo usage into proto
- SQL - Move TransferTask thrift serialization to Proto
- Cassandra - Move from Frozen<transfer_task> to proto
- Serialization occurs at store level until ExecutionStore interface is created with datablobs
> TransferTask Proto Persistence

- cmd/server/temporal/server.go
- cmd/server/temporal/temporal.go
- common/resource/bootstrapParams.go
- common/resource/resourceImpl.go
- common/service/config/config.go
- config/development.yaml
- config/development_active.yaml
- config/development_es.yaml
- config/development_mysql.yaml
- config/development_other.yaml
- config/development_postgres.yaml
- config/development_prometheus.yaml
- config/development_standby.yaml
- go.sum
- host/onebox.go
- host/testcluster.go
- Server config section introduced 
- Pprof and ringpop moved under Server section
- Pprof is now initialized once per process
**Why?**
- To make sense of pprof and other settings which should run only once per process
Integ Tests, Manual Server Start
- Pprof stops working
- Ringpop is misconfigured and causes Server to stop.
> Make pprof once per process, introduce Server config section

- Dockerfile
- docker/docker-compose.yml
- docker/start.sh
Docker container can be configured to automatically register a
default domain when container starts up.  Use the flag
'SKIP_DEFAULT_DOMAIN_CREATION' to skip creation of default domain.
Removed tcheck layer from Dockerfile as all tchannel rpc is now
removed.  Also cleaned up unnecessary ports from docker-compose
definition.
**Why?**
This simplifies Temporal experience, as first time users won't have 
to think about domain concept.  Once they download and run docker
container for the service it will automatically create a default domain 
when container comes up.
Buildkite automatically builds all relevant images and pushes to
dockerhub.
Tested docker-compose changes locally by bringing up the server
with 'SKIP_DEFAULT_DOMAIN_CREATION' set to 'true' …
> Register default domain on container start up

- common/service/dynamicconfig/config.go
- config/development.yaml
- config/dynamicconfig/development.yaml
Development dynamicConfig path is wrong, updating to reference path correctly. Additionally adding additional dynamicConfig values (set to their existing defaults) to give example definitions.
> Fix DynamicConfig Path, add more local dynamicConfig values

- tools/cli/app.go
- tools/cli/defs.go
Updated tctl to use following defaults:
- domain = "default"
- workflowIdReusePolicy = enums.WorkflowIdReusePolicyAllowDuplicate 
**Why?**
Better usability in default situations
Tested against local samples and temporal server with before and after behavior.
Defaults have changed, users must update behavior
> CLI Defaults - Domain 'default' and WRP 'AllowDuplicate'

- Makefile
- docs/persistence.md
Adding convenience target to allow schema installation for pre 5.7.20 mysql installs.
> Add makefile target for legacy mysql schema

- Makefile
- go.mod
- go.sum
Dependencies are not installed as part of building executables
**Why?**
It feels unnecessary to install dependencies for all built binaries
and could cause permissions issues on some machines.
Also some go.mod changes if you are running with 1.14 runtime.
Local build.
No risk
> Update makefile to not install dependencies for binaries

- tools/cli/flags.go
Fix help message to swap workflowIdReusePolicy values
**Why did you make the changes?**
Help message should be heplful
**Testing?**
I didnt
**Risks?**
Noone
> Fix default workflowIdReusePolicy in help message

- .buildkite/pipeline.yml
- Makefile
- docker/buildkite/Dockerfile
- docker/buildkite/docker-compose.yml
`Makefile` refactored.
On a fresh machine devs supposed to run `make` and it will install all required tools/plugins and builds binaries.
On regular basic, you don't need to update tools every time, so just run `make bins` to get all binaries or `make all` to run all possible tests and checks.
Run `make update-proto` when you need to update proto submodule with new changes.
Besides `lint` I added few other checks and they generates bunch of errors now, but these errors (as well as lint errors) do not stop build. Let's say they are warnings which we need to fix.
I changed buildkite pipeline. Before binaries where build on every step although they are not needed for tests at all. Now there is 1st step, which builds everything and run all checks. If it passed all tests are …
> Cleanup Makefile

- go.mod
- service/history/transferQueueActiveTaskExecutor.go
Using correct `context` package now.
**Why?**
Wrong `context` package was used in one file.
Run tests.
No risks.
> Fix wrong context package and update go to 1.14

- service/frontend/workflowHandler.go
We seemed to have introduced a bug earlier, which returned NamespaceID
in the RunID field as response to RespondDecisionTaskCompleted when
we have new events which cause a new decision to be returned.
This fixes the bug to return the RunID instead of NamespaceID.
**Why?**
Fixes a silly bug introduced earlier.
Ran branch sample which consistently reproduces this error.
No risk.
> Fixes response to return RunID instead of NamespaceID

- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/dataInterfaces.go
- common/persistence/persistence-tests/executionManagerTest.go
- common/persistence/persistence-tests/persistenceTestBase.go
- common/persistence/persistence-tests/shardPersistenceTest.go
- schema/cassandra/temporal/schema.cql
- schema/cassandra/temporal/versioned/v1.0/schema.cql
- schema/mysql/v57/temporal/schema.sql
- schema/mysql/v57/temporal/versioned/v0.1/base.sql
- schema/postgres/temporal/schema.sql
- schema/postgres/temporal/versioned/v0.1/base.sql
- service/history/historyEngine3_eventsv2_test.go
- service/history/replicationDLQHandler_test.go
- Remove unused BufferedReplicationTasks in persistence schema
- Also removed pblobs alias usage in this PR
**Why?**
Cleaning up schema and these are unused tables/fields/types
Buildkite/Local unit testing
None as they are not used
> Remove unused BufferedReplicationTasks in schema

- common/membership/rpServiceResolver.go
- docker/config_template.yaml
Users can specify 0.0.0.0 in BindOnIp which will never work for both membership sharding in a multi-node cluster and reachability as 0.0.0.0 is not a valid connect address. This requires users to specify BroadcastAddress in this case. 
1: Bind 0.0.0.0, Broadcast Unspecified - Failure
2: Bind Anything else, Broadcast Unspecified - Use Bind address
3: Bind Anything else, Broadcast Specified - Use Broadcast
4: Bind 0.0.0.0, Broadcast Specified - Use Broadcast
Also exposing this option in a new Docker environment variable `TEMPORAL_BROADCAST_ADDRESS`
**Why?**
To provide an easier way to determine this issue/invalid configuration for customers. 
Tested this by manually starting the server with the matrix of possible cases.
None
> Require BroadcastAddress when BindOnIP 0.0.0.0

- docker/start.sh
This exposes an environment variable knob to expose a way to use the correct connectAttributes for legacy MySQL (<5.7.20).
**Why?**
Customers need to be able to setup their schema in legacy MySQL installations.
I have not verified this change manually 
Conditonal option that does not introduce any default behavior.
> Expose MySQL connectAttributes for schema setup

- docker/docker-compose-es.yml
- docker/docker-compose-mysql.yml
- docker/docker-compose-postgres.yml
- docker/docker-compose.yml
Docker compose now uses the latest release server tags from docker hub
**Why?**
Getting started experience pulls docker-compose file from the repo to 
function correctly. 
Locally run docker-compose up
No risk.
> Update docker tag for latest server release 0.21.1

- docker/docker-compose-es.yml
- docker/docker-compose-mysql.yml
- docker/docker-compose-postgres.yml
- docker/docker-compose.yml
What changed?
Docker compose now uses the latest release web tags from docker hub
Why?
Getting started experience pulls docker-compose file from the repo to
function correctly.
How did you test it?
Locally run docker-compose up
Potential risks
No risk.
> Update docker web tag 0.21.1

- common/persistence/cassandra/cassandraMetadataPersistenceV2.go
- common/persistence/metadataStore.go
- host/onebox.go
Cassandra implementation of CreateNamespace to return 
NamespaceAleadyExistsError instead of InternalServiceError 
it was returning before.
Also updated onebox setup used for integration tests to also use
the newly added InitializeSystemNamespace API.
**Why?**
Cassandra implementation returns InternalServiceError on duplicate
calls to namespace registration instead of NamespaceAleadyExistsError
which is preventing Temporal server to start as now we try to register
SystemNamespace on server startup.
Updated integration tests to use the new InitializeSystemNamespace API.
Test Temporal Server so it starts on dev machine.
Fixes a critical bug which is preventing server to start.
> Return NamespaceAlreadyExistsError from CreateNamespace implementation

- service/history/decisionChecker.go
- service/history/historyEngine_test.go
Logic of defaulting activity timeouts. After this change only one of ScheduleToClose or StartToClose is required. If only ScheduleToClose is specified then both ScheduleToStart and StartToClose are defaulted to ScheduleToClose. If only StartToClose is specified then both ScheduleToStart and ScheduleToClose default to the workflow execution timeout.
**Why?**
In the majority of the practical situations ScheduleToStart for an activity should be as large as the maximum time of all possible activity worker outages. But most of the developer new to the workflows choose this value much lower than necessary. Making it optional and defaulting to the workflow timeout will eliminate the large class of production issues.
One less timeout to specify also improves the onboarding …
> Changed activity ScheduleToStart to optional

- service/frontend/workflowHandler.go
- service/frontend/workflowHandler_test.go
Removed outdated check for workflowExecutionTimeout
**Why?**
The workflowExecutionTimeout is already optional by history engine. So I removed excessive check in the frontend.
Unit tested
Invalid execution timeout is configured
> Removed invalid check on frontend handler

- docker/docker-compose-cockroach.yml
Added example using CockroachDB.
**Why?**
CockroachDB is PostgreSQL compliant but uses Raft under the hood, which makes for -very- easy clustering. Besides it's written in Go, so static binary.
This allows cadence to boot *much* faster compared to cassandra.
```go
version: '3.7'
networks:
backend:
name: backend
internal: true
frontend:
name: frontend
internal: false
services:
db:
hostname: db
image: cockroachdb:20.1
container_name: db
tty: false
restart: "on-failure:5"
security_opt:
- "no-new-privileges"
read_only: true
cap_drop:
- ALL
networks:
- backend
command: ["start", "--insecure"]
cadencedb:
hostname: cadencedb
image: cockroachdb:20.1
container_name: cadencedb
tty: false
restart: "on-failure:5"
security_opt:
- "no-new-privileges" …
```
> feat(docker): add cockroach example

- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/dataInterfaces.go
- common/persistence/persistence-tests/matchingPersistenceTest.go
- common/persistence/sql/sqlTaskManager.go
- proto/persistenceblobs/server_message.proto
- service/matching/db.go
- service/matching/taskListManager.go
Replacing the type of "Task List Kind" from `int32` to a protobuff enum, `TaskListKind`:
https://github.com/temporalio/temporal-proto/blob/8a95bbac3a1febf23d2e7f43954fa525ca300864/tasklist/enum.proto#L29-L32
**Why?**
This is part of the effort to make the code cleaner and more maintainable, via removing redundant types, and by using stronger typing. 
I build the code and ran unit tests.
There should be no externally-visible functionality change as a result of this change, this change is purely a code refactoring. If any of the existing functionality breaks, we should be able to fix or back out.
> Change the type of "Task List Kind" from int32 to a protobuff enum, TaskListKind

- common/rpc/context.go
- tools/cli/util.go
- tools/cli/workflowCommands.go
CLI `workflow run` command will now run and listen to history events as long as the workflow is executing
**Why?**
So that I can keep watching the execution progress and not experience random watch termination
Ran two options:
- to verify that watching works after 2 minutes `workflow run --tasklist TestTaskList --workflow_type TestWorkflow_test --execution_timeout 10000 --input '{}'`
- to verify that i can see the completion of workflow  `workflow run --tasklist TestTaskList --workflow_type TestWorkflow_test --execution_timeout 10 --input '{}'` and wait for 11 seconds to see output
No/low risk as the changes are local to workflow run command only
> Fix cli watching history times out after 2 minutes

- common/rpc/encryption/localStoreCertProvider.go
- common/rpc/encryption/localStoreTlsFactory.go
- common/rpc/encryption/tlsFactory.go
- common/rpc/rpc.go
The RootTLS config object is always created by our config loader as its not a pointer, I was passing this object as a pointer down to the tls/certProviders which check the pointer to determine if TLS has been enabled; since this is never nil, these providers would then try to load nil paths. 
Rather than doing this, I need to check the individual paths inside each call to the tls/certProvider and return nil when an individual setting is not specified. 
**Why?**
Because I can't start the server!
Ran server locally with no tls config, passed unit tests. 
No additional risks that TLS PR did not already introduce.
> Handle nil TLS options

- service/history/handler.go
fixes #379 
Remove validation for ShardID being 0
**Why?**
Every Shard sends a SyncShard message and 0 is a valid shard id.  So this validation is now broken.
Unit and integration tests
No risks
> Remove validation for ShardID being 0 as it is valid

- .vscode/launch.json
- common/persistence/dataInterfaces.go
- service/history/replicatorQueueProcessor.go
When reading messages from replication task processor we would wrap it
into ReplicationTaskInfoWrapper object.  Instead of creating a object reference 
we would pass it by value resulting in type cast to `*persistence.ReplicationTaskInfoWrapper`
fail.  This causes replication queue processor to get stuck.
**Why?**
Replication queue processing for history events is broken.
Manually run active/standby setup and confirm history events are getting replicated.
This impacts CrossDC path for replication queue processing.
> Fix replication task processor when converting to replication task

- service/frontend/service.go
- service/history/service.go
- service/matching/service.go
`server.GracefulStop()` was replaced with `server.Stop()`.
**Why?**
I did some investigations and found that there are 3 open connections (at least to frontend) at the moment we call `GracefulStop()`. It makes server to wait for these connections to be closed. I found one connection and was able to close it but it is very hard to track where the other two are coming from. Refactoring is required to shrink number of connection to 1 and properly close it before stopping the server. As long as we call `service.Stop()` only from integration tests (which also need to be refactored) it is safe to replace `GracefulStop()` with `Stop()` and decrease tests shutdown time. I don't want to invest time in proper fix because a lot of things need to be refactored and simplified first. …
> Use Stop instead of GracefulStop

- common/persistence/persistenceInterface.go
- proto/persistenceblobs/server_message.proto
Switching the type of `ChildExecutionInfo.parentClosePolicy` to an (already existing) `enum`, and removing the no-longer-needed cast.
**Why?**
This is part of our general effort to simplify and clean up the code.
Build, run unit tests.
This is just code cleanup; this change should have no effect on the behavior. If something breaks, will fix or revert.
> Switch parentClosePolicy from int32 to an enum

- tools/cli/admin.go
- tools/cli/defs.go
- tools/cli/flags.go
- tools/cli/persistenceUtil.go
Created an util that allows to easily initialize persistence managers 
**Why?**
Speeds up the development of CLI admin commands by providing a single method to get access to persistence
Ran commands using the new method and ran unit tests
No risks
> Create CLI persistence helper

- common/namespace/transmissionTaskHandler.go
- common/namespace/transmissionTaskHandler_test.go
- common/persistence/dataInterfaces.go
Minor code cleanup: removing unnecessary / virtually unused `convertNamespaceStatusToProto ` and the unnecessary definitions that go along with it.
**Why?**
The code is unused, just cleaning things up, as part of the general int/enum clean up effort.
Built and ran unit tests. 
This is purely a (minor) refactoring, no behavior changes are expected. If anything breaks, will fix or revert.
> Removing unused namespacestatus type conversions

- common/membership/rpMonitor.go
- common/primitives/role.go
- tools/cli/admin.go
- tools/cli/adminCommands.go
- tools/cli/app.go
- tools/cli/flags.go
Created an admin CLI command that allows to list Cluster Memberships. Optionally allows to filter based on role and last heartbeat
**Why?**
Allows to discover and get information on cluster memberships
Ran with and without options "--role", "frontend", "--heartbeated_within", "15m"
Minimal risk. Adds new path to mapping between service names to service type enum: add "all" as a primitive to reference all services
> Create CLI command to list Cluster Memberships

- Dockerfile
Removing what appears to be an unused package dependency (`bzr`) from `Dockerfile`. 
**Why?**
Our cicd builds started breaking, with the following error: 
```
...
Step 3/60 : FROM golang:1.14-alpine AS builder
...
Step 4/60 : RUN apk add --update --no-cache ca-certificates make curl git mercurial bzr protobuf
---> Running in 8b21fbae2528
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
bzr (missing):
required by: world[bzr]
The command '/bin/sh -c apk add --update --no-cache ca-certificates make curl git mercurial bzr protobuf' returned a non-zero code: 1
```
It appears that `golang:1.14-alpine` switched to alpine 3.12 …
> Remove unused breaking dependency (bzr) from Dockerfile

- tools/cli/admin.go
Changed the names of admin CLI commands to be consistent between each other
**Why?**
Was confusing having commands in completely different naming patterns
ran commands
Changes the API of Admin CLI - requires checking the new names. No other risks
> Add consistency to admin cli command names

- tools/cli/admin.go
- tools/cli/adminCommands.go
- tools/cli/flags.go
Created an admin CLI command that allows to list various Tasks based on shard_id and task_type. Supported types: Transfer, Timer and Replication tasks. For Timer tasks, also allows to filter based on min and max visibility timestamps
**Why?**
Allows to discover Transfer, Timer and Replications tasks
Ran all three new commands with various options
No risks
> Create CLI command to list Timer, Transfer, Replication tasks

- tools/cli/admin.go
- tools/cli/adminTaskListCommands.go
- tools/cli/flags.go
- tools/cli/persistenceUtil.go
Created an admin CLI command that allows to list Tasks from a TaskList
**Why?**
Allows to discover Tasks of Tasklists
Ran the command manually and tests
No risks
> Create CLI command to list Tasks from Tasklist

- tools/cli/admin.go
- tools/cli/adminCommands.go
- tools/cli/persistenceUtil.go
- tools/cli/util.go
Added a CLI util that allows to control the printing of items: interactive printing, printing everything at once, starting from a given page token. Can be extended to also control printing as table/json
**Why**
Helps to avoid repetition of the same `list` commands specific code. Makes it easier to support the code since it can be shared by all of the list commands 
Ran the commands and tests
No risks
> Create CLI util for list commands

- tools/cli/admin.go
- tools/cli/adminCommands.go
Changed the type of task_type option from int to string
**Why?**
Makes CLI experience friendlier by allowing users to type task type name (replication, transfer, timer) instead of obscure integers (0,1,3)
Ran tests and commands
Incompatible change, old task CLI commands will stop working and require to change to string values
> Change CLI task_type option to string value from int

- Makefile
`find -printf` was replaced with `make` build-functions.
**Why?**
Alpine Linux doesn't support `find -printf`.
Run build.
No risks.
> Fix find usage

- common/persistence/sql/sqlplugin/postgres/plugin.go
Instead of using a hardcoded format string, compose postres connection string dynamically, based on which parameters were actually supplied.
**Why?**
This fixes issue https://github.com/temporalio/temporal/issues/460. Using a hardcoded format string resulted in connection strings that were incorrect (causing the behavior described in the issue).
This change makes it so the connection string is composed only using non-empty elements.
I used docker/docker-compose-postgres.yml to test this to bring up the server, `docker-compose -f docker-compose-postgres.yml  up`.
Before the fix, starting the server with an empty value for `POSTGRES_PWD` caused the server trying to connect to 127.0.0.1.
After the fix,  an empty value of `POSTGRES_PWD` does not …
> Allow for empty postgres db password

- tools/cli/adminCommands.go
- tools/cli/util.go
Added Table view to CLI list util in addition to JSON view.  Use --print_json to switch between them. Default is Table view.
**Why?**
Allows to switch between table and json view for CLI list commands.
Ran tests and a list command that utilizes the new util. Example:
`./tctl admin shard list_tasks --shard_id 3 --task_type 3 --pagesize 4 --more --print_json --username <db_flags>`
Smaller risk of not properly handling a field of a row since the table view constructs the table dynamically using reflection
> Add table-view support for CLI list commands

- tools/cli/adminCommands.go
- tools/cli/adminTaskListCommands.go
- tools/cli/app_test.go
- tools/cli/util.go
- tools/cli/util_test.go
- tools/cli/workflowCommands.go
Added util to map user CLI input to concrete enums. Replaced integer options to actual enum names.
**Why?**
In CLI, users can now type human friendly options instead of obscure integers. Example:
before:
`-- workflowidreusepolicy 1`
after:
`--workflowidreusepolicy AllowDuplicateFailedOnly` (case-insensitive)
If typed incorrectly, CLI will print out possible candidates.
Ran tests and commands.
Low risk. Main inconvenience for some users will be having to re-learn the usage of affected CLI options.
> Replace CLI options to accept enum names instead of integers

- tools/cli/app_test.go
- tools/cli/flags.go
Fixed the type of the FlagWorkflowIDReusePolicy op
**Why?**
The input from users would not be accepted if ReusePolicy is specified
Ran tests and command
Low risk: the flag affects two commands: workflow start and run. Other than these commands nothing else is affected. Both of these commands properly process ReusePolicy with the current fix
> Fix cli reuse policy flag type

- service/history/historyEngine.go
`updateEntityNotExistsErrorOnPassiveCluster` generated panic on active cluster (=always). This func is called (at least) every time when `tctl` is called with some non-existing object (`workflow_id`, `run_id`, `namespace`, etc.) and instead of proper "Not found" error it shows "context cancelled" error.
**Why?**
Fix bug.
Run `tctl` commands manually.
No risks.
> Fix type assertion panic

- service/frontend/errors.go
- service/frontend/workflowHandler.go
- service/history/retry.go
- service/history/retry_test.go
`getCauseFailure` stops at first `ApplicationFailureInfo`.
Closes https://github.com/temporalio/temporal-go-sdk/issues/175.
**Why?**
Non-retryable behaviour doesn't work correctly if non-retryable error has retryable error as a cause.
Added bunch of unit tests to cover all possible cases.
No risks.
> Fix retry for wrapped failures

- common/persistence/cassandra/cassandraClusterMetadata.go
- common/persistence/cassandra/cassandraMetadataPersistenceV2.go
- go.mod
- go.sum
Upgrade gocql to latest release
**Why?**
Fixes #140 
We had to pin gocql to very old bits due to failures in running persistence unit test on upgrade.
I chased these failures were caused by [this](https://github.com/gocql/gocql/commit/f596bd36e19ecaa7a9be478cf137fedc75036b02) change in gocql.  The behavior changed where byte arrays are no longer copied before returning back to the caller.  If a buffer is passed in to read byte buffer from database then gocql will write the value in the preallocated buffer instead of allocating a new buffer for each value.  This requires a change in the caller pattern when they are passing in slices as if multiple values are read in the same buffer then it would cause the previous value to be overwritten resulting in corruption of …
> upgrade gocql to latest release

- README.md
Replacing the `Join Slack` badge with a badge linking to Discourse.
**Why?**
Due to the announcement that Discourse is now the official support forum.
Manual verification of hyperlink.
None.
> Replace Slack with Discourse info

- docker/docker-compose-cockroach.yml
- docker/docker-compose-es.yml
- docker/docker-compose-mysql.yml
- docker/docker-compose-postgres.yml
- docker/docker-compose.yml
docker-compose updates:
* remove statsd,
* add admin-tools,
* make it easy to specify the docker image tag for server and web images,
* switch from `temporalio/auto-setup` to `temporalio/server` + `AUTO_SETUP=True`,
* minor cleanup.
**Why?**
This is the fix for https://github.com/temporalio/temporal/issues/319 + making things a little cleaner / easier to use.
I ran each of the docker-compose files (`docker-compose -f docker-compose.yml up`), together with benchtest, ran a test workflow and made sure the workflow completed. Then I used web to check the UI. 
The behavior was unchanged before and after these changes.
(However, I noticed that cockroachdb docker-compose didn't work -- the service would fail to start. In all of the other docker-compose …
> Remove statsd from / add admin-tools to docker-compose files

- tools/cli/workflowCommands.go
Use `payloads.ToString` to print payload content.
**Why?**
CLI output is broken if payload is not of type `string`.
Run tests.
No risks.
> Fix printing Query CLI command results

- config/dynamicconfig/development_es.yaml
- docker/dependencies/docker-compose.yml
- go.mod
- go.sum
- schema/elasticsearch/visibility/index_template.json
Update index key definition for Elastic Search in development_es.yaml to reflect the recent renaming from 
`Status` to `ExecutionStatus`.
**Why?**
Recently we did massive renaming of ElasticSearch indexes.  As part of this renaming `Status` index
created by the system to represent status of closed workflow execution was renamed to
`ExecutionStatus`.  Default in the code is updated to represent this change but dynamic config
override used by local development with ES support was not updated.  This resulted in indexes to
go out of sync in all places which relies on development_es.yaml dynamic config file.  This broke
local development setup and anyone using docker-compose_es.yaml.  
Locally run Temporal server using dynamic config overrides in …
> Fix elastic search index name for ExecutionStatus

- service/history/historyBuilder.go
- service/history/historyEngine_test.go
- service/history/mutableState.go
- service/history/mutableStateBuilder.go
- service/history/mutableStateBuilder_test.go
- service/history/mutableState_mock.go
- service/history/stateBuilder.go
- service/history/stateBuilder_test.go
- service/history/workflowTaskHandler.go
- tools/cli/util.go
RequestCancelActivityTaskFailed was already removed in PR #355, so
this PR removes the unused EVENT_TYPE_REQUEST_CANCEL_ACTIVITY_TASK_FAILED
enum.
Removing all logic which results in CancelTimerFailed event in the
history when TimerCancel decision is made and instead fail the
entire decision.
**Why?**
Whenever workflow worker makes a cancel decision, requestCancelActivity
in the case of an activity and cancelTimer in the case of timer we
no longer fail the individual decision if we cannot find the activity
or timer to cancel.  This means sdk code has a bug which resulted in
client code to be able to make cancellation decision in the first
place.  We should be failing the entire decision like we do in all
other places.
Unit and Integration Tests …
> Remove cancel failed events for activity and timer

- docker/start.sh
This is a change for https://github.com/temporalio/temporal/issues/562. With this change, temporal container can be configuring to use a scheme other than http (such as https;) to connect to elastic search.
This change goes along with https://github.com/temporalio/helm-charts/pull/49
**Why?**
A customer reported that this is the behavior they would expect, but that was not the actual behavior.
I built the docker image and deployed it to a k8s cluster, using temporal helm chart (https://github.com/temporalio/helm-charts/pull/49), passing in "ES_SCHEME: https" env var. I made sure the env var took effect (I didn't have an ES listening on HTTPS port so the connection failed to esablish, as expected). 
```
◉ 22:44:48 [markmark …
```
> Allow for es scheme (https, http) to be configurable via container's env var

- service/matching/matchingEngine.go
We were appending to a pre-allocated array instead of updating the elements in-line. This results in nil elements in the array which caused a nil reference exception in the protobuf layer that crashed the matching service.
We have no unit tests for this. Will open an item to add unit tests. In the interim, this fixes the panic and was verified on a developer environment
> Fixes panic when ListTaskQueuePartitions is invoked

- common/persistence/sql/sqlplugin/mysql/admin.go
- common/persistence/sql/sqlplugin/postgres/admin.go
- Add `version_partition` column to MySQL/Postgres `schema_version` and `schema_update_history` tables.
- Convert MySQL `REPLACE INTO` usage to `INSERT ON DUPLICATE KEY UPDATE` for the `writeSchemaVersionQuery`.
**Why?**
We will need to change schema creation behavior in the future to support Vitess as we cannot perform schema structure CRUD operations over the mysql interface. However this ensures we have the correct key structure for the future. 
Existing CLI Schema Update Unit Tests
> Create SchemaVersion Tables with Partition Column

- common/persistence/sql/sqlplugin/mysql/cluster_metadata.go
- common/persistence/sql/sqlplugin/mysql/execution_maps.go
- common/persistence/sql/sqlplugin/mysql/task.go
- common/persistence/sql/sqlplugin/mysql/visibility.go
Converted all REPLACE INTO usages with INSERT ON DUPLICATE KEY UPDATE semantics.
Docs - https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html
**Why?**
Vitess does not support REPLACE INTO with fully sharded setups as REPLACE INTO deletes and reinserts the new row, which could possibly be in another shard depending on the VIndex. INSERT ON DUPLICATE KEY UPDATE forces you to specify which columns are being updated (cannot be VIndex column) and modifies the existing row.
Existing Unit Tests, Buildkite, Manual BenchTest on EKS cluster.
Update behavior change of REPLACE vs INSERT could bring in subtle changes in behavior, but this should not be a major issue. 
**Todo**
This needs to be validated for Postgres, but as …
> Convert REPLACE INTO ->  INSERT ON DUPLICATE KEY UPDATE (MySQL)

- tools/cli/flags.go
- tools/cli/util.go
- tools/cli/workflowCommands.go
Fixes #502 
Added support for multiple input payloads
`tctl workflow start --tq helloWorldGroup --wt main.WorkflowWithInputs --et 60 -i '{"Joker":"Heheheh", "Harley":"Pumpkin!"}' -i '"to infinity and beyond"' -i 'null'`
**Why?**
Before you could specify only one payload as `--input`
Ran the command. Ran tests
Low risk. The code shares some logic with --memo flag
> Support multiple input options in cli

- service/worker/parentclosepolicy/workflow.go
The system workflow, when trying to terminate a child workflow, passes in a nil context, which causes a nil reference exception deeper into the service. We have the activity context available, so we will pass that instead.
Verified that child workflows were all terminated once this was fixed. Need to understand WHY nil was passed in. Also need to see if I can add a unit test.
Looks like this PR caused the issue: https://github.com/temporalio/temporal/pull/176/files. It refactored the init-if-nil logic out of the history client, but the parentclosepolicy workflow as not updated. The lack of test coverage caused this to get missed
> Fixes nil reference exception when trying to cascade terminates to children

- common/service/dynamicconfig/constants.go
- service/worker/service.go
`EnableNewKafkaClient` knob was not used at all and updated `IndexerConcurrency`value to 100 instead of 1000.
> Clean up unused feature flags

- common/util.go
- common/util_test.go
- service/history/commandChecker.go
- service/history/commandChecker_test.go
Existing behavior: If the retryPolicy struct on ScheduleActivity is nil, override with the default. Otherwise, take 100% of the retry Policy.
Desired behavior: For each field on the retryPolicy, if the individual value is not-set ('0'), then override with the default.
Testing: Extensive unit test coverage
> Adds override for individual fields on activity retry policy 

- common/defaultActivityRetrySettings.go
- common/util.go
- common/util_test.go
- config/dynamicconfig/development.yaml
- service/history/commandChecker.go
- service/history/commandChecker_test.go
- service/history/retry.go
- service/history/retry_test.go
Fixes situation where user sets an initial retry interval that is greater than 100 seconds, but doesn't explicitly set the maximum retry interval, which will lead to a validation failure when they try to start an activity.
> Sets default activity maximum retry interval to be 100x minimum retry interval

- common/defaultActivityRetrySettings.go
- common/util.go
- common/util_test.go
- service/history/commandChecker.go
- service/history/retry.go
Recent change to allow per-field defaults for activity types neglected to copy over the non-retryable error types to the final copy of the activity retry policy info. The following changes were made:
1) Added a test to verify this field.
2) Changed the code to modify the original policy rather than operating on a copy so that any new fields added in the future are not accidentally missed.
> Fixes issue where NonRetryableErrorTypes was getting dropped during activity info validation

- common/cache/namespaceCache.go
- common/resource/resourceImpl.go
Noisy integration tests errors are disappeared.
Run tests.
No risks.
> Fix refresh namespace cache errors

- Dockerfile
- config/development.yaml
- config/development_active.yaml
- config/development_archival.yaml
- config/development_es.yaml
- config/development_mysql.yaml
- config/development_other.yaml
- config/development_postgres.yaml
- config/development_prometheus.yaml
- config/development_standby.yaml
Make sample yaml point at frontend on correct port. Current configuration will make worker fail.
> Fix development_*.yml PublicClient/ClusterRpcAddress Ports

- common/persistence/sql/sqlplugin/mysql/execution_maps.go
- common/persistence/sql/sqlplugin/mysql/visibility.go
`INSERT IGNORE` has many sharp edges and does more than just ignore Duplicate Key Conflicts. It also swallows errors such as partitioning allocation and divide by zero errors and we should aim to not use this anywhere. See more here: https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#ignore-strict-comparison 
Unfortunately MySQL does not have `ON DUPLICATE KEY DO NOTHING`, so instead we should use the `ON DUPLICATE KEY UPDATE` syntax and update something that is ideally part of the duplicate key conflict (in essence a no-op). However, that update should not be on the sharding key that we would want to use with Vitess, as this will cause issues with Vitess query validation. 
After this change there is only one more location to change - ImmutableClusterMetadata, but cannot be changed in …
> MySQL Execution - Replace Insert Ignore Usage

- common/persistence/dataInterfaces.go
- common/persistence/historyStore.go
- service/history/workflowResetor.go
This PR addresses #585 allowing resets on workflows with corrupted history given that reset point is located before the place where history corruption has occurred. If corruption occurs after the reset point then all valid batches will be carried out to the next workflow.
Reset behavior for workflows with normal history should remain unchanged.
> Allow reset for workflow with corrupted history when possible

- environment/env.go
- tools/cassandra/cqlclient.go
- tools/cassandra/cqlclient_test.go
- tools/cassandra/handler.go
- tools/cassandra/main.go
- tools/cassandra/version_test.go
`environment.GetCassandraPort()` is used instead of `defaultCassandraPort` in tests.
**Why?**
To be able to configure to run tests against cassandra on different port.
Run tests.
No risks.
> Use environment.GetCassandraPort() instead of defaultCassandraPort in tests

- Makefile
If unit tests or integration tests are failing with `make unit-test` or `make integration-test` commands, `make` returns non-zero exit code now.
**Why?**
There was a bug due to `| tee` redirection.
Run tests with failing and non failing scenarious.
No risks.
> Exit with error code when tests are failing

- tools/cli/workflowCommands.go
Fix error message for the reset, which was providing wrong argument names as well as didn't print valid options for the reset_type parameter.
> Fix error message for the reset

- docker/config_template.yaml
Support configurable public client dnsName:port in the docker `config_template.yaml` using envVar `PUBLIC_FRONTEND_ADDRESS`
Without this, config_template.yaml consumers are forced to run an instance of worker on every node.
> Support configurable PublicClient in docker config_template.yaml

- service/history/workflowResetor.go
- service/history/workflowResetor_test.go
- tools/cli/defs.go
- tools/cli/workflowCommands.go
This PR addressed an issue described in #494 allowing users to reset workflows without completed tasks.
In case if there is no completed task reset would use next event after workflow task scheduled event as a reset point.
It allows us to perform a reset on workflows that were unable to make any progress due to worker related issues.
Note that due to change in semantics two CLI parameters responsible for reset types were renamed:
- LastWorkflowTaskCompleted was renamed to LastWorkflowTask
- FirstWorkflowTaskCompleted was renamed to FirstWorkflowTask
> Reset for workflows without completed tasks

- Dockerfile
- docker/docker-compose-cockroach.yml
- docker/docker-compose-es.yml
- docker/docker-compose-mysql-es.yml
- docker/docker-compose-mysql.yml
- docker/docker-compose-postgres.yml
- docker/docker-compose.yml
This PR introduces a mounted folder with the dynamic config, which is used in the docker-compose startup process.
`DYNAMIC_CONFIG_FILE_PATH` points to the new location of dynamic config on the filesystem.
In case if user changes dynamic config on their machine, changes will also be reflected in the docker container automatically after the next refresh interval.
> Allow dynamic config editting outside of container when running docker-compose

- Dockerfile
Adding jq to admin tools docker image.
**Why?**
"tctl produces a lot of json. having jq there might be helpful for everybody"
- Alex.
;)
(also useful in our test pipelines)
Build the docker image and verified that it now has jq, the tool for processing json data.
```
$ make docker-images
...
$ docker run -it temporalio/admin-tools:markmark-local
...
$ docker exec -it youthful_bhabha ash
/usr/local/bin # jq
jq - commandline JSON processor [version master-v20191114-85-g260888d269]
Usage:	jq [options] <jq filter> [file...]
```
Not sure what could go wrong here, but we can always revert.
> Add jq to admin-tools image

- tools/cli/util.go
`tctl` won't trim `Failure` field in output.
**Why?**
In case of error/failure `Failure` field has important information and trim might trim it.
Run `tctl`.
No risks.
> Disable trimming of Failure field

- common/archiver/interface.go
The archiver interface methods are referenced in documentation about how to create a custom archiver. Currently, the interface code is copied into the documentation where comments are added to describe the methods usage. This PR moves those comments to be inline with the code. Now we can reference the interfaces as the source of truth.
Comments are added to archiver interface methods.
**Why?**
To create a source of truth for the information regarding the interface methods.
No testing needed, comments only.
None
> Archiver interface method comments

- service/worker/parentclosepolicy/workflow.go
- tools/cli/util.go
The ParentClosePolicy Workflow was passing in the first run ID of a child workflow getting executed. This is problematic because if the child workflow is continued as new, the termination attempt will fail as that particular instance of the child execution is already completed.
This change was made because a Workflow with a lot of Child Workflows (more than the ParentClosePolicyThreshold setting) will not successfully terminate (or cancel) any Workflows that are continued as new.
Tested locally via the bench test.
STILL TODO: Investigating if we can add an integration test to exercise the ParentClosePolicy Workflow.
Low-risk as the intent of terminating a workflow *is* to cascade to its children for ParentClosePolicy = Terminate
> Fixes bug where terminating a parent with a lot of child workflows that continue-as-new doesn't propagate terminate to children

- tools/cassandra/cqlclient.go
Don't fail if cassandra tables already exist. This allows us to retry and roll forward in case of mid-stream failures during installations.
**Why?**
Our test pipelines occasionally experienced failures, especially as we started testing with larger, replicated cassandra cluster 
I built a docker image with this change and used it to deploy to kubernetes cluster a few times.
If this doesn't work for some reason, we can rollback or fix.
> Don't fail if schema_version and schema_update_history tables already exist

- tools/cli/README.md
Old stale link was updated to the new location of the documentation
**Why?**
Documentation clarity
Checked archived version of the old link URL to verify the content was the same just hosted at a new location.
n/a
> Updated stale link

- common/persistence/executionStore.go
BufferedEvents should not be written to when there is no data to persist. 
There is an additional vulnerability on the read-path side where an empty row can cause a nil pointer exception in statsComputer.go -- Read path will discard these and log in a follow-up PR.
> Skip BufferedEvents persistence when empty

- docker/config_template.yaml
- Expose SQL Connection Options in docker template
- Note MySQL did not have any values set here previously
**Why?**
Should be user configurable.
No testing, looking at buildkite and pipeline stabilization.
Connection starvation
> Expose SQL Connection Options in docker template

- service/history/historyBuilder.go
We are not persisting the failure details on an incoming RecordLocalMarkerCommand. As a result on replay, if we have recorded a local activity failure, the SDK will panic since the expected failure field is missing.
> Fixes bug where we were not persisting the failure details for a marker recorded event, which corrupts workflow on replay 

- .vscode/launch.json
- common/persistence/sql/sqlExecutionManager.go
- common/persistence/sql/sqlHistoryManager.go
- common/persistence/sql/sqlplugin/mysql/events.go
- host/resetworkflow_test.go
After 2dc removal we trigger a slightly different codepath on mysql
persistence when resetting workflows.
AppendHistoryNodes when called with IsNewBranch add both
history_tree metadata and history_node.  This caused the problem
because history_node is already added when fork was called so
adding it again failed with duplicate error.  Updated
AppendHistoryNodes api to upsert instead.
Another issue was with create workflow execution never expected
to be called with `CreateWorkflowModeContinueAsNew` mode.  With
NDC now workflow reset is implemented in similar fashion as
doing continue as new.  So removed the check to disallow
`CreateWorkflowModeContinueAsNew` on create execution and added
appropriate validation.
> Fixes MySQL persistence for workflow reset

- service/history/handler.go
This PR fixes a bug where simultaneous SignalWithStart requests for the same WorkflowID randomly results in one of them failing with a "Workflow Execution Already Started Error." This error does not make sense given that SignalWithStart is supposed to seamlessly handle both the case where the WF is already running and the case where it needs to be created.
Our throughput stress scenario easily reproduces this issue in the one box environment. The issue stopped reproducing once this change was integrated.
This is a relatively low-risk change. We only retry under certain error conditions that we expect to be transient, and in the worst case, we keep retrying until the request times out.
> Fixes Internal Server Error returned on simultaneous SignalWithStart requests for the same WF ID

- common/rpc/grpc.go
gRPC MaxDelay was decreased to 10 seconds from default 120 seconds.
**Why?**
When failed connection is restored client (another service) needs to know about it faster than 2 minutes.
Run samples and will test under failures.
No risks.
> Set Backoff.MaxDelay to 10 seconds.

- common/persistence/cassandra/cassandraVisibilityPersistence.go
- common/persistence/persistence-tests/visibilityPersistenceTest.go
- common/persistence/sql/sqlVisibilityStore.go
The current implementations of UpsertWorkflowExecution on the Cassandra/SQL visibility persistence stores return a Service Error since Query Operations are not supported for those stores.
The problem is that we do allow customers to invoke UpsertWorkflowExecution successfully even if Elastic Search isn't enabled. This results in our Transfer Task Queues getting clogged because it keeps retrying a persistence operation that will always fail.
The fix is to just have all attempts to UpsertWorkflowExecution on Cassandra/SQL to function as a no-op so that it does not "fail" the transfer task perpetually. We will still fail with explicit errors on List/Scan/Count, so the user should be able to easily tell that their application logic is broken if it does depend on Elastic Search.
The change was …
> Fixes blockage of Transfer Queue if UpsertSearchAttributes is invoked on a Temporal Server w/o Elastic Search

- common/constants.go
In this PR, we are reducing the Maximum Page Size when retrieving Workflow History Records from the Persistence Layer from 1000 to 100.
We are doing this, because by adding gRPC support, there is a maximum message size of 4 MB when talking to Temporal Clients. With a page size of 1000, we are seeing paginations which are 7-8MB. Once a pagination gets this big, the workflow is not processable unless the Client gRPC limit is increased or the page size limit is decreased. 
Verifying via unit / integration tests. Will do extra validation with our nightly stress test runs (which initially caught this issue). We also have a separate issue open to do more intelligent paging so that we can still have a page size of 1000, but cut off the pagination if it exceeds the RPC size limit.
The downside / …
> Reduce Maximum Page Size when retrieving Workflow Execution History

- service/history/shardContext.go
When we merged Cadence into Temporal, we pulled in this change (https://github.com/uber/cadence/pull/3136), but not the subsequent fix for the regression it introduced (https://github.com/uber/cadence/pull/3405).
Temporal Frontend servers rely on ShardOwnershipLost to know to "retry" in the event a Shard has moved. The first Cadence change was masks ShardOwnershipLost with MaxRetriesExceeded, which the Temporal Frontend would not retry and simply pass back to the client. The net result is that during cluster startup / upgrades, the perceived reliability of the Create Workflow operation would be substantially reduced because our standard shard-movement-retry-logic in the FrontEnd was being circumvented.
Note that this pattern was introduced for:
1) CreateWorkflowExecution
2) …
> Create Workflowing is unreliable when History Shards have recently moved around the cluster

- tools/cli/factory.go
Annoying message `2020/09/18 17:53:01 INFO  No logger configured for temporal client. Created default one.` was added to every `tctl` output. This PR to fix it.
> Set logger in tctl GoSDK client

- go.mod
- tools/common/schema/setuptask.go
`make install-schema` can be run any number of times w/o harm to the database.
**Why?**
#697 broke idempotency of `make install-schema` and docker image.
Run `make install-schema` many times and ensured that server still can run.
No risks, bug fix.
> Fix install-schema target (and docker image) idempotency

- tools/cli/adminCommands.go
`tctl admin wf delete` command is fixed.
**Why?**
Command was broken due to erros in JSON serialization.
Run command manually.
No risks.
> Fix delete workflow execution admin command

- host/sizelimit_test.go
- host/taskpoller.go
- service/history/commandChecker.go
- service/history/historyEngine.go
- service/history/workflowExecutionContext.go
- service/history/workflowTaskHandler.go
Moved the logic to force terminate workflow execution to
workflowExecutionContext to make sure it is triggered for all cases
when workflow execution exceeds size limit.
Previously we are only performing this check on workflow task
completion.  This could result in scenarios where workflow would
never be forced terminated.
Removed the logic to fail the workflow on command processing as
it is redundant after moving force termination logic to more generic
location.
> Force terminate workflow execution when exceeds system limit

- .gitignore
- Makefile
- buf.yaml
- proto/buf.yaml
Two `Makefile` targets were added. 
The process has two steps:
1. Run `make buf-build` on golden branch first (master) and it will create `proto/image.bin` file. 
2. Switch to the branches with changes, or make those changes to proto files and run `make buf-breaking`. Output should not contains any rows. All errors must be fixed.
**Why?**
These targets allow to detect and recent proto changes are braking or not.
Run targets over various changes.
No risks, build process improvment.
> Add proto breaking change detector

- common/definition/indexedKeys.go
- common/elasticsearch/defs.go
- config/dynamicconfig/development_es.yaml
- host/testdata/es_index_template.json
- schema/elasticsearch/visibility/index_template.json
- service/worker/batcher/workflow.go
- service/worker/service.go
- tools/cli/workflowBatchCommands.go
- The EnableBatcher default value was set to false, which meant that batch commands would be accepted by the server, but never actually processed.
- For Temporal clusters with Elastic Search enabled, but without explicit dynamic configuration, key fields such as CustomNamespace, Operator, KafkaKey and Encoding were not registered as "indexed." This would cause any attempt to start the batch command to fail as the server would think we were performing an elastic search query on an unindexed field
- Adds missing ES index setup for "Encoding" key
- Cleans up a tiny bit of Batcher code/comments based on adhoc code-review
Change was verified through standard unit/integration test pipeline + manual validation of batch commands for starting (cancel, terminate, signal), terminating, describing, …
> Fix default out-of-box experience for tctl batch commands

- service/history/service.go
- service/history/workflowTaskHandler.go
- Reduces Default Maximum History Size Error and Warning thresholds by a factor of 10. As we do further profiling / stabilization of Temporal, these are open to being increased in the future.
- Fixes nil-reference panic that would occur when we attempt to process a request to cancel an activity that has already been completed.
- Validated with Unit and Integration tests
- Minimal risk for the nil-reference panic fix.
- Moderate risk for the History Size reduction if an environment has workflows which already exceed this limit, in which case, the user can just override the settings via dynamic config before deploying
> History activity cancellation fixes

- common/archiver/gcloud/queryParser.go
- common/archiver/gcloud/util.go
- common/archiver/gcloud/util_test.go
- common/archiver/gcloud/visibilityArchiver.go
- common/archiver/gcloud/visibilityArchiver_test.go
- common/archiver/s3store/util.go
- common/archiver/s3store/visibilityArchiver.go
- common/archiver/s3store/visibilityArchiver_test.go
Archival logic uses time as data type instead of unix nano
**Why?**
Temporal made a call to use time datatype everywhere in the code instead of timestamps
unit and integration tests
May cause issues with querying archival records using timestamps
> Use time datatype instead of unix nano representation for archival

- common/failure/failure.go
- host/activity_test.go
- service/history/timerQueueActiveTaskExecutor.go
Activity and Workflow timeout failures now contain message and source information
**Why?**
Such failures by default were showing up empty in web/tctl/any other consumer unless have a special case of processing internal Timeout structure
Ran tests and tried creating a timeout failure and verified through web/tctl
No risks
> Add message to Timeout failures

- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/dataInterfaces.go
- common/persistence/executionStore.go
- common/persistence/persistence-tests/persistenceTestBase.go
- common/persistence/persistenceInterface.go
- common/persistence/sql/sqlExecutionManager.go
- common/persistence/sql/sqlExecutionManagerUtil.go
- service/history/nDCTransactionMgrForExistingWorkflow.go
- service/history/nDCTransactionMgrForExistingWorkflow_test.go
- service/history/workflowExecutionContext.go
- service/history/workflowExecutionContext_mock.go
Removed more logic relevant only for removed 2dc code path.
> removed current workflow CAS from persistence used by 2dc only

- tools/cli/workflowCommands.go
`tctl workflow describe` now properly outputs failure type for timeout
**Why?**
failure type was missing for timeout failures
ran command and tests
no risks
> Add failure type info to tctl wf describe

- CONTRIBUTING.md
Contribution guide.
**Why?**
Unit tests are failing on MacOS without the increased file handle limit.
Unit tests on MacOS succeed after running `ulimit -n 8192`.
None
> Update contribution guide with a note about increasing file handle limit

- CONTRIBUTING.md
Add instructions for developing on Windows to the contribution guide
**Why?**
To be inclusive of the developers that use Windows as their primary platform.
Followed the instructions myself to build and test Temporal on Windows.
None
> Add instructions for developing on Windows to the contribution guide

- CONTRIBUTING.md
- Makefile
- docker/dependencies/docker-compose.mac.sh
- docker/dependencies/docker-compose.mac.yml
- docker/dependencies/docker-compose.yml
Added `docker-compose.yml` overrides for Mac developers. These 2 `make` commands work on Linux and Mac.
```
$ make start-dependencies
$ make stop-dependencies
```
**Why?**
Due to docker implementation on Mac (Linux VM) `web` can't reach server with original Linux configuration. This overrides should fix it.
Wasn't able to test.
No risks.
> Fix developer docker-compose on Mac

- tools/cli/util.go
WorkflowTaskFailed event now renders failure in human readable form (top level failure + stack trace + some of deeper lvl failures) 
**Why?**
Adds visibility into WorkflowTaskFailed data
Tests + ran command
no risks
> Make Task Failed event readable in cli 

- common/persistence/cassandra/cassandraQueue.go
Passes in 3 "nil" references to the ScanCAS() call when inserting cluster membership data.
This change is needed for the gocql client to work against an instance of ScyllaDB.
Change was verified against a ScyllaDB cluster.
This is a low risk change as if it causes issues, it would be caught immediately.
> Enable support for ScyllaDB

- common/persistence/cassandra/cassandraQueue.go
When running against certain Cassandra-compatible implementations (such as ScyllaDB), the ScanCAS call needs to take in as many arguments as there are parameters that are expected to be returned. We had an incorrect number of parameters for another one of our cassandra queue methods. We fix this so that Temporal can work properly.
Tested against a real-life ScyllaDB cluster. Also unit-tests/integration-tests will fail if this breaks anything. This is a low-risk change.
> Adds nil parameter to ScanCAS call()

- common/persistence/sql/sqlExecutionManager.go
- common/persistence/sql/sqlplugin/definition.go
- common/persistence/sql/sqlplugin/history.go
- common/persistence/sql/sqlplugin/history_timer_tasks.go
- common/persistence/sql/sqlplugin/history_transfer_tasks.go
- common/persistence/sql/sqlplugin/mysql/execution.go
- common/persistence/sql/sqlplugin/postgresql/execution.go
- common/persistence/sql/sqlplugin/tests/history_timer_task_test.go
- common/persistence/sql/sqlplugin/tests/history_transfer_task_test.go
Split overloaded transfer / timer task APIs
* Split TransferTasksFilter into TransferTasksFilter and TransferTasksRangeFilter
* Split SelectFromTransferTasks into SelectFromTransferTasks and RangeSelectFromTransferTasks
* Split DeleteFromTransferTasks into DeleteFromTransferTasks and RangeDeleteFromTransferTasks
* Split TimerTasksFilter into TimerTasksFilter and TimerTasksRangeFilter
* Split SelectFromTimerTasks into SelectFromTimerTasks and RangeSelectFromTimerTasks
* Split DeleteFromTimerTasks into DeleteFromTimerTasks and RangeDeleteFromTimerTasks
**Why?**
Run tests.
> Split overloaded transfer / timer task APIs

- docker/config_template.yaml
Fixed casing of TLS CA settings from "CA" as in go code to "Ca" as in the YAML schema.
Also remove server CA from the list of frontend's client CAs because that's extraneous.
**Why?**
The config settings weren't being loaded from config file produced with the config template.
Manually tested that settings get loaded with the right casing.
No risk as those settings weren't being loaded before this fix.
> Fix casing of TLS CA settings in config template

- common/convert/convert.go
- common/persistence/sql/sqlplugin/tests/visibility_test.go
* Use timestamp instead of convert package for time.Time pointer conversion
**Why?**
Remove duplicated functionality
Make bins
N/A
> Use timestamp instead of convert for time.Time pointer conversion

- common/auth/tlsConfigHelper.go
- common/cassandra/cassandraCluster.go
- common/messaging/kafkaClient.go
- common/persistence/sql/sqlplugin/mysql/plugin.go
- common/rpc/encryption/localStoreTlsFactory.go
- tools/cli/factory.go
Set minimum version of the TLS protocol to 1.2.
Consolidated instantiation of `tls.Config` structs to a set of helper function for easier maintenance going forward
**Why?**
To prevent connections over obsolete and insecure versions of the TLS protocol.
Ran Unit tests.
Will rely on BuildKite tests for broader test coverage.
If some of our dependencies don't support TLS 1.2, communication might break.
> Enforce minimum TLS version of 1.2

- cmd/server/main.go
- temporal/server.go
- temporal/server_option.go
- temporal/server_options.go
Added a server option for setting a low level API call authorizer.
**Why?**
In the absence of a more comprehensive AuthZ story, customers need to be able to authorize API calls at the low level as a stop gap solution.
Manually verified that a custom authorizer gets set via the option.
I see no risk as this is an optional feature, and the `nopAuthority` is set today by default.
> Add a server option for setting authorizer

- common/resource/bootstrapParams.go
- temporal/server.go
- temporal/server_option.go
- temporal/server_options.go
Added a server option for overriding default TLS config provider. Depends on #829.
**Why?**
In the absence of a more flexible configuration story, this allows customers to completely override TLS configuration at the low level if needed.
Manually tested that the server option when set is used by the server code. 
I see no risk as this setting is optional and is not set by default.
> Add server option for overriding default TLS config provider

- common/persistence/cassandra/cassandraClusterMetadata.go
- common/persistence/clusterMetadataStore.go
- common/persistence/sql/sqlClusterMetadataManager.go
- common/persistence/sql/sqlplugin/definition.go
- common/persistence/sql/sqlplugin/mysql/cluster_metadata.go
- common/persistence/sql/sqlplugin/postgresql/cluster_metadata.go
- schema/cassandra/temporal/schema.cql
- schema/cassandra/temporal/versioned/v1.1/cluster_metadata.cql
- schema/mysql/v57/temporal/schema.sql
- schema/mysql/v57/temporal/versioned/v1.1/cluster_metadata.sql
- schema/postgresql/v96/temporal/schema.sql
- schema/postgresql/v96/temporal/versioned/v1.1/cluster_metadata.sql
- temporal/server.go
This change adds immutable_data field back to allow older versions of temporal to be able to start on a new version of schema.
When we write metadata we'll write into both `data` and `immutable_data` columns.
When we read, we'll backfill data from the `immutable_data` when `data` is empty.
Special logic is needed to handle conditional updates and versioning for legacy records:
- In cassandra, due to lack of default column values we set `version=1` when legacy record is read.
- In SQL `version` column will be initialized with value 1 by default.
- When server starts up it will try to write a record with version 0 containing new cluster id, which will get recorded once. All subsequent writes will be rejected due to a change in the `cluster_id` field.
Cluster metadata initialization has been …
> Adding dual read/write for immutable metadata

- Dockerfile
- cmd/server/main.go
- docker/start-temporal.sh
- docs/persistence.md
`--services` flag format was fixed in `docker-compose.yml` file. Aslo code to support backwards compatibility was added.
**Why?**
Recently I changed format of the flag in `temporal-server` CLI but forget to fix it in `docker-compose.yml` file.
Run locally.
N/A
> Fix --services flag format

- common/auth/tlsConfigHelper.go
- common/cassandra/cassandraCluster.go
- common/messaging/kafkaClient.go
- common/persistence/sql/sqlplugin/mysql/tls.go
- common/persistence/sql/sqlplugin/postgresql/plugin.go
- common/persistence/sql/sqlplugin/postgresql/tls.go
- common/rpc/encryption/localStoreTlsFactory.go
- tools/cli/factory.go
* Allow set CA or key / cert seperately for PostgreSQL
* Add support of host name verification & fix existing issue
**Why?**
See above
Install schema with CA or CA & key & cert
N/A
> Update PostgreSQL TLS config

- docker/buildkite/docker-compose-local.yml
- docker/buildkite/docker-compose.yml
This PR disables version checking on our buildkite jobs reducing unnecessary requests from these build environments.
> Disable version checking on buildkite

- service/history/shardContext.go
* Chang log level from warn to debug if timer to be created is less than current min timer cursor and postponed
**Why?**
Logging becomes noisy and operator can rely on CPU utilization / load metrics instead of this logging
Make bins
N/A
> Suppress noisy timer related log

- tools/cli/admin.go
- tools/cli/adminClusterCommands.go
Sample output:
```
❯ ./tctl admin cluster metadata
{
"supportedClients": {
"temporal-cli": "\u003c2.0.0",
"temporal-go": "\u003c2.0.0",
"temporal-java": "\u003c2.0.0",
"temporal-server": "\u003c2.0.0"
},
"serverVersion": "1.1.0",
"clusterId": "48477d99-5847-45e1-bdcc-29c565230259",
"versionInfo": {
"current": {
"version": "1.1.0",
"releaseTime": "2020-10-13T01:30:00Z",
"notes": "Temporal v1.1.0"
},
"recommended": {
"version": "1.1.0",
"releaseTime": "2020-10-13T01:30:00Z",
"notes": "Temporal v1.1.0"
},
"lastUpdateTime": "2020-10-15T19:48:03.506578320Z"
},
"clusterName": "active",
"historyShardCount": 4
}
```
> Adding admin command for retrieving cluster metadata

- common/service/config/config.go
- docker/config_template.yaml
1) The current TLS configuration is a bit confusing because it is not obvious internode vs frontend and server vs. client. We add comments to config_template.yaml to clean that up.
2) Previous checkin introduced a bad comment. This fixes that
> Cleans up comments in config / config_template.yaml

- tools/cli/app.go
By default, tctl does not perform host verification on the temporal cluster it is talking to (if using TLS). The underlying code checks a flag, but the flag is not exposed as a Global option. This PR exposes the flag as a global option.
Validated this fix by running against a private environment with a mismatched server-name for the TLS cert. With the flag enabled, tctl gives the appropriate error message when communicating with the private environment.
> Adds support for --tls_enable_host_verification as global option for TCTL

- .gitattributes
Added Large File Storage tracking for .png and .jpg files.
**Why?**
To prevent bloating of git history with accidental committing of graphic files.
Submitted #861 with these settings in place.
No risk.
> Add LFS tracking for .png and .jpg files

- common/rpc/encryption/localStoreTlsFactory.go
- common/service/config/config.go
- docker/config_template.yaml
- tools/cli/admin.go
- tools/cli/factory.go
- tools/cli/workflowCommands.go
- Adds ability to enable host validation to Internode/Frontend TLS configuration.
- Updates config-template.yaml to surface environment variables for both serverName and enabling of host validation.
- TCTL commands that leveraged the Go Client SDK were not setting the TLS configuration correctly on the Client, so those commands would fail against a Temporal Cluster with TLS enabled.
Tested against a private deployment
> Adds additional TLS configuration parameters

- common/persistence/cassandra/cassandraClusterMetadata.go
- common/persistence/sql/sqlClusterMetadataManager.go
Mysql upgrade from 1.0 - 1.1 was causing server startup issues due to the fact that cluster metadata hasn't been backfilled.
Also although not required (as cql client returns nil slice) I made a similar change on the cassandra side just for the symmetry.
> Fix the bug with 1.1 startup on Mysql after the upgrade

- docker/start.sh
For auto-setup, the temporal-cassandra-tool is capable of reading certain values (such as username / password) via Environment Variables. We export those variables before invoking the tool in startup.sh so that a user can set values in Docker-Compose as needed.
> Enables Cassandra auto-setup to specify username, password, port and TLS

- tools/cli/app.go
- tools/cli/factory.go
- tools/cli/flags.go
Added an option for `tctl` to override server name for TLS host verification.
**Why?**
When `tctl` connects to frontend over mTLS, the target server address or host name may differ from the CN in the server certificate, and that fails server host verification. This option allows `tctl` to specify the expected CN of the server it is connecting to.
Manually verified that `tctl` is able to successfully connect to server by specifying `--tls_server_name` option where before it was failing to connect.
No risk. This is an optional flag.
> Add an option to tctl to override server name for TLS host verification

- common/service/dynamicconfig/config/testConfig.yaml
- common/service/dynamicconfig/constants.go
- common/service/dynamicconfig/fileBasedClient_test.go
Our Dynamic Configuration File-based logic was comparing a value that is typically supplied as an integer / string to an enum value, which would never match. As a result, any constraint that specified TaskQueueType would never match, which means that this constraint setting never worked.
This PR fixes this issue by converting the TaskType enum filter into its String equivalent, so the user can specify "Activity" or "Workflow" (case-sensitive)
Not in scope for this PR:
- Allowing multiple ways to specify TaskType (e.g. 1 or 2 instead of "Workflow" or "Activity") - this requires a heavier rewrite of Dynamic Config.
- Assumed defaults for Constrained Values - this also requires a very significant change for dynamic config
Verified this test on a local development environment and via …
> Fixes Dynamic Configuration bug where TaskType Constraint match always failed

- common/service/dynamicconfig/config.go
- common/service/dynamicconfig/config/testConfig.yaml
- common/service/dynamicconfig/fileBasedClient_test.go
We've noticed that a lot of users, when attempting to override TaskQueue partition count, don't realize that they need to explicitly set the taskType and have an entry for both "Workflow" and "Activity." In most cases, users are fine just scaling both simultaneously and don't need to care about the taskType.
We've changed the dynamic configuration so that it will match a constraint if the user chooses to omit taskType as well. It first searches for a constraint with the specific taskType set, and if it cannot find it, will search for a constraint w/o taskType.
Test using both unit tests and the local one box environment.
Users might be incorrectly thinking they have task queue partitioning enabled. After upgrading to this change, they will actually have task queue partitioning enabled. …
> Makes TaskType constraint in dynamic configuration optional when specifying Task Queue Partitions

- docker/config_template.yaml
Enables ability to set gRPC/membership ports via environment variables when launching a Docker container.
**Why?**
To be able to configure ports with environment variables.
Tested using `dockerize` command locally.
N/A
> Adds templatization for gRPC and membership ports exposed by Temporal

- schema/mysql/v57/temporal/versioned/v1.1/cluster_metadata.sql
- schema/postgresql/v96/temporal/versioned/v1.1/cluster_metadata.sql
- tools/common/schema/updatetask.go
* Fix SQL schema 1.1 bug, adding default value if possible
**Why?**
Schema upgrade error out due to missing default value
Manually create schema & start server in 1.0.0 then upgrade schema to 1.2.x and start server for both MySQL and PostgreSQL
N/A
> Bugfix SQL 1.1 schema change

- common/membership/rpMonitor.go
- common/membership/rpServiceResolver.go
**Why?**
Currently, we assume that if the Temporal service's gRPC port is defined in config, then all other services of the same type on the Temporal cluster are also communicating via the same port. This requires that the gRPC port for a given service type be identical across the entire cluster. Unfortunately, this breaks if a user wants to dynamically allocate gRPC ports or host two instances of a Temporal service type on the same IP address.
Rather than deriving other services' gRPC ports based on config, we will have each service write the gRPC port from its config as a ringpop label. Other services can then use this label to determine which port it needs to connect to to communicate with tthat particular service. This enables different instances of the same service type (e.g. …
> Adds support for differing gRPC ports for the same temporal service on a deployed cluster

- common/rpc/grpc.go
`MinConnectTimeout` is set to its former default value of 20 seconds.
**Why?**
Change similar to SDK PR: https://github.com/temporalio/sdk-go/pull/250
Issue is here: https://github.com/temporalio/sdk-go/pull/249
All tests.
No risks, bug fixing.
> Set MinConnectTimeout to 20 seconds

- service/history/mutableState.go
- service/history/mutableStateBuilder.go
- service/history/mutableState_mock.go
- service/history/workflowExecutionContext.go
* Make local namespace workflows also use version history
Solves #703 
**Why?**
Unify code path, less if / else
Run server & canary locally
N/A
> Update local namespace workflows to use version history

- common/service/config/config.go
- config/development.yaml
- config/development_active.yaml
- config/development_archival.yaml
- config/development_es.yaml
- config/development_mysql.yaml
- config/development_other.yaml
- config/development_postgres.yaml
- config/development_prometheus.yaml
- config/development_standby.yaml
- docker/config_template.yaml
- temporal/server.go
New `metrics` section was added to `global` section in `development.yml`. Old `metrics` section in `services` section is still supported but marked as deprecated. Closes #673.
**Why?**
Metrics scope should be created once per server (process), not per service.
Run server locally.
No risks for now but at some point `services.metrics` needs to be removed.
> Add global.metrics section and deprecate service.metrics

- service/history/configs/config.go
For Temporal clusters with a large number of shards, a single go-routine that acquires all the shards causes significant latency when a history node is starting up as it loads the shards one-by-one.
This fix increases the number of goroutines to "10" as that should not cause any issues for existing clusters, but will yield a significant benefit to clusters with a larger number of shards.
Ideally, the number of goroutines should be calculated based on a ratio of the total number of shards to make this slightly more flexible.
> Increases number of go-routines that acquire history shards

- tools/cassandra/cqlclient.go
- tools/cassandra/handler.go
- tools/cassandra/main.go
- tools/common/schema/types.go
Adds a `--datacenter` flag to temporal-cassandra-tool on create that will use NetworkTopologyStrategy for replication with the specified replication factor.
**Why?**
This is highly useful for clusters with topologies more complex than either single node or single node per rack with number of racks equal to replication factor. Any other layout will benefit from this.
Manual test:
```
temporal-cassandra-tool create --keyspace temporal_derek_net_top --rf 3 --datacenter dc1
``` 
Result: 
```
cluster1-superuser@cqlsh> DESC KEYSPACE temporal_derek_net_top 
CREATE KEYSPACE temporal_derek_net_top WITH replication = {'class': 'NetworkTopologyStrategy', 'dc1': '3'}  AND durable_writes = true;
```
None known, but no unit tests added for …
> Enable NetworkTopologyStrategy for cassandra

- README.md
Replacing `tctl` docker with `admin-tools` because it is already part of `docker-compose` we use to run the server and users don't need to download one more image. Also adding note about `--address` flag.
> Change docker tctl to admin-tools

- common/authorization/interceptor.go
Removed the workaround for extracting namespace names from four API calls after `Name` property in their proto objects got renames to `Namespace`.
**Why?**
Code cleanup.
Unit tests.
I don't see any risk here.
> Remove workaround for extracting namespace name from Name property

- cmd/server/main.go
- common/service/config/loader.go
Changed server initialization procedure to load configs before server options are set.
**Why?**
Some server options need to get configuration parameters as part of their initialization. That requires config to be already loaded. Today config gets loaded later, and hence server options cannot use it. 
Unit tests.
I don't see any risk here.
> Preload config before setting server options

- common/authorization/authorizer.go
Removed unused interface.
**Why?**
Interface `requestWithNamespace` was part of the workaround removed in #967.
Buildkite should suffice.
No risk.
> Remove requestWithNamespace interface that is not used anymore

- host/integration_test.go
- service/history/timerQueueActiveTaskExecutor.go
Also pass through LastCompletionResult to next execution when cron workflow times out.
**Why?**
See issue #992 
Added new integration test which tests timeout logic for cron workflow
No risk.
> Pass LastCompletionResult to next run on workflow timeout

- tools/cli/flags.go
- tools/cli/persistenceUtil.go
Added PostgreSQL support to tctl admin commands (newer commands that use persistenceUtil.go). Some older commands don't use this util and don't support PostgreSQL yet. There is a separate task that tracks refactoring of older commands 
**Why?**
Adds tctl admin visibility into temporal setups based on PostgreSQL db
ran `admin namespace list` with PostgreSQL and Cassandra setups
-- testing--
> Add PostgreSQL support to tctl admin commands

- service/frontend/adminHandler.go
- tools/cli/adminCommands.go
* Fix CLI / server admin handler bug
**Why?**
Fix bug
```zsh
./tctl --address 127.0.0.1:7233 admin history_host describe --shard_id 4
./tctl --address 127.0.0.1:7233 admin history_host describe --history_address 127.0.0.1:7234
./tctl --address 127.0.0.1:7233 --namespace canary admin history_host describe --workflow_id ff
```
N/A
> Fix broken DescribeHistoryHost API / CLI

- common/cache/namespaceCache.go
- common/cache/namespaceCache_test.go
- common/persistence/sql/sqlplugin/mysql/events.go
- common/persistence/sql/sqlplugin/postgresql/events.go
- common/persistence/sql/sqlplugin/tests/history_tree_test.go
- service/frontend/service.go
- service/history/service.go
- service/worker/service.go
* Remove forced namespace cache refresh
* Make SQL insert into history tree idempotent
**Why?**
Previously, if a namespace is newly created and not loaded
in cache, the namespace cache can do forced cache refresh reducing
the wait time for caller. This forced cache refreshment may able
to trigger a new callback for failover. Now, if a task with deleted
namespace is processed, namespace cache will trigger the above
cache refreshment and causing a deadlock. The only solution now is
to remove the namespace cache forced refreshment logic.
Run tests
N/A
> Remove forced namespace cache refresh

- common/cache/namespaceCache.go
- common/cache/namespaceCache_test.go
- common/persistence/sql/sqlplugin/mysql/events.go
- common/persistence/sql/sqlplugin/postgresql/events.go
- common/persistence/sql/sqlplugin/tests/history_tree_test.go
* Remove forced namespace cache refresh
* Make SQL insert into history tree idempotent
**Why?**
NOTE: Previously, if a namespace is newly created and not loaded
in cache, the namespace cache can do forced cache refresh reducing
the wait time for caller. This forced cache refreshment may able
to trigger a new callback for failover. Now, if a task with deleted
namespace is processed, namespace cache will trigger the above
cache refreshment and causing a deadlock. The only solution now is
to remove the namespace cache forced refreshment logic.
> Remove forced namespace cache refresh (#1014)

- common/persistence/cassandra/cassandraPersistenceUtil.go
- common/persistence/persistence-tests/executionManagerTest.go
- common/persistence/persistence-tests/persistenceTestBase.go
- common/persistence/sql/sqlExecutionManagerUtil.go
- service/history/historyEngine.go
- service/history/historyEngine_test.go
- service/history/mutableStateBuilder.go
- service/history/mutableState_mock.go
- service/history/nDCConflictResolver.go
- service/history/nDCHistoryReplicator.go
- service/history/nDCStateRebuilder.go
- service/history/nDCStateRebuilder_mock.go
- service/history/nDCStateRebuilder_test.go
- service/history/nDCWorkflowResetter.go
- service/history/nDCWorkflowResetter_mock.go
- service/history/nDCWorkflowResetter_test.go
- service/history/stateBuilder.go
- service/history/workflowResetter.go
* Set workflow start time within business logic (mutable state initialization) instead of within persistence layer
**Why?**
Persistence layer should not initialize variable related to business logic
Run tests
N/A
> Set workflow start time within business logic

- common/archiver/s3store/README.md
WorkflowID query parameter was renamed to WorkflowId in https://github.com/temporalio/temporal/pull/268 
Update the documentation to reflect the change
> Update s3 archiver documentation

- common/namespace/handler.go
- common/namespace/handler_GlobalNamespaceDisabled_test.go
- common/namespace/handler_GlobalNamespaceEnabled_MasterCluster_test.go
- common/namespace/handler_GlobalNamespaceEnabled_NotMasterCluster_test.go
- common/namespace/handler_test.go
- common/namespace/transmissionTaskHandler.go
* Return RegisterNamespaceResponse instead of nil if API call is a success
**Why?**
API should not return nil if call is a success
Run tests
N/A
> Fix namespace registration response

- common/cache/namespaceCache_test.go
- common/cluster/metadata.go
- common/cluster/metadataTest.go
- common/service/config/config.go
- common/service/dynamicconfig/constants.go
- config/development_active.yaml
- config/development_standby.yaml
- host/dynamicconfig.go
- host/testcluster.go
- service/frontend/adminHandler.go
- service/frontend/adminHandler_test.go
- service/frontend/service.go
- service/frontend/workflowHandler.go
- service/history/configs/config.go
- service/history/handler.go
- service/history/historyEngine.go
- service/history/replicationTaskFetcher.go
- service/history/replicationTaskProcessor.go
- service/history/replicatorQueueProcessor.go
- service/history/service.go
- service/worker/replicator/replicator.go
- service/worker/service.go
- temporal/server.go
- tools/cli/namespaceUtils.go
* Make entity with Start / Stop functions idempotent
* Remove misleading / unnecessary dynamic configs related to NDC
* Minor issue fixes
NOTE: 
* when running in `kafka` replication mode, both tx and rx will use Kafka replication stack
* when running in `kafka-to-rpc` replication mode
* tx will use RPC stack
* rx will use both RPC stack and Kafka stack
* when running in `rpc` replication mode, both tx and rx will use RPC replication stack
**Why?**
Code logic should guarantee at most once start / stop
Run locally with NDC w/ Kafka & NDC w/ RPC, NDC with Kafka -> RPC needs to be tested by larger cluster 
N/A
> Make entity with Start / Stop functions idempotent

- common/persistence/sql/sqlplugin/postgresql/tls.go
* Fix PostgreSQL EnableHostVerification behavior
**Why?**
TLS with EnableHostVerification == false means do not verify hostname and server cert
The definition of `EnableHostVerification` is `EnableHostVerification = !InsecureSkipVerify`
see `InsecureSkipVerify`: https://golang.org/pkg/crypto/tls/
PostgreSQL: https://www.postgresql.org/docs/9.6/libpq-ssl.html
Fix: #1047 
N/A
N/A
> Fix PostgreSQL EnableHostVerification behavior

- common/constants.go
* Change GetHistoryMaxPageSize from 100 to 256
**Why?**
GetHistoryMaxPageSize being too small will increase the history replay time on SDK
N/A
N/A
> Adjust GetHistoryMaxPageSize default size

- temporal/server.go
* Bugfix: messaging client not set when advanced visibility is used
**Why?**
When advanced visibility is enabled, messaging client should be initialized
N/A
N/A
> Bugfix: messaging client not set when advanced visibility is used

- common/metrics/client.go
- common/metrics/defs.go
- common/metrics/tags.go
- service/history/mutableStateBuilder_test.go
- service/matching/handler.go
Most of metrics received namespace="all" tag.
"forwarded" metric always reported with namespace and service_role tags.
**Why?**
Prometheus doesn't support reporting same metric name with different tags.
This is intended as a small fix to mitigate existing bugs. More generic fix is currently under ongoing discussion.
Integration tests with explicit os.exit(1)
Some metrics might change reporting location.
Aggregation of metrics logic should be changed in dashboards.
> Patch metrics reported with different tags.

- common/metrics/defs.go
- common/metrics/tags.go
- service/frontend/adminHandler.go
- service/frontend/workflowHandler.go
history_size and event_blob_size metrics now have same set of tags when reported.
**Why?**
Prometheus doesn't support report metrics with same name, but different tag sets.
Local unit/integration/canary tests.
Mistagged history_size and/or event_blob_size metrics.
> Fix: history_size and event_blob_size metrics should have same tags

- Makefile
Fixed:
```
Command "build" is deprecated, "image" sub-commands are now all implemented under the top-level "buf build" command, use "buf build" instead.
We recommend migrating, however this command continues to work.
```
**Why?**
Keep `buf` up to date.
N/A
N/A
> Fix buf build warning

- tools/cli/workflowCommands.go
* CLI use valid input for wfClient.GetSearchAttributes
**Why?**
We should use valid input, not nil
N/A
N/A
> Use valid input for wfClient.GetSearchAttributes

- service/matching/matchingEngine.go
* Go SDK cannot handle activity schedule to close timeout being 0, adding special handling int matching service
**Why?**
See above
N/A
N/A
> Properly handle infinite activity timeout for SDK

- common/log/tag/tags.go
- common/membership/rpMonitor.go
Adds a log when we are fetching bootstrap hosts which we try to connect to via Ringpop. This can help aid debuggability of cold starts in the future.
Low risk change as it is just an additional log.
> Adds log whenever we fetch bootstrap hosts for ringpop from DB

- common/authorization/defaultAuthorizer.go
Added nil checks for claims and namespaces within it.
**Why?**
The current code could cause NREs if claim mapper isn't configured. While nobody is expected to do that in production, it's a potential hurdle for initial development.
Unit tests.
No risk. This authorizer isn't enabled by default.
> Add checks for nil claims to defaultAuthorizer

- host/testdata/clientintegrationtestcluster.yaml
- host/testdata/integration_elasticsearch_cluster.yaml
- host/testdata/integration_sizelimit_cluster.yaml
- host/testdata/integration_test_cluster.yaml
- host/testdata/ndc_integration_test_clusters.yaml
- host/testdata/xdc_integration_es_clusters.yaml
- host/testdata/xdc_integration_test_clusters.yaml
Integration tests are configured to use internal visibility queue instead of Kafka for visibility.
**Why?**
As part of Kafka deprecation effort.
Run integration tests.
No risks, changes are in tests only.
> Switch integration tests to disable Kafka for visibility

- service/history/shard/context_impl.go
- service/history/timerQueueTaskExecutorBaseV2_test.go
`NotifyNew*Tasks` was added when `AddTasks` in shard context is used.
**Why?**
Bug fix.
Manually.
N/A
> Notify new task in shard context

- tools/cassandra/cqlclient.go
* Make Cassandra DB layer ReadSchemaVersion use LocalQuorum
**Why?**
In case Cassandra hosts down for maintenance
Solves #1085 
N/A
N/A
> Use local quorum for Cassandra when querying schema version

- config/dynamicconfig/development_es.yaml
`RolloutId` field was removed from ES dynamic config.
**Why?**
Field is not used. Leftover after ES fields cleanup.
N/A
N/A
> Remove leftover RolloutId

- common/service/dynamicconfig/constants.go
- host/onebox.go
- service/history/configs/config.go
- service/history/transferQueueActiveTaskExecutorV2_test.go
- service/history/transferQueueStandbyTaskExecutor_test.go
- service/history/transferQueueTaskExecutorBase.go
`history.disableTransferQueueProcessForVisibility` dynamic config flag was added to cover possible edge case during migration to Kafka free mode.
**Why?**
Backward compatibility upgrade plan:
1. Next release: no config change, `DisableKafkaForVisibility`: `false`, `DisableTransferQueueProcessForVisibility`: `false` (current defaults),
2. Next+1 release: disable publishing to transfer queue and Kafka: `DisableKafkaForVisibility`: `true`,
3. Next+2 release: disable processing of transfer queue and Kafka: `DisableTransferQueueProcessForVisibility`: `true`, `EnableIndexer`: `false`,
4. Next+3 release: Kafka and indexer code are completely removed.
I don't see any risks.
> Add DisableTransferQueueProcessForVisibility dynamic config flag

- common/constants.go
- common/service/dynamicconfig/constants.go
- host/onebox.go
- host/testdata/clientintegrationtestcluster.yaml
- host/testdata/integration_elasticsearch_cluster.yaml
- host/testdata/integration_sizelimit_cluster.yaml
- host/testdata/integration_test_cluster.yaml
- host/testdata/ndc_integration_test_clusters.yaml
- host/testdata/xdc_integration_es_clusters.yaml
- host/testdata/xdc_integration_test_clusters.yaml
- service/history/configs/config.go
- service/history/historyEngine.go
- service/history/mutableStateTaskGenerator.go
- service/history/service.go
- service/history/timerQueueTaskExecutorBase.go
- service/history/timerQueueTaskExecutorBaseV2_test.go
- service/history/transferQueueActiveTaskExecutorV2_test.go
- service/history/transferQueueStandbyTaskExecutor_test.go
- service/history/transferQueueTaskExecutorBase.go
- service/history/visibilityQueueTaskExecutor_test.go
- service/worker/service.go
`history.disableKafkaForVisibility`, `history.disableTransferQueueProcessForVisibility`, and `worker.enableIndexer` were replaced with single `history.visibilityQueue` setting with 3 possible values: `kafka`, `internalWithDualProcessor`, and `internal`.
**Why?**
To simplify upgrade experience. Current upgrade plan is the following:
1. Next release: default value for `history.visibilityQueue` is `kafka`.
* after rollout the release users change its value to `internalWithDualProcessor` and waits for Kafka queue to get drained and all previously created transfer queue tasks to be processed.
* when is is done (should be within seconds), value needs to be changed to `internal`.
2. Next+1 release: default value for `history.visibilityQueue` is `internal`. Kafka code path is …
> Replace bool visibility queue dynamic configs with single string config

- common/authorization/rsaTokenKeyProvider.go
- go.mod
- go.sum
Switched to using `jose.JSONWebKeySet` for parsing JWKS (sets of JWT signing keys).
Removed custom code for extracting RSA public keys from x509 certs that are optional in the JWKS standard.
**Why?**
Because the `X5c` field of JWKS is optional, existing code is failing to get RSA public keys from providers that don't support it. This was reported in #1090. 
Unit tests plus manual testing or Temporal Web.
The risk should be very low as this is an optional plugin.
> Switch to using jose.JSONWebKeySet for parsing JWKS

- schema/mysql/v57/visibility/schema.sql
- schema/mysql/v57/visibility/versioned/v1.1/index.sql
- schema/mysql/v57/visibility/versioned/v1.1/manifest.json
- schema/mysql/version.go
- schema/postgresql/v96/visibility/schema.sql
- schema/postgresql/v96/visibility/versioned/v1.1/index.sql
- schema/postgresql/v96/visibility/versioned/v1.1/manifest.json
- schema/postgresql/version.go
* Add new index to MySQL & PostgreSQL visibility table
NOTE: `The table remains available for read and write operations while the index is being created.`
Ref: https://dev.mysql.com/doc/refman/5.7/en/innodb-online-ddl-operations.html#online-ddl-index-operations
**Why?**
SQL side table schema lacks index on close time & run ID & status
Solves #1106
N/A
N/A
> Add proper index to SQL visibility store

- cmd/server/main.go
- common/service/config/loader.go
`EnvKeyAvailabilityZone` was changed from `TEMPORAL_AVAILABILTY_ZONE` to `TEMPORAL_AVAILABILITY_ZONE`.
This also adds backwards compatibility for the incorrectly spelt env key.
**Why?**
This corrects a typo that was a gotcha for me while trying to make use of this.
I've tried searching for existing references to this typo in this repo and could not find any. I assumed it's an indication that there are no tests around this, but I have run the full suite via `make test` and everything looks green locally.
I've manually verified by building the `server` bin and checking that both env vars are considered, with the correctly spelt version taking priority.
There shouldn't be any. This should be communicated in the release that …
> Fix typo on availability zone env key

- common/authorization/interceptor.go
- common/authorization/interceptor_test.go
- service/frontend/service.go
Stop sending details of authorization errors to the caller, log them on the server, and return a generic unauthorized error with no details. 
**Why?**
Returning details of authorization errors may inadvertently disclose information that could help a malicious caller. 
Unit tests
No risk
> Log details of authorization errors and return a generic unauthorized error to the caller

- config/development_active.yaml
- config/development_archival.yaml
- config/development_es.yaml
- config/development_mysql.yaml
- config/development_other.yaml
- config/development_postgres.yaml
- config/development_standby.yaml
Prometheus is used by default for metrics instead of `statsd`.
**Why?**
For consistency with main `development.yml` config.
N/A
No risks.
> Use Prometheus as default metrics provider for all configs

- common/metrics/defs.go
- common/persistence/elasticsearch/esProcessor.go
- common/persistence/elasticsearch/esProcessor_test.go
- common/persistence/elasticsearch/esVisibilityStore.go
ES bulk processor metrics were fixed to reflect recent copy of `ESProcessor.go` to the history service.
**Why?**
Fix bugs for Kafka deprecation effort.
Run locally and observe metrics.
No risks.
> Fix ES processor metrics

- service/history/service.go
Kafka producer didn't start in `internalWithDualProcessor` mode.
**Why?**
Bug fix.
Run manually.
No risks.
> Start Kafka producer in dual mode

- common/metrics/defs.go
Internal metrics ids (integers) are now unique per system, not per service.
**Why?**
If any metrics report call is moved from one service to another, it automatically starts to emit wrong metric instead of crashing.
Existing tests and manual run and observing metrics locally.
Some wrongly reported metrics may crush server with `nil dereference` now.
> Make metric ids globaly unique

- common/persistence/cassandra/cassandraClusterMetadata.go
- common/persistence/clusterMetadataStore.go
- common/persistence/sql/sqlplugin/mysql/cluster_metadata.go
- common/persistence/sql/sqlplugin/postgresql/cluster_metadata.go
- schema/cassandra/temporal/schema.cql
- schema/cassandra/temporal/versioned/v1.4/cluster_metadata.cql
- schema/cassandra/temporal/versioned/v1.4/executions.cql
- schema/cassandra/temporal/versioned/v1.4/manifest.json
- schema/cassandra/version.go
- schema/mysql/v57/temporal/schema.sql
- schema/mysql/v57/temporal/versioned/v1.4/cluster_metadata.sql
- schema/mysql/v57/temporal/versioned/v1.4/manifest.json
- schema/mysql/version.go
- schema/postgresql/v96/temporal/schema.sql
- schema/postgresql/v96/temporal/versioned/v1.4/cluster_metadata.sql
- schema/postgresql/v96/temporal/versioned/v1.4/manifest.json
- schema/postgresql/version.go
* Since 1.5.x is still using the to be deprecated column names, postpone the deprecation
**Why?**
Smooth schema migration
CICD pipeline
N/A
> Bugfix schema migration

- common/authorization/interceptor.go
Added content of "authorization" header to context.
**Why?**
This gives workflows and activities access to the JWT auth token (if passed).
Addresses #1135.
Unit tests.
No risk. This only adds data to context.
> Add authorization header to context

- service/history/configs/config.go
- service/history/transferQueueActiveTaskExecutorV2_test.go
- service/history/transferQueueStandbyTaskExecutor_test.go
- service/worker/service.go
#1140 switched default value to `internal` which is not backward compatible. With dual processor mode users can install next release w/o any changes in config files. 
**Why?**
To improve upgrade experience.
No risks.
> Switch visibility queue to dual processor mode

- common/persistence/cassandra/cassandraPersistence.go
- tools/cli/adminCommands.go
- tools/cli/adminDBScanCommand.go
Fixed DBScan admin commands which checks for corruptions in the db
**Why?**
DBScan command was broken as ListConcreteExecutions API was not working.  Fixed
ListConcreteExecutions API on cassandra persistence and also fixed logic to correctly
decode `BranchToken` in admin command handler.
Tested locally by manually corrupting workflow executions.
No risk.
> Fix db scan admin command

- common/persistence/cassandra/cassandraClusterMetadata.go
- common/persistence/cassandra/cassandraHistoryPersistence.go
- common/persistence/cassandra/cassandraMetadataPersistenceV2.go
- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/cassandra/cassandraQueue.go
- common/persistence/cassandra/cassandraVisibilityPersistence.go
- common/persistence/cassandra/factory.go
- common/persistence/cassandra/session.go
- common/persistence/client/factory.go
- common/persistence/sql/factory.go
- common/service/config/config.go
- common/service/dynamicconfig/constants.go
- docker/config_template.yaml
- host/onebox.go
- service/frontend/service.go
- service/history/configs/config.go
- service/history/service.go
* Reduce number of open cassandra sessions
**Why?**
See above
N/A
N/A
> Refactor Cassandra for less open sessions

- common/persistence/client/factory.go
- go.mod
- go.sum
- tools/cassandra/handler.go
For certain datastores, establishing a connection to it can take on the order of seconds. In many cases, we establish connections to the data and visibility stores serially as opposed to in parallel, which presents a significant opportunity for savings on startup-time.
Reduces the startup time for Temporal by up to 50% for certain types of persistence stores.
> Parallelizes instantiation of connections to data and visibility stores

- Makefile
`GOMODULE111` turned `off` for github.com/temporalio/gogo-protobuf/protoc-gen-gogoslick plugin.
**Why?**
Sources of this plugin are needed to build proto files. With `GOMODULE111=on` go will only install binaries. 
Run with empty cache.
N/A.
> Fix protoc-gen-gogoslick plugin installation

- tools/cli/admin-decode-commands.go
- tools/cli/admin.go
- tools/cli/app.go
- tools/cli/flags.go
Added new admin commands to `tctl`:
1. `admin decode proto`
2. `admin decode base64`
```
$ tctl admin decode proto --type temporal.server.api.persistence.v1.WorkflowExecutionInfo --hex_data 0a243462613036633466...
$ tctl admin decode base64 --base64_data WyJpbml0aWFsIHZlcnNpb24tMyJd
```
**Why?**
Useful for debugging.
Manually.
No risks.
> Add 'admin decode proto' and 'admin decode base64' commands

- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/cassandra/session.go
- tools/cassandra/cqlclient.go
* Update Cassandra cli consistency settings, with default to local quorum
**Why?**
AwaitSchemaAgreement is being used
Solves #1168 
N/A
N/A
> Update Cassandra cli consistency settings

- Makefile
- tools/cassandra/main.go
- tools/common/schema/types.go
- tools/sql/main.go
Added database/keyspace drop confirmation and `--force` flag (and `-f` alias) to sql and cassandra db tools. Modified `Makefile` accordingly.
**Why?**
To protect developers from accidental database/keyspace drop.
Run locally.
No risks.
> Add force flag to drop command of database tools

- common/service/dynamicconfig/constants.go
- service/history/configs/config.go
- service/history/historyEngine.go
- service/worker/service.go
Added dynamic config option to completely disable visibility processor (both internal and legacy Kafka).
**Why?**
To support smooth migration from ES6 to ES7.
Existing tests. Local run with different values (`true`/`false`).
No risks.
> Add option to disable visibility queue processor

- service/history/nDCStandbyTaskUtil.go
- service/history/nDCTaskUtil.go
- service/history/timerQueueStandbyTaskExecutor.go
- service/history/timerQueueStandbyTaskExecutor_test.go
- service/history/transferQueueStandbyTaskExecutor.go
- service/history/transferQueueStandbyTaskExecutor_test.go
* Try refresh tasks in source cluster before resend history
**Why?**
N/A
N/A
N/A
> Add extra protection logic to passive task processing

- common/elasticsearch/bulk_processor_v6.go
- common/elasticsearch/bulk_processor_v7.go
- common/persistence/elasticsearch/esVisibilityManager.go
- service/history/visibilityQueueTaskExecutor.go
Sampling for enhanced visibility is removed.
**Why?**
Sampling was designed for Cassandra and MySQL implementation but not for Elasticsearch. Elasticsearch should store all visibility data.
N/A.
No risks.
> Remove visibility sampling for ES

- common/elasticsearch/client_v6.go
- common/elasticsearch/client_v7.go
- common/elasticsearch/logger.go
- host/testcluster.go
- temporal/server.go
Added error logger to ES client.
**Why?**
Improve visibility of ES errors.
Run locally with simulated ES failures (ES is down).
No risks.
> Add ES logger

- common/persistence/elasticsearch/esVisibilityStore_test.go
- host/testcluster.go
- service/history/configs/config.go
- tools/cli/namespaceUtils.go
Changed default ES bulk processor ack timeout to 1 minute.
**Why?**
This timeout includes all possible retries bulk processor might do. In case of transient ES failures 5 seconds is too low.
Run locally.
No risks.
> Set default ES bulk processor ack timeout to 1 minute

- common/persistence/cassandra/factory.go
- common/persistence/sql/factory.go
- common/persistence/sql/sqlplugin/postgresql/plugin.go
- common/persistence/sql/sqlplugin/postgresql/tls.go
* Include connectAttributes as part of connection string
**Why?**
`connectAttributes` was not used
Closes #1208
Manual test locally
```yaml
persistence:
defaultStore: postgres-default
visibilityStore: postgres-visibility
numHistoryShards: 4
datastores:
postgres-default:
sql:
pluginName: "postgres"
databaseName: "temporal"
connectAddr: "127.0.0.1:5432"
connectProtocol: "tcp"
connectAttributes:
application_name: temporaltest
postgres-visibility:
sql:
pluginName: "postgres"
databaseName: "temporal_visibility"
connectAddr: "127.0.0.1:5432"
connectProtocol: "tcp"
connectAttributes:
application_name: temporaltest
```
```sql
postgres=# SELECT application_name FROM pg_stat_activity limit 1;
application_name 
------------------
temporaltest
(1 row)
``` …
> Improve PostgreSQL config

- service/history/commandChecker.go
* Activity heartbeat timeout can be override by start to close timeout, not schedule to close timeout
**Why?**
Bugfix
Close #1218 
Run tests
N/A
> Bugfix: activity heartbeat timeout

- common/metrics/interfaces.go
- common/metrics/scope.go
* Fix metrics scope namespace tagged initialization
**Why?**
Bugfix
N/A
N/A
> Fix metrics scope namespace tag initialization

- common/elasticsearch/client_v6.go
- common/elasticsearch/client_v7.go
- common/elasticsearch/config.go
- common/persistence/elasticsearch/esProcessor.go
- common/persistence/elasticsearch/esProcessor_test.go
- config/development_es.yaml
- config/development_mysql-es.yaml
* Added `logLevel` to ES config with possible values: `error` (default), `info`, `trace`, and `disabled`.
* Improved duplicate request logging.
**Why?**
Improve ES logging for better debug expirience.
Run locally and observed trace level logs.
No risks.
> Improve ES logging

- service/history/transferQueueTaskExecutorBase.go
Bugfix: close execution request goes to Kafka even when visibility queue type is set to `internalWithDualProcessor`.
**Why?**
When visibility queue type is set to `internalWithDualProcessor` no write requests should go to the Kafka.
Run locally.
No risks.
> Bugfix: close execution request goes to Kafka even when visibility queue type is set to internalWithDualProcessor

- .development/docker-compose/docker-compose.yml
Change development docker-compose prometheus error loeve to `error` only.
**Why?**
To suppress noise `warn` level logs when server is down and prometheus can scrape metrics.
Run locally.
No risks.
> Change prometheus log level to error only

- .development/docker-compose/docker-compose.yml
- service/history/configs/config.go
- service/worker/service.go
Switch visibility queue from `internalWithDualProcessor` to `internal`.
**Why?**
As part of Kafka deprecation this will completely remove usage of Kafka (code and configuration files are still there).
Tests already use `internal`. Run locally also.
Moving directly from `kafka` to `internal` may lead to some unprocessed visibility messages stuck in Kafka. Follow upgrade instruction from [v1.5.0](https://github.com/temporalio/temporal/releases/tag/v1.5.0) release to properly migrate out of Kafka.
> Switch visibility queue default to internal

- common/metrics/defs.go
- common/service/config/metrics.go
* Increase number of histogram buckets
**Why?**
N/A
N/A
N/A
> Adjust number of histogram buckets

- common/elasticsearch/aws.go
- common/elasticsearch/client_factory.go
- common/elasticsearch/client_v6.go
- common/elasticsearch/client_v7.go
- host/testcluster.go
- temporal/server.go
- temporal/server_option.go
- temporal/server_options.go
Add ability to pass custom HTTP client used for Elasticsearch using `ServerOption`.
**Why?**
To be able to inject any customer HTTP client for custom builds.
https://community.temporal.io/t/passing-in-custom-http-client-for-signing-elasticsearch-requests/1339
No risk, default behaviour stays the same.
> Add server option for custom Elasticsearch HTTP client

- tools/sql/clitest/handlerTest.go
- tools/sql/clitest/handler_test.go
- tools/sql/handler.go
This allows using TLS for transport but not authentication for the sql tool, consistent with temporal server.
Prior to this fix it was not possible to use the SQL tool to connect to Postgres which required TLS for transport
security but was not setup to use TLS for authentication.
Tested by running modified sql tool locally against an Postgres instance configured to require TLS for transport security but not authentication.
> Bugfix: Allow enabling TLS for sql tool without requiring key/cert.

- schema/elasticsearch/v7/visibility/index_template.json
Set `search.idle.after` parameter in ES7 index schema to 365 days.
**Why?**
We see some latency spikes for `_search` requests. After [investigation](https://discuss.elastic.co/t/bug-elasticsearch-7-after-upgrade-from-6-7-slow-search-during-3-5-seconds-every-60-seconds/177017/35) it turn out that it is because ES shard got [parked](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_skipped_background_refresh_on_search_idle_shards) after 30 seconds of default timeout.
Manually uploaded configuration to the test cluster and observed latency.
No risks.
> Set search.idle.after to 365 days

- cmd/server/main.go
Replace deprecated `NewExitError` with `Exit` method.
**Why?**
Remove deprecated call.
Run locally.
No risks.
> Replace deprecated NewExitError with Exit method

- Makefile
Add `build-test` target which only build tests but don't run them.
**Why?**
To improve developer experience. Currently if there are compile errors in tests, `staticcheck` will fail and it is not easy to find root cause.
Inspired by https://github.com/skipor/go-test-compile.
Run it locally and as part of `ci-build` target on Buildkite.
No risks.
> Add build-test target

- common/persistence/elasticsearch/esProcessor.go
- common/persistence/elasticsearch/esProcessor_test.go
- common/persistence/elasticsearch/esVisibilityStore.go
Use document Id to match request and response in ES processor `afterFunc` callback.
**Why?**
Request and response sizes are not guarantee to be the same and can be unordered in `afterFunc` handler of ES `BulkProcessorService`. Using document Id which is unique (it has `runID`) to match request and response items.
No risks.
> Use document Id to match request and response in ES processor afterFunc callback

- common/persistence/persistence-tests/shardPersistenceTest.go
- service/history/shard/context_impl.go
Copy `visibilityAckLevel` in `copyShardInfo`.
**Why?**
Bug fix. Missing assignment leaded to `visibilityAckLevel` being not persisted.
Run manual tests.
No risks.
> Copy visibilityAckLevel in copyShardInfo

- common/auth/tlsConfigHelper.go
- common/messaging/kafkaClient.go
- common/rpc/encryption/certificate.go
- common/rpc/encryption/localStoreTlsFactory.go
- common/rpc/encryption/testDynamicCertProvider.go
- common/rpc/encryption/testDynamicTLSConfigProvider.go
- common/rpc/test/rpc_common_test.go
- common/rpc/test/rpc_localstore_tls_test.go
Switched retrieval of all certs to be performed for each connection.
**Why?**
Before this change, TLS configuration is static. That is, a certificate is retrieved from the cert provider only once, and then is reused by gRPC until server restarts except for the per-host frontend certs. This change switches retrieval of all certs to be performed for each connection, which enables updating of cert without restarting server.
Establishment of new TLS connections can be slightly slower, but that should be negligible compared how long it TLS negotiation takes.
> Enable dynamic update of TLS certificates

- cmd/server/main.go
- common/authorization/authorizer.go
- common/authorization/claimMapper.go
- common/authorization/defaultAuthorizer.go
- common/authorization/defaultAuthorizer_test.go
- common/authorization/defaultJWTClaimMapper_test.go
- common/authorization/nopAuthorizer.go
- common/service/config/config.go
- docker/config_template.yaml
- host/onebox.go
- temporal/server.go
Added config switches and logic for selecting authorizer and claim mapper via config.
**Why?**
People that use our docker images need a way to select authorizer and claim mapper without resorting to building their own images (to use Server Options).
Manually and unit tests.
I see no real risk here as the default behavior stayed unchanged.
> Add config parameters for selecting authorizer and claim mapper

- service/frontend/workflowHandler.go
- service/history/commandChecker.go
- service/history/commandChecker_test.go
- service/history/historyEngine.go
- service/history/historyEngine_test.go
- service/history/workflowTaskHandlerCallbacks.go
Move search attributes validator from frontend to history.
**Why?**
1. Internal requests might bypass frontend.
2. All validation logic is already in history, so it is more natural to validate search attributes there too.
Run tests.
No risks.
> Move search attributes validator from frontend to history

- tools/cli/util.go
- tools/cli/workflowCommands.go
Fix `tctl` `start workflow` command with empty search attributes.
**Why?**
W/o fix, start command treats empty search attributes list as list with one empty item, which is wrong and doesn't pass server validation.
Run different combinations manually.
No risks.
No.
> Fix tctl start workflow command with empty search attributes

- common/log/loggerimpl/logger.go
- common/log/tag/interface.go
- common/log/tag/tags.go
- service/history/mutableStateBuilder.go
Exported Tag.Zap and tag helper functions.
**Why?**
Implementors of extensions to plug in via the server options have troubles logging their own data types via zap because Tag.Field is not exported and cannot use the tag helper functions. This change makes these facilities available to extension developers.  
Unit tests
No risk.
No.
> Export Tag.Field and tag helper functions

- common/persistence/cassandra/cassandraClusterMetadata.go
- common/persistence/cassandra/cassandraCommon.go
- common/persistence/cassandra/cassandraHistoryPersistence.go
- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/cassandra/cassandraQueue.go
- common/persistence/cassandra/cassandraVisibilityPersistence.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/errors.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go
* Unify cassandra error conversion
* Fix initialization issue of new gocql wrapper
**Why?**
N/A
N/A
N/A
N/A
> Unify cassandra error conversion

- host/integration_test.go
- service/history/workflowTaskHandler.go
- service/history/workflowTaskHandlerCallbacks.go
* Properly set the the default value of namespace attr of StartChildWorkflowExecutionInitiatedEvent
**Why?**
N/A
N/A
N/A
N/A
> Properly set the the default value of namespace attr

- common/elasticsearch/bulk_processor_v6.go
- common/elasticsearch/bulk_processor_v7.go
- common/elasticsearch/client.go
- common/elasticsearch/client_mock.go
- common/metrics/noop_metrics_client.go
- common/persistence/visibilityInterfaces.go
- common/searchattribute/defs.go
- host/testcluster.go
- tools/cli/admin.go
- tools/cli/adminElasticSearchCommands.go
`persistence.RecordWorkflowExecutionClosedRequest` is used instead of `indexerspb.Message` in `tctl admin es index` command.
**Why?**
Prepare to remove Kafka and `indexerspb.Message` from the code.
Run `tctl` manually locally.
`tctl admin es index` input file format is changed.
No.
> Remove Kafka message usage from admin ES index command

- .development/scripts/goreleaser.sh
- .github/workflows/goreleaser.yml
- .gitignore
- .goreleaser.yml
- CONTRIBUTING.md
Added GoReleaser configuration to attach binary builds to Github releases.
**Why?**
It is generally requested. This PR closes #305 #781 #927 #1075
By making a test release in the fork. 
Link to the test release: https://github.com/h7kanna/temporal/releases/tag/1.8.0
Link to the GitHub action run: https://github.com/h7kanna/temporal/actions/workflows/goreleaser.yml
None
No
> Added goreleaser configuration to publish binaries

- common/persistence/serialization/blob.go
- service/history/historyEngine.go
- service/history/mutableState.go
- service/history/mutableStateBuilder.go
- service/history/mutableState_mock.go
* Rename mutable state `ToProto` function to `CloneProto`
* Make `CloneProto` function do deep copy of mutable state
**Why?**
`ToProto` function was doing shallow copy of mutable state, which means pointer to mutable state is still valid after mutable state lock is released.
Ref:
https://github.com/temporalio/temporal/blob/v1.7.0/service/history/mutableStateBuilder.go#L270-L284
https://github.com/temporalio/temporal/blob/v1.7.0/service/history/historyEngine.go#L1076
https://github.com/temporalio/temporal/blob/v1.7.0/service/history/historyEngine.go#L1084
N/A
See why
No
> Fix potential data race DescribeMutableState API

- Dockerfile
Fix pip installer download path.
**Why?**
`pip` download path was changed on Python side and it broke Temporal `docker build`:
```
The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:
https://bootstrap.pypa.io/pip/2.7/get-pip.py
Sorry if this change causes any inconvenience for you!
```
Build image locally.
No risks.
No.
> Fix pip installer download path

- common/persistence/serialization/blob.go
- service/history/historyEngine.go
- service/history/mutableState.go
- service/history/mutableStateBuilder.go
- service/history/mutableState_mock.go
Use `proto.Clone` instead of custom serializer.
**Why?**
Recently potential data race was fixed in #1360. This PR slightly simply the fix by leavereging pregenerated `proto.Clone()` func.
No risks.
No.
> Use proto.Clone instead of custom serializer

- common/authorization/interceptor_test.go
- common/metrics/client.go
- common/metrics/common.go
- common/metrics/config.go
- common/metrics/config_test.go
- common/metrics/interfaces.go
- common/metrics/interfaces_mock.go
- common/metrics/nop.go
- common/metrics/stopwatch.go
- common/persistence/elasticsearch/processor.go
- common/persistence/elasticsearch/processor_test.go
- common/service/config/config.go
- service/worker/archiver/replay_metrics_client.go
Move metrics scope initialization logic to metrics package.
Remove Tally from metrics interface.
**Why?**
Cleaning up interface to make it easier to add support for OpenTelemetry.
No
> Cleanup metrics interface.

- tools/cli/stringify/stringify.go
- tools/cli/stringify/stringify_test.go
In `tctl`, always print first slice item and length if there are more. (when `tctl` prints out different structures such as workflow history).
Old version:
```
1  WorkflowExecutionStarted  {WorkflowType:{Name:cronWorkflow},                             
...
PrevAutoResetPoints:{Points:[len=1]},                          
Header:{Fields:map{_tracer-data:{}}}}  
```
New version:
```
1  WorkflowExecutionStarted  {WorkflowType:{Name:cronWorkflow}, ParentInitiatedEventId:0,                    
...
PrevAutoResetPoints:{Points:[{BinaryChecksum:85f30e2356766729577cccc58382d155,  
RunId:e50ded41-a4b2-4d4e-935b-80c82c93983f, FirstWorkflowTaskCompletedId:4,     
CreateTime:2021-03-15 20:24:38.806197758 +0000 UTC,                             
ExpireTime:2021-03-25 20:24:43.839456587 …
```
> tctl: always print first slice item and length if there are more

- common/rpc/encryption/localStoreCertProvider.go
- common/rpc/encryption/localStorePerHostCertProviderMap.go
- common/rpc/encryption/localStoreTlsProvider.go
- common/rpc/encryption/testDynamicCertProvider.go
- common/rpc/encryption/testDynamicTLSConfigProvider.go
- common/rpc/encryption/tlsFactory.go
Removed from `CertProvider` and `ClientCertProvider` methods that are not concerned with getting certs and only return pieces of TLS configuration in a roundabout way. 
**Why?**
To make cert provider pluggable, the interfaces need to be clean from the superfluous functionality that got into them
Unit tests
I don't see a risk as this functionality isn't pluggable yet.
No
> Refactor cert provider interfaces to simplify them

- common/rpc/encryption/localStoreCertProvider.go
- common/rpc/encryption/localStorePerHostCertProviderMap.go
Add a length check to protect from possible panic
**Why?**
To protect from an NRE panic in case certificate data is malformed.
Unit tests
None
No
> Add a length check to protect from possible panic

- common/metrics/scope.go
- common/metrics/tags.go
Before: Aggregated metrics are reported as "<metric_name>" metric name and namespace="all" label.
After: Aggregated metrics are reported as "<metric_name>_total" metric name.
Note: dashboards will have to be changed if they were showing old metric type.
**Why?**
It is inconvenient for user to aggregate and display metrics.
manual testing, automated tests
Name collision on prometheus server when reporting metrics.
Automation based on old metric format will stop working.
No
> Report aggregated metrics under explicit metric name

- common/rpc/encryption/localStoreCertProvider.go
- common/rpc/encryption/localStorePerHostCertProviderMap.go
- common/rpc/encryption/localStoreTlsProvider.go
- common/rpc/encryption/testDynamicCertProvider.go
- common/rpc/encryption/testDynamicTLSConfigProvider.go
- common/rpc/encryption/tlsFactory.go
- common/rpc/test/rpc_localstore_tls_test.go
- temporal/server.go
Removed `ClientCertProvider` interface and consolidated all cert provider methods in `CertProvider` interface.
Added `GetExpiringCerts()` to all cert provider interfaces.
Refactored `localStoreTlsProvider` to support injection of cert provider implementation instead of the hardcoded `localStoreCertProvider`.
**Why?**
This enables injection of cert provider implementation with a clean interface it needs to implement.
Unit tests.
No risk. The change is backward compatible expect for the GetExpiringCerts() method added to `TLSConfigProvider` interface. People who inject their custom TLS config providers would need to implement it.
No
> Refactor cert provider interfaces and make cert provider injectable

- .goreleaser.yml
* Include mac os / linux arm64 as binary release target
**Why?**
Close #1305 
See above pic
N/A
No
> Include mac arm64 for binary release

- common/namespace/attrValidator.go
- service/frontend/errors.go
- service/frontend/workflowHandler.go
* Add missing check on upper limit of retention days to UpdateNamespaceAPI
**Why?**
Check is missing
N/A
N/A
No
> Add missing retention days check on update namespace API

- common/dynamicconfig/config_test.go
- common/dynamicconfig/constants.go
- common/dynamicconfig/file_based_client.go
Changed the visibility of the `keys` mapping in dynamicconfig to public.
**Why?**
Dynamic config client extensions may want to reuse the same keys as upstream. Making it public will reduce copy/paste synchronization between version changes.
tests
None
No
> dynamicconfig: Make Keys public for use in extension clients

- common/persistence/sql/sqlplugin/postgresql/plugin.go
- tools/sql/clitest/connTest.go
* Try using a set of default database names when initializing admin DB connection
**Why?**
Aiven DB is a PostgreSQL compatible DB, but comes with a different default DB name
Close #1389
Existing test
N/A
No
> Improve compatibility with Aiven DB

- common/rpc/interceptor/namespace.go
- common/rpc/interceptor/namespace_count_limit.go
- common/rpc/interceptor/namespace_rate_limit.go
- common/rpc/interceptor/namespace_test.go
- common/rpc/interceptor/telemetry.go
- service/frontend/service.go
- service/history/service.go
- service/matching/service.go
* Fix namespace name metrics extraction issue for matching & history service
**Why?**
Previously, the namespace attribute extraction only works for frontend service (request comes with namespace name).
Internal request only contains namespace ID, which were not processed correctly
N/A
N/A
Yes
> Fix metrics namespace tagging issue for matching & history service

- service/history/nDCTransactionMgrForNewWorkflow.go
* When doing events reapplication, release current workflow lock earlier in case of deadlock
**Why?**
Cherry pick https://github.com/uber/cadence/pull/4085
N/A
N/A
No
> Fix NDC events reapplication potential deadlock issue

- common/dynamicconfig/constants.go
- service/frontend/service.go
**Summary:**
Added default keep-alive [server parameters](https://pkg.go.dev/google.golang.org/grpc@v1.36.0/keepalive#ServerParameters) and [enforcement policy](https://pkg.go.dev/google.golang.org/grpc@v1.36.0/keepalive#EnforcementPolicy) for gRPC connection management.
This compliments client-side changes that we recently made in [Go](https://github.com/temporalio/sdk-go/pull/370) and [java](https://github.com/temporalio/sdk-java/pull/363) SDKs.
**List of added properties (with frontend.keepAlive prefix) and their default values:**
* **MinTime**:  minimum amount of time a client should wait before sending a keepalive ping. **Default 1 min**. Rationale - set slightly higher than minimal interval to avoid lots of spamming requests.
* **PermitWithoutStream**: If true, server allows …
> Add basic connection management and keep alive parameters

- common/resource/bootstrapParams.go
- common/resource/resourceImpl.go
- host/onebox.go
- service/frontend/adminHandler.go
- service/frontend/adminHandler_test.go
- service/frontend/service.go
- service/frontend/versionChecker.go
- service/history/service.go
- service/matching/service.go
- service/worker/archiver/client_worker.go
- service/worker/service.go
- temporal/server.go
Remove `params` field from service and handler objects.
Move some service and handler initialization logic to constructor from `Start()` method.
**Why?**
`params` object is to pass params to constructors but not to be stored as a field inside object itself.
Build, run current tests, run canary locally.
No risks.
No.
> Remove params field from service and handler objects

- common/config/config.go
- common/log/tag/tags.go
- common/rpc/encryption/localStoreCertProvider.go
- common/rpc/encryption/localStorePerHostCertProviderMap.go
- common/rpc/encryption/localStoreTlsProvider.go
- common/rpc/encryption/testDynamicCertProvider.go
- common/rpc/encryption/tlsFactory.go
- common/rpc/test/rpc_common_test.go
- common/rpc/test/rpc_localstore_tls_test.go
This is a replacement for #1395 that I'm unable to reopen now.
What changed?
Added support for periodic refreshing of TLS certs loaded from files.
Why?
To allow for refreshing TLS certs without restarting server.
How did you test it?
Unit tests.
Potential risks
If a previously loaded cert disappears from the file system, TLS connections will get broken after a refresh period.
Is hotfix candidate?
No.
> Add support for periodic refreshing of TLS certs loaded from files

- common/authorization/roles.go
Added a field to `Claims` struct for passing additional data between ClaimMapper and Authorizer.
**Why?**
To enable extensibility for authorization scenarios.
No test is needed
None
No
> Add an ExtraData field to Claims struct 

- service/history/mutablestate/history_builder.go
- service/history/mutablestate/history_builder_test.go
* Port mutable state events buffering functionality to new history builder
* Port mutable state events flushing functionality to new history builder
* Port mutable state buffer events ID wire logic to new history builder
* Add necessary UT
**Why?**
Move events buffer / reordering logic into dedicated place && more UT
Easier to implement events chaining
New tests
No, code not used yet
No
> Port mutable state events buffering functionality to new history builder

- common/metrics/defs.go
- common/searchattribute/validator.go
- common/searchattribute/validator_test.go
- common/util.go
- service/history/commandChecker.go
- service/history/historyEngine.go
- service/history/workflowTaskHandler.go
- service/history/workflowTaskHandlerCallbacks.go
Fail workflow if search attributes size exceed limit.
Split single search attributes validator into two:
1. Validate names and types.
2. Validate size of each value and total size.
**Why?**
First validator works as before: it fails workflow task and therefore leads to retries (until Workflow code is fixed or search attribute is registered).
Second validator now fails Workflow right away to prevent server overload due to exceeded size of search attributes values.
Total size limit now include attributes names and metadata size, so if total size was very close to the limit before it might start fail workflow now. Which is very unlikely though, because default total size limit is 40K. …
> Fail workflow if search attributes size exceed limit

- tools/cassandra/cqlclient.go
We noticed a few instances where the temporal-cassandra-tool is taking a long time to apply schema updates. We suspect this is because testing connection establishment is taking quite a while, but we do not have any logs around this. This PR adds logs to better diagnose this.
> Adds additional logging around connection validation to temporal-cassandra-tool

- common/persistence/cassandra/cassandraVisibilityPersistence.go
- common/persistence/persistence-tests/visibilityPersistenceTest.go
- common/persistence/persistenceInterface.go
- common/persistence/visibilityInterfaces.go
- common/persistence/visibilityStore.go
- service/history/transferQueueActiveTaskExecutor_test.go
- service/history/transferQueueStandbyTaskExecutor_test.go
- service/history/transferQueueTaskExecutorBase.go
- service/history/visibilityQueueTaskExecutor.go
- service/history/visibilityQueueTaskExecutor_test.go
Remove TTL from `open_executions` Cassandra visibility table.
**Why?**
Previously TTL was set to workflow timeout as an extra protection in case of close workflow execution task lost. Also there was a bug in this protection which set this TTL to 1 day in case of `nil` (unlimited timeout). This protection is not needed with new visibility queue.
Current tests.
No risks.
Yes.
> Remove TTL from open_executions Cassandra visibility table

- host/resetworkflow_test.go
- service/history/historyEngine.go
- service/history/historyEngine_test.go
- service/history/mutableState.go
- service/history/mutableStateBuilder.go
- service/history/mutableStateBuilder_test.go
- service/history/mutableStateWorkflowTaskManager.go
- service/history/mutableStateWorkflowTaskManager_mock.go
- service/history/mutableState_mock.go
- service/history/nDCTransactionMgrForNewWorkflow.go
- service/history/timerQueueStandbyTaskExecutor_test.go
- service/history/workflowExecutionContext.go
- service/history/workflowResetter.go
- service/history/workflowResetter_test.go
- service/history/workflowTaskHandlerCallbacks.go
* Allow reset workflow with event ID in range [workflow task schedule ID+1, workflow task start ID+1]
* Add UT & integration test
**Why?**
Allow more reset points for ResetWorkflow API
Close #1358
New tests
N/A
No
> Relax the constraint on which event ID is allow for ResetWorkflow API

- host/xdc/integration_failover_test.go
- service/history/nDCStateRebuilder.go
* Add cross DC integration test for ResetWorkflow API
* Rewrite verbose code logic
**Why?**
Add missing integration test for workflow reset
New test
N/A
No
> Add XDC integration test for ResetWorkflow API

- common/persistence/history_node_util_test.go
- common/persistence/workflowStateStatusValidator_test.go
- host/xdc/integration_failover_test.go
* Add necessary tests to history node util
**Why?**
Adding necessary UT
New tests
N/A
No
> Add more tests for history node util

- docker/config_template.yaml
config_template.yaml now supports enabling TLS for SQL databases through the `SQL_TLS_ENABLED` env var.
> Introduce SQL_TLS_ENABLED env var to allow enabling TLS for SQL datastores

- common/rpc/encryption/localStoreCertProvider.go
- common/rpc/encryption/tlsFactory.go
Exported `encryption.NewLocalStoreCertProvider()`.
**Why?**
`NewLocalStoreCertProvider()` is currently only used from within `NewTLSConfigProviderFromConfig()`. This change will allow it to be leveraged from other implementations of `TLSConfigProvider`.
Unit test.
No risk.
No.
> Export encryption.NewLocalStoreCertProvider()

- tools/cassandra/handler.go
- tools/cassandra/main.go
- tools/cli/adminCommands.go
- tools/cli/app.go
- tools/cli/factory.go
- tools/cli/flags.go
- tools/cli/persistenceUtil.go
- tools/common/schema/types.go
- tools/sql/handler.go
- tools/sql/main.go
* CLI TLS default to perform host name verification
* Remove CLI TLS enable host verification flag, `tls_enable_host_verification` and `tls-enable-host-verification`
* Add CLI TLS disable host verification flag `tls_disable_host_verification` and `tls-disable-host-verification`
**Why?**
Changing the default behavior for better security reasons
Manual tests & CICD
CLI behavior breaking change
No
> Change CLI default TLS host name verification behavior

- tools/cli/factory.go
- If the server name was provided but not any cert paths, initialize TLS with the server name only for DNS resolution.
**Why?**
- We have Temporal frontend running behind a domain name and this allows us to hit it from `tctl` without needing to provide a certificate.
- Tested in Kubernetes with Temporal frontend behind a domain name.
- Nothing will be broken because if cert paths are provided, the TLS config is returned before this has a chance to get called.
- Probably not, but we need this for our developers to be able to hit Temporal from `tctl` on their developer machines without having to use admin tools or pod ip:port.
> Added TLS config for only server name if it's only option provided.

- tools/cassandra/handler.go
- tools/cassandra/main.go
- tools/cli/adminCommands.go
- tools/cli/factory.go
- tools/cli/persistenceUtil.go
- tools/common/schema/types.go
- tools/sql/handler.go
- tools/sql/main.go
* Allow overriding host name for TLS host name verification in schema tools
* Disable TLS host name verification when `tls_disable_host_verification` or `tls-disable-host-verification` is set
**Why?**
Disable TLS host name verification when `tls_disable_host_verification` or `tls-disable-host-verification` is set since user need to explicitly set this flag to disable the verification
CICD
same as #1478, behavior change
No
> Add TLS host name override config for Cassandra / SQL tool

- common/auth/tlsConfigHelper.go
- common/rpc/encryption/localStoreTlsProvider.go
- common/rpc/encryption/testDynamicTLSConfigProvider.go
Added logging of attempted and successfully established TLS connections to server
**Why?**
To have records in the log of all attempted TLS connections to server and remote IP addresses of parties trying to connect.
Unit tests.
No risks.
No.
> Add logging for attempted and successful TLS connections to server

- service/history/mutablestate/history_builder.go
- service/history/mutablestate/history_builder_test.go
* Port existing buffered events reorder alg to new history builder
**Why?**
Port of existing functionality
Buffered events can sometimes be reordered by Cassandra due to next event ID being the same
New tests
N/A
No
> Add additional service protection against reordering

- common/rpc/grpc.go
- common/rpc/rpc.go
* Set Temporal internode comm max recv payload size to 128MB
**Why?**
Temporal internode communication should not be limited to 4MB default gRPC size limit (receiver side)
N/A
N/A
No
> Set Temporal internode comm max recv payload size to 128MB

- host/activity_test.go
- host/ndc/ndc_integration_test.go
- host/xdc/integration_failover_test.go
* Improve the stability of TestActivityHeartbeatDetailsDuringRetry
* Improve the stability of TestUserTimerFailover
* Improve the stability of TestEventsReapply_ZombieWorkflow
**Why?**
Fix unstable tests
Existing tests
N/A
No
> Improve integration tests stability

- common/persistence/cassandra/version_checker.go
- common/persistence/sql/version_checker.go
- config/development_es.yaml
- config/development_mysql-es.yaml
- temporal/server.go
- tools/cassandra/version_test.go
- tools/sql/clitest/versionTest.go
Skip visibility database validation if advanced visibility is enabled.
**Why?**
If advanced visibility is enabled (`system.advancedVisibilityWritingMode` is `on` in dynamic config) there is no need to validate visibility database configuration because it is not used. This allows to remove visibility database configuration from static config in case if advanced visibility is enabled. Closes #1280.
Run server locally with and without ES.
If visibility database is not configured and `system.advancedVisibilityWritingMode` is changed to `off` while server is running, it will lead to unpredictable behaviour.
No.
> Skip visibility database validation if advanced visibility is enabled

- common/metrics/defs.go
- service/history/handler.go
- service/history/historyEngine.go
- service/history/workflowTaskHandler.go
* Fix double metrics emission for history service RecordActivityTaskHeartbeat API
* Fix double metrics emission for history service GetMutableState API
* Fix double metrics emission for history service PollMutableState API
* Fix double metrics emission for history service DescribeWorkflowExecution API
* Fix double metrics emission for history service SignalWorkflowExecution API
* Fix double metrics emission for history service SignalWithStartWorkflowExecution API
* Fix double metrics emission for history service RemoveSignalMutableState API
* Fix double metrics emission for history service TerminateWorkflowExecution API
* Fix double metrics emission for history service ResetWorkflowExecution API
* Fix double metrics emission for history service QueryWorkflow API
* Fix …
> Fix history service metrics double emission issue

- service/history/workflowResetter.go
- service/history/workflowResetter_test.go
* Override activity schedule time to reset time
**Why?**
Valid activities after workflow reset should be assigned with `now` schedule time, not time from activity schedule event, which can be long time ago.
New tests
N/A
No
> Fix reset workflow pending activity schedule time

- common/config/config.go
- common/config/elasticsearch.go
- common/config/persistence.go
- common/persistence/client/factory.go
- config/development_es.yaml
- config/development_mysql-es.yaml
- go.mod
- go.sum
Disable visibility config validation if advanced visibility is configured.
**Why?**
Disable validation of the config when it is not used. Also added some extra validation for advanced visibility.
Manually.
No risks.
Maybe.
> Disable visibility config validation if advanced visibility is configured

- service/history/historyEngine.go
- service/history/workflowTaskHandlerCallbacks.go
* Do not persist to DB when resetting sticky task queue
* Use updateWorkflowExecutionWithAction instead of updateWorkflowExecution
* Rename updateWorkflowExecutionWithAction to updateWorkflowExecution
**Why?**
Reduce unnecessary DB write
Existing tests
N/A
No
> Do not persist to DB when resetting sticky task queue

- client/admin/metricClient.go
- common/cache/namespaceCache_test.go
- common/log/tag/tags.go
- common/log/tag/values.go
- common/metrics/defs.go
- common/persistence/search_attributes_manager.go
- common/resource/bootstrapParams.go
- common/resource/resource.go
- common/resource/resourceImpl.go
- common/resource/resourceTest.go
- common/searchattribute/search_attirbute.go
- common/searchattribute/search_attribute_mock.go
- common/searchattribute/search_attribute_test.go
- host/onebox.go
- service/frontend/adminHandler.go
- service/frontend/service.go
- service/history/service.go
- service/matching/service.go
- service/worker/addsearchattributes/addsearchattributes.go
- service/worker/addsearchattributes/workflow.go
- service/worker/service.go
Add `addsearchattributes` worker and corresponding workflow.
**Why?**
New way to add search attributes to the system. `addsearchattributes` workflow perform 3 steps:
1. Modify ES schema,
2. Wait for ES schema to be applied,
3. Add new search attribute to cluster metadata to be known by the system.
Run manually.
No risks.
No.
> Add "addsearchattributes" worker

- common/rpc/encryption/localStoreCertProvider.go
- common/rpc/encryption/localStorePerHostCertProviderMap.go
- common/rpc/encryption/localStoreTlsProvider.go
- common/rpc/encryption/testDynamicCertProvider.go
- common/rpc/encryption/tlsFactory.go
- common/rpc/test/rpc_localstore_tls_test.go
- temporal/server.go
Replaced instantiations of new logger in TLS provider code with passing it all the way from server options.
**Why?**
Multiple logger instances create undesirable effects when used concurrently.
Unit tests
No risk
No
> Pass logger from server options instead of calling log.NewDefaultLogger()

- Makefile
- go.mod
- go.sum
Update `jmoiron/sqlx` to the latest version 1.3.4
**Why?**
Blocking bug was fixed in https://github.com/jmoiron/sqlx/issues/701. No need to pin `sqlx` anymore.
Another bugs in new `sqlx` dependency.
No.
> Update jmoiron/sqlx to the latest version 1.3.4

- host/testcluster.go
- schema/elasticsearch/v6/visibility/index_template.json
- schema/elasticsearch/v7/visibility/index_template.json
Remove `Custom*Field` search attributes from index template.
**Why?**
In #1540 `Custom*Field`s were removed from dynamic config but not from index template itself.
N/A
No risks.
No.
> Remove Custom*Field search attributes from index template

- service/history/historyEngine.go
- service/history/historyEngine_test.go
* Dedup signal request ID before checking workflow mutability, in case workflow is signaled by finished
**Why?**
Business logic should check request ID for deduping purpose first.
N/A
N/A
No
> Properly dedup signal request ID

- common/persistence/executionStore.go
* Properly propagate LastFirstEventTxnId when doing serialization / deserialization to / from DB
**Why?**
Value not copy pasted
N/A
N/A
No
> Fix LastFirstEventTxnId not being properly propagated to DB

- Dockerfile
Use `ONBUILD` in `Dockerfile` for develop image.
**Why?**
To run `apk` only when develop image build is explicitly requested: https://docs.docker.com/engine/reference/builder/#onbuild.
Build image locally.
No risks.
No.
> Use ONBUILD in Dockerfile for develop image

- common/persistence/cassandra/cassandraQueue.go
- common/persistence/sql/queue.go
- service/frontend/adminHandler.go
- service/worker/replicator/namespace_replication_message_processor.go
- service/worker/replicator/replicator.go
* Correctly set the cluster name in replication namespace request
**Why?**
Bugfix, ref: https://github.com/uber/cadence/pull/4212
N/A
N/A
No
> Fix issue that namespace replication name is not set in req

- common/persistence/serialization/serializer.go
- common/persistence/serialization/serializer_test.go
- go.mod
- go.sum
Added a new interface Serializer that contains all methods defined in PayloadSerializer and methods defined in common/persistence/seraliazation/blob.go.
**Why?**
We want to move all seralization/deseralization logic to the layer above persistence. The data layer will then use this new interface to do seralization/deseralization, and persistence layer will only deal with DataBlob. This will enforce abstract layering. Follow up PRs will convert existing persistence layer code to avoid doing seralization/deseralization.
Also related to #1531 
This is new separated code that is not hooked up with system yet. Tested in unit test.
No.
No.
> Merge serialization methods into new Serializer

- tools/cli/defs.go
Fix tctl visibility timeout to 10s.
**Why?**
Wrongly set it to 10ns in #1571.
Run `tctl` manually.
No risks.
No.
> Fix tctl visibility timeout to 10s

- common/persistence/elasticsearch/client/client_v7.go
Add `Attr` properties to Elasticsearch `GetMapping` API.
**Why?**
Because we are releasing the current version of search attributes storage which uses `Attr` prefix for custom search attributes.
Run manually.
No risks.
No.
> Add Attr properties to Elasticsearch GetMapping API

- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/client/factory.go
- common/persistence/persistenceInterface.go
- common/persistence/shard_manager.go
- common/persistence/sql/shard.go
Separate ShardManager and ShardStore
**Why?**
Clear separation of persistence layering. Move serialization / deserialization to ShardManager layer. ShardStore only deal with blob and handle storage layer business. 
Unit test. Also manually test to make sure temporal server still function for a simple workflow.
Moderate
No
> Refactor ShardManager

- service/frontend/workflowHandler_test.go
- tools/cli/flags.go
- tools/cli/namespaceCommands.go
- tools/cli/namespaceUtils.go
Removed CLI flags for security tokens.
**Why?**
They aren't actually used anywhere and only confuse users.
Unit tests.
I don't see any.
No.
> Remove CLI flags for security tokens

- common/metrics/opentelemetery_reporter.go
Opentelemetry configuration requires listen address.
**Why?**
We ignored listen address prior.
local test/auto tests
N/A
yes
> Fix metrics listen address

- common/persistence/cassandra/cassandraPersistenceTest.go
- common/persistence/cassandra/factory.go
- common/persistence/cassandra/version_checker.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/query.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go
- common/persistence/tests/cassandra_test.go
- tests/integration/cassandra_test.go
- tools/cassandra/cqlclient.go
- tools/cli/adminCommands.go
Adds additional logging on GoCQL session refresh attempts, failures and successes. This will help us diagnose instances where we've seen Temporal unable to re-establish a connection to a rolled Cassandra cluster by giving us more logging information. This is a low-risk change as it is just adding more logging.
> Emits warning/error logs when Temporal tries/fails to establish a new GoCQL session

- common/dynamicconfig/constants.go
- service/matching/config.go
- service/matching/taskQueueManager.go
* Make sync match wait time configurable, dynamic config key: `matching.syncMatchWaitDuration`
* Remove unused MatchingEnableSyncMatch dynamic config since sync match should always be enabled
**Why?**
Make sync match wait time configurable
N/A
N/A
N/A
> Make sync match wait time configurable

- common/metrics/defs.go
- common/rpc/interceptor/telemetry.go
- service/matching/matchingEngine.go
- service/matching/taskQueueManager.go
* Split ServiceErrContextTimeoutCounter metrics into ServiceErrContextTimeoutCounter and ServiceErrContextCancelledCounter
* ServiceErrContextCancelledCounter metrics indicates request being cancelled
* ServiceErrContextTimeoutCounter metrics indicates timeout
**Why?**
Use dedicated metrics for dedicated error.
Matching to matching task forwarding will return `*serviceerror.Canceled` which will emit `ServiceErrContextCancelledCounter` metrics
ref: https://github.com/temporalio/temporal/blob/v1.10.2/service/matching/taskQueueManager.go#L129
N/A
N/A
N/A
> Emit dedicated metrics for context cancelled

- docker/auto-setup.sh
Fix auto-setup.sh for PostgreSQL. Extra check added.
**Why?**
PostgreSQL container automatically creates a database with `POSTGRES_USER` name. Another attempt to create this database fails the `auto-setup.sh` script.
Closes #1613.
Built image locally and run it with docker-compose.
No risks.
Partially. Worth to pick it up for the next patch release but doesn't worth to create patch release with just this change.
> Fix auto-setup.sh for PostgreSQL

- common/persistence/elasticsearch/visibility_store.go
- host/testdata/es_v7_index_template.json
- service/frontend/workflowHandler.go
Add minimum date validation on both front end and persistence level.
**Why?**
Without this validation empty dates (`time.Time{}`) cause Elasticsearch to fail the query. `date_nanos` doesn't support dates bellow Unix epoch.
Existing tests and manual queries.
No risks.
No.
> Add minimum date validation

- common/metrics/defs.go
- common/persistence/elasticsearch/visibility_store.go
Fix Elasticsearch metrics and memo encoding.
**Why?**
ES metrics definitions were places incorrectly and didn't properly work for "read" path. Also memo is returned as `string` not `[]byte` and require custom `base64` decoding.
Manually.
No risks.
No.
> Fix Elasticsearch metrics and memo encoding

- common/persistence/elasticsearch/client/client_v7.go
- common/searchattribute/search_attirbute.go
- common/searchattribute/search_attribute_test.go
- host/elasticsearch_test.go
- host/testdata/es_v6_index_template.json
- host/testdata/es_v7_index_template.json
Use `scaled_float` instead of `double` for `Double` search attributes.
**Why?**
`scaled_float` is more suitable for search fields.
Modified integration test.
No risks.
No.
> Use scaled_float instead of double for Double search attributes

- common/persistence/elasticsearch/visibility_store.go
- common/persistence/elasticsearch/visibility_store_read_test.go
- common/persistence/elasticsearch/visibility_store_write_test.go
- common/searchattribute/defs.go
- host/testdata/es_v6_index_template.json
- host/testdata/es_v7_index_template.json
- schema/elasticsearch/visibility/index_template_v6.json
- schema/elasticsearch/visibility/index_template_v7.json
- schema/elasticsearch/visibility/versioned/v1/index_template_v6.json
- schema/elasticsearch/visibility/versioned/v1/index_template_v7.json
- schema/elasticsearch/visibility/versioned/v1/reindex.painless
Convert Elasticsearch `ExecutionStatus` field to `keyword` data type instead of `long`.
**Why?**
To support queries like `ExecutionStatus = 'Completed'` and improve internal index structure.
New and existing tests.
Some queries with `ExecutionStatus` might stop to work. Also if someone uses Elasticsearch directly, they need to modify queries accordinally.
No.
> Convert Elasticsearch ExecutionStatus field to keyword

- common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go
Enabling a Reconnection policy will enable better resiliency in the event that Cassandra nodes happen to churn for a given cluster. We have seen situations where nodes churned, and the only way to recover Temporal was by initiating a reboot. This should address this.
Validated change in a deployed test environment. This is a low-risk change.
> Sets Reconnection policy on gocql.ClusterObject

- common/rpc/grpc.go
- common/rpc/rpc.go
- common/rpc/test/rpc_common_test.go
- host/integrationbase.go
- host/onebox.go
- service/matching/service.go
This PR adds a 10-second keep-alive between the frontend and history/matching services. This will enable a request on a severed connection to fail more quickly so that it can be retried, therefore reducing recovery time if one of those services recycles.
This is a very low-risk change that is automatically validated via unit/integration testing
> Adds keep-alive to gRPC connections between the frontend and history/matching services

- temporal/server.go
nil check reporters when stopping
**Why?**
The configuration allows these to be optional. https://github.com/temporalio/temporal/blob/3c427e6a2d5e7bcdda5868f379a26f6eb578871f/temporal/server.go#L177-L180
If they were not set, I was getting a panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d54ba7]
goroutine 1 [running]:
go.temporal.io/server/temporal.(*Server).Stop(0xc0004b4280)
/home/jaym/workspace/godev/pkg/mod/go.temporal.io/server@v1.10.2/temporal/server.go:254 +0x1c7
go.temporal.io/server/temporal.(*Server).Start(0xc0004b4280, 0xc0004b4280, 0x3)
/home/jaym/workspace/godev/pkg/mod/go.temporal.io/server@v1.10.2/temporal/server.go:229 +0xf7e
...
```
**How did you test …
> nil check reporters when stopping

- common/persistence/elasticsearch/visibility_store.go
- common/persistence/elasticsearch/visibility_store_read_test.go
- common/searchattribute/defs.go
- common/searchattribute/encode.go
- common/searchattribute/name_type_map.go
- common/searchattribute/name_type_map_test.go
- common/searchattribute/search_attirbute.go
- common/searchattribute/stringify.go
- common/searchattribute/validator.go
- common/searchattribute/validator_test.go
- schema/elasticsearch/visibility/versioned/v1/reindex.sh
- service/frontend/adminHandler.go
- tools/cli/workflowBatchCommands.go
- Refactor search attributes `GetType` method.
- Fix reserved search attribute name validation logic
- Fix `reindex.sh`
**Why?**
`GetType` shouldn't use system search attributes to check custom search attributes.
No risks.
No.
> Refactor search attributes GetType method

- common/authorization/default_jwt_claim_mapper_test.go
- common/authorization/default_token_key_provider.go
Fixed typo in encryption algorithm name "ec256" -> "es256".
**Why?**
To support elliptic curves.
Fixes #1662.
None
Yes
> Fix typo in encryption algorithm name ec256 -> es256

- Makefile
Add optional arguments to make schema.
**Why?**
Make it easier to create different keyspaces / dbs names.
Run locally with `make install-schema` verify temporal and temporal_visibility keyspaces are created.
Run with `make install-schema TEMPORAL_DB=temporal2 VISIBILITY_DB=temporal_visibility2` and verify temporal2 and temporal_visibility2 is created.
No.
No.
> Add optional args for DB names to install schema

- cmd/tools/cli/plugins/authorization/main.go
The plugin is now set to use the configured provider.
Previously the provider configuration was being ignored as we were using an empty provider rather than the one we'd configured.
> Fix to use the configured token.

- docker/auto-setup.sh
- tools/cli/admin.go
- tools/cli/admin_cluster_search_attributes_commands.go
- tools/cli/app_test.go
- tools/cli/flags.go
Modify add-search-attributes tctl command to add only missing search attributes.
**Why?**
There are scenarios (such as `auto-setup.sh`) when only missing attributes should be added to the cluster.
Run locally.
No risks.
No.
> Modify add-search-attributes tctl command to add only missing search attributes 

- service/matching/matcher.go
Add metrics logging for TaskQueue task forwarding error.
**Why?**
We defined this metrics, but was never used. This metrics is useful to identify if task queue has not-enough-poller issue.
N/A
No.
No.
> Add metrics logging for forward error

- service/matching/matchingEngine.go
- service/matching/matchingEngine_test.go
- service/matching/taskQueueManager.go
- service/matching/taskQueueManager_test.go
- service/matching/taskReader.go
- service/matching/taskWriter.go
* Enforce daemon coroutine at most once start / stop logic within matching engine
* Enforce daemon coroutine at most once start / stop logic within task queue manager
* Enforce daemon coroutine at most once start / stop logic within task queue reader
* Enforce daemon coroutine at most once start / stop logic within task queue writer
**Why?**
Better guarantee
Existing tests
N/A
No
> Enforce daemon at most once start / stop logic within matching service

- service/matching/liveness.go
- service/matching/liveness_test.go
- service/matching/matchingEngine_test.go
- service/matching/taskQueueManager.go
- service/matching/taskQueueManager_test.go
- service/matching/taskReader.go
* Mark liveness when adding new tasks from history service
* Mark liveness when polling tasks from frontend service
* Unit test
**Why?**
Try to guarantee to unload a task queue if not new tasks added && no poller polling
New tests && manual tests
N/A
No
> Seperate liveness of task queue into a dedicated entity

- common/persistence/sql/sqlplugin/mysql/dsn_test.go
- common/persistence/sql/sqlplugin/mysql/plugin.go
* Use mysql.Config for mysql connection string management
* Set mysql.Config.RejectReadOnly = true in case mysql encounters automatic failover event
**Why?**
Do not use read only mysql instance
Close #1703
Existing tests && CICD
N/A
No
> Use mysql.Config for mysql connection string management

- common/metrics/defs.go
- common/persistence/elasticsearch/processor.go
- common/persistence/elasticsearch/processor_mock.go
- common/persistence/elasticsearch/processor_test.go
- common/persistence/elasticsearch/visibility_store.go
- common/persistence/elasticsearch/visibility_store_write_test.go
Refactor Elasticsearch related metrics. Renamed them to have `elasticsearch` prefix and arranged other definitions.
Also moved ack channel creation into `processor.go`.
**Why?**
Unify metrics.
Modified existing and added new unit tests. Local canary run.
Few Elasticsearch metrics are renamed and dashboards need to be updated.
No.
> Refactor Elasticsearch metrics

- tools/cli/app_test.go
- tools/cli/factory.go
- tools/cli/util.go
- tools/cli/workflowCommands.go
tctl now uses an SDK client rather than a service client to start workflows.
**Why?**
Using the SDK client brings the tctl code more inline with standard way
for users to start workflows and makes it easier for contributors to
adjust tctl and make use of SDK features such as interceptors/context
propagation.
This will also be useful in future if we wish to provide more plugin
APIs to control the SDK client.
This also avoids using more complex code paths for parsing memo and
search attributes given that we can only be receiving untyped JSON
inputs from the command line anyway.
Tests were updated. Also manually tested error handling for invalid memo/search inputs.
No.
> Use an SDK client to start workflows

- service/history/historyEngine2_test.go
- service/history/shard/context_impl.go
- service/history/shard/context_util.go
* Check shard status guarantee shard not being used after close for following operations:
* CreateWorkflowExecution
* UpdateWorkflowExecution
* ConflictResolveWorkflowExecution
* AddTasks
* AppendHistoryEvents
* Rewrite error handling logic
* Remove unused range ID var within shard context
**Why?**
Guarantee do not reuse shard after shard close
Existing logic already set the range ID to -1 so DB CAS will fail, this PR add check prior to making DB call for better understanding
Existing tests & CICD
N/A
No
> Check shard status before workflow modification

- common/authorization/default_authorizer.go
- common/authorization/default_authorizer_test.go
- common/authorization/frontend_api.go
Added definitions of read-only APIs at namespace and global level.
Updated `defaultAuthorizer` to allow read-only calls through if the caller has Reader permissions.
Custom authorizer plugins can leverage the same `IsReadOnlyNamespaceAPI` and `IsReadOnlyGlobalAPI` helper methods
Fixes #1688.
**Why?**
To support read-only access to Temporal.
Unit tests
I don't see any
No
> Add support for authorization of read-only frontend calls

- common/config/config.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go
This change adds a configuration (default: false) that instructs the gocql client to only connect using the supplied hosts.
For certain Cassandra deployments, using the supplied hosts to connect is the optimal approach vs looking up all the hosts from the cluster's system.peers table. This can reduce the time to establish a cql session by an order of magnitude.
Tested against a private deployment. No risk as the default behavior is not changed - the user must explicitly opt into this.
> Adds configuration flag to set DisableInitialHostLookup on gocql client driver

- common/persistence/cassandra/errors.go
* Currectly handle edge case if `db_version` is not set during error extraction
**Why?**
Correctly handle if `db_version` is not set
Existing tests
N/A
No
> Fix cassandra error handling edge case

- schema/elasticsearch/visibility/versioned/v1/reindex.sh
- service/frontend/adminHandler.go
Add `ES_VERSION` parameter to `reindex.sh`.
**Why?**
`date` type needs to be converted to `date_nanos` for Elasticsearch 7 when migrating custom search attributes.
`double` type always needs to be converted to `scaled_float` when migrating custom search attributes.
Run manually.
No risks.
No.
> Add ES_VERSION parameter to reindex.sh

- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/cassandra/cassandraPersistenceUtil.go
- service/history/workflow/mutable_state_impl.go
* Old version of mutable state `db_record_version` will be `null` on Cassandra, but gocql `MapScan` function will return `0` instead of `null`. This makes conditional update on `db_record_version` impossible due to business logic unable to tell the difference between `null` vs `0`. Solution is to continue using CAS on `next_event_id` for old version of mutable state; using CAS on `db_record_version` for new version of mutable state.
**Why?**
See above
Existing tests & manual tests
N/A
No
> Handle mutable state version migration edge case

- common/rpc/grpc.go
- common/rpc/rpc.go
- common/rpc/test/rpc_common_test.go
- host/integrationbase.go
- host/onebox.go
Remove internode keep alive pings.
**Why?**
Internode pings were added in #1654. Unfortunately 10 seconds interval is very aggressive and server part on both matching and history services are not configured properly (minimum allowed interval is 5 minutes by default).
Run locally.
No risks.
No.
> Remove internode keep alive pings

- schema/elasticsearch/visibility/versioned/v0/index_template_v6.json
- schema/elasticsearch/visibility/versioned/v0/index_template_v7.json
- schema/elasticsearch/visibility/versioned/v1/index_template_v6.json
- schema/elasticsearch/visibility/versioned/v1/index_template_v7.json
Visibility schema templates used in Elasticsearch.
**Why?**
- Since Elasticsearch 7.x it is advised to use one primary shard for performance reasons. It is also advisable in previous Elasticsearch versions. In general, default shard 5 was resulting in shard explosion and cluster collapse especially when using shared Elasticsearch cluster.
- Set auto expand replicas from 0 to 2, this allows to set up system even on single node and it will automatically adjust itself is more nodes are available.
We use our custom Temporal `admin-tools` container with custom template.
Tested under Elasticsearch 7.9.x only, but in general auto-expand was tested on other datasets under Elasticsearch 6.x as well.
- does not work well with already …
> Elasticsearch template tuning

- schema/elasticsearch/visibility/versioned/v1/reindex.sh
- schema/elasticsearch/visibility/versioned/v1/rollback.sh
Add `SLICES_COUNT` param and failure report to `reindex.sh`.
**Why?**
On big clusters with large number of shards `slices=auto` might not work properly.
Run locally and on large cluster.
No risks.
No.
> Add SLICES_COUNT param and failure report to reindex.sh

- service/history/transferQueueTaskExecutorBase.go
Default timeout for background task processing.
**Why?**
When history service has large latency, the short timeout and retry policy would cause transfer queue to keep initiate more and more requests causing them to pile up on history service side.
Deployed to test cluster where we have this issue, and see the issue resolved with the fix.
No.
No.
> Set longer task timeout to avoid stampede on history service

- common/persistence/elasticsearch/client/client.go
- common/persistence/elasticsearch/client/client_mock.go
- common/persistence/elasticsearch/client/client_v6.go
- common/persistence/elasticsearch/client/client_v7.go
- common/persistence/elasticsearch/visibility_store.go
- common/persistence/elasticsearch/visibility_store_read_test.go
Use [point in time](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/point-in-time-api.html) instead of [scroll](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/paginate-search-results.html#scroll-search-results) for `ScanWorkflowExecutions` API.
**Why?**
Recommendations for Elasticsearch v7 has changed:
> We no longer recommend using the scroll API for deep pagination. If you need to preserve the index state while paging through more than 10,000 hits, use the search_after parameter with a point in time (PIT).
PIT consumes less Elasticsearch resources and has better limitations.
Elasticsearch v6 still uses scroll.
Existing unit and integration tests.
No risks.
No.
> Use PIT instead of scroll for Scan API

- common/persistence/cassandra/cassandraHistoryPersistence.go
- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/cassandra/factory.go
- common/persistence/client/factory.go
- common/persistence/execution_manager.go
- common/persistence/history_manager.go
- common/persistence/mock/store_mock.go
- common/persistence/persistenceInterface.go
- common/persistence/sql/execution.go
- common/persistence/sql/execution_tasks.go
- common/persistence/sql/execution_util.go
- common/persistence/sql/factory.go
- common/persistence/sql/history_store.go
- common/persistence/tests/cassandra_test.go
- common/persistence/tests/history_store_test.go
- common/persistence/tests/mysql_test.go
- common/persistence/tests/postgresql_test.go
- common/persistence/visibility/sql/visibility_store.go
- tools/cli/adminCommands.go
- tools/cli/adminDBCleanCommand.go
- tools/cli/adminDBScanCommand.go
This is part 1 of a long series changes to unify the persistence interface for workflow.
WorkflowStore is combined interfaces of ExecutionStore and HistoryStore.
Expect no behavior change in this PR.
**Why?**
The operations to append history, update mutable state and add tasks are the result of one workflow update.
These operations should be treated as one operation at upper layer. The current implementation is greatly
influenced by the fact that Cassandra does not support transaction across multiple tables. 
Follow up changes will combine ExecutionManager and HistoryManager into WorkflowManager.
And the operation to create/update workflow will be combined with append history.
Then will wire the combined create/update with upper layer.
Unit …
> WorkflowStore interface

- service/worker/parentclosepolicy/processor.go
- service/worker/scanner/scanner.go
- service/worker/scanner/workflow.go
* Use 8 for activity / workflow task poller count instead of default 2
**Why?**
2 as poller count is probably only suitable for dev env
N/A
N/A
No
> Adjust system worker poller number

- common/persistence/visibility/elasticsearch/client/client_v7.go
This MR disables sniffing on the Elasticsearch Client (version 7) used by CLI commands.
This is needed for Elasticsearch Servers not supporting sniffing, eg. AWS Elasticsearch Service.
See the following issue for more details:
* https://github.com/temporalio/temporal/issues/621
* https://github.com/temporalio/temporal/issues/551
**Why?**
Without this setting you can't use the CLI commands using AWS Elasticsearch service eg.
```
$ TEMPORAL_CLI_SHOW_STACKS=1 tctl admin es catIndex --url https://my-temporal-1234567.eu-central-1.es.amazonaws.com:443/ --version v7
Error: Unable to create Elasticsearch client
Error Details: context deadline exceeded
Stack trace:
....
```
This was verified by compiling tctl with this change and running the command …
> Disable sniffing on ES7 client used in CLI

- tools/cli/factory.go
- tools/cli/factory_test.go
- Disallows fetching CA Cert over HTTP. Returns an error message suggesting to provide HTTPS 
- adds unit test to cover HTTP URLs
**Why?**
Addressing security request to only support HTTPS https://github.com/temporalio/temporal/pull/1773#discussion_r681205844
unit tests (including new one)
no risk (the feature is not yet released)
no
> Disallow fetching CA cert over HTTP in tctl commands

- docker/config_template.yaml
Exposes the TLS `RefreshInterval` & `ExpirationChecks` configurations via environment variable. Fixes https://github.com/temporalio/temporal/issues/1799
**Why?**
So that users can set this from environment variable without needing to vendor the template on their end.
Tested it by running a Temporal server, with this branch locally, and updating the certificate being used in the background. 
* Should not break existing behaviour. Might not be able to reliably set these variables for hot reloading certificates.
* It could conflict with this, but I am uncertain how this works: https://github.com/temporalio/temporal/blob/d7e24101f9581eef4128ee600952acd431f8326d/docker/config_template.yaml#L221
No
> Expose TLS RefreshInterval & ExpirationChecks via env var

- tools/cli/app_test.go
- tools/cli/defs.go
- tools/cli/util.go
- tools/cli/workflowCommands.go
Added top level retries for list/count workflow APIs in tctl.
**Why?**
Our pipelines are failing with a following error:
```
++ kubectl exec -it services/temporaltest-admintools -- bash -c 'tctl --ns canary-java wf count -q ExecutionStatus=3'
command terminated with exit code 1
+ FAILED_COUNT='Error: Failed to count workflow.
Error Details: context deadline exceeded
```
After deeper inspection it turned out that this error happens because our on-prem ES pod hangs and request times out. In the meantime new ES master is elected and subsequent requests succeed. Unfortunately this issue can not be handled at the level of gRPC retry built into the client as a single API call attempt uses entire context deadline interval (because request hangs) leaving no time for retries. …
> Add retries for tctl visibility APIs

- common/persistence/nosql/nosqlplugin/cassandra/gocql/session.go
* Start a new goroutine when closing gocql session
**Why?**
gocql session.Close is not reliable, sometimes there can be deadlock issue, details see below
1. stack trace proving that gocql session.Close is stuck
```bash
goroutine 700966 [chan send, 61 minutes]:
github.com/gocql/gocql.(*controlConn).close(0xc0026b8c80)
/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20210621133426-d83b80dfb480/control.go:488 +0xbb
github.com/gocql/gocql.(*Session).Close(0xc0015c2a80)
/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20210621133426-d83b80dfb480/session.go:464 +0x15f
go.temporal.io/server/common/persistence/nosql/nosqlplugin/cassandra/gocql.(*session).refresh(0xc001daeb60)
/go/pkg/mod/go.temporal.io/server@v1.11.1-0.20210801055905-ea5caf1c1ea1/common/persistence/nosql/nosqlplugin/cassandra …
```
> Handle unreliable gocql close function stuck issue

- service/matching/ackManager.go
- service/matching/matchingEngine_test.go
- service/matching/tasks.go
- service/matching/tasks_test.go
* Sort matching service task IDs before advancing ack level
**Why?**
When lots of ownership movement happens to matching task queue, task IDs allocated can be sparse, e.g. millions of numbers away. This condition can cost lot of CPU cycles when advancing task ack level. 
* Short term, sort task IDs each time before advancing ack level
* If no much backlog -> matching service is not busy, additional cost due to sort can be acceptable
* If no lots of backlog -> matching service is busy, additional cost due to sort << looping
* Long term, logic to advance ack level should be handled by a dedicated coroutine
New tests & existing tests
N/A
No
> Optimize matching ack manager loop perf

- service/history/shard/context_impl.go
- service/matching/matchingEngine.go
- service/matching/matchingEngine_test.go
- service/matching/taskQueueManager.go
- service/matching/taskQueueManager_test.go
Move tqm.Start() out of global lock scope
**Why?**
The tqm.Start() would try to renew lease which could fail and it would retry. The process could take more than 30s.
Doing this within global taskQueueLock would block entire matching service.
Manual test with a setup that I can fail some task queue renew.
No.
No.
> Fix TaskQueueLock starvation

- tools/cli/flags.go
Adds support for the following flag:
--tls_server_name value          DB tls server name (tls must be enabled)
This is needed if we want to run tctl admin commands against a DB with TLS enabled where we still want host verification but the certificate subject and dns entry are not aligned.
> Adds flag to tctl db-based commands to override TLS ServerName setting

- service/history/workflowResetter.go
- service/history/workflowResetter_test.go
- service/matching/taskQueueManager_test.go
* Only reapply current workflow events if current workflow is part of continue as new chain
* Fix matching service unit tests
**Why?**
Workflow reset should only re-apply events if events are part of the continue as new chain
New tests
N/A
No
> Fix workflow reset reapply current workflow events behavior

- tools/cli/taskQueueCommands.go
* Do not exit CLI if task queue has no poller
**Why?**
This is not an error case
Manual tests
Before:
```bash
tctl --ns canary taskqueue describe --tq canary-task-queue                                    
Error: No poller for taskqueue: canary-task-queue
```
After:
```bash
./tctl --ns canary taskqueue describe --tq canary-task-queue
WORKFLOW POLLER IDENTITY | LAST ACCESS TIME
```
N/A
No
> Do not exit CLI if task queue has no poller

- Dockerfile
Added the `tctl-authorization-plugin` to the docker images that currently contain the `tctl`binary.
To be able to easily enable the authorization plugin using just the environment variable.
I have tested this locally
None, other that potentially unused code beeing shipped.
No
> Add tctl-authorization-plugin to docker images (#1832)

- service/history/workflow/mutable_state_impl.go
Tweak the order of initializing fields so that the backfill `ExecutionTime` logic works correctly.
**Why?**
It was calling `GetStartEvent` before initializing `executionState`, which contains the run id. Without the run id, the event cache was using a bad key and confusing events from different runs.
Mostly manual testing and observation.
This only affects the `ExecutionTime` backfill logic, so shouldn't affect anything that doesn't depend on that.
yes
> Fix ExecutionTime backfill by changing init order

- service/history/events/cache.go
- service/history/events/cache_test.go
Logs if any id that goes into the event cache key are missing/invalid. Don't allow events to be cached under those keys, but allow `GetEvent` to return them.
**Why?**
We found one site where this happened (#1836) and would like to identify any others.
Ran unit tests and integration tests with `Warn` changed to `Fatal` to ensure tests would fail if it hit.
New unit test for change in behavior.
If there is buggy code calling the event cache with invalid ids, this will cause more lookups since it will stop caching those events. But it shouldn't make the code any more buggy, only reveal bugs.
> Validate ids in event cache

- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/dataInterfaces.go
- common/persistence/execution_manager.go
- common/persistence/history_manager.go
- common/persistence/persistence-tests/persistenceTestBase.go
- common/persistence/persistenceInterface.go
- common/persistence/sql/execution.go
- service/history/historyEngine2_test.go
- service/history/historyEngine3_eventsv2_test.go
- service/history/historyEngine_test.go
- service/history/timerQueueActiveTaskExecutor_test.go
- service/history/timerQueueStandbyTaskExecutor_test.go
- service/history/transferQueueActiveTaskExecutor_test.go
- service/history/workflow/transaction_impl.go
Merge AppendHistory into UpdateWorkflow API on data store layer.
**Why?**
Simplify the persistence API, and make it possible to optimize perf where AppendHistory and UpdateWorkflow can be done in one transection.
Existing unit tests and integration tests.
No
No.
> UpdateWorkflow transaction to include append history

- common/persistence/persistence-tests/persistenceTestBase.go
`persistenceTestBase#newTestBase `is exported as `#NewTestBaseForCluster`
**Why?**
For external persistence implementations to reuse `persistenceTestBase`. Currently `persistenceTestBase` exposes only methods supporting the creation of `TestBase` for only existing standard persistence implementations.
None
No
> Allow external persistence implementations to reuse persistenceTestBase by exporting a factory method accepting PersistenceTestCluster

- common/util.go
- host/taskpoller.go
- service/history/transferQueueActiveTaskExecutor.go
We add "context canceled" as a blacklist for determining if an error is transient or not.
We are proposing this change because otherwise a single poll getting canceled results in 7x the attempts with an already canceled context.
Verified on one-box.
Could be risky as there may be cases where we DO want to retry on a context canceled error (however, we already don't retry on context deadline exceeded, so why are we doing it on context cancelled)?
Not a hotfix. Main impact will be to reduce resource usage for non-retryable errors and fix up metrics reporting.
> Fixes bug where intra-node client is doing retries even if the error is context cancelled

- common/persistence/client/factory.go
Add metrics client to AbstractDataStoreFactory.NewFactory(). 
**Why?**
So custom data store could emit metrics as needed.
No
No
> Add metrics client to custom data store factory

- common/metrics/defs.go
- common/persistence/visibility/elasticsearch/visibility_manager.go
- common/persistence/visibility/elasticsearch/visibility_store.go
- common/persistence/visibility/elasticsearch/visibility_store_read_test.go
- host/testcluster.go
Change `parseESDoc` and `generateESDoc` to return error instead of logging.
**Why?**
More errors is about to be added and they can't be just logged but needs to be returned. Changing only existing ones in this PR.
Exiting tests.
Previously minor errors in Elasticsearch document was just logged but incomplete data was returned by visibility read API. In some cases this incomplete data might be good enough and users might not even notice that there is an error without checking server logs and metrics. Now, any error in any field in any document will fail visibility API read request.
No.
> Change parseESDoc and generateESDoc to return error instead of logging

- common/searchattribute/validator.go
- common/searchattribute/validator_test.go
- service/history/commandChecker.go
- service/history/commandChecker_test.go
- service/history/historyEngine.go
Remove search attributes errors logs.
**Why?**
Search attributes validation errors are user errors which shouldn't go to server log. They are returned to the caller (as other validation errors) and caller can react appropriately.
No risks.
No.
> Remove search attributes errors logs

- service/history/historyEngine2_test.go
- service/history/workflow/mutable_state_impl.go
* Correctly set the in memory current version if workflow is finished
**Why?**
In case future logic use current version, [reference](https://github.com/uber/cadence/pull/4431)
N/A
N/A
No
> Correctly set current version if workflow is finished

- common/persistence/visibility/elasticsearch/query/converter.go
- common/persistence/visibility/elasticsearch/query/errors.go
- common/persistence/visibility/elasticsearch/query/interceptors.go
- common/persistence/visibility/elasticsearch/query_interceptors.go
- common/persistence/visibility/elasticsearch/visibility_store.go
- common/persistence/visibility/elasticsearch/visibility_store_read_test.go
- common/persistence/visibility/visibility_manager.go
- common/persistence/visibility/visibility_store.go
- common/resource/resourceImpl.go
- common/searchattribute/defs.go
- common/searchattribute/encode.go
- common/searchattribute/name_type_map.go
- common/searchattribute/validator.go
- service/frontend/workflowHandler.go
- service/frontend/workflowHandler_test.go
Refactor Elasticsearch visibility store:
1. Query converter returns `ConverterError` if query is invalid and pass through all other errors from interceptors.
2. Move query converter from visibility store level to `func` level.
3. Minor renames and bug fixes.
**Why?**
Prepare to add custom search attribute mapper interface.
No risks.
No.
> Refactor Elasticsearch visibility store

- common/backoff/retry.go
- common/backoff/retry_test.go
- internal/goro/goro.go
- internal/goro/goro_test.go
- service/matching/taskWriter.go
- Shift from using a raw channel for shutdown to a `*goro.Handle`, which can be safely shut down multiple times.
- Switch from `backoff.Retry` to `backoff.RetryContext` so that the initial loading of `taskWriter` read/write state from persistence is interruptible
**Why?**
- With the right concurrency, `taskWriter` can panic due to closing the internal shutdown channel twice
- The initial read/write state load could not be interrupted (i.e. did not pay attention to `taskWriter.Stop()`)
Unit tests for new code, existing unit tests for the matching package.
Concurrency so deadlocks, races.
Yes
> Fix TaskWriter panic when shutdown

- Dockerfile
- docker/base-images/base-server.Dockerfile
Remove `openssl` from base server image.
**Why?**
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3711
Build and run locally.
If someone uses `openssl` from server image to generate certificates, they need to install it manually now.
No because `openssl` is not used in any production code path.
> Remove openssl from base server image

- common/persistence/visibility/elasticsearch/processor.go
- common/persistence/visibility/elasticsearch/processor_test.go
- service/history/timerQueueTaskExecutorBase.go
Ack existing visibility task in case of duplicates. It was nack before.
Also changed order of operation while deleting workflow because delete from visibility is asynchronous anyway.
**Why?**
If visibility tasks are duplicated for some reason, nacking them leads to retris and more duplicates. Existing task should be acked instead, as if it is successfully processed. 
Fixed existing tests.
No risks.
No.
> Ack existing visibility task in case of duplicates

- common/metrics/defs.go
- common/persistence/visibility/elasticsearch/processor.go
- common/persistence/visibility/elasticsearch/processor_test.go
- Split `elasticsearch_bulk_processor_wait_latency` into `elasticsearch_bulk_processor_wait_add_latency` and `elasticsearch_bulk_processor_wait_start_latency`,
- In case of duplicates, acknowledge new instead of existing tasks. It actually doesn't matter, but might cause some concurrency problem.
**Why?**
Improve and analyze performance under high load.
Fixed exiting tests.
No risks.
No.
> Add metrics to bulk processor

- service/matching/matcher.go
* Correctly handle matching task queue rate / burst calculation
**Why?**
Previously, Cadence's rate limiter only support rate as int, this caused some rounding issue.
Temporal's version support rate as float.
N/A
N/A
N/A
> Fix match task queue rate calculation issue

- common/persistence/visibility/elasticsearch/query/converter.go
- common/persistence/visibility/elasticsearch/query/converter_test.go
- common/persistence/visibility/elasticsearch/visibility_store_read_test.go
- tools/cli/app_test.go
- tools/cli/flags.go
- tools/cli/workflowCommands.go
Remove `missing` keyword support in visibility queries.
**Why?**
`missing` support was deprecated in 1.12 release and is removed in 1.13. Use `ExecutionStatus="Running"` to filter only running workflows or `CloseTime is null` to filter workflows with missed field.
Queries which are still using `missing` keywords (like `CloseTime=missing`) will fail.
No.
> Remove missing keyword support in visibility queries

- common/persistence/visibility/elasticsearch/visibility_store_read_test.go
- common/searchattribute/mapper.go
- common/searchattribute/mapper_test.go
Ignore `InvalidArgument` error for unknown custom search attributes.
**Why?**
To support search attribute alias deletion.
No risks.
No.
> Ignore InvalidArgument error for unknown custom search attributes

- service/matching/matchingEngine.go
- service/matching/matchingEngine_test.go
- service/matching/taskQueueManager.go
- service/matching/taskWriter.go
Unload taskQueueManager by instance, not queue ID
**Why?**
Matching engine can incorrectly unload a taskQueueManager instance
because the fatal signals from a previous instance are still being
delivered and reference the same queue ID. To address we unload by
taskQueueManager object instance rather than simply by queue ID.
New unit test
Minimal - unload occurs in strictly _fewer_ cases
no
> Unload taskQueueManager by instance, not queue ID

- common/persistence/visibility/elasticsearch/client/client.go
- common/persistence/visibility/elasticsearch/client/client_mock.go
- common/persistence/visibility/elasticsearch/client/client_v6.go
- common/persistence/visibility/elasticsearch/client/client_v7.go
- common/persistence/visibility/elasticsearch/visibility_store.go
- common/persistence/visibility/elasticsearch/visibility_store_read_test.go
Use point in time with Elasticsearch v7 only if it is available.
**Why?**
It turned out that "point in time" APIs are not available in open source version of Elasticsearch: https://github.com/elastic/elasticsearch/issues/65906. Fall back to scroll APIs if PIT is not available.
Modified existing and added new tests.
No risks.
Yes.
> Use point in time with Elasticsearch v7 only if it is available

- service/history/timerQueueActiveTaskExecutor.go
* Remove deprecated code related to activity namespace ID
**Why?**
[Migration already years ago](https://github.com/temporalio/temporal/blame/469b4e6160feba262ea0c50e3bed6ea64836412b/service/history/workflow/mutable_state_impl.go#L1825)
N/A
No
No
> Remove dead code

- common/util.go
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
Updates the event blog size warning message text to be clearer
> Update event blob size warning message

- common/persistence/cassandra/cassandraPersistenceTest.go
Set longer timeout for integration tests.
**Why?**
Avoid flakiness of integration test due to timeout.
Integration tests.
No
No
> Set timeout for TestCluster

- common/persistence/persistenceInterface.go
- common/persistence/size.go
- common/persistence/size_util.go
* Add function to extract count / size info from
* InternalWorkflowSnapshot
* InternalWorkflowMutation
* InternalWorkflowMutableState
**Why?**
Existing size calculation util is [not accurate](https://github.com/temporalio/temporal/blob/v1.12.0/common/persistence/statsComputer.go#L180-L246)
Size / count calculation is missing some attributes, e.g. request cancel info
N/A
N/A
No
> Add persistence mutable state mutation / snapshot binary size util

- service/matching/matchingEngine.go
- service/matching/matchingEngine_test.go
- service/matching/taskQueueManager.go
Makes the logic in removeTaskQueueManager consistent with the update to
unloadQueue. I.e. remove a specific instance of taskQueueManager rather
than whatever instance happens to be associated with that taskQueueID at
the time.
**Why?**
A simplified version of a previous PR that was more aggressive in eliminating these calls but which is still being investigated as it does not pass integration testing
Existing unit & integration tests
Minimal - we remove TQM in fewer cases
No
> Remove taskQueueManager by instance rather than queue ID

- common/persistence/cassandra/cassandraClusterMetadata.go
- common/persistence/cassandra/cassandraHistoryPersistence.go
- common/persistence/cassandra/cassandraMetadataPersistenceV2.go
- common/persistence/cassandra/cassandraPersistence.go
- common/persistence/cassandra/cassandraQueue.go
- common/persistence/visibility/cassandra/visibility_store.go
- common/persistence/visibility/sql/visibility_store.go
- host/elasticsearch_test.go
- host/workflow_visibility_test.go
Always return `nil` value for `NextPageToken` if there are no more pages. Previously some implementation returned `nil`, some zero length slice.
**Why?**
For consistency between different persistence implementations.
Modified existing test.
If there are explicit checks for zero-length slice (w/o checking for `nil`/`null` first) in user code in other languages it will fail.
No.
> Always return nil value for NextPageToken if there are no more pages

- Makefile
- develop/buildkite/pipeline.yml
Ignore goveralls exit code.
**Why?**
Don't block the build in case if [coveralls.io](https://coveralls.io/) is down. `goveralls` doesn't report actual coverage status right away anyway so there is no point blocking build on its exit code.
Run locally.
No risks.
No.
> Ignore goveralls exit code

- tools/common/schema/handler.go
- tools/common/schema/handler_test.go
- tools/common/schema/setuptask.go
- tools/common/schema/types.go
- tools/common/schema/updatetask.go
Added a logger configuration option to the schema migration tool. This enables filtering and reformatting of migration logs.
**Why?**
The existing schema migration logs can be noisy, particularly when they are mixed in with test logs (as is the case in `temporalite`). This also makes it possible to output structured logs, which are typically easier to integrate with third party log aggregation services.
Validated by adding a local override for `go.temporal.io/server` in the go.mod of `temporalite` and running migrations against sqlite.
The logs produced by the schema tool now default to a different format. This format is determined by the `log.NewCLILogger()` function.
no
> Add custom logger option to schema tool

- common/dynamicconfig/constants.go
- service/matching/config.go
- service/matching/taskQueueManager.go
- service/matching/taskQueueManager_test.go
Make ResilientSyncMatch the default behavior
**Why?**
Continues to do some matching during persistence outages
This has been in the product behind a feature flag for several weeks. Has seen multiple flavors of persistence outages through scale testing.
No
> Make ResilientSyncMatch the default behavior

- common/searchattribute/manager.go
- common/searchattribute/manager_test.go
- common/searchattribute/name_type_map.go
Don't refresh search attributes cache if database is down.
**Why?**
Before `ApplyTypeMap()` could stop all workflow tasks for entire cluster in case Cassandra nodes hosting cluster metadata is down because it is called as part of `workflowHandler.getHistory()` which is part of `PollWorkflowTask` API call.
Added unit test and local run with main database container stopped.
No risks.
No.
> Don't refresh search attributes cache if database is down

- common/config/config.go
- common/resource/bootstrapParams.go
- temporal/server.go
Removed deprecated per-service metrics config.
Deprecation not see https://github.com/temporalio/temporal/releases/tag/v1.11.0
**Why?**
Remove deprecated code.
automated tests.
deprecated configuration will not work.
No
> Remove deprecated metrics config code as per release 1.11 note

- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Remove default page size from Elasticsearch visibility store.
**Why?**
Elasticsearch page size is set on a frontend so it shouldn't be set on store level. Also other stores don't have it.
No risks.
No.
> Remove default page size from Elasticsearch visibility store

- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Convert Elasticsearch `BadRequest` error to `Internal` error.
**Why?**
`BadRequest` returned from Elasticsearch when index name wrong or index mapping is misconfigured. It should be mapped to `serviceerror.Internal` not `serviceerror.Unavailable` error. `Internal` error won't be retried by future versions of SDK and `tctl`.
Closes #582.
New unit test.
No risks.
No.
> Convert Elasticsearch BadRequest error to InvalidArgument error

- common/persistence/visibility/store/elasticsearch/visibility_store.go
Set timeout (16 seconds) for all Elasticsearch read calls.
**Why?**
Closes #581.
Calls to Elasticsearch longer than 16 seconds will start to fail. But our RPC timeout is shorter so no real calls should be affected.
No.
> Set timeout for all Elasticsearch read calls

- common/namespace/cache.go
- common/namespace/cache_mock.go
- common/namespace/mutate.go
- common/namespace/namespacetest/mutate.go
- common/namespace/testconstructors.go
- service/frontend/dcRedirectionPolicy.go
- service/history/commandChecker.go
- service/history/historyEngine.go
- service/history/replicationTaskExecutor.go
- service/history/shard/context_impl.go
- service/history/taskAllocator.go
- service/history/taskPriorityAssigner.go
- service/history/taskPriorityAssigner_test.go
- service/history/workflow/context.go
Remove CacheEntry.GetReplicationConfig and fixups to dependent code for the same.
**Why?**
Part of a larger refactoring to make CacheEntry immutable by prohibiting
access to its internal NamespaceInfo, NamespaceConfig, and
NamespaceReplicationConfig.
No
> Remove CacheEntry.GetReplicationConfig

- common/namespace/cache.go
- service/frontend/workflowHandler.go
- service/history/historyEngine2_test.go
- service/history/historyEngine3_eventsv2_test.go
- service/history/historyEngine_test.go
- service/history/timerQueueTaskExecutorBase.go
- service/history/transferQueueActiveTaskExecutor.go
- service/history/transferQueueTaskExecutorBase.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/test_util.go
- service/history/workflow/util.go
- service/history/workflowTaskHandlerCallbacks.go
- tools/cli/workflowCommands.go
Remove namespace.CacheEntry.GetConfig()
**Why?**
Part of a larger refactoring to make CacheEntry immutable by prohibiting
access to its internal NamespaceInfo, NamespaceConfig, and
NamespaceReplicationConfig
No
> Remove namespace.CacheEntry.GetConfig()

- service/history/nDCActivityReplicator_test.go
- service/history/timerQueueActiveTaskExecutor_test.go
- service/history/workflow/cache.go
- service/history/workflowResetter_test.go
Simplify workflow.Cache interface
**Why?**
There is no need to expose the underline cache.Cache interface. They are only used by tests.
Simplify workflow.Cache interface to include only necessary methods so it is easier for different implementation.
Unit tests and integration tests.
No
No
> Remove cache.Cache from workflow.Cache

- common/searchattribute/mapper.go
- common/searchattribute/mapper_test.go
- common/searchattribute/validator_test.go
Improve mapper tests and comment message.
**Why?**
Adding more tests to emphasize importance of swallowing `serviceerror.InvalidArgument` error.
Adding more tests.
N/A
No.
> Improve mapper tests and comment message

- service/frontend/service.go
Default MaxConnectionAge to infinity. 
**Why?**
We have see several reports where user has lost connections for unknown reason. For example this post:
https://community.temporal.io/t/how-to-best-handle-mysterious-context-deadline-exceeded-502-errors/2689/4
Verify in debugger that the 0 value of MaxConnectionAge is overwrite by grpc
https://github.com/grpc/grpc-go/blob/adb21c46100568b95ab41e97e3b267923a0a92a0/internal/transport/http2_server.go#L217
No
No
> unlimited MaxConnectionAge

- tools/cli/app_test.go
- tools/cli/flags.go
- tools/cli/workflowCommands.go
Allows to set Workflow Run Timeout when starting a workflow from tctl
**Why?**
Allows to limit workflow run timeout (in addition to execution and task timeouts)
Added the flag in unit tests
Verified the run timeout is set (through UI) 
> Allow setting workflow run timeout in tctl

- common/persistence/visibility/store/elasticsearch/processor.go
- common/persistence/visibility/store/elasticsearch/processor_test.go
- common/persistence/visibility/store/elasticsearch/visibility_store.go
- service/history/configs/config.go
Fix `elasticsearch_bulk_processor_wait_add_latency` metric.
**Why?**
Bulk processor wait add time was incorrectly counted towards wait start time.
Run test tool locally.
No risks.
No.
> Fix elasticsearch_bulk_processor_wait_add_latency metric

- service/history/historyEngine.go
Use StartedIdentity as LastWorkerIdentity for PendingActivity if no retry.
**Why?**
DescribeWorkflow reports pending activity info which includes LastWorkerIdentity. The LastWorkerIdentity is only set when retry is happening. This PR change that so it would return StartedIdentity before any retry. 
eye_balls
No
No
> Use StartedIdentity as LastWorkerIdentity if no retry

- common/persistence/visibility/store/elasticsearch/processor.go
Fix bulk processor NPE.
**Why?**
`atomic.Value` should always be loaded with value otherwise `Load()` returns `nil` even if type is not a pointer.
Run locally.
No risks.
No.
> Fix bulk processor NPE

- common/namespace/cache.go
- common/namespace/cache_mock.go
- common/namespace/cache_test.go
- common/namespace/mutate.go
- common/namespace/testconstructors.go
- common/resource/fx.go
- common/resource/resourceImpl.go
- common/xdc/nDCHistoryResender_test.go
- host/onebox.go
- service/frontend/dcRedirectionPolicy_test.go
- service/frontend/workflowHandler_test.go
- service/history/commandChecker_test.go
- service/history/historyEngine.go
- service/history/historyEngine2_test.go
- service/history/historyEngine3_eventsv2_test.go
- service/history/nDCActivityReplicator_test.go
- service/history/nDCStateRebuilder_test.go
- service/history/replicationTaskExecutor_test.go
- service/history/replicatorQueueProcessor_test.go
- service/history/shard/context_test.go
- service/history/tests/vars.go
- service/history/timerQueueTaskExecutorBase_test.go
- service/history/workflow/mutable_state_impl_test.go
- service/matching/handler.go
- service/matching/matcher_test.go
- service/matching/matchingEngine.go
- service/matching/matchingEngine_test.go
- service/matching/taskQueueManager.go
- service/matching/taskQueueManager_test.go
Removes the ClusterInfo interface for a bool parameter to the
cache constructor defining whether or not global namespaces are enabled
on the current cluster. Also refactored CacheEntry functions that relied
on a priori knowledge of the name of the cluster on which they are
currently being executed to taking that information as a parameter from
callers.
**Why?**
Decouples namespace.Cache from cluster metadata and makes it more flexible to use at the same time
Old & new unit tests
No
> Remove namespace/ dependence on cluster metadata

- tools/cli/admin_cluster_search_attributes_commands.go
Increase `add-search-attributes` tctl admin command timeout to 30s.
**Why?**
Default 5s timeout sometimes is not enough to run and get results of underlying system workflow.
N/A
No risks.
No.
> Increase add-search-attributes tctl admin command timeout to 30s

- common/metrics/defs.go
- common/metrics/tags.go
- common/persistence/visibility/store/elasticsearch/client/errors.go
- common/persistence/visibility/store/elasticsearch/processor.go
- common/persistence/visibility/store/elasticsearch/processor_test.go
Add http status metric tag to bulk processor errors.
**Why?**
To get better visibility of Elasticsearch errors.
With local graphana.
No risks.
No.
> Add http status metric tag to bulk processor errors

- Dockerfile
**What changed?**.
Specify the entrypoint in `Dockerfile` absolutely.
**Why?**
When used as a container in a K8s Pod in Jenkins with the K8s plugin, the working dir is overridden, causing the entrypoint script to not be found.
Tested the concept by specifying the command absolutely in the jenkins pod config. Tested the change by building the image locally.
Low. Container wouldn't start if this change was incorrect.
No.
> Specify the entrypoint absolutely

- common/log/tag/values.go
- service/worker/fx.go
- service/worker/service.go
- service/worker/worker.go
Add a new worker manager to manage all sdk workers for server worker role.
**Why?**
Currently, each component duplicate the logic to create separate sdk workers. We should have one place for all sdk workers and use DI to register workflow/activity from each component.
Run server, see below logs in start and stop:
{"level":"info","ts":"2021-11-03T10:26:44.091-0700","msg":"none","component":"worker-manager","lifecycle":"Started","logging-call-at":"worker.go:108"}
{"level":"info","ts":"2021-11-03T10:26:55.496-0700","msg":"none","component":"worker-manager","lifecycle":"Stopped","logging-call-at":"worker.go:123"}
No
No
> Add worker manager to worker service

- docker/entrypoint.sh
Use absolute paths to scripts and config in docker image
When used in a pod in Jenkins with the K8s plugin, the working directory is overridden, meaning none of these scripts can be located without manually specifying the command:
```
command: [ "/bin/bash", "-c", "cd /etc/temporal && ./entrypoint.sh autosetup" ]
```
Test in Jenkins to ensure correctness, and built the docker image locally.
Worst case: Container would fail to start
Hotfix: No
> Use correct absolute paths to scripts in dockerfile

- common/namespace/namespace.go
- common/namespace/namespace_test.go
- service/history/visibilityQueueTaskExecutor.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/task_generator.go
Remove sampled retention
**Why?**
This was added as a temporary hack more than 3 years ago that should have been removed long ago. It was never mentioned anywhere in the doc that this exists. No one should have used this hack. In fact, it seems the visibility queue executor is wrong when sampled retention is enabled, it only writes for those sampled workflows.
eye_balls
No.
No
> Remove sampled retention

- service/history/historyEngine.go
- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_mock.go
- service/history/workflow/task_generator.go
- service/history/workflow/task_generator_mock.go
Fix GenerateLastHistoryReplicationTask
**Why?**
Closed workflow are immutable, need to call shard.AddTasks directly for the generated replication task.
> Fix GenerateLastHistoryReplicationTask to use shard.AddTasks()

- service/frontend/adminHandler.go
- service/worker/addsearchattributes/fx.go
- service/worker/addsearchattributes/workflow.go
- service/worker/fx.go
- service/worker/service.go
Refactor worker part for addsearchattributes using fx
**Why?**
Remove duplicate code of initiating sdk workers for different background work types.
Manual test. 
1) tctl admin cl add-search-attributes --name FxWorkerKeywordField --type Keyword
2) tctl --ns temporal-system wf show -w temporal-sys-add-search-attributes-workflow
verify the workflow completed successfully and is run on taskqueue: default-worker-tq.
No
No
> Refactor worker for addsearchattributes using fx

- client/history/client.go
- service/frontend/workflowHandler.go
Add RequestID validation for ResetWorkflow
**Why?**
If this value is not set by user, the request will get deduped and causing lots of confusion.
> Add RequestID validation for ResetWorkflow

- tools/cli/admin.go
- tools/cli/adminClusterCommands.go
- Removing command `tctl admin cluster metadata` in favor of `tctl admin cluster describe`
**Why?**
- Cluster metadata is now part of admin DescribeCluster API and `tctl admin cluster describe`. Simplifying tctl admin commands usage
- related https://github.com/temporalio/temporal/pull/2150
- verified command is not available in `tctl admin cluster -h`
- automated scripts that rely on `tctl admin cluster metadata` won't work
> Remove tctl admin command to output cluster metadata

- cmd/server/main.go
- common/resource/bootstrapParams.go
- service/frontend/fx.go
- temporal/server_impl.go
- temporal/server_option.go
- temporal/server_options.go
Add server options for custom interceptors
**Why?**
This open up a new categories of integrations with server by using custom interceptors.
Manual test with 2 interceptors with code like:
```
temporal.WithChainedFrontendGrpcInterceptors(
func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp interface{}, err error) {
fmt.Printf("intercept1: %v\n", info.FullMethod)
return handler(ctx, req)
},
func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp interface{}, err error) {
fmt.Printf("intercept2: %v\n", info.FullMethod)
return handler(ctx, req)
},
),
```
And verify output like:
```
intercept1: …
```
> Add custom grpc inspectors

- service/frontend/workflowHandler.go
Move namespace name validation to `RegisterNamespace`.
**Why?**
Previously namespace name was validated when it was used (i.e. `StartWorkflowExecution`) but not when registered (`RegisterNamespace`).
No risks.
No.
> Move namespace name validation to RegisterNamespace

- service/matching/taskQueueManager.go
- service/matching/taskQueueManager_test.go
- service/matching/taskReader.go
- Don't signal the taskReader to fetch a batch after a sync-match
- Ensure taskReader gives priority to exiting over further signal
processing
- Remove redundant error handling in taskReader
**Why?**
We reviewed the taskReader task pump loop and the sync-match path and found these opportunities to improve clarity and reduce GetTasks calls.
New unit tests for taskReader signaling from taskQueueManager. Other changes are non-functional.
Frequency of taskReader.Signal() calls after sync-match success could be masking other places where such a call should exist but is missing.
No
> Matching GetTasks call reduction

- host/onebox.go
- temporal/fx.go
It disables fx's logging using `fx.NopLogger`.
**Why?**
My thinking is that fx logging is only useful when wiring dependencies during development but rather verbose and unneeded otherwise.
I've confirmed that fx logs are not written to stderr anymore when running or embedding Temporal.
> Disable fx logs

- tools/cli/batch.go
- tools/cli/workflowBatchCommands.go
A concurrency flag is added in the tctl cli tool for the `batch create` command
**Why?**
The concurrency parameter is supported by the batch API but not exposed in the tctl tool. We need to increase throughput of the batch execution by adjusting the concurrency parameter.
There are no unit test for batch command, so I did a local build and verified that the concurrency flag I added works with the batch jobs we created
N/A
No
> Support concurrency flag in the tctl batch command

- tools/cli/admin.go
- tools/cli/adminCommands.go
updated `tctl admin membership list_db` command to retrieve data from admin API instead of directly connecting to DB
**Why?**
Simplifies usage as users don't have to pass the DB connection options
`tctl admin membership list_db`
> Use admin API for tctl list cluster members

- common/persistence/cassandra/cluster_metadata_store.go
- common/persistence/client/fault_injection.go
- common/persistence/clusterMetadataStore.go
- common/persistence/dataInterfaces.go
- common/persistence/dataInterfaces_mock.go
- common/persistence/mock/store_mock.go
- common/persistence/persistence-tests/clusterMetadataManagerTest.go
- common/persistence/persistenceInterface.go
- common/persistence/persistenceMetricClients.go
- common/persistence/persistenceRateLimitedClients.go
- common/persistence/sql/cluster_metadata.go
- common/persistence/sql/sqlplugin/cluster_metadata.go
- common/persistence/sql/sqlplugin/mysql/cluster_metadata.go
- common/persistence/sql/sqlplugin/postgresql/cluster_metadata.go
- common/persistence/sql/sqlplugin/sqlite/cluster_metadata.go
- temporal/fx.go
1. SaveClusterMetadata write to both cluster_metadata and cluster_metadata_info
2. Fx initializes cluster metadata if it doesn't exist in both cluster_metadata and cluster_metadata_info or migrate date from cluster_metadata to cluster_metadata_info
**Why?**
1. Make service backward compatible. The indexed search attributes stores in cluster metadata so that if it only write to the new table. It will fail if the server is rolled back.
2. Make cluster metadata forward compatible. For existing search attribute, we should migration(backfill) them to the new table.
Local inter-cluster tests
In the worst case, the customized search attributes fail to be migrated and workflows could be blocked.
N/A
> Make cluster metadata schema backward compatible

- common/namespace/namespace.go
- common/rpc/interceptor/namespace_validator.go
- common/rpc/interceptor/namespace_validator_test.go
- host/ndc/ndc_integration_test.go
- host/xdc/elasticsearch_test.go
- host/xdc/integration_failover_test.go
- service/frontend/adminHandler.go
- service/frontend/errors.go
- service/frontend/fx.go
- service/frontend/workflowHandler.go
- service/frontend/workflowHandler_test.go
Add `NamespaceValidator` interceptor.
**Why?**
Centralize namespace validation on one place. `NamespaceValidatorInterceptor` validates:
1. Namespace is specified in request if there is a `namespace` field.
2. Namespace exists.
3. Namespace is in correct state.
New unit tests.
For some reason `RecordActivityTaskHeartbeat` (unlike all other similar APIs) didn't compare namespace Id from task token with namespace in request itself (`checkNamespaceMatch` call). I believe it was just a missing check which I added.
No.
> Add NamespaceValidator interceptor

- service/frontend/adminHandler.go
- tools/cli/admin.go
- tools/cli/adminCommands.go
- tools/cli/namespaceUtils.go
Switches to Admin API when registering namespaces through `tctl admin namespace register`
**Why?**
Simplifies tctl usage by removing direct DB connection params
tctl --namespace notdefault admin namespace register --description d1 --owner_email o@gmail.com --retention 24
> Switch to admin API in tctl register namespace

- common/archiver/gcloud/connector/client_test.go
- tools/sql/clitest/mysql_cli_test.go
- tools/sql/clitest/postgresql_cli_test.go
- Use t.Setenv() function instead of os.Setenv
**Why?**
- Leverage the *testing.T instance and isolate the unit testing scope (https://golang.org/doc/go1.17#testing)
- Unit test
- No
- No
> Use t.Setenv function to set env in unit tests

- common/metrics/defs.go
- common/metrics/defs_test.go
- common/persistence/cassandra/shard_store.go
- common/persistence/client/fault_injection.go
- common/persistence/dataInterfaces.go
- common/persistence/dataInterfaces_mock.go
- common/persistence/mock/store_mock.go
- common/persistence/persistence-tests/executionManagerTest.go
- common/persistence/persistence-tests/persistenceTestBase.go
- common/persistence/persistence-tests/shardPersistenceTest.go
- common/persistence/persistenceInterface.go
- common/persistence/persistenceMetricClients.go
- common/persistence/persistenceRateLimitedClients.go
- common/persistence/shard_manager.go
- common/persistence/sql/shard.go
- host/testcluster.go
- service/history/handler.go
- service/history/shard/context_impl.go
- service/history/shard/controller_test.go
Persistence shard interface is almost always used with "get or create" semantics instead of separate get and create, so make that the official interface. There's an admin rpc to get without create, which is still supported.
**Why?**
Simpler code (net line count minus 89 lines!), allows for optimizations in persistence.
Unit tests, integration tests
> Change shard persistence interface to get-or-create

- common/persistence/sql/sqlplugin/tests/visibility_test.go
- develop/buildkite/docker-compose.yml
- develop/docker-compose/docker-compose.yml
Pin MySQL version to 8.0.19.
**Why?**
8.0.19 is the first GA version of MySQL 8 which works fine and pass all tests. Previous versions don't work (visibility unit test fail while pagination). Using it for development environment as minimus MySQL 8 supported version.
I think previous versions don't work because of:
> The removal of a subquery because the condition in which it occurred was always false was expected to be performed during resolution, but when the subquery did not involve any tables, the server executed it while resolving it. This resulted in the failure of a subsequent check to confirm that the subquery was only being resolved and not yet optimized. Now in such cases, the server also checks to see whether the subquery was already executed. (Bug #30273827) …
> Pin MySQL version to 8.0.19

- service/history/handler.go
- service/history/shard/context_impl.go
- service/history/shard/controller_impl.go
- service/history/shard/controller_test.go
When the shard rangeid lock status is unknown, rpcs that call into this history engine wait a short amount of time for the lock to be [re]acquired before returning an unavailable error (since #2102). This makes them wait using the full timeout of the rpc context instead.
**Why?**
The client would just retry anyway, this moves the retry into the server.
Unit tests + integration tests
> Use rpc context for shard acquisition timeout

- common/archiver/filestore/historyArchiver_test.go
- common/archiver/filestore/util_test.go
- common/archiver/filestore/visibilityArchiver_test.go
- common/config/loader_test.go
- common/log/zap_logger_test.go
- tests/testhelper/io.go
- tools/common/schema/test/dbtest.go
- tools/common/schema/test/setuptest.go
- tools/common/schema/test/updatetest.go
- tools/common/schema/updatetask_test.go
- Introduce `testhelper` package to create temp file and dir, this receives testing.TB so both *testing.T and *testing.B are accepted.
- These functions use t.Cleanup function to cleanup the temporary files and dirs after tests are done.
**Why?**
- Reduce redundant defer code (remove temp files / dirs) after tests are completed.
- Error is asserted in the test helper functions so we don't need to check err when executing the MkdirTemp / CreateTemp.
- Unit/Integration tests
- No
- No
> Add testhelper package to create temp file and dir

- common/namespace/replicationTaskExecutor.go
- common/rpc/interceptor/namespace_validator.go
- service/history/historyEngine.go
- service/history/replicatorQueueProcessor.go
- service/history/shard/context.go
- service/history/shard/context_impl.go
- service/history/shard/context_mock.go
- service/history/shard/context_testutil.go
Track max replication task ID when Namespace in Handover state
**Why?**
So it is possible to monitor if remote cluster is ready to take over the namespace in handover state.
Manual test with print statement to verify the max replication task id is valid when namespace transition into handover state. Also test when shard reload, the max replication task is still valid. Server restart case is also tested.
No
No
> Track max replication task ID for Namespace Handover

- .github/workflows/goreleaser.yml
- CONTRIBUTING.md
- Dockerfile
- docker/base-images/base-builder.Dockerfile
- docker/base-images/base-ci-builder.Dockerfile
- docker/base-images/base-server.Dockerfile
Upgrade to go 1.17.3
**Why?**
Golang Vulnerability CVE-2021-39293
https://github.com/temporalio/temporal/issues/2184
> Upgrade golang to 1.17.3

- tools/cli/flags.go
- tools/cli/namespaceCommands.go
- tools/cli/namespaceUtils.go
Namespace state update needs more steps and should be handled by a workflow.
Update the state metadata should be just one step of the workflow.
We should create other command for tctl to trigger operations like DeleteNamespace.
> Remove --state from namespace update command

- common/metrics/defs.go
Fix Elasticsearch bulk processor metrics units.
**Why?**
Units was misconfigured with initial setup.
No risks.
No.
> Fix Elasticsearch bulk processor metrics units

- cmd/server/main.go
- common/dynamicconfig/noop_client.go
- temporal/fx.go
Stop server start up on malformed dynamic config.
**Why?**
If dynamic config has syntax error server shouldn't hide error and use default noop dynamic config but exit right away.
Running locally.
Server will not start if dynamic config has errors.
No.
> Stop server start up on malformed dynamic config

- common/log/tag/tags.go
- service/history/shard/context_impl.go
Fixes a potential bug in #2102: we shouldn't update maxReadLevel immediately when we attempt to reacquire the rangeid lock in the background, we should do it only after a successful re-acquisition (which on cassandra implies that the previous unknown transaction definitively succeeded or failed).
**Why?**
If maxReadLevel is updated, readers catch up to it, and then the original transaction actually gets applied and becomes visible later, then we'd lose tasks.
Unit tests and walking through the code
This is clearly a tricky area so it's possible we missed another case.
> Only update maxReadLevel after successful re-acquire of shard

- service/matching/ackManager.go
- service/matching/matchingEngine_test.go
- service/matching/taskReader.go
If we read a gap in tasks immediately after the current ack level, advance the ack level to the end of the gap.
Also, don't let taskReader start reading before taskWriter has acquired the lease (and thus initialized our rangeid and ack level).
**Why?**
If task queues are continuously reloaded (increasing rangeid with each lease), without any db activity to increase the ack level (either no load or low sync-match-only load), then the range that we try to read when loading a task queue (from the ack level to the end of the previous rangeid block) will increase over time, unless we advance the ack level past the gaps.
This also gets rid of the useless read of the range [-1, 0) that taskReader would do immediately on starting, before taskWriter acquires the lease and …
> Move ackLevel past gaps in task ids

- common/cluster/metadata.go
- common/cluster/metadata_mock.go
- common/cluster/metadata_test.go
- service/history/historyEngine.go
- service/history/historyEngine2_test.go
- service/history/historyEngine3_eventsv2_test.go
- service/history/historyEngine_test.go
- service/history/nDCBranchMgr_test.go
- service/history/nDCReplicationTask.go
- service/history/nDCTransactionMgr.go
- service/history/nDCTransactionMgr_test.go
- service/history/nDCWorkflow.go
- service/history/nDCWorkflow_test.go
- service/history/shard/context_impl.go
- service/history/shard/context_test.go
- service/history/shard/engine.go
- service/history/shard/engine_mock.go
- service/history/timerQueueActiveTaskExecutor_test.go
- service/history/timerQueueProcessor.go
- service/history/timerQueueStandbyTaskExecutor_test.go
- service/history/timerQueueTaskExecutorBase_test.go
- service/history/transferQueueActiveTaskExecutor_test.go
- service/history/transferQueueProcessor.go
- service/history/transferQueueStandbyTaskExecutor_test.go
- service/history/visibilityQueueTaskExecutor_test.go
- service/history/workflow/context.go
- service/history/workflow/context_mock.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_rebuilder_test.go
- service/history/workflow/transaction_impl.go
Correctly detect the right cluster for EmptyVersion global namespace
**Why?**
Local namespace uses 0 (EmptyVersion) as failover version. 
With namespace promotion, local namespace could become global namespace.
After promotion, workflow with 0 failover version could be replicate to other clusters.
This change is needed in order to correctly detect that the workflow with EmptyVersion was not from current cluster.
Unit tests.
No
No
> Handle EmptyVersion

- common/persistence/cassandra/schema_version_reader.go
- tools/cassandra/cqlclient.go
- tools/cassandra/handler.go
- tools/common/schema/types.go
* Use persistence config consistency for Cassandra schema version checking
* Update CQL schema tools accordingly
**Why?**
Should use persistence consistency from config or input
N/A
N/A
No
> Use persistence config consistency for schema version check

- common/metrics/defs.go
- common/metrics/metric_client_tests.go
- common/metrics/opentelemetry_client.go
- common/metrics/opentelemetry_reporter.go
- common/metrics/opentelemetry_scope.go
- common/metrics/opentelemetry_user_scope.go
- common/metrics/otel_gauge_cache.go
- common/metrics/otel_metric_test_utility.go
- common/metrics/otel_test.go
- common/metrics/tally_metric_test_utility.go
- common/metrics/tally_test.go
Added unit tests for metrics
**Why?**
Test coverage
these are unit tests.
N/A
N/A
> Add basic metrics unit tests

- service/matching/db_task_manager.go
- service/matching/db_task_queue_ownership.go
- service/matching/db_task_queue_ownership_test.go
- service/matching/taskQueueManager.go
- service/matching/taskReader.go
* Make matching service executeWithRetry function stateless
* Polish new db task logic for later integration
**Why?**
Cleanup logic for later integration
N/A
N/A
No
> Make matching service executeWithRetry function stateless

- service/matching/taskQueueManager.go
* Remove completion function reference when doing sync matching
**Why?**
Existing logic will provide both resp channel & completion function when doing sync matching: https://github.com/temporalio/temporal/blob/v1.14.0/service/matching/taskQueueManager.go#L529
https://github.com/temporalio/temporal/blob/v1.14.0/service/matching/task.go#L83
However only resp channel will be used: https://github.com/temporalio/temporal/blob/v1.14.0/service/matching/task.go#L158
Existing tests & CICD
N/A
No
> Matching sync match task should not have completion function

- common/persistence/persistenceMetricClients.go
- common/persistence/persistenceRateLimitedClients.go
- common/persistence/visibility/visiblity_manager_metrics.go
- service/history/shard/context_impl.go
Revert persistence rate limit error type.
**Why?**
Persistence rate limiting error type was changed from ResourceExahusted to Unavailable but the shard context's handleError was not updated. This cause shard to unload/reload on this error which increases persistence load and amplify the problem.
No
Yes
> Revert persistence rate limit error type

- client/frontend/client.go
- client/frontend/metricClient.go
- client/frontend/retryableClient.go
- common/authorization/frontend_api.go
- common/metrics/defs.go
- go.mod
- go.sum
- service/frontend/configs/quotas.go
- service/frontend/configs/quotas_test.go
- service/frontend/dcRedirectionHandler.go
- service/frontend/interface_mock.go
- service/frontend/workflowHandler.go
- service/frontend/workflowHandler_test.go
`WorkflowService.GetSystemInfo` RPC call was added mimics some of `GetClusterInfo` but is namespace aware. Initial version uses a fixed response. This uses https://github.com/temporalio/api/pull/134.
This was previously done in #2297 but a new branch was required to get fresh master without having to rebase over submodule updates.
Closes #2190
**Why?**
Callers for cloud and open-source servers need a namespace-aware call they can make to determine server version and system capabilities. Future capabilities can be added as needed.
Standard unit test.
None, but the proto should be reviewed for future compatibility.
No
> New GetSystemInfo RPC

- cmd/server/main.go
- docker/base-images/README.md
- docker/base-images/base-server.Dockerfile
This adds `tzdata` to the server base image (as an Alpine package), so it will end up in the built server images. It also adds embedded `tzdata` to the server binary as a fallback (using Go's time/tzdata package), in case the binary is run in another context. In general we expect the Alpine package to be more up-to-date than Go's embedded `tzdata` (currently 2021e vs 2021a).
**Why?**
So the server can do time zone calculations.
Built images + binaries.
No risks.
No.
> Add tzdata to server base image and binary

- Dockerfile
- Makefile
- docker/README.md
Use docker's built-in `--target` instead of a `TARGET` build arg.
**Why?**
Simpler, use built-in feature.
Manual test.
If anyone else has scripts that use the build arg, they'd have to be changed.
No.
> Use --target for docker builds

- service/frontend/workflowHandler.go
- service/frontend/workflowHandler_test.go
- Fix transient workflow task check in getRawHistory
**Why?**
- Existing check checks the wrong nextPageToken, and transient workflow task won't be returned if input nextPageToken is not empty.
- This will cause raw transient workflow task not being sent to worker if workflow history is long (larger than one page, which will cause worker to all GetWorkflowExecutionHistory). On the worker side, we will see the `premature end of stream` error.
- Added unit test. Tested locally.
Yes
> Fix transient workflow task check in getRawHistory

- service/matching/taskQueueManager.go
- service/matching/taskQueueManager_test.go
- do not persist forwarded tasks for standby namespaces
**Why?**
- Forwarded tasks should never be persisted
- Ideally child partition should not send remote sync request if namespace is passive, but child partition and parent partition may live in two different hosts and have different view of whether namespace is active or not (e.g. child think it's active while parent refreshes namespace cache first and found it's actually passive), so the check on the receiver side is still needed.
- forwarded tasks have no ttl and will live in db forever if namespace never does failover, causing large partition issue.
- more details here: https://github.com/uber/cadence/pull/4654
Yes
> Fix remote sync match for standby namespaces

- service/history/replicationDLQHandler_test.go
- service/history/shard/context_impl.go
- service/history/timerQueueAckMgr_test.go
- Ignore disabled cluster when calculating queue diff metrics
**Why?**
- Disabled clusters' ack level won't advance and they also won't prevent overall task queue ack level from advancing. If they are included in the calculation, the queue diff metrics will only keeping increasing, while there's actually no lag at all.
Existing tests
N/A, just changing metrics
No.
> Fix queue diff metrics for disabled clusters

- common/metrics/defs.go
- service/history/queueAckMgr.go
- service/history/shard/context_impl.go
Add lag and pending tasks metrics for visibility queue
**Why?**
Add lag and pending tasks metrics for visibility queue
Existing tests
N/A, just adding metrics
No
> Add lag and pending tasks metrics for visibility queue

- service/history/workflow/transaction_impl.go
- service/history/workflow/transaction_test.go
- Notify new tasks if persistence operation may succeed (applied)
**Why?**
- Please check https://github.com/uber/cadence/pull/3678
- Note: even if we don't notify, those tasks won't be lost since queue processor will load tasks every 30s or so. Workflow will just experience delay.
We may have more task loading persistence requests
No
> Notify new tasks when workflow is potentially updated

- host/client_integration_test.go
- service/history/workflowTaskHandlerCallbacks.go
Correctly handle new workflow task in case RespondWorkflowTaskCompleted failed.
**Why?**
In case of RespondWorkflowTaskCompleted failed, server would return error and won't be able to piggyback a new workflow task. The new workflow task needs to go through normal transfer queue -> matching -> poller route to be delivered to worker.
Added new integration test
No
No
> Fix fail workflow task and generate new workflow task

- service/history/fx.go
- service/history/handler.go
- service/history/service.go
- service/history/shard/controller_impl.go
- service/history/shard/controller_test.go
- service/history/shard/fx.go
Use fx to initialize shard controller.
**Why?**
Continue moving things to fx for consistency.
unit tests + integration tests
> Initialize shard controller with fx

- tools/sql/handler.go
There were two instances I found in `temporal-sql-tool` where an error was logged but not returned, causing execution to continue erroneously and ultimately panic.
I think using `Fatal` instead of `Error` would be better than having to ensure these returns are everywhere, but I wanted to keep the change set small.
**Why?**
In my case this resulted in a harmless panic when running the update-schema command of temporal-sql-tool with a bad password.
Error is logged and execution continues.
<details>
<summary>panic: runtime error: invalid memory address or nil pointer dereference ...</summary>
2021-12-02T14:42:21.990-0600    ERROR   Unable to connect to SQL database.      {"error": "pq: password authentication failed for user \"temporal_admin\"", "logging-call-at": …
> temporal-sql-tool: add missing err returns

- client/clientfactory.go
- client/history/metricClient.go
- client/matching/metricClient.go
- service/frontend/configs/quotas.go
* Add logging to matching client
* Add logging to history client
**Why?**
Add logging
Close #2308 
N/A
N/A
N/A
> Add logging to matching / history client

- common/authorization/default_jwt_claim_mapper.go
- common/authorization/default_jwt_claim_mapper_test.go
- common/authorization/default_token_key_provider.go
- common/authorization/token_key_provider.go
- go.mod
- go.sum
Replaced abandoned dependency `dgrijalva/jwt-go` with `golang-jwt/jwt`.
Adjusted the code to address the differences in API.
Added `SupportedMethods` method to `TokenKeyProvider`. This is a small breaking change that can be avoided by introducing a separate interface, but I don't think that would be better.
**Why?**
Fixes #2313
Abandoned dependencies are a concern.
Unit tests
This is a different implementation of the JWT library, which could in theory break something.
I could have made a mistake in adjusting the code.
No
> Replace abandoned dgrijalva/jwt-go with golang-jwt/jwt

- host/cron_test.go
- host/integration_test.go
- host/integrationbase.go
Add new integration test `TestCronWorkflowCompletionStates` using sdk to replace two existing tests.
**Why?**
The old tests were confusing and flaky.
is a test
It might also be flaky: it's still dependent on real time
> Rewrite TestCronWorkflow_Failed/Succeeded as SDK integration tests

- service/history/consts/const.go
- service/history/historyEngine.go
* Disallow marking activity as cancelled without activity being request cancelled first
**Why?**
SDK should not try to marking activity as cancelled without activity being request cancelled first
N/A
N/A
No
> Disallow marking activity as cancelled without activity being request cancelled first

- docker/README.md
this is my attempt to introduce documentation for future employees and users to discover more about the docker/auto-setup situation we have.
are there any other locations where adding links/info makes sense?
> add link to explain docker builds and auto setup

- common/cache/lru.go
- common/cache/lru_test.go
* Before this PR, LRU cache will only attempt to evict the last access cache item, if this item is pinned, cache is considered full.
* After this PR, LRU cache will attempt to evict the last access & evictable cache item, even if this item is in the middle.
* Update unit test
**Why?**
Fix cache eviction behavior, so cache can be better utilized.
New tests
N/A
Yes
> Fix LRU cache eviction behavior

- develop/buildkite/pipeline.yml
Updated buildkite config to run Fossa non-blocking (only on merge to master)
Fossa has too many false positives to run in blocking mode
> Set Fossa to run non-blocking

- service/history/historyEngine.go
detect stale cache when RecordChildExecutionCompleted
**Why?**
Below sequence could cause missing child completed event in parent:
t1: history pod h1 is owner of the shard, mutable state cache contains workflow p1, at this time child c1 is not started yet.
t2: h2 is new owner of the shard,
t3: on h2, p1 starts child c1
t4: h2 is killed, and h1 become the new owner, but previous engine from t1 for shard is still alive, with staled cache.
t5: child c1 completed, and calls RecordChildExecutionCompleted which is sent to h1 with staled cache that does not have c1 as pending child, it would respond Not_found error.
eye_ball
No
Yes
> Detecting stale cache when RecordChildExecutionCompleted

- service/history/historyEngine.go
Dedup signals received by SignalWithStartWorkflowExecution
**Why?**
Signals sent with same RequestId are not deduped.
Local test, call SignalWithStartWorkflowExecution and/or SignalWorkflowExecution with same RequestId, verify signal are deduped.
No
No
> Dedup SignalWithStart based on RequestId

- host/client_integration_test.go
1. Reduce heartbeat timeout for flaky test.
2. Reduce heartbeat count.
**Why?**
A detail is mentioned in the test. The client heartbeat do batches to send them to server. This change tries to reduce the heartbeat batch window and tries to send the heartbeats sooner if the test is slow.
Unit tests.
The test could still be flaky if the box is slow.
>  Reduce heartbeat timeout for flaky test

- host/onebox.go
- host/taskpoller.go
- host/test_cluster.go
Utilize actual worker in onebox setup.
**Why?**
This moves removal of resource even further and uses real implementation in integration tests.
Run tests.
N/A
No
> Use actual worker in one box

- service/history/shard/context.go
- service/history/shard/context_impl.go
- service/history/shard/context_mock.go
- service/history/taskProcessor.go
Add sanity check to task processor to make sure task ID is not greater than max task ID known to this shard. 
**Why?**
This will guard against from shard reading timer tasks generated by other shard owner while current pod lost ownership.
eye_balls.
No
No
> Unload shard if loaded task ID is greater than max transfer ID

- docker/config_template.yaml
add separate visibility env vars for different db instance - some deployment environments, like Render, do not allow for creating another db on the same db instance. There is no hard requirement inside of Temporal, but this assumption is baked into the docker image - so we need to offer separate env vars that people can override.
closes https://github.com/temporalio/temporal/issues/1388
not yet tested
n/a
no
> [Docker build] add separate visibility env vars for different db instance

- service/frontend/dcRedirectionPolicy.go
- service/frontend/dcRedirectionPolicy_test.go
Add option to enable forwarding for all APIs
**Why?**
So it is possible to forward all calls if needed during migration.
unit test
No
No
> Option to enable forwarding all APIs

- service/history/shard/context.go
- service/history/shard/context_impl.go
- service/history/shard/context_mock.go
- service/history/taskProcessor.go
Check max taskID of current range instead of max read level when process task.
**Why?**
Update max read level might be delayed, which would cause unnecessary shard unload.
eye_ball
No
No
> Check max taskID instead of max read level when process task

- host/client_integration_test.go
- host/cron_test.go
Remove dummy registrations that aren't needed anymore.
**Why?**
They can cause name conflicts with other tests that use anonymous functions as workflows/activities.
they are tests
> Remove dummy registrations in sdk integration test

- docker/config_template.yaml
fix for #2362 -
our templating errors when the second arg is empty. so i have to introduce yet another fallback layer to replicate the previous behavior.
internal discussion https://temporaltechnologies.slack.com/archives/C01RN061UMR/p1642085688084200
tested locally
n/a - all env vars should be specified in a real setup
no
> [Docker build] fix defaults with variables in templates

- service/worker/migration/workflow.go
- service/worker/migration/workflow_test.go
Scan visibility instead of core execution table.
**Why?**
Scan table API on SQL persistence is not implemented and also to avoid tombstone issue on Cassandra.
Manual test. Also integration test (will be in follow up PR).
No
No
> Switch force-replication to scan over visibility

- docker/config_template.yaml
Unicode symbol 'с' (U+0441) was replaced with 'c' (U+0063).
**Why?**
While testing access to RDS(Postgres) I found the issue with the variable `caCert` which uses Russian Unicode symbol 'с' (U+0441) instead of the English 'c' (U+0063).
Checked that setting up `SQL_CA` env variable sets the `caCert` fields in temporal service config.
> Fix c symbol in caCert variable name

- .goreleaser.yml
- Dockerfile
- Makefile
- cmd/server/main_cgo.go
- cmd/tools/sql/main_cgo.go
- common/persistence/sql/sqlplugin/sqlite/admin.go
- common/persistence/sql/sqlplugin/sqlite/cluster_metadata.go
- common/persistence/sql/sqlplugin/sqlite/db.go
- common/persistence/sql/sqlplugin/sqlite/events.go
- common/persistence/sql/sqlplugin/sqlite/execution.go
- common/persistence/sql/sqlplugin/sqlite/execution_maps.go
- common/persistence/sql/sqlplugin/sqlite/namespace.go
- common/persistence/sql/sqlplugin/sqlite/plugin.go
- common/persistence/sql/sqlplugin/sqlite/queue.go
- common/persistence/sql/sqlplugin/sqlite/shard.go
- common/persistence/sql/sqlplugin/sqlite/task.go
- common/persistence/sql/sqlplugin/sqlite/typeconv.go
- common/persistence/sql/sqlplugin/sqlite/visibility.go
- common/persistence/sql/sqlplugin/tests/sqlite_test.go
- develop/buildkite/pipeline.yml
Enable `cgo` by default and disable it explicitly for docker image build.
**Why?**
SQLite requires `cgo` to be enabled. Production image would never use SQLite and still can be built without `cgo` i.e. `CGO_ENABLED=0`.
Build locally.
No risks.
No.
> Enable cgo by default and disable it explicitly for docker image build

- docker/base-images/base-server.Dockerfile
Dockerize moved from using Glock to Go modules and introduced go.mod and go.sum files into the repository.
Therefore, the Go module initialization command has to be removed from the `base-server` Dockerfile as it breaks the build.
See: https://github.com/jwilder/dockerize/commit/6f92b85658d6d66bbad3771289a94c1a5c8c8172
The `go mod init` command was removed from the build of the `dockerize` tool in the `base-server` image.
**Why?**
A clean build of the `base-server` image fails.
I've run the build and checked the server locally.
The build of Docker images based on the `base-server` image will fail: `temporal-server` and  `temporal-tctl`.
No
> Remove `go mod init` from dockerize build in base-server.Dockerfile

- develop/buildkite/Dockerfile
- develop/buildkite/pipeline.yml
Build docker image using Buildkite.
**Why?**
`ci-build` target builds project with `CGO_ENABLED=1` but docker images are getting build without cgo. Adding extra validation step which build docker image (without publishing) and validates that:
1. Project can be built without cgo,
2. `Dockerfile` is valid and all its dependencies exist.
With Buildkite.
No risks.
No.
> Build docker image using Buildkite

- common/persistence/visibility/store/standard/converter_test.go
- common/persistence/visibility/store/standard/query_interceptors.go
Return errors when user specifies comparison filter for `StartTime` for standard visibility.
**Why?**
Right now it will panic due to `nil` pointer exception. Technically it is possible to process comparison filter for `StartTime`, but we decided to only support equals comparison for all the standard queries. Open this up just for `StartTime` adds unnecessary complexity with minimum benefit. User can easily translate a comparison expression to a `BETWEEN ... AND ...` expression for `StartTime` which is currently supported.
Unit test.
No risks.
No.
> Add validation for invalid starttime filter for standard visibility

- Dockerfile
- docker/base-images/base-server.Dockerfile
Use `base-server:1.5.0` after recent update.
**Why?**
Follow up for #2393.
With Buildkite.
New version of `dockerize` is used now. Should be 100% backwards compatible though.
No.
> Use base-server:1.5.0 after recent update

- service/history/fx.go
- service/history/handler.go
- service/history/historyEngineFactory.go
- service/history/shard/controller_impl.go
- service/history/shard/fx.go
- Separate history engine factory implementation from history handler
- Clean up some unnecessary parameters after the separation
**Why?**
- Existing initialization logic contains a cycle: history handler depend on shard controller, but shard controller needs to use history hander as the engine factory. This is currently done via fx.Invoke and quite confusing when reading the code.
- New dependency graph will look like the following: various resources -> host level components -> shard controller and engine factory -> history handler.
- Run sample locally
no
> Separate history engine factory from handler

- .github/workflows/trigger-publish.yml
Triggers update of Temporal submodule in https://github.com/temporalio/docker-builds
Results in docker images builds & publish for auto-setup, server and admin-tools images
**Why?**
automation and moving to Github Actions
commits history may start showing up as failed 
> Add pipeline to trigger Temporal docker images build

- common/rpc/interceptor/namespace_test.go
- go.mod
- go.sum
- service/frontend/workflowHandler.go
- service/frontend/workflowHandler_test.go
Removed namespace from `GetSystemInfo` since it is no longer at https://github.com/temporalio/api/pull/140. It was originally added in #2309 which has not been released so it should be safe.
**Why?**
We were incorrect in assuming we could make these namespace specific. For SDK client use, we have to have capabilities for cross-namespace clients.
None if merged before next release.
No.
> Remove namespace from GetSystemInfo call

- service/worker/parentclosepolicy/client.go
- service/worker/parentclosepolicy/processor.go
- service/worker/parentclosepolicy/workflow.go
- service/worker/parentclosepolicy/workflow_test.go
- service/worker/service.go
- Handle namespaceNotActive error in parentClosePolicy workflow
- If chlid domain active in a different cluster, signal the system workflow in the remote cluster to apply the parent close policy.
- We can't rely on frontend autoforwarding for Terminate/RequestCancel, because there're some request fields we need to use that only exist in history service interface.
**Why?**
- Currently if child domain performs a failover after parent close policy receive the signal, the signal request can not be processed.
- if remote cluster is down then, the workflow will keep retrying sending the signal, but this is the same as today because we will keep retrying on namespace not active error.
no
> Handle namespaceNotActive error in parentClosePolicy workflow

- host/xdc/integration_failover_test.go
- service/history/historyEngine.go
- service/history/nDCTransactionMgr.go
- service/history/shard/context_impl.go
- service/history/shard/engine.go
- service/history/shard/engine_mock.go
- service/history/timerQueueProcessor.go
- service/history/transferQueueProcessor.go
- service/history/workflow/context.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/transaction.go
- service/history/workflow/transaction_impl.go
- service/history/workflow/transaction_mock.go
- service/history/workflow/transaction_test.go
- service/history/workflowResetter.go
- service/history/workflowResetter_test.go
Correctly handle FakeClusterForEmptyVersion and added integration test for ns migration
**Why?**
Added integration test for migration.
New integration test
No
No
> Fix fake cluster for empty version

- common/dynamicconfig/constants.go
- common/persistence/persistence-tests/persistenceTestBase.go
- common/resource/fx.go
- common/resource/resourceImpl.go
- common/searchattribute/manager.go
- common/searchattribute/manager_test.go
Add a dynamic config to force refresh search attributes cache on each read.
This helps local testing scenarios so we get a consistent view of the latest info.
**Why?**
See above.
Local testing.
No. This flag should never be turned on in production.
No.
> Add dynamic config to force refresh search attributes cache

- common/persistence/clusterMetadataStore.go
- temporal/fx.go
Allow update initial failover version and version increment if not enable global namespace
**Why?**
Give it a chance to update the failover version and version increment.
Tested locally
> Allow update initial failover version and version increment

- common/archiver/filestore/historyArchiver_test.go
- common/archiver/gcloud/historyArchiver_test.go
- common/archiver/s3store/historyArchiver_test.go
- common/metrics/defs.go
- common/metrics/tags.go
- common/persistence/client/fault_injection.go
- common/persistence/nosql/nosqlplugin/cassandra/gocql/errors.go
- common/persistence/persistenceRateLimitedClients.go
- common/persistence/visibility/visiblity_manager_metrics.go
- common/rpc/interceptor/namespace_count_limit.go
- common/rpc/interceptor/namespace_rate_limit.go
- common/rpc/interceptor/rate_limit.go
- common/rpc/interceptor/telemetry.go
- go.mod
- go.sum
- host/sizelimit_test.go
- service/frontend/adminHandler.go
- service/history/consts/const.go
- service/history/replicationTaskProcessor.go
- service/matching/handler.go
- service/matching/matcher_test.go
- service/matching/taskWriter.go
- service/worker/archiver/client.go
Add resource_exhausted_cause metrics tag for ResourceExhaustedError metrics.
**Why?**
easer for oncall to handle error based on different resource type.
manual verify metrics
no
no
> Add resource_exhausted_cause metrics tag

- develop/scripts/create_build_info_data.sh
Allows to set git revision at build from env variable
**Why?**
Github actions only fetch one commit of data for submodules and not git history, hence the build was throwing "not a git repository"
https://github.com/temporalio/docker-builds/runs/4975313307?check_suite_focus=true#step:7:321
There is an option to fetch git history but seems only for the root project and not the submodules, using `fetch_depth` param, see https://github.com/actions/checkout#checkout-v2
```
$ bash develop/scripts/create_build_info_data.sh
$ cat ./build/info/data.json 
{"gitRevision":"864150a00","buildTimeUnix":1643337842}
$ export GITHUB_SHA_SHORT=333
$ bash develop/scripts/create_build_info_data.sh
$ cat ./build/info/data.json …
```
> Set git revision at build from env variable

- common/namespace/handler.go
- common/namespace/handler_GlobalNamespaceEnabled_NotMasterCluster_test.go
Allow global namespace update from all clusters. Registration is still only allowed from master cluster.
**Why?**
During namespace handover, the coordinator is source cluster which does not necessary be master cluster. So we should allow global namespace update from any cluster. 
manual test
No
No
> Allow global namespace update from all clusters

- service/history/taskProcessor.go
- service/history/taskProcessor_test.go
Added metrics context to golang context for proper metrics propagation.
**Why?**
Fix incorrectly reported metric.
manual tests
N/A
Yes
> Fix TQ user latency not reported correctly

- common/persistence/tests/cassandra_test.go
- common/persistence/tests/cassandra_test_util.go
Also, changed NewCassandraConfig to private function
> Moved Cassandra test utility methods to a new file so they can be used outside of temporal repo

- common/dynamicconfig/constants.go
- service/history/configs/config.go
- service/history/nDCHistoryReplicator.go
- service/history/workflow/context.go
- service/history/workflow/context_mock.go
* Remove hacky force flush buffer bypass for XDC if incoming version -> current cluster
**Why?**
NOTE: previously, this hacky bypass was added to allow workflow resend back to original
cluster due to local DB dataloss. Removing this hacky bypass due to breaking basic NDC
assumptions.
N/A
N/A
No
> Remove hacky force flush buffer check

- common/authorization/default_jwt_claim_mapper.go
- common/authorization/token_key_provider.go
> Add RawTokenKeyProvider

- common/persistence/tests/cassandra_test.go
- common/persistence/tests/cassandra_test_util.go
Also, minor cleanups:
- Deduplicated setUp/tearDown code
- Replaced no-op logger with test logger
> Added GetVersionedSchemaFilesInOrder helper function to cassandra_test_util.go

- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
- common/persistence/visibility/store/query/errors.go
- common/persistence/visibility/store/standard/converter.go
Convert `ConverterError` to `InvalidArgument` in standard visibility parser.
**Why?**
Go errors are converted to unknown error which is retryable by SDK. This leads to bad experience when user makes a mistake in `Query` parameter (or `--query` flag in `tctl`) and instead of getting appropriate error with message it gets "context deadline exceeded" error because SDK retries the error for 10 seconds and then times out.
Run `tctl wf list --query`manually.
No risks.
No.
> Convert ConverterError to InvalidArgument in standard visibility parser

- common/persistence/tests/cassandra_test.go
- common/persistence/tests/cassandra_test_util.go
This is useful for diagnosing persistence test failures.
> Updated SetUpCassandraDatabase to take an actual logger instead of creating a NoopLogger

- common/persistence/dataInterfaces.go
- common/persistence/history_manager.go
- service/history/nDCStateRebuilder.go
- service/history/nDCStateRebuilder_test.go
Assign LastFirstTxnID correctly for multiple branch case (reset workflow operation).
**Why?**
Establish expected behavior.
unit tests
Reset workflow doesn't perform correctly
No
> Assign LastFirstTransactionID correctly

- Makefile
Update developer tools to latest available versions. Developers may want to run `make update-tools` locally after this PR is merged, There is no notable changes though.
**Why?**
Keep tools up to date.
Update and build locally.
No risks.
No.
> Update developer tools

- common/dynamicconfig/basic_client.go
- common/dynamicconfig/config_benchmark_test.go
- common/dynamicconfig/config_test.go
- common/dynamicconfig/constants.go
- common/dynamicconfig/file_based_client_test.go
- common/rpc/test/rpc_localstore_tls_test.go
Remove dynamic config translation map
**Why?**
Remove unnecessary layer of translate key to string value
Copy/Paste error between key and value
No
> Remove dynamic config translation map

- common/archiver/README.md
- common/archiver/constants.go
- common/archiver/filestore/historyArchiver.go
- common/archiver/filestore/historyArchiver_test.go
- common/archiver/gcloud/historyArchiver.go
- common/archiver/gcloud/historyArchiver_test.go
- common/archiver/s3store/historyArchiver.go
- common/archiver/s3store/historyArchiver_test.go
- common/metrics/defs.go
- common/util.go
Skip archival if workflow history not found.
**Why?**
It's possible that history archiver get multiple requests for archiving the same workflow (e.g. when signal system workflow times out and retry). 
Skip archival if workflow history not found. If workflow history not found, we currently return an non-retryable error immediately. It's the same as just return from the Archive method with nil error in terms of behavior since workflow won't retry the non-retryable error. As not found is an expected error, we should not emit non-retryable log/metric.
https://github.com/temporalio/temporal/issues/2464
Unit test
> Handle history not found error when archiving history

- service/history/shard/context_impl.go
Order delete workflow execution steps and document the order.
**Why?**
New order is better protected against failure edge cases.
N/A
No risks.
No.
> Order delete workflow execution steps and document the order

- client/matching/metricClient.go
Fix bug in matching client error logging
**Why?**
The arguments of defer function are evaluated immediately so the retErr always is nil.
go playground: https://go.dev/play/p/xk9zWXGgmBZ
No
No
> Fix matching client error logging

- client/history/metricClient.go
Fix bug in history client error logging.  (Should have been fixed in last PR as well.)
**Why?**
The arguments of defer function are evaluated immediately so the retErr always is nil.
go playground: https://go.dev/play/p/xk9zWXGgmBZ
No
No
> fix error logging for history client

- service/frontend/adminHandler.go
Add missing task types to `getTaskType`
**Why?**
`getTaskType` is called for all task categories not just timer tasks.
> Fix admin handler getTaskType implementation

- client/clientFactory_mock.go
- client/clientfactory.go
- client/history/metricClient.go
- client/matching/metricClient.go
- common/metrics/defs.go
- common/metrics/defs_test.go
- common/metrics/tags.go
- common/resource/fx.go
Use throttled logger and use error type in metrics client
**Why?**
The logger and metrics may be noisy to identify issues.
> Use throttled logger and use error type in metrics client

- common/searchattribute/validator.go
- host/child_workflow_test.go
- host/continue_as_new_test.go
- host/onebox.go
- host/test_search_attribute_mapper.go
- service/frontend/workflowHandler.go
- service/history/historyEngine.go
- service/history/historyEngine2_test.go
Move search attribute validator and mapper calls to frontend service.
**Why?**
Calling search attributes mapper from history engine cause them to be mapped twice in case if workflow is started from command (child workflow and continue as new).
No risks.
Maybe.
> Move search attribute validator and mapper calls to frontend service

- common/persistence/cassandra/errors.go
- common/persistence/cassandra/errors_test.go
- common/persistence/cassandra/mutable_state_store.go
- service/history/workflow/transaction_impl.go
- Fix few bugs in CAS failed operation error logic.
- Improve error messages. 
- Add CAS error logging.
- Add comments to clarify error handling logic.
- Rename generic var and param names to be more specific.
**Why?**
N/A
No risks.
No.
> Fix conflict error handling

- client/history/metricClient.go
- client/matching/metricClient.go
- common/log/tag/tags.go
- common/log/tag/tags_test.go
- common/metrics/defs.go
- common/metrics/defs_test.go
- common/metrics/tags.go
1. Add error type for logging in clients.
2. Use error type instead of predefined values
**Why?**
Add error type for logging in clients to filter error type in logs.
> Add error type for logging in clients

- service/frontend/workflowHandler.go
- service/frontend/workflowHandler_test.go
Stop retrying long polls if user's context is near deadline.
**Why?**
To avoid many context cancelled error from long polls while in retrying.
> Exit retry for long poll if context is near deadline

- config/development_sqlite.yaml
Following along https://github.com/temporalio/temporal/pull/2397, there were still a couple more Cyrillic letters checedk-in, likely from copy-pasting the config.
To ensure caCert is set from the config.
Verified presence of the letters with `rg "[^\x00-\x7F]"`, changed them to `c`, and then verified again with ripgrep that the letters were no longer present.
Should be low-risk, worst case perhaps someone will hit an error now that their caCert file is set correctly.
Potentially not, as this is an sqlite development config which if I understand correctly is a feature still in development. Will defer to Temporal for this.
> Replace Cyrillic c with c in rest of caCert variables

- common/persistence/nosql/nosqlplugin/cassandra/gocql/errors.go
- service/history/timerQueueAckMgr.go
- service/history/transferQueueProcessorBase.go
* Do not blindly retry timer task read, rely on timer controller rate limiter instead
**Why?**
Remove lower layer timer task read retry, so upper layer rate limiter can have better control
N/A
N/A
N/A
> Do not blindly retry timer task read

- service/history/shard/context_impl.go
- service/history/shard/context_test.go
- service/history/shard/context_testutil.go
- When init, make sure for each cluster timer max read level is not before its ack level
- For update, make sure the time max read level won't go backward (e.g due to time skew)
**Why?**
- Fix bug, which may lead to timer task loss
yes
> Fix timerMaxReadLevel map init and update

- .goreleaser.yml
Split goreleaser archive in two:cgo/nocgo.
**Why?**
Because Linux archives has also no-cgo binaries, number of binaries per archive is different, which violates release best practices.
Run goreleaser locally. 
Release binaries won't be built.
No.
> Split goreleaser archive in two:cgo/nocgo

- client/frontend/client.go
- client/frontend/metricClient.go
- client/frontend/retryableClient.go
- common/metrics/defs.go
- common/persistence/cassandra/history_store.go
- common/persistence/dataInterfaces.go
- common/persistence/dataInterfaces_mock.go
- common/persistence/execution_manager.go
- common/persistence/history_manager.go
- common/persistence/history_manager_util.go
- common/persistence/persistenceInterface.go
- common/persistence/persistenceMetricClients.go
- common/persistence/persistenceRateLimitedClients.go
- common/persistence/sql/history_store.go
- common/persistence/sql/sqlplugin/history_node.go
- common/persistence/sql/sqlplugin/mysql/events.go
- common/persistence/sql/sqlplugin/postgresql/events.go
- common/persistence/sql/sqlplugin/sqlite/events.go
- common/rpc/interceptor/telemetry.go
- go.mod
- go.sum
- host/gethistory_test.go
- schema/cassandra/temporal/schema.cql
- service/frontend/configs/quotas.go
- service/frontend/configs/quotas_test.go
- service/frontend/dcRedirectionHandler.go
- service/frontend/interface_mock.go
- service/frontend/workflowHandler.go
**This PR requires changes to API repo first**
https://github.com/temporalio/api/pull/147
and fix to LastFirstTransactionID (changes included into this PR due to how github reviews work with branching) https://github.com/temporalio/temporal/pull/2438
I'll cleanup/rebase changes once above PRs are merged.
Add support to retrieve workflow history in reverse order.
**Why?**
More convenient query for long histories in some cases.
Automated tests, manual tests
History is not queried correctly.
No
> Add support for GetWorkflowHistory in reverse order

- common/config/config.go
- common/rpc/encryption/localStoreTlsProvider.go
- common/rpc/encryption/tls_config_test.go
- common/rpc/test/rpc_localstore_tls_test.go
Replaced `GroupTLS.IsEnabled()` with `GroupTLS.IsServerEnabled()` and `GroupTLS.IsClientEnabled()`.
**Why?**
Fixes #2448 
Client may need to be enabled even when server TLS is disabled. The typical example is when client talks to a TLS-enabled load balancer. 
Added a unit test that reproduced #2448.
In theory, this changes treatment of TLS configuration and may cause some unexpected change in behavior.
In reality, this restore the behavior that existed prior to the introduction of `ClientTLS.ForceTLS` flag.
Potentially
> Treat enablement of TLS separately for server and client config

- common/metrics/config.go
- common/metrics/config_test.go
- common/metrics/interfaces.go
- common/metrics/interfaces_mock.go
- common/metrics/opentelemetry_client.go
- common/metrics/opentelemetry_reporter.go
- common/metrics/opentelemetry_scope.go
- common/metrics/opentelemetry_user_scope.go
- common/metrics/otel_gauge_cache.go
- common/metrics/otel_metric_test_utility.go
- common/metrics/runtime.go
- common/metrics/tally_client.go
- common/metrics/tally_reporter.go
- common/resource/bootstrapParams.go
- service/frontend/service.go
- temporal/fx.go
- temporal/server_impl.go
Cleaned up and exposed metric reporters constructors to the user.
**Why?**
Simplify reporter construction for the user.
manual/auto tests
Metrics reporters are not initialized correctly.
No
> Expose metrics reporters constructors to end-user

- .github/workflows/trigger-publish.yml
Starts Triggering Docker builds on commits into Release branches
Related PR:
https://github.com/temporalio/docker-builds/pull/23
**Why?**
Automating releases
Tested the code with personal repos and simulating the changes:
https://github.com/feedmeapples/gha-parent
https://github.com/feedmeapples/gha-child
> Trigger Docker builds on release branches

- common/log/sdk_logger.go
- common/log/sdk_logger_test.go
- go.mod
- go.sum
Add `tag` support to `sdkLogger`.
Also accidentally updated submodules.
**Why?**
To improve logging experience from internal workflows. Now it is possible to use internal `tag.Tag` with workflow logger.
No risks.
No.
> Add tag support to sdkLogger

- docker/auto-setup.sh
Add `SKIP_DB_CREATE` env to `auto-setup.sh`.
**Why?**
Closes #2447.
Build and run docker image manually.
No risks.
No.
> Add SKIP_DB_CREATE env to auto-setup.sh

- service/history/historyEngine_test.go
- service/history/workflowTaskHandlerCallbacks.go
Remove one of two `continue` condition of the retry loop and narrow it to few lines instead of x hundred lines.
**Why?**
To prevent unnecessary retries in case of failed workflow execution updates.
Under some specific conditions, if workflow update failed it won't be retried. SDKs though will retry.
Yes.
> Refactor handleWorkflowTaskCompleted retry loop

- service/history/historyEngine.go
- service/history/nDCHistoryReplicator.go
- service/history/nDCStateRebuilder.go
- service/history/workflow/delete_manager.go
- service/history/workflow/delete_manager_mock.go
- service/history/workflow/delete_manager_test.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/task_generator.go
- service/history/workflow/task_generator_mock.go
- service/history/workflow/task_refresher.go
Fix `DeleteWorkflowExecution` API when delete non current execution. Instead of calling internal `updateWorkflow` funcion, adding transfer task using new `DeleteManager.AddDeleteWorkflowExecutionTask` function which essentially just calls `shard.AddTask`.
**Why?**
Previous implementation worked only for current workflows.
Integration test in another PR.
No risks.
No.
> Fix DeleteWorkflowExecution API when delete non current execution

- service/history/shard/context_impl.go
- service/history/tasks/category.go
- service/history/tasks/task.go
- service/history/workflow/mutable_state_util.go
- Define type and name for task categories. Instead of just an integer, task category is now a struct with ID, type and name.
**Why?**
https://github.com/temporalio/temporal/pull/2511#discussion_r809678893
Existing tests
no
> Define type and name for task categories

- common/metrics/config.go
- common/metrics/opentelemetry_client.go
- common/metrics/opentelemetry_must_provider.go
- common/metrics/opentelemetry_reporter.go
- common/metrics/opentelemetry_user_scope.go
- common/metrics/otel_metric_test_utility.go
Extracted OtelMustProvider for easier user override.
See sample at https://github.com/temporalio/samples-server/pull/25
**Why?**
Ease of use.
Manual/auto tests
Metrics are not reported correctly
No
> Improve extensibility of optentelemetry metrics

- build/cgo/cgo.go
- build/cgo/nocgo.go
- cmd/server/main.go
Log build `CGO_ENABLED` state.
**Why?**
For better debugging issues which are related to `cgo` it is very useful to know if `cgo` was enabled during build or not.
Run locally.
No risks.
No.
> Log build CGO_ENABLED state

- common/constants.go
- common/util.go
- common/util_test.go
- service/history/timerQueueActiveTaskExecutor.go
- service/history/workflow/retry.go
- service/history/workflow/retry_test.go
Allow customizing retry behavior for timeout errors
- NOTE: this changes the behavior for both activity and workflow retry policy
**Why?**
https://github.com/temporalio/temporal/issues/2496
This change is technically breaking as the new format defined for timeout failure may matching user defined application error types. But the chance this will happen is very very low.
no
> Allow customizing retry behavior for timeout failure

- service/history/fx.go
- service/history/historyEngine.go
- service/history/historyEngineFactory.go
- service/history/queues/queue.go
- service/history/queues/queue_mock.go
- service/history/timerQueueAckMgr.go
- service/history/timerQueueAckMgr_test.go
- service/history/timerQueueActiveProcessor.go
- service/history/timerQueueActiveTaskExecutor.go
- service/history/timerQueueActiveTaskExecutor_test.go
- service/history/timerQueueProcessor.go
- service/history/timerQueueProcessorBase.go
- service/history/timerQueueStandbyProcessor.go
- service/history/timerQueueStandbyTaskExecutor.go
- service/history/timerQueueStandbyTaskExecutor_test.go
- service/history/timerQueueTaskExecutorBase.go
- service/history/timerQueueTaskExecutorBase_test.go
- service/history/transferQueueActiveProcessor.go
- service/history/transferQueueActiveTaskExecutor.go
- service/history/transferQueueActiveTaskExecutor_test.go
- service/history/transferQueueProcessor.go
- service/history/transferQueueStandbyProcessor.go
- service/history/transferQueueStandbyTaskExecutor.go
- service/history/transferQueueStandbyTaskExecutor_test.go
- service/history/transferQueueTaskExecutorBase.go
- service/history/visibilityQueueProcessor.go
- service/history/visibilityQueueTaskExecutor.go
- service/history/visibilityQueueTaskExecutor_test.go
- service/history/workflow/delete_manager.go
- service/worker/archiver/client.go
- Make queue processor depend on history engine interface
**Why?**
- Prepare for initializing queue processor via queue processor factory
- In worst case some components may not be initialized correctly. should be caught be tests. 
no
> Separate queue processor and history engine implementation

- common/persistence/cassandra/util.go
- common/persistence/execution_manager.go
- common/persistence/persistenceInterface.go
- common/persistence/size.go
- common/persistence/sql/execution_util.go
This enables the underlying store to have access to the ExecutionInfo on the Mutation object without having to do deserialization
> Adds ExecutionInfo reference to InternalWorkflowMutation 

- common/persistence/cassandra/util.go
- common/persistence/execution_manager.go
- common/persistence/persistenceInterface.go
- common/persistence/size.go
- common/persistence/sql/execution_util.go
This enables the underlying store to have access to the ExecutionInfo on the Mutation object without having to do deserialization
> Cherry-picks change to 1.15.x branch: Adds ExecutionInfo reference to InternalWorkflowMutation #2530

- common/metrics/config.go
- common/metrics/config_test.go
- temporal/fx.go
- temporal/server_impl.go
- temporal/server_option.go
- temporal/server_options.go
Require metrics.Reporter for custom metrics reporter.
Samples update https://github.com/temporalio/samples-server/pull/26
**Why?**
Deprecate old API.
manual/auto tests
Custom metrics are not reported.
No
> Force metrics.Reporter as extension point

- common/persistence/serialization/serializer.go
- service/history/historyEngineInterfaces.go
- service/history/historyEngineInterfaces_mock.go
- service/history/queueProcessor.go
- service/history/taskProcessor.go
- service/history/taskProcessor_test.go
- service/history/timerQueueAckMgr.go
- service/history/timerQueueAckMgr_test.go
- service/history/timerQueueActiveProcessor.go
- service/history/timerQueueProcessor.go
- service/history/timerQueueProcessorBase.go
- service/history/timerQueueStandbyProcessor.go
Update interfaces and structs for admin use
**Why?**
Expose those interfaces and structs for future admin use
No logic changed
> Update interfaces and structs for admin use

- .vscode/launch.json
- common/persistence/sql/sqlplugin/mysql/visibility.go
- common/persistence/sql/sqlplugin/postgresql/visibility.go
- common/persistence/sql/sqlplugin/sqlite/visibility.go
- common/persistence/sql/sqlplugin/visibility.go
- common/persistence/visibility/persistence-tests/visibility_persistence_suite_test.go
- common/persistence/visibility/store/standard/sql/visibility_store.go
Added TaskQueue to SQL VisibilityRow implementation
Updated read and write paths converting from Request/Response to pass through TasQueue.
**Why?**
Completeness of api implementation and consistency
#2207 
Local tests and updated unit test
N/A
No
> Sql task queue visibility

- common/archiver/s3store/historyArchiver_test.go
- common/archiver/s3store/visibilityArchiver_test.go
- common/metrics/common.go
- common/metrics/metric_client_tests.go
- common/metrics/opentelemetry_client.go
- common/metrics/opentelemetry_reporter.go
- common/metrics/tags.go
- common/metrics/tally_client.go
- common/metrics/tally_metric_test_utility.go
- common/metrics/tally_reporter.go
- common/persistence/persistence-tests/persistenceTestBase.go
- common/primitives/role.go
- common/resource/resourceTest.go
- common/tasks/benchmark_test.go
- common/tasks/interleaved_weighted_round_robin_test.go
- common/tasks/parallel_processor_test.go
- host/onebox.go
- service/history/workflow/mutable_state_impl_test.go
- service/matching/matchingEngine_test.go
- service/worker/archiver/workflow_test.go
- temporal/fx.go
- tools/cli/namespaceCommands.go
- tools/cli/namespaceUtils.go
Added service type tag to metrics.
**Why?**
Easier debugging
manual/unit tests
Metrics are not reported correctly.
Dashboards might not handle new tag correctly.
No
> Add service type tag to metrics

- host/client_integration_test.go
- service/history/workflowTaskHandlerCallbacks.go
This fixed a regression introduced in 1.15 by PR #2335
**Why?**
PR #2335 fixed an unnecessary delay after a failed workflow task, but it introduce a serious regression that when workflow task keeps failing, it would fall into a tight loop of retrying. 
The fix to the regression is simple, to drop workflow task if it is continuously failing  and let it timeout.
Added integration test to cover invalid command attributes case. 
No
Yes.
> Backoff failed workflow task

- schema/cassandra/temporal/schema.cql
- schema/cassandra/temporal/versioned/v1.0/schema.cql
See #2551
Just bad syntax, nothing to add. Maybe a question: how is that possible that there are newer migrations if this one does not get through.
> #2551 Fixing syntax in first migration to the Cassandra schema

- common/persistence/execution_manager.go
- common/persistence/serialization/serializer.go
- common/persistence/serialization/task_serializer.go
- common/persistence/serialization/task_serializer_test.go
- Refactor persistence task serializer to serialize/deserialize one task at a time
**Why?**
- Address a TODO in code to avoid unnecessary conversion between `map[tasks.Key]common.DataBlob` and `[]p.InternalHistoryTask`
Existing tests
no
> Refactor persistence task serializer

- docker/README.md
improve documentation for building images
**Why?**
when i was working on auto-setup, it was not obvious from the readme that the main way to build the image was to run `make` at the project root, until Alex told me.
> [docs] improve documentation for building images

- service/history/workflow/cache.go
Check WorkflowID and return NOT_FOUND error for WorkflowID using invalid UTF8 string. 
**Why?**
PR #2276 prevent workflow with invalid UTF8 string as WorkflowID from being created. But for the ones already created, the GetWorkflowExecution (to load mutable state) will fail on persistence on "String didn't validate" error and the system would keep retrying. We need to skip those tasks that try to load workflow with invalid utf8 string as workflowID. 
eye_balls
No
Yes
> Return NOT_FOUND for invalid workflow ID

- service/history/historyEngine.go
- service/history/historyEngine_test.go
Error code and message for missing activity task
**Why?**
A bit more clear on reason for failure and direction for investigation
#2538 
unit tests
None
No
> Update error code and message for missing activity task.

- common/namespace/registry.go
- common/namespace/registry_test.go
Remove deleted namespace from registry.
**Why?**
Before if namespace is delete it keeps staying in the cache even after refresh.
New unit test.
No risks.
No.
> Remove deleted namespace from registry

- service/history/workflow/mutable_state_impl.go
- Do not generate sync activity task for deleted activity
**Why?**
- The generated sync activity will be a no-op as the activity has already closed
no
> Do not generate sync activity task for deleted activity

- service/history/queueProcessorFactory.go
- service/history/taskAllocator.go
- service/history/taskProcessor.go
- service/history/taskProcessor_test.go
- service/history/timerQueueActiveProcessor.go
- service/history/timerQueueProcessorBase.go
- service/history/timerQueueStandbyProcessor.go
- service/history/transferQueueActiveProcessor.go
- service/history/transferQueueProcessor.go
- service/history/transferQueueStandbyProcessor.go
- service/history/visibilityQueueProcessor.go
Refactor task filter function and interface.
**Why?**
I believe it is some leftover after namespace registry refactoring because the only error which can be returned from `GetNamespaceByID` is `serviceerror.NotFound` in fact.
No risks.
No.
> Refactor task filter function and interface

- docker/base-images/base-ci-builder.Dockerfile
This is useful for all consuming packages that generate and test mocks during CI
> Added mockgen to base-ci-builder Docker image

- common/persistence/cassandra/mutable_state_task_store.go
Fix get history scheduled tasks query
**Why?**
Previous query used wrong columns name
Tested locally.
no
> Fix get history scheduled tasks query

- service/history/shard/context_impl.go
- service/history/shard/context_testutil.go
- service/history/shard/controller_impl.go
- service/history/shard/controller_test.go
In #2361, the shard would get unloaded without going through the controller, which would leave it in the controller's map in a stopped state. This makes it go through the controller. Also renamed the stop method to make it less confusing.
**Why?**
The consequences are pretty benign for now (wrong metrics on number of shards loaded/unloaded), but could be worse if the interaction between controller and context gets more complex.
new unit test
> Fix unloading shard after task id sanity check

- common/persistence/tests/cassandra_test.go
- common/persistence/tests/cassandra_test_util.go
- common/persistence/tests/execution_mutable_state.go
- common/persistence/tests/execution_mutable_state_task.go
- common/persistence/tests/mysql_test.go
- common/persistence/tests/postgresql_test.go
- Export cassandra test setup definitions for reuse
**Why?**
Code reuse.
no,  only changed test files
no
> Export cassandra test setup definitions for reuse

- common/searchattribute/encode_value_test.go
The test clearly shows what is an expected format for SearchAttributes Datetime (RFC 3339)
> Add test for an expected format of Datetime search attribute

- service/history/tasks/category.go
- Match history and proto task category definition
**Why?**
- Make it easier to use
- This is not breaking change since the task category definition change is not released yet.
- However if you are using master branch and is already running a commit has the previous task category definition, the change is breaking, and may result in task loss.
no
> Match history and proto task category definition

- service/frontend/adminHandler.go
- service/frontend/adminHandler_test.go
- service/frontend/dcRedirectionHandler.go
- service/frontend/dcRedirectionHandler_test.go
- service/frontend/fx.go
- service/frontend/interface.go
- service/frontend/interface_mock.go
- service/frontend/operator_handler.go
- service/frontend/operator_handler_test.go
- service/frontend/service.go
- service/frontend/workflowHandler.go
- service/frontend/workflowHandler_test.go
The standard gRPC Health Check Service implementation is used instead of the custom implementation in Workflow Handler. This allows each separate service/handler to announce the state.
**Why?**
Less custom code, correct implementation of health check that doesn't fall back into a single handler.
Existing tests for health check cover this change
None
No
> Rework health check

- common/dynamicconfig/constants.go
- host/archival_test.go
- service/frontend/configs/quotas.go
- service/frontend/fx.go
- service/frontend/service.go
Add dynamic config for per instance visibility API rate limit
**Why?**
Service protection.
Existing tests?
rate limits are set wrong and frontend calls are accepted or rejected wrongfully
Yes
> Add dynamic config for per instance visibility API rate limit

- tools/cassandra/cqlclient.go
- tools/cassandra/handler.go
- tools/cassandra/main.go
- tools/common/schema/types.go
Adds optional flag to disable initial host lookup when performing operations via the temporal-cassandra-tool. This is useful for some configurations of Cassandra where not having this flag enabled can significantly increase connection time or cause other issues. Validated that this worked against a test cluster.
Note that the server configuration also exposes this option, so we are just achieving parity between the server configuration and the tool configuration
> Adds flag to temporal-cassandra-tool to disable Initial Host Lookup

- common/rpc/encryption/localStoreTlsProvider.go
Use `useTLS` in the GetFrontendClientConfig's callback instead of `Frontend.Server.RequireClientAuth`
**Why?**
https://community.temporal.io/t/temporal-service-1-14-4-upgraded-frontend-worker-pods-are-crashing/3882/17
Unit tests
Should be low
Yes
> Pass useTLS in GetFrontendClientConfig's callback

- service/history/workflow/context.go
- service/history/workflow/context_mock.go
Add SetWorkflowExecution to workflow context
**Why?**
Expose the API for admin tool to set workflow if incorrect mutable state
> Add SetWorkflowExecution to workflow context

- docker/base-images/base-admin-tools.Dockerfile
- docker/base-images/base-server.Dockerfile
Mirror of a commit
https://github.com/temporalio/docker-builds/pull/31
**Why?**
Resolve CVE, prevent future for same target tool
Same as mirrored PR
Users shouldn't depend on vim being available in the containers
Maybe?
> removing vim from docker images due to CVE

- service/frontend/workflowHandler.go
- service/history/workflow/mutable_state_impl.go
- Check task queue length in RespondWorkflowTaskCompletedRequest before sending the request to history
- Check if child workflow info exists in ReplicateChildWorkflowExecutionStartedEvent to avoid NPE issue.
**Why?**
- misc improvements.
N/A
No.
> Misc. improvements for error checking

- common/metrics/defs.go
- common/metrics/tags.go
- common/metrics/temporal_queues.go
- service/history/historyEngine.go
- service/history/workflowTaskHandlerCallbacks.go
- service/matching/matchingEngine_test.go
- service/matching/taskQueueManager.go
- service/matching/taskReader.go
- Emit estimated matching task lag metric
- Add task queue type tag for metrics emitted by matching task queue manager as activity and workflow task queue can have the same name.
**Why?**
- Estimate task lag.
Dashboard may need to be updated to use the new tag.
no
> Emit estimated matching task lag metric

- docker/base-images/base-ci-builder.Dockerfile
This reverts commit 9cb3f5a61da2d2aba2d6ade22054700411c77bbe.
After discussing with build pipeline owner, learned more idiomatic way to regenerate Mocks in CI
> Revert "Added mockgen to base-ci-builder Docker image (#2574)"

- service/worker/batcher/workflow.go
Use `ListWorkflow` instead of `ScanWorkflow` for batch operation.
**Why?**
`ScanWorkflow` holds Elasticsearch resource and become a concern of system stability.
Manually.
No risks.
No.
> Use ListWorkflow instead of ScanWorkflow for batch operation

- service/history/historyEngineInterfaces.go
- service/history/historyEngineInterfaces_mock.go
- service/history/timerQueueAckMgr.go
- service/history/timerQueueAckMgr_test.go
- service/history/timerQueueProcessorBase.go
* Limit timer look ahead from positive infinite to configed value
**Why?**
Existing tests
N/A
N/A
> Limit timer look ahead

- service/frontend/operator_handler.go
- service/frontend/operator_handler_test.go
Change operator service error codes if Search attributes are not found or already exist to NOT_FOUND and ALREADY_EXIST from INVALID_ARGUMENT, which will simplify the client-side handling of these failures.
> Change operator service error codes if Search attributes are not found or already exist

- service/history/historyEngine.go
- service/history/nDCTransactionMgr.go
Fix replication error handling
**Why?**
1. Drop replication task if the workflow is not found in source cluster.
2. Return no error if workflow cannot be reset in reapply case.
Local
Some no op tasks will be put into DLQ
Yes
> Fix replication error handling

- common/namespace/dlqMessageHandler.go
- common/namespace/dlqMessageHandler_test.go
- common/namespace/handler.go
- common/namespace/handler_GlobalNamespaceEnabled_MasterCluster_test.go
- common/namespace/handler_GlobalNamespaceEnabled_NotMasterCluster_test.go
- common/namespace/handler_test.go
- common/namespace/transmissionTaskHandler.go
- common/namespace/transmissionTaskHandler_test.go
- common/persistence/namespaceReplicationQueue.go
- common/persistence/namespaceReplicationQueue_mock.go
- common/persistence/persistence-tests/persistenceTestBase.go
- common/persistence/persistence-tests/queuePersistenceTest.go
- service/frontend/adminHandler.go
- service/worker/replicator/namespace_replication_message_processor.go
- Add context parameter to Namespace Replication Queue interface
- Passed in context is not used right now
- Wire up most logic in application layer to pass context parameter to persistence
- Some application logic still use context.TODO() as placeholder and will be replace later.
**Why?**
- Enforce persistence timeout, instead of always timeout after 10s
- Require for host level task worker pool
- Very low risk as passed in context not used
no
> Persistence Context Part 3: Namespace Replication Queue

- go.mod
- go.sum
- service/history/historyEngine_test.go
- service/history/workflowTaskHandler.go
- Update proto def
**Why?**
- https://github.com/temporalio/api/pull/162
- existing tests
- no, old proto field not released yet
- no
> Rename activity local dispatch request field

- service/worker/deletenamespace/activities.go
- service/worker/deletenamespace/reclaimresources/activities.go
- service/worker/deletenamespace/reclaimresources/workflow_test.go
Fix merge confict.
**Why?**
Last commit had merge confict and this fails build on master.
Local build.
No risks.
No.
> Fix merge confict

- service/worker/deletenamespace/activities.go
- service/worker/deletenamespace/deleteexecutions/workflow.go
- service/worker/deletenamespace/reclaimresources/workflow.go
- service/worker/deletenamespace/workflow.go
- service/worker/deletenamespace/workflow_test.go
Allow delete namespace by Id.
**Why?**
This was initial intent but for it was partially impemented in original PR.
No risks.
No.
> Allow delete namespace by Id

- service/history/nDCActivityReplicator.go
- service/history/nDCActivityReplicator_test.go
- service/history/nDCStandbyTaskUtil.go
- service/history/timerQueueProcessor.go
- service/history/timerQueueStandbyProcessor.go
- service/history/timerQueueStandbyTaskExecutor.go
- service/history/timerQueueStandbyTaskExecutor_test.go
- service/history/transferQueueStandbyTaskExecutor.go
- service/history/transferQueueTaskExecutorBase.go
Handle activity retry timer in passive
**Why?**
Case: activity is retrying in source cluster and then failover to target cluster. We should persist the retry timer and handle the timer correctly.
Unit tests
> Handle activity retry timer in passive

- common/namespace/handler.go
- common/persistence/cassandra/metadata_store.go
- common/persistence/client/fault_injection.go
- common/persistence/dataInterfaces.go
- common/persistence/metadata_manager.go
- common/persistence/mock/store_mock.go
- common/persistence/persistence-tests/metadataPersistenceV2Test.go
- common/persistence/persistenceInterface.go
- common/persistence/sql/metadata.go
- go.mod
- go.sum
Exclude deleted namespaces from `ListNamespace` response.
**Why?**
By default deleted namespaces (which exist in database during reclaim resources step) should not be returned by `ListNamespace` API.
New unit tests.
No risks.
No.
> Exclude deleted namespaces from ListNamespace response

- go.mod
- go.sum
- service/history/historyEngine_test.go
- service/history/transferQueueActiveTaskExecutor.go
- service/history/transferQueueActiveTaskExecutor_test.go
- service/history/workflow/history_builder.go
- service/history/workflow/history_builder_test.go
- service/history/workflow/mutable_state.go
- service/history/workflow/mutable_state_impl.go
- service/history/workflow/mutable_state_mock.go
- Record workflow cancellation RPC call reason in `WorkflowExecutionCancelRequestedEvent`
- Record workflow cancellation command reason in `RequestCancelExternalWorkflowExecutionInitiatedEvent`
- Use the reason in `RequestCancelExternalWorkflowExecutionInitiatedEvent` when cancelling external workflow
- Added tests
- API change: https://github.com/temporalio/api/pull/168
**Why?**
- https://github.com/temporalio/temporal/issues/2426
- Added unit tests
- Existing int test
no
> Add reason field for workflow cancellation

- common/persistence/cassandra/cluster_metadata_store.go
- common/persistence/cassandra/execution_store.go
- common/persistence/cassandra/history_store.go
- common/persistence/cassandra/matching_task_store.go
- common/persistence/cassandra/metadata_store.go
- common/persistence/cassandra/mutable_state_store.go
- common/persistence/cassandra/mutable_state_task_store.go
- common/persistence/cassandra/queue_store.go
- common/persistence/cassandra/shard_store.go
- common/persistence/client/fault_injection.go
- common/persistence/clusterMetadataStore.go
- common/persistence/execution_manager.go
- common/persistence/history_manager.go
- common/persistence/metadata_manager.go
- common/persistence/mock/store_mock.go
- common/persistence/namespaceReplicationQueue.go
- common/persistence/persistenceInterface.go
- common/persistence/persistenceMetricClients.go
- common/persistence/persistenceRateLimitedClients.go
- common/persistence/shard_manager.go
- common/persistence/sql/cluster_metadata.go
- common/persistence/sql/execution.go
- common/persistence/sql/execution_tasks.go
- common/persistence/sql/history_store.go
- common/persistence/sql/metadata.go
- common/persistence/sql/queue.go
- common/persistence/sql/shard.go
- common/persistence/sql/task.go
- common/persistence/task_manager.go
- Add context parameter to persistence store interfaces.
- NOTE: there's no behavior change in this PR. SQL and Cassandra store implementation still ignores the context passed it. Those will be changed in a follow up PR.
**Why?**
- Enforce persistence timeout, instead of always timeout after 10s
-  Very low, context is currently ignored by persistence store implementation
- No.
> Persistence context part 5: persistence store interfaces

- service/history/shard/context_impl.go
- Ensure minimal 1s context timeout for shard context APIs that may lead to shard movement.
**Why?**
- Context timeout errors in some shard context APIs will result in shard ownership lost and the processing for the entire shard will be blocked until the shard is re-acquired. Those context may from user calls or background task processing, and we don't have good control over what's the remaining time for making the shard context API call. To minimize the impact of this persistence context change, a minimal context timeout (1s) will be enforced on shard context methods that may lead to re-acquire shard.
- Prepare for the next set of changes for actually using persistence context timeout passed into persistence store implementation. …
> Ensure minimal context timeout for shard context APIs

- service/history/historyEngine.go
- service/history/nDCTransactionMgr.go
- service/history/shard/context.go
- service/history/shard/context_impl.go
- service/history/shard/context_mock.go
- service/history/transferQueueActiveTaskExecutor.go
- service/history/workflow/cache.go
- service/history/workflow/transaction_impl.go
- service/history/workflowRebuilder.go
* Unify error handling of CRUD operation of workflow within shard context
**Why?**
Better error handling
N/A
N/A
N/A
> Unify error handling of CRUD operation of workflow within shard context

- service/worker/deletenamespace/reclaimresources/workflow.go
- service/worker/deletenamespace/workflow.go
Move namespace cache delay to reclaim resources workflow.
**Why?**
Other namespace APIs don't want for cache to be updated and returns right away. To keep parity with them `DeleteNamespace` shouldn't wait for cache to be refreshed and return right away. This will also make API call almost instant and mitigate possible timeout errors on caller side.
No risks.
No.
> Move namespace cache delay to reclaim resources workflow

- service/history/transferQueueActiveTaskExecutor.go
- service/history/transferQueueActiveTaskExecutor_test.go
Fix parent close policy processor for deleted namespace.
**Why?**
Due to bug, `TerminateWorkflow` was still called even if namespace is deleted and not found in namespace registry.
New unit test.
No risks.
No.
> Fix parent close policy processor for deleted namespace

- common/namespace/registry.go
- common/namespace/registry_test.go
Store namespaces in `DELETED` state in registry.
**Why?**
Delete namespace workflow relies on namespace registry and it expects namespaces in `DELETED` state to be there.
Modified unit tests.
No risks.
No.
> Store namespaces in DELETED state in registry

- service/frontend/operator_handler.go
- service/frontend/operator_handler_test.go
Add `DeleteNamespace` API unit tests.
**Why?**
To improve code coverage.
N/A
No risks.
No.
> Add DeleteNamespace API unit tests

- common/persistence/visibility/store/elasticsearch/visibility_store.go
- common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
- common/persistence/visibility/store/elasticsearch/visibility_store_write_test.go
- common/persistence/visibility/store/standard/cassandra/visibility_store.go
- common/persistence/visibility/store/standard/sql/visibility_store.go
- common/persistence/visibility/store/standard/visibility_store.go
- common/persistence/visibility/store/visibility_store.go
- common/persistence/visibility/store/visibility_store_mock.go
- common/persistence/visibility/visibility_manager_impl.go
- common/persistence/visibility/visibility_manager_test.go
- Add context parameter to visibility store interfaces.
- NOTE: there's no behavior change in this PR. SQL, Cassandra and ElasticSearch store implementation still ignores the context passed it. Those will be changed in a follow up PR.
**Why?**
- Enforce persistence timeout, instead of always timeout after 10s
-  Very low, context is currently ignored by persistence store implementation
- No.
> Persistence context part 6: visibility store interfaces

- service/history/historyEngine.go
- service/history/workflowExecutionUtil.go
- service/history/workflowTaskHandlerCallbacks.go
- Only reload mutable state once if we detect possible stale mutable state when recording child workflow execution completed.
- This PR is a temp fix for avoiding the task infinite retry issue for 1.16 release. We should use child init event ID + version for verifying if the child actually exists or not.
**Why?**
- In xdc there's no guarantee that parent will have the child information and its next eventID will larger than the initiatedID in the RecordChildCompletedRequest after forced failover.
- Existing logic returns ErrStaleState, which will cause the handling logic keep loading mutable state and return and "maximum attempt exceeded" error for the record child completed API. Then task processing logic for CloseWorkflowExecution task will retry infinitely.
**How did …
> Fix record child workflow complete mutable state stale check

- service/frontend/operator_handler.go
- service/worker/deletenamespace/deleteexecutions/workflow.go
- service/worker/deletenamespace/reclaimresources/workflow.go
- service/worker/deletenamespace/workflow.go
Set `WorkflowID` for child workflows.
**Why?**
Using namespace name being deleted as part of `WorkflowID` helps to debug if several namespaces are deleted in parallel.
Manual run.
No risks.
No.
> Set WorkflowID for child workflows

- service/worker/deletenamespace/reclaimresources/activities.go
- service/worker/deletenamespace/reclaimresources/activities_test.go
- service/worker/deletenamespace/reclaimresources/workflow_test.go
Return `ErrExecutionsStillExist` if executions are still exist.
**Why?**
Due to bug `EnsureNoExecutionsActivity` always returned `nil` and activity wasn't retried when it should.
No risks.
No.
> Return ErrExecutionsStillExist if executions are still exist

- service/history/shard/context_impl.go
- Fix timer queue cluster ack level update
- Need to be part of 1.16
**Why?**
- Update the right field in shard info for backward compatibility
-  Tested/Verified locally
- No, won't cause big issue. Even if that field is not updated and we perform a rollback, since the underlying tasks in DB is already deleted, we don't re-processing them, and ack level will fix itself on next update.
- no, not released yet
> Fix timer queue cluster ack level update

- client/history/client.go
- Fix history client NPE for invalid shardID
**Why?**
- Current if shardID is 0, `client` will not be initialized but still be used to make the rpc call, result in an NPE error.
-  Tested locally
> Fix history client NPE for invalid shardID

- common/searchattribute/encode.go
- common/searchattribute/encode_value.go
- common/searchattribute/encode_value_test.go
Use type from type map before type from Metadata.
**Why?**
Before if wrong type was passed in metadata together with value of that type, it passes validation but fails on write to Elasticsearch. Closes #2693.
Modified unit tests.
No risks.
No.
> Use type from type map before type from Metadata

- host/xdc/integration_failover_test.go
- service/history/workflow/mutable_state_impl.go
Pretend namespace is still local after it is promoted if there is inflight workflow task.
**Why?**
So event will be buffered as local event while there is inflight workflow task
New integration test. Without this fix, the new case would fail on error "event version must be the same inside a batch"
> buffer event as local namespace after promotion
